declare namespace Form.defraimp_importnotification.Main {
  namespace Information {
    namespace Tabs {
      interface _0e9815cb6818432982dc8a11e303b3aa extends Xrm.SectionCollectionBase {
        get(name: "Hidden"): Xrm.PageSection;
        get(name: "{0e9815cb-6818-4329-82dc-8a11e303b3aa}_section_2"): Xrm.PageSection;
        get(name: "{0e9815cb-6818-4329-82dc-8a11e303b3aa}_section_3"): Xrm.PageSection;
        get(name: "{0e9815cb-6818-4329-82dc-8a11e303b3aa}_section_4"): Xrm.PageSection;
        get(name: "{0e9815cb-6818-4329-82dc-8a11e303b3aa}_section_5"): Xrm.PageSection;
        get(name: "{0e9815cb-6818-4329-82dc-8a11e303b3aa}_section_6"): Xrm.PageSection;
        get(name: "{0e9815cb-6818-4329-82dc-8a11e303b3aa}_section_7"): Xrm.PageSection;
        get(name: "{0e9815cb-6818-4329-82dc-8a11e303b3aa}_section_8"): Xrm.PageSection;
        get(name: "{37007aea-252a-45ea-9205-3dbaa90c1cee}"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
    }
    interface Attributes extends Xrm.AttributeCollectionBase {
      get(name: "defraimp_charityaddresscity"): Xrm.Attribute<string>;
      get(name: "defraimp_charityaddresscountry"): Xrm.LookupAttribute<"defra_country">;
      get(name: "defraimp_charityaddressline1"): Xrm.Attribute<string>;
      get(name: "defraimp_charityaddressline2"): Xrm.Attribute<string>;
      get(name: "defraimp_charityaddressline3"): Xrm.Attribute<string>;
      get(name: "defraimp_charityaddresspostcode"): Xrm.Attribute<string>;
      get(name: "defraimp_charityemail"): Xrm.Attribute<string>;
      get(name: "defraimp_charityname"): Xrm.Attribute<string>;
      get(name: "defraimp_charitytelephone"): Xrm.Attribute<string>;
      get(name: "defraimp_commoditytypeid"): Xrm.LookupAttribute<"defraexp_commoditytype">;
      get(name: "defraimp_countryoforiginid"): Xrm.LookupAttribute<"defra_country">;
      get(name: "defraimp_datenotificationreceived"): Xrm.DateAttribute;
      get(name: "defraimp_dateofimport"): Xrm.DateAttribute;
      get(name: "defraimp_importeraddresscity"): Xrm.Attribute<string>;
      get(name: "defraimp_importeraddresscountryid"): Xrm.LookupAttribute<"defra_country">;
      get(name: "defraimp_importeraddressline1"): Xrm.Attribute<string>;
      get(name: "defraimp_importeraddressline2"): Xrm.Attribute<string>;
      get(name: "defraimp_importeraddressline3"): Xrm.Attribute<string>;
      get(name: "defraimp_importeraddresspostcode"): Xrm.Attribute<string>;
      get(name: "defraimp_importeremail"): Xrm.Attribute<string>;
      get(name: "defraimp_importername"): Xrm.Attribute<string>;
      get(name: "defraimp_importertelephone"): Xrm.Attribute<string>;
      get(name: "defraimp_ins"): Xrm.Attribute<string>;
      get(name: "defraimp_name"): Xrm.Attribute<string>;
      get(name: "defraimp_notificationreceivedintimeframe"): Xrm.OptionSetAttribute<boolean>;
      get(name: "defraimp_originaddress"): Xrm.Attribute<string>;
      get(name: "defraimp_permanentdestinationaddresscity"): Xrm.Attribute<string>;
      get(name: "defraimp_permanentdestinationaddresscountryid"): Xrm.LookupAttribute<"defra_country">;
      get(name: "defraimp_permanentdestinationaddressline1"): Xrm.Attribute<string>;
      get(name: "defraimp_permanentdestinationaddressline2"): Xrm.Attribute<string>;
      get(name: "defraimp_permanentdestinationaddressline3"): Xrm.Attribute<string>;
      get(name: "defraimp_permanentdestinationaddresspostcode"): Xrm.Attribute<string>;
      get(name: "defraimp_permanentdestinationcontactname"): Xrm.Attribute<string>;
      get(name: "defraimp_permanentdestinationemail"): Xrm.Attribute<string>;
      get(name: "defraimp_permanentdestinationtelephone"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationaddresscity"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationaddresscountryid"): Xrm.LookupAttribute<"defra_country">;
      get(name: "defraimp_placeofdestinationaddressline1"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationaddressline2"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationaddressline3"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationaddresspostcode"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationcontactname"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationemail"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationtelephone"): Xrm.Attribute<string>;
      get(name: "defraimp_pointofentry"): Xrm.Attribute<string>;
      get(name: "defraimp_referencenumber"): Xrm.Attribute<string>;
      get(name: "defraimp_speciesproductname"): Xrm.Attribute<string>;
      get(name: "defraimp_transporteraddress"): Xrm.Attribute<string>;
      get(name: "defraimp_transporteremail"): Xrm.Attribute<string>;
      get(name: "defraimp_transportername"): Xrm.Attribute<string>;
      get(name: "defraimp_transportertelephone"): Xrm.Attribute<string>;
      get(name: "ownerid"): Xrm.LookupAttribute<"systemuser" | "team">;
      get(name: "statuscode"): Xrm.OptionSetAttribute<defraimp_importnotification_statuscode>;
      get(name: string): undefined;
      get(): Xrm.Attribute<any>[];
      get(index: number): Xrm.Attribute<any>;
      get(chooser: (item: Xrm.Attribute<any>, index: number) => boolean): Xrm.Attribute<any>[];
    }
    interface Controls extends Xrm.ControlCollectionBase {
      get(name: "defraimp_charityaddresscity"): Xrm.StringControl;
      get(name: "defraimp_charityaddresscountry"): Xrm.LookupControl<"defra_country">;
      get(name: "defraimp_charityaddressline1"): Xrm.StringControl;
      get(name: "defraimp_charityaddressline2"): Xrm.StringControl;
      get(name: "defraimp_charityaddressline3"): Xrm.StringControl;
      get(name: "defraimp_charityaddresspostcode"): Xrm.StringControl;
      get(name: "defraimp_charityemail"): Xrm.StringControl;
      get(name: "defraimp_charityname"): Xrm.StringControl;
      get(name: "defraimp_charitytelephone"): Xrm.StringControl;
      get(name: "defraimp_commoditytypeid"): Xrm.LookupControl<"defraexp_commoditytype">;
      get(name: "defraimp_countryoforiginid"): Xrm.LookupControl<"defra_country">;
      get(name: "defraimp_datenotificationreceived"): Xrm.DateControl;
      get(name: "defraimp_dateofimport"): Xrm.DateControl;
      get(name: "defraimp_importeraddresscity"): Xrm.StringControl;
      get(name: "defraimp_importeraddresscountryid"): Xrm.LookupControl<"defra_country">;
      get(name: "defraimp_importeraddressline1"): Xrm.StringControl;
      get(name: "defraimp_importeraddressline2"): Xrm.StringControl;
      get(name: "defraimp_importeraddressline3"): Xrm.StringControl;
      get(name: "defraimp_importeraddresspostcode"): Xrm.StringControl;
      get(name: "defraimp_importeremail"): Xrm.StringControl;
      get(name: "defraimp_importername"): Xrm.StringControl;
      get(name: "defraimp_importertelephone"): Xrm.StringControl;
      get(name: "defraimp_ins"): Xrm.StringControl;
      get(name: "defraimp_name"): Xrm.StringControl;
      get(name: "defraimp_notificationreceivedintimeframe"): Xrm.OptionSetControl<boolean>;
      get(name: "defraimp_originaddress"): Xrm.StringControl;
      get(name: "defraimp_permanentdestinationaddresscity"): Xrm.StringControl;
      get(name: "defraimp_permanentdestinationaddresscountryid"): Xrm.LookupControl<"defra_country">;
      get(name: "defraimp_permanentdestinationaddressline1"): Xrm.StringControl;
      get(name: "defraimp_permanentdestinationaddressline2"): Xrm.StringControl;
      get(name: "defraimp_permanentdestinationaddressline3"): Xrm.StringControl;
      get(name: "defraimp_permanentdestinationaddresspostcode"): Xrm.StringControl;
      get(name: "defraimp_permanentdestinationcontactname"): Xrm.StringControl;
      get(name: "defraimp_permanentdestinationemail"): Xrm.StringControl;
      get(name: "defraimp_permanentdestinationtelephone"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationaddresscity"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationaddresscountryid"): Xrm.LookupControl<"defra_country">;
      get(name: "defraimp_placeofdestinationaddressline1"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationaddressline2"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationaddressline3"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationaddresspostcode"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationcontactname"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationemail"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationtelephone"): Xrm.StringControl;
      get(name: "defraimp_pointofentry"): Xrm.StringControl;
      get(name: "defraimp_referencenumber"): Xrm.StringControl;
      get(name: "defraimp_speciesproductname"): Xrm.StringControl;
      get(name: "defraimp_transporteraddress"): Xrm.StringControl;
      get(name: "defraimp_transporteremail"): Xrm.StringControl;
      get(name: "defraimp_transportername"): Xrm.StringControl;
      get(name: "defraimp_transportertelephone"): Xrm.StringControl;
      get(name: "header_ownerid"): Xrm.LookupControl<"systemuser" | "team">;
      get(name: "header_statuscode"): Xrm.OptionSetControl<defraimp_importnotification_statuscode>;
      get(name: string): undefined;
      get(): Xrm.BaseControl[];
      get(index: number): Xrm.BaseControl;
      get(chooser: (item: Xrm.BaseControl, index: number) => boolean): Xrm.BaseControl[];
    }
    interface Tabs extends Xrm.TabCollectionBase {
      get(name: "{0e9815cb-6818-4329-82dc-8a11e303b3aa}"): Xrm.PageTab<Tabs._0e9815cb6818432982dc8a11e303b3aa>;
      get(name: string): undefined;
      get(): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
      get(index: number): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>;
      get(chooser: (item: Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>, index: number) => boolean): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
    }
  }
  interface Information extends Xrm.PageBase<Information.Attributes,Information.Tabs,Information.Controls> {
    getAttribute(attributeName: "defraimp_charityaddresscity"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_charityaddresscountry"): Xrm.LookupAttribute<"defra_country">;
    getAttribute(attributeName: "defraimp_charityaddressline1"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_charityaddressline2"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_charityaddressline3"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_charityaddresspostcode"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_charityemail"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_charityname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_charitytelephone"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_commoditytypeid"): Xrm.LookupAttribute<"defraexp_commoditytype">;
    getAttribute(attributeName: "defraimp_countryoforiginid"): Xrm.LookupAttribute<"defra_country">;
    getAttribute(attributeName: "defraimp_datenotificationreceived"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_dateofimport"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_importeraddresscity"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_importeraddresscountryid"): Xrm.LookupAttribute<"defra_country">;
    getAttribute(attributeName: "defraimp_importeraddressline1"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_importeraddressline2"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_importeraddressline3"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_importeraddresspostcode"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_importeremail"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_importername"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_importertelephone"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_ins"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_name"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_notificationreceivedintimeframe"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "defraimp_originaddress"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_permanentdestinationaddresscity"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_permanentdestinationaddresscountryid"): Xrm.LookupAttribute<"defra_country">;
    getAttribute(attributeName: "defraimp_permanentdestinationaddressline1"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_permanentdestinationaddressline2"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_permanentdestinationaddressline3"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_permanentdestinationaddresspostcode"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_permanentdestinationcontactname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_permanentdestinationemail"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_permanentdestinationtelephone"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationaddresscity"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationaddresscountryid"): Xrm.LookupAttribute<"defra_country">;
    getAttribute(attributeName: "defraimp_placeofdestinationaddressline1"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationaddressline2"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationaddressline3"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationaddresspostcode"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationcontactname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationemail"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationtelephone"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_pointofentry"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_referencenumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_speciesproductname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_transporteraddress"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_transporteremail"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_transportername"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_transportertelephone"): Xrm.Attribute<string>;
    getAttribute(attributeName: "ownerid"): Xrm.LookupAttribute<"systemuser" | "team">;
    getAttribute(attributeName: "statuscode"): Xrm.OptionSetAttribute<defraimp_importnotification_statuscode>;
    getAttribute(attributeName: string): undefined;
    getControl(controlName: "defraimp_charityaddresscity"): Xrm.StringControl;
    getControl(controlName: "defraimp_charityaddresscountry"): Xrm.LookupControl<"defra_country">;
    getControl(controlName: "defraimp_charityaddressline1"): Xrm.StringControl;
    getControl(controlName: "defraimp_charityaddressline2"): Xrm.StringControl;
    getControl(controlName: "defraimp_charityaddressline3"): Xrm.StringControl;
    getControl(controlName: "defraimp_charityaddresspostcode"): Xrm.StringControl;
    getControl(controlName: "defraimp_charityemail"): Xrm.StringControl;
    getControl(controlName: "defraimp_charityname"): Xrm.StringControl;
    getControl(controlName: "defraimp_charitytelephone"): Xrm.StringControl;
    getControl(controlName: "defraimp_commoditytypeid"): Xrm.LookupControl<"defraexp_commoditytype">;
    getControl(controlName: "defraimp_countryoforiginid"): Xrm.LookupControl<"defra_country">;
    getControl(controlName: "defraimp_datenotificationreceived"): Xrm.DateControl;
    getControl(controlName: "defraimp_dateofimport"): Xrm.DateControl;
    getControl(controlName: "defraimp_importeraddresscity"): Xrm.StringControl;
    getControl(controlName: "defraimp_importeraddresscountryid"): Xrm.LookupControl<"defra_country">;
    getControl(controlName: "defraimp_importeraddressline1"): Xrm.StringControl;
    getControl(controlName: "defraimp_importeraddressline2"): Xrm.StringControl;
    getControl(controlName: "defraimp_importeraddressline3"): Xrm.StringControl;
    getControl(controlName: "defraimp_importeraddresspostcode"): Xrm.StringControl;
    getControl(controlName: "defraimp_importeremail"): Xrm.StringControl;
    getControl(controlName: "defraimp_importername"): Xrm.StringControl;
    getControl(controlName: "defraimp_importertelephone"): Xrm.StringControl;
    getControl(controlName: "defraimp_ins"): Xrm.StringControl;
    getControl(controlName: "defraimp_name"): Xrm.StringControl;
    getControl(controlName: "defraimp_notificationreceivedintimeframe"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "defraimp_originaddress"): Xrm.StringControl;
    getControl(controlName: "defraimp_permanentdestinationaddresscity"): Xrm.StringControl;
    getControl(controlName: "defraimp_permanentdestinationaddresscountryid"): Xrm.LookupControl<"defra_country">;
    getControl(controlName: "defraimp_permanentdestinationaddressline1"): Xrm.StringControl;
    getControl(controlName: "defraimp_permanentdestinationaddressline2"): Xrm.StringControl;
    getControl(controlName: "defraimp_permanentdestinationaddressline3"): Xrm.StringControl;
    getControl(controlName: "defraimp_permanentdestinationaddresspostcode"): Xrm.StringControl;
    getControl(controlName: "defraimp_permanentdestinationcontactname"): Xrm.StringControl;
    getControl(controlName: "defraimp_permanentdestinationemail"): Xrm.StringControl;
    getControl(controlName: "defraimp_permanentdestinationtelephone"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationaddresscity"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationaddresscountryid"): Xrm.LookupControl<"defra_country">;
    getControl(controlName: "defraimp_placeofdestinationaddressline1"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationaddressline2"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationaddressline3"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationaddresspostcode"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationcontactname"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationemail"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationtelephone"): Xrm.StringControl;
    getControl(controlName: "defraimp_pointofentry"): Xrm.StringControl;
    getControl(controlName: "defraimp_referencenumber"): Xrm.StringControl;
    getControl(controlName: "defraimp_speciesproductname"): Xrm.StringControl;
    getControl(controlName: "defraimp_transporteraddress"): Xrm.StringControl;
    getControl(controlName: "defraimp_transporteremail"): Xrm.StringControl;
    getControl(controlName: "defraimp_transportername"): Xrm.StringControl;
    getControl(controlName: "defraimp_transportertelephone"): Xrm.StringControl;
    getControl(controlName: "header_ownerid"): Xrm.LookupControl<"systemuser" | "team">;
    getControl(controlName: "header_statuscode"): Xrm.OptionSetControl<defraimp_importnotification_statuscode>;
    getControl(controlName: string): undefined;
  }
}
