#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	/// <summary>
	/// Type of activity.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum activitypointer_activitytypecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fax = 4204,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PhoneCall = 4210,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Email = 4202,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Letter = 4207,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Appointment = 4201,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Task = 4212,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RecurringAppointment = 4251,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QuickCampaign = 4406,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CampaignActivity = 4402,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CampaignResponse = 4401,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CaseResolution = 4206,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ServiceActivity = 4214,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OpportunityClose = 4208,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OrderClose = 4209,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QuoteClose = 4211,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FormsProsurveyinvite = 10054,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FormsProsurveyresponse = 10055,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomerVoicealert = 10200,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ActivityrecordfortheTeamschat = 10550,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Conversation = 10769,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Session = 10786,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CopilotTranscript = 11057,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InviteRedemption = 11112,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PortalComment = 11113,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Voicemail = 11868,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Outboundmessage = 11895,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ImportQuery = 11914,
	}
}
#pragma warning restore CS1591
