#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum defraimp_reasonforunsatisfactoryvisit
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NonCompliantwelfare = 714100000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NonCompliantdocumentarycheck = 714100001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Quarantined = 714100002,
	}
}
#pragma warning restore CS1591
