#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum defraimp_animalcertifiedas
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Breeding = 714100000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fattening = 714100001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Slaughter = 714100002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Transhumance = 714100003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ApprovedBodies = 714100004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RegisteredHorses = 714100005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Storage = 714100006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pets = 714100007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Other = 714100008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ArtificialReproduction = 714100009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HumaneConsumption = 714100010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TechnicalUse = 714100011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AnimalFeedingstuff = 714100012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PharmaceuticalUse = 714100013,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Circus = 714100014,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Relaying = 714100015,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Approved = 714100016,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Quarantine = 714100017,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Registered = 714100018,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Commercialsale = 714100019,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Gamerestocking = 714100020,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Production = 714100021,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RacingCompetition = 714100022,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RescueRehoming = 714100023,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Research = 714100024,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ZooCollection = 714100025,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RejectedorReturnedConsignment = 714100026,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Transit = 714100027,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ForInternalMarket = 714100028,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ForTranshipment = 714100029,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ForReentry = 714100030,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PersonallyOwnedPetsNotforRehoming = 714100031,
	}
}
#pragma warning restore CS1591
