#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum defraimp_purposeofconsignment
	{
		
		/// <summary>
		/// Previous label : For Import
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InternalMarket = 714100000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ReEntry = 714100009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Temporaryadmissionhorses = 714100008,
		
		/// <summary>
		/// Previous label : For Transhipment to
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Transhipmentoronwardtravel = 714100001,
		
		/// <summary>
		/// previous label : For Transit to 3rd Country
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Transit = 714100002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ForReImport = 714100003,
	}
}
#pragma warning restore CS1591
