#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum defraimp_importernotificationtype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CHEDA = 714100004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CVEDA = 714100000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CVEDP = 714100001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GBNAG = 714100005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IMP = 714100003,
	}
}
#pragma warning restore CS1591
