#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	/// <summary>
	/// List of Mobile Offline Enabled Entities.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum mobileofflineenabledentities
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Account = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Contact = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		User = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Team = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Queue = 2020,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QueueItem = 2029,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SLAKPIInstance = 9752,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AccountLeads = 16,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ContactLeads = 22,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Lead = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Product = 1024,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PriceList = 1022,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PriceListItem = 1026,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProductRelationship = 1028,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unit = 1055,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnitGroup = 1056,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Entitlement = 9700,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntitlementContact = 7272,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntitlementProduct = 6363,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntitlementTemplateProduct = 4545,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Case = 112,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IncidentKnowledgeBaseRecord = 9931,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PhoneToCaseProcess = 952,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CompetitorAddress = 1004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CompetitorProduct = 1006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LeadCompetitors = 24,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LeadProduct = 27,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LeadToOpportunitySalesProcess = 954,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Opportunity = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OpportunityCompetitors = 25,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OpportunityProduct = 1083,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OpportunitySalesProcess = 953,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Competitor = 123,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Currency = 9105,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Property = 1048,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PropertyAssociation = 1235,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PropertyOptionSetItem = 1049,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PropertyInstance = 1333,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Invoice = 1090,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvoiceProduct = 1091,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QuoteProduct = 1085,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OrderProduct = 1089,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ImportApplicationBusinessProcessFlow = 10083,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Quote = 1084,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Order = 1088,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTAlerttoCaseProcess = 10148,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MatchRecordBusinessProcessFlow = 10154,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTSettings = 10143,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Connection = 3234,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConnectionRole = 3231,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTDevice = 10133,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTDeviceCategory = 10134,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTDeviceCommandDefinition = 10136,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTDeviceDataHistory = 10137,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTDeviceProperty = 10138,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTDeviceRegistrationHistory = 10139,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTPropertyDefinition = 10140,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTProvider = 10141,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ImageDescriptor = 1007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTAlert = 10132,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeArticleImage = 10006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTDeviceCommand = 10135,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Copilotknowledgeinteraction = 11327,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IoTProviderInstance = 10142,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_historicalcaseharvestbatch = 11330,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ActivityFileAttachment = 10309,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeArticleAttachment = 10376,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_historicalcaseharvestrun = 11331,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeHarvestJobRecord = 11332,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OrganizationDataSyncState = 10552,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProductMap = 11406,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OrganizationDataSyncFnoState = 10950,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityAttachment = 10974,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AccountResearchAgentTrigger = 11427,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AccountResearchResult = 11428,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LeadAgentResult = 11429,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LeadDelinkResult = 11430,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OutreachAgentResult = 11432,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OutreachTriggerAgent = 11433,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QualificationAgentTrigger = 11434,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SalesAgentUsage = 11436,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DispositionCodeCategory = 11443,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		StakeholderResearchOutput = 11450,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PowerPagesDDOSAlert = 11455,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CompetitorResearchAgentTrigger = 11460,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TargetCustomerProfilePrefillAgentResult = 11461,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TargetCustomerProfilePrefillAgentTrigger = 11475,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity0c5f7794dc = 11476,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentitybaaa246365 = 11477,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity462a913406 = 11478,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity047fdea724 = 11479,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity9b6aa0edc0 = 11480,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity8f51bfdb04 = 11481,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity6ba7d2661d = 11482,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EvaluationGlobalConfig = 11494,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PAFlowRunTracker = 11502,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentityd685f8f3a1 = 11503,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentityed64436c98 = 11504,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity4d73ae36d9 = 11505,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity4969f8ce46 = 11506,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity06789891c6 = 11507,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity318e2a8f9f = 11508,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity755c571271 = 11509,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity955eb1d201 = 11510,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SummarySynthesizerAgentTrigger = 11512,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OpportunityRankerMapping = 11513,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OpportunityResearchIndicator = 11515,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OpportunityResearchUserInteractions = 11517,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RCSWatermark = 11518,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity540a4366de = 11522,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity064fb0dcea = 11523,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentityc28d4349ab = 11524,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentityd77a007cc1 = 11525,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity40609e0c5a = 11526,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity59387e110e = 11527,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentitydc3c903d4e = 11528,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Shorturl = 11533,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity02c2f9b560 = 11536,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentitydca475dbb3 = 11537,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity3465944e71 = 11538,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity672fcb7203 = 11539,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentitybb9e390b78 = 11540,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentityfd218d23b0 = 11541,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity47c0763b2e = 11542,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentityebf8fafc10 = 11543,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_globalrulesetconfiguration = 11544,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ChannelProfile = 11546,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_broadcastmessagebulkactionapiprivilege = 11549,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_bulkassigntoqueueapiprivilege = 11550,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_bulkforcecloseapiprivilege = 11551,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_notifyagentbulkactionapiprivilege = 11559,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CRMActivityMapping = 11575,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InterimUpdateKnowledgeArticle = 11579,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeArticleCustomEntity = 11610,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProactiveEngagementConfigurationStatus = 11618,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BotVariable = 11643,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AccountResearchSummaryTrigger = 11645,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomAccountInsightsResult = 11646,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomizationAgentTrigger = 11647,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomOOBResearchResult = 11648,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DefaultOOBAccountResearchResult = 11649,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SalesCompanyResolverLeadTrigger = 11650,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RelatedConversationTriggerTable = 11651,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EvaluationNotificationConfiguration = 11653,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OpportunityAccountResearchResult = 11676,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dataqualitylog = 11677,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dataqualitysource = 11679,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Dataqualitysuggestion = 11680,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DQARankerTrigger = 11681,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PowerAppsWrapBuild = 11689,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_aiconnectormapping = 11697,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CopilotOrganizationWorkload = 11712,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CopilotUserWorkload = 11713,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AlwaysRunSQASegment = 11715,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ScreenRecordingLink = 11718,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		BulkHarvestRunLog = 11719,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HarvestWorkItem = 11720,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_governanceagent_status = 11727,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_guardrail_consumer_mapping = 11728,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_guardrail_execution_info = 11729,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_guardrail_rule = 11730,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_guardrail_rule_version = 11731,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_guardrail_scenariotype = 11732,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OpportunityCompetitorResearchResultCache = 11743,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PrioritizedActionCatalogue = 11744,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		msdyn_recommendedactionsourceagentconfig = 11748,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Action = 11755,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Guardrail = 11756,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GuardrailVersion = 11757,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IndicatorQuestion = 11758,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Monitor = 11759,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MonitorAction = 11760,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MonitorNotificationConfig = 11761,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QINotificationConfig = 11762,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QINotificationConfigItem = 11763,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QualityIndicator = 11764,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QualityIndicatorVersion = 11765,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		contactprofilerdetail = 11768,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		contactprofilerresult = 11769,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Emailthread = 11773,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgentCoachAdminSettings = 11775,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgentCoachPlaybook = 11776,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgentCoachPlaybookInstructions = 11777,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AgentCoachPolicySettings = 11778,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AthenaReconciliationInfo = 11793,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		HistoricalCaseHarvestRunLog = 11800,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomNeuralVoice = 11834,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LocationRecord = 11847,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NativeExtension = 11848,
	}
}
#pragma warning restore CS1591
