#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_eventtypechoice
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Created = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Assigned = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AssessmentChanged = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FraudsterEnrolled = 192350003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FraudsterDeleted = 192350004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		FraudsterMoved = 192350005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WatchlistCreated = 192350006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WatchlistUpdated = 192350007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WatchlistDeleted = 192350008,
	}
}
#pragma warning restore CS1591
