#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	/// <summary>
	/// Pattern Type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_optimizepatterntype
	{
		
		/// <summary>
		/// Reserved base value that does not identify an analyzable pattern.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Base = 200000500,
		
		/// <summary>
		/// Cases closed without confirming the resolution with the customer.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ClosureWithoutConfirmation = 200000501,
		
		/// <summary>
		/// Cases resolved without evidence that the underlying issue was verified.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UnverifiedResolution = 200000502,
		
		/// <summary>
		/// Cases that have shown no meaningful progress for an extended period.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		StalledCases = 200000503,
		
		/// <summary>
		/// Cases transferred repeatedly between agents or queues before resolution.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		TransferFriction = 200000504,
		
		/// <summary>
		/// Cases that lack the context needed to work them efficiently.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MissingCaseContext = 200000505,
		
		/// <summary>
		/// Inconsistent handling quality that routine review does not surface.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UndetectedQualityVariance = 200000506,
		
		/// <summary>
		/// Recurring case topics that have no supporting knowledge article.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeCoverageGap = 200000507,
		
		/// <summary>
		/// Knowledge articles that no longer reflect current guidance.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OutdatedKnowledge = 200000508,
		
		/// <summary>
		/// Repetitive, low-variation case volume that is a candidate for automation.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RoutineDemand = 200000509,
		
		/// <summary>
		/// Outbound customer communications sent with visible content defects.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		UncheckedOutboundCommunication = 200000510,
		
		/// <summary>
		/// Work handled manually even though an automated path was available.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AutomationAvoidance = 200000511,
	}
}
#pragma warning restore CS1591
