#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	/// <summary>
	/// Stores the list of event types for system messages.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_ocsystemmessageeventtype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Agentjoinedconversation = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Consultaccepted = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Transfertoagentaccepted = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Consultstarted = 192350003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Consultrequestfailed = 192350004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Transfertoagentrequested = 192350005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Transfertoagentfailed = 192350006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Consultrejected = 192350007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Transfertoagentrejected = 192350008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Consultrequesttimedout = 192350009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Transfertoagenttimedout = 192350010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Transfertoqueuestarted = 192350011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Transfertoqueuefailed = 192350012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Agentdisconnectedfromconversation = 192350013,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Agentendedconversation = 192350014,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Sessionended = 192350015,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Consultsessionended = 192350016,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Agentassignedtoconversation = 192350017,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Agentcouldntbeassignedtoconversation = 192350018,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Customerendedconversation = 192350019,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Customerdisconnected = 192350020,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Customerspositioninqueue = 192350021,
		
		/// <summary>
		/// Agent's message couldn't be sent
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Agentsmessagecouldntbesent = 192350022,
		
		/// <summary>
		/// Customer's message couldn't be sent: Outside of operation hours
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomersmessagecouldntbesentOutsideofoperationhours = 192350023,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Customerisnextinline = 192350024,
		
		/// <summary>
		/// Message couldn't be delivered: Unsupported message type
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MessagecouldntbedeliveredUnsupportedmessagetype = 192350025,
		
		/// <summary>
		/// Voice call requested
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Voicecallrequested = 192350026,
		
		/// <summary>
		/// Voice call accepted
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Voicecallaccepted = 192350027,
		
		/// <summary>
		/// Voice call declined
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Voicecalldeclined = 192350028,
		
		/// <summary>
		/// Message couldn't be sent: Outside allowed timeframe
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MessagecouldntbesentOutsideallowedtimeframe = 192350029,
		
		/// <summary>
		/// Average wait time for customers: Minutes
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AveragewaittimeforcustomersMinutes = 192350030,
		
		/// <summary>
		/// Average wait time for customers: Hours
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AveragewaittimeforcustomersHours = 192350031,
		
		/// <summary>
		/// Average wait time for customers: Hours and minutes
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AveragewaittimeforcustomersHoursandminutes = 192350032,
		
		/// <summary>
		/// Voice call ended
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Voicecallended = 192350033,
		
		/// <summary>
		/// Message couldn’t be sent: A channel account can’t message another account within Omnichannel
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MessagecouldntbesentAchannelaccountcantmessageanotheraccountwithinOmnichannel = 192350034,
		
		/// <summary>
		/// Holiday message to customer
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Holidaymessagetocustomer = 192350035,
		
		/// <summary>
		/// Out of operating hour message to customer
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Outofoperatinghourmessagetocustomer = 192350036,
		
		/// <summary>
		/// Couldn’t find the channel account in Omnichannel
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CouldntfindthechannelaccountinOmnichannel = 192350037,
		
		/// <summary>
		/// Customer's file couldn't be attached because it's too big
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Customersfilecouldntbeattachedbecauseitstoobig = 192350038,
		
		/// <summary>
		/// Transfer to out of operating hour queue
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Transfertooutofoperatinghourqueue = 192350039,
		
		/// <summary>
		/// Message couldn’t be sent: File couldn’t be attached
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MessagecouldntbesentFilecouldntbeattached = 192350040,
		
		/// <summary>
		/// Leave as many messages as you’d like and we’ll get back to you as soon as possible. We’ll save your chat history, so you can leave and come back anytime.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		LeaveasmanymessagesasyoudlikeandwellgetbacktoyouassoonaspossibleWellsaveyourchathistorysoyoucanleaveandcomebackanytime = 192350041,
		
		/// <summary>
		/// Customer put on hold.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Customerputonhold = 192350042,
		
		/// <summary>
		/// Customer no longer on hold.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Customernolongeronhold = 192350043,
		
		/// <summary>
		/// Message or attachment failed to send. Providing error details including error code, reason for failure, message id, timestamp, and transaction id
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MessageorattachmentfailedtosendProvidingerrordetailsincludingerrorcodereasonforfailuremessageidtimestampandtransactionid = 192350044,
		
		/// <summary>
		/// Transcription started.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Transcriptionstarted = 192350045,
		
		/// <summary>
		/// Transcription paused.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Transcriptionpaused = 192350046,
		
		/// <summary>
		/// Transcription resumed.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Transcriptionresumed = 192350047,
		
		/// <summary>
		/// Transcription stopped.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Transcriptionstopped = 192350048,
		
		/// <summary>
		/// Recording and transcription started.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Recordingandtranscriptionstarted = 192350049,
		
		/// <summary>
		/// Recording and transcription paused.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Recordingandtranscriptionpaused = 192350050,
		
		/// <summary>
		/// Recording and transcription resumed.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Recordingandtranscriptionresumed = 192350051,
		
		/// <summary>
		/// Recording and transcription stopped.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Recordingandtranscriptionstopped = 192350052,
		
		/// <summary>
		/// Usage limit for trial exceeded limits
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Trialusagelimitexceeded = 192350053,
		
		/// <summary>
		/// Time limit for a trial conversation exceeded
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Trialconversationtimelimitexceeded = 192350054,
		
		/// <summary>
		/// Ending the conversation when queue overflow condition met
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Endconversationduetooverflow = 192350055,
		
		/// <summary>
		/// Greeting Message for Async Channels and Voice
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GreetingMessageforAsyncChannelsandVoice = 192350056,
		
		/// <summary>
		/// Customer has opted out from Async Conversation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomerhasoptedoutfromAsyncConversation = 192350057,
		
		/// <summary>
		/// Agent left consult conversation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Agentleftconsultconversation = 192350058,
		
		/// <summary>
		/// Agent left customer conversation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Agentleftcustomerconversation = 192350059,
		
		/// <summary>
		/// Agent accepted consult conversation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Agentacceptedconsultconversation = 192350060,
		
		/// <summary>
		/// Agent joined customer conversation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Agentjoinedcustomerconversation = 192350061,
		
		/// <summary>
		/// Agent ended consult conversation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Agentendedconsultconversation = 192350062,
		
		/// <summary>
		/// Agent removed from consult conversation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Agentremovedfromconsultconversation = 192350063,
		
		/// <summary>
		/// Message displayed to customer when there is not enough data to show the average wait time when the feature has been enabled
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Notenoughdataforaveragewaittime = 192350064,
		
		/// <summary>
		/// Message displayed to agent when customer is disconnected from conversation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Waitingtimeforagentwhencustomerisdisconnected = 192350070,
		
		/// <summary>
		/// Invalid Apple OAuth response
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InvalidAppleOAuthresponse = 192350071,
		
		/// <summary>
		/// Supervisor force closed the conversation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Supervisorforceclosedtheconversation = 192350072,
		
		/// <summary>
		/// Offer customer callback
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Offercustomercallback = 192350073,
		
		/// <summary>
		/// Customer callback response
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Customercallbackresponse = 192350074,
		
		/// <summary>
		/// Consult with queue or user group is cancelled
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Consultwithqueueorusergroupiscancelled = 192350076,
		
		/// <summary>
		/// No service representatives found for consult with queue or user group
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Noservicerepresentativesfoundforconsultwithqueueorusergroup = 192350077,
		
		/// <summary>
		/// Consult request failed due to system failure
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Consultrequestfailedduetosystemfailure = 192350078,
		
		/// <summary>
		/// Consult to queue or user group failed due to out of operating hours
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Consulttoqueueorusergroupfailedduetooutofoperatinghours = 192350079,
		
		/// <summary>
		/// Customer's message couldn't be sent: Service is down.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomersmessagecouldntbesentServiceisdown = 192370001,
		
		/// <summary>
		/// Message to customer for Survey start.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pleasewaitamomenttogiveusfeedbackaboutyourexperience = 192370002,
		
		/// <summary>
		/// Message to customer for Survey timeout
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ThissurveyhastimedoutTostartanewconversationreopenthischatwindow = 192370003,
		
		/// <summary>
		/// Message to agent for conversation closed due to a new notification request.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Conversationclosedduetonewnotificationrequest = 192370006,
		
		/// <summary>
		/// Message to customer for estimated wait time notification.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Estimatedwaittimenotification = 192370007,
		
		/// <summary>
		/// Customer authenticated during active conversation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Customerauthenticatedduringactiveconversation = 192370009,
		
		/// <summary>
		/// Call Recording Notice
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CallRecordingNotice = 192370010,
		
		/// <summary>
		/// Message to agent for conversation closed due to SMS opt-out.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomerendedtheconversationduetoSMSoptout = 192370011,
		
		/// <summary>
		/// Message to be played back to the end customer when Voicemail is offered
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OfferVoicemail = 192360000,
		
		/// <summary>
		/// Message to be played back to the end customer when Voicemail recording is complete
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		VoicemailComplete = 192360001,
		
		/// <summary>
		/// Message to be played back to the end customer when Voicemail could not be recorded
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		VoicemailFail = 192360002,
		
		/// <summary>
		/// Message to be played back to the customer when direct agent is not available
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Directagentnotavailable = 192360003,
		
		/// <summary>
		/// Message for direct inward call forwarding
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DirectInwardCallForwarding = 192360005,
		
		/// <summary>
		/// Message for overflow external transfer initiated
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OverflowExternalTransferInitiated = 192360006,
		
		/// <summary>
		/// Message for Prompt and hang-up
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Promptandhangup = 192360007,
		
		/// <summary>
		/// Message for Prompt and tranfer to external number
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Promptandtransfertoexternalnumber = 192360008,
		
		/// <summary>
		/// Message for Prompt and escalate
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Promptandescalate = 192360009,
		
		/// <summary>
		/// Message for Bot Language Changed Message
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MessageforBotLanguageChangedMessage = 192360010,
		
		/// <summary>
		/// Message for Unsupported Bot Language
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MessageforUnsupportedBotLanguage = 192360011,
		
		/// <summary>
		/// Message for Entered a confidential section of the conversation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Enteredaconfidentialsectionoftheconversation = 192360012,
		
		/// <summary>
		/// Message for Exited the confidential section of the conversation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Exitedtheconfidentialsectionoftheconversation = 192360013,
		
		/// <summary>
		/// Message for Consent Based Recording – Customer said Yes to Recording prompt
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConsentBasedRecordingCustomersaidYestoRecordingprompt = 192360014,
		
		/// <summary>
		/// Message for Consent Based Recording – Customer said No to Recording prompt
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConsentBasedRecordingCustomersaidNotoRecordingprompt = 192360015,
		
		/// <summary>
		/// Message for Consent Based Recording – Did not receive Event after {n} seconds
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConsentBasedRecordingDidnotreceiveEventafternseconds = 192360016,
		
		/// <summary>
		/// Message for Consent Based Recording – Bot not configured for consent recording
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConsentBasedRecordingBotnotconfiguredforconsentrecording = 192360017,
		
		/// <summary>
		/// Consult with queue or user group is initiated
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Consultwithqueueorusergroupisinitiated = 192360018,
		
		/// <summary>
		/// Consult request failed due to system failure.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Consultrequestfailedduetosystemfailure1 = 192360019,
		
		/// <summary>
		/// Consult to queue or user group failed due to out of operating hours
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Consulttoqueueorusergroupfailedduetooutofoperatinghours1 = 192360020,
		
		/// <summary>
		/// Consult with queue or user group is cancelled
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Consultwithqueueorusergroupiscancelled1 = 192360021,
		
		/// <summary>
		/// No service representatives found for consult with queue or user group
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Noservicerepresentativesfoundforconsultwithqueueorusergroup1 = 192360022,
		
		/// <summary>
		/// Message to be played when a voice conversation is added to the queue
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Openconversationaddedtoqueueforvoice = 192360025,
		
		/// <summary>
		/// You are already in queue to receive a callback when a customer service representative is available. You can choose to continue waiting on this call if needed or disconnect and receive the callback
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		YouarealreadyinqueuetoreceiveacallbackwhenacustomerservicerepresentativeisavailableYoucanchoosetocontinuewaitingonthiscallifneededordisconnectandreceivethecallback = 192350075,
		
		/// <summary>
		/// Agent on hold
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Agentonhold = 192370004,
		
		/// <summary>
		/// Agent is no longer on hold
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Agentisnolongeronhold = 192370005,
		
		/// <summary>
		/// Duplicate Callback
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DuplicateCallback = 192370008,
		
		/// <summary>
		/// Message to be played to the customer when the concurrent callback calls limit has been exceeded
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Callbackfailedconcurrentcallslimitexceeded = 192380001,
		
		/// <summary>
		/// Message to be played to the customer when the callback number is not entitled to call the destination
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Callbackfailednumberisnotentitledtocallthisdestination = 192380002,
		
		/// <summary>
		/// Message to be played to the customer when a callback fails due to an invalid dialed number
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Callbackfailedinvalidphonenumber = 192380003,
		
		/// <summary>
		/// Message to be played to the customer when a callback fails because the customer declined the call
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Callbackfailedcustomerdeclinedthecall = 192380004,
		
		/// <summary>
		/// Message to be played to the customer when a callback fails because the customer's number is busy
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Callbackfailedcustomernumberisbusy = 192380005,
		
		/// <summary>
		/// Message to be played to the customer when the concurrent outbound calls limit has been exceeded
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Outboundcallfailedconcurrentcallslimitexceeded = 192380006,
		
		/// <summary>
		/// Message to be played to the customer when the outbound number is not entitled to call the destination
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OutboundcallfailedOutboundnumberisnotentitledtocallthisdestination = 192380007,
		
		/// <summary>
		/// Message to be played to the customer when an outbound call fails due to an invalid dialed number
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Outboundcallfailedinvalidphonenumber = 192380008,
		
		/// <summary>
		/// Message to be played to the customer when an outbound call fails because the customer declined the call
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Outboundcallfailedcustomerdeclinedthecall = 192380009,
		
		/// <summary>
		/// Message to be played to the customer when an outbound call fails because the customer's number is busy
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Outboundcallfailedcustomernumberisbusy = 192380010,
		
		/// <summary>
		/// Message to be played to the customer when the destination number is temporarily unavailable
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OutboundcallfailedDestinationnumberistemporarilyunavailable = 192380011,
		
		/// <summary>
		/// Message to be played to the customer when the call could not be completed
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Callfailedcouldnotbecompleted = 192380012,
		
		/// <summary>
		/// Message to agent when conversation is rerouted
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Conversationrerouted = 192370012,
		
		/// <summary>
		/// Message to agent when conversation reroute succeeds
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Conversationreroutesucceeded = 192370013,
		
		/// <summary>
		/// Message to agent when conversation reroute fails
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Conversationreroutefailed = 192370014,
		
		/// <summary>
		/// Message to be played to the customer when callback scheduling fails
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Callbackschedulingfailed = 192380013,
		
		/// <summary>
		/// Message to offer the customer a callback with the option to provide an alternate number
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Offercallbackwithalternatenumber = 192380014,
	}
}
#pragma warning restore CS1591
