#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	/// <summary>
	/// Custom model type selection
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_occustommodel
	{
		
		/// <summary>
		/// OpenAI GPT Realtime model
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		gptrealtime = 192350000,
		
		/// <summary>
		/// OpenAI GPT Realtime Mini model
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		gptrealtimemini = 192350001,
	}
}
#pragma warning restore CS1591
