#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_streamsource
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntityRecords = 192350000,
		
		/// <summary>
		/// Connect with customers via Facebook channel option
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Facebook = 192330000,
		
		/// <summary>
		/// Connect with customers via Teams channel option
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MicrosoftTeams = 19241000,
		
		/// <summary>
		/// Connect with customers via voice call channel option
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Voicecall = 192440000,
	}
}
#pragma warning restore CS1591
