#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_profilekey
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AAA_Profile_00 = 192350009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AAA_Profile_01 = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AAA_Profile_02 = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AAA_Profile_03 = 192350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AAA_Profile_04 = 192350003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AAA_Profile_05 = 192350004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AAA_Profile_06 = 192350005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AAA_Profile_07 = 192350006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AAA_Profile_08 = 192350007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AAA_Profile_09 = 192350008,
	}
}
#pragma warning restore CS1591
