#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	/// <summary>
	/// Message format / channel discriminator for a catalog template: SMS, MMS, RCS, or WhatsApp.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_octemplateformat
	{
		
		/// <summary>
		/// Plain text SMS.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SMS = 100000000,
		
		/// <summary>
		/// Multimedia message (text plus media attachments).
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MMS = 100000001,
		
		/// <summary>
		/// Rich Communication Services message.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RCS = 100000002,
		
		/// <summary>
		/// WhatsApp template format.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		WhatsApp = 100000004,
	}
}
#pragma warning restore CS1591
