#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	/// <summary>
	/// Select who should be evaluated.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_evaluationparticipantscope
	{
		
		/// <summary>
		/// Evaluate the entire record — every participant.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Entirerecord = 192350000,
		
		/// <summary>
		/// Evaluate only the current conversation owner's turns.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Currentowner = 192350001,
		
		/// <summary>
		/// Evaluate only virtual-agent or bot turns.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		IVRBot = 192350002,
	}
}
#pragma warning restore CS1591
