#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	/// <summary>
	/// Prioritization principles used to rank and score recommended sales actions. An action may map to multiple principles; the primary principle reflects the most direct intended business outcome.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_recommendedactionagent_salesprioritizationprinciples
	{
		
		/// <summary>
		/// Actions that directly accelerate closing revenue or protect committed or late-stage revenue. Applies to later pipeline stages (Proposal, Negotiation, Close) to remove blockers preventing deal closure.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RevenueGeneration = 1,
		
		/// <summary>
		/// Actions that speed up deal progression through pipeline stages by removing friction, unblocking next steps, or restoring momentum to reduce sales cycle time.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DealVelocity = 2,
		
		/// <summary>
		/// Actions that create new qualified pipeline or increase the volume and quality of opportunities entering the funnel, including lead qualification, conversion, cross-sell, and upsell motions.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PipelineGeneration = 3,
		
		/// <summary>
		/// Actions that directly mitigate the risk of losing a deal or missing a revenue target by addressing competitive threats, stakeholder loss, inactivity, pricing objections, or slipped timelines.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RiskReduction = 4,
		
		/// <summary>
		/// Actions tied to customer engagement, satisfaction, relationship health, or sentiment signals that restore or improve buyer confidence and responsiveness.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomerSentiment = 5,
		
		/// <summary>
		/// Actions that improve the quality, completeness, or correctness of CRM data required for forecasting, pipeline management, and downstream execution. Usually lower priority unless tied to risk or deadlines.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DataHygiene = 6,
		
		/// <summary>
		/// Actions that close stakeholder gaps by identifying, engaging, or validating the right decision makers and influencers across buying roles and approval paths.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		StakeholderCoverage = 7,
	}
}
#pragma warning restore CS1591
