#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	/// <summary>
	/// Lifecycle status of an optimize work item.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_optimizeworkitemstatus
	{
		
		/// <summary>
		/// The work item is queued and available to be claimed.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pending = 200001000,
		
		/// <summary>
		/// The work item has been claimed by an executor and is being processed.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Claimed = 200001001,
		
		/// <summary>
		/// The work item completed and its result was recorded.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Done = 200001002,
		
		/// <summary>
		/// The work item exhausted its attempts without producing a valid result.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Failed = 200001003,
	}
}
#pragma warning restore CS1591
