#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	/// <summary>
	/// Environment-local health status of a scheduled segment.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_optimizeschedulestatus
	{
		
		/// <summary>
		/// The schedule is turned off and will not fire.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Disabled = 200000900,
		
		/// <summary>
		/// The schedule is enabled and will fire at its next due slot.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 200000901,
		
		/// <summary>
		/// The schedule was turned off automatically after repeated failures.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Autodisabled = 200000902,
		
		/// <summary>
		/// The schedule reached its end date or maximum occurrences and will not fire again.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Completed = 200000903,
	}
}
#pragma warning restore CS1591
