#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	/// <summary>
	/// Model Provider for custom model configuration
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_ocmodelprovider
	{
		
		/// <summary>
		/// Azure AI Foundry models
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Foundry = 192350000,
		
		/// <summary>
		/// External/third-party models
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		External = 192350001,
	}
}
#pragma warning restore CS1591
