#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	/// <summary>
	/// Lifecycle status of an optimize artifact chunk.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_optimizeartifactstatus
	{
		
		/// <summary>
		/// The artifact row is reserved but its payload chunks are not yet completely written.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Pending = 200000200,
		
		/// <summary>
		/// All payload chunks were written and the artifact can be read back as evidence.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Complete = 200000201,
		
		/// <summary>
		/// Writing the artifact payload did not finish, so the artifact must not be read as evidence.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Failed = 200000202,
	}
}
#pragma warning restore CS1591
