#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	/// <summary>
	/// Internal scenario tag used by PredictUserRequestedFields for pay-go metering.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_enrichscenario
	{
		
		/// <summary>
		/// Default scenario bucket.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		@default = 0,
		
		/// <summary>
		/// MCP-origin caller; honored only when caller identity matches the MCP application user.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		mcp = 1,
	}
}
#pragma warning restore CS1591
