#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	/// <summary>
	/// Security type of external consult or transfer
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_externalsecuritytype
	{
		
		/// <summary>
		/// Follow workstream settings
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Followworkstreamsettings = 426130000,
		
		/// <summary>
		/// Turn off transcription & recording
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Turnofftranscriptionrecording = 426130001,
		
		/// <summary>
		/// Turn off recording, but keep transcription if on
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Turnoffrecordingbutkeeptranscriptionifon = 426130002,
	}
}
#pragma warning restore CS1591
