#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	/// <summary>
	/// Platform(s) a native extension targets within a wrapped mobile app build.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_targetplatform
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Android = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		iOS = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Both = 3,
	}
}
#pragma warning restore CS1591
