#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	/// <summary>
	/// Modes of operation of a feature
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_ocfeaturemode
	{
		
		/// <summary>
		/// Feature is disabled
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 192351000,
		
		/// <summary>
		/// Feature is enabled/disabled manually
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Manual = 192351001,
		
		/// <summary>
		/// Feature enable and disable is automatically managed
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Automatic = 192351002,
	}
}
#pragma warning restore CS1591
