#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	/// <summary>
	/// Allows a specific Customer Service Agent to be referred to without relying on individual agent implementation.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_optimizeagenttype
	{
		
		/// <summary>
		/// Reference to CMA
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CaseManagementAgent = 200000100,
		
		/// <summary>
		/// Reference to QEA
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QualityEvaluationAgent = 200000101,
		
		/// <summary>
		/// Reference to KMA
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomerKnowledgeManagementAgent = 200000103,
		
		/// <summary>
		/// Reference to CIA
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		CustomerIntentAgent = 200000104,
	}
}
#pragma warning restore CS1591
