#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	/// <summary>
	/// Portable schedule mode for an optimize segment.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_optimizeschedulemode
	{
		
		/// <summary>
		/// The segment fires once at its anchor time.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Onetime = 200000800,
		
		/// <summary>
		/// The segment fires repeatedly on its configured cadence.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Recurring = 200000801,
	}
}
#pragma warning restore CS1591
