#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	/// <summary>
	/// Scenario types supported by per Line of Business email template configurations for the Case Management Agent.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum msdyn_emailtemplatescenariotype
	{
		
		/// <summary>
		/// Email template used when the agent asks the customer a clarifying question.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		AskaQuestion = 100000000,
		
		/// <summary>
		/// Email template used when the agent provides a solution to the customer.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ProvideaSolution = 100000001,
	}
}
#pragma warning restore CS1591
