trigger:
  batch: true
  branches:
    include: ["master"]

pool:
  vmImage: 'windows-latest'

variables:
  SolutionNames: 'Defra.Imports.Analytics,Defra.Imports.Apps,Defra.Imports.Core,Defra.Imports.Plugins,Defra.Imports.SecurityModel,Defra.Imports.WebResources,Defra.Imports.Workflows'
  DynamicsEnvironment: 'https://defra-custmstr-eue-dev-imp.crm4.dynamics.com/'
  ExportPath: '$(Build.ArtifactStagingDirectory)/solutions'
  ZipFileName: 'DynamicsSolutions.zip'

steps:
- task: PowerPlatformToolInstaller@0
  inputs:
    DefaultVersion: true

- script: |
    echo Extracting solutions...
    mkdir $(ExportPath)
    IFS=',' read -r -a solutions <<< "$(SolutionNames)"
    for solution in "${solutions[@]}"
    do
      pac solution export --name $solution --path $(ExportPath)/$solution.zip --target $(DynamicsEnvironment)
    done
  displayName: 'Export Dynamics 365 Solutions'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(ExportPath)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(ZipFileName)'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/$(ZipFileName)'
    artifactName: 'DynamicsSolutions'
    publishLocation: 'Container'

- task: CmdLine@2
  inputs:
    script: |
      git add $(Build.ArtifactStagingDirectory)/$(ZipFileName)
      git commit -m "Added Dynamics solutions ZIP"
      git push
  displayName: 'Commit and Push ZIP to Repo'
