#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace Defra.Imports.Model
{
	
	
	/// <summary>
	/// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class ImportsContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public ImportsContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Defra.Imports.Model.Annotation"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Defra.Imports.Model.Annotation> AnnotationSet
		{
			get
			{
				return this.CreateQuery<Defra.Imports.Model.Annotation>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Defra.Imports.Model.Contact"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Defra.Imports.Model.Contact> ContactSet
		{
			get
			{
				return this.CreateQuery<Defra.Imports.Model.Contact>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Defra.Imports.Model.defra_country"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Defra.Imports.Model.defra_country> defra_countrySet
		{
			get
			{
				return this.CreateQuery<Defra.Imports.Model.defra_country>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Defra.Imports.Model.defraexp_configurationparameter"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Defra.Imports.Model.defraexp_configurationparameter> defraexp_configurationparameterSet
		{
			get
			{
				return this.CreateQuery<Defra.Imports.Model.defraexp_configurationparameter>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Defra.Imports.Model.defraimp_autonumber"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Defra.Imports.Model.defraimp_autonumber> defraimp_autonumberSet
		{
			get
			{
				return this.CreateQuery<Defra.Imports.Model.defraimp_autonumber>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Defra.Imports.Model.defraimp_commoditycomplement"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Defra.Imports.Model.defraimp_commoditycomplement> defraimp_commoditycomplementSet
		{
			get
			{
				return this.CreateQuery<Defra.Imports.Model.defraimp_commoditycomplement>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Defra.Imports.Model.defraimp_Consignee"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Defra.Imports.Model.defraimp_Consignee> defraimp_ConsigneeSet
		{
			get
			{
				return this.CreateQuery<Defra.Imports.Model.defraimp_Consignee>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Defra.Imports.Model.defraimp_counterhistory"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Defra.Imports.Model.defraimp_counterhistory> defraimp_counterhistorySet
		{
			get
			{
				return this.CreateQuery<Defra.Imports.Model.defraimp_counterhistory>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Defra.Imports.Model.defraimp_docom"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Defra.Imports.Model.defraimp_docom> defraimp_docomSet
		{
			get
			{
				return this.CreateQuery<Defra.Imports.Model.defraimp_docom>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Defra.Imports.Model.defraimp_goldbronzecommodity"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Defra.Imports.Model.defraimp_goldbronzecommodity> defraimp_goldbronzecommoditySet
		{
			get
			{
				return this.CreateQuery<Defra.Imports.Model.defraimp_goldbronzecommodity>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Defra.Imports.Model.defraimp_goldbronzecountriesnn"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Defra.Imports.Model.defraimp_goldbronzecountriesnn> defraimp_goldbronzecountriesnnSet
		{
			get
			{
				return this.CreateQuery<Defra.Imports.Model.defraimp_goldbronzecountriesnn>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Defra.Imports.Model.defraimp_importapplication"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Defra.Imports.Model.defraimp_importapplication> defraimp_importapplicationSet
		{
			get
			{
				return this.CreateQuery<Defra.Imports.Model.defraimp_importapplication>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Defra.Imports.Model.defraimp_importapplication_defra_country"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Defra.Imports.Model.defraimp_importapplication_defra_country> defraimp_importapplication_defra_countrySet
		{
			get
			{
				return this.CreateQuery<Defra.Imports.Model.defraimp_importapplication_defra_country>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Defra.Imports.Model.defraimp_importcountrycommodityrisklevel"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Defra.Imports.Model.defraimp_importcountrycommodityrisklevel> defraimp_importcountrycommodityrisklevelSet
		{
			get
			{
				return this.CreateQuery<Defra.Imports.Model.defraimp_importcountrycommodityrisklevel>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Defra.Imports.Model.defraimp_ImporterNotification"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Defra.Imports.Model.defraimp_ImporterNotification> defraimp_ImporterNotificationSet
		{
			get
			{
				return this.CreateQuery<Defra.Imports.Model.defraimp_ImporterNotification>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Defra.Imports.Model.defraimp_ImporterNotification_CountriesofTransit"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Defra.Imports.Model.defraimp_ImporterNotification_CountriesofTransit> defraimp_ImporterNotification_CountriesofTransitSet
		{
			get
			{
				return this.CreateQuery<Defra.Imports.Model.defraimp_ImporterNotification_CountriesofTransit>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Defra.Imports.Model.defraimp_importinspection"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Defra.Imports.Model.defraimp_importinspection> defraimp_importinspectionSet
		{
			get
			{
				return this.CreateQuery<Defra.Imports.Model.defraimp_importinspection>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Defra.Imports.Model.defraimp_importquery"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Defra.Imports.Model.defraimp_importquery> defraimp_importquerySet
		{
			get
			{
				return this.CreateQuery<Defra.Imports.Model.defraimp_importquery>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Defra.Imports.Model.defraimp_importrisklevel"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Defra.Imports.Model.defraimp_importrisklevel> defraimp_importrisklevelSet
		{
			get
			{
				return this.CreateQuery<Defra.Imports.Model.defraimp_importrisklevel>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Defra.Imports.Model.defraimp_imptype"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Defra.Imports.Model.defraimp_imptype> defraimp_imptypeSet
		{
			get
			{
				return this.CreateQuery<Defra.Imports.Model.defraimp_imptype>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Defra.Imports.Model.defraimp_inspectioncoveragerule"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Defra.Imports.Model.defraimp_inspectioncoveragerule> defraimp_inspectioncoverageruleSet
		{
			get
			{
				return this.CreateQuery<Defra.Imports.Model.defraimp_inspectioncoveragerule>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Defra.Imports.Model.defraimp_ipaffsdocument"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Defra.Imports.Model.defraimp_ipaffsdocument> defraimp_ipaffsdocumentSet
		{
			get
			{
				return this.CreateQuery<Defra.Imports.Model.defraimp_ipaffsdocument>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Defra.Imports.Model.defraimp_itahc"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Defra.Imports.Model.defraimp_itahc> defraimp_itahcSet
		{
			get
			{
				return this.CreateQuery<Defra.Imports.Model.defraimp_itahc>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Defra.Imports.Model.defraimp_matchrecord"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Defra.Imports.Model.defraimp_matchrecord> defraimp_matchrecordSet
		{
			get
			{
				return this.CreateQuery<Defra.Imports.Model.defraimp_matchrecord>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Defra.Imports.Model.defraimp_PlaceOfDestination"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Defra.Imports.Model.defraimp_PlaceOfDestination> defraimp_PlaceOfDestinationSet
		{
			get
			{
				return this.CreateQuery<Defra.Imports.Model.defraimp_PlaceOfDestination>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Defra.Imports.Model.defraimp_placeoforigin"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Defra.Imports.Model.defraimp_placeoforigin> defraimp_placeoforiginSet
		{
			get
			{
				return this.CreateQuery<Defra.Imports.Model.defraimp_placeoforigin>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Defra.Imports.Model.defraimp_postcoderegion"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Defra.Imports.Model.defraimp_postcoderegion> defraimp_postcoderegionSet
		{
			get
			{
				return this.CreateQuery<Defra.Imports.Model.defraimp_postcoderegion>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Defra.Imports.Model.defraimp_PotentiallyRelatedImportRecords"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Defra.Imports.Model.defraimp_PotentiallyRelatedImportRecords> defraimp_PotentiallyRelatedImportRecordsSet
		{
			get
			{
				return this.CreateQuery<Defra.Imports.Model.defraimp_PotentiallyRelatedImportRecords>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Defra.Imports.Model.defraimp_Transporter"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Defra.Imports.Model.defraimp_Transporter> defraimp_TransporterSet
		{
			get
			{
				return this.CreateQuery<Defra.Imports.Model.defraimp_Transporter>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Defra.Imports.Model.defraimp_WatchFlag"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Defra.Imports.Model.defraimp_WatchFlag> defraimp_WatchFlagSet
		{
			get
			{
				return this.CreateQuery<Defra.Imports.Model.defraimp_WatchFlag>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Defra.Imports.Model.defraimp_WatchList"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Defra.Imports.Model.defraimp_WatchList> defraimp_WatchListSet
		{
			get
			{
				return this.CreateQuery<Defra.Imports.Model.defraimp_WatchList>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Defra.Imports.Model.SystemUser"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Defra.Imports.Model.SystemUser> SystemUserSet
		{
			get
			{
				return this.CreateQuery<Defra.Imports.Model.SystemUser>();
			}
		}
	}
}
#pragma warning restore CS1591
