declare namespace WebApi {
  interface defraimp_itahc_Base extends WebEntity {
    createdon?: Date | null;
    defraimp_animalcertifiedas?: defraimp_animalcertifiedas | null;
    defraimp_centralcompetentauthority?: string | null;
    defraimp_certificatestatus?: defraimp_certificatestatus | null;
    defraimp_certificateversionnumber?: number | null;
    defraimp_commoditycode?: string | null;
    defraimp_commoditycomplementstext?: string | null;
    defraimp_consigneeaddresscity?: string | null;
    defraimp_consigneeaddresscountryisocode?: string | null;
    defraimp_consigneeaddresspostcode?: string | null;
    defraimp_consigneeaddressstreet?: string | null;
    defraimp_consigneeapprovalnumber?: string | null;
    defraimp_consigneegeneralnumber?: string | null;
    defraimp_consigneename?: string | null;
    defraimp_consigneetracesid?: number | null;
    defraimp_consigneetype?: string | null;
    defraimp_consignoraddresscity?: string | null;
    defraimp_consignoraddresscountryisocode?: string | null;
    defraimp_consignoraddresspostcode?: string | null;
    defraimp_consignoraddressstreet?: string | null;
    defraimp_consignorapprovalnumber?: string | null;
    defraimp_consignorgeneralnumber?: string | null;
    defraimp_consignorname?: string | null;
    defraimp_consignortracesid?: number | null;
    defraimp_consignortype?: string | null;
    defraimp_countryoforiginisocode?: string | null;
    defraimp_declarationemail?: string | null;
    defraimp_declarationfax?: string | null;
    defraimp_declarationfirstname?: string | null;
    defraimp_declarationlastname?: string | null;
    defraimp_declarationphone?: string | null;
    defraimp_declarationsignaturedate?: Date | null;
    defraimp_departuredatetime?: Date | null;
    defraimp_estimatedjourneytime?: number | null;
    defraimp_hasmultiplecommodities?: boolean | null;
    defraimp_healthcertificatenumber?: string | null;
    defraimp_identificationofanimalstext?: string | null;
    defraimp_itahcid?: string | null;
    defraimp_localcompetentauthority?: string | null;
    defraimp_localveterinaryunit?: string | null;
    defraimp_lvuno?: string | null;
    defraimp_name?: string | null;
    defraimp_numberofpackages?: number | null;
    defraimp_officialvetcapacity?: defraimp_officialvetcapacity | null;
    defraimp_officialvetcompetentauthority?: string | null;
    defraimp_officialvetemail?: string | null;
    defraimp_officialvetfax?: string | null;
    defraimp_officialvetfirstname?: string | null;
    defraimp_officialvetid?: number | null;
    defraimp_officialvetlastname?: string | null;
    defraimp_officialvetphone?: string | null;
    defraimp_officialvetsignaturedate?: Date | null;
    defraimp_ovname?: string | null;
    defraimp_placeofdestinationaddresscity?: string | null;
    defraimp_placeofdestinationaddresscountryisocode?: string | null;
    defraimp_placeofdestinationaddresspostcode?: string | null;
    defraimp_placeofdestinationaddressstreet?: string | null;
    defraimp_placeofdestinationapprovalnumber?: string | null;
    defraimp_placeofdestinationgeneralnumber?: string | null;
    defraimp_placeofdestinationname?: string | null;
    defraimp_placeofdestinationtracesid?: number | null;
    defraimp_placeofdestinationtype?: string | null;
    defraimp_placeofloadingaddresscity?: string | null;
    defraimp_placeofloadingaddresscountryisocode?: string | null;
    defraimp_placeofloadingaddresspostcode?: string | null;
    defraimp_placeofloadingaddressstreet?: string | null;
    defraimp_placeofloadingapprovalnumber?: string | null;
    defraimp_placeofloadinggeneralnumber?: string | null;
    defraimp_placeofloadingname?: string | null;
    defraimp_placeofloadingtracesid?: number | null;
    defraimp_placeofloadingtype?: string | null;
    defraimp_placeoforiginharvestaddresscity?: string | null;
    defraimp_placeoforiginharvestaddresspostcode?: string | null;
    defraimp_placeoforiginharvestaddressstreet?: string | null;
    defraimp_placeoforiginharvestapprovalnumber?: string | null;
    defraimp_placeoforiginharvestgeneralnumber?: string | null;
    defraimp_placeoforiginharvestname?: string | null;
    defraimp_placeoforiginharvesttracesid?: number | null;
    defraimp_placeoforiginharvesttype?: string | null;
    defraimp_purpose?: string | null;
    defraimp_quantity?: number | null;
    defraimp_replacedreferencenumber?: string | null;
    defraimp_replacingreferencenumber?: string | null;
    defraimp_species?: string | null;
    defraimp_tracesreceiveddate?: Date | null;
    defraimp_transporteraddresscity?: string | null;
    defraimp_transporteraddresscountryisocode?: string | null;
    defraimp_transporteraddresspostcode?: string | null;
    defraimp_transporteraddressstreet?: string | null;
    defraimp_transporterapprovalnumber?: string | null;
    defraimp_transportergeneralnumber?: string | null;
    defraimp_transportername?: string | null;
    defraimp_transportertracesid?: number | null;
    defraimp_transportertype?: string | null;
    importsequencenumber?: number | null;
    modifiedon?: Date | null;
    overriddencreatedon?: Date | null;
    statecode?: defraimp_itahc_statecode | null;
    statuscode?: defraimp_itahc_statuscode | null;
    timezoneruleversionnumber?: number | null;
    utcconversiontimezonecode?: number | null;
    versionnumber?: number | null;
  }
  interface defraimp_itahc_Relationships {
    defraimp_ReplacedById?: defraimp_itahc_Result | null;
    defraimp_ReplacesId?: defraimp_itahc_Result | null;
    defraimp_defraimp_importapplication_defraimp_itahc?: defraimp_importapplication_Result[] | null;
    defraimp_defraimp_itahc_defraimp_importapplication?: defraimp_importapplication_Result[] | null;
    defraimp_defraimp_itahc_defraimp_importinspection_RelatedITAHC?: defraimp_importinspection_Result[] | null;
    defraimp_defraimp_itahc_defraimp_itahc?: defraimp_itahc_Result[] | null;
    defraimp_defraimp_itahc_defraimp_matchrecord_ITAHC?: defraimp_matchrecord_Result[] | null;
    defraimp_defraimp_itahc_defraimp_rb?: defraimp_itahc_Result[] | null;
  }
  interface defraimp_itahc extends defraimp_itahc_Base, defraimp_itahc_Relationships {
    defraimp_CommodityType_bind$defraexp_commoditytypes?: string | null;
    defraimp_ConsigneeAddressCountryId_bind$defra_countries?: string | null;
    defraimp_ConsignorAddressCountryId_bind$defra_countries?: string | null;
    defraimp_CountryOfOriginId_bind$defra_countries?: string | null;
    defraimp_PlaceOfDestinationAddressCountryId_bind$defra_countries?: string | null;
    defraimp_PlaceOfLoadingAddressCountryId_bind$defra_countries?: string | null;
    defraimp_PlaceOfOriginHarvestAddressCountryId_bind$defra_countries?: string | null;
    defraimp_ReplacedById_bind$defraimp_itahcs?: string | null;
    defraimp_ReplacesId_bind$defraimp_itahcs?: string | null;
    defraimp_TransporterAddressCountryId_bind$defra_countries?: string | null;
    ownerid_bind$owners?: string | null;
  }
  interface defraimp_itahc_Create extends defraimp_itahc {
  }
  interface defraimp_itahc_Update extends defraimp_itahc {
  }
  interface defraimp_itahc_Select {
    createdby_guid: WebAttribute<defraimp_itahc_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
    createdon: WebAttribute<defraimp_itahc_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
    createdonbehalfby_guid: WebAttribute<defraimp_itahc_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
    defraimp_animalcertifiedas: WebAttribute<defraimp_itahc_Select, { defraimp_animalcertifiedas: defraimp_animalcertifiedas | null }, { defraimp_animalcertifiedas_formatted?: string }>;
    defraimp_centralcompetentauthority: WebAttribute<defraimp_itahc_Select, { defraimp_centralcompetentauthority: string | null }, {  }>;
    defraimp_certificatestatus: WebAttribute<defraimp_itahc_Select, { defraimp_certificatestatus: defraimp_certificatestatus | null }, { defraimp_certificatestatus_formatted?: string }>;
    defraimp_certificateversionnumber: WebAttribute<defraimp_itahc_Select, { defraimp_certificateversionnumber: number | null }, {  }>;
    defraimp_commoditycode: WebAttribute<defraimp_itahc_Select, { defraimp_commoditycode: string | null }, {  }>;
    defraimp_commoditycomplementstext: WebAttribute<defraimp_itahc_Select, { defraimp_commoditycomplementstext: string | null }, {  }>;
    defraimp_commoditytype_guid: WebAttribute<defraimp_itahc_Select, { defraimp_commoditytype_guid: string | null }, { defraimp_commoditytype_formatted?: string }>;
    defraimp_consigneeaddresscity: WebAttribute<defraimp_itahc_Select, { defraimp_consigneeaddresscity: string | null }, {  }>;
    defraimp_consigneeaddresscountryid_guid: WebAttribute<defraimp_itahc_Select, { defraimp_consigneeaddresscountryid_guid: string | null }, { defraimp_consigneeaddresscountryid_formatted?: string }>;
    defraimp_consigneeaddresscountryisocode: WebAttribute<defraimp_itahc_Select, { defraimp_consigneeaddresscountryisocode: string | null }, {  }>;
    defraimp_consigneeaddresspostcode: WebAttribute<defraimp_itahc_Select, { defraimp_consigneeaddresspostcode: string | null }, {  }>;
    defraimp_consigneeaddressstreet: WebAttribute<defraimp_itahc_Select, { defraimp_consigneeaddressstreet: string | null }, {  }>;
    defraimp_consigneeapprovalnumber: WebAttribute<defraimp_itahc_Select, { defraimp_consigneeapprovalnumber: string | null }, {  }>;
    defraimp_consigneegeneralnumber: WebAttribute<defraimp_itahc_Select, { defraimp_consigneegeneralnumber: string | null }, {  }>;
    defraimp_consigneename: WebAttribute<defraimp_itahc_Select, { defraimp_consigneename: string | null }, {  }>;
    defraimp_consigneetracesid: WebAttribute<defraimp_itahc_Select, { defraimp_consigneetracesid: number | null }, {  }>;
    defraimp_consigneetype: WebAttribute<defraimp_itahc_Select, { defraimp_consigneetype: string | null }, {  }>;
    defraimp_consignoraddresscity: WebAttribute<defraimp_itahc_Select, { defraimp_consignoraddresscity: string | null }, {  }>;
    defraimp_consignoraddresscountryid_guid: WebAttribute<defraimp_itahc_Select, { defraimp_consignoraddresscountryid_guid: string | null }, { defraimp_consignoraddresscountryid_formatted?: string }>;
    defraimp_consignoraddresscountryisocode: WebAttribute<defraimp_itahc_Select, { defraimp_consignoraddresscountryisocode: string | null }, {  }>;
    defraimp_consignoraddresspostcode: WebAttribute<defraimp_itahc_Select, { defraimp_consignoraddresspostcode: string | null }, {  }>;
    defraimp_consignoraddressstreet: WebAttribute<defraimp_itahc_Select, { defraimp_consignoraddressstreet: string | null }, {  }>;
    defraimp_consignorapprovalnumber: WebAttribute<defraimp_itahc_Select, { defraimp_consignorapprovalnumber: string | null }, {  }>;
    defraimp_consignorgeneralnumber: WebAttribute<defraimp_itahc_Select, { defraimp_consignorgeneralnumber: string | null }, {  }>;
    defraimp_consignorname: WebAttribute<defraimp_itahc_Select, { defraimp_consignorname: string | null }, {  }>;
    defraimp_consignortracesid: WebAttribute<defraimp_itahc_Select, { defraimp_consignortracesid: number | null }, {  }>;
    defraimp_consignortype: WebAttribute<defraimp_itahc_Select, { defraimp_consignortype: string | null }, {  }>;
    defraimp_countryoforiginid_guid: WebAttribute<defraimp_itahc_Select, { defraimp_countryoforiginid_guid: string | null }, { defraimp_countryoforiginid_formatted?: string }>;
    defraimp_countryoforiginisocode: WebAttribute<defraimp_itahc_Select, { defraimp_countryoforiginisocode: string | null }, {  }>;
    defraimp_declarationemail: WebAttribute<defraimp_itahc_Select, { defraimp_declarationemail: string | null }, {  }>;
    defraimp_declarationfax: WebAttribute<defraimp_itahc_Select, { defraimp_declarationfax: string | null }, {  }>;
    defraimp_declarationfirstname: WebAttribute<defraimp_itahc_Select, { defraimp_declarationfirstname: string | null }, {  }>;
    defraimp_declarationlastname: WebAttribute<defraimp_itahc_Select, { defraimp_declarationlastname: string | null }, {  }>;
    defraimp_declarationphone: WebAttribute<defraimp_itahc_Select, { defraimp_declarationphone: string | null }, {  }>;
    defraimp_declarationsignaturedate: WebAttribute<defraimp_itahc_Select, { defraimp_declarationsignaturedate: Date | null }, { defraimp_declarationsignaturedate_formatted?: string }>;
    defraimp_departuredatetime: WebAttribute<defraimp_itahc_Select, { defraimp_departuredatetime: Date | null }, { defraimp_departuredatetime_formatted?: string }>;
    defraimp_estimatedjourneytime: WebAttribute<defraimp_itahc_Select, { defraimp_estimatedjourneytime: number | null }, {  }>;
    defraimp_hasmultiplecommodities: WebAttribute<defraimp_itahc_Select, { defraimp_hasmultiplecommodities: boolean | null }, {  }>;
    defraimp_healthcertificatenumber: WebAttribute<defraimp_itahc_Select, { defraimp_healthcertificatenumber: string | null }, {  }>;
    defraimp_identificationofanimalstext: WebAttribute<defraimp_itahc_Select, { defraimp_identificationofanimalstext: string | null }, {  }>;
    defraimp_itahcid: WebAttribute<defraimp_itahc_Select, { defraimp_itahcid: string | null }, {  }>;
    defraimp_localcompetentauthority: WebAttribute<defraimp_itahc_Select, { defraimp_localcompetentauthority: string | null }, {  }>;
    defraimp_localveterinaryunit: WebAttribute<defraimp_itahc_Select, { defraimp_localveterinaryunit: string | null }, {  }>;
    defraimp_lvuno: WebAttribute<defraimp_itahc_Select, { defraimp_lvuno: string | null }, {  }>;
    defraimp_name: WebAttribute<defraimp_itahc_Select, { defraimp_name: string | null }, {  }>;
    defraimp_numberofpackages: WebAttribute<defraimp_itahc_Select, { defraimp_numberofpackages: number | null }, {  }>;
    defraimp_officialvetcapacity: WebAttribute<defraimp_itahc_Select, { defraimp_officialvetcapacity: defraimp_officialvetcapacity | null }, { defraimp_officialvetcapacity_formatted?: string }>;
    defraimp_officialvetcompetentauthority: WebAttribute<defraimp_itahc_Select, { defraimp_officialvetcompetentauthority: string | null }, {  }>;
    defraimp_officialvetemail: WebAttribute<defraimp_itahc_Select, { defraimp_officialvetemail: string | null }, {  }>;
    defraimp_officialvetfax: WebAttribute<defraimp_itahc_Select, { defraimp_officialvetfax: string | null }, {  }>;
    defraimp_officialvetfirstname: WebAttribute<defraimp_itahc_Select, { defraimp_officialvetfirstname: string | null }, {  }>;
    defraimp_officialvetid: WebAttribute<defraimp_itahc_Select, { defraimp_officialvetid: number | null }, {  }>;
    defraimp_officialvetlastname: WebAttribute<defraimp_itahc_Select, { defraimp_officialvetlastname: string | null }, {  }>;
    defraimp_officialvetphone: WebAttribute<defraimp_itahc_Select, { defraimp_officialvetphone: string | null }, {  }>;
    defraimp_officialvetsignaturedate: WebAttribute<defraimp_itahc_Select, { defraimp_officialvetsignaturedate: Date | null }, { defraimp_officialvetsignaturedate_formatted?: string }>;
    defraimp_ovname: WebAttribute<defraimp_itahc_Select, { defraimp_ovname: string | null }, {  }>;
    defraimp_placeofdestinationaddresscity: WebAttribute<defraimp_itahc_Select, { defraimp_placeofdestinationaddresscity: string | null }, {  }>;
    defraimp_placeofdestinationaddresscountryid_guid: WebAttribute<defraimp_itahc_Select, { defraimp_placeofdestinationaddresscountryid_guid: string | null }, { defraimp_placeofdestinationaddresscountryid_formatted?: string }>;
    defraimp_placeofdestinationaddresscountryisocode: WebAttribute<defraimp_itahc_Select, { defraimp_placeofdestinationaddresscountryisocode: string | null }, {  }>;
    defraimp_placeofdestinationaddresspostcode: WebAttribute<defraimp_itahc_Select, { defraimp_placeofdestinationaddresspostcode: string | null }, {  }>;
    defraimp_placeofdestinationaddressstreet: WebAttribute<defraimp_itahc_Select, { defraimp_placeofdestinationaddressstreet: string | null }, {  }>;
    defraimp_placeofdestinationapprovalnumber: WebAttribute<defraimp_itahc_Select, { defraimp_placeofdestinationapprovalnumber: string | null }, {  }>;
    defraimp_placeofdestinationgeneralnumber: WebAttribute<defraimp_itahc_Select, { defraimp_placeofdestinationgeneralnumber: string | null }, {  }>;
    defraimp_placeofdestinationname: WebAttribute<defraimp_itahc_Select, { defraimp_placeofdestinationname: string | null }, {  }>;
    defraimp_placeofdestinationtracesid: WebAttribute<defraimp_itahc_Select, { defraimp_placeofdestinationtracesid: number | null }, {  }>;
    defraimp_placeofdestinationtype: WebAttribute<defraimp_itahc_Select, { defraimp_placeofdestinationtype: string | null }, {  }>;
    defraimp_placeofloadingaddresscity: WebAttribute<defraimp_itahc_Select, { defraimp_placeofloadingaddresscity: string | null }, {  }>;
    defraimp_placeofloadingaddresscountryid_guid: WebAttribute<defraimp_itahc_Select, { defraimp_placeofloadingaddresscountryid_guid: string | null }, { defraimp_placeofloadingaddresscountryid_formatted?: string }>;
    defraimp_placeofloadingaddresscountryisocode: WebAttribute<defraimp_itahc_Select, { defraimp_placeofloadingaddresscountryisocode: string | null }, {  }>;
    defraimp_placeofloadingaddresspostcode: WebAttribute<defraimp_itahc_Select, { defraimp_placeofloadingaddresspostcode: string | null }, {  }>;
    defraimp_placeofloadingaddressstreet: WebAttribute<defraimp_itahc_Select, { defraimp_placeofloadingaddressstreet: string | null }, {  }>;
    defraimp_placeofloadingapprovalnumber: WebAttribute<defraimp_itahc_Select, { defraimp_placeofloadingapprovalnumber: string | null }, {  }>;
    defraimp_placeofloadinggeneralnumber: WebAttribute<defraimp_itahc_Select, { defraimp_placeofloadinggeneralnumber: string | null }, {  }>;
    defraimp_placeofloadingname: WebAttribute<defraimp_itahc_Select, { defraimp_placeofloadingname: string | null }, {  }>;
    defraimp_placeofloadingtracesid: WebAttribute<defraimp_itahc_Select, { defraimp_placeofloadingtracesid: number | null }, {  }>;
    defraimp_placeofloadingtype: WebAttribute<defraimp_itahc_Select, { defraimp_placeofloadingtype: string | null }, {  }>;
    defraimp_placeoforiginharvestaddresscity: WebAttribute<defraimp_itahc_Select, { defraimp_placeoforiginharvestaddresscity: string | null }, {  }>;
    defraimp_placeoforiginharvestaddresscountryid_guid: WebAttribute<defraimp_itahc_Select, { defraimp_placeoforiginharvestaddresscountryid_guid: string | null }, { defraimp_placeoforiginharvestaddresscountryid_formatted?: string }>;
    defraimp_placeoforiginharvestaddresspostcode: WebAttribute<defraimp_itahc_Select, { defraimp_placeoforiginharvestaddresspostcode: string | null }, {  }>;
    defraimp_placeoforiginharvestaddressstreet: WebAttribute<defraimp_itahc_Select, { defraimp_placeoforiginharvestaddressstreet: string | null }, {  }>;
    defraimp_placeoforiginharvestapprovalnumber: WebAttribute<defraimp_itahc_Select, { defraimp_placeoforiginharvestapprovalnumber: string | null }, {  }>;
    defraimp_placeoforiginharvestgeneralnumber: WebAttribute<defraimp_itahc_Select, { defraimp_placeoforiginharvestgeneralnumber: string | null }, {  }>;
    defraimp_placeoforiginharvestname: WebAttribute<defraimp_itahc_Select, { defraimp_placeoforiginharvestname: string | null }, {  }>;
    defraimp_placeoforiginharvesttracesid: WebAttribute<defraimp_itahc_Select, { defraimp_placeoforiginharvesttracesid: number | null }, {  }>;
    defraimp_placeoforiginharvesttype: WebAttribute<defraimp_itahc_Select, { defraimp_placeoforiginharvesttype: string | null }, {  }>;
    defraimp_purpose: WebAttribute<defraimp_itahc_Select, { defraimp_purpose: string | null }, {  }>;
    defraimp_quantity: WebAttribute<defraimp_itahc_Select, { defraimp_quantity: number | null }, {  }>;
    defraimp_replacedbyid_guid: WebAttribute<defraimp_itahc_Select, { defraimp_replacedbyid_guid: string | null }, { defraimp_replacedbyid_formatted?: string }>;
    defraimp_replacedreferencenumber: WebAttribute<defraimp_itahc_Select, { defraimp_replacedreferencenumber: string | null }, {  }>;
    defraimp_replacesid_guid: WebAttribute<defraimp_itahc_Select, { defraimp_replacesid_guid: string | null }, { defraimp_replacesid_formatted?: string }>;
    defraimp_replacingreferencenumber: WebAttribute<defraimp_itahc_Select, { defraimp_replacingreferencenumber: string | null }, {  }>;
    defraimp_species: WebAttribute<defraimp_itahc_Select, { defraimp_species: string | null }, {  }>;
    defraimp_tracesreceiveddate: WebAttribute<defraimp_itahc_Select, { defraimp_tracesreceiveddate: Date | null }, { defraimp_tracesreceiveddate_formatted?: string }>;
    defraimp_transporteraddresscity: WebAttribute<defraimp_itahc_Select, { defraimp_transporteraddresscity: string | null }, {  }>;
    defraimp_transporteraddresscountryid_guid: WebAttribute<defraimp_itahc_Select, { defraimp_transporteraddresscountryid_guid: string | null }, { defraimp_transporteraddresscountryid_formatted?: string }>;
    defraimp_transporteraddresscountryisocode: WebAttribute<defraimp_itahc_Select, { defraimp_transporteraddresscountryisocode: string | null }, {  }>;
    defraimp_transporteraddresspostcode: WebAttribute<defraimp_itahc_Select, { defraimp_transporteraddresspostcode: string | null }, {  }>;
    defraimp_transporteraddressstreet: WebAttribute<defraimp_itahc_Select, { defraimp_transporteraddressstreet: string | null }, {  }>;
    defraimp_transporterapprovalnumber: WebAttribute<defraimp_itahc_Select, { defraimp_transporterapprovalnumber: string | null }, {  }>;
    defraimp_transportergeneralnumber: WebAttribute<defraimp_itahc_Select, { defraimp_transportergeneralnumber: string | null }, {  }>;
    defraimp_transportername: WebAttribute<defraimp_itahc_Select, { defraimp_transportername: string | null }, {  }>;
    defraimp_transportertracesid: WebAttribute<defraimp_itahc_Select, { defraimp_transportertracesid: number | null }, {  }>;
    defraimp_transportertype: WebAttribute<defraimp_itahc_Select, { defraimp_transportertype: string | null }, {  }>;
    importsequencenumber: WebAttribute<defraimp_itahc_Select, { importsequencenumber: number | null }, {  }>;
    modifiedby_guid: WebAttribute<defraimp_itahc_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
    modifiedon: WebAttribute<defraimp_itahc_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
    modifiedonbehalfby_guid: WebAttribute<defraimp_itahc_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
    overriddencreatedon: WebAttribute<defraimp_itahc_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
    ownerid_guid: WebAttribute<defraimp_itahc_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
    owningbusinessunit_guid: WebAttribute<defraimp_itahc_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
    owningteam_guid: WebAttribute<defraimp_itahc_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
    owninguser_guid: WebAttribute<defraimp_itahc_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
    statecode: WebAttribute<defraimp_itahc_Select, { statecode: defraimp_itahc_statecode | null }, { statecode_formatted?: string }>;
    statuscode: WebAttribute<defraimp_itahc_Select, { statuscode: defraimp_itahc_statuscode | null }, { statuscode_formatted?: string }>;
    timezoneruleversionnumber: WebAttribute<defraimp_itahc_Select, { timezoneruleversionnumber: number | null }, {  }>;
    utcconversiontimezonecode: WebAttribute<defraimp_itahc_Select, { utcconversiontimezonecode: number | null }, {  }>;
    versionnumber: WebAttribute<defraimp_itahc_Select, { versionnumber: number | null }, {  }>;
  }
  interface defraimp_itahc_Filter {
    createdby_guid: XQW.Guid;
    createdon: Date;
    createdonbehalfby_guid: XQW.Guid;
    defraimp_animalcertifiedas: defraimp_animalcertifiedas;
    defraimp_centralcompetentauthority: string;
    defraimp_certificatestatus: defraimp_certificatestatus;
    defraimp_certificateversionnumber: number;
    defraimp_commoditycode: string;
    defraimp_commoditycomplementstext: string;
    defraimp_commoditytype_guid: XQW.Guid;
    defraimp_consigneeaddresscity: string;
    defraimp_consigneeaddresscountryid_guid: XQW.Guid;
    defraimp_consigneeaddresscountryisocode: string;
    defraimp_consigneeaddresspostcode: string;
    defraimp_consigneeaddressstreet: string;
    defraimp_consigneeapprovalnumber: string;
    defraimp_consigneegeneralnumber: string;
    defraimp_consigneename: string;
    defraimp_consigneetracesid: number;
    defraimp_consigneetype: string;
    defraimp_consignoraddresscity: string;
    defraimp_consignoraddresscountryid_guid: XQW.Guid;
    defraimp_consignoraddresscountryisocode: string;
    defraimp_consignoraddresspostcode: string;
    defraimp_consignoraddressstreet: string;
    defraimp_consignorapprovalnumber: string;
    defraimp_consignorgeneralnumber: string;
    defraimp_consignorname: string;
    defraimp_consignortracesid: number;
    defraimp_consignortype: string;
    defraimp_countryoforiginid_guid: XQW.Guid;
    defraimp_countryoforiginisocode: string;
    defraimp_declarationemail: string;
    defraimp_declarationfax: string;
    defraimp_declarationfirstname: string;
    defraimp_declarationlastname: string;
    defraimp_declarationphone: string;
    defraimp_declarationsignaturedate: Date;
    defraimp_departuredatetime: Date;
    defraimp_estimatedjourneytime: any;
    defraimp_hasmultiplecommodities: boolean;
    defraimp_healthcertificatenumber: string;
    defraimp_identificationofanimalstext: string;
    defraimp_itahcid: XQW.Guid;
    defraimp_localcompetentauthority: string;
    defraimp_localveterinaryunit: string;
    defraimp_lvuno: string;
    defraimp_name: string;
    defraimp_numberofpackages: number;
    defraimp_officialvetcapacity: defraimp_officialvetcapacity;
    defraimp_officialvetcompetentauthority: string;
    defraimp_officialvetemail: string;
    defraimp_officialvetfax: string;
    defraimp_officialvetfirstname: string;
    defraimp_officialvetid: number;
    defraimp_officialvetlastname: string;
    defraimp_officialvetphone: string;
    defraimp_officialvetsignaturedate: Date;
    defraimp_ovname: string;
    defraimp_placeofdestinationaddresscity: string;
    defraimp_placeofdestinationaddresscountryid_guid: XQW.Guid;
    defraimp_placeofdestinationaddresscountryisocode: string;
    defraimp_placeofdestinationaddresspostcode: string;
    defraimp_placeofdestinationaddressstreet: string;
    defraimp_placeofdestinationapprovalnumber: string;
    defraimp_placeofdestinationgeneralnumber: string;
    defraimp_placeofdestinationname: string;
    defraimp_placeofdestinationtracesid: number;
    defraimp_placeofdestinationtype: string;
    defraimp_placeofloadingaddresscity: string;
    defraimp_placeofloadingaddresscountryid_guid: XQW.Guid;
    defraimp_placeofloadingaddresscountryisocode: string;
    defraimp_placeofloadingaddresspostcode: string;
    defraimp_placeofloadingaddressstreet: string;
    defraimp_placeofloadingapprovalnumber: string;
    defraimp_placeofloadinggeneralnumber: string;
    defraimp_placeofloadingname: string;
    defraimp_placeofloadingtracesid: number;
    defraimp_placeofloadingtype: string;
    defraimp_placeoforiginharvestaddresscity: string;
    defraimp_placeoforiginharvestaddresscountryid_guid: XQW.Guid;
    defraimp_placeoforiginharvestaddresspostcode: string;
    defraimp_placeoforiginharvestaddressstreet: string;
    defraimp_placeoforiginharvestapprovalnumber: string;
    defraimp_placeoforiginharvestgeneralnumber: string;
    defraimp_placeoforiginharvestname: string;
    defraimp_placeoforiginharvesttracesid: number;
    defraimp_placeoforiginharvesttype: string;
    defraimp_purpose: string;
    defraimp_quantity: any;
    defraimp_replacedbyid_guid: XQW.Guid;
    defraimp_replacedreferencenumber: string;
    defraimp_replacesid_guid: XQW.Guid;
    defraimp_replacingreferencenumber: string;
    defraimp_species: string;
    defraimp_tracesreceiveddate: Date;
    defraimp_transporteraddresscity: string;
    defraimp_transporteraddresscountryid_guid: XQW.Guid;
    defraimp_transporteraddresscountryisocode: string;
    defraimp_transporteraddresspostcode: string;
    defraimp_transporteraddressstreet: string;
    defraimp_transporterapprovalnumber: string;
    defraimp_transportergeneralnumber: string;
    defraimp_transportername: string;
    defraimp_transportertracesid: number;
    defraimp_transportertype: string;
    importsequencenumber: number;
    modifiedby_guid: XQW.Guid;
    modifiedon: Date;
    modifiedonbehalfby_guid: XQW.Guid;
    overriddencreatedon: Date;
    ownerid_guid: XQW.Guid;
    owningbusinessunit_guid: XQW.Guid;
    owningteam_guid: XQW.Guid;
    owninguser_guid: XQW.Guid;
    statecode: defraimp_itahc_statecode;
    statuscode: defraimp_itahc_statuscode;
    timezoneruleversionnumber: number;
    utcconversiontimezonecode: number;
    versionnumber: number;
  }
  interface defraimp_itahc_Expand {
    defraimp_ReplacedById: WebExpand<defraimp_itahc_Expand, defraimp_itahc_Select, defraimp_itahc_Filter, { defraimp_ReplacedById: defraimp_itahc_Result }>;
    defraimp_ReplacesId: WebExpand<defraimp_itahc_Expand, defraimp_itahc_Select, defraimp_itahc_Filter, { defraimp_ReplacesId: defraimp_itahc_Result }>;
    defraimp_defraimp_importapplication_defraimp_itahc: WebExpand<defraimp_itahc_Expand, defraimp_importapplication_Select, defraimp_importapplication_Filter, { defraimp_defraimp_importapplication_defraimp_itahc: defraimp_importapplication_Result[] }>;
    defraimp_defraimp_itahc_defraimp_importapplication: WebExpand<defraimp_itahc_Expand, defraimp_importapplication_Select, defraimp_importapplication_Filter, { defraimp_defraimp_itahc_defraimp_importapplication: defraimp_importapplication_Result[] }>;
    defraimp_defraimp_itahc_defraimp_importinspection_RelatedITAHC: WebExpand<defraimp_itahc_Expand, defraimp_importinspection_Select, defraimp_importinspection_Filter, { defraimp_defraimp_itahc_defraimp_importinspection_RelatedITAHC: defraimp_importinspection_Result[] }>;
    defraimp_defraimp_itahc_defraimp_itahc: WebExpand<defraimp_itahc_Expand, defraimp_itahc_Select, defraimp_itahc_Filter, { defraimp_defraimp_itahc_defraimp_itahc: defraimp_itahc_Result[] }>;
    defraimp_defraimp_itahc_defraimp_matchrecord_ITAHC: WebExpand<defraimp_itahc_Expand, defraimp_matchrecord_Select, defraimp_matchrecord_Filter, { defraimp_defraimp_itahc_defraimp_matchrecord_ITAHC: defraimp_matchrecord_Result[] }>;
    defraimp_defraimp_itahc_defraimp_rb: WebExpand<defraimp_itahc_Expand, defraimp_itahc_Select, defraimp_itahc_Filter, { defraimp_defraimp_itahc_defraimp_rb: defraimp_itahc_Result[] }>;
  }
  interface defraimp_itahc_FormattedResult {
    createdby_formatted?: string;
    createdon_formatted?: string;
    createdonbehalfby_formatted?: string;
    defraimp_animalcertifiedas_formatted?: string;
    defraimp_certificatestatus_formatted?: string;
    defraimp_commoditytype_formatted?: string;
    defraimp_consigneeaddresscountryid_formatted?: string;
    defraimp_consignoraddresscountryid_formatted?: string;
    defraimp_countryoforiginid_formatted?: string;
    defraimp_declarationsignaturedate_formatted?: string;
    defraimp_departuredatetime_formatted?: string;
    defraimp_officialvetcapacity_formatted?: string;
    defraimp_officialvetsignaturedate_formatted?: string;
    defraimp_placeofdestinationaddresscountryid_formatted?: string;
    defraimp_placeofloadingaddresscountryid_formatted?: string;
    defraimp_placeoforiginharvestaddresscountryid_formatted?: string;
    defraimp_replacedbyid_formatted?: string;
    defraimp_replacesid_formatted?: string;
    defraimp_tracesreceiveddate_formatted?: string;
    defraimp_transporteraddresscountryid_formatted?: string;
    modifiedby_formatted?: string;
    modifiedon_formatted?: string;
    modifiedonbehalfby_formatted?: string;
    overriddencreatedon_formatted?: string;
    ownerid_formatted?: string;
    owningbusinessunit_formatted?: string;
    owningteam_formatted?: string;
    owninguser_formatted?: string;
    statecode_formatted?: string;
    statuscode_formatted?: string;
  }
  interface defraimp_itahc_Result extends defraimp_itahc_Base, defraimp_itahc_Relationships {
    "@odata.etag": string;
    createdby_guid: string | null;
    createdonbehalfby_guid: string | null;
    defraimp_commoditytype_guid: string | null;
    defraimp_consigneeaddresscountryid_guid: string | null;
    defraimp_consignoraddresscountryid_guid: string | null;
    defraimp_countryoforiginid_guid: string | null;
    defraimp_placeofdestinationaddresscountryid_guid: string | null;
    defraimp_placeofloadingaddresscountryid_guid: string | null;
    defraimp_placeoforiginharvestaddresscountryid_guid: string | null;
    defraimp_replacedbyid_guid: string | null;
    defraimp_replacesid_guid: string | null;
    defraimp_transporteraddresscountryid_guid: string | null;
    modifiedby_guid: string | null;
    modifiedonbehalfby_guid: string | null;
    ownerid_guid: string | null;
    owningbusinessunit_guid: string | null;
    owningteam_guid: string | null;
    owninguser_guid: string | null;
  }
  interface defraimp_itahc_RelatedOne {
    defraimp_ReplacedById: WebMappingRetrieve<WebApi.defraimp_itahc_Select,WebApi.defraimp_itahc_Expand,WebApi.defraimp_itahc_Filter,WebApi.defraimp_itahc_Fixed,WebApi.defraimp_itahc_Result,WebApi.defraimp_itahc_FormattedResult>;
    defraimp_ReplacesId: WebMappingRetrieve<WebApi.defraimp_itahc_Select,WebApi.defraimp_itahc_Expand,WebApi.defraimp_itahc_Filter,WebApi.defraimp_itahc_Fixed,WebApi.defraimp_itahc_Result,WebApi.defraimp_itahc_FormattedResult>;
  }
  interface defraimp_itahc_RelatedMany {
    defraimp_defraimp_importapplication_defraimp_itahc: WebMappingRetrieve<WebApi.defraimp_importapplication_Select,WebApi.defraimp_importapplication_Expand,WebApi.defraimp_importapplication_Filter,WebApi.defraimp_importapplication_Fixed,WebApi.defraimp_importapplication_Result,WebApi.defraimp_importapplication_FormattedResult>;
    defraimp_defraimp_itahc_defraimp_importapplication: WebMappingRetrieve<WebApi.defraimp_importapplication_Select,WebApi.defraimp_importapplication_Expand,WebApi.defraimp_importapplication_Filter,WebApi.defraimp_importapplication_Fixed,WebApi.defraimp_importapplication_Result,WebApi.defraimp_importapplication_FormattedResult>;
    defraimp_defraimp_itahc_defraimp_importinspection_RelatedITAHC: WebMappingRetrieve<WebApi.defraimp_importinspection_Select,WebApi.defraimp_importinspection_Expand,WebApi.defraimp_importinspection_Filter,WebApi.defraimp_importinspection_Fixed,WebApi.defraimp_importinspection_Result,WebApi.defraimp_importinspection_FormattedResult>;
    defraimp_defraimp_itahc_defraimp_itahc: WebMappingRetrieve<WebApi.defraimp_itahc_Select,WebApi.defraimp_itahc_Expand,WebApi.defraimp_itahc_Filter,WebApi.defraimp_itahc_Fixed,WebApi.defraimp_itahc_Result,WebApi.defraimp_itahc_FormattedResult>;
    defraimp_defraimp_itahc_defraimp_matchrecord_ITAHC: WebMappingRetrieve<WebApi.defraimp_matchrecord_Select,WebApi.defraimp_matchrecord_Expand,WebApi.defraimp_matchrecord_Filter,WebApi.defraimp_matchrecord_Fixed,WebApi.defraimp_matchrecord_Result,WebApi.defraimp_matchrecord_FormattedResult>;
    defraimp_defraimp_itahc_defraimp_rb: WebMappingRetrieve<WebApi.defraimp_itahc_Select,WebApi.defraimp_itahc_Expand,WebApi.defraimp_itahc_Filter,WebApi.defraimp_itahc_Fixed,WebApi.defraimp_itahc_Result,WebApi.defraimp_itahc_FormattedResult>;
  }
}
interface WebEntitiesRetrieve {
  defraimp_itahcs: WebMappingRetrieve<WebApi.defraimp_itahc_Select,WebApi.defraimp_itahc_Expand,WebApi.defraimp_itahc_Filter,WebApi.defraimp_itahc_Fixed,WebApi.defraimp_itahc_Result,WebApi.defraimp_itahc_FormattedResult>;
}
interface WebEntitiesRelated {
  defraimp_itahcs: WebMappingRelated<WebApi.defraimp_itahc_RelatedOne,WebApi.defraimp_itahc_RelatedMany>;
}
interface WebEntitiesCUDA {
  defraimp_itahcs: WebMappingCUDA<WebApi.defraimp_itahc_Create,WebApi.defraimp_itahc_Update,WebApi.defraimp_itahc_Select>;
}
