declare namespace WebApi {
  interface defraimp_importinspection_Base extends WebEntity {
    createdon?: Date | null;
    defraimp_additionalinfo?: string | null;
    defraimp_amendediv17receiveddate?: Date | null;
    defraimp_comments?: string | null;
    defraimp_compliantfirsttime?: boolean | null;
    defraimp_cphnumber?: string | null;
    defraimp_customernumber?: string | null;
    defraimp_datecompleted?: Date | null;
    defraimp_dateofvisit?: Date | null;
    defraimp_datestartedworking?: Date | null;
    defraimp_datevisitallocated?: Date | null;
    defraimp_failedtovisit?: boolean | null;
    defraimp_fullycompliantvisit?: boolean | null;
    defraimp_id46issued?: boolean | null;
    defraimp_id46issueddate?: Date | null;
    defraimp_importinspectionid?: string | null;
    defraimp_initial?: string | null;
    defraimp_inspectionoutcome?: defraimp_importinspection_defraimp_inspectionoutcome | null;
    defraimp_inspectionoutcomereason?: string | null;
    defraimp_iv16completeddate?: Date | null;
    defraimp_iv16issued?: boolean | null;
    defraimp_iv17chasedate?: Date | null;
    defraimp_iv17feedback?: string | null;
    defraimp_iv17receiveddate?: Date | null;
    defraimp_iv17returnedtofield?: boolean | null;
    defraimp_iv17reviewapproveddate?: Date | null;
    defraimp_name?: string | null;
    defraimp_newvisittoallocate?: boolean | null;
    defraimp_numberofanimalstested?: number | null;
    defraimp_othernoncompliancereason?: string | null;
    defraimp_reactorsorirsidentified?: defraimp_importinspection_defraimp_reactorsorirsidentified | null;
    defraimp_reasonfornoncompliance?: defraimp_reasonfornoncompliance | null;
    defraimp_reasoniv17returned?: string | null;
    defraimp_reasonnotvisited?: string | null;
    defraimp_reasontimeframemissed?: string | null;
    defraimp_replacementhealthcertificaterequested?: boolean | null;
    defraimp_replyfromahodue?: Date | null;
    defraimp_restrictionslifted?: defraimp_importinspection_defraimp_restrictionslifted | null;
    defraimp_restrictionsserved?: defraimp_importinspection_defraimp_restrictionsserved | null;
    defraimp_resultsoftests?: string | null;
    defraimp_sampleresultsreceiveddate?: Date | null;
    defraimp_samplestestsrequired?: defraimp_importinspection_defraimp_samplestestsrequired | null;
    defraimp_samplingrequired?: boolean | null;
    defraimp_samworkschedulenumber?: string | null;
    defraimp_tradeintelligence?: string | null;
    defraimp_visitwithinrequiredtimescale?: boolean | null;
    defraimp_welfareconcerns?: string | null;
    defraimp_wsno?: string | null;
    importsequencenumber?: number | null;
    modifiedon?: Date | null;
    overriddencreatedon?: Date | null;
    statecode?: defraimp_importinspection_statecode | null;
    statuscode?: defraimp_importinspection_statuscode | null;
    timezoneruleversionnumber?: number | null;
    utcconversiontimezonecode?: number | null;
    versionnumber?: number | null;
  }
  interface defraimp_importinspection_Relationships {
    defraimp_IV17ReviewApprovedByID?: SystemUser_Result | null;
    defraimp_NextInspection?: defraimp_importinspection_Result | null;
    defraimp_PreviousInspection?: defraimp_importinspection_Result | null;
    defraimp_RegionAreaAllocatedtoID?: defraimp_apharegion_Result | null;
    defraimp_RelatedITAHC?: defraimp_itahc_Result | null;
    defraimp_RelatedImportApplication?: defraimp_importapplication_Result | null;
    defraimp_defraimp_importinspection_defraimp_importinspection_NextInspection?: defraimp_importinspection_Result[] | null;
    defraimp_defraimp_importinspection_defraimp_importinspection_PreviousInspection?: defraimp_importinspection_Result[] | null;
    defraimp_defraimp_importinspection_defraimp_sample?: defraimp_sampletest_Result[] | null;
    defraimp_importinspection_ProcessSession?: ProcessSession_Result[] | null;
    defraimp_importinspection_SyncErrors?: SyncError_Result[] | null;
  }
  interface defraimp_importinspection extends defraimp_importinspection_Base, defraimp_importinspection_Relationships {
    defraimp_IV17ReviewApprovedByID_bind$systemusers?: string | null;
    defraimp_NextInspection_bind$defraimp_importinspections?: string | null;
    defraimp_PreviousInspection_bind$defraimp_importinspections?: string | null;
    defraimp_RegionAreaAllocatedtoID_bind$defraimp_apharegions?: string | null;
    defraimp_RelatedITAHC_bind$defraimp_itahcs?: string | null;
    defraimp_RelatedImportApplication_bind$defraimp_importapplications?: string | null;
    ownerid_bind$owners?: string | null;
  }
  interface defraimp_importinspection_Create extends defraimp_importinspection {
  }
  interface defraimp_importinspection_Update extends defraimp_importinspection {
  }
  interface defraimp_importinspection_Select {
    createdby_guid: WebAttribute<defraimp_importinspection_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
    createdon: WebAttribute<defraimp_importinspection_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
    createdonbehalfby_guid: WebAttribute<defraimp_importinspection_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
    defraimp_additionalinfo: WebAttribute<defraimp_importinspection_Select, { defraimp_additionalinfo: string | null }, {  }>;
    defraimp_amendediv17receiveddate: WebAttribute<defraimp_importinspection_Select, { defraimp_amendediv17receiveddate: Date | null }, { defraimp_amendediv17receiveddate_formatted?: string }>;
    defraimp_comments: WebAttribute<defraimp_importinspection_Select, { defraimp_comments: string | null }, {  }>;
    defraimp_compliantfirsttime: WebAttribute<defraimp_importinspection_Select, { defraimp_compliantfirsttime: boolean | null }, {  }>;
    defraimp_cphnumber: WebAttribute<defraimp_importinspection_Select, { defraimp_cphnumber: string | null }, {  }>;
    defraimp_customernumber: WebAttribute<defraimp_importinspection_Select, { defraimp_customernumber: string | null }, {  }>;
    defraimp_datecompleted: WebAttribute<defraimp_importinspection_Select, { defraimp_datecompleted: Date | null }, { defraimp_datecompleted_formatted?: string }>;
    defraimp_dateofvisit: WebAttribute<defraimp_importinspection_Select, { defraimp_dateofvisit: Date | null }, { defraimp_dateofvisit_formatted?: string }>;
    defraimp_datestartedworking: WebAttribute<defraimp_importinspection_Select, { defraimp_datestartedworking: Date | null }, { defraimp_datestartedworking_formatted?: string }>;
    defraimp_datevisitallocated: WebAttribute<defraimp_importinspection_Select, { defraimp_datevisitallocated: Date | null }, { defraimp_datevisitallocated_formatted?: string }>;
    defraimp_failedtovisit: WebAttribute<defraimp_importinspection_Select, { defraimp_failedtovisit: boolean | null }, {  }>;
    defraimp_fullycompliantvisit: WebAttribute<defraimp_importinspection_Select, { defraimp_fullycompliantvisit: boolean | null }, {  }>;
    defraimp_id46issued: WebAttribute<defraimp_importinspection_Select, { defraimp_id46issued: boolean | null }, {  }>;
    defraimp_id46issueddate: WebAttribute<defraimp_importinspection_Select, { defraimp_id46issueddate: Date | null }, { defraimp_id46issueddate_formatted?: string }>;
    defraimp_importinspectionid: WebAttribute<defraimp_importinspection_Select, { defraimp_importinspectionid: string | null }, {  }>;
    defraimp_initial: WebAttribute<defraimp_importinspection_Select, { defraimp_initial: string | null }, {  }>;
    defraimp_inspectionoutcome: WebAttribute<defraimp_importinspection_Select, { defraimp_inspectionoutcome: defraimp_importinspection_defraimp_inspectionoutcome | null }, { defraimp_inspectionoutcome_formatted?: string }>;
    defraimp_inspectionoutcomereason: WebAttribute<defraimp_importinspection_Select, { defraimp_inspectionoutcomereason: string | null }, {  }>;
    defraimp_iv16completeddate: WebAttribute<defraimp_importinspection_Select, { defraimp_iv16completeddate: Date | null }, { defraimp_iv16completeddate_formatted?: string }>;
    defraimp_iv16issued: WebAttribute<defraimp_importinspection_Select, { defraimp_iv16issued: boolean | null }, {  }>;
    defraimp_iv17chasedate: WebAttribute<defraimp_importinspection_Select, { defraimp_iv17chasedate: Date | null }, { defraimp_iv17chasedate_formatted?: string }>;
    defraimp_iv17feedback: WebAttribute<defraimp_importinspection_Select, { defraimp_iv17feedback: string | null }, {  }>;
    defraimp_iv17receiveddate: WebAttribute<defraimp_importinspection_Select, { defraimp_iv17receiveddate: Date | null }, { defraimp_iv17receiveddate_formatted?: string }>;
    defraimp_iv17returnedtofield: WebAttribute<defraimp_importinspection_Select, { defraimp_iv17returnedtofield: boolean | null }, {  }>;
    defraimp_iv17reviewapprovedbyid_guid: WebAttribute<defraimp_importinspection_Select, { defraimp_iv17reviewapprovedbyid_guid: string | null }, { defraimp_iv17reviewapprovedbyid_formatted?: string }>;
    defraimp_iv17reviewapproveddate: WebAttribute<defraimp_importinspection_Select, { defraimp_iv17reviewapproveddate: Date | null }, { defraimp_iv17reviewapproveddate_formatted?: string }>;
    defraimp_name: WebAttribute<defraimp_importinspection_Select, { defraimp_name: string | null }, {  }>;
    defraimp_newvisittoallocate: WebAttribute<defraimp_importinspection_Select, { defraimp_newvisittoallocate: boolean | null }, {  }>;
    defraimp_nextinspection_guid: WebAttribute<defraimp_importinspection_Select, { defraimp_nextinspection_guid: string | null }, { defraimp_nextinspection_formatted?: string }>;
    defraimp_numberofanimalstested: WebAttribute<defraimp_importinspection_Select, { defraimp_numberofanimalstested: number | null }, {  }>;
    defraimp_othernoncompliancereason: WebAttribute<defraimp_importinspection_Select, { defraimp_othernoncompliancereason: string | null }, {  }>;
    defraimp_previousinspection_guid: WebAttribute<defraimp_importinspection_Select, { defraimp_previousinspection_guid: string | null }, { defraimp_previousinspection_formatted?: string }>;
    defraimp_reactorsorirsidentified: WebAttribute<defraimp_importinspection_Select, { defraimp_reactorsorirsidentified: defraimp_importinspection_defraimp_reactorsorirsidentified | null }, { defraimp_reactorsorirsidentified_formatted?: string }>;
    defraimp_reasonfornoncompliance: WebAttribute<defraimp_importinspection_Select, { defraimp_reasonfornoncompliance: defraimp_reasonfornoncompliance | null }, { defraimp_reasonfornoncompliance_formatted?: string }>;
    defraimp_reasoniv17returned: WebAttribute<defraimp_importinspection_Select, { defraimp_reasoniv17returned: string | null }, {  }>;
    defraimp_reasonnotvisited: WebAttribute<defraimp_importinspection_Select, { defraimp_reasonnotvisited: string | null }, {  }>;
    defraimp_reasontimeframemissed: WebAttribute<defraimp_importinspection_Select, { defraimp_reasontimeframemissed: string | null }, {  }>;
    defraimp_regionareaallocatedtoid_guid: WebAttribute<defraimp_importinspection_Select, { defraimp_regionareaallocatedtoid_guid: string | null }, { defraimp_regionareaallocatedtoid_formatted?: string }>;
    defraimp_relatedimportapplication_guid: WebAttribute<defraimp_importinspection_Select, { defraimp_relatedimportapplication_guid: string | null }, { defraimp_relatedimportapplication_formatted?: string }>;
    defraimp_relateditahc_guid: WebAttribute<defraimp_importinspection_Select, { defraimp_relateditahc_guid: string | null }, { defraimp_relateditahc_formatted?: string }>;
    defraimp_replacementhealthcertificaterequested: WebAttribute<defraimp_importinspection_Select, { defraimp_replacementhealthcertificaterequested: boolean | null }, {  }>;
    defraimp_replyfromahodue: WebAttribute<defraimp_importinspection_Select, { defraimp_replyfromahodue: Date | null }, { defraimp_replyfromahodue_formatted?: string }>;
    defraimp_restrictionslifted: WebAttribute<defraimp_importinspection_Select, { defraimp_restrictionslifted: defraimp_importinspection_defraimp_restrictionslifted | null }, { defraimp_restrictionslifted_formatted?: string }>;
    defraimp_restrictionsserved: WebAttribute<defraimp_importinspection_Select, { defraimp_restrictionsserved: defraimp_importinspection_defraimp_restrictionsserved | null }, { defraimp_restrictionsserved_formatted?: string }>;
    defraimp_resultsoftests: WebAttribute<defraimp_importinspection_Select, { defraimp_resultsoftests: string | null }, {  }>;
    defraimp_sampleresultsreceiveddate: WebAttribute<defraimp_importinspection_Select, { defraimp_sampleresultsreceiveddate: Date | null }, { defraimp_sampleresultsreceiveddate_formatted?: string }>;
    defraimp_samplestestsrequired: WebAttribute<defraimp_importinspection_Select, { defraimp_samplestestsrequired: defraimp_importinspection_defraimp_samplestestsrequired | null }, { defraimp_samplestestsrequired_formatted?: string }>;
    defraimp_samplingrequired: WebAttribute<defraimp_importinspection_Select, { defraimp_samplingrequired: boolean | null }, {  }>;
    defraimp_samworkschedulenumber: WebAttribute<defraimp_importinspection_Select, { defraimp_samworkschedulenumber: string | null }, {  }>;
    defraimp_tradeintelligence: WebAttribute<defraimp_importinspection_Select, { defraimp_tradeintelligence: string | null }, {  }>;
    defraimp_visitwithinrequiredtimescale: WebAttribute<defraimp_importinspection_Select, { defraimp_visitwithinrequiredtimescale: boolean | null }, {  }>;
    defraimp_welfareconcerns: WebAttribute<defraimp_importinspection_Select, { defraimp_welfareconcerns: string | null }, {  }>;
    defraimp_wsno: WebAttribute<defraimp_importinspection_Select, { defraimp_wsno: string | null }, {  }>;
    importsequencenumber: WebAttribute<defraimp_importinspection_Select, { importsequencenumber: number | null }, {  }>;
    modifiedby_guid: WebAttribute<defraimp_importinspection_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
    modifiedon: WebAttribute<defraimp_importinspection_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
    modifiedonbehalfby_guid: WebAttribute<defraimp_importinspection_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
    overriddencreatedon: WebAttribute<defraimp_importinspection_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
    ownerid_guid: WebAttribute<defraimp_importinspection_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
    owningbusinessunit_guid: WebAttribute<defraimp_importinspection_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
    owningteam_guid: WebAttribute<defraimp_importinspection_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
    owninguser_guid: WebAttribute<defraimp_importinspection_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
    statecode: WebAttribute<defraimp_importinspection_Select, { statecode: defraimp_importinspection_statecode | null }, { statecode_formatted?: string }>;
    statuscode: WebAttribute<defraimp_importinspection_Select, { statuscode: defraimp_importinspection_statuscode | null }, { statuscode_formatted?: string }>;
    timezoneruleversionnumber: WebAttribute<defraimp_importinspection_Select, { timezoneruleversionnumber: number | null }, {  }>;
    utcconversiontimezonecode: WebAttribute<defraimp_importinspection_Select, { utcconversiontimezonecode: number | null }, {  }>;
    versionnumber: WebAttribute<defraimp_importinspection_Select, { versionnumber: number | null }, {  }>;
  }
  interface defraimp_importinspection_Filter {
    createdby_guid: XQW.Guid;
    createdon: Date;
    createdonbehalfby_guid: XQW.Guid;
    defraimp_additionalinfo: string;
    defraimp_amendediv17receiveddate: Date;
    defraimp_comments: string;
    defraimp_compliantfirsttime: boolean;
    defraimp_cphnumber: string;
    defraimp_customernumber: string;
    defraimp_datecompleted: Date;
    defraimp_dateofvisit: Date;
    defraimp_datestartedworking: Date;
    defraimp_datevisitallocated: Date;
    defraimp_failedtovisit: boolean;
    defraimp_fullycompliantvisit: boolean;
    defraimp_id46issued: boolean;
    defraimp_id46issueddate: Date;
    defraimp_importinspectionid: XQW.Guid;
    defraimp_initial: string;
    defraimp_inspectionoutcome: defraimp_importinspection_defraimp_inspectionoutcome;
    defraimp_inspectionoutcomereason: string;
    defraimp_iv16completeddate: Date;
    defraimp_iv16issued: boolean;
    defraimp_iv17chasedate: Date;
    defraimp_iv17feedback: string;
    defraimp_iv17receiveddate: Date;
    defraimp_iv17returnedtofield: boolean;
    defraimp_iv17reviewapprovedbyid_guid: XQW.Guid;
    defraimp_iv17reviewapproveddate: Date;
    defraimp_name: string;
    defraimp_newvisittoallocate: boolean;
    defraimp_nextinspection_guid: XQW.Guid;
    defraimp_numberofanimalstested: number;
    defraimp_othernoncompliancereason: string;
    defraimp_previousinspection_guid: XQW.Guid;
    defraimp_reactorsorirsidentified: defraimp_importinspection_defraimp_reactorsorirsidentified;
    defraimp_reasonfornoncompliance: defraimp_reasonfornoncompliance;
    defraimp_reasoniv17returned: string;
    defraimp_reasonnotvisited: string;
    defraimp_reasontimeframemissed: string;
    defraimp_regionareaallocatedtoid_guid: XQW.Guid;
    defraimp_relatedimportapplication_guid: XQW.Guid;
    defraimp_relateditahc_guid: XQW.Guid;
    defraimp_replacementhealthcertificaterequested: boolean;
    defraimp_replyfromahodue: Date;
    defraimp_restrictionslifted: defraimp_importinspection_defraimp_restrictionslifted;
    defraimp_restrictionsserved: defraimp_importinspection_defraimp_restrictionsserved;
    defraimp_resultsoftests: string;
    defraimp_sampleresultsreceiveddate: Date;
    defraimp_samplestestsrequired: defraimp_importinspection_defraimp_samplestestsrequired;
    defraimp_samplingrequired: boolean;
    defraimp_samworkschedulenumber: string;
    defraimp_tradeintelligence: string;
    defraimp_visitwithinrequiredtimescale: boolean;
    defraimp_welfareconcerns: string;
    defraimp_wsno: string;
    importsequencenumber: number;
    modifiedby_guid: XQW.Guid;
    modifiedon: Date;
    modifiedonbehalfby_guid: XQW.Guid;
    overriddencreatedon: Date;
    ownerid_guid: XQW.Guid;
    owningbusinessunit_guid: XQW.Guid;
    owningteam_guid: XQW.Guid;
    owninguser_guid: XQW.Guid;
    statecode: defraimp_importinspection_statecode;
    statuscode: defraimp_importinspection_statuscode;
    timezoneruleversionnumber: number;
    utcconversiontimezonecode: number;
    versionnumber: number;
  }
  interface defraimp_importinspection_Expand {
    createdby: WebExpand<defraimp_importinspection_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
    createdonbehalfby: WebExpand<defraimp_importinspection_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
    defraimp_IV17ReviewApprovedByID: WebExpand<defraimp_importinspection_Expand, SystemUser_Select, SystemUser_Filter, { defraimp_IV17ReviewApprovedByID: SystemUser_Result }>;
    defraimp_NextInspection: WebExpand<defraimp_importinspection_Expand, defraimp_importinspection_Select, defraimp_importinspection_Filter, { defraimp_NextInspection: defraimp_importinspection_Result }>;
    defraimp_PreviousInspection: WebExpand<defraimp_importinspection_Expand, defraimp_importinspection_Select, defraimp_importinspection_Filter, { defraimp_PreviousInspection: defraimp_importinspection_Result }>;
    defraimp_RegionAreaAllocatedtoID: WebExpand<defraimp_importinspection_Expand, defraimp_apharegion_Select, defraimp_apharegion_Filter, { defraimp_RegionAreaAllocatedtoID: defraimp_apharegion_Result }>;
    defraimp_RelatedITAHC: WebExpand<defraimp_importinspection_Expand, defraimp_itahc_Select, defraimp_itahc_Filter, { defraimp_RelatedITAHC: defraimp_itahc_Result }>;
    defraimp_RelatedImportApplication: WebExpand<defraimp_importinspection_Expand, defraimp_importapplication_Select, defraimp_importapplication_Filter, { defraimp_RelatedImportApplication: defraimp_importapplication_Result }>;
    defraimp_defraimp_importinspection_defraimp_importinspection_NextInspection: WebExpand<defraimp_importinspection_Expand, defraimp_importinspection_Select, defraimp_importinspection_Filter, { defraimp_defraimp_importinspection_defraimp_importinspection_NextInspection: defraimp_importinspection_Result[] }>;
    defraimp_defraimp_importinspection_defraimp_importinspection_PreviousInspection: WebExpand<defraimp_importinspection_Expand, defraimp_importinspection_Select, defraimp_importinspection_Filter, { defraimp_defraimp_importinspection_defraimp_importinspection_PreviousInspection: defraimp_importinspection_Result[] }>;
    defraimp_defraimp_importinspection_defraimp_sample: WebExpand<defraimp_importinspection_Expand, defraimp_sampletest_Select, defraimp_sampletest_Filter, { defraimp_defraimp_importinspection_defraimp_sample: defraimp_sampletest_Result[] }>;
    defraimp_importinspection_ProcessSession: WebExpand<defraimp_importinspection_Expand, ProcessSession_Select, ProcessSession_Filter, { defraimp_importinspection_ProcessSession: ProcessSession_Result[] }>;
    defraimp_importinspection_SyncErrors: WebExpand<defraimp_importinspection_Expand, SyncError_Select, SyncError_Filter, { defraimp_importinspection_SyncErrors: SyncError_Result[] }>;
    modifiedby: WebExpand<defraimp_importinspection_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
    modifiedonbehalfby: WebExpand<defraimp_importinspection_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
    owningteam: WebExpand<defraimp_importinspection_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
    owninguser: WebExpand<defraimp_importinspection_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
  }
  interface defraimp_importinspection_FormattedResult {
    createdby_formatted?: string;
    createdon_formatted?: string;
    createdonbehalfby_formatted?: string;
    defraimp_amendediv17receiveddate_formatted?: string;
    defraimp_datecompleted_formatted?: string;
    defraimp_dateofvisit_formatted?: string;
    defraimp_datestartedworking_formatted?: string;
    defraimp_datevisitallocated_formatted?: string;
    defraimp_id46issueddate_formatted?: string;
    defraimp_inspectionoutcome_formatted?: string;
    defraimp_iv16completeddate_formatted?: string;
    defraimp_iv17chasedate_formatted?: string;
    defraimp_iv17receiveddate_formatted?: string;
    defraimp_iv17reviewapprovedbyid_formatted?: string;
    defraimp_iv17reviewapproveddate_formatted?: string;
    defraimp_nextinspection_formatted?: string;
    defraimp_previousinspection_formatted?: string;
    defraimp_reactorsorirsidentified_formatted?: string;
    defraimp_reasonfornoncompliance_formatted?: string;
    defraimp_regionareaallocatedtoid_formatted?: string;
    defraimp_relatedimportapplication_formatted?: string;
    defraimp_relateditahc_formatted?: string;
    defraimp_replyfromahodue_formatted?: string;
    defraimp_restrictionslifted_formatted?: string;
    defraimp_restrictionsserved_formatted?: string;
    defraimp_sampleresultsreceiveddate_formatted?: string;
    defraimp_samplestestsrequired_formatted?: string;
    modifiedby_formatted?: string;
    modifiedon_formatted?: string;
    modifiedonbehalfby_formatted?: string;
    overriddencreatedon_formatted?: string;
    ownerid_formatted?: string;
    owningbusinessunit_formatted?: string;
    owningteam_formatted?: string;
    owninguser_formatted?: string;
    statecode_formatted?: string;
    statuscode_formatted?: string;
  }
  interface defraimp_importinspection_Result extends defraimp_importinspection_Base, defraimp_importinspection_Relationships {
    "@odata.etag": string;
    createdby_guid: string | null;
    createdonbehalfby_guid: string | null;
    defraimp_iv17reviewapprovedbyid_guid: string | null;
    defraimp_nextinspection_guid: string | null;
    defraimp_previousinspection_guid: string | null;
    defraimp_regionareaallocatedtoid_guid: string | null;
    defraimp_relatedimportapplication_guid: string | null;
    defraimp_relateditahc_guid: string | null;
    modifiedby_guid: string | null;
    modifiedonbehalfby_guid: string | null;
    ownerid_guid: string | null;
    owningbusinessunit_guid: string | null;
    owningteam_guid: string | null;
    owninguser_guid: string | null;
  }
  interface defraimp_importinspection_RelatedOne {
    createdby: WebMappingRetrieve<WebApi.SystemUser_Select,WebApi.SystemUser_Expand,WebApi.SystemUser_Filter,WebApi.SystemUser_Fixed,WebApi.SystemUser_Result,WebApi.SystemUser_FormattedResult>;
    createdonbehalfby: WebMappingRetrieve<WebApi.SystemUser_Select,WebApi.SystemUser_Expand,WebApi.SystemUser_Filter,WebApi.SystemUser_Fixed,WebApi.SystemUser_Result,WebApi.SystemUser_FormattedResult>;
    defraimp_IV17ReviewApprovedByID: WebMappingRetrieve<WebApi.SystemUser_Select,WebApi.SystemUser_Expand,WebApi.SystemUser_Filter,WebApi.SystemUser_Fixed,WebApi.SystemUser_Result,WebApi.SystemUser_FormattedResult>;
    defraimp_NextInspection: WebMappingRetrieve<WebApi.defraimp_importinspection_Select,WebApi.defraimp_importinspection_Expand,WebApi.defraimp_importinspection_Filter,WebApi.defraimp_importinspection_Fixed,WebApi.defraimp_importinspection_Result,WebApi.defraimp_importinspection_FormattedResult>;
    defraimp_PreviousInspection: WebMappingRetrieve<WebApi.defraimp_importinspection_Select,WebApi.defraimp_importinspection_Expand,WebApi.defraimp_importinspection_Filter,WebApi.defraimp_importinspection_Fixed,WebApi.defraimp_importinspection_Result,WebApi.defraimp_importinspection_FormattedResult>;
    defraimp_RegionAreaAllocatedtoID: WebMappingRetrieve<WebApi.defraimp_apharegion_Select,WebApi.defraimp_apharegion_Expand,WebApi.defraimp_apharegion_Filter,WebApi.defraimp_apharegion_Fixed,WebApi.defraimp_apharegion_Result,WebApi.defraimp_apharegion_FormattedResult>;
    defraimp_RelatedITAHC: WebMappingRetrieve<WebApi.defraimp_itahc_Select,WebApi.defraimp_itahc_Expand,WebApi.defraimp_itahc_Filter,WebApi.defraimp_itahc_Fixed,WebApi.defraimp_itahc_Result,WebApi.defraimp_itahc_FormattedResult>;
    defraimp_RelatedImportApplication: WebMappingRetrieve<WebApi.defraimp_importapplication_Select,WebApi.defraimp_importapplication_Expand,WebApi.defraimp_importapplication_Filter,WebApi.defraimp_importapplication_Fixed,WebApi.defraimp_importapplication_Result,WebApi.defraimp_importapplication_FormattedResult>;
    modifiedby: WebMappingRetrieve<WebApi.SystemUser_Select,WebApi.SystemUser_Expand,WebApi.SystemUser_Filter,WebApi.SystemUser_Fixed,WebApi.SystemUser_Result,WebApi.SystemUser_FormattedResult>;
    modifiedonbehalfby: WebMappingRetrieve<WebApi.SystemUser_Select,WebApi.SystemUser_Expand,WebApi.SystemUser_Filter,WebApi.SystemUser_Fixed,WebApi.SystemUser_Result,WebApi.SystemUser_FormattedResult>;
    owningteam: WebMappingRetrieve<WebApi.Team_Select,WebApi.Team_Expand,WebApi.Team_Filter,WebApi.Team_Fixed,WebApi.Team_Result,WebApi.Team_FormattedResult>;
    owninguser: WebMappingRetrieve<WebApi.SystemUser_Select,WebApi.SystemUser_Expand,WebApi.SystemUser_Filter,WebApi.SystemUser_Fixed,WebApi.SystemUser_Result,WebApi.SystemUser_FormattedResult>;
  }
  interface defraimp_importinspection_RelatedMany {
    defraimp_defraimp_importinspection_defraimp_importinspection_NextInspection: WebMappingRetrieve<WebApi.defraimp_importinspection_Select,WebApi.defraimp_importinspection_Expand,WebApi.defraimp_importinspection_Filter,WebApi.defraimp_importinspection_Fixed,WebApi.defraimp_importinspection_Result,WebApi.defraimp_importinspection_FormattedResult>;
    defraimp_defraimp_importinspection_defraimp_importinspection_PreviousInspection: WebMappingRetrieve<WebApi.defraimp_importinspection_Select,WebApi.defraimp_importinspection_Expand,WebApi.defraimp_importinspection_Filter,WebApi.defraimp_importinspection_Fixed,WebApi.defraimp_importinspection_Result,WebApi.defraimp_importinspection_FormattedResult>;
    defraimp_defraimp_importinspection_defraimp_sample: WebMappingRetrieve<WebApi.defraimp_sampletest_Select,WebApi.defraimp_sampletest_Expand,WebApi.defraimp_sampletest_Filter,WebApi.defraimp_sampletest_Fixed,WebApi.defraimp_sampletest_Result,WebApi.defraimp_sampletest_FormattedResult>;
    defraimp_importinspection_ProcessSession: WebMappingRetrieve<WebApi.ProcessSession_Select,WebApi.ProcessSession_Expand,WebApi.ProcessSession_Filter,WebApi.ProcessSession_Fixed,WebApi.ProcessSession_Result,WebApi.ProcessSession_FormattedResult>;
    defraimp_importinspection_SyncErrors: WebMappingRetrieve<WebApi.SyncError_Select,WebApi.SyncError_Expand,WebApi.SyncError_Filter,WebApi.SyncError_Fixed,WebApi.SyncError_Result,WebApi.SyncError_FormattedResult>;
  }
}
interface WebEntitiesRetrieve {
  defraimp_importinspections: WebMappingRetrieve<WebApi.defraimp_importinspection_Select,WebApi.defraimp_importinspection_Expand,WebApi.defraimp_importinspection_Filter,WebApi.defraimp_importinspection_Fixed,WebApi.defraimp_importinspection_Result,WebApi.defraimp_importinspection_FormattedResult>;
}
interface WebEntitiesRelated {
  defraimp_importinspections: WebMappingRelated<WebApi.defraimp_importinspection_RelatedOne,WebApi.defraimp_importinspection_RelatedMany>;
}
interface WebEntitiesCUDA {
  defraimp_importinspections: WebMappingCUDA<WebApi.defraimp_importinspection_Create,WebApi.defraimp_importinspection_Update,WebApi.defraimp_importinspection_Select>;
}
