declare namespace WebApi {
  interface defraimp_importnotification_Base extends WebEntity {
    createdon?: Date | null;
    defraimp_charityaddresscity?: string | null;
    defraimp_charityaddressline1?: string | null;
    defraimp_charityaddressline2?: string | null;
    defraimp_charityaddressline3?: string | null;
    defraimp_charityaddresspostcode?: string | null;
    defraimp_charityemail?: string | null;
    defraimp_charityname?: string | null;
    defraimp_charitytelephone?: string | null;
    defraimp_cphnumber?: string | null;
    defraimp_datenotificationreceived?: Date | null;
    defraimp_dateofimport?: Date | null;
    defraimp_importeraddresscity?: string | null;
    defraimp_importeraddressline1?: string | null;
    defraimp_importeraddressline2?: string | null;
    defraimp_importeraddressline3?: string | null;
    defraimp_importeraddresspostcode?: string | null;
    defraimp_importeremail?: string | null;
    defraimp_importername?: string | null;
    defraimp_importertelephone?: string | null;
    defraimp_importnotificationid?: string | null;
    defraimp_ins?: string | null;
    defraimp_name?: string | null;
    defraimp_notificationreceivedintimeframe?: boolean | null;
    defraimp_originaddress?: string | null;
    defraimp_permanentdestinationaddresscity?: string | null;
    defraimp_permanentdestinationaddressline1?: string | null;
    defraimp_permanentdestinationaddressline2?: string | null;
    defraimp_permanentdestinationaddressline3?: string | null;
    defraimp_permanentdestinationaddresspostcode?: string | null;
    defraimp_permanentdestinationcontactname?: string | null;
    defraimp_permanentdestinationemail?: string | null;
    defraimp_permanentdestinationtelephone?: string | null;
    defraimp_placeofdestinationaddresscity?: string | null;
    defraimp_placeofdestinationaddressline1?: string | null;
    defraimp_placeofdestinationaddressline2?: string | null;
    defraimp_placeofdestinationaddressline3?: string | null;
    defraimp_placeofdestinationaddresspostcode?: string | null;
    defraimp_placeofdestinationcontactname?: string | null;
    defraimp_placeofdestinationemail?: string | null;
    defraimp_placeofdestinationtelephone?: string | null;
    defraimp_pointofentry?: string | null;
    defraimp_referencenumber?: string | null;
    defraimp_speciesproductname?: string | null;
    defraimp_transporteraddress?: string | null;
    defraimp_transporteremail?: string | null;
    defraimp_transportername?: string | null;
    defraimp_transportertelephone?: string | null;
    importsequencenumber?: number | null;
    modifiedon?: Date | null;
    overriddencreatedon?: Date | null;
    statecode?: defraimp_importnotification_statecode | null;
    statuscode?: defraimp_importnotification_statuscode | null;
    timezoneruleversionnumber?: number | null;
    utcconversiontimezonecode?: number | null;
    versionnumber?: number | null;
  }
  interface defraimp_importnotification_Relationships {
    defraimp_CharityAddressCountry?: defra_country_Result | null;
    defraimp_CommodityTypeId?: defraexp_commoditytype_Result | null;
    defraimp_CountryofOriginId?: defra_country_Result | null;
    defraimp_ImporterAddressCountryid?: defra_country_Result | null;
    defraimp_PermanentDestinationAddressCountryid?: defra_country_Result | null;
    defraimp_PlaceofDestinationAddressCountryid?: defra_country_Result | null;
    defraimp_defraimp_importapplication_defraimp_impor?: defraimp_importapplication_Result[] | null;
    defraimp_defraimp_importnotification_defraimp_impo?: defraimp_importapplication_Result[] | null;
    defraimp_defraimp_importnotification_defraimp_importnotification_replacedbyid?: defraimp_importnotification_Result[] | null;
    defraimp_defraimp_importnotification_defraimp_importnotification_replacesid?: defraimp_importnotification_Result[] | null;
    defraimp_importnotification_ProcessSession?: ProcessSession_Result[] | null;
    defraimp_importnotification_SyncErrors?: SyncError_Result[] | null;
  }
  interface defraimp_importnotification extends defraimp_importnotification_Base, defraimp_importnotification_Relationships {
    defraimp_CharityAddressCountry_bind$defra_countries?: string | null;
    defraimp_CommodityTypeId_bind$defraexp_commoditytypes?: string | null;
    defraimp_CountryofOriginId_bind$defra_countries?: string | null;
    defraimp_ImporterAddressCountryid_bind$defra_countries?: string | null;
    defraimp_PermanentDestinationAddressCountryid_bind$defra_countries?: string | null;
    defraimp_PlaceofDestinationAddressCountryid_bind$defra_countries?: string | null;
    defraimp_replacedbyid_bind$defraimp_importnotifications?: string | null;
    defraimp_replacesid_bind$defraimp_importnotifications?: string | null;
    ownerid_bind$owners?: string | null;
  }
  interface defraimp_importnotification_Create extends defraimp_importnotification {
  }
  interface defraimp_importnotification_Update extends defraimp_importnotification {
  }
  interface defraimp_importnotification_Select {
    createdby_guid: WebAttribute<defraimp_importnotification_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
    createdon: WebAttribute<defraimp_importnotification_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
    createdonbehalfby_guid: WebAttribute<defraimp_importnotification_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
    defraimp_charityaddresscity: WebAttribute<defraimp_importnotification_Select, { defraimp_charityaddresscity: string | null }, {  }>;
    defraimp_charityaddresscountry_guid: WebAttribute<defraimp_importnotification_Select, { defraimp_charityaddresscountry_guid: string | null }, { defraimp_charityaddresscountry_formatted?: string }>;
    defraimp_charityaddressline1: WebAttribute<defraimp_importnotification_Select, { defraimp_charityaddressline1: string | null }, {  }>;
    defraimp_charityaddressline2: WebAttribute<defraimp_importnotification_Select, { defraimp_charityaddressline2: string | null }, {  }>;
    defraimp_charityaddressline3: WebAttribute<defraimp_importnotification_Select, { defraimp_charityaddressline3: string | null }, {  }>;
    defraimp_charityaddresspostcode: WebAttribute<defraimp_importnotification_Select, { defraimp_charityaddresspostcode: string | null }, {  }>;
    defraimp_charityemail: WebAttribute<defraimp_importnotification_Select, { defraimp_charityemail: string | null }, {  }>;
    defraimp_charityname: WebAttribute<defraimp_importnotification_Select, { defraimp_charityname: string | null }, {  }>;
    defraimp_charitytelephone: WebAttribute<defraimp_importnotification_Select, { defraimp_charitytelephone: string | null }, {  }>;
    defraimp_commoditytypeid_guid: WebAttribute<defraimp_importnotification_Select, { defraimp_commoditytypeid_guid: string | null }, { defraimp_commoditytypeid_formatted?: string }>;
    defraimp_countryoforiginid_guid: WebAttribute<defraimp_importnotification_Select, { defraimp_countryoforiginid_guid: string | null }, { defraimp_countryoforiginid_formatted?: string }>;
    defraimp_cphnumber: WebAttribute<defraimp_importnotification_Select, { defraimp_cphnumber: string | null }, {  }>;
    defraimp_datenotificationreceived: WebAttribute<defraimp_importnotification_Select, { defraimp_datenotificationreceived: Date | null }, { defraimp_datenotificationreceived_formatted?: string }>;
    defraimp_dateofimport: WebAttribute<defraimp_importnotification_Select, { defraimp_dateofimport: Date | null }, { defraimp_dateofimport_formatted?: string }>;
    defraimp_importeraddresscity: WebAttribute<defraimp_importnotification_Select, { defraimp_importeraddresscity: string | null }, {  }>;
    defraimp_importeraddresscountryid_guid: WebAttribute<defraimp_importnotification_Select, { defraimp_importeraddresscountryid_guid: string | null }, { defraimp_importeraddresscountryid_formatted?: string }>;
    defraimp_importeraddressline1: WebAttribute<defraimp_importnotification_Select, { defraimp_importeraddressline1: string | null }, {  }>;
    defraimp_importeraddressline2: WebAttribute<defraimp_importnotification_Select, { defraimp_importeraddressline2: string | null }, {  }>;
    defraimp_importeraddressline3: WebAttribute<defraimp_importnotification_Select, { defraimp_importeraddressline3: string | null }, {  }>;
    defraimp_importeraddresspostcode: WebAttribute<defraimp_importnotification_Select, { defraimp_importeraddresspostcode: string | null }, {  }>;
    defraimp_importeremail: WebAttribute<defraimp_importnotification_Select, { defraimp_importeremail: string | null }, {  }>;
    defraimp_importername: WebAttribute<defraimp_importnotification_Select, { defraimp_importername: string | null }, {  }>;
    defraimp_importertelephone: WebAttribute<defraimp_importnotification_Select, { defraimp_importertelephone: string | null }, {  }>;
    defraimp_importnotificationid: WebAttribute<defraimp_importnotification_Select, { defraimp_importnotificationid: string | null }, {  }>;
    defraimp_ins: WebAttribute<defraimp_importnotification_Select, { defraimp_ins: string | null }, {  }>;
    defraimp_name: WebAttribute<defraimp_importnotification_Select, { defraimp_name: string | null }, {  }>;
    defraimp_notificationreceivedintimeframe: WebAttribute<defraimp_importnotification_Select, { defraimp_notificationreceivedintimeframe: boolean | null }, {  }>;
    defraimp_originaddress: WebAttribute<defraimp_importnotification_Select, { defraimp_originaddress: string | null }, {  }>;
    defraimp_permanentdestinationaddresscity: WebAttribute<defraimp_importnotification_Select, { defraimp_permanentdestinationaddresscity: string | null }, {  }>;
    defraimp_permanentdestinationaddresscountryid_guid: WebAttribute<defraimp_importnotification_Select, { defraimp_permanentdestinationaddresscountryid_guid: string | null }, { defraimp_permanentdestinationaddresscountryid_formatted?: string }>;
    defraimp_permanentdestinationaddressline1: WebAttribute<defraimp_importnotification_Select, { defraimp_permanentdestinationaddressline1: string | null }, {  }>;
    defraimp_permanentdestinationaddressline2: WebAttribute<defraimp_importnotification_Select, { defraimp_permanentdestinationaddressline2: string | null }, {  }>;
    defraimp_permanentdestinationaddressline3: WebAttribute<defraimp_importnotification_Select, { defraimp_permanentdestinationaddressline3: string | null }, {  }>;
    defraimp_permanentdestinationaddresspostcode: WebAttribute<defraimp_importnotification_Select, { defraimp_permanentdestinationaddresspostcode: string | null }, {  }>;
    defraimp_permanentdestinationcontactname: WebAttribute<defraimp_importnotification_Select, { defraimp_permanentdestinationcontactname: string | null }, {  }>;
    defraimp_permanentdestinationemail: WebAttribute<defraimp_importnotification_Select, { defraimp_permanentdestinationemail: string | null }, {  }>;
    defraimp_permanentdestinationtelephone: WebAttribute<defraimp_importnotification_Select, { defraimp_permanentdestinationtelephone: string | null }, {  }>;
    defraimp_placeofdestinationaddresscity: WebAttribute<defraimp_importnotification_Select, { defraimp_placeofdestinationaddresscity: string | null }, {  }>;
    defraimp_placeofdestinationaddresscountryid_guid: WebAttribute<defraimp_importnotification_Select, { defraimp_placeofdestinationaddresscountryid_guid: string | null }, { defraimp_placeofdestinationaddresscountryid_formatted?: string }>;
    defraimp_placeofdestinationaddressline1: WebAttribute<defraimp_importnotification_Select, { defraimp_placeofdestinationaddressline1: string | null }, {  }>;
    defraimp_placeofdestinationaddressline2: WebAttribute<defraimp_importnotification_Select, { defraimp_placeofdestinationaddressline2: string | null }, {  }>;
    defraimp_placeofdestinationaddressline3: WebAttribute<defraimp_importnotification_Select, { defraimp_placeofdestinationaddressline3: string | null }, {  }>;
    defraimp_placeofdestinationaddresspostcode: WebAttribute<defraimp_importnotification_Select, { defraimp_placeofdestinationaddresspostcode: string | null }, {  }>;
    defraimp_placeofdestinationcontactname: WebAttribute<defraimp_importnotification_Select, { defraimp_placeofdestinationcontactname: string | null }, {  }>;
    defraimp_placeofdestinationemail: WebAttribute<defraimp_importnotification_Select, { defraimp_placeofdestinationemail: string | null }, {  }>;
    defraimp_placeofdestinationtelephone: WebAttribute<defraimp_importnotification_Select, { defraimp_placeofdestinationtelephone: string | null }, {  }>;
    defraimp_pointofentry: WebAttribute<defraimp_importnotification_Select, { defraimp_pointofentry: string | null }, {  }>;
    defraimp_referencenumber: WebAttribute<defraimp_importnotification_Select, { defraimp_referencenumber: string | null }, {  }>;
    defraimp_replacedbyid_guid: WebAttribute<defraimp_importnotification_Select, { defraimp_replacedbyid_guid: string | null }, { defraimp_replacedbyid_formatted?: string }>;
    defraimp_replacesid_guid: WebAttribute<defraimp_importnotification_Select, { defraimp_replacesid_guid: string | null }, { defraimp_replacesid_formatted?: string }>;
    defraimp_speciesproductname: WebAttribute<defraimp_importnotification_Select, { defraimp_speciesproductname: string | null }, {  }>;
    defraimp_transporteraddress: WebAttribute<defraimp_importnotification_Select, { defraimp_transporteraddress: string | null }, {  }>;
    defraimp_transporteremail: WebAttribute<defraimp_importnotification_Select, { defraimp_transporteremail: string | null }, {  }>;
    defraimp_transportername: WebAttribute<defraimp_importnotification_Select, { defraimp_transportername: string | null }, {  }>;
    defraimp_transportertelephone: WebAttribute<defraimp_importnotification_Select, { defraimp_transportertelephone: string | null }, {  }>;
    importsequencenumber: WebAttribute<defraimp_importnotification_Select, { importsequencenumber: number | null }, {  }>;
    modifiedby_guid: WebAttribute<defraimp_importnotification_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
    modifiedon: WebAttribute<defraimp_importnotification_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
    modifiedonbehalfby_guid: WebAttribute<defraimp_importnotification_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
    overriddencreatedon: WebAttribute<defraimp_importnotification_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
    ownerid_guid: WebAttribute<defraimp_importnotification_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
    owningbusinessunit_guid: WebAttribute<defraimp_importnotification_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
    owningteam_guid: WebAttribute<defraimp_importnotification_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
    owninguser_guid: WebAttribute<defraimp_importnotification_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
    statecode: WebAttribute<defraimp_importnotification_Select, { statecode: defraimp_importnotification_statecode | null }, { statecode_formatted?: string }>;
    statuscode: WebAttribute<defraimp_importnotification_Select, { statuscode: defraimp_importnotification_statuscode | null }, { statuscode_formatted?: string }>;
    timezoneruleversionnumber: WebAttribute<defraimp_importnotification_Select, { timezoneruleversionnumber: number | null }, {  }>;
    utcconversiontimezonecode: WebAttribute<defraimp_importnotification_Select, { utcconversiontimezonecode: number | null }, {  }>;
    versionnumber: WebAttribute<defraimp_importnotification_Select, { versionnumber: number | null }, {  }>;
  }
  interface defraimp_importnotification_Filter {
    createdby_guid: XQW.Guid;
    createdon: Date;
    createdonbehalfby_guid: XQW.Guid;
    defraimp_charityaddresscity: string;
    defraimp_charityaddresscountry_guid: XQW.Guid;
    defraimp_charityaddressline1: string;
    defraimp_charityaddressline2: string;
    defraimp_charityaddressline3: string;
    defraimp_charityaddresspostcode: string;
    defraimp_charityemail: string;
    defraimp_charityname: string;
    defraimp_charitytelephone: string;
    defraimp_commoditytypeid_guid: XQW.Guid;
    defraimp_countryoforiginid_guid: XQW.Guid;
    defraimp_cphnumber: string;
    defraimp_datenotificationreceived: Date;
    defraimp_dateofimport: Date;
    defraimp_importeraddresscity: string;
    defraimp_importeraddresscountryid_guid: XQW.Guid;
    defraimp_importeraddressline1: string;
    defraimp_importeraddressline2: string;
    defraimp_importeraddressline3: string;
    defraimp_importeraddresspostcode: string;
    defraimp_importeremail: string;
    defraimp_importername: string;
    defraimp_importertelephone: string;
    defraimp_importnotificationid: XQW.Guid;
    defraimp_ins: string;
    defraimp_name: string;
    defraimp_notificationreceivedintimeframe: boolean;
    defraimp_originaddress: string;
    defraimp_permanentdestinationaddresscity: string;
    defraimp_permanentdestinationaddresscountryid_guid: XQW.Guid;
    defraimp_permanentdestinationaddressline1: string;
    defraimp_permanentdestinationaddressline2: string;
    defraimp_permanentdestinationaddressline3: string;
    defraimp_permanentdestinationaddresspostcode: string;
    defraimp_permanentdestinationcontactname: string;
    defraimp_permanentdestinationemail: string;
    defraimp_permanentdestinationtelephone: string;
    defraimp_placeofdestinationaddresscity: string;
    defraimp_placeofdestinationaddresscountryid_guid: XQW.Guid;
    defraimp_placeofdestinationaddressline1: string;
    defraimp_placeofdestinationaddressline2: string;
    defraimp_placeofdestinationaddressline3: string;
    defraimp_placeofdestinationaddresspostcode: string;
    defraimp_placeofdestinationcontactname: string;
    defraimp_placeofdestinationemail: string;
    defraimp_placeofdestinationtelephone: string;
    defraimp_pointofentry: string;
    defraimp_referencenumber: string;
    defraimp_replacedbyid_guid: XQW.Guid;
    defraimp_replacesid_guid: XQW.Guid;
    defraimp_speciesproductname: string;
    defraimp_transporteraddress: string;
    defraimp_transporteremail: string;
    defraimp_transportername: string;
    defraimp_transportertelephone: string;
    importsequencenumber: number;
    modifiedby_guid: XQW.Guid;
    modifiedon: Date;
    modifiedonbehalfby_guid: XQW.Guid;
    overriddencreatedon: Date;
    ownerid_guid: XQW.Guid;
    owningbusinessunit_guid: XQW.Guid;
    owningteam_guid: XQW.Guid;
    owninguser_guid: XQW.Guid;
    statecode: defraimp_importnotification_statecode;
    statuscode: defraimp_importnotification_statuscode;
    timezoneruleversionnumber: number;
    utcconversiontimezonecode: number;
    versionnumber: number;
  }
  interface defraimp_importnotification_Expand {
    createdby: WebExpand<defraimp_importnotification_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
    createdonbehalfby: WebExpand<defraimp_importnotification_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
    defraimp_CharityAddressCountry: WebExpand<defraimp_importnotification_Expand, defra_country_Select, defra_country_Filter, { defraimp_CharityAddressCountry: defra_country_Result }>;
    defraimp_CommodityTypeId: WebExpand<defraimp_importnotification_Expand, defraexp_commoditytype_Select, defraexp_commoditytype_Filter, { defraimp_CommodityTypeId: defraexp_commoditytype_Result }>;
    defraimp_CountryofOriginId: WebExpand<defraimp_importnotification_Expand, defra_country_Select, defra_country_Filter, { defraimp_CountryofOriginId: defra_country_Result }>;
    defraimp_ImporterAddressCountryid: WebExpand<defraimp_importnotification_Expand, defra_country_Select, defra_country_Filter, { defraimp_ImporterAddressCountryid: defra_country_Result }>;
    defraimp_PermanentDestinationAddressCountryid: WebExpand<defraimp_importnotification_Expand, defra_country_Select, defra_country_Filter, { defraimp_PermanentDestinationAddressCountryid: defra_country_Result }>;
    defraimp_PlaceofDestinationAddressCountryid: WebExpand<defraimp_importnotification_Expand, defra_country_Select, defra_country_Filter, { defraimp_PlaceofDestinationAddressCountryid: defra_country_Result }>;
    defraimp_defraimp_importapplication_defraimp_impor: WebExpand<defraimp_importnotification_Expand, defraimp_importapplication_Select, defraimp_importapplication_Filter, { defraimp_defraimp_importapplication_defraimp_impor: defraimp_importapplication_Result[] }>;
    defraimp_defraimp_importnotification_defraimp_impo: WebExpand<defraimp_importnotification_Expand, defraimp_importapplication_Select, defraimp_importapplication_Filter, { defraimp_defraimp_importnotification_defraimp_impo: defraimp_importapplication_Result[] }>;
    defraimp_defraimp_importnotification_defraimp_importnotification_replacedbyid: WebExpand<defraimp_importnotification_Expand, defraimp_importnotification_Select, defraimp_importnotification_Filter, { defraimp_defraimp_importnotification_defraimp_importnotification_replacedbyid: defraimp_importnotification_Result[] }>;
    defraimp_defraimp_importnotification_defraimp_importnotification_replacesid: WebExpand<defraimp_importnotification_Expand, defraimp_importnotification_Select, defraimp_importnotification_Filter, { defraimp_defraimp_importnotification_defraimp_importnotification_replacesid: defraimp_importnotification_Result[] }>;
    defraimp_importnotification_ProcessSession: WebExpand<defraimp_importnotification_Expand, ProcessSession_Select, ProcessSession_Filter, { defraimp_importnotification_ProcessSession: ProcessSession_Result[] }>;
    defraimp_importnotification_SyncErrors: WebExpand<defraimp_importnotification_Expand, SyncError_Select, SyncError_Filter, { defraimp_importnotification_SyncErrors: SyncError_Result[] }>;
    defraimp_replacedbyid: WebExpand<defraimp_importnotification_Expand, defraimp_importnotification_Select, defraimp_importnotification_Filter, { defraimp_replacedbyid: defraimp_importnotification_Result }>;
    defraimp_replacesid: WebExpand<defraimp_importnotification_Expand, defraimp_importnotification_Select, defraimp_importnotification_Filter, { defraimp_replacesid: defraimp_importnotification_Result }>;
    modifiedby: WebExpand<defraimp_importnotification_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
    modifiedonbehalfby: WebExpand<defraimp_importnotification_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
    owningteam: WebExpand<defraimp_importnotification_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
    owninguser: WebExpand<defraimp_importnotification_Expand, SystemUser_Select, SystemUser_Filter, { owninguser: SystemUser_Result }>;
  }
  interface defraimp_importnotification_FormattedResult {
    createdby_formatted?: string;
    createdon_formatted?: string;
    createdonbehalfby_formatted?: string;
    defraimp_charityaddresscountry_formatted?: string;
    defraimp_commoditytypeid_formatted?: string;
    defraimp_countryoforiginid_formatted?: string;
    defraimp_datenotificationreceived_formatted?: string;
    defraimp_dateofimport_formatted?: string;
    defraimp_importeraddresscountryid_formatted?: string;
    defraimp_permanentdestinationaddresscountryid_formatted?: string;
    defraimp_placeofdestinationaddresscountryid_formatted?: string;
    defraimp_replacedbyid_formatted?: string;
    defraimp_replacesid_formatted?: string;
    modifiedby_formatted?: string;
    modifiedon_formatted?: string;
    modifiedonbehalfby_formatted?: string;
    overriddencreatedon_formatted?: string;
    ownerid_formatted?: string;
    owningbusinessunit_formatted?: string;
    owningteam_formatted?: string;
    owninguser_formatted?: string;
    statecode_formatted?: string;
    statuscode_formatted?: string;
  }
  interface defraimp_importnotification_Result extends defraimp_importnotification_Base, defraimp_importnotification_Relationships {
    "@odata.etag": string;
    createdby_guid: string | null;
    createdonbehalfby_guid: string | null;
    defraimp_charityaddresscountry_guid: string | null;
    defraimp_commoditytypeid_guid: string | null;
    defraimp_countryoforiginid_guid: string | null;
    defraimp_importeraddresscountryid_guid: string | null;
    defraimp_permanentdestinationaddresscountryid_guid: string | null;
    defraimp_placeofdestinationaddresscountryid_guid: string | null;
    defraimp_replacedbyid_guid: string | null;
    defraimp_replacesid_guid: string | null;
    modifiedby_guid: string | null;
    modifiedonbehalfby_guid: string | null;
    ownerid_guid: string | null;
    owningbusinessunit_guid: string | null;
    owningteam_guid: string | null;
    owninguser_guid: string | null;
  }
  interface defraimp_importnotification_RelatedOne {
    createdby: WebMappingRetrieve<WebApi.SystemUser_Select,WebApi.SystemUser_Expand,WebApi.SystemUser_Filter,WebApi.SystemUser_Fixed,WebApi.SystemUser_Result,WebApi.SystemUser_FormattedResult>;
    createdonbehalfby: WebMappingRetrieve<WebApi.SystemUser_Select,WebApi.SystemUser_Expand,WebApi.SystemUser_Filter,WebApi.SystemUser_Fixed,WebApi.SystemUser_Result,WebApi.SystemUser_FormattedResult>;
    defraimp_CharityAddressCountry: WebMappingRetrieve<WebApi.defra_country_Select,WebApi.defra_country_Expand,WebApi.defra_country_Filter,WebApi.defra_country_Fixed,WebApi.defra_country_Result,WebApi.defra_country_FormattedResult>;
    defraimp_CommodityTypeId: WebMappingRetrieve<WebApi.defraexp_commoditytype_Select,WebApi.defraexp_commoditytype_Expand,WebApi.defraexp_commoditytype_Filter,WebApi.defraexp_commoditytype_Fixed,WebApi.defraexp_commoditytype_Result,WebApi.defraexp_commoditytype_FormattedResult>;
    defraimp_CountryofOriginId: WebMappingRetrieve<WebApi.defra_country_Select,WebApi.defra_country_Expand,WebApi.defra_country_Filter,WebApi.defra_country_Fixed,WebApi.defra_country_Result,WebApi.defra_country_FormattedResult>;
    defraimp_ImporterAddressCountryid: WebMappingRetrieve<WebApi.defra_country_Select,WebApi.defra_country_Expand,WebApi.defra_country_Filter,WebApi.defra_country_Fixed,WebApi.defra_country_Result,WebApi.defra_country_FormattedResult>;
    defraimp_PermanentDestinationAddressCountryid: WebMappingRetrieve<WebApi.defra_country_Select,WebApi.defra_country_Expand,WebApi.defra_country_Filter,WebApi.defra_country_Fixed,WebApi.defra_country_Result,WebApi.defra_country_FormattedResult>;
    defraimp_PlaceofDestinationAddressCountryid: WebMappingRetrieve<WebApi.defra_country_Select,WebApi.defra_country_Expand,WebApi.defra_country_Filter,WebApi.defra_country_Fixed,WebApi.defra_country_Result,WebApi.defra_country_FormattedResult>;
    defraimp_replacedbyid: WebMappingRetrieve<WebApi.defraimp_importnotification_Select,WebApi.defraimp_importnotification_Expand,WebApi.defraimp_importnotification_Filter,WebApi.defraimp_importnotification_Fixed,WebApi.defraimp_importnotification_Result,WebApi.defraimp_importnotification_FormattedResult>;
    defraimp_replacesid: WebMappingRetrieve<WebApi.defraimp_importnotification_Select,WebApi.defraimp_importnotification_Expand,WebApi.defraimp_importnotification_Filter,WebApi.defraimp_importnotification_Fixed,WebApi.defraimp_importnotification_Result,WebApi.defraimp_importnotification_FormattedResult>;
    modifiedby: WebMappingRetrieve<WebApi.SystemUser_Select,WebApi.SystemUser_Expand,WebApi.SystemUser_Filter,WebApi.SystemUser_Fixed,WebApi.SystemUser_Result,WebApi.SystemUser_FormattedResult>;
    modifiedonbehalfby: WebMappingRetrieve<WebApi.SystemUser_Select,WebApi.SystemUser_Expand,WebApi.SystemUser_Filter,WebApi.SystemUser_Fixed,WebApi.SystemUser_Result,WebApi.SystemUser_FormattedResult>;
    owningteam: WebMappingRetrieve<WebApi.Team_Select,WebApi.Team_Expand,WebApi.Team_Filter,WebApi.Team_Fixed,WebApi.Team_Result,WebApi.Team_FormattedResult>;
    owninguser: WebMappingRetrieve<WebApi.SystemUser_Select,WebApi.SystemUser_Expand,WebApi.SystemUser_Filter,WebApi.SystemUser_Fixed,WebApi.SystemUser_Result,WebApi.SystemUser_FormattedResult>;
  }
  interface defraimp_importnotification_RelatedMany {
    defraimp_defraimp_importapplication_defraimp_impor: WebMappingRetrieve<WebApi.defraimp_importapplication_Select,WebApi.defraimp_importapplication_Expand,WebApi.defraimp_importapplication_Filter,WebApi.defraimp_importapplication_Fixed,WebApi.defraimp_importapplication_Result,WebApi.defraimp_importapplication_FormattedResult>;
    defraimp_defraimp_importnotification_defraimp_impo: WebMappingRetrieve<WebApi.defraimp_importapplication_Select,WebApi.defraimp_importapplication_Expand,WebApi.defraimp_importapplication_Filter,WebApi.defraimp_importapplication_Fixed,WebApi.defraimp_importapplication_Result,WebApi.defraimp_importapplication_FormattedResult>;
    defraimp_defraimp_importnotification_defraimp_importnotification_replacedbyid: WebMappingRetrieve<WebApi.defraimp_importnotification_Select,WebApi.defraimp_importnotification_Expand,WebApi.defraimp_importnotification_Filter,WebApi.defraimp_importnotification_Fixed,WebApi.defraimp_importnotification_Result,WebApi.defraimp_importnotification_FormattedResult>;
    defraimp_defraimp_importnotification_defraimp_importnotification_replacesid: WebMappingRetrieve<WebApi.defraimp_importnotification_Select,WebApi.defraimp_importnotification_Expand,WebApi.defraimp_importnotification_Filter,WebApi.defraimp_importnotification_Fixed,WebApi.defraimp_importnotification_Result,WebApi.defraimp_importnotification_FormattedResult>;
    defraimp_importnotification_ProcessSession: WebMappingRetrieve<WebApi.ProcessSession_Select,WebApi.ProcessSession_Expand,WebApi.ProcessSession_Filter,WebApi.ProcessSession_Fixed,WebApi.ProcessSession_Result,WebApi.ProcessSession_FormattedResult>;
    defraimp_importnotification_SyncErrors: WebMappingRetrieve<WebApi.SyncError_Select,WebApi.SyncError_Expand,WebApi.SyncError_Filter,WebApi.SyncError_Fixed,WebApi.SyncError_Result,WebApi.SyncError_FormattedResult>;
  }
}
interface WebEntitiesRetrieve {
  defraimp_importnotifications: WebMappingRetrieve<WebApi.defraimp_importnotification_Select,WebApi.defraimp_importnotification_Expand,WebApi.defraimp_importnotification_Filter,WebApi.defraimp_importnotification_Fixed,WebApi.defraimp_importnotification_Result,WebApi.defraimp_importnotification_FormattedResult>;
}
interface WebEntitiesRelated {
  defraimp_importnotifications: WebMappingRelated<WebApi.defraimp_importnotification_RelatedOne,WebApi.defraimp_importnotification_RelatedMany>;
}
interface WebEntitiesCUDA {
  defraimp_importnotifications: WebMappingCUDA<WebApi.defraimp_importnotification_Create,WebApi.defraimp_importnotification_Update,WebApi.defraimp_importnotification_Select>;
}
