declare namespace WebApi {
  interface defraimp_ImporterNotification_Base extends WebEntity {
    createdon?: Date | null;
    defraimp_arrivaldate?: Date | null;
    defraimp_arrivaltime?: string | null;
    defraimp_commoditiesanimalscertifiedas?: defraimp_animalcertifiedas | null;
    defraimp_commoditiescommodityintendedfor?: string | null;
    defraimp_commoditiesconsignedcountry?: string | null;
    defraimp_commoditiescountryoforigin?: string | null;
    defraimp_commoditiesincludenonablactedanimals?: boolean | null;
    defraimp_commoditiesnumberofanimals?: number | null;
    defraimp_commoditiesregionoforigin?: string | null;
    defraimp_commoditiestotalgrossweight?: number | null;
    defraimp_commoditiestotalnetweight?: number | null;
    defraimp_commoditycomplementid?: number | null;
    defraimp_commoditycomplementname?: string | null;
    defraimp_commoditycomplementstext?: string | null;
    defraimp_commoditydescription?: string | null;
    defraimp_commodityid?: string | null;
    defraimp_commodityidtypes?: string | null;
    defraimp_commodityspeciesclass?: string | null;
    defraimp_commodityspeciesclassname?: string | null;
    defraimp_commodityspeciescommonname?: string | null;
    defraimp_commodityspeciesid?: string | null;
    defraimp_commodityspeciesname?: string | null;
    defraimp_commodityspeciesnomination?: string | null;
    defraimp_commodityspeciestype?: string | null;
    defraimp_complexcommodityselected?: boolean | null;
    defraimp_consigneeaddressaddressline1?: string | null;
    defraimp_consigneeaddressaddressline2?: string | null;
    defraimp_consigneeaddressaddressline3?: string | null;
    defraimp_consigneeaddresscity?: string | null;
    defraimp_consigneeaddresscountryisocode?: string | null;
    defraimp_consigneeaddressemail?: string | null;
    defraimp_consigneeaddresspostalzipcode?: string | null;
    defraimp_consigneeaddresstelephone?: string | null;
    defraimp_consigneeaddressuktelephone?: string | null;
    defraimp_consigneeapprovalnumber?: string | null;
    defraimp_consigneecompanyname?: string | null;
    defraimp_consigneeid?: string | null;
    defraimp_consigneeindividualname?: string | null;
    defraimp_consigneeinternationalphonecode?: string | null;
    defraimp_consigneeinternationalphonenumber?: string | null;
    defraimp_consigneeotheridentifier?: string | null;
    defraimp_consigneestatus?: string | null;
    defraimp_consigneetype?: string | null;
    defraimp_consignoraddressaddressline1?: string | null;
    defraimp_consignoraddressaddressline2?: string | null;
    defraimp_consignoraddressaddressline3?: string | null;
    defraimp_consignoraddresscity?: string | null;
    defraimp_consignoraddresscountryisocode?: string | null;
    defraimp_consignoraddressemail?: string | null;
    defraimp_consignoraddresspostalzipcode?: string | null;
    defraimp_consignoraddresstelephone?: string | null;
    defraimp_consignoraddressuktelephone?: string | null;
    defraimp_consignorapprovalnumber?: string | null;
    defraimp_consignorcompanyname?: string | null;
    defraimp_consignorid?: string | null;
    defraimp_consignorindividualname?: string | null;
    defraimp_consignorinternationalphonecode?: string | null;
    defraimp_consignorinternationalphonenumber?: string | null;
    defraimp_consignorotheridentifier?: string | null;
    defraimp_consignorstatus?: string | null;
    defraimp_consignortwoaddressaddressline1?: string | null;
    defraimp_consignortwoaddressaddressline2?: string | null;
    defraimp_consignortwoaddressaddressline3?: string | null;
    defraimp_consignortwoaddresscity?: string | null;
    defraimp_consignortwoaddresscountryisocode?: string | null;
    defraimp_consignortwoaddressemail?: string | null;
    defraimp_consignortwoaddresspostalzipcode?: string | null;
    defraimp_consignortwoaddresstelephone?: string | null;
    defraimp_consignortwoaddressuktelephone?: string | null;
    defraimp_consignortwoapprovalnumber?: string | null;
    defraimp_consignortwocompanyname?: string | null;
    defraimp_consignortwoid?: string | null;
    defraimp_consignortwoindividualname?: string | null;
    defraimp_consignortwointernationalphonecode?: string | null;
    defraimp_consignortwointernationalphonenumber?: string | null;
    defraimp_consignortwootheridentifier?: string | null;
    defraimp_consignortwostatus?: string | null;
    defraimp_consignortwotype?: string | null;
    defraimp_consignortype?: string | null;
    defraimp_cphnumber?: string | null;
    defraimp_departuredate?: Date | null;
    defraimp_departuretime?: string | null;
    defraimp_estimatedjourneytimeinminutes?: number | null;
    defraimp_formattedcommoditycomplementstext?: string | null;
    defraimp_formattedidentificationofanimalstext?: string | null;
    defraimp_identificationofanimalstext?: string | null;
    defraimp_importeraddressaddressline1?: string | null;
    defraimp_importeraddressaddressline2?: string | null;
    defraimp_importeraddressaddressline3?: string | null;
    defraimp_importeraddresscity?: string | null;
    defraimp_importeraddresscountryisocode?: string | null;
    defraimp_importeraddressemail?: string | null;
    defraimp_importeraddresspostalzipcode?: string | null;
    defraimp_importeraddresstelephone?: string | null;
    defraimp_importeraddressuktelephone?: string | null;
    defraimp_importerapprovalnumber?: string | null;
    defraimp_importercompanyname?: string | null;
    defraimp_importerid?: string | null;
    defraimp_importerindividualname?: string | null;
    defraimp_importerinternationalphonecode?: string | null;
    defraimp_importerinternationalphonenumber?: string | null;
    defraimp_importernotificationid?: string | null;
    defraimp_importerotheridentifier?: string | null;
    defraimp_importerstatus?: string | null;
    defraimp_importertype?: string | null;
    defraimp_importingfromcharity?: boolean | null;
    defraimp_ipaffsid?: number | null;
    defraimp_isplaceofdestinationthepermanentaddress?: boolean | null;
    defraimp_lastupdated?: Date | null;
    defraimp_lastupdatedbydisplayname?: string | null;
    defraimp_lastupdatedbyuserid?: string | null;
    defraimp_meansoftransportfromentrypointdocument?: string | null;
    defraimp_meansoftransportfromentrypointid?: string | null;
    defraimp_meansoftransportfromentrypointtype?: string | null;
    defraimp_name?: string | null;
    defraimp_personresponsibleaddress?: string | null;
    defraimp_personresponsiblecity?: string | null;
    defraimp_personresponsiblecompanyid?: string | null;
    defraimp_personresponsiblecompanyname?: string | null;
    defraimp_personresponsiblecontactid?: string | null;
    defraimp_personresponsiblecountry?: string | null;
    defraimp_personresponsiblecounty?: string | null;
    defraimp_personresponsibleemail?: string | null;
    defraimp_personresponsiblefax?: string | null;
    defraimp_personresponsibleid?: string | null;
    defraimp_personresponsiblename?: string | null;
    defraimp_personresponsiblephone?: string | null;
    defraimp_personresponsiblepostcode?: string | null;
    defraimp_personresponsibletype?: string | null;
    defraimp_placeofdestinationaddressaddressline1?: string | null;
    defraimp_placeofdestinationaddressaddressline2?: string | null;
    defraimp_placeofdestinationaddressaddressline3?: string | null;
    defraimp_placeofdestinationaddresscity?: string | null;
    defraimp_placeofdestinationaddresscountryisocode?: string | null;
    defraimp_placeofdestinationaddressemail?: string | null;
    defraimp_placeofdestinationaddresspostalzipcode?: string | null;
    defraimp_placeofdestinationaddresstelephone?: string | null;
    defraimp_placeofdestinationaddressuktelephone?: string | null;
    defraimp_placeofdestinationapprovalnumber?: string | null;
    defraimp_placeofdestinationcompanyname?: string | null;
    defraimp_placeofdestinationid?: string | null;
    defraimp_placeofdestinationindividualname?: string | null;
    defraimp_placeofdestinationintphonecode?: string | null;
    defraimp_placeofdestinationintphonenumber?: string | null;
    defraimp_placeofdestinationotheridentifier?: string | null;
    defraimp_placeofdestinationstatus?: string | null;
    defraimp_placeofdestinationtype?: string | null;
    defraimp_placeoforiginharvestaddressaddressline1?: string | null;
    defraimp_placeoforiginharvestaddressaddressline2?: string | null;
    defraimp_placeoforiginharvestaddressaddressline3?: string | null;
    defraimp_placeoforiginharvestaddresscity?: string | null;
    defraimp_placeoforiginharvestaddresscountryisocode?: string | null;
    defraimp_placeoforiginharvestaddressemail?: string | null;
    defraimp_placeoforiginharvestaddresspostalzipcode?: string | null;
    defraimp_placeoforiginharvestaddresstelephone?: string | null;
    defraimp_placeoforiginharvestaddressuktelephone?: string | null;
    defraimp_placeoforiginharvestapprovalnumber?: string | null;
    defraimp_placeoforiginharvestcompanyname?: string | null;
    defraimp_placeoforiginharvestid?: string | null;
    defraimp_placeoforiginharvestindividualname?: string | null;
    defraimp_placeoforiginharvestintphonecode?: string | null;
    defraimp_placeoforiginharvestintphonenumber?: string | null;
    defraimp_placeoforiginharvestotheridentifier?: string | null;
    defraimp_placeoforiginharveststatus?: string | null;
    defraimp_placeoforiginharvesttype?: string | null;
    defraimp_portofentry?: string | null;
    defraimp_quickviewspacer?: string | null;
    defraimp_responsiblefortransport?: string | null;
    defraimp_routetransitingstates?: string | null;
    defraimp_status?: defraimp_importernotificationstatus | null;
    defraimp_submissiondate?: Date | null;
    defraimp_submittedbydisplayname?: string | null;
    defraimp_submittedbyiscontroluser?: boolean | null;
    defraimp_submittedbyuserid?: string | null;
    defraimp_transporteraddressaddressline1?: string | null;
    defraimp_transporteraddressaddressline2?: string | null;
    defraimp_transporteraddressaddressline3?: string | null;
    defraimp_transporteraddresscity?: string | null;
    defraimp_transporteraddresscountryisocode?: string | null;
    defraimp_transporteraddressemail?: string | null;
    defraimp_transporteraddresspostalzipcode?: string | null;
    defraimp_transporteraddresstelephone?: string | null;
    defraimp_transporteraddressuktelephone?: string | null;
    defraimp_transporterapprovalnumber?: string | null;
    defraimp_transportercompanyname?: string | null;
    defraimp_transporterdetailsrequired?: boolean | null;
    defraimp_transporterid?: string | null;
    defraimp_transporterindividualname?: string | null;
    defraimp_transporterinternationalphonecode?: string | null;
    defraimp_transporterinternationalphonenumber?: string | null;
    defraimp_transporterotheridentifier?: string | null;
    defraimp_transporterstatus?: string | null;
    defraimp_transportertype?: string | null;
    defraimp_type?: defraimp_importernotificationtype | null;
    defraimp_version?: number | null;
    defraimp_veterinaryinformationveterinarydocument?: string | null;
    importsequencenumber?: number | null;
    modifiedon?: Date | null;
    overriddencreatedon?: Date | null;
    statecode?: defraimp_importernotification_statecode | null;
    statuscode?: defraimp_importernotification_statuscode | null;
    timezoneruleversionnumber?: number | null;
    utcconversiontimezonecode?: number | null;
    versionnumber?: number | null;
  }
  interface defraimp_ImporterNotification_Relationships {
    defraimp_defraimp_importernotification_defraimp_importapplication_PrimaryImporterNotificationId?: defraimp_importapplication_Result[] | null;
    defraimp_defraimp_importernotification_defraimp_matchrecord_ImporterNotification?: defraimp_matchrecord_Result[] | null;
  }
  interface defraimp_ImporterNotification extends defraimp_ImporterNotification_Base, defraimp_ImporterNotification_Relationships {
    defraimp_ConsignedCountryid_bind$defra_countries?: string | null;
    defraimp_ConsigneeAddressCountryId_bind$defra_countries?: string | null;
    defraimp_ConsignorAddressCountryid_bind$defra_countries?: string | null;
    defraimp_ConsignorTwoAddressCountry_bind$defra_countries?: string | null;
    defraimp_CountryofOriginId_bind$defra_countries?: string | null;
    defraimp_ImporterAddressCountryid_bind$defra_countries?: string | null;
    defraimp_PersonResponsibleCountryId_bind$defra_countries?: string | null;
    defraimp_PlaceofDestinationCountryid_bind$defra_countries?: string | null;
    defraimp_PlaceofOriginHarvestAddressCountryId_bind$defra_countries?: string | null;
    defraimp_TransporterAddressCountryid_bind$defra_countries?: string | null;
    ownerid_bind$owners?: string | null;
  }
  interface defraimp_ImporterNotification_Create extends defraimp_ImporterNotification {
  }
  interface defraimp_ImporterNotification_Update extends defraimp_ImporterNotification {
  }
  interface defraimp_ImporterNotification_Select {
    createdby_guid: WebAttribute<defraimp_ImporterNotification_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
    createdon: WebAttribute<defraimp_ImporterNotification_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
    createdonbehalfby_guid: WebAttribute<defraimp_ImporterNotification_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
    defraimp_arrivaldate: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_arrivaldate: Date | null }, { defraimp_arrivaldate_formatted?: string }>;
    defraimp_arrivaltime: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_arrivaltime: string | null }, {  }>;
    defraimp_commoditiesanimalscertifiedas: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_commoditiesanimalscertifiedas: defraimp_animalcertifiedas | null }, { defraimp_commoditiesanimalscertifiedas_formatted?: string }>;
    defraimp_commoditiescommodityintendedfor: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_commoditiescommodityintendedfor: string | null }, {  }>;
    defraimp_commoditiesconsignedcountry: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_commoditiesconsignedcountry: string | null }, {  }>;
    defraimp_commoditiescountryoforigin: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_commoditiescountryoforigin: string | null }, {  }>;
    defraimp_commoditiesincludenonablactedanimals: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_commoditiesincludenonablactedanimals: boolean | null }, {  }>;
    defraimp_commoditiesnumberofanimals: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_commoditiesnumberofanimals: number | null }, {  }>;
    defraimp_commoditiesregionoforigin: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_commoditiesregionoforigin: string | null }, {  }>;
    defraimp_commoditiestotalgrossweight: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_commoditiestotalgrossweight: number | null }, {  }>;
    defraimp_commoditiestotalnetweight: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_commoditiestotalnetweight: number | null }, {  }>;
    defraimp_commoditycomplementid: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_commoditycomplementid: number | null }, {  }>;
    defraimp_commoditycomplementname: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_commoditycomplementname: string | null }, {  }>;
    defraimp_commoditycomplementstext: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_commoditycomplementstext: string | null }, {  }>;
    defraimp_commoditydescription: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_commoditydescription: string | null }, {  }>;
    defraimp_commodityid: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_commodityid: string | null }, {  }>;
    defraimp_commodityidtypes: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_commodityidtypes: string | null }, {  }>;
    defraimp_commodityspeciesclass: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_commodityspeciesclass: string | null }, {  }>;
    defraimp_commodityspeciesclassname: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_commodityspeciesclassname: string | null }, {  }>;
    defraimp_commodityspeciescommonname: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_commodityspeciescommonname: string | null }, {  }>;
    defraimp_commodityspeciesid: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_commodityspeciesid: string | null }, {  }>;
    defraimp_commodityspeciesname: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_commodityspeciesname: string | null }, {  }>;
    defraimp_commodityspeciesnomination: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_commodityspeciesnomination: string | null }, {  }>;
    defraimp_commodityspeciestype: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_commodityspeciestype: string | null }, {  }>;
    defraimp_complexcommodityselected: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_complexcommodityselected: boolean | null }, {  }>;
    defraimp_consignedcountryid_guid: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignedcountryid_guid: string | null }, { defraimp_consignedcountryid_formatted?: string }>;
    defraimp_consigneeaddressaddressline1: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consigneeaddressaddressline1: string | null }, {  }>;
    defraimp_consigneeaddressaddressline2: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consigneeaddressaddressline2: string | null }, {  }>;
    defraimp_consigneeaddressaddressline3: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consigneeaddressaddressline3: string | null }, {  }>;
    defraimp_consigneeaddresscity: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consigneeaddresscity: string | null }, {  }>;
    defraimp_consigneeaddresscountryid_guid: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consigneeaddresscountryid_guid: string | null }, { defraimp_consigneeaddresscountryid_formatted?: string }>;
    defraimp_consigneeaddresscountryisocode: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consigneeaddresscountryisocode: string | null }, {  }>;
    defraimp_consigneeaddressemail: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consigneeaddressemail: string | null }, {  }>;
    defraimp_consigneeaddresspostalzipcode: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consigneeaddresspostalzipcode: string | null }, {  }>;
    defraimp_consigneeaddresstelephone: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consigneeaddresstelephone: string | null }, {  }>;
    defraimp_consigneeaddressuktelephone: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consigneeaddressuktelephone: string | null }, {  }>;
    defraimp_consigneeapprovalnumber: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consigneeapprovalnumber: string | null }, {  }>;
    defraimp_consigneecompanyname: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consigneecompanyname: string | null }, {  }>;
    defraimp_consigneeid: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consigneeid: string | null }, {  }>;
    defraimp_consigneeindividualname: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consigneeindividualname: string | null }, {  }>;
    defraimp_consigneeinternationalphonecode: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consigneeinternationalphonecode: string | null }, {  }>;
    defraimp_consigneeinternationalphonenumber: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consigneeinternationalphonenumber: string | null }, {  }>;
    defraimp_consigneeotheridentifier: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consigneeotheridentifier: string | null }, {  }>;
    defraimp_consigneestatus: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consigneestatus: string | null }, {  }>;
    defraimp_consigneetype: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consigneetype: string | null }, {  }>;
    defraimp_consignoraddressaddressline1: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignoraddressaddressline1: string | null }, {  }>;
    defraimp_consignoraddressaddressline2: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignoraddressaddressline2: string | null }, {  }>;
    defraimp_consignoraddressaddressline3: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignoraddressaddressline3: string | null }, {  }>;
    defraimp_consignoraddresscity: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignoraddresscity: string | null }, {  }>;
    defraimp_consignoraddresscountryid_guid: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignoraddresscountryid_guid: string | null }, { defraimp_consignoraddresscountryid_formatted?: string }>;
    defraimp_consignoraddresscountryisocode: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignoraddresscountryisocode: string | null }, {  }>;
    defraimp_consignoraddressemail: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignoraddressemail: string | null }, {  }>;
    defraimp_consignoraddresspostalzipcode: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignoraddresspostalzipcode: string | null }, {  }>;
    defraimp_consignoraddresstelephone: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignoraddresstelephone: string | null }, {  }>;
    defraimp_consignoraddressuktelephone: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignoraddressuktelephone: string | null }, {  }>;
    defraimp_consignorapprovalnumber: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignorapprovalnumber: string | null }, {  }>;
    defraimp_consignorcompanyname: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignorcompanyname: string | null }, {  }>;
    defraimp_consignorid: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignorid: string | null }, {  }>;
    defraimp_consignorindividualname: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignorindividualname: string | null }, {  }>;
    defraimp_consignorinternationalphonecode: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignorinternationalphonecode: string | null }, {  }>;
    defraimp_consignorinternationalphonenumber: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignorinternationalphonenumber: string | null }, {  }>;
    defraimp_consignorotheridentifier: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignorotheridentifier: string | null }, {  }>;
    defraimp_consignorstatus: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignorstatus: string | null }, {  }>;
    defraimp_consignortwoaddressaddressline1: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignortwoaddressaddressline1: string | null }, {  }>;
    defraimp_consignortwoaddressaddressline2: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignortwoaddressaddressline2: string | null }, {  }>;
    defraimp_consignortwoaddressaddressline3: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignortwoaddressaddressline3: string | null }, {  }>;
    defraimp_consignortwoaddresscity: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignortwoaddresscity: string | null }, {  }>;
    defraimp_consignortwoaddresscountry_guid: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignortwoaddresscountry_guid: string | null }, { defraimp_consignortwoaddresscountry_formatted?: string }>;
    defraimp_consignortwoaddresscountryisocode: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignortwoaddresscountryisocode: string | null }, {  }>;
    defraimp_consignortwoaddressemail: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignortwoaddressemail: string | null }, {  }>;
    defraimp_consignortwoaddresspostalzipcode: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignortwoaddresspostalzipcode: string | null }, {  }>;
    defraimp_consignortwoaddresstelephone: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignortwoaddresstelephone: string | null }, {  }>;
    defraimp_consignortwoaddressuktelephone: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignortwoaddressuktelephone: string | null }, {  }>;
    defraimp_consignortwoapprovalnumber: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignortwoapprovalnumber: string | null }, {  }>;
    defraimp_consignortwocompanyname: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignortwocompanyname: string | null }, {  }>;
    defraimp_consignortwoid: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignortwoid: string | null }, {  }>;
    defraimp_consignortwoindividualname: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignortwoindividualname: string | null }, {  }>;
    defraimp_consignortwointernationalphonecode: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignortwointernationalphonecode: string | null }, {  }>;
    defraimp_consignortwointernationalphonenumber: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignortwointernationalphonenumber: string | null }, {  }>;
    defraimp_consignortwootheridentifier: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignortwootheridentifier: string | null }, {  }>;
    defraimp_consignortwostatus: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignortwostatus: string | null }, {  }>;
    defraimp_consignortwotype: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignortwotype: string | null }, {  }>;
    defraimp_consignortype: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_consignortype: string | null }, {  }>;
    defraimp_countryoforiginid_guid: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_countryoforiginid_guid: string | null }, { defraimp_countryoforiginid_formatted?: string }>;
    defraimp_cphnumber: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_cphnumber: string | null }, {  }>;
    defraimp_departuredate: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_departuredate: Date | null }, { defraimp_departuredate_formatted?: string }>;
    defraimp_departuretime: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_departuretime: string | null }, {  }>;
    defraimp_estimatedjourneytimeinminutes: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_estimatedjourneytimeinminutes: number | null }, {  }>;
    defraimp_formattedcommoditycomplementstext: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_formattedcommoditycomplementstext: string | null }, {  }>;
    defraimp_formattedidentificationofanimalstext: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_formattedidentificationofanimalstext: string | null }, {  }>;
    defraimp_identificationofanimalstext: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_identificationofanimalstext: string | null }, {  }>;
    defraimp_importeraddressaddressline1: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_importeraddressaddressline1: string | null }, {  }>;
    defraimp_importeraddressaddressline2: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_importeraddressaddressline2: string | null }, {  }>;
    defraimp_importeraddressaddressline3: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_importeraddressaddressline3: string | null }, {  }>;
    defraimp_importeraddresscity: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_importeraddresscity: string | null }, {  }>;
    defraimp_importeraddresscountryid_guid: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_importeraddresscountryid_guid: string | null }, { defraimp_importeraddresscountryid_formatted?: string }>;
    defraimp_importeraddresscountryisocode: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_importeraddresscountryisocode: string | null }, {  }>;
    defraimp_importeraddressemail: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_importeraddressemail: string | null }, {  }>;
    defraimp_importeraddresspostalzipcode: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_importeraddresspostalzipcode: string | null }, {  }>;
    defraimp_importeraddresstelephone: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_importeraddresstelephone: string | null }, {  }>;
    defraimp_importeraddressuktelephone: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_importeraddressuktelephone: string | null }, {  }>;
    defraimp_importerapprovalnumber: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_importerapprovalnumber: string | null }, {  }>;
    defraimp_importercompanyname: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_importercompanyname: string | null }, {  }>;
    defraimp_importerid: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_importerid: string | null }, {  }>;
    defraimp_importerindividualname: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_importerindividualname: string | null }, {  }>;
    defraimp_importerinternationalphonecode: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_importerinternationalphonecode: string | null }, {  }>;
    defraimp_importerinternationalphonenumber: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_importerinternationalphonenumber: string | null }, {  }>;
    defraimp_importernotificationid: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_importernotificationid: string | null }, {  }>;
    defraimp_importerotheridentifier: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_importerotheridentifier: string | null }, {  }>;
    defraimp_importerstatus: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_importerstatus: string | null }, {  }>;
    defraimp_importertype: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_importertype: string | null }, {  }>;
    defraimp_importingfromcharity: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_importingfromcharity: boolean | null }, {  }>;
    defraimp_ipaffsid: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_ipaffsid: number | null }, {  }>;
    defraimp_isplaceofdestinationthepermanentaddress: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_isplaceofdestinationthepermanentaddress: boolean | null }, {  }>;
    defraimp_lastupdated: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_lastupdated: Date | null }, { defraimp_lastupdated_formatted?: string }>;
    defraimp_lastupdatedbydisplayname: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_lastupdatedbydisplayname: string | null }, {  }>;
    defraimp_lastupdatedbyuserid: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_lastupdatedbyuserid: string | null }, {  }>;
    defraimp_meansoftransportfromentrypointdocument: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_meansoftransportfromentrypointdocument: string | null }, {  }>;
    defraimp_meansoftransportfromentrypointid: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_meansoftransportfromentrypointid: string | null }, {  }>;
    defraimp_meansoftransportfromentrypointtype: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_meansoftransportfromentrypointtype: string | null }, {  }>;
    defraimp_name: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_name: string | null }, {  }>;
    defraimp_personresponsibleaddress: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_personresponsibleaddress: string | null }, {  }>;
    defraimp_personresponsiblecity: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_personresponsiblecity: string | null }, {  }>;
    defraimp_personresponsiblecompanyid: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_personresponsiblecompanyid: string | null }, {  }>;
    defraimp_personresponsiblecompanyname: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_personresponsiblecompanyname: string | null }, {  }>;
    defraimp_personresponsiblecontactid: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_personresponsiblecontactid: string | null }, {  }>;
    defraimp_personresponsiblecountry: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_personresponsiblecountry: string | null }, {  }>;
    defraimp_personresponsiblecountryid_guid: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_personresponsiblecountryid_guid: string | null }, { defraimp_personresponsiblecountryid_formatted?: string }>;
    defraimp_personresponsiblecounty: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_personresponsiblecounty: string | null }, {  }>;
    defraimp_personresponsibleemail: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_personresponsibleemail: string | null }, {  }>;
    defraimp_personresponsiblefax: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_personresponsiblefax: string | null }, {  }>;
    defraimp_personresponsibleid: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_personresponsibleid: string | null }, {  }>;
    defraimp_personresponsiblename: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_personresponsiblename: string | null }, {  }>;
    defraimp_personresponsiblephone: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_personresponsiblephone: string | null }, {  }>;
    defraimp_personresponsiblepostcode: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_personresponsiblepostcode: string | null }, {  }>;
    defraimp_personresponsibletype: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_personresponsibletype: string | null }, {  }>;
    defraimp_placeofdestinationaddressaddressline1: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeofdestinationaddressaddressline1: string | null }, {  }>;
    defraimp_placeofdestinationaddressaddressline2: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeofdestinationaddressaddressline2: string | null }, {  }>;
    defraimp_placeofdestinationaddressaddressline3: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeofdestinationaddressaddressline3: string | null }, {  }>;
    defraimp_placeofdestinationaddresscity: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeofdestinationaddresscity: string | null }, {  }>;
    defraimp_placeofdestinationaddresscountryisocode: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeofdestinationaddresscountryisocode: string | null }, {  }>;
    defraimp_placeofdestinationaddressemail: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeofdestinationaddressemail: string | null }, {  }>;
    defraimp_placeofdestinationaddresspostalzipcode: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeofdestinationaddresspostalzipcode: string | null }, {  }>;
    defraimp_placeofdestinationaddresstelephone: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeofdestinationaddresstelephone: string | null }, {  }>;
    defraimp_placeofdestinationaddressuktelephone: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeofdestinationaddressuktelephone: string | null }, {  }>;
    defraimp_placeofdestinationapprovalnumber: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeofdestinationapprovalnumber: string | null }, {  }>;
    defraimp_placeofdestinationcompanyname: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeofdestinationcompanyname: string | null }, {  }>;
    defraimp_placeofdestinationcountryid_guid: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeofdestinationcountryid_guid: string | null }, { defraimp_placeofdestinationcountryid_formatted?: string }>;
    defraimp_placeofdestinationid: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeofdestinationid: string | null }, {  }>;
    defraimp_placeofdestinationindividualname: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeofdestinationindividualname: string | null }, {  }>;
    defraimp_placeofdestinationintphonecode: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeofdestinationintphonecode: string | null }, {  }>;
    defraimp_placeofdestinationintphonenumber: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeofdestinationintphonenumber: string | null }, {  }>;
    defraimp_placeofdestinationotheridentifier: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeofdestinationotheridentifier: string | null }, {  }>;
    defraimp_placeofdestinationstatus: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeofdestinationstatus: string | null }, {  }>;
    defraimp_placeofdestinationtype: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeofdestinationtype: string | null }, {  }>;
    defraimp_placeoforiginharvestaddressaddressline1: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeoforiginharvestaddressaddressline1: string | null }, {  }>;
    defraimp_placeoforiginharvestaddressaddressline2: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeoforiginharvestaddressaddressline2: string | null }, {  }>;
    defraimp_placeoforiginharvestaddressaddressline3: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeoforiginharvestaddressaddressline3: string | null }, {  }>;
    defraimp_placeoforiginharvestaddresscity: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeoforiginharvestaddresscity: string | null }, {  }>;
    defraimp_placeoforiginharvestaddresscountryid_guid: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeoforiginharvestaddresscountryid_guid: string | null }, { defraimp_placeoforiginharvestaddresscountryid_formatted?: string }>;
    defraimp_placeoforiginharvestaddresscountryisocode: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeoforiginharvestaddresscountryisocode: string | null }, {  }>;
    defraimp_placeoforiginharvestaddressemail: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeoforiginharvestaddressemail: string | null }, {  }>;
    defraimp_placeoforiginharvestaddresspostalzipcode: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeoforiginharvestaddresspostalzipcode: string | null }, {  }>;
    defraimp_placeoforiginharvestaddresstelephone: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeoforiginharvestaddresstelephone: string | null }, {  }>;
    defraimp_placeoforiginharvestaddressuktelephone: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeoforiginharvestaddressuktelephone: string | null }, {  }>;
    defraimp_placeoforiginharvestapprovalnumber: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeoforiginharvestapprovalnumber: string | null }, {  }>;
    defraimp_placeoforiginharvestcompanyname: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeoforiginharvestcompanyname: string | null }, {  }>;
    defraimp_placeoforiginharvestid: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeoforiginharvestid: string | null }, {  }>;
    defraimp_placeoforiginharvestindividualname: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeoforiginharvestindividualname: string | null }, {  }>;
    defraimp_placeoforiginharvestintphonecode: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeoforiginharvestintphonecode: string | null }, {  }>;
    defraimp_placeoforiginharvestintphonenumber: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeoforiginharvestintphonenumber: string | null }, {  }>;
    defraimp_placeoforiginharvestotheridentifier: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeoforiginharvestotheridentifier: string | null }, {  }>;
    defraimp_placeoforiginharveststatus: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeoforiginharveststatus: string | null }, {  }>;
    defraimp_placeoforiginharvesttype: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_placeoforiginharvesttype: string | null }, {  }>;
    defraimp_portofentry: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_portofentry: string | null }, {  }>;
    defraimp_quickviewspacer: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_quickviewspacer: string | null }, {  }>;
    defraimp_responsiblefortransport: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_responsiblefortransport: string | null }, {  }>;
    defraimp_routetransitingstates: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_routetransitingstates: string | null }, {  }>;
    defraimp_status: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_status: defraimp_importernotificationstatus | null }, { defraimp_status_formatted?: string }>;
    defraimp_submissiondate: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_submissiondate: Date | null }, { defraimp_submissiondate_formatted?: string }>;
    defraimp_submittedbydisplayname: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_submittedbydisplayname: string | null }, {  }>;
    defraimp_submittedbyiscontroluser: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_submittedbyiscontroluser: boolean | null }, {  }>;
    defraimp_submittedbyuserid: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_submittedbyuserid: string | null }, {  }>;
    defraimp_transporteraddressaddressline1: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_transporteraddressaddressline1: string | null }, {  }>;
    defraimp_transporteraddressaddressline2: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_transporteraddressaddressline2: string | null }, {  }>;
    defraimp_transporteraddressaddressline3: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_transporteraddressaddressline3: string | null }, {  }>;
    defraimp_transporteraddresscity: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_transporteraddresscity: string | null }, {  }>;
    defraimp_transporteraddresscountryid_guid: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_transporteraddresscountryid_guid: string | null }, { defraimp_transporteraddresscountryid_formatted?: string }>;
    defraimp_transporteraddresscountryisocode: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_transporteraddresscountryisocode: string | null }, {  }>;
    defraimp_transporteraddressemail: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_transporteraddressemail: string | null }, {  }>;
    defraimp_transporteraddresspostalzipcode: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_transporteraddresspostalzipcode: string | null }, {  }>;
    defraimp_transporteraddresstelephone: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_transporteraddresstelephone: string | null }, {  }>;
    defraimp_transporteraddressuktelephone: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_transporteraddressuktelephone: string | null }, {  }>;
    defraimp_transporterapprovalnumber: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_transporterapprovalnumber: string | null }, {  }>;
    defraimp_transportercompanyname: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_transportercompanyname: string | null }, {  }>;
    defraimp_transporterdetailsrequired: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_transporterdetailsrequired: boolean | null }, {  }>;
    defraimp_transporterid: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_transporterid: string | null }, {  }>;
    defraimp_transporterindividualname: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_transporterindividualname: string | null }, {  }>;
    defraimp_transporterinternationalphonecode: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_transporterinternationalphonecode: string | null }, {  }>;
    defraimp_transporterinternationalphonenumber: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_transporterinternationalphonenumber: string | null }, {  }>;
    defraimp_transporterotheridentifier: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_transporterotheridentifier: string | null }, {  }>;
    defraimp_transporterstatus: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_transporterstatus: string | null }, {  }>;
    defraimp_transportertype: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_transportertype: string | null }, {  }>;
    defraimp_type: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_type: defraimp_importernotificationtype | null }, { defraimp_type_formatted?: string }>;
    defraimp_version: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_version: number | null }, {  }>;
    defraimp_veterinaryinformationveterinarydocument: WebAttribute<defraimp_ImporterNotification_Select, { defraimp_veterinaryinformationveterinarydocument: string | null }, {  }>;
    importsequencenumber: WebAttribute<defraimp_ImporterNotification_Select, { importsequencenumber: number | null }, {  }>;
    modifiedby_guid: WebAttribute<defraimp_ImporterNotification_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
    modifiedon: WebAttribute<defraimp_ImporterNotification_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
    modifiedonbehalfby_guid: WebAttribute<defraimp_ImporterNotification_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
    overriddencreatedon: WebAttribute<defraimp_ImporterNotification_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
    ownerid_guid: WebAttribute<defraimp_ImporterNotification_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
    owningbusinessunit_guid: WebAttribute<defraimp_ImporterNotification_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
    owningteam_guid: WebAttribute<defraimp_ImporterNotification_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
    owninguser_guid: WebAttribute<defraimp_ImporterNotification_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
    statecode: WebAttribute<defraimp_ImporterNotification_Select, { statecode: defraimp_importernotification_statecode | null }, { statecode_formatted?: string }>;
    statuscode: WebAttribute<defraimp_ImporterNotification_Select, { statuscode: defraimp_importernotification_statuscode | null }, { statuscode_formatted?: string }>;
    timezoneruleversionnumber: WebAttribute<defraimp_ImporterNotification_Select, { timezoneruleversionnumber: number | null }, {  }>;
    utcconversiontimezonecode: WebAttribute<defraimp_ImporterNotification_Select, { utcconversiontimezonecode: number | null }, {  }>;
    versionnumber: WebAttribute<defraimp_ImporterNotification_Select, { versionnumber: number | null }, {  }>;
  }
  interface defraimp_ImporterNotification_Filter {
    createdby_guid: XQW.Guid;
    createdon: Date;
    createdonbehalfby_guid: XQW.Guid;
    defraimp_arrivaldate: Date;
    defraimp_arrivaltime: string;
    defraimp_commoditiesanimalscertifiedas: defraimp_animalcertifiedas;
    defraimp_commoditiescommodityintendedfor: string;
    defraimp_commoditiesconsignedcountry: string;
    defraimp_commoditiescountryoforigin: string;
    defraimp_commoditiesincludenonablactedanimals: boolean;
    defraimp_commoditiesnumberofanimals: number;
    defraimp_commoditiesregionoforigin: string;
    defraimp_commoditiestotalgrossweight: any;
    defraimp_commoditiestotalnetweight: any;
    defraimp_commoditycomplementid: number;
    defraimp_commoditycomplementname: string;
    defraimp_commoditycomplementstext: string;
    defraimp_commoditydescription: string;
    defraimp_commodityid: string;
    defraimp_commodityidtypes: string;
    defraimp_commodityspeciesclass: string;
    defraimp_commodityspeciesclassname: string;
    defraimp_commodityspeciescommonname: string;
    defraimp_commodityspeciesid: string;
    defraimp_commodityspeciesname: string;
    defraimp_commodityspeciesnomination: string;
    defraimp_commodityspeciestype: string;
    defraimp_complexcommodityselected: boolean;
    defraimp_consignedcountryid_guid: XQW.Guid;
    defraimp_consigneeaddressaddressline1: string;
    defraimp_consigneeaddressaddressline2: string;
    defraimp_consigneeaddressaddressline3: string;
    defraimp_consigneeaddresscity: string;
    defraimp_consigneeaddresscountryid_guid: XQW.Guid;
    defraimp_consigneeaddresscountryisocode: string;
    defraimp_consigneeaddressemail: string;
    defraimp_consigneeaddresspostalzipcode: string;
    defraimp_consigneeaddresstelephone: string;
    defraimp_consigneeaddressuktelephone: string;
    defraimp_consigneeapprovalnumber: string;
    defraimp_consigneecompanyname: string;
    defraimp_consigneeid: string;
    defraimp_consigneeindividualname: string;
    defraimp_consigneeinternationalphonecode: string;
    defraimp_consigneeinternationalphonenumber: string;
    defraimp_consigneeotheridentifier: string;
    defraimp_consigneestatus: string;
    defraimp_consigneetype: string;
    defraimp_consignoraddressaddressline1: string;
    defraimp_consignoraddressaddressline2: string;
    defraimp_consignoraddressaddressline3: string;
    defraimp_consignoraddresscity: string;
    defraimp_consignoraddresscountryid_guid: XQW.Guid;
    defraimp_consignoraddresscountryisocode: string;
    defraimp_consignoraddressemail: string;
    defraimp_consignoraddresspostalzipcode: string;
    defraimp_consignoraddresstelephone: string;
    defraimp_consignoraddressuktelephone: string;
    defraimp_consignorapprovalnumber: string;
    defraimp_consignorcompanyname: string;
    defraimp_consignorid: string;
    defraimp_consignorindividualname: string;
    defraimp_consignorinternationalphonecode: string;
    defraimp_consignorinternationalphonenumber: string;
    defraimp_consignorotheridentifier: string;
    defraimp_consignorstatus: string;
    defraimp_consignortwoaddressaddressline1: string;
    defraimp_consignortwoaddressaddressline2: string;
    defraimp_consignortwoaddressaddressline3: string;
    defraimp_consignortwoaddresscity: string;
    defraimp_consignortwoaddresscountry_guid: XQW.Guid;
    defraimp_consignortwoaddresscountryisocode: string;
    defraimp_consignortwoaddressemail: string;
    defraimp_consignortwoaddresspostalzipcode: string;
    defraimp_consignortwoaddresstelephone: string;
    defraimp_consignortwoaddressuktelephone: string;
    defraimp_consignortwoapprovalnumber: string;
    defraimp_consignortwocompanyname: string;
    defraimp_consignortwoid: string;
    defraimp_consignortwoindividualname: string;
    defraimp_consignortwointernationalphonecode: string;
    defraimp_consignortwointernationalphonenumber: string;
    defraimp_consignortwootheridentifier: string;
    defraimp_consignortwostatus: string;
    defraimp_consignortwotype: string;
    defraimp_consignortype: string;
    defraimp_countryoforiginid_guid: XQW.Guid;
    defraimp_cphnumber: string;
    defraimp_departuredate: Date;
    defraimp_departuretime: string;
    defraimp_estimatedjourneytimeinminutes: any;
    defraimp_formattedcommoditycomplementstext: string;
    defraimp_formattedidentificationofanimalstext: string;
    defraimp_identificationofanimalstext: string;
    defraimp_importeraddressaddressline1: string;
    defraimp_importeraddressaddressline2: string;
    defraimp_importeraddressaddressline3: string;
    defraimp_importeraddresscity: string;
    defraimp_importeraddresscountryid_guid: XQW.Guid;
    defraimp_importeraddresscountryisocode: string;
    defraimp_importeraddressemail: string;
    defraimp_importeraddresspostalzipcode: string;
    defraimp_importeraddresstelephone: string;
    defraimp_importeraddressuktelephone: string;
    defraimp_importerapprovalnumber: string;
    defraimp_importercompanyname: string;
    defraimp_importerid: string;
    defraimp_importerindividualname: string;
    defraimp_importerinternationalphonecode: string;
    defraimp_importerinternationalphonenumber: string;
    defraimp_importernotificationid: XQW.Guid;
    defraimp_importerotheridentifier: string;
    defraimp_importerstatus: string;
    defraimp_importertype: string;
    defraimp_importingfromcharity: boolean;
    defraimp_ipaffsid: number;
    defraimp_isplaceofdestinationthepermanentaddress: boolean;
    defraimp_lastupdated: Date;
    defraimp_lastupdatedbydisplayname: string;
    defraimp_lastupdatedbyuserid: string;
    defraimp_meansoftransportfromentrypointdocument: string;
    defraimp_meansoftransportfromentrypointid: string;
    defraimp_meansoftransportfromentrypointtype: string;
    defraimp_name: string;
    defraimp_personresponsibleaddress: string;
    defraimp_personresponsiblecity: string;
    defraimp_personresponsiblecompanyid: string;
    defraimp_personresponsiblecompanyname: string;
    defraimp_personresponsiblecontactid: string;
    defraimp_personresponsiblecountry: string;
    defraimp_personresponsiblecountryid_guid: XQW.Guid;
    defraimp_personresponsiblecounty: string;
    defraimp_personresponsibleemail: string;
    defraimp_personresponsiblefax: string;
    defraimp_personresponsibleid: string;
    defraimp_personresponsiblename: string;
    defraimp_personresponsiblephone: string;
    defraimp_personresponsiblepostcode: string;
    defraimp_personresponsibletype: string;
    defraimp_placeofdestinationaddressaddressline1: string;
    defraimp_placeofdestinationaddressaddressline2: string;
    defraimp_placeofdestinationaddressaddressline3: string;
    defraimp_placeofdestinationaddresscity: string;
    defraimp_placeofdestinationaddresscountryisocode: string;
    defraimp_placeofdestinationaddressemail: string;
    defraimp_placeofdestinationaddresspostalzipcode: string;
    defraimp_placeofdestinationaddresstelephone: string;
    defraimp_placeofdestinationaddressuktelephone: string;
    defraimp_placeofdestinationapprovalnumber: string;
    defraimp_placeofdestinationcompanyname: string;
    defraimp_placeofdestinationcountryid_guid: XQW.Guid;
    defraimp_placeofdestinationid: string;
    defraimp_placeofdestinationindividualname: string;
    defraimp_placeofdestinationintphonecode: string;
    defraimp_placeofdestinationintphonenumber: string;
    defraimp_placeofdestinationotheridentifier: string;
    defraimp_placeofdestinationstatus: string;
    defraimp_placeofdestinationtype: string;
    defraimp_placeoforiginharvestaddressaddressline1: string;
    defraimp_placeoforiginharvestaddressaddressline2: string;
    defraimp_placeoforiginharvestaddressaddressline3: string;
    defraimp_placeoforiginharvestaddresscity: string;
    defraimp_placeoforiginharvestaddresscountryid_guid: XQW.Guid;
    defraimp_placeoforiginharvestaddresscountryisocode: string;
    defraimp_placeoforiginharvestaddressemail: string;
    defraimp_placeoforiginharvestaddresspostalzipcode: string;
    defraimp_placeoforiginharvestaddresstelephone: string;
    defraimp_placeoforiginharvestaddressuktelephone: string;
    defraimp_placeoforiginharvestapprovalnumber: string;
    defraimp_placeoforiginharvestcompanyname: string;
    defraimp_placeoforiginharvestid: string;
    defraimp_placeoforiginharvestindividualname: string;
    defraimp_placeoforiginharvestintphonecode: string;
    defraimp_placeoforiginharvestintphonenumber: string;
    defraimp_placeoforiginharvestotheridentifier: string;
    defraimp_placeoforiginharveststatus: string;
    defraimp_placeoforiginharvesttype: string;
    defraimp_portofentry: string;
    defraimp_quickviewspacer: string;
    defraimp_responsiblefortransport: string;
    defraimp_routetransitingstates: string;
    defraimp_status: defraimp_importernotificationstatus;
    defraimp_submissiondate: Date;
    defraimp_submittedbydisplayname: string;
    defraimp_submittedbyiscontroluser: boolean;
    defraimp_submittedbyuserid: string;
    defraimp_transporteraddressaddressline1: string;
    defraimp_transporteraddressaddressline2: string;
    defraimp_transporteraddressaddressline3: string;
    defraimp_transporteraddresscity: string;
    defraimp_transporteraddresscountryid_guid: XQW.Guid;
    defraimp_transporteraddresscountryisocode: string;
    defraimp_transporteraddressemail: string;
    defraimp_transporteraddresspostalzipcode: string;
    defraimp_transporteraddresstelephone: string;
    defraimp_transporteraddressuktelephone: string;
    defraimp_transporterapprovalnumber: string;
    defraimp_transportercompanyname: string;
    defraimp_transporterdetailsrequired: boolean;
    defraimp_transporterid: string;
    defraimp_transporterindividualname: string;
    defraimp_transporterinternationalphonecode: string;
    defraimp_transporterinternationalphonenumber: string;
    defraimp_transporterotheridentifier: string;
    defraimp_transporterstatus: string;
    defraimp_transportertype: string;
    defraimp_type: defraimp_importernotificationtype;
    defraimp_version: number;
    defraimp_veterinaryinformationveterinarydocument: string;
    importsequencenumber: number;
    modifiedby_guid: XQW.Guid;
    modifiedon: Date;
    modifiedonbehalfby_guid: XQW.Guid;
    overriddencreatedon: Date;
    ownerid_guid: XQW.Guid;
    owningbusinessunit_guid: XQW.Guid;
    owningteam_guid: XQW.Guid;
    owninguser_guid: XQW.Guid;
    statecode: defraimp_importernotification_statecode;
    statuscode: defraimp_importernotification_statuscode;
    timezoneruleversionnumber: number;
    utcconversiontimezonecode: number;
    versionnumber: number;
  }
  interface defraimp_ImporterNotification_Expand {
    defraimp_defraimp_importernotification_defraimp_importapplication_PrimaryImporterNotificationId: WebExpand<defraimp_ImporterNotification_Expand, defraimp_importapplication_Select, defraimp_importapplication_Filter, { defraimp_defraimp_importernotification_defraimp_importapplication_PrimaryImporterNotificationId: defraimp_importapplication_Result[] }>;
    defraimp_defraimp_importernotification_defraimp_matchrecord_ImporterNotification: WebExpand<defraimp_ImporterNotification_Expand, defraimp_matchrecord_Select, defraimp_matchrecord_Filter, { defraimp_defraimp_importernotification_defraimp_matchrecord_ImporterNotification: defraimp_matchrecord_Result[] }>;
  }
  interface defraimp_ImporterNotification_FormattedResult {
    createdby_formatted?: string;
    createdon_formatted?: string;
    createdonbehalfby_formatted?: string;
    defraimp_arrivaldate_formatted?: string;
    defraimp_commoditiesanimalscertifiedas_formatted?: string;
    defraimp_consignedcountryid_formatted?: string;
    defraimp_consigneeaddresscountryid_formatted?: string;
    defraimp_consignoraddresscountryid_formatted?: string;
    defraimp_consignortwoaddresscountry_formatted?: string;
    defraimp_countryoforiginid_formatted?: string;
    defraimp_departuredate_formatted?: string;
    defraimp_importeraddresscountryid_formatted?: string;
    defraimp_lastupdated_formatted?: string;
    defraimp_personresponsiblecountryid_formatted?: string;
    defraimp_placeofdestinationcountryid_formatted?: string;
    defraimp_placeoforiginharvestaddresscountryid_formatted?: string;
    defraimp_status_formatted?: string;
    defraimp_submissiondate_formatted?: string;
    defraimp_transporteraddresscountryid_formatted?: string;
    defraimp_type_formatted?: string;
    modifiedby_formatted?: string;
    modifiedon_formatted?: string;
    modifiedonbehalfby_formatted?: string;
    overriddencreatedon_formatted?: string;
    ownerid_formatted?: string;
    owningbusinessunit_formatted?: string;
    owningteam_formatted?: string;
    owninguser_formatted?: string;
    statecode_formatted?: string;
    statuscode_formatted?: string;
  }
  interface defraimp_ImporterNotification_Result extends defraimp_ImporterNotification_Base, defraimp_ImporterNotification_Relationships {
    "@odata.etag": string;
    createdby_guid: string | null;
    createdonbehalfby_guid: string | null;
    defraimp_consignedcountryid_guid: string | null;
    defraimp_consigneeaddresscountryid_guid: string | null;
    defraimp_consignoraddresscountryid_guid: string | null;
    defraimp_consignortwoaddresscountry_guid: string | null;
    defraimp_countryoforiginid_guid: string | null;
    defraimp_importeraddresscountryid_guid: string | null;
    defraimp_personresponsiblecountryid_guid: string | null;
    defraimp_placeofdestinationcountryid_guid: string | null;
    defraimp_placeoforiginharvestaddresscountryid_guid: string | null;
    defraimp_transporteraddresscountryid_guid: string | null;
    modifiedby_guid: string | null;
    modifiedonbehalfby_guid: string | null;
    ownerid_guid: string | null;
    owningbusinessunit_guid: string | null;
    owningteam_guid: string | null;
    owninguser_guid: string | null;
  }
  interface defraimp_ImporterNotification_RelatedOne {
  }
  interface defraimp_ImporterNotification_RelatedMany {
    defraimp_defraimp_importernotification_defraimp_importapplication_PrimaryImporterNotificationId: WebMappingRetrieve<WebApi.defraimp_importapplication_Select,WebApi.defraimp_importapplication_Expand,WebApi.defraimp_importapplication_Filter,WebApi.defraimp_importapplication_Fixed,WebApi.defraimp_importapplication_Result,WebApi.defraimp_importapplication_FormattedResult>;
    defraimp_defraimp_importernotification_defraimp_matchrecord_ImporterNotification: WebMappingRetrieve<WebApi.defraimp_matchrecord_Select,WebApi.defraimp_matchrecord_Expand,WebApi.defraimp_matchrecord_Filter,WebApi.defraimp_matchrecord_Fixed,WebApi.defraimp_matchrecord_Result,WebApi.defraimp_matchrecord_FormattedResult>;
  }
}
interface WebEntitiesRetrieve {
  defraimp_importernotifications: WebMappingRetrieve<WebApi.defraimp_ImporterNotification_Select,WebApi.defraimp_ImporterNotification_Expand,WebApi.defraimp_ImporterNotification_Filter,WebApi.defraimp_ImporterNotification_Fixed,WebApi.defraimp_ImporterNotification_Result,WebApi.defraimp_ImporterNotification_FormattedResult>;
}
interface WebEntitiesRelated {
  defraimp_importernotifications: WebMappingRelated<WebApi.defraimp_ImporterNotification_RelatedOne,WebApi.defraimp_ImporterNotification_RelatedMany>;
}
interface WebEntitiesCUDA {
  defraimp_importernotifications: WebMappingCUDA<WebApi.defraimp_ImporterNotification_Create,WebApi.defraimp_ImporterNotification_Update,WebApi.defraimp_ImporterNotification_Select>;
}
