declare namespace WebApi {
  interface defraimp_importapplication_Base extends WebEntity {
    createdon?: Date | null;
    defraimp_animalcertifiedas?: defraimp_animalcertifiedas | null;
    defraimp_article15reimport?: boolean | null;
    defraimp_article8monitored?: boolean | null;
    defraimp_certificatecompliantfirsttime?: boolean | null;
    defraimp_certificatenoncompliancereason?: defraimp_importapplication_defraimp_certificatenoncompliancereason | null;
    defraimp_certificatenoncompliancereasonother?: string | null;
    defraimp_certificatenumber?: string | null;
    defraimp_certificateverified?: boolean | null;
    defraimp_charityaddresscity?: string | null;
    defraimp_charityaddressline1?: string | null;
    defraimp_charityaddressline2?: string | null;
    defraimp_charityaddressline3?: string | null;
    defraimp_charityaddresspostcode?: string | null;
    defraimp_charityname?: string | null;
    defraimp_chedacertificatenumber?: string | null;
    defraimp_commoditycode?: string | null;
    defraimp_commodityidentifiers?: string | null;
    defraimp_commoditynotes?: string | null;
    defraimp_completionsummary?: string | null;
    defraimp_consignmentconforming?: boolean | null;
    defraimp_contactedduetononcompliance?: boolean | null;
    defraimp_containernumber?: string | null;
    defraimp_countryoforiginisocode?: string | null;
    defraimp_datecompleted?: Date | null;
    defraimp_dateconfirmedontraces?: Date | null;
    defraimp_dateconsignmentreceived?: Date | null;
    defraimp_dateemailsent?: Date | null;
    defraimp_dateimportercontacted?: Date | null;
    defraimp_dateiv66received?: Date | null;
    defraimp_dateofconfirmationfromimporter?: Date | null;
    defraimp_dateofconfirmationtobip?: Date | null;
    defraimp_dateofemailtoimporter?: Date | null;
    defraimp_dateofimport?: Date | null;
    defraimp_datepodrequested?: Date | null;
    defraimp_datetelephonecallmade?: Date | null;
    defraimp_docomcategory?: defraimp_importapplication_defraimp_docomcategory | null;
    defraimp_docomreference?: string | null;
    defraimp_documentationnumber?: string | null;
    defraimp_documentnumber?: string | null;
    defraimp_gbimporthealthcertificate?: string | null;
    defraimp_generalcomments?: string | null;
    defraimp_healthcertificatenumber?: string | null;
    defraimp_importapplicationid?: string | null;
    defraimp_importapplicationtype?: defraimp_importapplication_defraimp_importapplicationtype | null;
    defraimp_importeraddress1?: string | null;
    defraimp_importeraddress2?: string | null;
    defraimp_importeraddress3?: string | null;
    defraimp_importeraddresscity?: string | null;
    defraimp_importeraddresspostcode?: string | null;
    defraimp_importercontactname?: string | null;
    defraimp_importercphnumber?: string | null;
    defraimp_importeremail?: string | null;
    defraimp_importerorganisation?: string | null;
    defraimp_importertelephone?: string | null;
    defraimp_importingfromcharity?: boolean | null;
    defraimp_importrecordcounted?: boolean | null;
    defraimp_importrisklevelstatus?: defraimp_importapplication_defraimp_importrisklevelstatus | null;
    defraimp_inspectioncompleted?: boolean | null;
    defraimp_inspectiondeclinedreason?: string | null;
    defraimp_inspectionoutcome?: defraimp_importapplication_defraimp_inspectionoutcome | null;
    defraimp_inspectionrequested?: boolean | null;
    defraimp_inspectionrequired?: defraimp_importapplication_defraimp_inspectionrequired | null;
    defraimp_inspectionrequiredoriginalvalue?: number | null;
    defraimp_inspectionrequiredreason?: defraimp_importapplication_defraimp_inspectionrequiredreason | null;
    defraimp_inspectionrequiredreasonoriginalvalue?: number | null;
    defraimp_ipaffsspeciesid?: string | null;
    defraimp_isnoncompliantcalculated?: boolean | null;
    defraimp_itahcreference?: string | null;
    defraimp_iv65responseduedate?: Date | null;
    defraimp_iv65responsereceiveddate?: Date | null;
    defraimp_iv65sent?: boolean | null;
    defraimp_iv65sentdate?: Date | null;
    defraimp_iv66receivedinrequiredtimescale?: boolean | null;
    defraimp_localreferencenumber?: string | null;
    defraimp_manualpostimportcheckdecision?: defraimp_importapplication_defraimp_manualpostimportcheckdecision | null;
    defraimp_matchingvalidated?: boolean | null;
    defraimp_meansoftransport?: defraimp_meansoftransport | null;
    defraimp_movedtocompletiondate?: Date | null;
    defraimp_movetocompletion?: boolean | null;
    defraimp_name?: string | null;
    defraimp_noncomplianceothercomments?: string | null;
    defraimp_noncompliancestatus?: defraimp_noncompliancestatus | null;
    defraimp_notifiedtobipwithin15days?: boolean | null;
    defraimp_permanentdestinationaddresscity?: string | null;
    defraimp_permanentdestinationaddressline1?: string | null;
    defraimp_permanentdestinationaddressline2?: string | null;
    defraimp_permanentdestinationaddressline3?: string | null;
    defraimp_permanentdestinationaddresspostcode?: string | null;
    defraimp_permanentdestinationcontactname?: string | null;
    defraimp_permanentdestinationemail?: string | null;
    defraimp_permanentdestinationorganisation?: string | null;
    defraimp_permanentdestinationtelephone?: string | null;
    defraimp_pimsstatus?: defraimp_pimsstatus | null;
    defraimp_placeofdestinationaddresscity?: string | null;
    defraimp_placeofdestinationaddressline1?: string | null;
    defraimp_placeofdestinationaddressline2?: string | null;
    defraimp_placeofdestinationaddressline3?: string | null;
    defraimp_placeofdestinationaddresspostcode?: string | null;
    defraimp_placeofdestinationcontactname?: string | null;
    defraimp_placeofdestinationemail?: string | null;
    defraimp_placeofdestinationorganisation?: string | null;
    defraimp_placeofdestinationtelephone?: string | null;
    defraimp_placeoforiginaddresscity?: string | null;
    defraimp_placeoforiginaddressline1?: string | null;
    defraimp_placeoforiginaddressline2?: string | null;
    defraimp_placeoforiginaddressline3?: string | null;
    defraimp_placeoforiginaddresspostcode?: string | null;
    defraimp_placeoforigincontactname?: string | null;
    defraimp_placeoforiginorganisation?: string | null;
    defraimp_placeoforigintrustlevel?: defraimp_trustlevel | null;
    defraimp_pointofentry?: string | null;
    defraimp_purpose?: defraimp_importapplication_defraimp_purpose | null;
    defraimp_quantity?: number | null;
    defraimp_replyreceived?: defraimp_importapplication_defraimp_replyreceived | null;
    defraimp_requestedpod?: defraimp_importapplication_defraimp_requestedpod | null;
    defraimp_resettrustleveltobronze?: boolean | null;
    defraimp_risklevelverified?: boolean | null;
    defraimp_sealnumber?: string | null;
    defraimp_tracesexporthealthcertificate?: string | null;
    defraimp_tracesspeciesid?: string | null;
    defraimp_transporteraddress?: string | null;
    defraimp_transporteraddresscity?: string | null;
    defraimp_transporteraddressline1?: string | null;
    defraimp_transporteraddressline2?: string | null;
    defraimp_transporteraddressline3?: string | null;
    defraimp_transporteraddresspostcode?: string | null;
    defraimp_transporteremail?: string | null;
    defraimp_transportername?: string | null;
    defraimp_transportertelephone?: string | null;
    defraimp_transportertype?: string | null;
    defraimp_type?: string | null;
    defraimp_typesofnoncompliance?: defraimp_noncompliancetype | null;
    defraimp_unit?: string | null;
    defraimp_warbleflytreatmentdeclarationreceiveddate?: Date | null;
    defraimp_warbleflytreatmentdeclarationrequired?: boolean | null;
    defraimp_weight?: string | null;
    defraimp_workschedulenumber?: string | null;
    importsequencenumber?: number | null;
    modifiedon?: Date | null;
    overriddencreatedon?: Date | null;
    processid?: string | null;
    stageid?: string | null;
    statecode?: defraimp_importapplication_statecode | null;
    statuscode?: defraimp_importapplication_statuscode | null;
    timezoneruleversionnumber?: number | null;
    traversedpath?: string | null;
    utcconversiontimezonecode?: number | null;
    versionnumber?: number | null;
  }
  interface defraimp_importapplication_Relationships {
    defraimp_PlaceofOriginid?: defraimp_placeoforigin_Result | null;
    defraimp_PotentiallyRelatedImportRecords?: defraimp_matchrecord_Result[] | null;
    defraimp_PrimaryITAHCId?: defraimp_itahc_Result | null;
    defraimp_PrimaryImporterNotificationId?: defraimp_ImporterNotification_Result | null;
    defraimp_defraimp_importapplication_defraimp_importinspection_RelatedImportApplication?: defraimp_importinspection_Result[] | null;
    defraimp_defraimp_importapplication_defraimp_itahc?: defraimp_itahc_Result[] | null;
    defraimp_defraimp_matchrecord_defraimp_Im?: defraimp_matchrecord_Result[] | null;
    defraimp_importapplication_defraimp_importqueries?: defraimp_importquery_Result[] | null;
  }
  interface defraimp_importapplication extends defraimp_importapplication_Base, defraimp_importapplication_Relationships {
    defraimp_CharityAddressCountry_bind$defra_countries?: string | null;
    defraimp_CommodityTypeId_bind$defraexp_commoditytypes?: string | null;
    defraimp_CountryofOriginId_bind$defra_countries?: string | null;
    defraimp_DevolvedOfficeId_bind$teams?: string | null;
    defraimp_IRMSPersonResponsible_bind$systemusers?: string | null;
    defraimp_ImporterAddressCountryID_bind$defra_countries?: string | null;
    defraimp_PermanentDestinationAddressCounId_bind$defra_countries?: string | null;
    defraimp_PlaceofOriginCountryID_bind$defra_countries?: string | null;
    defraimp_PlaceofOriginid_bind$defraimp_placeoforigins?: string | null;
    defraimp_PreviousImportRiskLevelId_bind$defraimp_importrisklevels?: string | null;
    defraimp_PrimaryCVEDId_bind$defraimp_cveds?: string | null;
    defraimp_PrimaryITAHCId_bind$defraimp_itahcs?: string | null;
    defraimp_PrimaryImporterNotificationId_bind$defraimp_importernotifications?: string | null;
    defraimp_RegionAreaAllocatedtoId_bind$defraimp_apharegions?: string | null;
    defraimp_RegistrantOrganisationId_bind$accounts?: string | null;
    defraimp_destinationaddresscountryId_bind$defra_countries?: string | null;
    defraimp_importrisklevelid_bind$defraimp_importrisklevels?: string | null;
    defraimp_imptypeid_bind$defraimp_imptypes?: string | null;
    defraimp_previousplaceoforiginid_bind$defraimp_placeoforigins?: string | null;
    defraimp_transporteraddresscountryid_bind$defra_countries?: string | null;
    ownerid_bind$systemusers?: string | null;
    ownerid_bind$teams?: string | null;
    stageid_bind$processstages?: string | null;
  }
  interface defraimp_importapplication_Create extends defraimp_importapplication {
  }
  interface defraimp_importapplication_Update extends defraimp_importapplication {
  }
  interface defraimp_importapplication_Select {
    createdby_guid: WebAttribute<defraimp_importapplication_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
    createdon: WebAttribute<defraimp_importapplication_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
    createdonbehalfby_guid: WebAttribute<defraimp_importapplication_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
    defraimp_animalcertifiedas: WebAttribute<defraimp_importapplication_Select, { defraimp_animalcertifiedas: defraimp_animalcertifiedas | null }, { defraimp_animalcertifiedas_formatted?: string }>;
    defraimp_article15reimport: WebAttribute<defraimp_importapplication_Select, { defraimp_article15reimport: boolean | null }, {  }>;
    defraimp_article8monitored: WebAttribute<defraimp_importapplication_Select, { defraimp_article8monitored: boolean | null }, {  }>;
    defraimp_certificatecompliantfirsttime: WebAttribute<defraimp_importapplication_Select, { defraimp_certificatecompliantfirsttime: boolean | null }, {  }>;
    defraimp_certificatenoncompliancereason: WebAttribute<defraimp_importapplication_Select, { defraimp_certificatenoncompliancereason: defraimp_importapplication_defraimp_certificatenoncompliancereason | null }, { defraimp_certificatenoncompliancereason_formatted?: string }>;
    defraimp_certificatenoncompliancereasonother: WebAttribute<defraimp_importapplication_Select, { defraimp_certificatenoncompliancereasonother: string | null }, {  }>;
    defraimp_certificatenumber: WebAttribute<defraimp_importapplication_Select, { defraimp_certificatenumber: string | null }, {  }>;
    defraimp_certificateverified: WebAttribute<defraimp_importapplication_Select, { defraimp_certificateverified: boolean | null }, {  }>;
    defraimp_charityaddresscity: WebAttribute<defraimp_importapplication_Select, { defraimp_charityaddresscity: string | null }, {  }>;
    defraimp_charityaddresscountry_guid: WebAttribute<defraimp_importapplication_Select, { defraimp_charityaddresscountry_guid: string | null }, { defraimp_charityaddresscountry_formatted?: string }>;
    defraimp_charityaddressline1: WebAttribute<defraimp_importapplication_Select, { defraimp_charityaddressline1: string | null }, {  }>;
    defraimp_charityaddressline2: WebAttribute<defraimp_importapplication_Select, { defraimp_charityaddressline2: string | null }, {  }>;
    defraimp_charityaddressline3: WebAttribute<defraimp_importapplication_Select, { defraimp_charityaddressline3: string | null }, {  }>;
    defraimp_charityaddresspostcode: WebAttribute<defraimp_importapplication_Select, { defraimp_charityaddresspostcode: string | null }, {  }>;
    defraimp_charityname: WebAttribute<defraimp_importapplication_Select, { defraimp_charityname: string | null }, {  }>;
    defraimp_chedacertificatenumber: WebAttribute<defraimp_importapplication_Select, { defraimp_chedacertificatenumber: string | null }, {  }>;
    defraimp_commoditycode: WebAttribute<defraimp_importapplication_Select, { defraimp_commoditycode: string | null }, {  }>;
    defraimp_commodityidentifiers: WebAttribute<defraimp_importapplication_Select, { defraimp_commodityidentifiers: string | null }, {  }>;
    defraimp_commoditynotes: WebAttribute<defraimp_importapplication_Select, { defraimp_commoditynotes: string | null }, {  }>;
    defraimp_commoditytypeid_guid: WebAttribute<defraimp_importapplication_Select, { defraimp_commoditytypeid_guid: string | null }, { defraimp_commoditytypeid_formatted?: string }>;
    defraimp_completionsummary: WebAttribute<defraimp_importapplication_Select, { defraimp_completionsummary: string | null }, {  }>;
    defraimp_consignmentconforming: WebAttribute<defraimp_importapplication_Select, { defraimp_consignmentconforming: boolean | null }, {  }>;
    defraimp_contactedduetononcompliance: WebAttribute<defraimp_importapplication_Select, { defraimp_contactedduetononcompliance: boolean | null }, {  }>;
    defraimp_containernumber: WebAttribute<defraimp_importapplication_Select, { defraimp_containernumber: string | null }, {  }>;
    defraimp_countryoforiginid_guid: WebAttribute<defraimp_importapplication_Select, { defraimp_countryoforiginid_guid: string | null }, { defraimp_countryoforiginid_formatted?: string }>;
    defraimp_countryoforiginisocode: WebAttribute<defraimp_importapplication_Select, { defraimp_countryoforiginisocode: string | null }, {  }>;
    defraimp_datecompleted: WebAttribute<defraimp_importapplication_Select, { defraimp_datecompleted: Date | null }, { defraimp_datecompleted_formatted?: string }>;
    defraimp_dateconfirmedontraces: WebAttribute<defraimp_importapplication_Select, { defraimp_dateconfirmedontraces: Date | null }, { defraimp_dateconfirmedontraces_formatted?: string }>;
    defraimp_dateconsignmentreceived: WebAttribute<defraimp_importapplication_Select, { defraimp_dateconsignmentreceived: Date | null }, { defraimp_dateconsignmentreceived_formatted?: string }>;
    defraimp_dateemailsent: WebAttribute<defraimp_importapplication_Select, { defraimp_dateemailsent: Date | null }, { defraimp_dateemailsent_formatted?: string }>;
    defraimp_dateimportercontacted: WebAttribute<defraimp_importapplication_Select, { defraimp_dateimportercontacted: Date | null }, { defraimp_dateimportercontacted_formatted?: string }>;
    defraimp_dateiv66received: WebAttribute<defraimp_importapplication_Select, { defraimp_dateiv66received: Date | null }, { defraimp_dateiv66received_formatted?: string }>;
    defraimp_dateofconfirmationfromimporter: WebAttribute<defraimp_importapplication_Select, { defraimp_dateofconfirmationfromimporter: Date | null }, { defraimp_dateofconfirmationfromimporter_formatted?: string }>;
    defraimp_dateofconfirmationtobip: WebAttribute<defraimp_importapplication_Select, { defraimp_dateofconfirmationtobip: Date | null }, { defraimp_dateofconfirmationtobip_formatted?: string }>;
    defraimp_dateofemailtoimporter: WebAttribute<defraimp_importapplication_Select, { defraimp_dateofemailtoimporter: Date | null }, { defraimp_dateofemailtoimporter_formatted?: string }>;
    defraimp_dateofimport: WebAttribute<defraimp_importapplication_Select, { defraimp_dateofimport: Date | null }, { defraimp_dateofimport_formatted?: string }>;
    defraimp_datepodrequested: WebAttribute<defraimp_importapplication_Select, { defraimp_datepodrequested: Date | null }, { defraimp_datepodrequested_formatted?: string }>;
    defraimp_datetelephonecallmade: WebAttribute<defraimp_importapplication_Select, { defraimp_datetelephonecallmade: Date | null }, { defraimp_datetelephonecallmade_formatted?: string }>;
    defraimp_destinationaddresscountryid_guid: WebAttribute<defraimp_importapplication_Select, { defraimp_destinationaddresscountryid_guid: string | null }, { defraimp_destinationaddresscountryid_formatted?: string }>;
    defraimp_devolvedofficeid_guid: WebAttribute<defraimp_importapplication_Select, { defraimp_devolvedofficeid_guid: string | null }, { defraimp_devolvedofficeid_formatted?: string }>;
    defraimp_docomcategory: WebAttribute<defraimp_importapplication_Select, { defraimp_docomcategory: defraimp_importapplication_defraimp_docomcategory | null }, { defraimp_docomcategory_formatted?: string }>;
    defraimp_docomreference: WebAttribute<defraimp_importapplication_Select, { defraimp_docomreference: string | null }, {  }>;
    defraimp_documentationnumber: WebAttribute<defraimp_importapplication_Select, { defraimp_documentationnumber: string | null }, {  }>;
    defraimp_documentnumber: WebAttribute<defraimp_importapplication_Select, { defraimp_documentnumber: string | null }, {  }>;
    defraimp_gbimporthealthcertificate: WebAttribute<defraimp_importapplication_Select, { defraimp_gbimporthealthcertificate: string | null }, {  }>;
    defraimp_generalcomments: WebAttribute<defraimp_importapplication_Select, { defraimp_generalcomments: string | null }, {  }>;
    defraimp_healthcertificatenumber: WebAttribute<defraimp_importapplication_Select, { defraimp_healthcertificatenumber: string | null }, {  }>;
    defraimp_importapplicationid: WebAttribute<defraimp_importapplication_Select, { defraimp_importapplicationid: string | null }, {  }>;
    defraimp_importapplicationtype: WebAttribute<defraimp_importapplication_Select, { defraimp_importapplicationtype: defraimp_importapplication_defraimp_importapplicationtype | null }, { defraimp_importapplicationtype_formatted?: string }>;
    defraimp_importeraddress1: WebAttribute<defraimp_importapplication_Select, { defraimp_importeraddress1: string | null }, {  }>;
    defraimp_importeraddress2: WebAttribute<defraimp_importapplication_Select, { defraimp_importeraddress2: string | null }, {  }>;
    defraimp_importeraddress3: WebAttribute<defraimp_importapplication_Select, { defraimp_importeraddress3: string | null }, {  }>;
    defraimp_importeraddresscity: WebAttribute<defraimp_importapplication_Select, { defraimp_importeraddresscity: string | null }, {  }>;
    defraimp_importeraddresscountryid_guid: WebAttribute<defraimp_importapplication_Select, { defraimp_importeraddresscountryid_guid: string | null }, { defraimp_importeraddresscountryid_formatted?: string }>;
    defraimp_importeraddresspostcode: WebAttribute<defraimp_importapplication_Select, { defraimp_importeraddresspostcode: string | null }, {  }>;
    defraimp_importercontactname: WebAttribute<defraimp_importapplication_Select, { defraimp_importercontactname: string | null }, {  }>;
    defraimp_importercphnumber: WebAttribute<defraimp_importapplication_Select, { defraimp_importercphnumber: string | null }, {  }>;
    defraimp_importeremail: WebAttribute<defraimp_importapplication_Select, { defraimp_importeremail: string | null }, {  }>;
    defraimp_importerorganisation: WebAttribute<defraimp_importapplication_Select, { defraimp_importerorganisation: string | null }, {  }>;
    defraimp_importertelephone: WebAttribute<defraimp_importapplication_Select, { defraimp_importertelephone: string | null }, {  }>;
    defraimp_importingfromcharity: WebAttribute<defraimp_importapplication_Select, { defraimp_importingfromcharity: boolean | null }, {  }>;
    defraimp_importrecordcounted: WebAttribute<defraimp_importapplication_Select, { defraimp_importrecordcounted: boolean | null }, {  }>;
    defraimp_importrisklevelid_guid: WebAttribute<defraimp_importapplication_Select, { defraimp_importrisklevelid_guid: string | null }, { defraimp_importrisklevelid_formatted?: string }>;
    defraimp_importrisklevelstatus: WebAttribute<defraimp_importapplication_Select, { defraimp_importrisklevelstatus: defraimp_importapplication_defraimp_importrisklevelstatus | null }, { defraimp_importrisklevelstatus_formatted?: string }>;
    defraimp_imptypeid_guid: WebAttribute<defraimp_importapplication_Select, { defraimp_imptypeid_guid: string | null }, { defraimp_imptypeid_formatted?: string }>;
    defraimp_inspectioncompleted: WebAttribute<defraimp_importapplication_Select, { defraimp_inspectioncompleted: boolean | null }, {  }>;
    defraimp_inspectiondeclinedreason: WebAttribute<defraimp_importapplication_Select, { defraimp_inspectiondeclinedreason: string | null }, {  }>;
    defraimp_inspectionoutcome: WebAttribute<defraimp_importapplication_Select, { defraimp_inspectionoutcome: defraimp_importapplication_defraimp_inspectionoutcome | null }, { defraimp_inspectionoutcome_formatted?: string }>;
    defraimp_inspectionrequested: WebAttribute<defraimp_importapplication_Select, { defraimp_inspectionrequested: boolean | null }, {  }>;
    defraimp_inspectionrequired: WebAttribute<defraimp_importapplication_Select, { defraimp_inspectionrequired: defraimp_importapplication_defraimp_inspectionrequired | null }, { defraimp_inspectionrequired_formatted?: string }>;
    defraimp_inspectionrequiredoriginalvalue: WebAttribute<defraimp_importapplication_Select, { defraimp_inspectionrequiredoriginalvalue: number | null }, {  }>;
    defraimp_inspectionrequiredreason: WebAttribute<defraimp_importapplication_Select, { defraimp_inspectionrequiredreason: defraimp_importapplication_defraimp_inspectionrequiredreason | null }, { defraimp_inspectionrequiredreason_formatted?: string }>;
    defraimp_inspectionrequiredreasonoriginalvalue: WebAttribute<defraimp_importapplication_Select, { defraimp_inspectionrequiredreasonoriginalvalue: number | null }, {  }>;
    defraimp_ipaffsspeciesid: WebAttribute<defraimp_importapplication_Select, { defraimp_ipaffsspeciesid: string | null }, {  }>;
    defraimp_irmspersonresponsible_guid: WebAttribute<defraimp_importapplication_Select, { defraimp_irmspersonresponsible_guid: string | null }, { defraimp_irmspersonresponsible_formatted?: string }>;
    defraimp_isnoncompliantcalculated: WebAttribute<defraimp_importapplication_Select, { defraimp_isnoncompliantcalculated: boolean | null }, {  }>;
    defraimp_itahcreference: WebAttribute<defraimp_importapplication_Select, { defraimp_itahcreference: string | null }, {  }>;
    defraimp_iv65responseduedate: WebAttribute<defraimp_importapplication_Select, { defraimp_iv65responseduedate: Date | null }, { defraimp_iv65responseduedate_formatted?: string }>;
    defraimp_iv65responsereceiveddate: WebAttribute<defraimp_importapplication_Select, { defraimp_iv65responsereceiveddate: Date | null }, { defraimp_iv65responsereceiveddate_formatted?: string }>;
    defraimp_iv65sent: WebAttribute<defraimp_importapplication_Select, { defraimp_iv65sent: boolean | null }, {  }>;
    defraimp_iv65sentdate: WebAttribute<defraimp_importapplication_Select, { defraimp_iv65sentdate: Date | null }, { defraimp_iv65sentdate_formatted?: string }>;
    defraimp_iv66receivedinrequiredtimescale: WebAttribute<defraimp_importapplication_Select, { defraimp_iv66receivedinrequiredtimescale: boolean | null }, {  }>;
    defraimp_localreferencenumber: WebAttribute<defraimp_importapplication_Select, { defraimp_localreferencenumber: string | null }, {  }>;
    defraimp_manualpostimportcheckdecision: WebAttribute<defraimp_importapplication_Select, { defraimp_manualpostimportcheckdecision: defraimp_importapplication_defraimp_manualpostimportcheckdecision | null }, { defraimp_manualpostimportcheckdecision_formatted?: string }>;
    defraimp_matchingvalidated: WebAttribute<defraimp_importapplication_Select, { defraimp_matchingvalidated: boolean | null }, {  }>;
    defraimp_meansoftransport: WebAttribute<defraimp_importapplication_Select, { defraimp_meansoftransport: defraimp_meansoftransport | null }, { defraimp_meansoftransport_formatted?: string }>;
    defraimp_movedtocompletiondate: WebAttribute<defraimp_importapplication_Select, { defraimp_movedtocompletiondate: Date | null }, { defraimp_movedtocompletiondate_formatted?: string }>;
    defraimp_movetocompletion: WebAttribute<defraimp_importapplication_Select, { defraimp_movetocompletion: boolean | null }, {  }>;
    defraimp_name: WebAttribute<defraimp_importapplication_Select, { defraimp_name: string | null }, {  }>;
    defraimp_noncomplianceothercomments: WebAttribute<defraimp_importapplication_Select, { defraimp_noncomplianceothercomments: string | null }, {  }>;
    defraimp_noncompliancestatus: WebAttribute<defraimp_importapplication_Select, { defraimp_noncompliancestatus: defraimp_noncompliancestatus | null }, { defraimp_noncompliancestatus_formatted?: string }>;
    defraimp_notifiedtobipwithin15days: WebAttribute<defraimp_importapplication_Select, { defraimp_notifiedtobipwithin15days: boolean | null }, {  }>;
    defraimp_permanentdestinationaddresscity: WebAttribute<defraimp_importapplication_Select, { defraimp_permanentdestinationaddresscity: string | null }, {  }>;
    defraimp_permanentdestinationaddresscounid_guid: WebAttribute<defraimp_importapplication_Select, { defraimp_permanentdestinationaddresscounid_guid: string | null }, { defraimp_permanentdestinationaddresscounid_formatted?: string }>;
    defraimp_permanentdestinationaddressline1: WebAttribute<defraimp_importapplication_Select, { defraimp_permanentdestinationaddressline1: string | null }, {  }>;
    defraimp_permanentdestinationaddressline2: WebAttribute<defraimp_importapplication_Select, { defraimp_permanentdestinationaddressline2: string | null }, {  }>;
    defraimp_permanentdestinationaddressline3: WebAttribute<defraimp_importapplication_Select, { defraimp_permanentdestinationaddressline3: string | null }, {  }>;
    defraimp_permanentdestinationaddresspostcode: WebAttribute<defraimp_importapplication_Select, { defraimp_permanentdestinationaddresspostcode: string | null }, {  }>;
    defraimp_permanentdestinationcontactname: WebAttribute<defraimp_importapplication_Select, { defraimp_permanentdestinationcontactname: string | null }, {  }>;
    defraimp_permanentdestinationemail: WebAttribute<defraimp_importapplication_Select, { defraimp_permanentdestinationemail: string | null }, {  }>;
    defraimp_permanentdestinationorganisation: WebAttribute<defraimp_importapplication_Select, { defraimp_permanentdestinationorganisation: string | null }, {  }>;
    defraimp_permanentdestinationtelephone: WebAttribute<defraimp_importapplication_Select, { defraimp_permanentdestinationtelephone: string | null }, {  }>;
    defraimp_pimsstatus: WebAttribute<defraimp_importapplication_Select, { defraimp_pimsstatus: defraimp_pimsstatus | null }, { defraimp_pimsstatus_formatted?: string }>;
    defraimp_placeofdestinationaddresscity: WebAttribute<defraimp_importapplication_Select, { defraimp_placeofdestinationaddresscity: string | null }, {  }>;
    defraimp_placeofdestinationaddressline1: WebAttribute<defraimp_importapplication_Select, { defraimp_placeofdestinationaddressline1: string | null }, {  }>;
    defraimp_placeofdestinationaddressline2: WebAttribute<defraimp_importapplication_Select, { defraimp_placeofdestinationaddressline2: string | null }, {  }>;
    defraimp_placeofdestinationaddressline3: WebAttribute<defraimp_importapplication_Select, { defraimp_placeofdestinationaddressline3: string | null }, {  }>;
    defraimp_placeofdestinationaddresspostcode: WebAttribute<defraimp_importapplication_Select, { defraimp_placeofdestinationaddresspostcode: string | null }, {  }>;
    defraimp_placeofdestinationcontactname: WebAttribute<defraimp_importapplication_Select, { defraimp_placeofdestinationcontactname: string | null }, {  }>;
    defraimp_placeofdestinationemail: WebAttribute<defraimp_importapplication_Select, { defraimp_placeofdestinationemail: string | null }, {  }>;
    defraimp_placeofdestinationorganisation: WebAttribute<defraimp_importapplication_Select, { defraimp_placeofdestinationorganisation: string | null }, {  }>;
    defraimp_placeofdestinationtelephone: WebAttribute<defraimp_importapplication_Select, { defraimp_placeofdestinationtelephone: string | null }, {  }>;
    defraimp_placeoforiginaddresscity: WebAttribute<defraimp_importapplication_Select, { defraimp_placeoforiginaddresscity: string | null }, {  }>;
    defraimp_placeoforiginaddressline1: WebAttribute<defraimp_importapplication_Select, { defraimp_placeoforiginaddressline1: string | null }, {  }>;
    defraimp_placeoforiginaddressline2: WebAttribute<defraimp_importapplication_Select, { defraimp_placeoforiginaddressline2: string | null }, {  }>;
    defraimp_placeoforiginaddressline3: WebAttribute<defraimp_importapplication_Select, { defraimp_placeoforiginaddressline3: string | null }, {  }>;
    defraimp_placeoforiginaddresspostcode: WebAttribute<defraimp_importapplication_Select, { defraimp_placeoforiginaddresspostcode: string | null }, {  }>;
    defraimp_placeoforigincontactname: WebAttribute<defraimp_importapplication_Select, { defraimp_placeoforigincontactname: string | null }, {  }>;
    defraimp_placeoforigincountryid_guid: WebAttribute<defraimp_importapplication_Select, { defraimp_placeoforigincountryid_guid: string | null }, { defraimp_placeoforigincountryid_formatted?: string }>;
    defraimp_placeoforiginid_guid: WebAttribute<defraimp_importapplication_Select, { defraimp_placeoforiginid_guid: string | null }, { defraimp_placeoforiginid_formatted?: string }>;
    defraimp_placeoforiginorganisation: WebAttribute<defraimp_importapplication_Select, { defraimp_placeoforiginorganisation: string | null }, {  }>;
    defraimp_placeoforigintrustlevel: WebAttribute<defraimp_importapplication_Select, { defraimp_placeoforigintrustlevel: defraimp_trustlevel | null }, { defraimp_placeoforigintrustlevel_formatted?: string }>;
    defraimp_pointofentry: WebAttribute<defraimp_importapplication_Select, { defraimp_pointofentry: string | null }, {  }>;
    defraimp_previousimportrisklevelid_guid: WebAttribute<defraimp_importapplication_Select, { defraimp_previousimportrisklevelid_guid: string | null }, { defraimp_previousimportrisklevelid_formatted?: string }>;
    defraimp_previousplaceoforiginid_guid: WebAttribute<defraimp_importapplication_Select, { defraimp_previousplaceoforiginid_guid: string | null }, { defraimp_previousplaceoforiginid_formatted?: string }>;
    defraimp_primarycvedid_guid: WebAttribute<defraimp_importapplication_Select, { defraimp_primarycvedid_guid: string | null }, { defraimp_primarycvedid_formatted?: string }>;
    defraimp_primaryimporternotificationid_guid: WebAttribute<defraimp_importapplication_Select, { defraimp_primaryimporternotificationid_guid: string | null }, { defraimp_primaryimporternotificationid_formatted?: string }>;
    defraimp_primaryitahcid_guid: WebAttribute<defraimp_importapplication_Select, { defraimp_primaryitahcid_guid: string | null }, { defraimp_primaryitahcid_formatted?: string }>;
    defraimp_purpose: WebAttribute<defraimp_importapplication_Select, { defraimp_purpose: defraimp_importapplication_defraimp_purpose | null }, { defraimp_purpose_formatted?: string }>;
    defraimp_quantity: WebAttribute<defraimp_importapplication_Select, { defraimp_quantity: number | null }, {  }>;
    defraimp_regionareaallocatedtoid_guid: WebAttribute<defraimp_importapplication_Select, { defraimp_regionareaallocatedtoid_guid: string | null }, { defraimp_regionareaallocatedtoid_formatted?: string }>;
    defraimp_registrantorganisationid_guid: WebAttribute<defraimp_importapplication_Select, { defraimp_registrantorganisationid_guid: string | null }, { defraimp_registrantorganisationid_formatted?: string }>;
    defraimp_replyreceived: WebAttribute<defraimp_importapplication_Select, { defraimp_replyreceived: defraimp_importapplication_defraimp_replyreceived | null }, { defraimp_replyreceived_formatted?: string }>;
    defraimp_requestedpod: WebAttribute<defraimp_importapplication_Select, { defraimp_requestedpod: defraimp_importapplication_defraimp_requestedpod | null }, { defraimp_requestedpod_formatted?: string }>;
    defraimp_resettrustleveltobronze: WebAttribute<defraimp_importapplication_Select, { defraimp_resettrustleveltobronze: boolean | null }, {  }>;
    defraimp_risklevelverified: WebAttribute<defraimp_importapplication_Select, { defraimp_risklevelverified: boolean | null }, {  }>;
    defraimp_sealnumber: WebAttribute<defraimp_importapplication_Select, { defraimp_sealnumber: string | null }, {  }>;
    defraimp_tracesexporthealthcertificate: WebAttribute<defraimp_importapplication_Select, { defraimp_tracesexporthealthcertificate: string | null }, {  }>;
    defraimp_tracesspeciesid: WebAttribute<defraimp_importapplication_Select, { defraimp_tracesspeciesid: string | null }, {  }>;
    defraimp_transporteraddress: WebAttribute<defraimp_importapplication_Select, { defraimp_transporteraddress: string | null }, {  }>;
    defraimp_transporteraddresscity: WebAttribute<defraimp_importapplication_Select, { defraimp_transporteraddresscity: string | null }, {  }>;
    defraimp_transporteraddresscountryid_guid: WebAttribute<defraimp_importapplication_Select, { defraimp_transporteraddresscountryid_guid: string | null }, { defraimp_transporteraddresscountryid_formatted?: string }>;
    defraimp_transporteraddressline1: WebAttribute<defraimp_importapplication_Select, { defraimp_transporteraddressline1: string | null }, {  }>;
    defraimp_transporteraddressline2: WebAttribute<defraimp_importapplication_Select, { defraimp_transporteraddressline2: string | null }, {  }>;
    defraimp_transporteraddressline3: WebAttribute<defraimp_importapplication_Select, { defraimp_transporteraddressline3: string | null }, {  }>;
    defraimp_transporteraddresspostcode: WebAttribute<defraimp_importapplication_Select, { defraimp_transporteraddresspostcode: string | null }, {  }>;
    defraimp_transporteremail: WebAttribute<defraimp_importapplication_Select, { defraimp_transporteremail: string | null }, {  }>;
    defraimp_transportername: WebAttribute<defraimp_importapplication_Select, { defraimp_transportername: string | null }, {  }>;
    defraimp_transportertelephone: WebAttribute<defraimp_importapplication_Select, { defraimp_transportertelephone: string | null }, {  }>;
    defraimp_transportertype: WebAttribute<defraimp_importapplication_Select, { defraimp_transportertype: string | null }, {  }>;
    defraimp_type: WebAttribute<defraimp_importapplication_Select, { defraimp_type: string | null }, {  }>;
    defraimp_typesofnoncompliance: WebAttribute<defraimp_importapplication_Select, { defraimp_typesofnoncompliance: defraimp_noncompliancetype | null }, { defraimp_typesofnoncompliance_formatted?: string }>;
    defraimp_unit: WebAttribute<defraimp_importapplication_Select, { defraimp_unit: string | null }, {  }>;
    defraimp_warbleflytreatmentdeclarationreceiveddate: WebAttribute<defraimp_importapplication_Select, { defraimp_warbleflytreatmentdeclarationreceiveddate: Date | null }, { defraimp_warbleflytreatmentdeclarationreceiveddate_formatted?: string }>;
    defraimp_warbleflytreatmentdeclarationrequired: WebAttribute<defraimp_importapplication_Select, { defraimp_warbleflytreatmentdeclarationrequired: boolean | null }, {  }>;
    defraimp_weight: WebAttribute<defraimp_importapplication_Select, { defraimp_weight: string | null }, {  }>;
    defraimp_workschedulenumber: WebAttribute<defraimp_importapplication_Select, { defraimp_workschedulenumber: string | null }, {  }>;
    importsequencenumber: WebAttribute<defraimp_importapplication_Select, { importsequencenumber: number | null }, {  }>;
    modifiedby_guid: WebAttribute<defraimp_importapplication_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
    modifiedon: WebAttribute<defraimp_importapplication_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
    modifiedonbehalfby_guid: WebAttribute<defraimp_importapplication_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
    overriddencreatedon: WebAttribute<defraimp_importapplication_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
    ownerid_guid: WebAttribute<defraimp_importapplication_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
    owningbusinessunit_guid: WebAttribute<defraimp_importapplication_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
    owningteam_guid: WebAttribute<defraimp_importapplication_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
    owninguser_guid: WebAttribute<defraimp_importapplication_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
    processid: WebAttribute<defraimp_importapplication_Select, { processid: string | null }, {  }>;
    stageid: WebAttribute<defraimp_importapplication_Select, { stageid: string | null }, {  }>;
    statecode: WebAttribute<defraimp_importapplication_Select, { statecode: defraimp_importapplication_statecode | null }, { statecode_formatted?: string }>;
    statuscode: WebAttribute<defraimp_importapplication_Select, { statuscode: defraimp_importapplication_statuscode | null }, { statuscode_formatted?: string }>;
    timezoneruleversionnumber: WebAttribute<defraimp_importapplication_Select, { timezoneruleversionnumber: number | null }, {  }>;
    traversedpath: WebAttribute<defraimp_importapplication_Select, { traversedpath: string | null }, {  }>;
    utcconversiontimezonecode: WebAttribute<defraimp_importapplication_Select, { utcconversiontimezonecode: number | null }, {  }>;
    versionnumber: WebAttribute<defraimp_importapplication_Select, { versionnumber: number | null }, {  }>;
  }
  interface defraimp_importapplication_Filter {
    createdby_guid: XQW.Guid;
    createdon: Date;
    createdonbehalfby_guid: XQW.Guid;
    defraimp_animalcertifiedas: defraimp_animalcertifiedas;
    defraimp_article15reimport: boolean;
    defraimp_article8monitored: boolean;
    defraimp_certificatecompliantfirsttime: boolean;
    defraimp_certificatenoncompliancereason: defraimp_importapplication_defraimp_certificatenoncompliancereason;
    defraimp_certificatenoncompliancereasonother: string;
    defraimp_certificatenumber: string;
    defraimp_certificateverified: boolean;
    defraimp_charityaddresscity: string;
    defraimp_charityaddresscountry_guid: XQW.Guid;
    defraimp_charityaddressline1: string;
    defraimp_charityaddressline2: string;
    defraimp_charityaddressline3: string;
    defraimp_charityaddresspostcode: string;
    defraimp_charityname: string;
    defraimp_chedacertificatenumber: string;
    defraimp_commoditycode: string;
    defraimp_commodityidentifiers: string;
    defraimp_commoditynotes: string;
    defraimp_commoditytypeid_guid: XQW.Guid;
    defraimp_completionsummary: string;
    defraimp_consignmentconforming: boolean;
    defraimp_contactedduetononcompliance: boolean;
    defraimp_containernumber: string;
    defraimp_countryoforiginid_guid: XQW.Guid;
    defraimp_countryoforiginisocode: string;
    defraimp_datecompleted: Date;
    defraimp_dateconfirmedontraces: Date;
    defraimp_dateconsignmentreceived: Date;
    defraimp_dateemailsent: Date;
    defraimp_dateimportercontacted: Date;
    defraimp_dateiv66received: Date;
    defraimp_dateofconfirmationfromimporter: Date;
    defraimp_dateofconfirmationtobip: Date;
    defraimp_dateofemailtoimporter: Date;
    defraimp_dateofimport: Date;
    defraimp_datepodrequested: Date;
    defraimp_datetelephonecallmade: Date;
    defraimp_destinationaddresscountryid_guid: XQW.Guid;
    defraimp_devolvedofficeid_guid: XQW.Guid;
    defraimp_docomcategory: defraimp_importapplication_defraimp_docomcategory;
    defraimp_docomreference: string;
    defraimp_documentationnumber: string;
    defraimp_documentnumber: string;
    defraimp_gbimporthealthcertificate: string;
    defraimp_generalcomments: string;
    defraimp_healthcertificatenumber: string;
    defraimp_importapplicationid: XQW.Guid;
    defraimp_importapplicationtype: defraimp_importapplication_defraimp_importapplicationtype;
    defraimp_importeraddress1: string;
    defraimp_importeraddress2: string;
    defraimp_importeraddress3: string;
    defraimp_importeraddresscity: string;
    defraimp_importeraddresscountryid_guid: XQW.Guid;
    defraimp_importeraddresspostcode: string;
    defraimp_importercontactname: string;
    defraimp_importercphnumber: string;
    defraimp_importeremail: string;
    defraimp_importerorganisation: string;
    defraimp_importertelephone: string;
    defraimp_importingfromcharity: boolean;
    defraimp_importrecordcounted: boolean;
    defraimp_importrisklevelid_guid: XQW.Guid;
    defraimp_importrisklevelstatus: defraimp_importapplication_defraimp_importrisklevelstatus;
    defraimp_imptypeid_guid: XQW.Guid;
    defraimp_inspectioncompleted: boolean;
    defraimp_inspectiondeclinedreason: string;
    defraimp_inspectionoutcome: defraimp_importapplication_defraimp_inspectionoutcome;
    defraimp_inspectionrequested: boolean;
    defraimp_inspectionrequired: defraimp_importapplication_defraimp_inspectionrequired;
    defraimp_inspectionrequiredoriginalvalue: number;
    defraimp_inspectionrequiredreason: defraimp_importapplication_defraimp_inspectionrequiredreason;
    defraimp_inspectionrequiredreasonoriginalvalue: number;
    defraimp_ipaffsspeciesid: string;
    defraimp_irmspersonresponsible_guid: XQW.Guid;
    defraimp_isnoncompliantcalculated: boolean;
    defraimp_itahcreference: string;
    defraimp_iv65responseduedate: Date;
    defraimp_iv65responsereceiveddate: Date;
    defraimp_iv65sent: boolean;
    defraimp_iv65sentdate: Date;
    defraimp_iv66receivedinrequiredtimescale: boolean;
    defraimp_localreferencenumber: string;
    defraimp_manualpostimportcheckdecision: defraimp_importapplication_defraimp_manualpostimportcheckdecision;
    defraimp_matchingvalidated: boolean;
    defraimp_meansoftransport: defraimp_meansoftransport;
    defraimp_movedtocompletiondate: Date;
    defraimp_movetocompletion: boolean;
    defraimp_name: string;
    defraimp_noncomplianceothercomments: string;
    defraimp_noncompliancestatus: defraimp_noncompliancestatus;
    defraimp_notifiedtobipwithin15days: boolean;
    defraimp_permanentdestinationaddresscity: string;
    defraimp_permanentdestinationaddresscounid_guid: XQW.Guid;
    defraimp_permanentdestinationaddressline1: string;
    defraimp_permanentdestinationaddressline2: string;
    defraimp_permanentdestinationaddressline3: string;
    defraimp_permanentdestinationaddresspostcode: string;
    defraimp_permanentdestinationcontactname: string;
    defraimp_permanentdestinationemail: string;
    defraimp_permanentdestinationorganisation: string;
    defraimp_permanentdestinationtelephone: string;
    defraimp_pimsstatus: defraimp_pimsstatus;
    defraimp_placeofdestinationaddresscity: string;
    defraimp_placeofdestinationaddressline1: string;
    defraimp_placeofdestinationaddressline2: string;
    defraimp_placeofdestinationaddressline3: string;
    defraimp_placeofdestinationaddresspostcode: string;
    defraimp_placeofdestinationcontactname: string;
    defraimp_placeofdestinationemail: string;
    defraimp_placeofdestinationorganisation: string;
    defraimp_placeofdestinationtelephone: string;
    defraimp_placeoforiginaddresscity: string;
    defraimp_placeoforiginaddressline1: string;
    defraimp_placeoforiginaddressline2: string;
    defraimp_placeoforiginaddressline3: string;
    defraimp_placeoforiginaddresspostcode: string;
    defraimp_placeoforigincontactname: string;
    defraimp_placeoforigincountryid_guid: XQW.Guid;
    defraimp_placeoforiginid_guid: XQW.Guid;
    defraimp_placeoforiginorganisation: string;
    defraimp_placeoforigintrustlevel: defraimp_trustlevel;
    defraimp_pointofentry: string;
    defraimp_previousimportrisklevelid_guid: XQW.Guid;
    defraimp_previousplaceoforiginid_guid: XQW.Guid;
    defraimp_primarycvedid_guid: XQW.Guid;
    defraimp_primaryimporternotificationid_guid: XQW.Guid;
    defraimp_primaryitahcid_guid: XQW.Guid;
    defraimp_purpose: defraimp_importapplication_defraimp_purpose;
    defraimp_quantity: number;
    defraimp_regionareaallocatedtoid_guid: XQW.Guid;
    defraimp_registrantorganisationid_guid: XQW.Guid;
    defraimp_replyreceived: defraimp_importapplication_defraimp_replyreceived;
    defraimp_requestedpod: defraimp_importapplication_defraimp_requestedpod;
    defraimp_resettrustleveltobronze: boolean;
    defraimp_risklevelverified: boolean;
    defraimp_sealnumber: string;
    defraimp_tracesexporthealthcertificate: string;
    defraimp_tracesspeciesid: string;
    defraimp_transporteraddress: string;
    defraimp_transporteraddresscity: string;
    defraimp_transporteraddresscountryid_guid: XQW.Guid;
    defraimp_transporteraddressline1: string;
    defraimp_transporteraddressline2: string;
    defraimp_transporteraddressline3: string;
    defraimp_transporteraddresspostcode: string;
    defraimp_transporteremail: string;
    defraimp_transportername: string;
    defraimp_transportertelephone: string;
    defraimp_transportertype: string;
    defraimp_type: string;
    defraimp_typesofnoncompliance: defraimp_noncompliancetype;
    defraimp_unit: string;
    defraimp_warbleflytreatmentdeclarationreceiveddate: Date;
    defraimp_warbleflytreatmentdeclarationrequired: boolean;
    defraimp_weight: string;
    defraimp_workschedulenumber: string;
    importsequencenumber: number;
    modifiedby_guid: XQW.Guid;
    modifiedon: Date;
    modifiedonbehalfby_guid: XQW.Guid;
    overriddencreatedon: Date;
    ownerid_guid: XQW.Guid;
    owningbusinessunit_guid: XQW.Guid;
    owningteam_guid: XQW.Guid;
    owninguser_guid: XQW.Guid;
    processid: XQW.Guid;
    stageid: XQW.Guid;
    statecode: defraimp_importapplication_statecode;
    statuscode: defraimp_importapplication_statuscode;
    timezoneruleversionnumber: number;
    traversedpath: string;
    utcconversiontimezonecode: number;
    versionnumber: number;
  }
  interface defraimp_importapplication_Expand {
    defraimp_PlaceofOriginid: WebExpand<defraimp_importapplication_Expand, defraimp_placeoforigin_Select, defraimp_placeoforigin_Filter, { defraimp_PlaceofOriginid: defraimp_placeoforigin_Result }>;
    defraimp_PotentiallyRelatedImportRecords: WebExpand<defraimp_importapplication_Expand, defraimp_matchrecord_Select, defraimp_matchrecord_Filter, { defraimp_PotentiallyRelatedImportRecords: defraimp_matchrecord_Result[] }>;
    defraimp_PrimaryITAHCId: WebExpand<defraimp_importapplication_Expand, defraimp_itahc_Select, defraimp_itahc_Filter, { defraimp_PrimaryITAHCId: defraimp_itahc_Result }>;
    defraimp_PrimaryImporterNotificationId: WebExpand<defraimp_importapplication_Expand, defraimp_ImporterNotification_Select, defraimp_ImporterNotification_Filter, { defraimp_PrimaryImporterNotificationId: defraimp_ImporterNotification_Result }>;
    defraimp_defraimp_importapplication_defraimp_importinspection_RelatedImportApplication: WebExpand<defraimp_importapplication_Expand, defraimp_importinspection_Select, defraimp_importinspection_Filter, { defraimp_defraimp_importapplication_defraimp_importinspection_RelatedImportApplication: defraimp_importinspection_Result[] }>;
    defraimp_defraimp_importapplication_defraimp_itahc: WebExpand<defraimp_importapplication_Expand, defraimp_itahc_Select, defraimp_itahc_Filter, { defraimp_defraimp_importapplication_defraimp_itahc: defraimp_itahc_Result[] }>;
    defraimp_defraimp_matchrecord_defraimp_Im: WebExpand<defraimp_importapplication_Expand, defraimp_matchrecord_Select, defraimp_matchrecord_Filter, { defraimp_defraimp_matchrecord_defraimp_Im: defraimp_matchrecord_Result[] }>;
    defraimp_importapplication_defraimp_importqueries: WebExpand<defraimp_importapplication_Expand, defraimp_importquery_Select, defraimp_importquery_Filter, { defraimp_importapplication_defraimp_importqueries: defraimp_importquery_Result[] }>;
    defraimp_previousplaceoforiginid: WebExpand<defraimp_importapplication_Expand, defraimp_placeoforigin_Select, defraimp_placeoforigin_Filter, { defraimp_previousplaceoforiginid: defraimp_placeoforigin_Result }>;
  }
  interface defraimp_importapplication_FormattedResult {
    createdby_formatted?: string;
    createdon_formatted?: string;
    createdonbehalfby_formatted?: string;
    defraimp_animalcertifiedas_formatted?: string;
    defraimp_certificatenoncompliancereason_formatted?: string;
    defraimp_charityaddresscountry_formatted?: string;
    defraimp_commoditytypeid_formatted?: string;
    defraimp_countryoforiginid_formatted?: string;
    defraimp_datecompleted_formatted?: string;
    defraimp_dateconfirmedontraces_formatted?: string;
    defraimp_dateconsignmentreceived_formatted?: string;
    defraimp_dateemailsent_formatted?: string;
    defraimp_dateimportercontacted_formatted?: string;
    defraimp_dateiv66received_formatted?: string;
    defraimp_dateofconfirmationfromimporter_formatted?: string;
    defraimp_dateofconfirmationtobip_formatted?: string;
    defraimp_dateofemailtoimporter_formatted?: string;
    defraimp_dateofimport_formatted?: string;
    defraimp_datepodrequested_formatted?: string;
    defraimp_datetelephonecallmade_formatted?: string;
    defraimp_destinationaddresscountryid_formatted?: string;
    defraimp_devolvedofficeid_formatted?: string;
    defraimp_docomcategory_formatted?: string;
    defraimp_importapplicationtype_formatted?: string;
    defraimp_importeraddresscountryid_formatted?: string;
    defraimp_importrisklevelid_formatted?: string;
    defraimp_importrisklevelstatus_formatted?: string;
    defraimp_imptypeid_formatted?: string;
    defraimp_inspectionoutcome_formatted?: string;
    defraimp_inspectionrequired_formatted?: string;
    defraimp_inspectionrequiredreason_formatted?: string;
    defraimp_irmspersonresponsible_formatted?: string;
    defraimp_iv65responseduedate_formatted?: string;
    defraimp_iv65responsereceiveddate_formatted?: string;
    defraimp_iv65sentdate_formatted?: string;
    defraimp_manualpostimportcheckdecision_formatted?: string;
    defraimp_meansoftransport_formatted?: string;
    defraimp_movedtocompletiondate_formatted?: string;
    defraimp_noncompliancestatus_formatted?: string;
    defraimp_permanentdestinationaddresscounid_formatted?: string;
    defraimp_pimsstatus_formatted?: string;
    defraimp_placeoforigincountryid_formatted?: string;
    defraimp_placeoforiginid_formatted?: string;
    defraimp_placeoforigintrustlevel_formatted?: string;
    defraimp_previousimportrisklevelid_formatted?: string;
    defraimp_previousplaceoforiginid_formatted?: string;
    defraimp_primarycvedid_formatted?: string;
    defraimp_primaryimporternotificationid_formatted?: string;
    defraimp_primaryitahcid_formatted?: string;
    defraimp_purpose_formatted?: string;
    defraimp_regionareaallocatedtoid_formatted?: string;
    defraimp_registrantorganisationid_formatted?: string;
    defraimp_replyreceived_formatted?: string;
    defraimp_requestedpod_formatted?: string;
    defraimp_transporteraddresscountryid_formatted?: string;
    defraimp_typesofnoncompliance_formatted?: string;
    defraimp_warbleflytreatmentdeclarationreceiveddate_formatted?: string;
    modifiedby_formatted?: string;
    modifiedon_formatted?: string;
    modifiedonbehalfby_formatted?: string;
    overriddencreatedon_formatted?: string;
    ownerid_formatted?: string;
    owningbusinessunit_formatted?: string;
    owningteam_formatted?: string;
    owninguser_formatted?: string;
    statecode_formatted?: string;
    statuscode_formatted?: string;
  }
  interface defraimp_importapplication_Result extends defraimp_importapplication_Base, defraimp_importapplication_Relationships {
    "@odata.etag": string;
    createdby_guid: string | null;
    createdonbehalfby_guid: string | null;
    defraimp_charityaddresscountry_guid: string | null;
    defraimp_commoditytypeid_guid: string | null;
    defraimp_countryoforiginid_guid: string | null;
    defraimp_destinationaddresscountryid_guid: string | null;
    defraimp_devolvedofficeid_guid: string | null;
    defraimp_importeraddresscountryid_guid: string | null;
    defraimp_importrisklevelid_guid: string | null;
    defraimp_imptypeid_guid: string | null;
    defraimp_irmspersonresponsible_guid: string | null;
    defraimp_permanentdestinationaddresscounid_guid: string | null;
    defraimp_placeoforigincountryid_guid: string | null;
    defraimp_placeoforiginid_guid: string | null;
    defraimp_previousimportrisklevelid_guid: string | null;
    defraimp_previousplaceoforiginid_guid: string | null;
    defraimp_primarycvedid_guid: string | null;
    defraimp_primaryimporternotificationid_guid: string | null;
    defraimp_primaryitahcid_guid: string | null;
    defraimp_regionareaallocatedtoid_guid: string | null;
    defraimp_registrantorganisationid_guid: string | null;
    defraimp_transporteraddresscountryid_guid: string | null;
    modifiedby_guid: string | null;
    modifiedonbehalfby_guid: string | null;
    ownerid_guid: string | null;
    owningbusinessunit_guid: string | null;
    owningteam_guid: string | null;
    owninguser_guid: string | null;
  }
  interface defraimp_importapplication_RelatedOne {
    defraimp_PlaceofOriginid: WebMappingRetrieve<WebApi.defraimp_placeoforigin_Select,WebApi.defraimp_placeoforigin_Expand,WebApi.defraimp_placeoforigin_Filter,WebApi.defraimp_placeoforigin_Fixed,WebApi.defraimp_placeoforigin_Result,WebApi.defraimp_placeoforigin_FormattedResult>;
    defraimp_PrimaryITAHCId: WebMappingRetrieve<WebApi.defraimp_itahc_Select,WebApi.defraimp_itahc_Expand,WebApi.defraimp_itahc_Filter,WebApi.defraimp_itahc_Fixed,WebApi.defraimp_itahc_Result,WebApi.defraimp_itahc_FormattedResult>;
    defraimp_PrimaryImporterNotificationId: WebMappingRetrieve<WebApi.defraimp_ImporterNotification_Select,WebApi.defraimp_ImporterNotification_Expand,WebApi.defraimp_ImporterNotification_Filter,WebApi.defraimp_ImporterNotification_Fixed,WebApi.defraimp_ImporterNotification_Result,WebApi.defraimp_ImporterNotification_FormattedResult>;
    defraimp_previousplaceoforiginid: WebMappingRetrieve<WebApi.defraimp_placeoforigin_Select,WebApi.defraimp_placeoforigin_Expand,WebApi.defraimp_placeoforigin_Filter,WebApi.defraimp_placeoforigin_Fixed,WebApi.defraimp_placeoforigin_Result,WebApi.defraimp_placeoforigin_FormattedResult>;
  }
  interface defraimp_importapplication_RelatedMany {
    defraimp_PotentiallyRelatedImportRecords: WebMappingRetrieve<WebApi.defraimp_matchrecord_Select,WebApi.defraimp_matchrecord_Expand,WebApi.defraimp_matchrecord_Filter,WebApi.defraimp_matchrecord_Fixed,WebApi.defraimp_matchrecord_Result,WebApi.defraimp_matchrecord_FormattedResult>;
    defraimp_defraimp_importapplication_defraimp_importinspection_RelatedImportApplication: WebMappingRetrieve<WebApi.defraimp_importinspection_Select,WebApi.defraimp_importinspection_Expand,WebApi.defraimp_importinspection_Filter,WebApi.defraimp_importinspection_Fixed,WebApi.defraimp_importinspection_Result,WebApi.defraimp_importinspection_FormattedResult>;
    defraimp_defraimp_importapplication_defraimp_itahc: WebMappingRetrieve<WebApi.defraimp_itahc_Select,WebApi.defraimp_itahc_Expand,WebApi.defraimp_itahc_Filter,WebApi.defraimp_itahc_Fixed,WebApi.defraimp_itahc_Result,WebApi.defraimp_itahc_FormattedResult>;
    defraimp_defraimp_matchrecord_defraimp_Im: WebMappingRetrieve<WebApi.defraimp_matchrecord_Select,WebApi.defraimp_matchrecord_Expand,WebApi.defraimp_matchrecord_Filter,WebApi.defraimp_matchrecord_Fixed,WebApi.defraimp_matchrecord_Result,WebApi.defraimp_matchrecord_FormattedResult>;
    defraimp_importapplication_defraimp_importqueries: WebMappingRetrieve<WebApi.defraimp_importquery_Select,WebApi.defraimp_importquery_Expand,WebApi.defraimp_importquery_Filter,WebApi.defraimp_importquery_Fixed,WebApi.defraimp_importquery_Result,WebApi.defraimp_importquery_FormattedResult>;
  }
}
interface WebEntitiesRetrieve {
  defraimp_importapplications: WebMappingRetrieve<WebApi.defraimp_importapplication_Select,WebApi.defraimp_importapplication_Expand,WebApi.defraimp_importapplication_Filter,WebApi.defraimp_importapplication_Fixed,WebApi.defraimp_importapplication_Result,WebApi.defraimp_importapplication_FormattedResult>;
}
interface WebEntitiesRelated {
  defraimp_importapplications: WebMappingRelated<WebApi.defraimp_importapplication_RelatedOne,WebApi.defraimp_importapplication_RelatedMany>;
}
interface WebEntitiesCUDA {
  defraimp_importapplications: WebMappingCUDA<WebApi.defraimp_importapplication_Create,WebApi.defraimp_importapplication_Update,WebApi.defraimp_importapplication_Select>;
}
