declare namespace WebApi {
  interface ProcessSession_Base extends WebEntity {
    activityname?: string | null;
    canceledon?: Date | null;
    comments?: string | null;
    completedon?: Date | null;
    createdon?: Date | null;
    errorcode?: number | null;
    executedon?: Date | null;
    inputarguments?: string | null;
    modifiedon?: Date | null;
    name?: string | null;
    processsessionid?: string | null;
    processstagename?: string | null;
    processstate?: string | null;
    protectionkey?: string | null;
    startedon?: Date | null;
    statecode?: processsession_statecode | null;
    statuscode?: processsession_statuscode | null;
    stepname?: string | null;
  }
  interface ProcessSession_Relationships {
    ProcessSession_SyncErrors?: SyncError_Result[] | null;
    lk_processsession_nextlinkedsessionid?: ProcessSession_Result[] | null;
    lk_processsession_originatingsessionid?: ProcessSession_Result[] | null;
    lk_processsession_previouslinkedsessionid?: ProcessSession_Result[] | null;
    regardingobjectid_defra_country?: defra_country_Result | null;
    regardingobjectid_defraexp_commoditytype?: defraexp_commoditytype_Result | null;
    regardingobjectid_defraimp_apharegion?: defraimp_apharegion_Result | null;
    regardingobjectid_defraimp_autonumber?: defraimp_autonumber_Result | null;
    regardingobjectid_defraimp_cved?: defraimp_cved_Result | null;
    regardingobjectid_defraimp_docom?: defraimp_docom_Result | null;
    regardingobjectid_defraimp_goldbronzecommodity?: defraimp_goldbronzecommodity_Result | null;
    regardingobjectid_defraimp_importapplication?: defraimp_importapplication_Result | null;
    regardingobjectid_defraimp_importapplicationbusinessprocessflow?: defraimp_importapplicationbusinessprocessflow_Result | null;
    regardingobjectid_defraimp_importcountrycommodityrisklevel?: defraimp_importcountrycommodityrisklevel_Result | null;
    regardingobjectid_defraimp_importinspection?: defraimp_importinspection_Result | null;
    regardingobjectid_defraimp_importquery?: defraimp_importquery_Result | null;
    regardingobjectid_defraimp_importrisklevel?: defraimp_importrisklevel_Result | null;
    regardingobjectid_defraimp_inspectioncoveragerule?: defraimp_inspectioncoveragerule_Result | null;
    regardingobjectid_defraimp_itahc?: defraimp_itahc_Result | null;
    regardingobjectid_defraimp_placeoforigin?: defraimp_placeoforigin_Result | null;
    regardingobjectid_defraimp_sampletest?: defraimp_sampletest_Result | null;
  }
  interface ProcessSession extends ProcessSession_Base, ProcessSession_Relationships {
    executedby_bind$systemusers?: string | null;
    nextlinkedsessionid_bind$processsessions?: string | null;
    ownerid_bind$owners?: string | null;
  }
  interface ProcessSession_Create extends ProcessSession {
    channelaccessprofile_processsession_bind$channelaccessprofiles?: string | null;
    externalparty_processsession_bind$externalparties?: string | null;
    externalpartyitem_processsession_bind$externalpartyitems?: string | null;
    originatingsessionid_bind$processsessions?: string | null;
    previouslinkedsessionid_bind$processsessions?: string | null;
    processid_bind$workflows?: string | null;
    profileid_bind$channelaccessprofilerules?: string | null;
    regardingobjectid_account_bind$accounts?: string | null;
    regardingobjectid_adminsettingsentity_bind$new_admin_settings_entities?: string | null;
    regardingobjectid_annotation_bind$annotations?: string | null;
    regardingobjectid_apisettings_bind$apisettingscollection?: string | null;
    regardingobjectid_appointment_bind$appointments?: string | null;
    regardingobjectid_bookableresource_bind$bookableresources?: string | null;
    regardingobjectid_bookableresourcebooking_bind$bookableresourcebookings?: string | null;
    regardingobjectid_bookableresourcebookingheader_bind$bookableresourcebookingheaders?: string | null;
    regardingobjectid_bookableresourcecategory_bind$bookableresourcecategories?: string | null;
    regardingobjectid_bookableresourcecategoryassn_bind$bookableresourcecategoryassns?: string | null;
    regardingobjectid_bookableresourcecharacteristic_bind$bookableresourcecharacteristics?: string | null;
    regardingobjectid_bookableresourcegroup_bind$bookableresourcegroups?: string | null;
    regardingobjectid_bookingstatus_bind$bookingstatuses?: string | null;
    regardingobjectid_businessunit_bind$businessunits?: string | null;
    regardingobjectid_businessunitnewsarticle_bind$businessunitnewsarticles?: string | null;
    regardingobjectid_campaign_bind$campaigns?: string | null;
    regardingobjectid_campaignactivity_bind$campaignactivities?: string | null;
    regardingobjectid_campaignresponse_bind$campaignresponses?: string | null;
    regardingobjectid_characteristic_bind$characteristics?: string | null;
    regardingobjectid_competitor_bind$competitors?: string | null;
    regardingobjectid_connection_bind$connections?: string | null;
    regardingobjectid_connectionrole_bind$connectionroles?: string | null;
    regardingobjectid_connector_bind$connectors?: string | null;
    regardingobjectid_constraintbasedgroup_bind$constraintbasedgroups?: string | null;
    regardingobjectid_contact_bind$contacts?: string | null;
    regardingobjectid_contract_bind$contracts?: string | null;
    regardingobjectid_contractdetail_bind$contractdetails?: string | null;
    regardingobjectid_contracttemplate_bind$contracttemplates?: string | null;
    regardingobjectid_convertrule_bind$convertrules?: string | null;
    regardingobjectid_customeraddress_bind$customeraddresses?: string | null;
    regardingobjectid_customeropportunityrole_bind$customeropportunityroles?: string | null;
    regardingobjectid_customerrelationship_bind$customerrelationships?: string | null;
    regardingobjectid_defra_accessrequest_bind$defra_accessrequests?: string | null;
    regardingobjectid_defra_address_bind$defra_addresses?: string | null;
    regardingobjectid_defra_addressdetails_bind$defra_addressdetailses?: string | null;
    regardingobjectid_defra_connectiondetails_bind$defra_connectiondetailses?: string | null;
    regardingobjectid_defra_contactsearch_bind$defra_contactsearchs?: string | null;
    regardingobjectid_defra_country_bind$defra_countries?: string | null;
    regardingobjectid_defra_customerconfiguration_bind$defra_customerconfigurations?: string | null;
    regardingobjectid_defra_ggapirequest_bind$defra_ggapirequests?: string | null;
    regardingobjectid_defra_id_bind$defra_ids?: string | null;
    regardingobjectid_defra_invitation_bind$defra_invitations?: string | null;
    regardingobjectid_defra_lobserivcerole_bind$defra_lobserivceroles?: string | null;
    regardingobjectid_defra_lobservice_bind$defra_lobservices?: string | null;
    regardingobjectid_defra_lobserviceapproval_bind$defra_lobserviceapprovals?: string | null;
    regardingobjectid_defra_lobserviceapprovaldetail_bind$defra_lobserviceapprovaldetails?: string | null;
    regardingobjectid_defra_lobserviceuserlink_bind$defra_lobserviceuserlinks?: string | null;
    regardingobjectid_defra_lobserviceuserlinkrequest_bind$defra_lobserviceuserlinkrequests?: string | null;
    regardingobjectid_defra_lobtermsandcondition_bind$defra_lobtermsandconditions?: string | null;
    regardingobjectid_defra_location_bind$defra_locations?: string | null;
    regardingobjectid_defra_relationshipstatus_bind$defra_relationshipstatuses?: string | null;
    regardingobjectid_defra_town_bind$defra_towns?: string | null;
    regardingobjectid_defraexp_additionalcheck_bind$defraexp_additionalchecks?: string | null;
    regardingobjectid_defraexp_additionalcheckconfigurator_bind$defraexp_additionalcheckconfigurators?: string | null;
    regardingobjectid_defraexp_applicationmethod_bind$defraexp_applicationmethods?: string | null;
    regardingobjectid_defraexp_autonumber_bind$defraexp_autonumbers?: string | null;
    regardingobjectid_defraexp_certificateitem_bind$defraexp_certificateitems?: string | null;
    regardingobjectid_defraexp_certificatelifecycle_bind$defraexp_certificatelifecycles?: string | null;
    regardingobjectid_defraexp_certifierorganisation_bind$defraexp_certifierorganisations?: string | null;
    regardingobjectid_defraexp_certifierorganisationaddress_bind$defraexp_certifierorganisationaddresses?: string | null;
    regardingobjectid_defraexp_commoditygroup_bind$defraexp_commoditygroups?: string | null;
    regardingobjectid_defraexp_commodityname_bind$defraexp_commoditynames?: string | null;
    regardingobjectid_defraexp_commoditytype_bind$defraexp_commoditytypes?: string | null;
    regardingobjectid_defraexp_configurationparameter_bind$defraexp_configurationparameters?: string | null;
    regardingobjectid_defraexp_country_bind$defraexp_countries?: string | null;
    regardingobjectid_defraexp_deliverymethod_bind$defraexp_deliverymethods?: string | null;
    regardingobjectid_defraexp_ehctemplate_bind$defraexp_ehctemplates?: string | null;
    regardingobjectid_defraexp_exportapplication_bind$defraexp_exportapplications?: string | null;
    regardingobjectid_defraexp_exportapplicationlifecycle_bind$defraexp_exportapplicationlifecycles?: string | null;
    regardingobjectid_defraexp_office_bind$defraexp_offices?: string | null;
    regardingobjectid_defraexp_reasonfordelay_bind$defraexp_reasonfordelaies?: string | null;
    regardingobjectid_defraimp_apharegion_bind$defraimp_apharegions?: string | null;
    regardingobjectid_defraimp_autonumber_bind$defraimp_autonumbers?: string | null;
    regardingobjectid_defraimp_cved_bind$defraimp_cveds?: string | null;
    regardingobjectid_defraimp_docom_bind$defraimp_docoms?: string | null;
    regardingobjectid_defraimp_goldbronzecommodity_bind$defraimp_goldbronzecommodities?: string | null;
    regardingobjectid_defraimp_importapplication_bind$defraimp_importapplications?: string | null;
    regardingobjectid_defraimp_importapplicationbusinessprocessflow_bind$defraimp_importapplicationbusinessprocessflows?: string | null;
    regardingobjectid_defraimp_importcountrycommodityrisklevel_bind$defraimp_importcountrycommodityrisklevels?: string | null;
    regardingobjectid_defraimp_importinspection_bind$defraimp_importinspections?: string | null;
    regardingobjectid_defraimp_importquery_bind$defraimp_importqueries?: string | null;
    regardingobjectid_defraimp_importrisklevel_bind$defraimp_importrisklevels?: string | null;
    regardingobjectid_defraimp_inspectioncoveragerule_bind$defraimp_inspectioncoveragerules?: string | null;
    regardingobjectid_defraimp_itahc_bind$defraimp_itahcs?: string | null;
    regardingobjectid_defraimp_placeoforigin_bind$defraimp_placeoforigins?: string | null;
    regardingobjectid_defraimp_sampletest_bind$defraimp_sampletests?: string | null;
    regardingobjectid_discount_bind$discounts?: string | null;
    regardingobjectid_discounttype_bind$discounttypes?: string | null;
    regardingobjectid_email_bind$emails?: string | null;
    regardingobjectid_entitlement_bind$entitlements?: string | null;
    regardingobjectid_entitlementchannel_bind$entitlementchannels?: string | null;
    regardingobjectid_entitlemententityallocationtypemapping_bind$entitlemententityallocationtypemappings?: string | null;
    regardingobjectid_entitlementtemplate_bind$entitlementtemplates?: string | null;
    regardingobjectid_environmentvariabledefinition_bind$environmentvariabledefinitions?: string | null;
    regardingobjectid_environmentvariablevalue_bind$environmentvariablevalues?: string | null;
    regardingobjectid_equipment_bind$equipments?: string | null;
    regardingobjectid_expiredprocess_bind$expiredprocesses?: string | null;
    regardingobjectid_fax_bind$faxes?: string | null;
    regardingobjectid_goal_bind$goals?: string | null;
    regardingobjectid_goalrollupquery_bind$goalrollupqueries?: string | null;
    regardingobjectid_holidaywrapper_bind$holidaywrappers?: string | null;
    regardingobjectid_incident_bind$incidents?: string | null;
    regardingobjectid_invoice_bind$invoices?: string | null;
    regardingobjectid_invoicedetail_bind$invoicedetails?: string | null;
    regardingobjectid_kbarticle_bind$kbarticles?: string | null;
    regardingobjectid_kbarticlecomment_bind$kbarticlecomments?: string | null;
    regardingobjectid_kbarticletemplate_bind$kbarticletemplates?: string | null;
    regardingobjectid_knowledgearticle_bind$knowledgearticles?: string | null;
    regardingobjectid_knowledgearticleincident_bind$knowledgearticleincidents?: string | null;
    regardingobjectid_knowledgebaserecord_bind$knowledgebaserecords?: string | null;
    regardingobjectid_lead_bind$leads?: string | null;
    regardingobjectid_leadtoopportunitysalesprocess_bind$leadtoopportunitysalesprocesses?: string | null;
    regardingobjectid_letter_bind$letters?: string | null;
    regardingobjectid_list_bind$lists?: string | null;
    regardingobjectid_mailbox_bind$mailboxes?: string | null;
    regardingobjectid_mailmergetemplate_bind$mailmergetemplates?: string | null;
    regardingobjectid_mbs_pluginprofile_bind$mbs_pluginprofiles?: string | null;
    regardingobjectid_metric_bind$metrics?: string | null;
    regardingobjectid_msdyn_actioncardregarding_bind$msdyn_actioncardregardings?: string | null;
    regardingobjectid_msdyn_actioncardrolesetting_bind$msdyn_actioncardrolesettings?: string | null;
    regardingobjectid_msdyn_aibdataset_bind$msdyn_aibdatasets?: string | null;
    regardingobjectid_msdyn_aibdatasetfile_bind$msdyn_aibdatasetfiles?: string | null;
    regardingobjectid_msdyn_aibdatasetscontainer_bind$msdyn_aibdatasetscontainers?: string | null;
    regardingobjectid_msdyn_aibfile_bind$msdyn_aibfiles?: string | null;
    regardingobjectid_msdyn_aibfileattacheddata_bind$msdyn_aibfileattacheddatas?: string | null;
    regardingobjectid_msdyn_aiconfiguration_bind$msdyn_aiconfigurations?: string | null;
    regardingobjectid_msdyn_aifptrainingdocument_bind$msdyn_aifptrainingdocuments?: string | null;
    regardingobjectid_msdyn_aimodel_bind$msdyn_aimodels?: string | null;
    regardingobjectid_msdyn_aiodimage_bind$msdyn_aiodimages?: string | null;
    regardingobjectid_msdyn_aiodlabel_bind$msdyn_aiodlabels?: string | null;
    regardingobjectid_msdyn_aiodtrainingboundingbox_bind$msdyn_aiodtrainingboundingboxes?: string | null;
    regardingobjectid_msdyn_aiodtrainingimage_bind$msdyn_aiodtrainingimages?: string | null;
    regardingobjectid_msdyn_aitemplate_bind$msdyn_aitemplates?: string | null;
    regardingobjectid_msdyn_analysiscomponent_bind$msdyn_analysiscomponents?: string | null;
    regardingobjectid_msdyn_analysisjob_bind$msdyn_analysisjobs?: string | null;
    regardingobjectid_msdyn_analysisresult_bind$msdyn_analysisresults?: string | null;
    regardingobjectid_msdyn_analysisresultdetail_bind$msdyn_analysisresultdetails?: string | null;
    regardingobjectid_msdyn_attachmentprocessrecords_bind$msdyn_attachmentprocessrecordses?: string | null;
    regardingobjectid_msdyn_autocapturerule_bind$msdyn_autocapturerules?: string | null;
    regardingobjectid_msdyn_autocapturesettings_bind$msdyn_autocapturesettingses?: string | null;
    regardingobjectid_msdyn_azureblobstoragesetting_bind$msdyn_azureblobstoragesettings?: string | null;
    regardingobjectid_msdyn_callablecontext_bind$msdyn_callablecontexts?: string | null;
    regardingobjectid_msdyn_collabgraphresource_bind$msdyn_collabgraphresource?: string | null;
    regardingobjectid_msdyn_databaseversion_bind$msdyn_databaseversions?: string | null;
    regardingobjectid_msdyn_entityrankingrule_bind$msdyn_entityrankingrules?: string | null;
    regardingobjectid_msdyn_flowcardtype_bind$msdyn_flowcardtypes?: string | null;
    regardingobjectid_msdyn_forecastconfiguration_bind$msdyn_forecastconfigurations?: string | null;
    regardingobjectid_msdyn_forecastdefinition_bind$msdyn_forecastdefinitions?: string | null;
    regardingobjectid_msdyn_forecastinstance_bind$msdyn_forecastinstances?: string | null;
    regardingobjectid_msdyn_forecastrecurrence_bind$msdyn_forecastrecurrences?: string | null;
    regardingobjectid_msdyn_helppage_bind$msdyn_helppages?: string | null;
    regardingobjectid_msdyn_icebreakersconfig_bind$msdyn_icebreakersconfigs?: string | null;
    regardingobjectid_msdyn_knowledgearticleimage_bind$msdyn_knowledgearticleimages?: string | null;
    regardingobjectid_msdyn_knowledgearticletemplate_bind$msdyn_knowledgearticletemplates?: string | null;
    regardingobjectid_msdyn_msteamssetting_bind$msdyn_msteamssettings?: string | null;
    regardingobjectid_msdyn_msteamssettingsv2_bind$msdyn_msteamssettingsv2?: string | null;
    regardingobjectid_msdyn_notesanalysisconfig_bind$msdyn_notesanalysisconfigs?: string | null;
    regardingobjectid_msdyn_notesattachmententitysetting_bind$msdyn_notesattachmententitysettings?: string | null;
    regardingobjectid_msdyn_playbookactivity_bind$msdyn_playbookactivities?: string | null;
    regardingobjectid_msdyn_playbookactivityattribute_bind$msdyn_playbookactivityattributes?: string | null;
    regardingobjectid_msdyn_playbookcategory_bind$msdyn_playbookcategories?: string | null;
    regardingobjectid_msdyn_playbookinstance_bind$msdyn_playbookinstances?: string | null;
    regardingobjectid_msdyn_playbooktemplate_bind$msdyn_playbooktemplates?: string | null;
    regardingobjectid_msdyn_postalbum_bind$msdyn_postalbums?: string | null;
    regardingobjectid_msdyn_postconfig_bind$msdyn_postconfigs?: string | null;
    regardingobjectid_msdyn_postruleconfig_bind$msdyn_postruleconfigs?: string | null;
    regardingobjectid_msdyn_relationshipinsightsunifiedconfig_bind$msdyn_relationshipinsightsunifiedconfigs?: string | null;
    regardingobjectid_msdyn_salesinsightssettings_bind$msdyn_salesinsightssettings?: string | null;
    regardingobjectid_msdyn_siconfig_bind$msdyn_siconfigs?: string | null;
    regardingobjectid_msdyn_sikeyvalueconfig_bind$msdyn_sikeyvalueconfigs?: string | null;
    regardingobjectid_msdyn_solutionhealthrule_bind$msdyn_solutionhealthrules?: string | null;
    regardingobjectid_msdyn_solutionhealthruleargument_bind$msdyn_solutionhealthrulearguments?: string | null;
    regardingobjectid_msdyn_solutionhealthruleset_bind$msdyn_solutionhealthrulesets?: string | null;
    regardingobjectid_msdyn_teamscollaboration_bind$msdyn_teamscollaborations?: string | null;
    regardingobjectid_msdyn_untrackedappointment_bind$msdyn_untrackedappointments?: string | null;
    regardingobjectid_msdyn_upgraderun_bind$msdyn_upgraderuns?: string | null;
    regardingobjectid_msdyn_upgradestep_bind$msdyn_upgradesteps?: string | null;
    regardingobjectid_msdyn_upgradeversion_bind$msdyn_upgradeversions?: string | null;
    regardingobjectid_msdyn_wallsavedquery_bind$msdyn_wallsavedqueries?: string | null;
    regardingobjectid_msdyn_wallsavedqueryusersettings_bind$msdyn_wallsavedqueryusersettingses?: string | null;
    regardingobjectid_msfp_emailtemplate_bind$msfp_emailtemplates?: string | null;
    regardingobjectid_msfp_question_bind$msfp_questions?: string | null;
    regardingobjectid_msfp_questionresponse_bind$msfp_questionresponses?: string | null;
    regardingobjectid_msfp_survey_bind$msfp_surveies?: string | null;
    regardingobjectid_msfp_surveyinvite_bind$msfp_surveyinvites?: string | null;
    regardingobjectid_msfp_surveyresponse_bind$msfp_surveyresponses?: string | null;
    regardingobjectid_msfp_unsubscribedrecipient_bind$msfp_unsubscribedrecipients?: string | null;
    regardingobjectid_newprocess_bind$newprocesses?: string | null;
    regardingobjectid_opportunity_bind$opportunities?: string | null;
    regardingobjectid_opportunityproduct_bind$opportunityproducts?: string | null;
    regardingobjectid_opportunitysalesprocess_bind$opportunitysalesprocesses?: string | null;
    regardingobjectid_phonecall_bind$phonecalls?: string | null;
    regardingobjectid_phonetocaseprocess_bind$phonetocaseprocesses?: string | null;
    regardingobjectid_position_bind$positions?: string | null;
    regardingobjectid_pricelevel_bind$pricelevels?: string | null;
    regardingobjectid_product_bind$products?: string | null;
    regardingobjectid_productassociation_bind$productassociations?: string | null;
    regardingobjectid_productpricelevel_bind$productpricelevels?: string | null;
    regardingobjectid_productsubstitute_bind$productsubstitutes?: string | null;
    regardingobjectid_queue_bind$queues?: string | null;
    regardingobjectid_queueitem_bind$queueitems?: string | null;
    regardingobjectid_quote_bind$quotes?: string | null;
    regardingobjectid_quotedetail_bind$quotedetails?: string | null;
    regardingobjectid_ratingmodel_bind$ratingmodels?: string | null;
    regardingobjectid_ratingvalue_bind$ratingvalues?: string | null;
    regardingobjectid_recurringappointmentmaster_bind$recurringappointmentmasters?: string | null;
    regardingobjectid_relationshiprole_bind$relationshiproles?: string | null;
    regardingobjectid_report_bind$reports?: string | null;
    regardingobjectid_rollupfield_bind$rollupfields?: string | null;
    regardingobjectid_routingrule_bind$routingrules?: string | null;
    regardingobjectid_routingruleitem_bind$routingruleitems?: string | null;
    regardingobjectid_salesliterature_bind$salesliteratures?: string | null;
    regardingobjectid_salesliteratureitem_bind$salesliteratureitems?: string | null;
    regardingobjectid_salesorder_bind$salesorders?: string | null;
    regardingobjectid_salesorderdetail_bind$salesorderdetails?: string | null;
    regardingobjectid_service_bind$services?: string | null;
    regardingobjectid_serviceappointment_bind$serviceappointments?: string | null;
    regardingobjectid_serviceplan_bind$serviceplans?: string | null;
    regardingobjectid_sharepointdocumentlocation_bind$sharepointdocumentlocations?: string | null;
    regardingobjectid_sharepointsite_bind$sharepointsites?: string | null;
    regardingobjectid_site_bind$sites?: string | null;
    regardingobjectid_sla_bind$slas?: string | null;
    regardingobjectid_socialactivity_bind$socialactivities?: string | null;
    regardingobjectid_socialprofile_bind$socialprofiles?: string | null;
    regardingobjectid_solutioncomponentattributeconfiguration_bind$solutioncomponentattributeconfigurations?: string | null;
    regardingobjectid_subject_bind$subjects?: string | null;
    regardingobjectid_systemuser_bind$systemusers?: string | null;
    regardingobjectid_task_bind$tasks?: string | null;
    regardingobjectid_team_bind$teams?: string | null;
    regardingobjectid_template_bind$templates?: string | null;
    regardingobjectid_territory_bind$territories?: string | null;
    regardingobjectid_theme_bind$themes?: string | null;
    regardingobjectid_transactioncurrency_bind$transactioncurrencies?: string | null;
    regardingobjectid_translationprocess_bind$translationprocesses?: string | null;
    regardingobjectid_usermapping_bind$usermappings?: string | null;
    regardingobjectid_workflowbinary_bind$workflowbinaries?: string | null;
  }
  interface ProcessSession_Update extends ProcessSession {
  }
  interface ProcessSession_Select {
    activityname: WebAttribute<ProcessSession_Select, { activityname: string | null }, {  }>;
    canceledby_guid: WebAttribute<ProcessSession_Select, { canceledby_guid: string | null }, { canceledby_formatted?: string }>;
    canceledon: WebAttribute<ProcessSession_Select, { canceledon: Date | null }, { canceledon_formatted?: string }>;
    comments: WebAttribute<ProcessSession_Select, { comments: string | null }, {  }>;
    completedby_guid: WebAttribute<ProcessSession_Select, { completedby_guid: string | null }, { completedby_formatted?: string }>;
    completedon: WebAttribute<ProcessSession_Select, { completedon: Date | null }, { completedon_formatted?: string }>;
    createdby_guid: WebAttribute<ProcessSession_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
    createdon: WebAttribute<ProcessSession_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
    createdonbehalfby_guid: WebAttribute<ProcessSession_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
    errorcode: WebAttribute<ProcessSession_Select, { errorcode: number | null }, {  }>;
    executedby_guid: WebAttribute<ProcessSession_Select, { executedby_guid: string | null }, { executedby_formatted?: string }>;
    executedon: WebAttribute<ProcessSession_Select, { executedon: Date | null }, { executedon_formatted?: string }>;
    inputarguments: WebAttribute<ProcessSession_Select, { inputarguments: string | null }, {  }>;
    modifiedby_guid: WebAttribute<ProcessSession_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
    modifiedon: WebAttribute<ProcessSession_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
    modifiedonbehalfby_guid: WebAttribute<ProcessSession_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
    name: WebAttribute<ProcessSession_Select, { name: string | null }, {  }>;
    nextlinkedsessionid_guid: WebAttribute<ProcessSession_Select, { nextlinkedsessionid_guid: string | null }, { nextlinkedsessionid_formatted?: string }>;
    originatingsessionid_guid: WebAttribute<ProcessSession_Select, { originatingsessionid_guid: string | null }, { originatingsessionid_formatted?: string }>;
    ownerid_guid: WebAttribute<ProcessSession_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
    owningbusinessunit_guid: WebAttribute<ProcessSession_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
    owningteam_guid: WebAttribute<ProcessSession_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
    owninguser_guid: WebAttribute<ProcessSession_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
    previouslinkedsessionid_guid: WebAttribute<ProcessSession_Select, { previouslinkedsessionid_guid: string | null }, { previouslinkedsessionid_formatted?: string }>;
    processid_guid: WebAttribute<ProcessSession_Select, { processid_guid: string | null }, { processid_formatted?: string }>;
    processsessionid: WebAttribute<ProcessSession_Select, { processsessionid: string | null }, {  }>;
    processstagename: WebAttribute<ProcessSession_Select, { processstagename: string | null }, {  }>;
    processstate: WebAttribute<ProcessSession_Select, { processstate: string | null }, {  }>;
    protectionkey: WebAttribute<ProcessSession_Select, { protectionkey: string | null }, {  }>;
    regardingobjectid_guid: WebAttribute<ProcessSession_Select, { regardingobjectid_guid: string | null }, { regardingobjectid_formatted?: string }>;
    startedby_guid: WebAttribute<ProcessSession_Select, { startedby_guid: string | null }, { startedby_formatted?: string }>;
    startedon: WebAttribute<ProcessSession_Select, { startedon: Date | null }, { startedon_formatted?: string }>;
    statecode: WebAttribute<ProcessSession_Select, { statecode: processsession_statecode | null }, { statecode_formatted?: string }>;
    statuscode: WebAttribute<ProcessSession_Select, { statuscode: processsession_statuscode | null }, { statuscode_formatted?: string }>;
    stepname: WebAttribute<ProcessSession_Select, { stepname: string | null }, {  }>;
  }
  interface ProcessSession_Filter {
    activityname: string;
    canceledby_guid: XQW.Guid;
    canceledon: Date;
    comments: string;
    completedby_guid: XQW.Guid;
    completedon: Date;
    createdby_guid: XQW.Guid;
    createdon: Date;
    createdonbehalfby_guid: XQW.Guid;
    errorcode: number;
    executedby_guid: XQW.Guid;
    executedon: Date;
    inputarguments: string;
    modifiedby_guid: XQW.Guid;
    modifiedon: Date;
    modifiedonbehalfby_guid: XQW.Guid;
    name: string;
    nextlinkedsessionid_guid: XQW.Guid;
    originatingsessionid_guid: XQW.Guid;
    ownerid_guid: XQW.Guid;
    owningbusinessunit_guid: XQW.Guid;
    owningteam_guid: XQW.Guid;
    owninguser_guid: XQW.Guid;
    previouslinkedsessionid_guid: XQW.Guid;
    processid_guid: XQW.Guid;
    processsessionid: XQW.Guid;
    processstagename: string;
    processstate: string;
    protectionkey: string;
    regardingobjectid_guid: XQW.Guid;
    startedby_guid: XQW.Guid;
    startedon: Date;
    statecode: processsession_statecode;
    statuscode: processsession_statuscode;
    stepname: string;
  }
  interface ProcessSession_Expand {
    ProcessSession_SyncErrors: WebExpand<ProcessSession_Expand, SyncError_Select, SyncError_Filter, { ProcessSession_SyncErrors: SyncError_Result[] }>;
    lk_processsession_nextlinkedsessionid: WebExpand<ProcessSession_Expand, ProcessSession_Select, ProcessSession_Filter, { lk_processsession_nextlinkedsessionid: ProcessSession_Result[] }>;
    lk_processsession_originatingsessionid: WebExpand<ProcessSession_Expand, ProcessSession_Select, ProcessSession_Filter, { lk_processsession_originatingsessionid: ProcessSession_Result[] }>;
    lk_processsession_previouslinkedsessionid: WebExpand<ProcessSession_Expand, ProcessSession_Select, ProcessSession_Filter, { lk_processsession_previouslinkedsessionid: ProcessSession_Result[] }>;
    nextlinkedsessionid: WebExpand<ProcessSession_Expand, ProcessSession_Select, ProcessSession_Filter, { nextlinkedsessionid: ProcessSession_Result }>;
    originatingsessionid: WebExpand<ProcessSession_Expand, ProcessSession_Select, ProcessSession_Filter, { originatingsessionid: ProcessSession_Result }>;
    previouslinkedsessionid: WebExpand<ProcessSession_Expand, ProcessSession_Select, ProcessSession_Filter, { previouslinkedsessionid: ProcessSession_Result }>;
    processid: WebExpand<ProcessSession_Expand, Workflow_Select, Workflow_Filter, { processid: Workflow_Result }>;
    regardingobjectid_defra_country: WebExpand<ProcessSession_Expand, defra_country_Select, defra_country_Filter, { regardingobjectid_defra_country: defra_country_Result }>;
    regardingobjectid_defraexp_commoditytype: WebExpand<ProcessSession_Expand, defraexp_commoditytype_Select, defraexp_commoditytype_Filter, { regardingobjectid_defraexp_commoditytype: defraexp_commoditytype_Result }>;
    regardingobjectid_defraimp_apharegion: WebExpand<ProcessSession_Expand, defraimp_apharegion_Select, defraimp_apharegion_Filter, { regardingobjectid_defraimp_apharegion: defraimp_apharegion_Result }>;
    regardingobjectid_defraimp_autonumber: WebExpand<ProcessSession_Expand, defraimp_autonumber_Select, defraimp_autonumber_Filter, { regardingobjectid_defraimp_autonumber: defraimp_autonumber_Result }>;
    regardingobjectid_defraimp_cved: WebExpand<ProcessSession_Expand, defraimp_cved_Select, defraimp_cved_Filter, { regardingobjectid_defraimp_cved: defraimp_cved_Result }>;
    regardingobjectid_defraimp_docom: WebExpand<ProcessSession_Expand, defraimp_docom_Select, defraimp_docom_Filter, { regardingobjectid_defraimp_docom: defraimp_docom_Result }>;
    regardingobjectid_defraimp_goldbronzecommodity: WebExpand<ProcessSession_Expand, defraimp_goldbronzecommodity_Select, defraimp_goldbronzecommodity_Filter, { regardingobjectid_defraimp_goldbronzecommodity: defraimp_goldbronzecommodity_Result }>;
    regardingobjectid_defraimp_importapplication: WebExpand<ProcessSession_Expand, defraimp_importapplication_Select, defraimp_importapplication_Filter, { regardingobjectid_defraimp_importapplication: defraimp_importapplication_Result }>;
    regardingobjectid_defraimp_importapplicationbusinessprocessflow: WebExpand<ProcessSession_Expand, defraimp_importapplicationbusinessprocessflow_Select, defraimp_importapplicationbusinessprocessflow_Filter, { regardingobjectid_defraimp_importapplicationbusinessprocessflow: defraimp_importapplicationbusinessprocessflow_Result }>;
    regardingobjectid_defraimp_importcountrycommodityrisklevel: WebExpand<ProcessSession_Expand, defraimp_importcountrycommodityrisklevel_Select, defraimp_importcountrycommodityrisklevel_Filter, { regardingobjectid_defraimp_importcountrycommodityrisklevel: defraimp_importcountrycommodityrisklevel_Result }>;
    regardingobjectid_defraimp_importinspection: WebExpand<ProcessSession_Expand, defraimp_importinspection_Select, defraimp_importinspection_Filter, { regardingobjectid_defraimp_importinspection: defraimp_importinspection_Result }>;
    regardingobjectid_defraimp_importquery: WebExpand<ProcessSession_Expand, defraimp_importquery_Select, defraimp_importquery_Filter, { regardingobjectid_defraimp_importquery: defraimp_importquery_Result }>;
    regardingobjectid_defraimp_importrisklevel: WebExpand<ProcessSession_Expand, defraimp_importrisklevel_Select, defraimp_importrisklevel_Filter, { regardingobjectid_defraimp_importrisklevel: defraimp_importrisklevel_Result }>;
    regardingobjectid_defraimp_inspectioncoveragerule: WebExpand<ProcessSession_Expand, defraimp_inspectioncoveragerule_Select, defraimp_inspectioncoveragerule_Filter, { regardingobjectid_defraimp_inspectioncoveragerule: defraimp_inspectioncoveragerule_Result }>;
    regardingobjectid_defraimp_itahc: WebExpand<ProcessSession_Expand, defraimp_itahc_Select, defraimp_itahc_Filter, { regardingobjectid_defraimp_itahc: defraimp_itahc_Result }>;
    regardingobjectid_defraimp_placeoforigin: WebExpand<ProcessSession_Expand, defraimp_placeoforigin_Select, defraimp_placeoforigin_Filter, { regardingobjectid_defraimp_placeoforigin: defraimp_placeoforigin_Result }>;
    regardingobjectid_defraimp_sampletest: WebExpand<ProcessSession_Expand, defraimp_sampletest_Select, defraimp_sampletest_Filter, { regardingobjectid_defraimp_sampletest: defraimp_sampletest_Result }>;
  }
  interface ProcessSession_FormattedResult {
    canceledby_formatted?: string;
    canceledon_formatted?: string;
    completedby_formatted?: string;
    completedon_formatted?: string;
    createdby_formatted?: string;
    createdon_formatted?: string;
    createdonbehalfby_formatted?: string;
    executedby_formatted?: string;
    executedon_formatted?: string;
    modifiedby_formatted?: string;
    modifiedon_formatted?: string;
    modifiedonbehalfby_formatted?: string;
    nextlinkedsessionid_formatted?: string;
    originatingsessionid_formatted?: string;
    ownerid_formatted?: string;
    owningbusinessunit_formatted?: string;
    owningteam_formatted?: string;
    owninguser_formatted?: string;
    previouslinkedsessionid_formatted?: string;
    processid_formatted?: string;
    regardingobjectid_formatted?: string;
    startedby_formatted?: string;
    startedon_formatted?: string;
    statecode_formatted?: string;
    statuscode_formatted?: string;
  }
  interface ProcessSession_Result extends ProcessSession_Base, ProcessSession_Relationships {
    "@odata.etag": string;
    canceledby_guid: string | null;
    completedby_guid: string | null;
    createdby_guid: string | null;
    createdonbehalfby_guid: string | null;
    executedby_guid: string | null;
    modifiedby_guid: string | null;
    modifiedonbehalfby_guid: string | null;
    nextlinkedsessionid_guid: string | null;
    originatingsessionid_guid: string | null;
    ownerid_guid: string | null;
    owningbusinessunit_guid: string | null;
    owningteam_guid: string | null;
    owninguser_guid: string | null;
    previouslinkedsessionid_guid: string | null;
    processid_guid: string | null;
    regardingobjectid_guid: string | null;
    startedby_guid: string | null;
  }
  interface ProcessSession_RelatedOne {
    nextlinkedsessionid: WebMappingRetrieve<WebApi.ProcessSession_Select,WebApi.ProcessSession_Expand,WebApi.ProcessSession_Filter,WebApi.ProcessSession_Fixed,WebApi.ProcessSession_Result,WebApi.ProcessSession_FormattedResult>;
    originatingsessionid: WebMappingRetrieve<WebApi.ProcessSession_Select,WebApi.ProcessSession_Expand,WebApi.ProcessSession_Filter,WebApi.ProcessSession_Fixed,WebApi.ProcessSession_Result,WebApi.ProcessSession_FormattedResult>;
    previouslinkedsessionid: WebMappingRetrieve<WebApi.ProcessSession_Select,WebApi.ProcessSession_Expand,WebApi.ProcessSession_Filter,WebApi.ProcessSession_Fixed,WebApi.ProcessSession_Result,WebApi.ProcessSession_FormattedResult>;
    processid: WebMappingRetrieve<WebApi.Workflow_Select,WebApi.Workflow_Expand,WebApi.Workflow_Filter,WebApi.Workflow_Fixed,WebApi.Workflow_Result,WebApi.Workflow_FormattedResult>;
    regardingobjectid_defra_country: WebMappingRetrieve<WebApi.defra_country_Select,WebApi.defra_country_Expand,WebApi.defra_country_Filter,WebApi.defra_country_Fixed,WebApi.defra_country_Result,WebApi.defra_country_FormattedResult>;
    regardingobjectid_defraexp_commoditytype: WebMappingRetrieve<WebApi.defraexp_commoditytype_Select,WebApi.defraexp_commoditytype_Expand,WebApi.defraexp_commoditytype_Filter,WebApi.defraexp_commoditytype_Fixed,WebApi.defraexp_commoditytype_Result,WebApi.defraexp_commoditytype_FormattedResult>;
    regardingobjectid_defraimp_apharegion: WebMappingRetrieve<WebApi.defraimp_apharegion_Select,WebApi.defraimp_apharegion_Expand,WebApi.defraimp_apharegion_Filter,WebApi.defraimp_apharegion_Fixed,WebApi.defraimp_apharegion_Result,WebApi.defraimp_apharegion_FormattedResult>;
    regardingobjectid_defraimp_autonumber: WebMappingRetrieve<WebApi.defraimp_autonumber_Select,WebApi.defraimp_autonumber_Expand,WebApi.defraimp_autonumber_Filter,WebApi.defraimp_autonumber_Fixed,WebApi.defraimp_autonumber_Result,WebApi.defraimp_autonumber_FormattedResult>;
    regardingobjectid_defraimp_cved: WebMappingRetrieve<WebApi.defraimp_cved_Select,WebApi.defraimp_cved_Expand,WebApi.defraimp_cved_Filter,WebApi.defraimp_cved_Fixed,WebApi.defraimp_cved_Result,WebApi.defraimp_cved_FormattedResult>;
    regardingobjectid_defraimp_docom: WebMappingRetrieve<WebApi.defraimp_docom_Select,WebApi.defraimp_docom_Expand,WebApi.defraimp_docom_Filter,WebApi.defraimp_docom_Fixed,WebApi.defraimp_docom_Result,WebApi.defraimp_docom_FormattedResult>;
    regardingobjectid_defraimp_goldbronzecommodity: WebMappingRetrieve<WebApi.defraimp_goldbronzecommodity_Select,WebApi.defraimp_goldbronzecommodity_Expand,WebApi.defraimp_goldbronzecommodity_Filter,WebApi.defraimp_goldbronzecommodity_Fixed,WebApi.defraimp_goldbronzecommodity_Result,WebApi.defraimp_goldbronzecommodity_FormattedResult>;
    regardingobjectid_defraimp_importapplication: WebMappingRetrieve<WebApi.defraimp_importapplication_Select,WebApi.defraimp_importapplication_Expand,WebApi.defraimp_importapplication_Filter,WebApi.defraimp_importapplication_Fixed,WebApi.defraimp_importapplication_Result,WebApi.defraimp_importapplication_FormattedResult>;
    regardingobjectid_defraimp_importapplicationbusinessprocessflow: WebMappingRetrieve<WebApi.defraimp_importapplicationbusinessprocessflow_Select,WebApi.defraimp_importapplicationbusinessprocessflow_Expand,WebApi.defraimp_importapplicationbusinessprocessflow_Filter,WebApi.defraimp_importapplicationbusinessprocessflow_Fixed,WebApi.defraimp_importapplicationbusinessprocessflow_Result,WebApi.defraimp_importapplicationbusinessprocessflow_FormattedResult>;
    regardingobjectid_defraimp_importcountrycommodityrisklevel: WebMappingRetrieve<WebApi.defraimp_importcountrycommodityrisklevel_Select,WebApi.defraimp_importcountrycommodityrisklevel_Expand,WebApi.defraimp_importcountrycommodityrisklevel_Filter,WebApi.defraimp_importcountrycommodityrisklevel_Fixed,WebApi.defraimp_importcountrycommodityrisklevel_Result,WebApi.defraimp_importcountrycommodityrisklevel_FormattedResult>;
    regardingobjectid_defraimp_importinspection: WebMappingRetrieve<WebApi.defraimp_importinspection_Select,WebApi.defraimp_importinspection_Expand,WebApi.defraimp_importinspection_Filter,WebApi.defraimp_importinspection_Fixed,WebApi.defraimp_importinspection_Result,WebApi.defraimp_importinspection_FormattedResult>;
    regardingobjectid_defraimp_importquery: WebMappingRetrieve<WebApi.defraimp_importquery_Select,WebApi.defraimp_importquery_Expand,WebApi.defraimp_importquery_Filter,WebApi.defraimp_importquery_Fixed,WebApi.defraimp_importquery_Result,WebApi.defraimp_importquery_FormattedResult>;
    regardingobjectid_defraimp_importrisklevel: WebMappingRetrieve<WebApi.defraimp_importrisklevel_Select,WebApi.defraimp_importrisklevel_Expand,WebApi.defraimp_importrisklevel_Filter,WebApi.defraimp_importrisklevel_Fixed,WebApi.defraimp_importrisklevel_Result,WebApi.defraimp_importrisklevel_FormattedResult>;
    regardingobjectid_defraimp_inspectioncoveragerule: WebMappingRetrieve<WebApi.defraimp_inspectioncoveragerule_Select,WebApi.defraimp_inspectioncoveragerule_Expand,WebApi.defraimp_inspectioncoveragerule_Filter,WebApi.defraimp_inspectioncoveragerule_Fixed,WebApi.defraimp_inspectioncoveragerule_Result,WebApi.defraimp_inspectioncoveragerule_FormattedResult>;
    regardingobjectid_defraimp_itahc: WebMappingRetrieve<WebApi.defraimp_itahc_Select,WebApi.defraimp_itahc_Expand,WebApi.defraimp_itahc_Filter,WebApi.defraimp_itahc_Fixed,WebApi.defraimp_itahc_Result,WebApi.defraimp_itahc_FormattedResult>;
    regardingobjectid_defraimp_placeoforigin: WebMappingRetrieve<WebApi.defraimp_placeoforigin_Select,WebApi.defraimp_placeoforigin_Expand,WebApi.defraimp_placeoforigin_Filter,WebApi.defraimp_placeoforigin_Fixed,WebApi.defraimp_placeoforigin_Result,WebApi.defraimp_placeoforigin_FormattedResult>;
    regardingobjectid_defraimp_sampletest: WebMappingRetrieve<WebApi.defraimp_sampletest_Select,WebApi.defraimp_sampletest_Expand,WebApi.defraimp_sampletest_Filter,WebApi.defraimp_sampletest_Fixed,WebApi.defraimp_sampletest_Result,WebApi.defraimp_sampletest_FormattedResult>;
  }
  interface ProcessSession_RelatedMany {
    ProcessSession_SyncErrors: WebMappingRetrieve<WebApi.SyncError_Select,WebApi.SyncError_Expand,WebApi.SyncError_Filter,WebApi.SyncError_Fixed,WebApi.SyncError_Result,WebApi.SyncError_FormattedResult>;
    lk_processsession_nextlinkedsessionid: WebMappingRetrieve<WebApi.ProcessSession_Select,WebApi.ProcessSession_Expand,WebApi.ProcessSession_Filter,WebApi.ProcessSession_Fixed,WebApi.ProcessSession_Result,WebApi.ProcessSession_FormattedResult>;
    lk_processsession_originatingsessionid: WebMappingRetrieve<WebApi.ProcessSession_Select,WebApi.ProcessSession_Expand,WebApi.ProcessSession_Filter,WebApi.ProcessSession_Fixed,WebApi.ProcessSession_Result,WebApi.ProcessSession_FormattedResult>;
    lk_processsession_previouslinkedsessionid: WebMappingRetrieve<WebApi.ProcessSession_Select,WebApi.ProcessSession_Expand,WebApi.ProcessSession_Filter,WebApi.ProcessSession_Fixed,WebApi.ProcessSession_Result,WebApi.ProcessSession_FormattedResult>;
  }
}
interface WebEntitiesRetrieve {
  processsessions: WebMappingRetrieve<WebApi.ProcessSession_Select,WebApi.ProcessSession_Expand,WebApi.ProcessSession_Filter,WebApi.ProcessSession_Fixed,WebApi.ProcessSession_Result,WebApi.ProcessSession_FormattedResult>;
}
interface WebEntitiesRelated {
  processsessions: WebMappingRelated<WebApi.ProcessSession_RelatedOne,WebApi.ProcessSession_RelatedMany>;
}
interface WebEntitiesCUDA {
  processsessions: WebMappingCUDA<WebApi.ProcessSession_Create,WebApi.ProcessSession_Update,WebApi.ProcessSession_Select>;
}
