declare namespace WebApi {
  interface SyncError_Base extends WebEntity {
    action?: string | null;
    actiondata?: string | null;
    createdon?: Date | null;
    description?: string | null;
    errorcode?: string | null;
    errordetail?: string | null;
    errormessage?: string | null;
    errortime?: Date | null;
    errortype?: errortype_errortypecategory | null;
    modifiedon?: Date | null;
    name?: string | null;
    requestdata?: string | null;
    statecode?: syncerror_statecode | null;
    statuscode?: syncerror_statuscode | null;
    syncerrorid?: string | null;
    versionnumber?: number | null;
  }
  interface SyncError_Relationships {
    SyncError_SyncErrors?: SyncError_Result[] | null;
    regardingobjectid_activityparty_syncerror?: ActivityParty_Result | null;
    regardingobjectid_connection_syncerror?: Connection_Result | null;
    regardingobjectid_defra_country?: defra_country_Result | null;
    regardingobjectid_defraexp_commoditytype?: defraexp_commoditytype_Result | null;
    regardingobjectid_defraimp_apharegion?: defraimp_apharegion_Result | null;
    regardingobjectid_defraimp_autonumber?: defraimp_autonumber_Result | null;
    regardingobjectid_defraimp_docom?: defraimp_docom_Result | null;
    regardingobjectid_defraimp_goldbronzecommodity?: defraimp_goldbronzecommodity_Result | null;
    regardingobjectid_defraimp_importapplication?: defraimp_importapplication_Result | null;
    regardingobjectid_defraimp_importcountrycommodityrisklevel?: defraimp_importcountrycommodityrisklevel_Result | null;
    regardingobjectid_defraimp_importinspection?: defraimp_importinspection_Result | null;
    regardingobjectid_defraimp_importnotification?: defraimp_importnotification_Result | null;
    regardingobjectid_defraimp_importquery?: defraimp_importquery_Result | null;
    regardingobjectid_defraimp_importrisklevel?: defraimp_importrisklevel_Result | null;
    regardingobjectid_defraimp_inspectioncoveragerule?: defraimp_inspectioncoveragerule_Result | null;
    regardingobjectid_defraimp_itahc?: defraimp_itahc_Result | null;
    regardingobjectid_defraimp_placeoforigin?: defraimp_placeoforigin_Result | null;
    regardingobjectid_defraimp_sampletest?: defraimp_sampletest_Result | null;
    regardingobjectid_postfollow_syncerror?: PostFollow_Result | null;
    regardingobjectid_processsession_syncerror?: ProcessSession_Result | null;
    regardingobjectid_syncerror_syncerror?: SyncError_Result | null;
    regardingobjectid_systemuser?: SystemUser_Result | null;
    regardingobjectid_systemuser_syncerror?: SystemUser_Result | null;
    regardingobjectid_team_syncerror?: Team_Result | null;
    regardingobjectid_workflow_syncerror?: Workflow_Result | null;
  }
  interface SyncError extends SyncError_Base, SyncError_Relationships {
    ownerid_bind$owners?: string | null;
  }
  interface SyncError_Create extends SyncError {
    regardingobjectid_ExpiredProcess_syncerror_bind$expiredprocesses?: string | null;
    regardingobjectid_LeadToOpportunitySalesProcess_syncerror_bind$leadtoopportunitysalesprocesses?: string | null;
    regardingobjectid_NewProcess_syncerror_bind$newprocesses?: string | null;
    regardingobjectid_OpportunitySalesProcess_syncerror_bind$opportunitysalesprocesses?: string | null;
    regardingobjectid_PhoneToCaseProcess_syncerror_bind$phonetocaseprocesses?: string | null;
    regardingobjectid_TranslationProcess_syncerror_bind$translationprocesses?: string | null;
    regardingobjectid_account_syncerror_bind$accounts?: string | null;
    regardingobjectid_activitymimeattachment_syncerror_bind$activitymimeattachments?: string | null;
    regardingobjectid_activityparty_syncerror_bind$activityparties?: string | null;
    regardingobjectid_adminsettingsentity_bind$new_admin_settings_entities?: string | null;
    regardingobjectid_annotation_syncerror_bind$annotations?: string | null;
    regardingobjectid_appointment_syncerror_bind$appointments?: string | null;
    regardingobjectid_attachment_syncerror_bind$attachments?: string | null;
    regardingobjectid_attributeimageconfig_bind$attributeimageconfigs?: string | null;
    regardingobjectid_bookableresource_syncerror_bind$bookableresources?: string | null;
    regardingobjectid_bookableresourcebooking_syncerror_bind$bookableresourcebookings?: string | null;
    regardingobjectid_bookableresourcebookingexchangesyncidmapping_bind$bookableresourcebookingexchangesyncidmappings?: string | null;
    regardingobjectid_bookableresourcebookingheader_syncerror_bind$bookableresourcebookingheaders?: string | null;
    regardingobjectid_bookableresourcecategory_syncerror_bind$bookableresourcecategories?: string | null;
    regardingobjectid_bookableresourcecategoryassn_syncerror_bind$bookableresourcecategoryassns?: string | null;
    regardingobjectid_bookableresourcecharacteristic_syncerror_bind$bookableresourcecharacteristics?: string | null;
    regardingobjectid_bookableresourcegroup_syncerror_bind$bookableresourcegroups?: string | null;
    regardingobjectid_bookingstatus_syncerror_bind$bookingstatuses?: string | null;
    regardingobjectid_bulkoperation_syncerror_bind$bulkoperations?: string | null;
    regardingobjectid_bulkoperationlog_bind$bulkoperationlogs?: string | null;
    regardingobjectid_businessdatalocalizedlabel_syncerror_bind$businessdatalocalizedlabels?: string | null;
    regardingobjectid_businessunit_syncerror_bind$businessunits?: string | null;
    regardingobjectid_campaign_syncerror_bind$campaigns?: string | null;
    regardingobjectid_campaignactivity_syncerror_bind$campaignactivities?: string | null;
    regardingobjectid_campaignresponse_syncerror_bind$campaignresponses?: string | null;
    regardingobjectid_category_syncerror_bind$categories?: string | null;
    regardingobjectid_channelaccessprofile_syncerror_bind$channelaccessprofiles?: string | null;
    regardingobjectid_channelaccessprofilerule_syncerror_bind$channelaccessprofilerules?: string | null;
    regardingobjectid_channelaccessprofileruleitem_syncerror_bind$channelaccessprofileruleitems?: string | null;
    regardingobjectid_characteristic_syncerror_bind$characteristics?: string | null;
    regardingobjectid_childincidentcount_bind$childincidentcounts?: string | null;
    regardingobjectid_commitment_bind$commitments?: string | null;
    regardingobjectid_competitor_syncerror_bind$competitors?: string | null;
    regardingobjectid_competitoraddress_syncerror_bind$competitoraddresses?: string | null;
    regardingobjectid_connection_syncerror_bind$connections?: string | null;
    regardingobjectid_connectionrole_syncerror_bind$connectionroles?: string | null;
    regardingobjectid_connector_bind$connectors?: string | null;
    regardingobjectid_constraintbasedgroup_bind$constraintbasedgroups?: string | null;
    regardingobjectid_contact_syncerror_bind$contacts?: string | null;
    regardingobjectid_contract_syncerror_bind$contracts?: string | null;
    regardingobjectid_contractdetail_syncerror_bind$contractdetails?: string | null;
    regardingobjectid_contracttemplate_syncerror_bind$contracttemplates?: string | null;
    regardingobjectid_customeraddress_syncerror_bind$customeraddresses?: string | null;
    regardingobjectid_customeropportunityrole_syncerror_bind$customeropportunityroles?: string | null;
    regardingobjectid_defra_accessrequest_bind$defra_accessrequests?: string | null;
    regardingobjectid_defra_address_bind$defra_addresses?: string | null;
    regardingobjectid_defra_addressdetails_bind$defra_addressdetailses?: string | null;
    regardingobjectid_defra_connectiondetails_bind$defra_connectiondetailses?: string | null;
    regardingobjectid_defra_contactsearch_bind$defra_contactsearchs?: string | null;
    regardingobjectid_defra_country_bind$defra_countries?: string | null;
    regardingobjectid_defra_customerconfiguration_bind$defra_customerconfigurations?: string | null;
    regardingobjectid_defra_ggapirequest_bind$defra_ggapirequests?: string | null;
    regardingobjectid_defra_id_bind$defra_ids?: string | null;
    regardingobjectid_defra_invitation_bind$defra_invitations?: string | null;
    regardingobjectid_defra_lobserivcerole_bind$defra_lobserivceroles?: string | null;
    regardingobjectid_defra_lobservice_bind$defra_lobservices?: string | null;
    regardingobjectid_defra_lobserviceapproval_bind$defra_lobserviceapprovals?: string | null;
    regardingobjectid_defra_lobserviceapprovaldetail_bind$defra_lobserviceapprovaldetails?: string | null;
    regardingobjectid_defra_lobserviceuserlink_bind$defra_lobserviceuserlinks?: string | null;
    regardingobjectid_defra_lobserviceuserlinkrequest_bind$defra_lobserviceuserlinkrequests?: string | null;
    regardingobjectid_defra_lobtermsandcondition_bind$defra_lobtermsandconditions?: string | null;
    regardingobjectid_defra_location_bind$defra_locations?: string | null;
    regardingobjectid_defra_relationshipstatus_bind$defra_relationshipstatuses?: string | null;
    regardingobjectid_defra_town_bind$defra_towns?: string | null;
    regardingobjectid_defraexp_additionalcheck_bind$defraexp_additionalchecks?: string | null;
    regardingobjectid_defraexp_additionalcheckconfigurator_bind$defraexp_additionalcheckconfigurators?: string | null;
    regardingobjectid_defraexp_applicationmethod_bind$defraexp_applicationmethods?: string | null;
    regardingobjectid_defraexp_autonumber_bind$defraexp_autonumbers?: string | null;
    regardingobjectid_defraexp_certificateitem_bind$defraexp_certificateitems?: string | null;
    regardingobjectid_defraexp_certificatelifecycle_bind$defraexp_certificatelifecycles?: string | null;
    regardingobjectid_defraexp_certifierorganisation_bind$defraexp_certifierorganisations?: string | null;
    regardingobjectid_defraexp_certifierorganisationaddress_bind$defraexp_certifierorganisationaddresses?: string | null;
    regardingobjectid_defraexp_commoditygroup_bind$defraexp_commoditygroups?: string | null;
    regardingobjectid_defraexp_commodityname_bind$defraexp_commoditynames?: string | null;
    regardingobjectid_defraexp_commoditytype_bind$defraexp_commoditytypes?: string | null;
    regardingobjectid_defraexp_configurationparameter_bind$defraexp_configurationparameters?: string | null;
    regardingobjectid_defraexp_country_bind$defraexp_countries?: string | null;
    regardingobjectid_defraexp_deliverymethod_bind$defraexp_deliverymethods?: string | null;
    regardingobjectid_defraexp_ehctemplate_bind$defraexp_ehctemplates?: string | null;
    regardingobjectid_defraexp_exportapplication_bind$defraexp_exportapplications?: string | null;
    regardingobjectid_defraexp_exportapplicationlifecycle_bind$defraexp_exportapplicationlifecycles?: string | null;
    regardingobjectid_defraexp_office_bind$defraexp_offices?: string | null;
    regardingobjectid_defraexp_reasonfordelay_bind$defraexp_reasonfordelaies?: string | null;
    regardingobjectid_defraimp_apharegion_bind$defraimp_apharegions?: string | null;
    regardingobjectid_defraimp_autonumber_bind$defraimp_autonumbers?: string | null;
    regardingobjectid_defraimp_docom_bind$defraimp_docoms?: string | null;
    regardingobjectid_defraimp_goldbronzecommodity_bind$defraimp_goldbronzecommodities?: string | null;
    regardingobjectid_defraimp_importapplication_bind$defraimp_importapplications?: string | null;
    regardingobjectid_defraimp_importapplicationbusinessprocessflow_bind$defraimp_importapplicationbusinessprocessflows?: string | null;
    regardingobjectid_defraimp_importcountrycommodityrisklevel_bind$defraimp_importcountrycommodityrisklevels?: string | null;
    regardingobjectid_defraimp_importinspection_bind$defraimp_importinspections?: string | null;
    regardingobjectid_defraimp_importnotification_bind$defraimp_importnotifications?: string | null;
    regardingobjectid_defraimp_importquery_bind$defraimp_importqueries?: string | null;
    regardingobjectid_defraimp_importrisklevel_bind$defraimp_importrisklevels?: string | null;
    regardingobjectid_defraimp_inspectioncoveragerule_bind$defraimp_inspectioncoveragerules?: string | null;
    regardingobjectid_defraimp_itahc_bind$defraimp_itahcs?: string | null;
    regardingobjectid_defraimp_placeoforigin_bind$defraimp_placeoforigins?: string | null;
    regardingobjectid_defraimp_sampletest_bind$defraimp_sampletests?: string | null;
    regardingobjectid_discount_syncerror_bind$discounts?: string | null;
    regardingobjectid_discounttype_syncerror_bind$discounttypes?: string | null;
    regardingobjectid_duplicaterule_syncerror_bind$duplicaterules?: string | null;
    regardingobjectid_duplicaterulecondition_syncerror_bind$duplicateruleconditions?: string | null;
    regardingobjectid_dynamicproperty_bind$dynamicproperties?: string | null;
    regardingobjectid_dynamicpropertyassociation_bind$dynamicpropertyassociations?: string | null;
    regardingobjectid_dynamicpropertyinstance_bind$dynamicpropertyinstances?: string | null;
    regardingobjectid_dynamicpropertyoptionsetitem_bind$dynamicpropertyoptionsetitems?: string | null;
    regardingobjectid_email_syncerror_bind$emails?: string | null;
    regardingobjectid_emailserverprofile_syncerror_bind$emailserverprofiles?: string | null;
    regardingobjectid_entitlement_syncerror_bind$entitlements?: string | null;
    regardingobjectid_entitlementchannel_bind$entitlementchannels?: string | null;
    regardingobjectid_entitlemententityallocationtypemapping_bind$entitlemententityallocationtypemappings?: string | null;
    regardingobjectid_entitlementtemplate_syncerror_bind$entitlementtemplates?: string | null;
    regardingobjectid_entitlementtemplatechannel_bind$entitlementtemplatechannels?: string | null;
    regardingobjectid_entityanalyticsconfig_bind$entityanalyticsconfigs?: string | null;
    regardingobjectid_entityimageconfig_bind$entityimageconfigs?: string | null;
    regardingobjectid_environmentvariabledefinition_bind$environmentvariabledefinitions?: string | null;
    regardingobjectid_environmentvariablevalue_bind$environmentvariablevalues?: string | null;
    regardingobjectid_equipment_syncerror_bind$equipments?: string | null;
    regardingobjectid_externalparty_syncerror_bind$externalparties?: string | null;
    regardingobjectid_externalpartyitem_syncerror_bind$externalpartyitems?: string | null;
    regardingobjectid_fax_syncerror_bind$faxes?: string | null;
    regardingobjectid_feedback_syncerror_bind$feedback?: string | null;
    regardingobjectid_fieldpermission_syncerror_bind$fieldpermissions?: string | null;
    regardingobjectid_fieldsecurityprofile_syncerror_bind$fieldsecurityprofiles?: string | null;
    regardingobjectid_fileattachment_syncerror_bind$fileattachments?: string | null;
    regardingobjectid_flowsession_bind$flowsessions?: string | null;
    regardingobjectid_goal_syncerror_bind$goals?: string | null;
    regardingobjectid_goalrollupquery_syncerror_bind$goalrollupqueries?: string | null;
    regardingobjectid_holidaywrapper_bind$holidaywrappers?: string | null;
    regardingobjectid_importmap_syncerror_bind$importmaps?: string | null;
    regardingobjectid_incident_syncerror_bind$incidents?: string | null;
    regardingobjectid_incidentresolution_syncerror_bind$incidentresolutions?: string | null;
    regardingobjectid_internaladdress_syncerror_bind$internaladdresses?: string | null;
    regardingobjectid_invoice_syncerror_bind$invoices?: string | null;
    regardingobjectid_invoicedetail_syncerror_bind$invoicedetails?: string | null;
    regardingobjectid_kbarticle_syncerror_bind$kbarticles?: string | null;
    regardingobjectid_kbarticletemplate_syncerror_bind$kbarticletemplates?: string | null;
    regardingobjectid_knowledgearticle_syncerror_bind$knowledgearticles?: string | null;
    regardingobjectid_knowledgearticleincident_syncerror_bind$knowledgearticleincidents?: string | null;
    regardingobjectid_knowledgearticleviews_syncerror_bind$knowledgearticleviews?: string | null;
    regardingobjectid_knowledgebaserecord_syncerror_bind$knowledgebaserecords?: string | null;
    regardingobjectid_lead_syncerror_bind$leads?: string | null;
    regardingobjectid_leadaddress_syncerror_bind$leadaddresses?: string | null;
    regardingobjectid_letter_syncerror_bind$letters?: string | null;
    regardingobjectid_list_syncerror_bind$lists?: string | null;
    regardingobjectid_mailbox_syncerror_bind$mailboxes?: string | null;
    regardingobjectid_mailmergetemplate_syncerror_bind$mailmergetemplates?: string | null;
    regardingobjectid_metric_syncerror_bind$metrics?: string | null;
    regardingobjectid_msdyn_actioncardregarding_bind$msdyn_actioncardregardings?: string | null;
    regardingobjectid_msdyn_actioncardrolesetting_bind$msdyn_actioncardrolesettings?: string | null;
    regardingobjectid_msdyn_aiconfiguration_bind$msdyn_aiconfigurations?: string | null;
    regardingobjectid_msdyn_aifptrainingdocument_bind$msdyn_aifptrainingdocuments?: string | null;
    regardingobjectid_msdyn_aimodel_bind$msdyn_aimodels?: string | null;
    regardingobjectid_msdyn_aiodimage_bind$msdyn_aiodimages?: string | null;
    regardingobjectid_msdyn_aiodlabel_bind$msdyn_aiodlabels?: string | null;
    regardingobjectid_msdyn_aiodtrainingboundingbox_bind$msdyn_aiodtrainingboundingboxes?: string | null;
    regardingobjectid_msdyn_aiodtrainingimage_bind$msdyn_aiodtrainingimages?: string | null;
    regardingobjectid_msdyn_aitemplate_bind$msdyn_aitemplates?: string | null;
    regardingobjectid_msdyn_analysiscomponent_bind$msdyn_analysiscomponents?: string | null;
    regardingobjectid_msdyn_analysisjob_bind$msdyn_analysisjobs?: string | null;
    regardingobjectid_msdyn_analysisresult_bind$msdyn_analysisresults?: string | null;
    regardingobjectid_msdyn_analysisresultdetail_bind$msdyn_analysisresultdetails?: string | null;
    regardingobjectid_msdyn_attachmentprocessrecords_bind$msdyn_attachmentprocessrecordses?: string | null;
    regardingobjectid_msdyn_azureblobstoragesetting_bind$msdyn_azureblobstoragesettings?: string | null;
    regardingobjectid_msdyn_callablecontext_bind$msdyn_callablecontexts?: string | null;
    regardingobjectid_msdyn_collabgraphresource_bind$msdyn_collabgraphresource?: string | null;
    regardingobjectid_msdyn_databaseversion_bind$msdyn_databaseversions?: string | null;
    regardingobjectid_msdyn_entityrankingrule_bind$msdyn_entityrankingrules?: string | null;
    regardingobjectid_msdyn_flowcardtype_bind$msdyn_flowcardtypes?: string | null;
    regardingobjectid_msdyn_forecastconfiguration_bind$msdyn_forecastconfigurations?: string | null;
    regardingobjectid_msdyn_forecastdefinition_bind$msdyn_forecastdefinitions?: string | null;
    regardingobjectid_msdyn_forecastinstance_bind$msdyn_forecastinstances?: string | null;
    regardingobjectid_msdyn_forecastrecurrence_bind$msdyn_forecastrecurrences?: string | null;
    regardingobjectid_msdyn_helppage_bind$msdyn_helppages?: string | null;
    regardingobjectid_msdyn_icebreakersconfig_bind$msdyn_icebreakersconfigs?: string | null;
    regardingobjectid_msdyn_knowledgearticleimage_bind$msdyn_knowledgearticleimages?: string | null;
    regardingobjectid_msdyn_knowledgearticletemplate_bind$msdyn_knowledgearticletemplates?: string | null;
    regardingobjectid_msdyn_msteamssetting_bind$msdyn_msteamssettings?: string | null;
    regardingobjectid_msdyn_msteamssettingsv2_bind$msdyn_msteamssettingsv2?: string | null;
    regardingobjectid_msdyn_notesanalysisconfig_bind$msdyn_notesanalysisconfigs?: string | null;
    regardingobjectid_msdyn_notesattachmententitysetting_bind$msdyn_notesattachmententitysettings?: string | null;
    regardingobjectid_msdyn_playbookactivity_bind$msdyn_playbookactivities?: string | null;
    regardingobjectid_msdyn_playbookactivityattribute_bind$msdyn_playbookactivityattributes?: string | null;
    regardingobjectid_msdyn_playbookcategory_bind$msdyn_playbookcategories?: string | null;
    regardingobjectid_msdyn_playbookinstance_bind$msdyn_playbookinstances?: string | null;
    regardingobjectid_msdyn_playbooktemplate_bind$msdyn_playbooktemplates?: string | null;
    regardingobjectid_msdyn_postalbum_bind$msdyn_postalbums?: string | null;
    regardingobjectid_msdyn_postconfig_bind$msdyn_postconfigs?: string | null;
    regardingobjectid_msdyn_postruleconfig_bind$msdyn_postruleconfigs?: string | null;
    regardingobjectid_msdyn_relationshipinsightsunifiedconfig_bind$msdyn_relationshipinsightsunifiedconfigs?: string | null;
    regardingobjectid_msdyn_salesinsightssettings_bind$msdyn_salesinsightssettings?: string | null;
    regardingobjectid_msdyn_siconfig_bind$msdyn_siconfigs?: string | null;
    regardingobjectid_msdyn_sikeyvalueconfig_bind$msdyn_sikeyvalueconfigs?: string | null;
    regardingobjectid_msdyn_solutionhealthrule_bind$msdyn_solutionhealthrules?: string | null;
    regardingobjectid_msdyn_solutionhealthruleargument_bind$msdyn_solutionhealthrulearguments?: string | null;
    regardingobjectid_msdyn_solutionhealthruleset_bind$msdyn_solutionhealthrulesets?: string | null;
    regardingobjectid_msdyn_teamscollaboration_bind$msdyn_teamscollaborations?: string | null;
    regardingobjectid_msdyn_untrackedappointment_bind$msdyn_untrackedappointments?: string | null;
    regardingobjectid_msdyn_upgraderun_bind$msdyn_upgraderuns?: string | null;
    regardingobjectid_msdyn_upgradestep_bind$msdyn_upgradesteps?: string | null;
    regardingobjectid_msdyn_upgradeversion_bind$msdyn_upgradeversions?: string | null;
    regardingobjectid_msdyn_wallsavedquery_bind$msdyn_wallsavedqueries?: string | null;
    regardingobjectid_msdyn_wallsavedqueryusersettings_bind$msdyn_wallsavedqueryusersettingses?: string | null;
    regardingobjectid_msfp_emailtemplate_bind$msfp_emailtemplates?: string | null;
    regardingobjectid_msfp_question_bind$msfp_questions?: string | null;
    regardingobjectid_msfp_questionresponse_bind$msfp_questionresponses?: string | null;
    regardingobjectid_msfp_survey_bind$msfp_surveies?: string | null;
    regardingobjectid_msfp_surveyinvite_bind$msfp_surveyinvites?: string | null;
    regardingobjectid_msfp_surveyresponse_bind$msfp_surveyresponses?: string | null;
    regardingobjectid_msfp_unsubscribedrecipient_bind$msfp_unsubscribedrecipients?: string | null;
    regardingobjectid_offlinecommanddefinition_syncerror_bind$offlinecommanddefinitions?: string | null;
    regardingobjectid_opportunity_syncerror_bind$opportunities?: string | null;
    regardingobjectid_opportunityclose_syncerror_bind$opportunitycloses?: string | null;
    regardingobjectid_opportunityproduct_syncerror_bind$opportunityproducts?: string | null;
    regardingobjectid_orderclose_syncerror_bind$ordercloses?: string | null;
    regardingobjectid_organization_syncerror_bind$organizations?: string | null;
    regardingobjectid_phonecall_syncerror_bind$phonecalls?: string | null;
    regardingobjectid_position_syncerror_bind$positions?: string | null;
    regardingobjectid_postfollow_syncerror_bind$postfollows?: string | null;
    regardingobjectid_pricelevel_syncerror_bind$pricelevels?: string | null;
    regardingobjectid_processsession_syncerror_bind$processsessions?: string | null;
    regardingobjectid_processstage_syncerror_bind$processstages?: string | null;
    regardingobjectid_processtrigger_syncerror_bind$processtriggers?: string | null;
    regardingobjectid_product_syncerror_bind$products?: string | null;
    regardingobjectid_productassociation_syncerror_bind$productassociations?: string | null;
    regardingobjectid_productpricelevel_syncerror_bind$productpricelevels?: string | null;
    regardingobjectid_productsubstitute_syncerror_bind$productsubstitutes?: string | null;
    regardingobjectid_publisher_syncerror_bind$publishers?: string | null;
    regardingobjectid_queue_syncerror_bind$queues?: string | null;
    regardingobjectid_queueitem_syncerror_bind$queueitems?: string | null;
    regardingobjectid_quote_syncerror_bind$quotes?: string | null;
    regardingobjectid_quoteclose_syncerror_bind$quotecloses?: string | null;
    regardingobjectid_quotedetail_syncerror_bind$quotedetails?: string | null;
    regardingobjectid_ratingmodel_syncerror_bind$ratingmodels?: string | null;
    regardingobjectid_ratingvalue_syncerror_bind$ratingvalues?: string | null;
    regardingobjectid_recurringappointmentmaster_syncerror_bind$recurringappointmentmasters?: string | null;
    regardingobjectid_report_syncerror_bind$reports?: string | null;
    regardingobjectid_reportcategory_syncerror_bind$reportcategories?: string | null;
    regardingobjectid_resource_syncerror_bind$resources?: string | null;
    regardingobjectid_resourcegroup_syncerror_bind$resourcegroups?: string | null;
    regardingobjectid_resourcegroupexpansion_syncerror_bind$resourcegroupexpansions?: string | null;
    regardingobjectid_resourcespec_bind$resourcespecs?: string | null;
    regardingobjectid_role_syncerror_bind$roles?: string | null;
    regardingobjectid_rollupfield_syncerror_bind$rollupfields?: string | null;
    regardingobjectid_salesliterature_syncerror_bind$salesliteratures?: string | null;
    regardingobjectid_salesliteratureitem_bind$salesliteratureitems?: string | null;
    regardingobjectid_salesorder_syncerror_bind$salesorders?: string | null;
    regardingobjectid_salesorderdetail_syncerror_bind$salesorderdetails?: string | null;
    regardingobjectid_salesprocessinstance_bind$salesprocessinstances?: string | null;
    regardingobjectid_savedquery_syncerror_bind$savedqueries?: string | null;
    regardingobjectid_savedqueryvisualization_syncerror_bind$savedqueryvisualizations?: string | null;
    regardingobjectid_service_syncerror_bind$services?: string | null;
    regardingobjectid_serviceappointment_syncerror_bind$serviceappointments?: string | null;
    regardingobjectid_sharepointdocumentlocation_syncerror_bind$sharepointdocumentlocations?: string | null;
    regardingobjectid_sharepointsite_syncerror_bind$sharepointsites?: string | null;
    regardingobjectid_site_syncerror_bind$sites?: string | null;
    regardingobjectid_sla_syncerror_bind$slas?: string | null;
    regardingobjectid_slaitem_syncerror_bind$slaitems?: string | null;
    regardingobjectid_slakpiinstance_syncerror_bind$slakpiinstances?: string | null;
    regardingobjectid_socialactivity_syncerror_bind$socialactivities?: string | null;
    regardingobjectid_socialprofile_syncerror_bind$socialprofiles?: string | null;
    regardingobjectid_solution_syncerror_bind$solutions?: string | null;
    regardingobjectid_solutioncomponentfileconfiguration_bind$solutioncomponentfileconfigurations?: string | null;
    regardingobjectid_subject_syncerror_bind$subjects?: string | null;
    regardingobjectid_syncerror_syncerror_bind$syncerrors?: string | null;
    regardingobjectid_systemuser_syncerror_bind$systemusers?: string | null;
    regardingobjectid_task_syncerror_bind$tasks?: string | null;
    regardingobjectid_team_syncerror_bind$teams?: string | null;
    regardingobjectid_teamtemplate_syncerror_bind$teamtemplates?: string | null;
    regardingobjectid_template_syncerror_bind$templates?: string | null;
    regardingobjectid_territory_syncerror_bind$territories?: string | null;
    regardingobjectid_topic_bind$topics?: string | null;
    regardingobjectid_topichistory_bind$topichistories?: string | null;
    regardingobjectid_topicmodel_bind$topicmodels?: string | null;
    regardingobjectid_topicmodelconfiguration_bind$topicmodelconfigurations?: string | null;
    regardingobjectid_topicmodelexecutionhistory_bind$topicmodelexecutionhistories?: string | null;
    regardingobjectid_transactioncurrency_syncerror_bind$transactioncurrencies?: string | null;
    regardingobjectid_uom_syncerror_bind$uoms?: string | null;
    regardingobjectid_uomschedule_syncerror_bind$uomschedules?: string | null;
    regardingobjectid_userquery_syncerror_bind$userqueries?: string | null;
    regardingobjectid_userqueryvisualization_syncerror_bind$userqueryvisualizations?: string | null;
    regardingobjectid_workflow_syncerror_bind$workflows?: string | null;
    regardingobjectid_workflowbinary_bind$workflowbinaries?: string | null;
  }
  interface SyncError_Update extends SyncError {
  }
  interface SyncError_Select {
    action: WebAttribute<SyncError_Select, { action: string | null }, {  }>;
    actiondata: WebAttribute<SyncError_Select, { actiondata: string | null }, {  }>;
    createdby_guid: WebAttribute<SyncError_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
    createdon: WebAttribute<SyncError_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
    createdonbehalfby_guid: WebAttribute<SyncError_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
    description: WebAttribute<SyncError_Select, { description: string | null }, {  }>;
    errorcode: WebAttribute<SyncError_Select, { errorcode: string | null }, {  }>;
    errordetail: WebAttribute<SyncError_Select, { errordetail: string | null }, {  }>;
    errormessage: WebAttribute<SyncError_Select, { errormessage: string | null }, {  }>;
    errortime: WebAttribute<SyncError_Select, { errortime: Date | null }, { errortime_formatted?: string }>;
    errortype: WebAttribute<SyncError_Select, { errortype: errortype_errortypecategory | null }, { errortype_formatted?: string }>;
    modifiedby_guid: WebAttribute<SyncError_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
    modifiedon: WebAttribute<SyncError_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
    modifiedonbehalfby_guid: WebAttribute<SyncError_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
    name: WebAttribute<SyncError_Select, { name: string | null }, {  }>;
    ownerid_guid: WebAttribute<SyncError_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
    owningbusinessunit_guid: WebAttribute<SyncError_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
    owningteam_guid: WebAttribute<SyncError_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
    owninguser_guid: WebAttribute<SyncError_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
    regardingobjectid_guid: WebAttribute<SyncError_Select, { regardingobjectid_guid: string | null }, { regardingobjectid_formatted?: string }>;
    requestdata: WebAttribute<SyncError_Select, { requestdata: string | null }, {  }>;
    statecode: WebAttribute<SyncError_Select, { statecode: syncerror_statecode | null }, { statecode_formatted?: string }>;
    statuscode: WebAttribute<SyncError_Select, { statuscode: syncerror_statuscode | null }, { statuscode_formatted?: string }>;
    syncerrorid: WebAttribute<SyncError_Select, { syncerrorid: string | null }, {  }>;
    versionnumber: WebAttribute<SyncError_Select, { versionnumber: number | null }, {  }>;
  }
  interface SyncError_Filter {
    action: string;
    actiondata: string;
    createdby_guid: XQW.Guid;
    createdon: Date;
    createdonbehalfby_guid: XQW.Guid;
    description: string;
    errorcode: string;
    errordetail: string;
    errormessage: string;
    errortime: Date;
    errortype: errortype_errortypecategory;
    modifiedby_guid: XQW.Guid;
    modifiedon: Date;
    modifiedonbehalfby_guid: XQW.Guid;
    name: string;
    ownerid_guid: XQW.Guid;
    owningbusinessunit_guid: XQW.Guid;
    owningteam_guid: XQW.Guid;
    owninguser_guid: XQW.Guid;
    regardingobjectid_guid: XQW.Guid;
    requestdata: string;
    statecode: syncerror_statecode;
    statuscode: syncerror_statuscode;
    syncerrorid: XQW.Guid;
    versionnumber: number;
  }
  interface SyncError_Expand {
    SyncError_SyncErrors: WebExpand<SyncError_Expand, SyncError_Select, SyncError_Filter, { SyncError_SyncErrors: SyncError_Result[] }>;
    createdby: WebExpand<SyncError_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
    createdonbehalfby: WebExpand<SyncError_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
    modifiedby: WebExpand<SyncError_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
    modifiedonbehalfby: WebExpand<SyncError_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
    owningteam: WebExpand<SyncError_Expand, Team_Select, Team_Filter, { owningteam: Team_Result }>;
    regardingobjectid_activityparty_syncerror: WebExpand<SyncError_Expand, ActivityParty_Select, ActivityParty_Filter, { regardingobjectid_activityparty_syncerror: ActivityParty_Result }>;
    regardingobjectid_connection_syncerror: WebExpand<SyncError_Expand, Connection_Select, Connection_Filter, { regardingobjectid_connection_syncerror: Connection_Result }>;
    regardingobjectid_defra_country: WebExpand<SyncError_Expand, defra_country_Select, defra_country_Filter, { regardingobjectid_defra_country: defra_country_Result }>;
    regardingobjectid_defraexp_commoditytype: WebExpand<SyncError_Expand, defraexp_commoditytype_Select, defraexp_commoditytype_Filter, { regardingobjectid_defraexp_commoditytype: defraexp_commoditytype_Result }>;
    regardingobjectid_defraimp_apharegion: WebExpand<SyncError_Expand, defraimp_apharegion_Select, defraimp_apharegion_Filter, { regardingobjectid_defraimp_apharegion: defraimp_apharegion_Result }>;
    regardingobjectid_defraimp_autonumber: WebExpand<SyncError_Expand, defraimp_autonumber_Select, defraimp_autonumber_Filter, { regardingobjectid_defraimp_autonumber: defraimp_autonumber_Result }>;
    regardingobjectid_defraimp_docom: WebExpand<SyncError_Expand, defraimp_docom_Select, defraimp_docom_Filter, { regardingobjectid_defraimp_docom: defraimp_docom_Result }>;
    regardingobjectid_defraimp_goldbronzecommodity: WebExpand<SyncError_Expand, defraimp_goldbronzecommodity_Select, defraimp_goldbronzecommodity_Filter, { regardingobjectid_defraimp_goldbronzecommodity: defraimp_goldbronzecommodity_Result }>;
    regardingobjectid_defraimp_importapplication: WebExpand<SyncError_Expand, defraimp_importapplication_Select, defraimp_importapplication_Filter, { regardingobjectid_defraimp_importapplication: defraimp_importapplication_Result }>;
    regardingobjectid_defraimp_importcountrycommodityrisklevel: WebExpand<SyncError_Expand, defraimp_importcountrycommodityrisklevel_Select, defraimp_importcountrycommodityrisklevel_Filter, { regardingobjectid_defraimp_importcountrycommodityrisklevel: defraimp_importcountrycommodityrisklevel_Result }>;
    regardingobjectid_defraimp_importinspection: WebExpand<SyncError_Expand, defraimp_importinspection_Select, defraimp_importinspection_Filter, { regardingobjectid_defraimp_importinspection: defraimp_importinspection_Result }>;
    regardingobjectid_defraimp_importnotification: WebExpand<SyncError_Expand, defraimp_importnotification_Select, defraimp_importnotification_Filter, { regardingobjectid_defraimp_importnotification: defraimp_importnotification_Result }>;
    regardingobjectid_defraimp_importquery: WebExpand<SyncError_Expand, defraimp_importquery_Select, defraimp_importquery_Filter, { regardingobjectid_defraimp_importquery: defraimp_importquery_Result }>;
    regardingobjectid_defraimp_importrisklevel: WebExpand<SyncError_Expand, defraimp_importrisklevel_Select, defraimp_importrisklevel_Filter, { regardingobjectid_defraimp_importrisklevel: defraimp_importrisklevel_Result }>;
    regardingobjectid_defraimp_inspectioncoveragerule: WebExpand<SyncError_Expand, defraimp_inspectioncoveragerule_Select, defraimp_inspectioncoveragerule_Filter, { regardingobjectid_defraimp_inspectioncoveragerule: defraimp_inspectioncoveragerule_Result }>;
    regardingobjectid_defraimp_itahc: WebExpand<SyncError_Expand, defraimp_itahc_Select, defraimp_itahc_Filter, { regardingobjectid_defraimp_itahc: defraimp_itahc_Result }>;
    regardingobjectid_defraimp_placeoforigin: WebExpand<SyncError_Expand, defraimp_placeoforigin_Select, defraimp_placeoforigin_Filter, { regardingobjectid_defraimp_placeoforigin: defraimp_placeoforigin_Result }>;
    regardingobjectid_defraimp_sampletest: WebExpand<SyncError_Expand, defraimp_sampletest_Select, defraimp_sampletest_Filter, { regardingobjectid_defraimp_sampletest: defraimp_sampletest_Result }>;
    regardingobjectid_postfollow_syncerror: WebExpand<SyncError_Expand, PostFollow_Select, PostFollow_Filter, { regardingobjectid_postfollow_syncerror: PostFollow_Result }>;
    regardingobjectid_processsession_syncerror: WebExpand<SyncError_Expand, ProcessSession_Select, ProcessSession_Filter, { regardingobjectid_processsession_syncerror: ProcessSession_Result }>;
    regardingobjectid_syncerror_syncerror: WebExpand<SyncError_Expand, SyncError_Select, SyncError_Filter, { regardingobjectid_syncerror_syncerror: SyncError_Result }>;
    regardingobjectid_systemuser: WebExpand<SyncError_Expand, SystemUser_Select, SystemUser_Filter, { regardingobjectid_systemuser: SystemUser_Result }>;
    regardingobjectid_systemuser_syncerror: WebExpand<SyncError_Expand, SystemUser_Select, SystemUser_Filter, { regardingobjectid_systemuser_syncerror: SystemUser_Result }>;
    regardingobjectid_team_syncerror: WebExpand<SyncError_Expand, Team_Select, Team_Filter, { regardingobjectid_team_syncerror: Team_Result }>;
    regardingobjectid_workflow_syncerror: WebExpand<SyncError_Expand, Workflow_Select, Workflow_Filter, { regardingobjectid_workflow_syncerror: Workflow_Result }>;
  }
  interface SyncError_FormattedResult {
    createdby_formatted?: string;
    createdon_formatted?: string;
    createdonbehalfby_formatted?: string;
    errortime_formatted?: string;
    errortype_formatted?: string;
    modifiedby_formatted?: string;
    modifiedon_formatted?: string;
    modifiedonbehalfby_formatted?: string;
    ownerid_formatted?: string;
    owningbusinessunit_formatted?: string;
    owningteam_formatted?: string;
    owninguser_formatted?: string;
    regardingobjectid_formatted?: string;
    statecode_formatted?: string;
    statuscode_formatted?: string;
  }
  interface SyncError_Result extends SyncError_Base, SyncError_Relationships {
    "@odata.etag": string;
    createdby_guid: string | null;
    createdonbehalfby_guid: string | null;
    modifiedby_guid: string | null;
    modifiedonbehalfby_guid: string | null;
    ownerid_guid: string | null;
    owningbusinessunit_guid: string | null;
    owningteam_guid: string | null;
    owninguser_guid: string | null;
    regardingobjectid_guid: string | null;
  }
  interface SyncError_RelatedOne {
    createdby: WebMappingRetrieve<WebApi.SystemUser_Select,WebApi.SystemUser_Expand,WebApi.SystemUser_Filter,WebApi.SystemUser_Fixed,WebApi.SystemUser_Result,WebApi.SystemUser_FormattedResult>;
    createdonbehalfby: WebMappingRetrieve<WebApi.SystemUser_Select,WebApi.SystemUser_Expand,WebApi.SystemUser_Filter,WebApi.SystemUser_Fixed,WebApi.SystemUser_Result,WebApi.SystemUser_FormattedResult>;
    modifiedby: WebMappingRetrieve<WebApi.SystemUser_Select,WebApi.SystemUser_Expand,WebApi.SystemUser_Filter,WebApi.SystemUser_Fixed,WebApi.SystemUser_Result,WebApi.SystemUser_FormattedResult>;
    modifiedonbehalfby: WebMappingRetrieve<WebApi.SystemUser_Select,WebApi.SystemUser_Expand,WebApi.SystemUser_Filter,WebApi.SystemUser_Fixed,WebApi.SystemUser_Result,WebApi.SystemUser_FormattedResult>;
    owningteam: WebMappingRetrieve<WebApi.Team_Select,WebApi.Team_Expand,WebApi.Team_Filter,WebApi.Team_Fixed,WebApi.Team_Result,WebApi.Team_FormattedResult>;
    regardingobjectid_activityparty_syncerror: WebMappingRetrieve<WebApi.ActivityParty_Select,WebApi.ActivityParty_Expand,WebApi.ActivityParty_Filter,WebApi.ActivityParty_Fixed,WebApi.ActivityParty_Result,WebApi.ActivityParty_FormattedResult>;
    regardingobjectid_connection_syncerror: WebMappingRetrieve<WebApi.Connection_Select,WebApi.Connection_Expand,WebApi.Connection_Filter,WebApi.Connection_Fixed,WebApi.Connection_Result,WebApi.Connection_FormattedResult>;
    regardingobjectid_defra_country: WebMappingRetrieve<WebApi.defra_country_Select,WebApi.defra_country_Expand,WebApi.defra_country_Filter,WebApi.defra_country_Fixed,WebApi.defra_country_Result,WebApi.defra_country_FormattedResult>;
    regardingobjectid_defraexp_commoditytype: WebMappingRetrieve<WebApi.defraexp_commoditytype_Select,WebApi.defraexp_commoditytype_Expand,WebApi.defraexp_commoditytype_Filter,WebApi.defraexp_commoditytype_Fixed,WebApi.defraexp_commoditytype_Result,WebApi.defraexp_commoditytype_FormattedResult>;
    regardingobjectid_defraimp_apharegion: WebMappingRetrieve<WebApi.defraimp_apharegion_Select,WebApi.defraimp_apharegion_Expand,WebApi.defraimp_apharegion_Filter,WebApi.defraimp_apharegion_Fixed,WebApi.defraimp_apharegion_Result,WebApi.defraimp_apharegion_FormattedResult>;
    regardingobjectid_defraimp_autonumber: WebMappingRetrieve<WebApi.defraimp_autonumber_Select,WebApi.defraimp_autonumber_Expand,WebApi.defraimp_autonumber_Filter,WebApi.defraimp_autonumber_Fixed,WebApi.defraimp_autonumber_Result,WebApi.defraimp_autonumber_FormattedResult>;
    regardingobjectid_defraimp_docom: WebMappingRetrieve<WebApi.defraimp_docom_Select,WebApi.defraimp_docom_Expand,WebApi.defraimp_docom_Filter,WebApi.defraimp_docom_Fixed,WebApi.defraimp_docom_Result,WebApi.defraimp_docom_FormattedResult>;
    regardingobjectid_defraimp_goldbronzecommodity: WebMappingRetrieve<WebApi.defraimp_goldbronzecommodity_Select,WebApi.defraimp_goldbronzecommodity_Expand,WebApi.defraimp_goldbronzecommodity_Filter,WebApi.defraimp_goldbronzecommodity_Fixed,WebApi.defraimp_goldbronzecommodity_Result,WebApi.defraimp_goldbronzecommodity_FormattedResult>;
    regardingobjectid_defraimp_importapplication: WebMappingRetrieve<WebApi.defraimp_importapplication_Select,WebApi.defraimp_importapplication_Expand,WebApi.defraimp_importapplication_Filter,WebApi.defraimp_importapplication_Fixed,WebApi.defraimp_importapplication_Result,WebApi.defraimp_importapplication_FormattedResult>;
    regardingobjectid_defraimp_importcountrycommodityrisklevel: WebMappingRetrieve<WebApi.defraimp_importcountrycommodityrisklevel_Select,WebApi.defraimp_importcountrycommodityrisklevel_Expand,WebApi.defraimp_importcountrycommodityrisklevel_Filter,WebApi.defraimp_importcountrycommodityrisklevel_Fixed,WebApi.defraimp_importcountrycommodityrisklevel_Result,WebApi.defraimp_importcountrycommodityrisklevel_FormattedResult>;
    regardingobjectid_defraimp_importinspection: WebMappingRetrieve<WebApi.defraimp_importinspection_Select,WebApi.defraimp_importinspection_Expand,WebApi.defraimp_importinspection_Filter,WebApi.defraimp_importinspection_Fixed,WebApi.defraimp_importinspection_Result,WebApi.defraimp_importinspection_FormattedResult>;
    regardingobjectid_defraimp_importnotification: WebMappingRetrieve<WebApi.defraimp_importnotification_Select,WebApi.defraimp_importnotification_Expand,WebApi.defraimp_importnotification_Filter,WebApi.defraimp_importnotification_Fixed,WebApi.defraimp_importnotification_Result,WebApi.defraimp_importnotification_FormattedResult>;
    regardingobjectid_defraimp_importquery: WebMappingRetrieve<WebApi.defraimp_importquery_Select,WebApi.defraimp_importquery_Expand,WebApi.defraimp_importquery_Filter,WebApi.defraimp_importquery_Fixed,WebApi.defraimp_importquery_Result,WebApi.defraimp_importquery_FormattedResult>;
    regardingobjectid_defraimp_importrisklevel: WebMappingRetrieve<WebApi.defraimp_importrisklevel_Select,WebApi.defraimp_importrisklevel_Expand,WebApi.defraimp_importrisklevel_Filter,WebApi.defraimp_importrisklevel_Fixed,WebApi.defraimp_importrisklevel_Result,WebApi.defraimp_importrisklevel_FormattedResult>;
    regardingobjectid_defraimp_inspectioncoveragerule: WebMappingRetrieve<WebApi.defraimp_inspectioncoveragerule_Select,WebApi.defraimp_inspectioncoveragerule_Expand,WebApi.defraimp_inspectioncoveragerule_Filter,WebApi.defraimp_inspectioncoveragerule_Fixed,WebApi.defraimp_inspectioncoveragerule_Result,WebApi.defraimp_inspectioncoveragerule_FormattedResult>;
    regardingobjectid_defraimp_itahc: WebMappingRetrieve<WebApi.defraimp_itahc_Select,WebApi.defraimp_itahc_Expand,WebApi.defraimp_itahc_Filter,WebApi.defraimp_itahc_Fixed,WebApi.defraimp_itahc_Result,WebApi.defraimp_itahc_FormattedResult>;
    regardingobjectid_defraimp_placeoforigin: WebMappingRetrieve<WebApi.defraimp_placeoforigin_Select,WebApi.defraimp_placeoforigin_Expand,WebApi.defraimp_placeoforigin_Filter,WebApi.defraimp_placeoforigin_Fixed,WebApi.defraimp_placeoforigin_Result,WebApi.defraimp_placeoforigin_FormattedResult>;
    regardingobjectid_defraimp_sampletest: WebMappingRetrieve<WebApi.defraimp_sampletest_Select,WebApi.defraimp_sampletest_Expand,WebApi.defraimp_sampletest_Filter,WebApi.defraimp_sampletest_Fixed,WebApi.defraimp_sampletest_Result,WebApi.defraimp_sampletest_FormattedResult>;
    regardingobjectid_postfollow_syncerror: WebMappingRetrieve<WebApi.PostFollow_Select,WebApi.PostFollow_Expand,WebApi.PostFollow_Filter,WebApi.PostFollow_Fixed,WebApi.PostFollow_Result,WebApi.PostFollow_FormattedResult>;
    regardingobjectid_processsession_syncerror: WebMappingRetrieve<WebApi.ProcessSession_Select,WebApi.ProcessSession_Expand,WebApi.ProcessSession_Filter,WebApi.ProcessSession_Fixed,WebApi.ProcessSession_Result,WebApi.ProcessSession_FormattedResult>;
    regardingobjectid_syncerror_syncerror: WebMappingRetrieve<WebApi.SyncError_Select,WebApi.SyncError_Expand,WebApi.SyncError_Filter,WebApi.SyncError_Fixed,WebApi.SyncError_Result,WebApi.SyncError_FormattedResult>;
    regardingobjectid_systemuser: WebMappingRetrieve<WebApi.SystemUser_Select,WebApi.SystemUser_Expand,WebApi.SystemUser_Filter,WebApi.SystemUser_Fixed,WebApi.SystemUser_Result,WebApi.SystemUser_FormattedResult>;
    regardingobjectid_systemuser_syncerror: WebMappingRetrieve<WebApi.SystemUser_Select,WebApi.SystemUser_Expand,WebApi.SystemUser_Filter,WebApi.SystemUser_Fixed,WebApi.SystemUser_Result,WebApi.SystemUser_FormattedResult>;
    regardingobjectid_team_syncerror: WebMappingRetrieve<WebApi.Team_Select,WebApi.Team_Expand,WebApi.Team_Filter,WebApi.Team_Fixed,WebApi.Team_Result,WebApi.Team_FormattedResult>;
    regardingobjectid_workflow_syncerror: WebMappingRetrieve<WebApi.Workflow_Select,WebApi.Workflow_Expand,WebApi.Workflow_Filter,WebApi.Workflow_Fixed,WebApi.Workflow_Result,WebApi.Workflow_FormattedResult>;
  }
  interface SyncError_RelatedMany {
    SyncError_SyncErrors: WebMappingRetrieve<WebApi.SyncError_Select,WebApi.SyncError_Expand,WebApi.SyncError_Filter,WebApi.SyncError_Fixed,WebApi.SyncError_Result,WebApi.SyncError_FormattedResult>;
  }
}
interface WebEntitiesRetrieve {
  syncerrors: WebMappingRetrieve<WebApi.SyncError_Select,WebApi.SyncError_Expand,WebApi.SyncError_Filter,WebApi.SyncError_Fixed,WebApi.SyncError_Result,WebApi.SyncError_FormattedResult>;
}
interface WebEntitiesRelated {
  syncerrors: WebMappingRelated<WebApi.SyncError_RelatedOne,WebApi.SyncError_RelatedMany>;
}
interface WebEntitiesCUDA {
  syncerrors: WebMappingCUDA<WebApi.SyncError_Create,WebApi.SyncError_Update,WebApi.SyncError_Select>;
}
