declare namespace WebApi {
  interface SystemUser_Base extends WebEntity {
    accessmode?: systemuser_accessmode | null;
    activedirectoryguid?: string | null;
    address1_addressid?: string | null;
    address1_addresstypecode?: systemuser_address1_addresstypecode | null;
    address1_city?: string | null;
    address1_composite?: string | null;
    address1_country?: string | null;
    address1_county?: string | null;
    address1_fax?: string | null;
    address1_latitude?: number | null;
    address1_line1?: string | null;
    address1_line2?: string | null;
    address1_line3?: string | null;
    address1_longitude?: number | null;
    address1_name?: string | null;
    address1_postalcode?: string | null;
    address1_postofficebox?: string | null;
    address1_shippingmethodcode?: systemuser_address1_shippingmethodcode | null;
    address1_stateorprovince?: string | null;
    address1_telephone1?: string | null;
    address1_telephone2?: string | null;
    address1_telephone3?: string | null;
    address1_upszone?: string | null;
    address1_utcoffset?: number | null;
    address2_addressid?: string | null;
    address2_addresstypecode?: systemuser_address2_addresstypecode | null;
    address2_city?: string | null;
    address2_composite?: string | null;
    address2_country?: string | null;
    address2_county?: string | null;
    address2_fax?: string | null;
    address2_latitude?: number | null;
    address2_line1?: string | null;
    address2_line2?: string | null;
    address2_line3?: string | null;
    address2_longitude?: number | null;
    address2_name?: string | null;
    address2_postalcode?: string | null;
    address2_postofficebox?: string | null;
    address2_shippingmethodcode?: systemuser_address2_shippingmethodcode | null;
    address2_stateorprovince?: string | null;
    address2_telephone1?: string | null;
    address2_telephone2?: string | null;
    address2_telephone3?: string | null;
    address2_upszone?: string | null;
    address2_utcoffset?: number | null;
    applicationid?: string | null;
    applicationiduri?: string | null;
    azureactivedirectoryobjectid?: string | null;
    caltype?: systemuser_caltype | null;
    createdon?: Date | null;
    defaultfilterspopulated?: boolean | null;
    defaultodbfoldername?: string | null;
    disabledreason?: string | null;
    displayinserviceviews?: boolean | null;
    domainname?: string | null;
    emailrouteraccessapproval?: systemuser_emailrouteraccessapproval | null;
    employeeid?: string | null;
    entityimageid?: string | null;
    exchangerate?: number | null;
    firstname?: string | null;
    fullname?: string | null;
    governmentid?: string | null;
    homephone?: string | null;
    identityid?: number | null;
    importsequencenumber?: number | null;
    incomingemaildeliverymethod?: systemuser_incomingemaildeliverymethod | null;
    internalemailaddress?: string | null;
    invitestatuscode?: systemuser_invitestatuscode | null;
    isactivedirectoryuser?: boolean | null;
    isdisabled?: boolean | null;
    isemailaddressapprovedbyo365admin?: boolean | null;
    isintegrationuser?: boolean | null;
    islicensed?: boolean | null;
    issyncwithdirectory?: boolean | null;
    jobtitle?: string | null;
    lastname?: string | null;
    latestupdatetime?: Date | null;
    middlename?: string | null;
    mobilealertemail?: string | null;
    mobilephone?: string | null;
    modifiedon?: Date | null;
    msdyn_gdproptout?: boolean | null;
    nickname?: string | null;
    organizationid?: string | null;
    outgoingemaildeliverymethod?: systemuser_outgoingemaildeliverymethod | null;
    overriddencreatedon?: Date | null;
    passporthi?: number | null;
    passportlo?: number | null;
    personalemailaddress?: string | null;
    photourl?: string | null;
    preferredaddresscode?: systemuser_preferredaddresscode | null;
    preferredemailcode?: systemuser_preferredemailcode | null;
    preferredphonecode?: systemuser_preferredphonecode | null;
    processid?: string | null;
    salutation?: string | null;
    setupuser?: boolean | null;
    sharepointemailaddress?: string | null;
    skills?: string | null;
    stageid?: string | null;
    systemuserid?: string | null;
    timezoneruleversionnumber?: number | null;
    title?: string | null;
    traversedpath?: string | null;
    userlicensetype?: number | null;
    userpuid?: string | null;
    utcconversiontimezonecode?: number | null;
    versionnumber?: number | null;
    windowsliveid?: string | null;
    yammeremailaddress?: string | null;
    yammeruserid?: string | null;
  }
  interface SystemUser_Relationships {
    SystemUser_ProcessSessions?: ProcessSession_Result[] | null;
    SystemUser_SyncError?: SyncError_Result[] | null;
    SystemUser_SyncErrors?: SyncError_Result[] | null;
    createdby_connection?: Connection_Result[] | null;
    defraimp_importquery_systemuser_createdby?: defraimp_importquery_Result[] | null;
    defraimp_importquery_systemuser_createdonbehalfby?: defraimp_importquery_Result[] | null;
    defraimp_importquery_systemuser_modifiedby?: defraimp_importquery_Result[] | null;
    defraimp_importquery_systemuser_modifiedonbehalfby?: defraimp_importquery_Result[] | null;
    defraimp_importquery_systemuser_owninguser?: defraimp_importquery_Result[] | null;
    defraimp_systemuser_defraimp_importinspection_IV17ReviewApprovedBy?: defraimp_importinspection_Result[] | null;
    lk_PostFollow_createdby?: PostFollow_Result[] | null;
    lk_connectionbase_createdonbehalfby?: Connection_Result[] | null;
    lk_connectionbase_modifiedonbehalfby?: Connection_Result[] | null;
    lk_defra_country_createdby?: defra_country_Result[] | null;
    lk_defra_country_createdonbehalfby?: defra_country_Result[] | null;
    lk_defra_country_modifiedby?: defra_country_Result[] | null;
    lk_defra_country_modifiedonbehalfby?: defra_country_Result[] | null;
    lk_defraexp_commoditytype_createdby?: defraexp_commoditytype_Result[] | null;
    lk_defraexp_commoditytype_createdonbehalfby?: defraexp_commoditytype_Result[] | null;
    lk_defraexp_commoditytype_modifiedby?: defraexp_commoditytype_Result[] | null;
    lk_defraexp_commoditytype_modifiedonbehalfby?: defraexp_commoditytype_Result[] | null;
    lk_defraimp_apharegion_createdby?: defraimp_apharegion_Result[] | null;
    lk_defraimp_apharegion_createdonbehalfby?: defraimp_apharegion_Result[] | null;
    lk_defraimp_apharegion_modifiedby?: defraimp_apharegion_Result[] | null;
    lk_defraimp_apharegion_modifiedonbehalfby?: defraimp_apharegion_Result[] | null;
    lk_defraimp_autonumber_createdby?: defraimp_autonumber_Result[] | null;
    lk_defraimp_autonumber_createdonbehalfby?: defraimp_autonumber_Result[] | null;
    lk_defraimp_autonumber_modifiedby?: defraimp_autonumber_Result[] | null;
    lk_defraimp_autonumber_modifiedonbehalfby?: defraimp_autonumber_Result[] | null;
    lk_defraimp_docom_createdby?: defraimp_docom_Result[] | null;
    lk_defraimp_docom_createdonbehalfby?: defraimp_docom_Result[] | null;
    lk_defraimp_docom_modifiedby?: defraimp_docom_Result[] | null;
    lk_defraimp_docom_modifiedonbehalfby?: defraimp_docom_Result[] | null;
    lk_defraimp_goldbronzecommodity_createdby?: defraimp_goldbronzecommodity_Result[] | null;
    lk_defraimp_goldbronzecommodity_createdonbehalfby?: defraimp_goldbronzecommodity_Result[] | null;
    lk_defraimp_goldbronzecommodity_modifiedby?: defraimp_goldbronzecommodity_Result[] | null;
    lk_defraimp_goldbronzecommodity_modifiedonbehalfby?: defraimp_goldbronzecommodity_Result[] | null;
    lk_defraimp_importapplication_createdby?: defraimp_importapplication_Result[] | null;
    lk_defraimp_importapplication_createdonbehalfby?: defraimp_importapplication_Result[] | null;
    lk_defraimp_importapplication_modifiedby?: defraimp_importapplication_Result[] | null;
    lk_defraimp_importapplication_modifiedonbehalfby?: defraimp_importapplication_Result[] | null;
    lk_defraimp_importcountrycommodityrisklevel_createdby?: defraimp_importcountrycommodityrisklevel_Result[] | null;
    lk_defraimp_importcountrycommodityrisklevel_createdonbehalfby?: defraimp_importcountrycommodityrisklevel_Result[] | null;
    lk_defraimp_importcountrycommodityrisklevel_modifiedby?: defraimp_importcountrycommodityrisklevel_Result[] | null;
    lk_defraimp_importcountrycommodityrisklevel_modifiedonbehalfby?: defraimp_importcountrycommodityrisklevel_Result[] | null;
    lk_defraimp_importinspection_createdby?: defraimp_importinspection_Result[] | null;
    lk_defraimp_importinspection_createdonbehalfby?: defraimp_importinspection_Result[] | null;
    lk_defraimp_importinspection_modifiedby?: defraimp_importinspection_Result[] | null;
    lk_defraimp_importinspection_modifiedonbehalfby?: defraimp_importinspection_Result[] | null;
    lk_defraimp_importnotification_createdby?: defraimp_importnotification_Result[] | null;
    lk_defraimp_importnotification_createdonbehalfby?: defraimp_importnotification_Result[] | null;
    lk_defraimp_importnotification_modifiedby?: defraimp_importnotification_Result[] | null;
    lk_defraimp_importnotification_modifiedonbehalfby?: defraimp_importnotification_Result[] | null;
    lk_defraimp_importrisklevel_createdby?: defraimp_importrisklevel_Result[] | null;
    lk_defraimp_importrisklevel_createdonbehalfby?: defraimp_importrisklevel_Result[] | null;
    lk_defraimp_importrisklevel_modifiedby?: defraimp_importrisklevel_Result[] | null;
    lk_defraimp_importrisklevel_modifiedonbehalfby?: defraimp_importrisklevel_Result[] | null;
    lk_defraimp_inspectioncoveragerule_createdby?: defraimp_inspectioncoveragerule_Result[] | null;
    lk_defraimp_inspectioncoveragerule_createdonbehalfby?: defraimp_inspectioncoveragerule_Result[] | null;
    lk_defraimp_inspectioncoveragerule_modifiedby?: defraimp_inspectioncoveragerule_Result[] | null;
    lk_defraimp_inspectioncoveragerule_modifiedonbehalfby?: defraimp_inspectioncoveragerule_Result[] | null;
    lk_defraimp_itahc_createdby?: defraimp_itahc_Result[] | null;
    lk_defraimp_itahc_createdonbehalfby?: defraimp_itahc_Result[] | null;
    lk_defraimp_itahc_modifiedby?: defraimp_itahc_Result[] | null;
    lk_defraimp_itahc_modifiedonbehalfby?: defraimp_itahc_Result[] | null;
    lk_defraimp_placeoforigin_createdby?: defraimp_placeoforigin_Result[] | null;
    lk_defraimp_placeoforigin_createdonbehalfby?: defraimp_placeoforigin_Result[] | null;
    lk_defraimp_placeoforigin_modifiedby?: defraimp_placeoforigin_Result[] | null;
    lk_defraimp_placeoforigin_modifiedonbehalfby?: defraimp_placeoforigin_Result[] | null;
    lk_defraimp_sampletest_createdby?: defraimp_sampletest_Result[] | null;
    lk_defraimp_sampletest_createdonbehalfby?: defraimp_sampletest_Result[] | null;
    lk_defraimp_sampletest_modifiedby?: defraimp_sampletest_Result[] | null;
    lk_defraimp_sampletest_modifiedonbehalfby?: defraimp_sampletest_Result[] | null;
    lk_post_createdby?: Post_Result[] | null;
    lk_post_createdonbehalfby?: Post_Result[] | null;
    lk_post_modifiedby?: Post_Result[] | null;
    lk_post_modifiedonbehalfby?: Post_Result[] | null;
    lk_postfollow_createdonbehalfby?: PostFollow_Result[] | null;
    lk_processsession_canceledby?: ProcessSession_Result[] | null;
    lk_processsession_completedby?: ProcessSession_Result[] | null;
    lk_processsession_createdby?: ProcessSession_Result[] | null;
    lk_processsession_executedby?: ProcessSession_Result[] | null;
    lk_processsession_modifiedby?: ProcessSession_Result[] | null;
    lk_processsession_startedby?: ProcessSession_Result[] | null;
    lk_processsessionbase_createdonbehalfby?: ProcessSession_Result[] | null;
    lk_processsessionbase_modifiedonbehalfby?: ProcessSession_Result[] | null;
    lk_syncerrorbase_createdby?: SyncError_Result[] | null;
    lk_syncerrorbase_createdonbehalfby?: SyncError_Result[] | null;
    lk_syncerrorbase_modifiedby?: SyncError_Result[] | null;
    lk_syncerrorbase_modifiedonbehalfby?: SyncError_Result[] | null;
    lk_systemuser_createdonbehalfby?: SystemUser_Result[] | null;
    lk_systemuser_modifiedonbehalfby?: SystemUser_Result[] | null;
    lk_systemuserbase_createdby?: SystemUser_Result[] | null;
    lk_systemuserbase_modifiedby?: SystemUser_Result[] | null;
    lk_team_createdonbehalfby?: Team_Result[] | null;
    lk_team_modifiedonbehalfby?: Team_Result[] | null;
    lk_teambase_administratorid?: Team_Result[] | null;
    lk_teambase_createdby?: Team_Result[] | null;
    lk_teambase_modifiedby?: Team_Result[] | null;
    modifiedby_connection?: Connection_Result[] | null;
    system_user_activity_parties?: ActivityParty_Result[] | null;
    system_user_workflow?: Workflow_Result[] | null;
    systemuser_PostFollows?: PostFollow_Result[] | null;
    systemuser_connections1?: Connection_Result[] | null;
    systemuser_connections2?: Connection_Result[] | null;
    teammembership_association?: Team_Result[] | null;
    user_defra_country?: defra_country_Result[] | null;
    user_defraexp_commoditytype?: defraexp_commoditytype_Result[] | null;
    user_defraimp_apharegion?: defraimp_apharegion_Result[] | null;
    user_defraimp_docom?: defraimp_docom_Result[] | null;
    user_defraimp_goldbronzecommodity?: defraimp_goldbronzecommodity_Result[] | null;
    user_defraimp_importapplication?: defraimp_importapplication_Result[] | null;
    user_defraimp_importinspection?: defraimp_importinspection_Result[] | null;
    user_defraimp_importnotification?: defraimp_importnotification_Result[] | null;
    user_defraimp_inspectioncoveragerule?: defraimp_inspectioncoveragerule_Result[] | null;
    user_defraimp_itahc?: defraimp_itahc_Result[] | null;
    user_defraimp_placeoforigin?: defraimp_placeoforigin_Result[] | null;
    user_defraimp_sampletest?: defraimp_sampletest_Result[] | null;
    user_owner_postfollows?: PostFollow_Result[] | null;
    user_parent_user?: SystemUser_Result[] | null;
    workflow_createdby?: Workflow_Result[] | null;
    workflow_createdonbehalfby?: Workflow_Result[] | null;
    workflow_modifiedby?: Workflow_Result[] | null;
    workflow_modifiedonbehalfby?: Workflow_Result[] | null;
  }
  interface SystemUser extends SystemUser_Base, SystemUser_Relationships {
    businessunitid_bind$businessunits?: string | null;
    calendarid_bind$calendars?: string | null;
    defraexp_Office_bind$defraexp_offices?: string | null;
    mobileofflineprofileid_bind$mobileofflineprofiles?: string | null;
    parentsystemuserid_bind$systemusers?: string | null;
    positionid_bind$positions?: string | null;
    queueid_bind$queues?: string | null;
    siteid_bind$sites?: string | null;
    stageid_processstage_bind$processstages?: string | null;
    territoryid_bind$territories?: string | null;
    transactioncurrencyid_bind$transactioncurrencies?: string | null;
  }
  interface SystemUser_Create extends SystemUser {
  }
  interface SystemUser_Update extends SystemUser {
  }
  interface SystemUser_Select {
    accessmode: WebAttribute<SystemUser_Select, { accessmode: systemuser_accessmode | null }, { accessmode_formatted?: string }>;
    activedirectoryguid: WebAttribute<SystemUser_Select, { activedirectoryguid: string | null }, {  }>;
    address1_addressid: WebAttribute<SystemUser_Select, { address1_addressid: string | null }, {  }>;
    address1_addresstypecode: WebAttribute<SystemUser_Select, { address1_addresstypecode: systemuser_address1_addresstypecode | null }, { address1_addresstypecode_formatted?: string }>;
    address1_city: WebAttribute<SystemUser_Select, { address1_city: string | null }, {  }>;
    address1_composite: WebAttribute<SystemUser_Select, { address1_composite: string | null }, {  }>;
    address1_country: WebAttribute<SystemUser_Select, { address1_country: string | null }, {  }>;
    address1_county: WebAttribute<SystemUser_Select, { address1_county: string | null }, {  }>;
    address1_fax: WebAttribute<SystemUser_Select, { address1_fax: string | null }, {  }>;
    address1_latitude: WebAttribute<SystemUser_Select, { address1_latitude: number | null }, {  }>;
    address1_line1: WebAttribute<SystemUser_Select, { address1_line1: string | null }, {  }>;
    address1_line2: WebAttribute<SystemUser_Select, { address1_line2: string | null }, {  }>;
    address1_line3: WebAttribute<SystemUser_Select, { address1_line3: string | null }, {  }>;
    address1_longitude: WebAttribute<SystemUser_Select, { address1_longitude: number | null }, {  }>;
    address1_name: WebAttribute<SystemUser_Select, { address1_name: string | null }, {  }>;
    address1_postalcode: WebAttribute<SystemUser_Select, { address1_postalcode: string | null }, {  }>;
    address1_postofficebox: WebAttribute<SystemUser_Select, { address1_postofficebox: string | null }, {  }>;
    address1_shippingmethodcode: WebAttribute<SystemUser_Select, { address1_shippingmethodcode: systemuser_address1_shippingmethodcode | null }, { address1_shippingmethodcode_formatted?: string }>;
    address1_stateorprovince: WebAttribute<SystemUser_Select, { address1_stateorprovince: string | null }, {  }>;
    address1_telephone1: WebAttribute<SystemUser_Select, { address1_telephone1: string | null }, {  }>;
    address1_telephone2: WebAttribute<SystemUser_Select, { address1_telephone2: string | null }, {  }>;
    address1_telephone3: WebAttribute<SystemUser_Select, { address1_telephone3: string | null }, {  }>;
    address1_upszone: WebAttribute<SystemUser_Select, { address1_upszone: string | null }, {  }>;
    address1_utcoffset: WebAttribute<SystemUser_Select, { address1_utcoffset: number | null }, {  }>;
    address2_addressid: WebAttribute<SystemUser_Select, { address2_addressid: string | null }, {  }>;
    address2_addresstypecode: WebAttribute<SystemUser_Select, { address2_addresstypecode: systemuser_address2_addresstypecode | null }, { address2_addresstypecode_formatted?: string }>;
    address2_city: WebAttribute<SystemUser_Select, { address2_city: string | null }, {  }>;
    address2_composite: WebAttribute<SystemUser_Select, { address2_composite: string | null }, {  }>;
    address2_country: WebAttribute<SystemUser_Select, { address2_country: string | null }, {  }>;
    address2_county: WebAttribute<SystemUser_Select, { address2_county: string | null }, {  }>;
    address2_fax: WebAttribute<SystemUser_Select, { address2_fax: string | null }, {  }>;
    address2_latitude: WebAttribute<SystemUser_Select, { address2_latitude: number | null }, {  }>;
    address2_line1: WebAttribute<SystemUser_Select, { address2_line1: string | null }, {  }>;
    address2_line2: WebAttribute<SystemUser_Select, { address2_line2: string | null }, {  }>;
    address2_line3: WebAttribute<SystemUser_Select, { address2_line3: string | null }, {  }>;
    address2_longitude: WebAttribute<SystemUser_Select, { address2_longitude: number | null }, {  }>;
    address2_name: WebAttribute<SystemUser_Select, { address2_name: string | null }, {  }>;
    address2_postalcode: WebAttribute<SystemUser_Select, { address2_postalcode: string | null }, {  }>;
    address2_postofficebox: WebAttribute<SystemUser_Select, { address2_postofficebox: string | null }, {  }>;
    address2_shippingmethodcode: WebAttribute<SystemUser_Select, { address2_shippingmethodcode: systemuser_address2_shippingmethodcode | null }, { address2_shippingmethodcode_formatted?: string }>;
    address2_stateorprovince: WebAttribute<SystemUser_Select, { address2_stateorprovince: string | null }, {  }>;
    address2_telephone1: WebAttribute<SystemUser_Select, { address2_telephone1: string | null }, {  }>;
    address2_telephone2: WebAttribute<SystemUser_Select, { address2_telephone2: string | null }, {  }>;
    address2_telephone3: WebAttribute<SystemUser_Select, { address2_telephone3: string | null }, {  }>;
    address2_upszone: WebAttribute<SystemUser_Select, { address2_upszone: string | null }, {  }>;
    address2_utcoffset: WebAttribute<SystemUser_Select, { address2_utcoffset: number | null }, {  }>;
    applicationid: WebAttribute<SystemUser_Select, { applicationid: string | null }, {  }>;
    applicationiduri: WebAttribute<SystemUser_Select, { applicationiduri: string | null }, {  }>;
    azureactivedirectoryobjectid: WebAttribute<SystemUser_Select, { azureactivedirectoryobjectid: string | null }, {  }>;
    businessunitid_guid: WebAttribute<SystemUser_Select, { businessunitid_guid: string | null }, { businessunitid_formatted?: string }>;
    calendarid_guid: WebAttribute<SystemUser_Select, { calendarid_guid: string | null }, { calendarid_formatted?: string }>;
    caltype: WebAttribute<SystemUser_Select, { caltype: systemuser_caltype | null }, { caltype_formatted?: string }>;
    createdby_guid: WebAttribute<SystemUser_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
    createdon: WebAttribute<SystemUser_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
    createdonbehalfby_guid: WebAttribute<SystemUser_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
    defaultfilterspopulated: WebAttribute<SystemUser_Select, { defaultfilterspopulated: boolean | null }, {  }>;
    defaultmailbox_guid: WebAttribute<SystemUser_Select, { defaultmailbox_guid: string | null }, { defaultmailbox_formatted?: string }>;
    defaultodbfoldername: WebAttribute<SystemUser_Select, { defaultodbfoldername: string | null }, {  }>;
    defraexp_office_guid: WebAttribute<SystemUser_Select, { defraexp_office_guid: string | null }, { defraexp_office_formatted?: string }>;
    disabledreason: WebAttribute<SystemUser_Select, { disabledreason: string | null }, {  }>;
    displayinserviceviews: WebAttribute<SystemUser_Select, { displayinserviceviews: boolean | null }, {  }>;
    domainname: WebAttribute<SystemUser_Select, { domainname: string | null }, {  }>;
    emailrouteraccessapproval: WebAttribute<SystemUser_Select, { emailrouteraccessapproval: systemuser_emailrouteraccessapproval | null }, { emailrouteraccessapproval_formatted?: string }>;
    employeeid: WebAttribute<SystemUser_Select, { employeeid: string | null }, {  }>;
    entityimageid: WebAttribute<SystemUser_Select, { entityimageid: string | null }, {  }>;
    exchangerate: WebAttribute<SystemUser_Select, { exchangerate: number | null }, {  }>;
    firstname: WebAttribute<SystemUser_Select, { firstname: string | null }, {  }>;
    fullname: WebAttribute<SystemUser_Select, { fullname: string | null }, {  }>;
    governmentid: WebAttribute<SystemUser_Select, { governmentid: string | null }, {  }>;
    homephone: WebAttribute<SystemUser_Select, { homephone: string | null }, {  }>;
    identityid: WebAttribute<SystemUser_Select, { identityid: number | null }, {  }>;
    importsequencenumber: WebAttribute<SystemUser_Select, { importsequencenumber: number | null }, {  }>;
    incomingemaildeliverymethod: WebAttribute<SystemUser_Select, { incomingemaildeliverymethod: systemuser_incomingemaildeliverymethod | null }, { incomingemaildeliverymethod_formatted?: string }>;
    internalemailaddress: WebAttribute<SystemUser_Select, { internalemailaddress: string | null }, {  }>;
    invitestatuscode: WebAttribute<SystemUser_Select, { invitestatuscode: systemuser_invitestatuscode | null }, { invitestatuscode_formatted?: string }>;
    isactivedirectoryuser: WebAttribute<SystemUser_Select, { isactivedirectoryuser: boolean | null }, {  }>;
    isdisabled: WebAttribute<SystemUser_Select, { isdisabled: boolean | null }, {  }>;
    isemailaddressapprovedbyo365admin: WebAttribute<SystemUser_Select, { isemailaddressapprovedbyo365admin: boolean | null }, {  }>;
    isintegrationuser: WebAttribute<SystemUser_Select, { isintegrationuser: boolean | null }, {  }>;
    islicensed: WebAttribute<SystemUser_Select, { islicensed: boolean | null }, {  }>;
    issyncwithdirectory: WebAttribute<SystemUser_Select, { issyncwithdirectory: boolean | null }, {  }>;
    jobtitle: WebAttribute<SystemUser_Select, { jobtitle: string | null }, {  }>;
    lastname: WebAttribute<SystemUser_Select, { lastname: string | null }, {  }>;
    latestupdatetime: WebAttribute<SystemUser_Select, { latestupdatetime: Date | null }, { latestupdatetime_formatted?: string }>;
    middlename: WebAttribute<SystemUser_Select, { middlename: string | null }, {  }>;
    mobilealertemail: WebAttribute<SystemUser_Select, { mobilealertemail: string | null }, {  }>;
    mobileofflineprofileid_guid: WebAttribute<SystemUser_Select, { mobileofflineprofileid_guid: string | null }, { mobileofflineprofileid_formatted?: string }>;
    mobilephone: WebAttribute<SystemUser_Select, { mobilephone: string | null }, {  }>;
    modifiedby_guid: WebAttribute<SystemUser_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
    modifiedon: WebAttribute<SystemUser_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
    modifiedonbehalfby_guid: WebAttribute<SystemUser_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
    msdyn_gdproptout: WebAttribute<SystemUser_Select, { msdyn_gdproptout: boolean | null }, {  }>;
    nickname: WebAttribute<SystemUser_Select, { nickname: string | null }, {  }>;
    organizationid: WebAttribute<SystemUser_Select, { organizationid: string | null }, {  }>;
    outgoingemaildeliverymethod: WebAttribute<SystemUser_Select, { outgoingemaildeliverymethod: systemuser_outgoingemaildeliverymethod | null }, { outgoingemaildeliverymethod_formatted?: string }>;
    overriddencreatedon: WebAttribute<SystemUser_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
    parentsystemuserid_guid: WebAttribute<SystemUser_Select, { parentsystemuserid_guid: string | null }, { parentsystemuserid_formatted?: string }>;
    passporthi: WebAttribute<SystemUser_Select, { passporthi: number | null }, {  }>;
    passportlo: WebAttribute<SystemUser_Select, { passportlo: number | null }, {  }>;
    personalemailaddress: WebAttribute<SystemUser_Select, { personalemailaddress: string | null }, {  }>;
    photourl: WebAttribute<SystemUser_Select, { photourl: string | null }, {  }>;
    positionid_guid: WebAttribute<SystemUser_Select, { positionid_guid: string | null }, { positionid_formatted?: string }>;
    preferredaddresscode: WebAttribute<SystemUser_Select, { preferredaddresscode: systemuser_preferredaddresscode | null }, { preferredaddresscode_formatted?: string }>;
    preferredemailcode: WebAttribute<SystemUser_Select, { preferredemailcode: systemuser_preferredemailcode | null }, { preferredemailcode_formatted?: string }>;
    preferredphonecode: WebAttribute<SystemUser_Select, { preferredphonecode: systemuser_preferredphonecode | null }, { preferredphonecode_formatted?: string }>;
    processid: WebAttribute<SystemUser_Select, { processid: string | null }, {  }>;
    queueid_guid: WebAttribute<SystemUser_Select, { queueid_guid: string | null }, { queueid_formatted?: string }>;
    salutation: WebAttribute<SystemUser_Select, { salutation: string | null }, {  }>;
    setupuser: WebAttribute<SystemUser_Select, { setupuser: boolean | null }, {  }>;
    sharepointemailaddress: WebAttribute<SystemUser_Select, { sharepointemailaddress: string | null }, {  }>;
    siteid_guid: WebAttribute<SystemUser_Select, { siteid_guid: string | null }, { siteid_formatted?: string }>;
    skills: WebAttribute<SystemUser_Select, { skills: string | null }, {  }>;
    stageid: WebAttribute<SystemUser_Select, { stageid: string | null }, {  }>;
    systemuserid: WebAttribute<SystemUser_Select, { systemuserid: string | null }, {  }>;
    territoryid_guid: WebAttribute<SystemUser_Select, { territoryid_guid: string | null }, { territoryid_formatted?: string }>;
    timezoneruleversionnumber: WebAttribute<SystemUser_Select, { timezoneruleversionnumber: number | null }, {  }>;
    title: WebAttribute<SystemUser_Select, { title: string | null }, {  }>;
    transactioncurrencyid_guid: WebAttribute<SystemUser_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
    traversedpath: WebAttribute<SystemUser_Select, { traversedpath: string | null }, {  }>;
    userlicensetype: WebAttribute<SystemUser_Select, { userlicensetype: number | null }, {  }>;
    userpuid: WebAttribute<SystemUser_Select, { userpuid: string | null }, {  }>;
    utcconversiontimezonecode: WebAttribute<SystemUser_Select, { utcconversiontimezonecode: number | null }, {  }>;
    versionnumber: WebAttribute<SystemUser_Select, { versionnumber: number | null }, {  }>;
    windowsliveid: WebAttribute<SystemUser_Select, { windowsliveid: string | null }, {  }>;
    yammeremailaddress: WebAttribute<SystemUser_Select, { yammeremailaddress: string | null }, {  }>;
    yammeruserid: WebAttribute<SystemUser_Select, { yammeruserid: string | null }, {  }>;
  }
  interface SystemUser_Filter {
    accessmode: systemuser_accessmode;
    activedirectoryguid: XQW.Guid;
    address1_addressid: XQW.Guid;
    address1_addresstypecode: systemuser_address1_addresstypecode;
    address1_city: string;
    address1_composite: string;
    address1_country: string;
    address1_county: string;
    address1_fax: string;
    address1_latitude: number;
    address1_line1: string;
    address1_line2: string;
    address1_line3: string;
    address1_longitude: number;
    address1_name: string;
    address1_postalcode: string;
    address1_postofficebox: string;
    address1_shippingmethodcode: systemuser_address1_shippingmethodcode;
    address1_stateorprovince: string;
    address1_telephone1: string;
    address1_telephone2: string;
    address1_telephone3: string;
    address1_upszone: string;
    address1_utcoffset: number;
    address2_addressid: XQW.Guid;
    address2_addresstypecode: systemuser_address2_addresstypecode;
    address2_city: string;
    address2_composite: string;
    address2_country: string;
    address2_county: string;
    address2_fax: string;
    address2_latitude: number;
    address2_line1: string;
    address2_line2: string;
    address2_line3: string;
    address2_longitude: number;
    address2_name: string;
    address2_postalcode: string;
    address2_postofficebox: string;
    address2_shippingmethodcode: systemuser_address2_shippingmethodcode;
    address2_stateorprovince: string;
    address2_telephone1: string;
    address2_telephone2: string;
    address2_telephone3: string;
    address2_upszone: string;
    address2_utcoffset: number;
    applicationid: XQW.Guid;
    applicationiduri: string;
    azureactivedirectoryobjectid: XQW.Guid;
    businessunitid_guid: XQW.Guid;
    calendarid_guid: XQW.Guid;
    caltype: systemuser_caltype;
    createdby_guid: XQW.Guid;
    createdon: Date;
    createdonbehalfby_guid: XQW.Guid;
    defaultfilterspopulated: boolean;
    defaultmailbox_guid: XQW.Guid;
    defaultodbfoldername: string;
    defraexp_office_guid: XQW.Guid;
    disabledreason: string;
    displayinserviceviews: boolean;
    domainname: string;
    emailrouteraccessapproval: systemuser_emailrouteraccessapproval;
    employeeid: string;
    entityimageid: XQW.Guid;
    exchangerate: any;
    firstname: string;
    fullname: string;
    governmentid: string;
    homephone: string;
    identityid: number;
    importsequencenumber: number;
    incomingemaildeliverymethod: systemuser_incomingemaildeliverymethod;
    internalemailaddress: string;
    invitestatuscode: systemuser_invitestatuscode;
    isactivedirectoryuser: boolean;
    isdisabled: boolean;
    isemailaddressapprovedbyo365admin: boolean;
    isintegrationuser: boolean;
    islicensed: boolean;
    issyncwithdirectory: boolean;
    jobtitle: string;
    lastname: string;
    latestupdatetime: Date;
    middlename: string;
    mobilealertemail: string;
    mobileofflineprofileid_guid: XQW.Guid;
    mobilephone: string;
    modifiedby_guid: XQW.Guid;
    modifiedon: Date;
    modifiedonbehalfby_guid: XQW.Guid;
    msdyn_gdproptout: boolean;
    nickname: string;
    organizationid: XQW.Guid;
    outgoingemaildeliverymethod: systemuser_outgoingemaildeliverymethod;
    overriddencreatedon: Date;
    parentsystemuserid_guid: XQW.Guid;
    passporthi: number;
    passportlo: number;
    personalemailaddress: string;
    photourl: string;
    positionid_guid: XQW.Guid;
    preferredaddresscode: systemuser_preferredaddresscode;
    preferredemailcode: systemuser_preferredemailcode;
    preferredphonecode: systemuser_preferredphonecode;
    processid: XQW.Guid;
    queueid_guid: XQW.Guid;
    salutation: string;
    setupuser: boolean;
    sharepointemailaddress: string;
    siteid_guid: XQW.Guid;
    skills: string;
    stageid: XQW.Guid;
    systemuserid: XQW.Guid;
    territoryid_guid: XQW.Guid;
    timezoneruleversionnumber: number;
    title: string;
    transactioncurrencyid_guid: XQW.Guid;
    traversedpath: string;
    userlicensetype: number;
    userpuid: string;
    utcconversiontimezonecode: number;
    versionnumber: number;
    windowsliveid: string;
    yammeremailaddress: string;
    yammeruserid: string;
  }
  interface SystemUser_Expand {
    SystemUser_ProcessSessions: WebExpand<SystemUser_Expand, ProcessSession_Select, ProcessSession_Filter, { SystemUser_ProcessSessions: ProcessSession_Result[] }>;
    SystemUser_SyncError: WebExpand<SystemUser_Expand, SyncError_Select, SyncError_Filter, { SystemUser_SyncError: SyncError_Result[] }>;
    SystemUser_SyncErrors: WebExpand<SystemUser_Expand, SyncError_Select, SyncError_Filter, { SystemUser_SyncErrors: SyncError_Result[] }>;
    createdby: WebExpand<SystemUser_Expand, SystemUser_Select, SystemUser_Filter, { createdby: SystemUser_Result }>;
    createdby_connection: WebExpand<SystemUser_Expand, Connection_Select, Connection_Filter, { createdby_connection: Connection_Result[] }>;
    createdonbehalfby: WebExpand<SystemUser_Expand, SystemUser_Select, SystemUser_Filter, { createdonbehalfby: SystemUser_Result }>;
    defraimp_importquery_systemuser_createdby: WebExpand<SystemUser_Expand, defraimp_importquery_Select, defraimp_importquery_Filter, { defraimp_importquery_systemuser_createdby: defraimp_importquery_Result[] }>;
    defraimp_importquery_systemuser_createdonbehalfby: WebExpand<SystemUser_Expand, defraimp_importquery_Select, defraimp_importquery_Filter, { defraimp_importquery_systemuser_createdonbehalfby: defraimp_importquery_Result[] }>;
    defraimp_importquery_systemuser_modifiedby: WebExpand<SystemUser_Expand, defraimp_importquery_Select, defraimp_importquery_Filter, { defraimp_importquery_systemuser_modifiedby: defraimp_importquery_Result[] }>;
    defraimp_importquery_systemuser_modifiedonbehalfby: WebExpand<SystemUser_Expand, defraimp_importquery_Select, defraimp_importquery_Filter, { defraimp_importquery_systemuser_modifiedonbehalfby: defraimp_importquery_Result[] }>;
    defraimp_importquery_systemuser_owninguser: WebExpand<SystemUser_Expand, defraimp_importquery_Select, defraimp_importquery_Filter, { defraimp_importquery_systemuser_owninguser: defraimp_importquery_Result[] }>;
    defraimp_systemuser_defraimp_importinspection_IV17ReviewApprovedBy: WebExpand<SystemUser_Expand, defraimp_importinspection_Select, defraimp_importinspection_Filter, { defraimp_systemuser_defraimp_importinspection_IV17ReviewApprovedBy: defraimp_importinspection_Result[] }>;
    lk_PostFollow_createdby: WebExpand<SystemUser_Expand, PostFollow_Select, PostFollow_Filter, { lk_PostFollow_createdby: PostFollow_Result[] }>;
    lk_connectionbase_createdonbehalfby: WebExpand<SystemUser_Expand, Connection_Select, Connection_Filter, { lk_connectionbase_createdonbehalfby: Connection_Result[] }>;
    lk_connectionbase_modifiedonbehalfby: WebExpand<SystemUser_Expand, Connection_Select, Connection_Filter, { lk_connectionbase_modifiedonbehalfby: Connection_Result[] }>;
    lk_defra_country_createdby: WebExpand<SystemUser_Expand, defra_country_Select, defra_country_Filter, { lk_defra_country_createdby: defra_country_Result[] }>;
    lk_defra_country_createdonbehalfby: WebExpand<SystemUser_Expand, defra_country_Select, defra_country_Filter, { lk_defra_country_createdonbehalfby: defra_country_Result[] }>;
    lk_defra_country_modifiedby: WebExpand<SystemUser_Expand, defra_country_Select, defra_country_Filter, { lk_defra_country_modifiedby: defra_country_Result[] }>;
    lk_defra_country_modifiedonbehalfby: WebExpand<SystemUser_Expand, defra_country_Select, defra_country_Filter, { lk_defra_country_modifiedonbehalfby: defra_country_Result[] }>;
    lk_defraexp_commoditytype_createdby: WebExpand<SystemUser_Expand, defraexp_commoditytype_Select, defraexp_commoditytype_Filter, { lk_defraexp_commoditytype_createdby: defraexp_commoditytype_Result[] }>;
    lk_defraexp_commoditytype_createdonbehalfby: WebExpand<SystemUser_Expand, defraexp_commoditytype_Select, defraexp_commoditytype_Filter, { lk_defraexp_commoditytype_createdonbehalfby: defraexp_commoditytype_Result[] }>;
    lk_defraexp_commoditytype_modifiedby: WebExpand<SystemUser_Expand, defraexp_commoditytype_Select, defraexp_commoditytype_Filter, { lk_defraexp_commoditytype_modifiedby: defraexp_commoditytype_Result[] }>;
    lk_defraexp_commoditytype_modifiedonbehalfby: WebExpand<SystemUser_Expand, defraexp_commoditytype_Select, defraexp_commoditytype_Filter, { lk_defraexp_commoditytype_modifiedonbehalfby: defraexp_commoditytype_Result[] }>;
    lk_defraimp_apharegion_createdby: WebExpand<SystemUser_Expand, defraimp_apharegion_Select, defraimp_apharegion_Filter, { lk_defraimp_apharegion_createdby: defraimp_apharegion_Result[] }>;
    lk_defraimp_apharegion_createdonbehalfby: WebExpand<SystemUser_Expand, defraimp_apharegion_Select, defraimp_apharegion_Filter, { lk_defraimp_apharegion_createdonbehalfby: defraimp_apharegion_Result[] }>;
    lk_defraimp_apharegion_modifiedby: WebExpand<SystemUser_Expand, defraimp_apharegion_Select, defraimp_apharegion_Filter, { lk_defraimp_apharegion_modifiedby: defraimp_apharegion_Result[] }>;
    lk_defraimp_apharegion_modifiedonbehalfby: WebExpand<SystemUser_Expand, defraimp_apharegion_Select, defraimp_apharegion_Filter, { lk_defraimp_apharegion_modifiedonbehalfby: defraimp_apharegion_Result[] }>;
    lk_defraimp_autonumber_createdby: WebExpand<SystemUser_Expand, defraimp_autonumber_Select, defraimp_autonumber_Filter, { lk_defraimp_autonumber_createdby: defraimp_autonumber_Result[] }>;
    lk_defraimp_autonumber_createdonbehalfby: WebExpand<SystemUser_Expand, defraimp_autonumber_Select, defraimp_autonumber_Filter, { lk_defraimp_autonumber_createdonbehalfby: defraimp_autonumber_Result[] }>;
    lk_defraimp_autonumber_modifiedby: WebExpand<SystemUser_Expand, defraimp_autonumber_Select, defraimp_autonumber_Filter, { lk_defraimp_autonumber_modifiedby: defraimp_autonumber_Result[] }>;
    lk_defraimp_autonumber_modifiedonbehalfby: WebExpand<SystemUser_Expand, defraimp_autonumber_Select, defraimp_autonumber_Filter, { lk_defraimp_autonumber_modifiedonbehalfby: defraimp_autonumber_Result[] }>;
    lk_defraimp_docom_createdby: WebExpand<SystemUser_Expand, defraimp_docom_Select, defraimp_docom_Filter, { lk_defraimp_docom_createdby: defraimp_docom_Result[] }>;
    lk_defraimp_docom_createdonbehalfby: WebExpand<SystemUser_Expand, defraimp_docom_Select, defraimp_docom_Filter, { lk_defraimp_docom_createdonbehalfby: defraimp_docom_Result[] }>;
    lk_defraimp_docom_modifiedby: WebExpand<SystemUser_Expand, defraimp_docom_Select, defraimp_docom_Filter, { lk_defraimp_docom_modifiedby: defraimp_docom_Result[] }>;
    lk_defraimp_docom_modifiedonbehalfby: WebExpand<SystemUser_Expand, defraimp_docom_Select, defraimp_docom_Filter, { lk_defraimp_docom_modifiedonbehalfby: defraimp_docom_Result[] }>;
    lk_defraimp_goldbronzecommodity_createdby: WebExpand<SystemUser_Expand, defraimp_goldbronzecommodity_Select, defraimp_goldbronzecommodity_Filter, { lk_defraimp_goldbronzecommodity_createdby: defraimp_goldbronzecommodity_Result[] }>;
    lk_defraimp_goldbronzecommodity_createdonbehalfby: WebExpand<SystemUser_Expand, defraimp_goldbronzecommodity_Select, defraimp_goldbronzecommodity_Filter, { lk_defraimp_goldbronzecommodity_createdonbehalfby: defraimp_goldbronzecommodity_Result[] }>;
    lk_defraimp_goldbronzecommodity_modifiedby: WebExpand<SystemUser_Expand, defraimp_goldbronzecommodity_Select, defraimp_goldbronzecommodity_Filter, { lk_defraimp_goldbronzecommodity_modifiedby: defraimp_goldbronzecommodity_Result[] }>;
    lk_defraimp_goldbronzecommodity_modifiedonbehalfby: WebExpand<SystemUser_Expand, defraimp_goldbronzecommodity_Select, defraimp_goldbronzecommodity_Filter, { lk_defraimp_goldbronzecommodity_modifiedonbehalfby: defraimp_goldbronzecommodity_Result[] }>;
    lk_defraimp_importapplication_createdby: WebExpand<SystemUser_Expand, defraimp_importapplication_Select, defraimp_importapplication_Filter, { lk_defraimp_importapplication_createdby: defraimp_importapplication_Result[] }>;
    lk_defraimp_importapplication_createdonbehalfby: WebExpand<SystemUser_Expand, defraimp_importapplication_Select, defraimp_importapplication_Filter, { lk_defraimp_importapplication_createdonbehalfby: defraimp_importapplication_Result[] }>;
    lk_defraimp_importapplication_modifiedby: WebExpand<SystemUser_Expand, defraimp_importapplication_Select, defraimp_importapplication_Filter, { lk_defraimp_importapplication_modifiedby: defraimp_importapplication_Result[] }>;
    lk_defraimp_importapplication_modifiedonbehalfby: WebExpand<SystemUser_Expand, defraimp_importapplication_Select, defraimp_importapplication_Filter, { lk_defraimp_importapplication_modifiedonbehalfby: defraimp_importapplication_Result[] }>;
    lk_defraimp_importcountrycommodityrisklevel_createdby: WebExpand<SystemUser_Expand, defraimp_importcountrycommodityrisklevel_Select, defraimp_importcountrycommodityrisklevel_Filter, { lk_defraimp_importcountrycommodityrisklevel_createdby: defraimp_importcountrycommodityrisklevel_Result[] }>;
    lk_defraimp_importcountrycommodityrisklevel_createdonbehalfby: WebExpand<SystemUser_Expand, defraimp_importcountrycommodityrisklevel_Select, defraimp_importcountrycommodityrisklevel_Filter, { lk_defraimp_importcountrycommodityrisklevel_createdonbehalfby: defraimp_importcountrycommodityrisklevel_Result[] }>;
    lk_defraimp_importcountrycommodityrisklevel_modifiedby: WebExpand<SystemUser_Expand, defraimp_importcountrycommodityrisklevel_Select, defraimp_importcountrycommodityrisklevel_Filter, { lk_defraimp_importcountrycommodityrisklevel_modifiedby: defraimp_importcountrycommodityrisklevel_Result[] }>;
    lk_defraimp_importcountrycommodityrisklevel_modifiedonbehalfby: WebExpand<SystemUser_Expand, defraimp_importcountrycommodityrisklevel_Select, defraimp_importcountrycommodityrisklevel_Filter, { lk_defraimp_importcountrycommodityrisklevel_modifiedonbehalfby: defraimp_importcountrycommodityrisklevel_Result[] }>;
    lk_defraimp_importinspection_createdby: WebExpand<SystemUser_Expand, defraimp_importinspection_Select, defraimp_importinspection_Filter, { lk_defraimp_importinspection_createdby: defraimp_importinspection_Result[] }>;
    lk_defraimp_importinspection_createdonbehalfby: WebExpand<SystemUser_Expand, defraimp_importinspection_Select, defraimp_importinspection_Filter, { lk_defraimp_importinspection_createdonbehalfby: defraimp_importinspection_Result[] }>;
    lk_defraimp_importinspection_modifiedby: WebExpand<SystemUser_Expand, defraimp_importinspection_Select, defraimp_importinspection_Filter, { lk_defraimp_importinspection_modifiedby: defraimp_importinspection_Result[] }>;
    lk_defraimp_importinspection_modifiedonbehalfby: WebExpand<SystemUser_Expand, defraimp_importinspection_Select, defraimp_importinspection_Filter, { lk_defraimp_importinspection_modifiedonbehalfby: defraimp_importinspection_Result[] }>;
    lk_defraimp_importnotification_createdby: WebExpand<SystemUser_Expand, defraimp_importnotification_Select, defraimp_importnotification_Filter, { lk_defraimp_importnotification_createdby: defraimp_importnotification_Result[] }>;
    lk_defraimp_importnotification_createdonbehalfby: WebExpand<SystemUser_Expand, defraimp_importnotification_Select, defraimp_importnotification_Filter, { lk_defraimp_importnotification_createdonbehalfby: defraimp_importnotification_Result[] }>;
    lk_defraimp_importnotification_modifiedby: WebExpand<SystemUser_Expand, defraimp_importnotification_Select, defraimp_importnotification_Filter, { lk_defraimp_importnotification_modifiedby: defraimp_importnotification_Result[] }>;
    lk_defraimp_importnotification_modifiedonbehalfby: WebExpand<SystemUser_Expand, defraimp_importnotification_Select, defraimp_importnotification_Filter, { lk_defraimp_importnotification_modifiedonbehalfby: defraimp_importnotification_Result[] }>;
    lk_defraimp_importrisklevel_createdby: WebExpand<SystemUser_Expand, defraimp_importrisklevel_Select, defraimp_importrisklevel_Filter, { lk_defraimp_importrisklevel_createdby: defraimp_importrisklevel_Result[] }>;
    lk_defraimp_importrisklevel_createdonbehalfby: WebExpand<SystemUser_Expand, defraimp_importrisklevel_Select, defraimp_importrisklevel_Filter, { lk_defraimp_importrisklevel_createdonbehalfby: defraimp_importrisklevel_Result[] }>;
    lk_defraimp_importrisklevel_modifiedby: WebExpand<SystemUser_Expand, defraimp_importrisklevel_Select, defraimp_importrisklevel_Filter, { lk_defraimp_importrisklevel_modifiedby: defraimp_importrisklevel_Result[] }>;
    lk_defraimp_importrisklevel_modifiedonbehalfby: WebExpand<SystemUser_Expand, defraimp_importrisklevel_Select, defraimp_importrisklevel_Filter, { lk_defraimp_importrisklevel_modifiedonbehalfby: defraimp_importrisklevel_Result[] }>;
    lk_defraimp_inspectioncoveragerule_createdby: WebExpand<SystemUser_Expand, defraimp_inspectioncoveragerule_Select, defraimp_inspectioncoveragerule_Filter, { lk_defraimp_inspectioncoveragerule_createdby: defraimp_inspectioncoveragerule_Result[] }>;
    lk_defraimp_inspectioncoveragerule_createdonbehalfby: WebExpand<SystemUser_Expand, defraimp_inspectioncoveragerule_Select, defraimp_inspectioncoveragerule_Filter, { lk_defraimp_inspectioncoveragerule_createdonbehalfby: defraimp_inspectioncoveragerule_Result[] }>;
    lk_defraimp_inspectioncoveragerule_modifiedby: WebExpand<SystemUser_Expand, defraimp_inspectioncoveragerule_Select, defraimp_inspectioncoveragerule_Filter, { lk_defraimp_inspectioncoveragerule_modifiedby: defraimp_inspectioncoveragerule_Result[] }>;
    lk_defraimp_inspectioncoveragerule_modifiedonbehalfby: WebExpand<SystemUser_Expand, defraimp_inspectioncoveragerule_Select, defraimp_inspectioncoveragerule_Filter, { lk_defraimp_inspectioncoveragerule_modifiedonbehalfby: defraimp_inspectioncoveragerule_Result[] }>;
    lk_defraimp_itahc_createdby: WebExpand<SystemUser_Expand, defraimp_itahc_Select, defraimp_itahc_Filter, { lk_defraimp_itahc_createdby: defraimp_itahc_Result[] }>;
    lk_defraimp_itahc_createdonbehalfby: WebExpand<SystemUser_Expand, defraimp_itahc_Select, defraimp_itahc_Filter, { lk_defraimp_itahc_createdonbehalfby: defraimp_itahc_Result[] }>;
    lk_defraimp_itahc_modifiedby: WebExpand<SystemUser_Expand, defraimp_itahc_Select, defraimp_itahc_Filter, { lk_defraimp_itahc_modifiedby: defraimp_itahc_Result[] }>;
    lk_defraimp_itahc_modifiedonbehalfby: WebExpand<SystemUser_Expand, defraimp_itahc_Select, defraimp_itahc_Filter, { lk_defraimp_itahc_modifiedonbehalfby: defraimp_itahc_Result[] }>;
    lk_defraimp_placeoforigin_createdby: WebExpand<SystemUser_Expand, defraimp_placeoforigin_Select, defraimp_placeoforigin_Filter, { lk_defraimp_placeoforigin_createdby: defraimp_placeoforigin_Result[] }>;
    lk_defraimp_placeoforigin_createdonbehalfby: WebExpand<SystemUser_Expand, defraimp_placeoforigin_Select, defraimp_placeoforigin_Filter, { lk_defraimp_placeoforigin_createdonbehalfby: defraimp_placeoforigin_Result[] }>;
    lk_defraimp_placeoforigin_modifiedby: WebExpand<SystemUser_Expand, defraimp_placeoforigin_Select, defraimp_placeoforigin_Filter, { lk_defraimp_placeoforigin_modifiedby: defraimp_placeoforigin_Result[] }>;
    lk_defraimp_placeoforigin_modifiedonbehalfby: WebExpand<SystemUser_Expand, defraimp_placeoforigin_Select, defraimp_placeoforigin_Filter, { lk_defraimp_placeoforigin_modifiedonbehalfby: defraimp_placeoforigin_Result[] }>;
    lk_defraimp_sampletest_createdby: WebExpand<SystemUser_Expand, defraimp_sampletest_Select, defraimp_sampletest_Filter, { lk_defraimp_sampletest_createdby: defraimp_sampletest_Result[] }>;
    lk_defraimp_sampletest_createdonbehalfby: WebExpand<SystemUser_Expand, defraimp_sampletest_Select, defraimp_sampletest_Filter, { lk_defraimp_sampletest_createdonbehalfby: defraimp_sampletest_Result[] }>;
    lk_defraimp_sampletest_modifiedby: WebExpand<SystemUser_Expand, defraimp_sampletest_Select, defraimp_sampletest_Filter, { lk_defraimp_sampletest_modifiedby: defraimp_sampletest_Result[] }>;
    lk_defraimp_sampletest_modifiedonbehalfby: WebExpand<SystemUser_Expand, defraimp_sampletest_Select, defraimp_sampletest_Filter, { lk_defraimp_sampletest_modifiedonbehalfby: defraimp_sampletest_Result[] }>;
    lk_post_createdby: WebExpand<SystemUser_Expand, Post_Select, Post_Filter, { lk_post_createdby: Post_Result[] }>;
    lk_post_createdonbehalfby: WebExpand<SystemUser_Expand, Post_Select, Post_Filter, { lk_post_createdonbehalfby: Post_Result[] }>;
    lk_post_modifiedby: WebExpand<SystemUser_Expand, Post_Select, Post_Filter, { lk_post_modifiedby: Post_Result[] }>;
    lk_post_modifiedonbehalfby: WebExpand<SystemUser_Expand, Post_Select, Post_Filter, { lk_post_modifiedonbehalfby: Post_Result[] }>;
    lk_postfollow_createdonbehalfby: WebExpand<SystemUser_Expand, PostFollow_Select, PostFollow_Filter, { lk_postfollow_createdonbehalfby: PostFollow_Result[] }>;
    lk_processsession_canceledby: WebExpand<SystemUser_Expand, ProcessSession_Select, ProcessSession_Filter, { lk_processsession_canceledby: ProcessSession_Result[] }>;
    lk_processsession_completedby: WebExpand<SystemUser_Expand, ProcessSession_Select, ProcessSession_Filter, { lk_processsession_completedby: ProcessSession_Result[] }>;
    lk_processsession_createdby: WebExpand<SystemUser_Expand, ProcessSession_Select, ProcessSession_Filter, { lk_processsession_createdby: ProcessSession_Result[] }>;
    lk_processsession_executedby: WebExpand<SystemUser_Expand, ProcessSession_Select, ProcessSession_Filter, { lk_processsession_executedby: ProcessSession_Result[] }>;
    lk_processsession_modifiedby: WebExpand<SystemUser_Expand, ProcessSession_Select, ProcessSession_Filter, { lk_processsession_modifiedby: ProcessSession_Result[] }>;
    lk_processsession_startedby: WebExpand<SystemUser_Expand, ProcessSession_Select, ProcessSession_Filter, { lk_processsession_startedby: ProcessSession_Result[] }>;
    lk_processsessionbase_createdonbehalfby: WebExpand<SystemUser_Expand, ProcessSession_Select, ProcessSession_Filter, { lk_processsessionbase_createdonbehalfby: ProcessSession_Result[] }>;
    lk_processsessionbase_modifiedonbehalfby: WebExpand<SystemUser_Expand, ProcessSession_Select, ProcessSession_Filter, { lk_processsessionbase_modifiedonbehalfby: ProcessSession_Result[] }>;
    lk_syncerrorbase_createdby: WebExpand<SystemUser_Expand, SyncError_Select, SyncError_Filter, { lk_syncerrorbase_createdby: SyncError_Result[] }>;
    lk_syncerrorbase_createdonbehalfby: WebExpand<SystemUser_Expand, SyncError_Select, SyncError_Filter, { lk_syncerrorbase_createdonbehalfby: SyncError_Result[] }>;
    lk_syncerrorbase_modifiedby: WebExpand<SystemUser_Expand, SyncError_Select, SyncError_Filter, { lk_syncerrorbase_modifiedby: SyncError_Result[] }>;
    lk_syncerrorbase_modifiedonbehalfby: WebExpand<SystemUser_Expand, SyncError_Select, SyncError_Filter, { lk_syncerrorbase_modifiedonbehalfby: SyncError_Result[] }>;
    lk_systemuser_createdonbehalfby: WebExpand<SystemUser_Expand, SystemUser_Select, SystemUser_Filter, { lk_systemuser_createdonbehalfby: SystemUser_Result[] }>;
    lk_systemuser_modifiedonbehalfby: WebExpand<SystemUser_Expand, SystemUser_Select, SystemUser_Filter, { lk_systemuser_modifiedonbehalfby: SystemUser_Result[] }>;
    lk_systemuserbase_createdby: WebExpand<SystemUser_Expand, SystemUser_Select, SystemUser_Filter, { lk_systemuserbase_createdby: SystemUser_Result[] }>;
    lk_systemuserbase_modifiedby: WebExpand<SystemUser_Expand, SystemUser_Select, SystemUser_Filter, { lk_systemuserbase_modifiedby: SystemUser_Result[] }>;
    lk_team_createdonbehalfby: WebExpand<SystemUser_Expand, Team_Select, Team_Filter, { lk_team_createdonbehalfby: Team_Result[] }>;
    lk_team_modifiedonbehalfby: WebExpand<SystemUser_Expand, Team_Select, Team_Filter, { lk_team_modifiedonbehalfby: Team_Result[] }>;
    lk_teambase_administratorid: WebExpand<SystemUser_Expand, Team_Select, Team_Filter, { lk_teambase_administratorid: Team_Result[] }>;
    lk_teambase_createdby: WebExpand<SystemUser_Expand, Team_Select, Team_Filter, { lk_teambase_createdby: Team_Result[] }>;
    lk_teambase_modifiedby: WebExpand<SystemUser_Expand, Team_Select, Team_Filter, { lk_teambase_modifiedby: Team_Result[] }>;
    modifiedby: WebExpand<SystemUser_Expand, SystemUser_Select, SystemUser_Filter, { modifiedby: SystemUser_Result }>;
    modifiedby_connection: WebExpand<SystemUser_Expand, Connection_Select, Connection_Filter, { modifiedby_connection: Connection_Result[] }>;
    modifiedonbehalfby: WebExpand<SystemUser_Expand, SystemUser_Select, SystemUser_Filter, { modifiedonbehalfby: SystemUser_Result }>;
    parentsystemuserid: WebExpand<SystemUser_Expand, SystemUser_Select, SystemUser_Filter, { parentsystemuserid: SystemUser_Result }>;
    system_user_activity_parties: WebExpand<SystemUser_Expand, ActivityParty_Select, ActivityParty_Filter, { system_user_activity_parties: ActivityParty_Result[] }>;
    system_user_workflow: WebExpand<SystemUser_Expand, Workflow_Select, Workflow_Filter, { system_user_workflow: Workflow_Result[] }>;
    systemuser_PostFollows: WebExpand<SystemUser_Expand, PostFollow_Select, PostFollow_Filter, { systemuser_PostFollows: PostFollow_Result[] }>;
    systemuser_connections1: WebExpand<SystemUser_Expand, Connection_Select, Connection_Filter, { systemuser_connections1: Connection_Result[] }>;
    systemuser_connections2: WebExpand<SystemUser_Expand, Connection_Select, Connection_Filter, { systemuser_connections2: Connection_Result[] }>;
    teammembership_association: WebExpand<SystemUser_Expand, Team_Select, Team_Filter, { teammembership_association: Team_Result[] }>;
    user_defra_country: WebExpand<SystemUser_Expand, defra_country_Select, defra_country_Filter, { user_defra_country: defra_country_Result[] }>;
    user_defraexp_commoditytype: WebExpand<SystemUser_Expand, defraexp_commoditytype_Select, defraexp_commoditytype_Filter, { user_defraexp_commoditytype: defraexp_commoditytype_Result[] }>;
    user_defraimp_apharegion: WebExpand<SystemUser_Expand, defraimp_apharegion_Select, defraimp_apharegion_Filter, { user_defraimp_apharegion: defraimp_apharegion_Result[] }>;
    user_defraimp_docom: WebExpand<SystemUser_Expand, defraimp_docom_Select, defraimp_docom_Filter, { user_defraimp_docom: defraimp_docom_Result[] }>;
    user_defraimp_goldbronzecommodity: WebExpand<SystemUser_Expand, defraimp_goldbronzecommodity_Select, defraimp_goldbronzecommodity_Filter, { user_defraimp_goldbronzecommodity: defraimp_goldbronzecommodity_Result[] }>;
    user_defraimp_importapplication: WebExpand<SystemUser_Expand, defraimp_importapplication_Select, defraimp_importapplication_Filter, { user_defraimp_importapplication: defraimp_importapplication_Result[] }>;
    user_defraimp_importinspection: WebExpand<SystemUser_Expand, defraimp_importinspection_Select, defraimp_importinspection_Filter, { user_defraimp_importinspection: defraimp_importinspection_Result[] }>;
    user_defraimp_importnotification: WebExpand<SystemUser_Expand, defraimp_importnotification_Select, defraimp_importnotification_Filter, { user_defraimp_importnotification: defraimp_importnotification_Result[] }>;
    user_defraimp_inspectioncoveragerule: WebExpand<SystemUser_Expand, defraimp_inspectioncoveragerule_Select, defraimp_inspectioncoveragerule_Filter, { user_defraimp_inspectioncoveragerule: defraimp_inspectioncoveragerule_Result[] }>;
    user_defraimp_itahc: WebExpand<SystemUser_Expand, defraimp_itahc_Select, defraimp_itahc_Filter, { user_defraimp_itahc: defraimp_itahc_Result[] }>;
    user_defraimp_placeoforigin: WebExpand<SystemUser_Expand, defraimp_placeoforigin_Select, defraimp_placeoforigin_Filter, { user_defraimp_placeoforigin: defraimp_placeoforigin_Result[] }>;
    user_defraimp_sampletest: WebExpand<SystemUser_Expand, defraimp_sampletest_Select, defraimp_sampletest_Filter, { user_defraimp_sampletest: defraimp_sampletest_Result[] }>;
    user_owner_postfollows: WebExpand<SystemUser_Expand, PostFollow_Select, PostFollow_Filter, { user_owner_postfollows: PostFollow_Result[] }>;
    user_parent_user: WebExpand<SystemUser_Expand, SystemUser_Select, SystemUser_Filter, { user_parent_user: SystemUser_Result[] }>;
    workflow_createdby: WebExpand<SystemUser_Expand, Workflow_Select, Workflow_Filter, { workflow_createdby: Workflow_Result[] }>;
    workflow_createdonbehalfby: WebExpand<SystemUser_Expand, Workflow_Select, Workflow_Filter, { workflow_createdonbehalfby: Workflow_Result[] }>;
    workflow_modifiedby: WebExpand<SystemUser_Expand, Workflow_Select, Workflow_Filter, { workflow_modifiedby: Workflow_Result[] }>;
    workflow_modifiedonbehalfby: WebExpand<SystemUser_Expand, Workflow_Select, Workflow_Filter, { workflow_modifiedonbehalfby: Workflow_Result[] }>;
  }
  interface SystemUser_FormattedResult {
    accessmode_formatted?: string;
    address1_addresstypecode_formatted?: string;
    address1_shippingmethodcode_formatted?: string;
    address2_addresstypecode_formatted?: string;
    address2_shippingmethodcode_formatted?: string;
    businessunitid_formatted?: string;
    calendarid_formatted?: string;
    caltype_formatted?: string;
    createdby_formatted?: string;
    createdon_formatted?: string;
    createdonbehalfby_formatted?: string;
    defaultmailbox_formatted?: string;
    defraexp_office_formatted?: string;
    emailrouteraccessapproval_formatted?: string;
    incomingemaildeliverymethod_formatted?: string;
    invitestatuscode_formatted?: string;
    latestupdatetime_formatted?: string;
    mobileofflineprofileid_formatted?: string;
    modifiedby_formatted?: string;
    modifiedon_formatted?: string;
    modifiedonbehalfby_formatted?: string;
    outgoingemaildeliverymethod_formatted?: string;
    overriddencreatedon_formatted?: string;
    parentsystemuserid_formatted?: string;
    positionid_formatted?: string;
    preferredaddresscode_formatted?: string;
    preferredemailcode_formatted?: string;
    preferredphonecode_formatted?: string;
    queueid_formatted?: string;
    siteid_formatted?: string;
    territoryid_formatted?: string;
    transactioncurrencyid_formatted?: string;
  }
  interface SystemUser_Result extends SystemUser_Base, SystemUser_Relationships {
    "@odata.etag": string;
    businessunitid_guid: string | null;
    calendarid_guid: string | null;
    createdby_guid: string | null;
    createdonbehalfby_guid: string | null;
    defaultmailbox_guid: string | null;
    defraexp_office_guid: string | null;
    mobileofflineprofileid_guid: string | null;
    modifiedby_guid: string | null;
    modifiedonbehalfby_guid: string | null;
    parentsystemuserid_guid: string | null;
    positionid_guid: string | null;
    queueid_guid: string | null;
    siteid_guid: string | null;
    territoryid_guid: string | null;
    transactioncurrencyid_guid: string | null;
  }
  interface SystemUser_RelatedOne {
    createdby: WebMappingRetrieve<WebApi.SystemUser_Select,WebApi.SystemUser_Expand,WebApi.SystemUser_Filter,WebApi.SystemUser_Fixed,WebApi.SystemUser_Result,WebApi.SystemUser_FormattedResult>;
    createdonbehalfby: WebMappingRetrieve<WebApi.SystemUser_Select,WebApi.SystemUser_Expand,WebApi.SystemUser_Filter,WebApi.SystemUser_Fixed,WebApi.SystemUser_Result,WebApi.SystemUser_FormattedResult>;
    modifiedby: WebMappingRetrieve<WebApi.SystemUser_Select,WebApi.SystemUser_Expand,WebApi.SystemUser_Filter,WebApi.SystemUser_Fixed,WebApi.SystemUser_Result,WebApi.SystemUser_FormattedResult>;
    modifiedonbehalfby: WebMappingRetrieve<WebApi.SystemUser_Select,WebApi.SystemUser_Expand,WebApi.SystemUser_Filter,WebApi.SystemUser_Fixed,WebApi.SystemUser_Result,WebApi.SystemUser_FormattedResult>;
    parentsystemuserid: WebMappingRetrieve<WebApi.SystemUser_Select,WebApi.SystemUser_Expand,WebApi.SystemUser_Filter,WebApi.SystemUser_Fixed,WebApi.SystemUser_Result,WebApi.SystemUser_FormattedResult>;
  }
  interface SystemUser_RelatedMany {
    SystemUser_ProcessSessions: WebMappingRetrieve<WebApi.ProcessSession_Select,WebApi.ProcessSession_Expand,WebApi.ProcessSession_Filter,WebApi.ProcessSession_Fixed,WebApi.ProcessSession_Result,WebApi.ProcessSession_FormattedResult>;
    SystemUser_SyncError: WebMappingRetrieve<WebApi.SyncError_Select,WebApi.SyncError_Expand,WebApi.SyncError_Filter,WebApi.SyncError_Fixed,WebApi.SyncError_Result,WebApi.SyncError_FormattedResult>;
    SystemUser_SyncErrors: WebMappingRetrieve<WebApi.SyncError_Select,WebApi.SyncError_Expand,WebApi.SyncError_Filter,WebApi.SyncError_Fixed,WebApi.SyncError_Result,WebApi.SyncError_FormattedResult>;
    createdby_connection: WebMappingRetrieve<WebApi.Connection_Select,WebApi.Connection_Expand,WebApi.Connection_Filter,WebApi.Connection_Fixed,WebApi.Connection_Result,WebApi.Connection_FormattedResult>;
    defraimp_importquery_systemuser_createdby: WebMappingRetrieve<WebApi.defraimp_importquery_Select,WebApi.defraimp_importquery_Expand,WebApi.defraimp_importquery_Filter,WebApi.defraimp_importquery_Fixed,WebApi.defraimp_importquery_Result,WebApi.defraimp_importquery_FormattedResult>;
    defraimp_importquery_systemuser_createdonbehalfby: WebMappingRetrieve<WebApi.defraimp_importquery_Select,WebApi.defraimp_importquery_Expand,WebApi.defraimp_importquery_Filter,WebApi.defraimp_importquery_Fixed,WebApi.defraimp_importquery_Result,WebApi.defraimp_importquery_FormattedResult>;
    defraimp_importquery_systemuser_modifiedby: WebMappingRetrieve<WebApi.defraimp_importquery_Select,WebApi.defraimp_importquery_Expand,WebApi.defraimp_importquery_Filter,WebApi.defraimp_importquery_Fixed,WebApi.defraimp_importquery_Result,WebApi.defraimp_importquery_FormattedResult>;
    defraimp_importquery_systemuser_modifiedonbehalfby: WebMappingRetrieve<WebApi.defraimp_importquery_Select,WebApi.defraimp_importquery_Expand,WebApi.defraimp_importquery_Filter,WebApi.defraimp_importquery_Fixed,WebApi.defraimp_importquery_Result,WebApi.defraimp_importquery_FormattedResult>;
    defraimp_importquery_systemuser_owninguser: WebMappingRetrieve<WebApi.defraimp_importquery_Select,WebApi.defraimp_importquery_Expand,WebApi.defraimp_importquery_Filter,WebApi.defraimp_importquery_Fixed,WebApi.defraimp_importquery_Result,WebApi.defraimp_importquery_FormattedResult>;
    defraimp_systemuser_defraimp_importinspection_IV17ReviewApprovedBy: WebMappingRetrieve<WebApi.defraimp_importinspection_Select,WebApi.defraimp_importinspection_Expand,WebApi.defraimp_importinspection_Filter,WebApi.defraimp_importinspection_Fixed,WebApi.defraimp_importinspection_Result,WebApi.defraimp_importinspection_FormattedResult>;
    lk_PostFollow_createdby: WebMappingRetrieve<WebApi.PostFollow_Select,WebApi.PostFollow_Expand,WebApi.PostFollow_Filter,WebApi.PostFollow_Fixed,WebApi.PostFollow_Result,WebApi.PostFollow_FormattedResult>;
    lk_connectionbase_createdonbehalfby: WebMappingRetrieve<WebApi.Connection_Select,WebApi.Connection_Expand,WebApi.Connection_Filter,WebApi.Connection_Fixed,WebApi.Connection_Result,WebApi.Connection_FormattedResult>;
    lk_connectionbase_modifiedonbehalfby: WebMappingRetrieve<WebApi.Connection_Select,WebApi.Connection_Expand,WebApi.Connection_Filter,WebApi.Connection_Fixed,WebApi.Connection_Result,WebApi.Connection_FormattedResult>;
    lk_defra_country_createdby: WebMappingRetrieve<WebApi.defra_country_Select,WebApi.defra_country_Expand,WebApi.defra_country_Filter,WebApi.defra_country_Fixed,WebApi.defra_country_Result,WebApi.defra_country_FormattedResult>;
    lk_defra_country_createdonbehalfby: WebMappingRetrieve<WebApi.defra_country_Select,WebApi.defra_country_Expand,WebApi.defra_country_Filter,WebApi.defra_country_Fixed,WebApi.defra_country_Result,WebApi.defra_country_FormattedResult>;
    lk_defra_country_modifiedby: WebMappingRetrieve<WebApi.defra_country_Select,WebApi.defra_country_Expand,WebApi.defra_country_Filter,WebApi.defra_country_Fixed,WebApi.defra_country_Result,WebApi.defra_country_FormattedResult>;
    lk_defra_country_modifiedonbehalfby: WebMappingRetrieve<WebApi.defra_country_Select,WebApi.defra_country_Expand,WebApi.defra_country_Filter,WebApi.defra_country_Fixed,WebApi.defra_country_Result,WebApi.defra_country_FormattedResult>;
    lk_defraexp_commoditytype_createdby: WebMappingRetrieve<WebApi.defraexp_commoditytype_Select,WebApi.defraexp_commoditytype_Expand,WebApi.defraexp_commoditytype_Filter,WebApi.defraexp_commoditytype_Fixed,WebApi.defraexp_commoditytype_Result,WebApi.defraexp_commoditytype_FormattedResult>;
    lk_defraexp_commoditytype_createdonbehalfby: WebMappingRetrieve<WebApi.defraexp_commoditytype_Select,WebApi.defraexp_commoditytype_Expand,WebApi.defraexp_commoditytype_Filter,WebApi.defraexp_commoditytype_Fixed,WebApi.defraexp_commoditytype_Result,WebApi.defraexp_commoditytype_FormattedResult>;
    lk_defraexp_commoditytype_modifiedby: WebMappingRetrieve<WebApi.defraexp_commoditytype_Select,WebApi.defraexp_commoditytype_Expand,WebApi.defraexp_commoditytype_Filter,WebApi.defraexp_commoditytype_Fixed,WebApi.defraexp_commoditytype_Result,WebApi.defraexp_commoditytype_FormattedResult>;
    lk_defraexp_commoditytype_modifiedonbehalfby: WebMappingRetrieve<WebApi.defraexp_commoditytype_Select,WebApi.defraexp_commoditytype_Expand,WebApi.defraexp_commoditytype_Filter,WebApi.defraexp_commoditytype_Fixed,WebApi.defraexp_commoditytype_Result,WebApi.defraexp_commoditytype_FormattedResult>;
    lk_defraimp_apharegion_createdby: WebMappingRetrieve<WebApi.defraimp_apharegion_Select,WebApi.defraimp_apharegion_Expand,WebApi.defraimp_apharegion_Filter,WebApi.defraimp_apharegion_Fixed,WebApi.defraimp_apharegion_Result,WebApi.defraimp_apharegion_FormattedResult>;
    lk_defraimp_apharegion_createdonbehalfby: WebMappingRetrieve<WebApi.defraimp_apharegion_Select,WebApi.defraimp_apharegion_Expand,WebApi.defraimp_apharegion_Filter,WebApi.defraimp_apharegion_Fixed,WebApi.defraimp_apharegion_Result,WebApi.defraimp_apharegion_FormattedResult>;
    lk_defraimp_apharegion_modifiedby: WebMappingRetrieve<WebApi.defraimp_apharegion_Select,WebApi.defraimp_apharegion_Expand,WebApi.defraimp_apharegion_Filter,WebApi.defraimp_apharegion_Fixed,WebApi.defraimp_apharegion_Result,WebApi.defraimp_apharegion_FormattedResult>;
    lk_defraimp_apharegion_modifiedonbehalfby: WebMappingRetrieve<WebApi.defraimp_apharegion_Select,WebApi.defraimp_apharegion_Expand,WebApi.defraimp_apharegion_Filter,WebApi.defraimp_apharegion_Fixed,WebApi.defraimp_apharegion_Result,WebApi.defraimp_apharegion_FormattedResult>;
    lk_defraimp_autonumber_createdby: WebMappingRetrieve<WebApi.defraimp_autonumber_Select,WebApi.defraimp_autonumber_Expand,WebApi.defraimp_autonumber_Filter,WebApi.defraimp_autonumber_Fixed,WebApi.defraimp_autonumber_Result,WebApi.defraimp_autonumber_FormattedResult>;
    lk_defraimp_autonumber_createdonbehalfby: WebMappingRetrieve<WebApi.defraimp_autonumber_Select,WebApi.defraimp_autonumber_Expand,WebApi.defraimp_autonumber_Filter,WebApi.defraimp_autonumber_Fixed,WebApi.defraimp_autonumber_Result,WebApi.defraimp_autonumber_FormattedResult>;
    lk_defraimp_autonumber_modifiedby: WebMappingRetrieve<WebApi.defraimp_autonumber_Select,WebApi.defraimp_autonumber_Expand,WebApi.defraimp_autonumber_Filter,WebApi.defraimp_autonumber_Fixed,WebApi.defraimp_autonumber_Result,WebApi.defraimp_autonumber_FormattedResult>;
    lk_defraimp_autonumber_modifiedonbehalfby: WebMappingRetrieve<WebApi.defraimp_autonumber_Select,WebApi.defraimp_autonumber_Expand,WebApi.defraimp_autonumber_Filter,WebApi.defraimp_autonumber_Fixed,WebApi.defraimp_autonumber_Result,WebApi.defraimp_autonumber_FormattedResult>;
    lk_defraimp_docom_createdby: WebMappingRetrieve<WebApi.defraimp_docom_Select,WebApi.defraimp_docom_Expand,WebApi.defraimp_docom_Filter,WebApi.defraimp_docom_Fixed,WebApi.defraimp_docom_Result,WebApi.defraimp_docom_FormattedResult>;
    lk_defraimp_docom_createdonbehalfby: WebMappingRetrieve<WebApi.defraimp_docom_Select,WebApi.defraimp_docom_Expand,WebApi.defraimp_docom_Filter,WebApi.defraimp_docom_Fixed,WebApi.defraimp_docom_Result,WebApi.defraimp_docom_FormattedResult>;
    lk_defraimp_docom_modifiedby: WebMappingRetrieve<WebApi.defraimp_docom_Select,WebApi.defraimp_docom_Expand,WebApi.defraimp_docom_Filter,WebApi.defraimp_docom_Fixed,WebApi.defraimp_docom_Result,WebApi.defraimp_docom_FormattedResult>;
    lk_defraimp_docom_modifiedonbehalfby: WebMappingRetrieve<WebApi.defraimp_docom_Select,WebApi.defraimp_docom_Expand,WebApi.defraimp_docom_Filter,WebApi.defraimp_docom_Fixed,WebApi.defraimp_docom_Result,WebApi.defraimp_docom_FormattedResult>;
    lk_defraimp_goldbronzecommodity_createdby: WebMappingRetrieve<WebApi.defraimp_goldbronzecommodity_Select,WebApi.defraimp_goldbronzecommodity_Expand,WebApi.defraimp_goldbronzecommodity_Filter,WebApi.defraimp_goldbronzecommodity_Fixed,WebApi.defraimp_goldbronzecommodity_Result,WebApi.defraimp_goldbronzecommodity_FormattedResult>;
    lk_defraimp_goldbronzecommodity_createdonbehalfby: WebMappingRetrieve<WebApi.defraimp_goldbronzecommodity_Select,WebApi.defraimp_goldbronzecommodity_Expand,WebApi.defraimp_goldbronzecommodity_Filter,WebApi.defraimp_goldbronzecommodity_Fixed,WebApi.defraimp_goldbronzecommodity_Result,WebApi.defraimp_goldbronzecommodity_FormattedResult>;
    lk_defraimp_goldbronzecommodity_modifiedby: WebMappingRetrieve<WebApi.defraimp_goldbronzecommodity_Select,WebApi.defraimp_goldbronzecommodity_Expand,WebApi.defraimp_goldbronzecommodity_Filter,WebApi.defraimp_goldbronzecommodity_Fixed,WebApi.defraimp_goldbronzecommodity_Result,WebApi.defraimp_goldbronzecommodity_FormattedResult>;
    lk_defraimp_goldbronzecommodity_modifiedonbehalfby: WebMappingRetrieve<WebApi.defraimp_goldbronzecommodity_Select,WebApi.defraimp_goldbronzecommodity_Expand,WebApi.defraimp_goldbronzecommodity_Filter,WebApi.defraimp_goldbronzecommodity_Fixed,WebApi.defraimp_goldbronzecommodity_Result,WebApi.defraimp_goldbronzecommodity_FormattedResult>;
    lk_defraimp_importapplication_createdby: WebMappingRetrieve<WebApi.defraimp_importapplication_Select,WebApi.defraimp_importapplication_Expand,WebApi.defraimp_importapplication_Filter,WebApi.defraimp_importapplication_Fixed,WebApi.defraimp_importapplication_Result,WebApi.defraimp_importapplication_FormattedResult>;
    lk_defraimp_importapplication_createdonbehalfby: WebMappingRetrieve<WebApi.defraimp_importapplication_Select,WebApi.defraimp_importapplication_Expand,WebApi.defraimp_importapplication_Filter,WebApi.defraimp_importapplication_Fixed,WebApi.defraimp_importapplication_Result,WebApi.defraimp_importapplication_FormattedResult>;
    lk_defraimp_importapplication_modifiedby: WebMappingRetrieve<WebApi.defraimp_importapplication_Select,WebApi.defraimp_importapplication_Expand,WebApi.defraimp_importapplication_Filter,WebApi.defraimp_importapplication_Fixed,WebApi.defraimp_importapplication_Result,WebApi.defraimp_importapplication_FormattedResult>;
    lk_defraimp_importapplication_modifiedonbehalfby: WebMappingRetrieve<WebApi.defraimp_importapplication_Select,WebApi.defraimp_importapplication_Expand,WebApi.defraimp_importapplication_Filter,WebApi.defraimp_importapplication_Fixed,WebApi.defraimp_importapplication_Result,WebApi.defraimp_importapplication_FormattedResult>;
    lk_defraimp_importcountrycommodityrisklevel_createdby: WebMappingRetrieve<WebApi.defraimp_importcountrycommodityrisklevel_Select,WebApi.defraimp_importcountrycommodityrisklevel_Expand,WebApi.defraimp_importcountrycommodityrisklevel_Filter,WebApi.defraimp_importcountrycommodityrisklevel_Fixed,WebApi.defraimp_importcountrycommodityrisklevel_Result,WebApi.defraimp_importcountrycommodityrisklevel_FormattedResult>;
    lk_defraimp_importcountrycommodityrisklevel_createdonbehalfby: WebMappingRetrieve<WebApi.defraimp_importcountrycommodityrisklevel_Select,WebApi.defraimp_importcountrycommodityrisklevel_Expand,WebApi.defraimp_importcountrycommodityrisklevel_Filter,WebApi.defraimp_importcountrycommodityrisklevel_Fixed,WebApi.defraimp_importcountrycommodityrisklevel_Result,WebApi.defraimp_importcountrycommodityrisklevel_FormattedResult>;
    lk_defraimp_importcountrycommodityrisklevel_modifiedby: WebMappingRetrieve<WebApi.defraimp_importcountrycommodityrisklevel_Select,WebApi.defraimp_importcountrycommodityrisklevel_Expand,WebApi.defraimp_importcountrycommodityrisklevel_Filter,WebApi.defraimp_importcountrycommodityrisklevel_Fixed,WebApi.defraimp_importcountrycommodityrisklevel_Result,WebApi.defraimp_importcountrycommodityrisklevel_FormattedResult>;
    lk_defraimp_importcountrycommodityrisklevel_modifiedonbehalfby: WebMappingRetrieve<WebApi.defraimp_importcountrycommodityrisklevel_Select,WebApi.defraimp_importcountrycommodityrisklevel_Expand,WebApi.defraimp_importcountrycommodityrisklevel_Filter,WebApi.defraimp_importcountrycommodityrisklevel_Fixed,WebApi.defraimp_importcountrycommodityrisklevel_Result,WebApi.defraimp_importcountrycommodityrisklevel_FormattedResult>;
    lk_defraimp_importinspection_createdby: WebMappingRetrieve<WebApi.defraimp_importinspection_Select,WebApi.defraimp_importinspection_Expand,WebApi.defraimp_importinspection_Filter,WebApi.defraimp_importinspection_Fixed,WebApi.defraimp_importinspection_Result,WebApi.defraimp_importinspection_FormattedResult>;
    lk_defraimp_importinspection_createdonbehalfby: WebMappingRetrieve<WebApi.defraimp_importinspection_Select,WebApi.defraimp_importinspection_Expand,WebApi.defraimp_importinspection_Filter,WebApi.defraimp_importinspection_Fixed,WebApi.defraimp_importinspection_Result,WebApi.defraimp_importinspection_FormattedResult>;
    lk_defraimp_importinspection_modifiedby: WebMappingRetrieve<WebApi.defraimp_importinspection_Select,WebApi.defraimp_importinspection_Expand,WebApi.defraimp_importinspection_Filter,WebApi.defraimp_importinspection_Fixed,WebApi.defraimp_importinspection_Result,WebApi.defraimp_importinspection_FormattedResult>;
    lk_defraimp_importinspection_modifiedonbehalfby: WebMappingRetrieve<WebApi.defraimp_importinspection_Select,WebApi.defraimp_importinspection_Expand,WebApi.defraimp_importinspection_Filter,WebApi.defraimp_importinspection_Fixed,WebApi.defraimp_importinspection_Result,WebApi.defraimp_importinspection_FormattedResult>;
    lk_defraimp_importnotification_createdby: WebMappingRetrieve<WebApi.defraimp_importnotification_Select,WebApi.defraimp_importnotification_Expand,WebApi.defraimp_importnotification_Filter,WebApi.defraimp_importnotification_Fixed,WebApi.defraimp_importnotification_Result,WebApi.defraimp_importnotification_FormattedResult>;
    lk_defraimp_importnotification_createdonbehalfby: WebMappingRetrieve<WebApi.defraimp_importnotification_Select,WebApi.defraimp_importnotification_Expand,WebApi.defraimp_importnotification_Filter,WebApi.defraimp_importnotification_Fixed,WebApi.defraimp_importnotification_Result,WebApi.defraimp_importnotification_FormattedResult>;
    lk_defraimp_importnotification_modifiedby: WebMappingRetrieve<WebApi.defraimp_importnotification_Select,WebApi.defraimp_importnotification_Expand,WebApi.defraimp_importnotification_Filter,WebApi.defraimp_importnotification_Fixed,WebApi.defraimp_importnotification_Result,WebApi.defraimp_importnotification_FormattedResult>;
    lk_defraimp_importnotification_modifiedonbehalfby: WebMappingRetrieve<WebApi.defraimp_importnotification_Select,WebApi.defraimp_importnotification_Expand,WebApi.defraimp_importnotification_Filter,WebApi.defraimp_importnotification_Fixed,WebApi.defraimp_importnotification_Result,WebApi.defraimp_importnotification_FormattedResult>;
    lk_defraimp_importrisklevel_createdby: WebMappingRetrieve<WebApi.defraimp_importrisklevel_Select,WebApi.defraimp_importrisklevel_Expand,WebApi.defraimp_importrisklevel_Filter,WebApi.defraimp_importrisklevel_Fixed,WebApi.defraimp_importrisklevel_Result,WebApi.defraimp_importrisklevel_FormattedResult>;
    lk_defraimp_importrisklevel_createdonbehalfby: WebMappingRetrieve<WebApi.defraimp_importrisklevel_Select,WebApi.defraimp_importrisklevel_Expand,WebApi.defraimp_importrisklevel_Filter,WebApi.defraimp_importrisklevel_Fixed,WebApi.defraimp_importrisklevel_Result,WebApi.defraimp_importrisklevel_FormattedResult>;
    lk_defraimp_importrisklevel_modifiedby: WebMappingRetrieve<WebApi.defraimp_importrisklevel_Select,WebApi.defraimp_importrisklevel_Expand,WebApi.defraimp_importrisklevel_Filter,WebApi.defraimp_importrisklevel_Fixed,WebApi.defraimp_importrisklevel_Result,WebApi.defraimp_importrisklevel_FormattedResult>;
    lk_defraimp_importrisklevel_modifiedonbehalfby: WebMappingRetrieve<WebApi.defraimp_importrisklevel_Select,WebApi.defraimp_importrisklevel_Expand,WebApi.defraimp_importrisklevel_Filter,WebApi.defraimp_importrisklevel_Fixed,WebApi.defraimp_importrisklevel_Result,WebApi.defraimp_importrisklevel_FormattedResult>;
    lk_defraimp_inspectioncoveragerule_createdby: WebMappingRetrieve<WebApi.defraimp_inspectioncoveragerule_Select,WebApi.defraimp_inspectioncoveragerule_Expand,WebApi.defraimp_inspectioncoveragerule_Filter,WebApi.defraimp_inspectioncoveragerule_Fixed,WebApi.defraimp_inspectioncoveragerule_Result,WebApi.defraimp_inspectioncoveragerule_FormattedResult>;
    lk_defraimp_inspectioncoveragerule_createdonbehalfby: WebMappingRetrieve<WebApi.defraimp_inspectioncoveragerule_Select,WebApi.defraimp_inspectioncoveragerule_Expand,WebApi.defraimp_inspectioncoveragerule_Filter,WebApi.defraimp_inspectioncoveragerule_Fixed,WebApi.defraimp_inspectioncoveragerule_Result,WebApi.defraimp_inspectioncoveragerule_FormattedResult>;
    lk_defraimp_inspectioncoveragerule_modifiedby: WebMappingRetrieve<WebApi.defraimp_inspectioncoveragerule_Select,WebApi.defraimp_inspectioncoveragerule_Expand,WebApi.defraimp_inspectioncoveragerule_Filter,WebApi.defraimp_inspectioncoveragerule_Fixed,WebApi.defraimp_inspectioncoveragerule_Result,WebApi.defraimp_inspectioncoveragerule_FormattedResult>;
    lk_defraimp_inspectioncoveragerule_modifiedonbehalfby: WebMappingRetrieve<WebApi.defraimp_inspectioncoveragerule_Select,WebApi.defraimp_inspectioncoveragerule_Expand,WebApi.defraimp_inspectioncoveragerule_Filter,WebApi.defraimp_inspectioncoveragerule_Fixed,WebApi.defraimp_inspectioncoveragerule_Result,WebApi.defraimp_inspectioncoveragerule_FormattedResult>;
    lk_defraimp_itahc_createdby: WebMappingRetrieve<WebApi.defraimp_itahc_Select,WebApi.defraimp_itahc_Expand,WebApi.defraimp_itahc_Filter,WebApi.defraimp_itahc_Fixed,WebApi.defraimp_itahc_Result,WebApi.defraimp_itahc_FormattedResult>;
    lk_defraimp_itahc_createdonbehalfby: WebMappingRetrieve<WebApi.defraimp_itahc_Select,WebApi.defraimp_itahc_Expand,WebApi.defraimp_itahc_Filter,WebApi.defraimp_itahc_Fixed,WebApi.defraimp_itahc_Result,WebApi.defraimp_itahc_FormattedResult>;
    lk_defraimp_itahc_modifiedby: WebMappingRetrieve<WebApi.defraimp_itahc_Select,WebApi.defraimp_itahc_Expand,WebApi.defraimp_itahc_Filter,WebApi.defraimp_itahc_Fixed,WebApi.defraimp_itahc_Result,WebApi.defraimp_itahc_FormattedResult>;
    lk_defraimp_itahc_modifiedonbehalfby: WebMappingRetrieve<WebApi.defraimp_itahc_Select,WebApi.defraimp_itahc_Expand,WebApi.defraimp_itahc_Filter,WebApi.defraimp_itahc_Fixed,WebApi.defraimp_itahc_Result,WebApi.defraimp_itahc_FormattedResult>;
    lk_defraimp_placeoforigin_createdby: WebMappingRetrieve<WebApi.defraimp_placeoforigin_Select,WebApi.defraimp_placeoforigin_Expand,WebApi.defraimp_placeoforigin_Filter,WebApi.defraimp_placeoforigin_Fixed,WebApi.defraimp_placeoforigin_Result,WebApi.defraimp_placeoforigin_FormattedResult>;
    lk_defraimp_placeoforigin_createdonbehalfby: WebMappingRetrieve<WebApi.defraimp_placeoforigin_Select,WebApi.defraimp_placeoforigin_Expand,WebApi.defraimp_placeoforigin_Filter,WebApi.defraimp_placeoforigin_Fixed,WebApi.defraimp_placeoforigin_Result,WebApi.defraimp_placeoforigin_FormattedResult>;
    lk_defraimp_placeoforigin_modifiedby: WebMappingRetrieve<WebApi.defraimp_placeoforigin_Select,WebApi.defraimp_placeoforigin_Expand,WebApi.defraimp_placeoforigin_Filter,WebApi.defraimp_placeoforigin_Fixed,WebApi.defraimp_placeoforigin_Result,WebApi.defraimp_placeoforigin_FormattedResult>;
    lk_defraimp_placeoforigin_modifiedonbehalfby: WebMappingRetrieve<WebApi.defraimp_placeoforigin_Select,WebApi.defraimp_placeoforigin_Expand,WebApi.defraimp_placeoforigin_Filter,WebApi.defraimp_placeoforigin_Fixed,WebApi.defraimp_placeoforigin_Result,WebApi.defraimp_placeoforigin_FormattedResult>;
    lk_defraimp_sampletest_createdby: WebMappingRetrieve<WebApi.defraimp_sampletest_Select,WebApi.defraimp_sampletest_Expand,WebApi.defraimp_sampletest_Filter,WebApi.defraimp_sampletest_Fixed,WebApi.defraimp_sampletest_Result,WebApi.defraimp_sampletest_FormattedResult>;
    lk_defraimp_sampletest_createdonbehalfby: WebMappingRetrieve<WebApi.defraimp_sampletest_Select,WebApi.defraimp_sampletest_Expand,WebApi.defraimp_sampletest_Filter,WebApi.defraimp_sampletest_Fixed,WebApi.defraimp_sampletest_Result,WebApi.defraimp_sampletest_FormattedResult>;
    lk_defraimp_sampletest_modifiedby: WebMappingRetrieve<WebApi.defraimp_sampletest_Select,WebApi.defraimp_sampletest_Expand,WebApi.defraimp_sampletest_Filter,WebApi.defraimp_sampletest_Fixed,WebApi.defraimp_sampletest_Result,WebApi.defraimp_sampletest_FormattedResult>;
    lk_defraimp_sampletest_modifiedonbehalfby: WebMappingRetrieve<WebApi.defraimp_sampletest_Select,WebApi.defraimp_sampletest_Expand,WebApi.defraimp_sampletest_Filter,WebApi.defraimp_sampletest_Fixed,WebApi.defraimp_sampletest_Result,WebApi.defraimp_sampletest_FormattedResult>;
    lk_post_createdby: WebMappingRetrieve<WebApi.Post_Select,WebApi.Post_Expand,WebApi.Post_Filter,WebApi.Post_Fixed,WebApi.Post_Result,WebApi.Post_FormattedResult>;
    lk_post_createdonbehalfby: WebMappingRetrieve<WebApi.Post_Select,WebApi.Post_Expand,WebApi.Post_Filter,WebApi.Post_Fixed,WebApi.Post_Result,WebApi.Post_FormattedResult>;
    lk_post_modifiedby: WebMappingRetrieve<WebApi.Post_Select,WebApi.Post_Expand,WebApi.Post_Filter,WebApi.Post_Fixed,WebApi.Post_Result,WebApi.Post_FormattedResult>;
    lk_post_modifiedonbehalfby: WebMappingRetrieve<WebApi.Post_Select,WebApi.Post_Expand,WebApi.Post_Filter,WebApi.Post_Fixed,WebApi.Post_Result,WebApi.Post_FormattedResult>;
    lk_postfollow_createdonbehalfby: WebMappingRetrieve<WebApi.PostFollow_Select,WebApi.PostFollow_Expand,WebApi.PostFollow_Filter,WebApi.PostFollow_Fixed,WebApi.PostFollow_Result,WebApi.PostFollow_FormattedResult>;
    lk_processsession_canceledby: WebMappingRetrieve<WebApi.ProcessSession_Select,WebApi.ProcessSession_Expand,WebApi.ProcessSession_Filter,WebApi.ProcessSession_Fixed,WebApi.ProcessSession_Result,WebApi.ProcessSession_FormattedResult>;
    lk_processsession_completedby: WebMappingRetrieve<WebApi.ProcessSession_Select,WebApi.ProcessSession_Expand,WebApi.ProcessSession_Filter,WebApi.ProcessSession_Fixed,WebApi.ProcessSession_Result,WebApi.ProcessSession_FormattedResult>;
    lk_processsession_createdby: WebMappingRetrieve<WebApi.ProcessSession_Select,WebApi.ProcessSession_Expand,WebApi.ProcessSession_Filter,WebApi.ProcessSession_Fixed,WebApi.ProcessSession_Result,WebApi.ProcessSession_FormattedResult>;
    lk_processsession_executedby: WebMappingRetrieve<WebApi.ProcessSession_Select,WebApi.ProcessSession_Expand,WebApi.ProcessSession_Filter,WebApi.ProcessSession_Fixed,WebApi.ProcessSession_Result,WebApi.ProcessSession_FormattedResult>;
    lk_processsession_modifiedby: WebMappingRetrieve<WebApi.ProcessSession_Select,WebApi.ProcessSession_Expand,WebApi.ProcessSession_Filter,WebApi.ProcessSession_Fixed,WebApi.ProcessSession_Result,WebApi.ProcessSession_FormattedResult>;
    lk_processsession_startedby: WebMappingRetrieve<WebApi.ProcessSession_Select,WebApi.ProcessSession_Expand,WebApi.ProcessSession_Filter,WebApi.ProcessSession_Fixed,WebApi.ProcessSession_Result,WebApi.ProcessSession_FormattedResult>;
    lk_processsessionbase_createdonbehalfby: WebMappingRetrieve<WebApi.ProcessSession_Select,WebApi.ProcessSession_Expand,WebApi.ProcessSession_Filter,WebApi.ProcessSession_Fixed,WebApi.ProcessSession_Result,WebApi.ProcessSession_FormattedResult>;
    lk_processsessionbase_modifiedonbehalfby: WebMappingRetrieve<WebApi.ProcessSession_Select,WebApi.ProcessSession_Expand,WebApi.ProcessSession_Filter,WebApi.ProcessSession_Fixed,WebApi.ProcessSession_Result,WebApi.ProcessSession_FormattedResult>;
    lk_syncerrorbase_createdby: WebMappingRetrieve<WebApi.SyncError_Select,WebApi.SyncError_Expand,WebApi.SyncError_Filter,WebApi.SyncError_Fixed,WebApi.SyncError_Result,WebApi.SyncError_FormattedResult>;
    lk_syncerrorbase_createdonbehalfby: WebMappingRetrieve<WebApi.SyncError_Select,WebApi.SyncError_Expand,WebApi.SyncError_Filter,WebApi.SyncError_Fixed,WebApi.SyncError_Result,WebApi.SyncError_FormattedResult>;
    lk_syncerrorbase_modifiedby: WebMappingRetrieve<WebApi.SyncError_Select,WebApi.SyncError_Expand,WebApi.SyncError_Filter,WebApi.SyncError_Fixed,WebApi.SyncError_Result,WebApi.SyncError_FormattedResult>;
    lk_syncerrorbase_modifiedonbehalfby: WebMappingRetrieve<WebApi.SyncError_Select,WebApi.SyncError_Expand,WebApi.SyncError_Filter,WebApi.SyncError_Fixed,WebApi.SyncError_Result,WebApi.SyncError_FormattedResult>;
    lk_systemuser_createdonbehalfby: WebMappingRetrieve<WebApi.SystemUser_Select,WebApi.SystemUser_Expand,WebApi.SystemUser_Filter,WebApi.SystemUser_Fixed,WebApi.SystemUser_Result,WebApi.SystemUser_FormattedResult>;
    lk_systemuser_modifiedonbehalfby: WebMappingRetrieve<WebApi.SystemUser_Select,WebApi.SystemUser_Expand,WebApi.SystemUser_Filter,WebApi.SystemUser_Fixed,WebApi.SystemUser_Result,WebApi.SystemUser_FormattedResult>;
    lk_systemuserbase_createdby: WebMappingRetrieve<WebApi.SystemUser_Select,WebApi.SystemUser_Expand,WebApi.SystemUser_Filter,WebApi.SystemUser_Fixed,WebApi.SystemUser_Result,WebApi.SystemUser_FormattedResult>;
    lk_systemuserbase_modifiedby: WebMappingRetrieve<WebApi.SystemUser_Select,WebApi.SystemUser_Expand,WebApi.SystemUser_Filter,WebApi.SystemUser_Fixed,WebApi.SystemUser_Result,WebApi.SystemUser_FormattedResult>;
    lk_team_createdonbehalfby: WebMappingRetrieve<WebApi.Team_Select,WebApi.Team_Expand,WebApi.Team_Filter,WebApi.Team_Fixed,WebApi.Team_Result,WebApi.Team_FormattedResult>;
    lk_team_modifiedonbehalfby: WebMappingRetrieve<WebApi.Team_Select,WebApi.Team_Expand,WebApi.Team_Filter,WebApi.Team_Fixed,WebApi.Team_Result,WebApi.Team_FormattedResult>;
    lk_teambase_administratorid: WebMappingRetrieve<WebApi.Team_Select,WebApi.Team_Expand,WebApi.Team_Filter,WebApi.Team_Fixed,WebApi.Team_Result,WebApi.Team_FormattedResult>;
    lk_teambase_createdby: WebMappingRetrieve<WebApi.Team_Select,WebApi.Team_Expand,WebApi.Team_Filter,WebApi.Team_Fixed,WebApi.Team_Result,WebApi.Team_FormattedResult>;
    lk_teambase_modifiedby: WebMappingRetrieve<WebApi.Team_Select,WebApi.Team_Expand,WebApi.Team_Filter,WebApi.Team_Fixed,WebApi.Team_Result,WebApi.Team_FormattedResult>;
    modifiedby_connection: WebMappingRetrieve<WebApi.Connection_Select,WebApi.Connection_Expand,WebApi.Connection_Filter,WebApi.Connection_Fixed,WebApi.Connection_Result,WebApi.Connection_FormattedResult>;
    system_user_activity_parties: WebMappingRetrieve<WebApi.ActivityParty_Select,WebApi.ActivityParty_Expand,WebApi.ActivityParty_Filter,WebApi.ActivityParty_Fixed,WebApi.ActivityParty_Result,WebApi.ActivityParty_FormattedResult>;
    system_user_workflow: WebMappingRetrieve<WebApi.Workflow_Select,WebApi.Workflow_Expand,WebApi.Workflow_Filter,WebApi.Workflow_Fixed,WebApi.Workflow_Result,WebApi.Workflow_FormattedResult>;
    systemuser_PostFollows: WebMappingRetrieve<WebApi.PostFollow_Select,WebApi.PostFollow_Expand,WebApi.PostFollow_Filter,WebApi.PostFollow_Fixed,WebApi.PostFollow_Result,WebApi.PostFollow_FormattedResult>;
    systemuser_connections1: WebMappingRetrieve<WebApi.Connection_Select,WebApi.Connection_Expand,WebApi.Connection_Filter,WebApi.Connection_Fixed,WebApi.Connection_Result,WebApi.Connection_FormattedResult>;
    systemuser_connections2: WebMappingRetrieve<WebApi.Connection_Select,WebApi.Connection_Expand,WebApi.Connection_Filter,WebApi.Connection_Fixed,WebApi.Connection_Result,WebApi.Connection_FormattedResult>;
    teammembership_association: WebMappingRetrieve<WebApi.Team_Select,WebApi.Team_Expand,WebApi.Team_Filter,WebApi.Team_Fixed,WebApi.Team_Result,WebApi.Team_FormattedResult>;
    user_defra_country: WebMappingRetrieve<WebApi.defra_country_Select,WebApi.defra_country_Expand,WebApi.defra_country_Filter,WebApi.defra_country_Fixed,WebApi.defra_country_Result,WebApi.defra_country_FormattedResult>;
    user_defraexp_commoditytype: WebMappingRetrieve<WebApi.defraexp_commoditytype_Select,WebApi.defraexp_commoditytype_Expand,WebApi.defraexp_commoditytype_Filter,WebApi.defraexp_commoditytype_Fixed,WebApi.defraexp_commoditytype_Result,WebApi.defraexp_commoditytype_FormattedResult>;
    user_defraimp_apharegion: WebMappingRetrieve<WebApi.defraimp_apharegion_Select,WebApi.defraimp_apharegion_Expand,WebApi.defraimp_apharegion_Filter,WebApi.defraimp_apharegion_Fixed,WebApi.defraimp_apharegion_Result,WebApi.defraimp_apharegion_FormattedResult>;
    user_defraimp_docom: WebMappingRetrieve<WebApi.defraimp_docom_Select,WebApi.defraimp_docom_Expand,WebApi.defraimp_docom_Filter,WebApi.defraimp_docom_Fixed,WebApi.defraimp_docom_Result,WebApi.defraimp_docom_FormattedResult>;
    user_defraimp_goldbronzecommodity: WebMappingRetrieve<WebApi.defraimp_goldbronzecommodity_Select,WebApi.defraimp_goldbronzecommodity_Expand,WebApi.defraimp_goldbronzecommodity_Filter,WebApi.defraimp_goldbronzecommodity_Fixed,WebApi.defraimp_goldbronzecommodity_Result,WebApi.defraimp_goldbronzecommodity_FormattedResult>;
    user_defraimp_importapplication: WebMappingRetrieve<WebApi.defraimp_importapplication_Select,WebApi.defraimp_importapplication_Expand,WebApi.defraimp_importapplication_Filter,WebApi.defraimp_importapplication_Fixed,WebApi.defraimp_importapplication_Result,WebApi.defraimp_importapplication_FormattedResult>;
    user_defraimp_importinspection: WebMappingRetrieve<WebApi.defraimp_importinspection_Select,WebApi.defraimp_importinspection_Expand,WebApi.defraimp_importinspection_Filter,WebApi.defraimp_importinspection_Fixed,WebApi.defraimp_importinspection_Result,WebApi.defraimp_importinspection_FormattedResult>;
    user_defraimp_importnotification: WebMappingRetrieve<WebApi.defraimp_importnotification_Select,WebApi.defraimp_importnotification_Expand,WebApi.defraimp_importnotification_Filter,WebApi.defraimp_importnotification_Fixed,WebApi.defraimp_importnotification_Result,WebApi.defraimp_importnotification_FormattedResult>;
    user_defraimp_inspectioncoveragerule: WebMappingRetrieve<WebApi.defraimp_inspectioncoveragerule_Select,WebApi.defraimp_inspectioncoveragerule_Expand,WebApi.defraimp_inspectioncoveragerule_Filter,WebApi.defraimp_inspectioncoveragerule_Fixed,WebApi.defraimp_inspectioncoveragerule_Result,WebApi.defraimp_inspectioncoveragerule_FormattedResult>;
    user_defraimp_itahc: WebMappingRetrieve<WebApi.defraimp_itahc_Select,WebApi.defraimp_itahc_Expand,WebApi.defraimp_itahc_Filter,WebApi.defraimp_itahc_Fixed,WebApi.defraimp_itahc_Result,WebApi.defraimp_itahc_FormattedResult>;
    user_defraimp_placeoforigin: WebMappingRetrieve<WebApi.defraimp_placeoforigin_Select,WebApi.defraimp_placeoforigin_Expand,WebApi.defraimp_placeoforigin_Filter,WebApi.defraimp_placeoforigin_Fixed,WebApi.defraimp_placeoforigin_Result,WebApi.defraimp_placeoforigin_FormattedResult>;
    user_defraimp_sampletest: WebMappingRetrieve<WebApi.defraimp_sampletest_Select,WebApi.defraimp_sampletest_Expand,WebApi.defraimp_sampletest_Filter,WebApi.defraimp_sampletest_Fixed,WebApi.defraimp_sampletest_Result,WebApi.defraimp_sampletest_FormattedResult>;
    user_owner_postfollows: WebMappingRetrieve<WebApi.PostFollow_Select,WebApi.PostFollow_Expand,WebApi.PostFollow_Filter,WebApi.PostFollow_Fixed,WebApi.PostFollow_Result,WebApi.PostFollow_FormattedResult>;
    user_parent_user: WebMappingRetrieve<WebApi.SystemUser_Select,WebApi.SystemUser_Expand,WebApi.SystemUser_Filter,WebApi.SystemUser_Fixed,WebApi.SystemUser_Result,WebApi.SystemUser_FormattedResult>;
    workflow_createdby: WebMappingRetrieve<WebApi.Workflow_Select,WebApi.Workflow_Expand,WebApi.Workflow_Filter,WebApi.Workflow_Fixed,WebApi.Workflow_Result,WebApi.Workflow_FormattedResult>;
    workflow_createdonbehalfby: WebMappingRetrieve<WebApi.Workflow_Select,WebApi.Workflow_Expand,WebApi.Workflow_Filter,WebApi.Workflow_Fixed,WebApi.Workflow_Result,WebApi.Workflow_FormattedResult>;
    workflow_modifiedby: WebMappingRetrieve<WebApi.Workflow_Select,WebApi.Workflow_Expand,WebApi.Workflow_Filter,WebApi.Workflow_Fixed,WebApi.Workflow_Result,WebApi.Workflow_FormattedResult>;
    workflow_modifiedonbehalfby: WebMappingRetrieve<WebApi.Workflow_Select,WebApi.Workflow_Expand,WebApi.Workflow_Filter,WebApi.Workflow_Fixed,WebApi.Workflow_Result,WebApi.Workflow_FormattedResult>;
  }
}
interface WebEntitiesRetrieve {
  systemusers: WebMappingRetrieve<WebApi.SystemUser_Select,WebApi.SystemUser_Expand,WebApi.SystemUser_Filter,WebApi.SystemUser_Fixed,WebApi.SystemUser_Result,WebApi.SystemUser_FormattedResult>;
}
interface WebEntitiesRelated {
  systemusers: WebMappingRelated<WebApi.SystemUser_RelatedOne,WebApi.SystemUser_RelatedMany>;
}
interface WebEntitiesCUDA {
  systemusers: WebMappingCUDA<WebApi.SystemUser_Create,WebApi.SystemUser_Update,WebApi.SystemUser_Select>;
}
