name: $(GITVERSION_FullSemVer)

pool:
  vmImage: windows-latest

trigger:
  batch: false
  branches:
    include:
      - main
pr: none

resources:
  repositories:
    - repository: power-pipelines
      name: ewingjm/power-pipelines
      ref: refs/heads/main
      type: github
      endpoint: github.com_ewingjm

variables:
  - group: Environment - Imports - DEV

extends:
  template: templates/power-platform/pipelines/build-package-pipeline.yml@power-pipelines
  parameters:
    dotNetSdkVersion: 8.x
    packageProject: deploy\Defra.Imports.Deployment\Defra.Imports.Deployment.csproj
    unitTestsProject: tests\Defra.Imports.UnitTests\Defra.Imports.UnitTests.csproj
    serviceConnection: $(Environment.ManagementApp.ServiceConnectionName)
    preBuildSteps:
      - template: templates\steps\sonarqube-prepare-steps.yml@self
    postBuildSteps:
      - template: templates\steps\run-typescript-unit-tests-steps.yml@self
      - template: templates\steps\sonarqube-publish-steps.yml@self