name: $(GITVERSION_FullSemVer)

parameters:
  - name: solution
    displayName: Solution
    type: string
    values:
      - defra_Imports
  - name: workItemId
    displayName: Work item ID
    type: string
  - name: branch
    displayName: Branch name
    type: string
    default: ''

pool:
  vmImage: windows-latest

trigger: none
pr: none

resources:
  repositories:
    - repository: power-pipelines
      name: ewingjm/power-pipelines
      ref: refs/heads/main
      type: github
      endpoint: github.com_ewingjm

variables:
  - group: Environment - Imports - DEV
  - group: Tests - Imports - DEV

extends:
  template: templates/power-platform/pipelines/create-development-environment-pipeline.yml@power-pipelines
  parameters:
    solution: ${{ parameters.solution }}
    workItemId: ${{ parameters.workItemId }}
    packageProject: deploy\Defra.Imports.Deployment\Defra.Imports.Deployment.csproj
    displayNamePrefix: $(Environment.DisplayNamePrefix)
    domainNamePrefix: $(Environment.DomainNamePrefix)
    serviceConnection: $(Environment.ManagementApp.ServiceConnectionName)
    deployServiceConnection: $(Environment.DeploymentUser.ServiceConnectionName)
    templates: D365_CustomerService
    securityGroupId: $(Environment.SecurityGroupId)
    adminSecurityGroupId: $(Environment.AdminSecurityGroupId)
    templateEnvironmentUrl: $(Environment.TemplateEnvironmentUrl)
    branch: ${{ parameters.branch }}
    prepareEnvironmentJobs:
      - template: templates/jobs/create-application-user-job.yml
        parameters:
          jobName: CreateDeploymentApplicationUser
          jobDisplayName: Ensure deployment application user exists
          applicationId: $(Environment.DeploymentUser.ApplicationId)
          systemUserId: $(Environment.DeploymentUser.SystemUserId)
          applicationUserName: $(Environment.DeploymentUser.Username)
          securityRoleName: System Administrator
          serviceConnection: $(Environment.ManagementApp.ServiceConnectionName)
      - template: templates/jobs/create-application-user-job.yml
        parameters:
          jobName: CreateTestsApplicationUser
          jobDisplayName: Ensure test application user exists
          applicationId: $(Tests.ApplicationUser.ApplicationId)
          securityRoleName: System Administrator
          serviceConnection: $(Environment.ManagementApp.ServiceConnectionName)
    config: PkgAssets/ImportConfig.Standalone.xml
