name: $(SetAggregateRunNumber.RunNumber)

pool:
  vmImage: windows-latest

# Triggered by deploy-orchestrator-tst.yml, which only queues a run here when
# new pims artifacts are available to deploy.
trigger: none
pr: none

resources:
  pipelines:
    - pipeline: pims
      source: pims
      branch: main
  repositories:
    - repository: power-pipelines
      name: ewingjm/power-pipelines
      ref: refs/heads/main
      type: github
      endpoint: github.com_ewingjm

variables:
  - group: Environment - Imports - TST
  - group: Tests - Imports - TST
  - group: Key Vault - Test Users - defradev

extends:
  template: templates/power-platform/pipelines/deploy-packages-pipeline.yml@power-pipelines
  parameters:
    serviceConnection: Power Platform - Deployment (defradev)
    environment: TST
    url: $(Environment.Url)
    packages:
      - resource: pims
        artifact: package
        file: Defra.Imports.Deployment.dll
    tagSuccess: true
    testJobs:
      - template: templates/jobs/run-dotnet-integration-tests-job.yml
        parameters:
          clientId: $(Tests.ApplicationUser.ApplicationId)
          keyVaultTenantId: $(KeyVault.TestUsers.TenantId)
          keyVaultClientId: $(KeyVault.TestUsers.ClientId)
          keyVaultClientSecret: $(KeyVault.TestUsers.ClientSecret)
          keyVaultName: $(KeyVault.TestUsers.Name)
      - template: templates/jobs/run-dotnet-acceptance-tests-job.yml
        parameters:
          clientId: $(Tests.ApplicationUser.ApplicationId)
          keyVaultTenantId: $(KeyVault.TestUsers.TenantId)
          keyVaultClientId: $(KeyVault.TestUsers.ClientId)
          keyVaultClientSecret: $(KeyVault.TestUsers.ClientSecret)
          keyVaultName: $(KeyVault.TestUsers.Name)
          dependsOn: RunDotNetIntegrationTests