name: $(GITVERSION_FullSemVer)

pool:
  vmImage: windows-latest

pr:
  autoCancel: false

trigger: none

resources:
  repositories:
    - repository: power-pipelines
      name: ewingjm/power-pipelines
      ref: refs/heads/main
      type: github
      endpoint: github.com_ewingjm

variables:
  - group: Environment - Imports - CI

extends:
  template: templates/power-platform/pipelines/validate-package-pipeline.yml@power-pipelines
  parameters:
    packageProject: deploy\Defra.Imports.Deployment\Defra.Imports.Deployment.csproj
    serviceConnection: Power Platform - Management App
    deployServiceConnection: Power Platform - Deployment (defradev)
    solutionSourcePattern: src/solutions/*/src
    packageSourcePatterns:
      - deploy/Defra.Imports.Deployment/*
    webResourceSourcePatterns: 
      - src/webresources/*
    assemblySourcePatterns:
      - src/common/*
      - src/pluginassemblies/*
    displayNamePrefix: DEFRA-CUSTMSTR-EUE-CI-IMP
    domainNamePrefix: custmstr-ci-imp
    templates: D365_CustomerService
    securityGroupId: 002fed8f-6752-4c81-80c8-4928d23ed7d5
    adminSecurityGroupId: 54b2386b-c4dd-4e31-b7b1-3f31d71dcec7 # AG-DEFRA-TRADE-DEV-CORE (TODO: make new group)
    templateEnvironmentUrl: https://custmstr-eue-template-imp.crm4.dynamics.com/
    prepareEnvironmentJobs:
      - template: templates/jobs/create-application-user-job.yml
        parameters:
          applicationId: afa59571-3c39-4ebc-80d8-a9a0fb49077d
          systemUserId: ca80c879-8351-ea11-a812-000d3ab5d511
          applicationUserName: EUE-IMP-DYNAMICS-DEV
          securityRoleName: System Administrator
          serviceConnection: Power Platform - Management App
    postBuildSteps:
      - template: templates\steps\run-typescript-unit-tests-steps.yml@self