declare namespace WebApi {
  interface defraimp_importquery_Base extends WebEntity {
    activityadditionalparams?: string | null;
    activityid?: string | null;
    activitytypecode?: string | null;
    actualdurationminutes?: number | null;
    actualend?: Date | null;
    actualstart?: Date | null;
    community?: socialprofile_community | null;
    createdon?: Date | null;
    defraimp_dateresolved?: Date | null;
    defraimp_duedate?: Date | null;
    defraimp_querynumber?: string | null;
    defraimp_querysentto?: string | null;
    deliverylastattemptedon?: Date | null;
    deliveryprioritycode?: activitypointer_deliveryprioritycode | null;
    description?: string | null;
    exchangeitemid?: string | null;
    exchangerate?: number | null;
    exchangeweblink?: string | null;
    importsequencenumber?: number | null;
    instancetypecode?: defraimp_importquery_instancetypecode | null;
    isbilled?: boolean | null;
    ismapiprivate?: boolean | null;
    isregularactivity?: boolean | null;
    isworkflowcreated?: boolean | null;
    lastonholdtime?: Date | null;
    leftvoicemail?: boolean | null;
    modifiedon?: Date | null;
    onholdtime?: number | null;
    overriddencreatedon?: Date | null;
    postponeactivityprocessinguntil?: Date | null;
    prioritycode?: defraimp_importquery_prioritycode | null;
    processid?: string | null;
    scheduleddurationminutes?: number | null;
    scheduledend?: Date | null;
    scheduledstart?: Date | null;
    senton?: Date | null;
    seriesid?: string | null;
    sortdate?: Date | null;
    stageid?: string | null;
    statecode?: defraimp_importquery_statecode | null;
    statuscode?: defraimp_importquery_statuscode | null;
    subject?: string | null;
    timezoneruleversionnumber?: number | null;
    traversedpath?: string | null;
    utcconversiontimezonecode?: number | null;
    versionnumber?: number | null;
  }
  interface defraimp_importquery_Relationships {
    defraimp_ITAHC_defraimp_importquery?: defraimp_itahc_Result | null;
    defraimp_OriginalQuery_defraimp_importquery?: defraimp_importquery_Result | null;
    defraimp_defraimp_importquery_defraimp_importquery_OriginalQuery?: defraimp_importquery_Result[] | null;
    defraimp_importquery_activity_parties?: ActivityParty_Result[] | null;
    regardingobjectid_defraimp_importapplication_defraimp_importquery?: defraimp_importapplication_Result | null;
  }
  interface defraimp_importquery extends defraimp_importquery_Base, defraimp_importquery_Relationships {
    defraimp_ITAHC_defraimp_importquery_bind$defraimp_itahcs?: string | null;
    defraimp_OriginalQuery_defraimp_importquery_bind$defraimp_importqueries?: string | null;
    ownerid_defraimp_importquery_bind$systemusers?: string | null;
    ownerid_defraimp_importquery_bind$teams?: string | null;
    regardingobjectid_account_defraimp_importquery_bind$accounts?: string | null;
    regardingobjectid_bookableresourcebooking_defraimp_importquery_bind$bookableresourcebookings?: string | null;
    regardingobjectid_bookableresourcebookingheader_defraimp_importquery_bind$bookableresourcebookingheaders?: string | null;
    regardingobjectid_bulkoperation_defraimp_importquery_bind$bulkoperations?: string | null;
    regardingobjectid_campaign_defraimp_importquery_bind$campaigns?: string | null;
    regardingobjectid_campaignactivity_defraimp_importquery_bind$campaignactivities?: string | null;
    regardingobjectid_contact_defraimp_importquery_bind$contacts?: string | null;
    regardingobjectid_contract_defraimp_importquery_bind$contracts?: string | null;
    regardingobjectid_defra_addressdetails_defraimp_importquery_bind$defra_addressdetailses?: string | null;
    regardingobjectid_defra_invitation_defraimp_importquery_bind$defra_invitations?: string | null;
    regardingobjectid_defraexp_exportapplication_defraimp_importquery_bind$defraexp_exportapplications?: string | null;
    regardingobjectid_defraimp_importapplication_defraimp_importquery_bind$defraimp_importapplications?: string | null;
    regardingobjectid_entitlement_defraimp_importquery_bind$entitlements?: string | null;
    regardingobjectid_entitlementtemplate_defraimp_importquery_bind$entitlementtemplates?: string | null;
    regardingobjectid_incident_defraimp_importquery_bind$incidents?: string | null;
    regardingobjectid_invoice_defraimp_importquery_bind$invoices?: string | null;
    regardingobjectid_knowledgearticle_defraimp_importquery_bind$knowledgearticles?: string | null;
    regardingobjectid_knowledgebaserecord_defraimp_importquery_bind$knowledgebaserecords?: string | null;
    regardingobjectid_lead_defraimp_importquery_bind$leads?: string | null;
    regardingobjectid_msdyn_customerasset_defraimp_importquery_bind$msdyn_customerassets?: string | null;
    regardingobjectid_msdyn_playbookinstance_defraimp_importquery_bind$msdyn_playbookinstances?: string | null;
    regardingobjectid_msdyn_postalbum_defraimp_importquery_bind$msdyn_postalbums?: string | null;
    regardingobjectid_new_interactionforemail_defraimp_importquery_bind$interactionforemails?: string | null;
    regardingobjectid_opportunity_defraimp_importquery_bind$opportunities?: string | null;
    regardingobjectid_quote_defraimp_importquery_bind$quotes?: string | null;
    regardingobjectid_salesorder_defraimp_importquery_bind$salesorders?: string | null;
    regardingobjectid_site_defraimp_importquery_bind$sites?: string | null;
    serviceid_defraimp_importquery_bind$services?: string | null;
    sla_activitypointer_sla_defraimp_importquery_bind$slas?: string | null;
    transactioncurrencyid_defraimp_importquery_bind$transactioncurrencies?: string | null;
  }
  interface defraimp_importquery_Create extends defraimp_importquery {
    activityid_defraimp_importquery_bind$activitypointers?: string | null;
  }
  interface defraimp_importquery_Update extends defraimp_importquery {
  }
  interface defraimp_importquery_Select {
    activityadditionalparams: WebAttribute<defraimp_importquery_Select, { activityadditionalparams: string | null }, {  }>;
    activityid: WebAttribute<defraimp_importquery_Select, { activityid: string | null }, {  }>;
    activitytypecode: WebAttribute<defraimp_importquery_Select, { activitytypecode: string | null }, {  }>;
    actualdurationminutes: WebAttribute<defraimp_importquery_Select, { actualdurationminutes: number | null }, {  }>;
    actualend: WebAttribute<defraimp_importquery_Select, { actualend: Date | null }, { actualend_formatted?: string }>;
    actualstart: WebAttribute<defraimp_importquery_Select, { actualstart: Date | null }, { actualstart_formatted?: string }>;
    bcc_guid: WebAttribute<defraimp_importquery_Select, { bcc_guid: string | null }, { bcc_formatted?: string }>;
    cc_guid: WebAttribute<defraimp_importquery_Select, { cc_guid: string | null }, { cc_formatted?: string }>;
    community: WebAttribute<defraimp_importquery_Select, { community: socialprofile_community | null }, { community_formatted?: string }>;
    createdby_guid: WebAttribute<defraimp_importquery_Select, { createdby_guid: string | null }, { createdby_formatted?: string }>;
    createdon: WebAttribute<defraimp_importquery_Select, { createdon: Date | null }, { createdon_formatted?: string }>;
    createdonbehalfby_guid: WebAttribute<defraimp_importquery_Select, { createdonbehalfby_guid: string | null }, { createdonbehalfby_formatted?: string }>;
    customers_guid: WebAttribute<defraimp_importquery_Select, { customers_guid: string | null }, { customers_formatted?: string }>;
    defraimp_dateresolved: WebAttribute<defraimp_importquery_Select, { defraimp_dateresolved: Date | null }, { defraimp_dateresolved_formatted?: string }>;
    defraimp_duedate: WebAttribute<defraimp_importquery_Select, { defraimp_duedate: Date | null }, { defraimp_duedate_formatted?: string }>;
    defraimp_itahc_guid: WebAttribute<defraimp_importquery_Select, { defraimp_itahc_guid: string | null }, { defraimp_itahc_formatted?: string }>;
    defraimp_originalquery_guid: WebAttribute<defraimp_importquery_Select, { defraimp_originalquery_guid: string | null }, { defraimp_originalquery_formatted?: string }>;
    defraimp_querynumber: WebAttribute<defraimp_importquery_Select, { defraimp_querynumber: string | null }, {  }>;
    defraimp_querysentto: WebAttribute<defraimp_importquery_Select, { defraimp_querysentto: string | null }, {  }>;
    deliverylastattemptedon: WebAttribute<defraimp_importquery_Select, { deliverylastattemptedon: Date | null }, { deliverylastattemptedon_formatted?: string }>;
    deliveryprioritycode: WebAttribute<defraimp_importquery_Select, { deliveryprioritycode: activitypointer_deliveryprioritycode | null }, { deliveryprioritycode_formatted?: string }>;
    description: WebAttribute<defraimp_importquery_Select, { description: string | null }, {  }>;
    exchangeitemid: WebAttribute<defraimp_importquery_Select, { exchangeitemid: string | null }, {  }>;
    exchangerate: WebAttribute<defraimp_importquery_Select, { exchangerate: number | null }, {  }>;
    exchangeweblink: WebAttribute<defraimp_importquery_Select, { exchangeweblink: string | null }, {  }>;
    from_guid: WebAttribute<defraimp_importquery_Select, { from_guid: string | null }, { from_formatted?: string }>;
    importsequencenumber: WebAttribute<defraimp_importquery_Select, { importsequencenumber: number | null }, {  }>;
    instancetypecode: WebAttribute<defraimp_importquery_Select, { instancetypecode: defraimp_importquery_instancetypecode | null }, { instancetypecode_formatted?: string }>;
    isbilled: WebAttribute<defraimp_importquery_Select, { isbilled: boolean | null }, {  }>;
    ismapiprivate: WebAttribute<defraimp_importquery_Select, { ismapiprivate: boolean | null }, {  }>;
    isregularactivity: WebAttribute<defraimp_importquery_Select, { isregularactivity: boolean | null }, {  }>;
    isworkflowcreated: WebAttribute<defraimp_importquery_Select, { isworkflowcreated: boolean | null }, {  }>;
    lastonholdtime: WebAttribute<defraimp_importquery_Select, { lastonholdtime: Date | null }, { lastonholdtime_formatted?: string }>;
    leftvoicemail: WebAttribute<defraimp_importquery_Select, { leftvoicemail: boolean | null }, {  }>;
    modifiedby_guid: WebAttribute<defraimp_importquery_Select, { modifiedby_guid: string | null }, { modifiedby_formatted?: string }>;
    modifiedon: WebAttribute<defraimp_importquery_Select, { modifiedon: Date | null }, { modifiedon_formatted?: string }>;
    modifiedonbehalfby_guid: WebAttribute<defraimp_importquery_Select, { modifiedonbehalfby_guid: string | null }, { modifiedonbehalfby_formatted?: string }>;
    onholdtime: WebAttribute<defraimp_importquery_Select, { onholdtime: number | null }, {  }>;
    optionalattendees_guid: WebAttribute<defraimp_importquery_Select, { optionalattendees_guid: string | null }, { optionalattendees_formatted?: string }>;
    organizer_guid: WebAttribute<defraimp_importquery_Select, { organizer_guid: string | null }, { organizer_formatted?: string }>;
    overriddencreatedon: WebAttribute<defraimp_importquery_Select, { overriddencreatedon: Date | null }, { overriddencreatedon_formatted?: string }>;
    ownerid_guid: WebAttribute<defraimp_importquery_Select, { ownerid_guid: string | null }, { ownerid_formatted?: string }>;
    owningbusinessunit_guid: WebAttribute<defraimp_importquery_Select, { owningbusinessunit_guid: string | null }, { owningbusinessunit_formatted?: string }>;
    owningteam_guid: WebAttribute<defraimp_importquery_Select, { owningteam_guid: string | null }, { owningteam_formatted?: string }>;
    owninguser_guid: WebAttribute<defraimp_importquery_Select, { owninguser_guid: string | null }, { owninguser_formatted?: string }>;
    partners_guid: WebAttribute<defraimp_importquery_Select, { partners_guid: string | null }, { partners_formatted?: string }>;
    postponeactivityprocessinguntil: WebAttribute<defraimp_importquery_Select, { postponeactivityprocessinguntil: Date | null }, { postponeactivityprocessinguntil_formatted?: string }>;
    prioritycode: WebAttribute<defraimp_importquery_Select, { prioritycode: defraimp_importquery_prioritycode | null }, { prioritycode_formatted?: string }>;
    processid: WebAttribute<defraimp_importquery_Select, { processid: string | null }, {  }>;
    regardingobjectid_guid: WebAttribute<defraimp_importquery_Select, { regardingobjectid_guid: string | null }, { regardingobjectid_formatted?: string }>;
    requiredattendees_guid: WebAttribute<defraimp_importquery_Select, { requiredattendees_guid: string | null }, { requiredattendees_formatted?: string }>;
    resources_guid: WebAttribute<defraimp_importquery_Select, { resources_guid: string | null }, { resources_formatted?: string }>;
    scheduleddurationminutes: WebAttribute<defraimp_importquery_Select, { scheduleddurationminutes: number | null }, {  }>;
    scheduledend: WebAttribute<defraimp_importquery_Select, { scheduledend: Date | null }, { scheduledend_formatted?: string }>;
    scheduledstart: WebAttribute<defraimp_importquery_Select, { scheduledstart: Date | null }, { scheduledstart_formatted?: string }>;
    sendermailboxid_guid: WebAttribute<defraimp_importquery_Select, { sendermailboxid_guid: string | null }, { sendermailboxid_formatted?: string }>;
    senton: WebAttribute<defraimp_importquery_Select, { senton: Date | null }, { senton_formatted?: string }>;
    seriesid: WebAttribute<defraimp_importquery_Select, { seriesid: string | null }, {  }>;
    serviceid_guid: WebAttribute<defraimp_importquery_Select, { serviceid_guid: string | null }, { serviceid_formatted?: string }>;
    slaid_guid: WebAttribute<defraimp_importquery_Select, { slaid_guid: string | null }, { slaid_formatted?: string }>;
    slainvokedid_guid: WebAttribute<defraimp_importquery_Select, { slainvokedid_guid: string | null }, { slainvokedid_formatted?: string }>;
    sortdate: WebAttribute<defraimp_importquery_Select, { sortdate: Date | null }, { sortdate_formatted?: string }>;
    stageid: WebAttribute<defraimp_importquery_Select, { stageid: string | null }, {  }>;
    statecode: WebAttribute<defraimp_importquery_Select, { statecode: defraimp_importquery_statecode | null }, { statecode_formatted?: string }>;
    statuscode: WebAttribute<defraimp_importquery_Select, { statuscode: defraimp_importquery_statuscode | null }, { statuscode_formatted?: string }>;
    subject: WebAttribute<defraimp_importquery_Select, { subject: string | null }, {  }>;
    timezoneruleversionnumber: WebAttribute<defraimp_importquery_Select, { timezoneruleversionnumber: number | null }, {  }>;
    to_guid: WebAttribute<defraimp_importquery_Select, { to_guid: string | null }, { to_formatted?: string }>;
    transactioncurrencyid_guid: WebAttribute<defraimp_importquery_Select, { transactioncurrencyid_guid: string | null }, { transactioncurrencyid_formatted?: string }>;
    traversedpath: WebAttribute<defraimp_importquery_Select, { traversedpath: string | null }, {  }>;
    utcconversiontimezonecode: WebAttribute<defraimp_importquery_Select, { utcconversiontimezonecode: number | null }, {  }>;
    versionnumber: WebAttribute<defraimp_importquery_Select, { versionnumber: number | null }, {  }>;
  }
  interface defraimp_importquery_Filter {
    activityadditionalparams: string;
    activityid: XQW.Guid;
    activitytypecode: string;
    actualdurationminutes: number;
    actualend: Date;
    actualstart: Date;
    bcc_guid: XQW.Guid;
    cc_guid: XQW.Guid;
    community: socialprofile_community;
    createdby_guid: XQW.Guid;
    createdon: Date;
    createdonbehalfby_guid: XQW.Guid;
    customers_guid: XQW.Guid;
    defraimp_dateresolved: Date;
    defraimp_duedate: Date;
    defraimp_itahc_guid: XQW.Guid;
    defraimp_originalquery_guid: XQW.Guid;
    defraimp_querynumber: string;
    defraimp_querysentto: string;
    deliverylastattemptedon: Date;
    deliveryprioritycode: activitypointer_deliveryprioritycode;
    description: string;
    exchangeitemid: string;
    exchangerate: any;
    exchangeweblink: string;
    from_guid: XQW.Guid;
    importsequencenumber: number;
    instancetypecode: defraimp_importquery_instancetypecode;
    isbilled: boolean;
    ismapiprivate: boolean;
    isregularactivity: boolean;
    isworkflowcreated: boolean;
    lastonholdtime: Date;
    leftvoicemail: boolean;
    modifiedby_guid: XQW.Guid;
    modifiedon: Date;
    modifiedonbehalfby_guid: XQW.Guid;
    onholdtime: number;
    optionalattendees_guid: XQW.Guid;
    organizer_guid: XQW.Guid;
    overriddencreatedon: Date;
    ownerid_guid: XQW.Guid;
    owningbusinessunit_guid: XQW.Guid;
    owningteam_guid: XQW.Guid;
    owninguser_guid: XQW.Guid;
    partners_guid: XQW.Guid;
    postponeactivityprocessinguntil: Date;
    prioritycode: defraimp_importquery_prioritycode;
    processid: XQW.Guid;
    regardingobjectid_guid: XQW.Guid;
    requiredattendees_guid: XQW.Guid;
    resources_guid: XQW.Guid;
    scheduleddurationminutes: number;
    scheduledend: Date;
    scheduledstart: Date;
    sendermailboxid_guid: XQW.Guid;
    senton: Date;
    seriesid: XQW.Guid;
    serviceid_guid: XQW.Guid;
    slaid_guid: XQW.Guid;
    slainvokedid_guid: XQW.Guid;
    sortdate: Date;
    stageid: XQW.Guid;
    statecode: defraimp_importquery_statecode;
    statuscode: defraimp_importquery_statuscode;
    subject: string;
    timezoneruleversionnumber: number;
    to_guid: XQW.Guid;
    transactioncurrencyid_guid: XQW.Guid;
    traversedpath: string;
    utcconversiontimezonecode: number;
    versionnumber: number;
  }
  interface defraimp_importquery_Expand {
    defraimp_ITAHC_defraimp_importquery: WebExpand<defraimp_importquery_Expand, defraimp_itahc_Select, defraimp_itahc_Filter, { defraimp_ITAHC_defraimp_importquery: defraimp_itahc_Result }>;
    defraimp_OriginalQuery_defraimp_importquery: WebExpand<defraimp_importquery_Expand, defraimp_importquery_Select, defraimp_importquery_Filter, { defraimp_OriginalQuery_defraimp_importquery: defraimp_importquery_Result }>;
    defraimp_defraimp_importquery_defraimp_importquery_OriginalQuery: WebExpand<defraimp_importquery_Expand, defraimp_importquery_Select, defraimp_importquery_Filter, { defraimp_defraimp_importquery_defraimp_importquery_OriginalQuery: defraimp_importquery_Result[] }>;
    defraimp_importquery_activity_parties: WebExpand<defraimp_importquery_Expand, ActivityParty_Select, ActivityParty_Filter, { defraimp_importquery_activity_parties: ActivityParty_Result[] }>;
    regardingobjectid_defraimp_importapplication_defraimp_importquery: WebExpand<defraimp_importquery_Expand, defraimp_importapplication_Select, defraimp_importapplication_Filter, { regardingobjectid_defraimp_importapplication_defraimp_importquery: defraimp_importapplication_Result }>;
  }
  interface defraimp_importquery_FormattedResult {
    actualend_formatted?: string;
    actualstart_formatted?: string;
    bcc_formatted?: string;
    cc_formatted?: string;
    community_formatted?: string;
    createdby_formatted?: string;
    createdon_formatted?: string;
    createdonbehalfby_formatted?: string;
    customers_formatted?: string;
    defraimp_dateresolved_formatted?: string;
    defraimp_duedate_formatted?: string;
    defraimp_itahc_formatted?: string;
    defraimp_originalquery_formatted?: string;
    deliverylastattemptedon_formatted?: string;
    deliveryprioritycode_formatted?: string;
    from_formatted?: string;
    instancetypecode_formatted?: string;
    lastonholdtime_formatted?: string;
    modifiedby_formatted?: string;
    modifiedon_formatted?: string;
    modifiedonbehalfby_formatted?: string;
    optionalattendees_formatted?: string;
    organizer_formatted?: string;
    overriddencreatedon_formatted?: string;
    ownerid_formatted?: string;
    owningbusinessunit_formatted?: string;
    owningteam_formatted?: string;
    owninguser_formatted?: string;
    partners_formatted?: string;
    postponeactivityprocessinguntil_formatted?: string;
    prioritycode_formatted?: string;
    regardingobjectid_formatted?: string;
    requiredattendees_formatted?: string;
    resources_formatted?: string;
    scheduledend_formatted?: string;
    scheduledstart_formatted?: string;
    sendermailboxid_formatted?: string;
    senton_formatted?: string;
    serviceid_formatted?: string;
    slaid_formatted?: string;
    slainvokedid_formatted?: string;
    sortdate_formatted?: string;
    statecode_formatted?: string;
    statuscode_formatted?: string;
    to_formatted?: string;
    transactioncurrencyid_formatted?: string;
  }
  interface defraimp_importquery_Result extends defraimp_importquery_Base, defraimp_importquery_Relationships {
    "@odata.etag": string;
    bcc_guid: string | null;
    cc_guid: string | null;
    createdby_guid: string | null;
    createdonbehalfby_guid: string | null;
    customers_guid: string | null;
    defraimp_itahc_guid: string | null;
    defraimp_originalquery_guid: string | null;
    from_guid: string | null;
    modifiedby_guid: string | null;
    modifiedonbehalfby_guid: string | null;
    optionalattendees_guid: string | null;
    organizer_guid: string | null;
    ownerid_guid: string | null;
    owningbusinessunit_guid: string | null;
    owningteam_guid: string | null;
    owninguser_guid: string | null;
    partners_guid: string | null;
    regardingobjectid_guid: string | null;
    requiredattendees_guid: string | null;
    resources_guid: string | null;
    sendermailboxid_guid: string | null;
    serviceid_guid: string | null;
    slaid_guid: string | null;
    slainvokedid_guid: string | null;
    to_guid: string | null;
    transactioncurrencyid_guid: string | null;
  }
  interface defraimp_importquery_RelatedOne {
    defraimp_ITAHC_defraimp_importquery: WebMappingRetrieve<WebApi.defraimp_itahc_Select,WebApi.defraimp_itahc_Expand,WebApi.defraimp_itahc_Filter,WebApi.defraimp_itahc_Fixed,WebApi.defraimp_itahc_Result,WebApi.defraimp_itahc_FormattedResult>;
    defraimp_OriginalQuery_defraimp_importquery: WebMappingRetrieve<WebApi.defraimp_importquery_Select,WebApi.defraimp_importquery_Expand,WebApi.defraimp_importquery_Filter,WebApi.defraimp_importquery_Fixed,WebApi.defraimp_importquery_Result,WebApi.defraimp_importquery_FormattedResult>;
    regardingobjectid_defraimp_importapplication_defraimp_importquery: WebMappingRetrieve<WebApi.defraimp_importapplication_Select,WebApi.defraimp_importapplication_Expand,WebApi.defraimp_importapplication_Filter,WebApi.defraimp_importapplication_Fixed,WebApi.defraimp_importapplication_Result,WebApi.defraimp_importapplication_FormattedResult>;
  }
  interface defraimp_importquery_RelatedMany {
    defraimp_defraimp_importquery_defraimp_importquery_OriginalQuery: WebMappingRetrieve<WebApi.defraimp_importquery_Select,WebApi.defraimp_importquery_Expand,WebApi.defraimp_importquery_Filter,WebApi.defraimp_importquery_Fixed,WebApi.defraimp_importquery_Result,WebApi.defraimp_importquery_FormattedResult>;
    defraimp_importquery_activity_parties: WebMappingRetrieve<WebApi.ActivityParty_Select,WebApi.ActivityParty_Expand,WebApi.ActivityParty_Filter,WebApi.ActivityParty_Fixed,WebApi.ActivityParty_Result,WebApi.ActivityParty_FormattedResult>;
  }
}
interface WebEntitiesRetrieve {
  defraimp_importqueries: WebMappingRetrieve<WebApi.defraimp_importquery_Select,WebApi.defraimp_importquery_Expand,WebApi.defraimp_importquery_Filter,WebApi.defraimp_importquery_Fixed,WebApi.defraimp_importquery_Result,WebApi.defraimp_importquery_FormattedResult>;
}
interface WebEntitiesRelated {
  defraimp_importqueries: WebMappingRelated<WebApi.defraimp_importquery_RelatedOne,WebApi.defraimp_importquery_RelatedMany>;
}
interface WebEntitiesCUDA {
  defraimp_importqueries: WebMappingCUDA<WebApi.defraimp_importquery_Create,WebApi.defraimp_importquery_Update,WebApi.defraimp_importquery_Select>;
}
