<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" Version="35.6.5" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.10" />
    <PackageReference Include="Microsoft.PowerPlatform.Dataverse.Client" Version="1.2.26" />
    <PackageReference Include="ScenarioBuilder" Version="0.1.0" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Events\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\common\Defra.Imports.Container\Defra.Imports.Container.csproj" />
  </ItemGroup>

</Project>
