#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	/// <summary>
	/// Status of the Watch Flag
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum defraimp_watchflag_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Watch Flag
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum defraimp_watchflag_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("defraimp_watchflag")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class defraimp_WatchFlag : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the defraimp_watchflag entity
		/// </summary>
		public partial class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string defraimp_ImportApplicationId = "defraimp_importapplicationid";
			public const string defraimp_ImporterNotificationId = "defraimp_importernotificationid";
			public const string defraimp_ItahcId = "defraimp_itahcid";
			public const string defraimp_Name = "defraimp_name";
			public const string defraimp_WatchFlagId = "defraimp_watchflagid";
			public const string Id = "defraimp_watchflagid";
			public const string defraimp_WatchListId = "defraimp_watchlistid";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string defraimp_defraimp_importapplication_defraimp_watchflag_ImportApplicationId = "defraimp_defraimp_importapplication_defraimp_watchflag_ImportApplicationId";
			public const string defraimp_defraimp_importernotification_defraimp_watchflag_ImporterNotificationId = "defraimp_defraimp_importernotification_defraimp_watchflag_ImporterNotificationId";
			public const string defraimp_defraimp_itahc_defraimp_watchflag_ItahcId = "defraimp_defraimp_itahc_defraimp_watchflag_ItahcId";
			public const string defraimp_defraimp_watchlist_defraimp_watchflag_WatchListId = "defraimp_defraimp_watchlist_defraimp_watchflag_WatchListId";
			public const string lk_defraimp_watchflag_createdby = "lk_defraimp_watchflag_createdby";
			public const string lk_defraimp_watchflag_createdonbehalfby = "lk_defraimp_watchflag_createdonbehalfby";
			public const string lk_defraimp_watchflag_modifiedby = "lk_defraimp_watchflag_modifiedby";
			public const string lk_defraimp_watchflag_modifiedonbehalfby = "lk_defraimp_watchflag_modifiedonbehalfby";
			public const string user_defraimp_watchflag = "user_defraimp_watchflag";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public defraimp_WatchFlag() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "defraimp_watchflag";
		
		public const string EntityLogicalCollectionName = "defraimp_watchflags";
		
		public const string EntitySetName = "defraimp_watchflags";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_importapplicationid")]
		public Microsoft.Xrm.Sdk.EntityReference defraimp_ImportApplicationId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defraimp_importapplicationid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ImportApplicationId");
				this.SetAttributeValue("defraimp_importapplicationid", value);
				this.OnPropertyChanged("defraimp_ImportApplicationId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_importernotificationid")]
		public Microsoft.Xrm.Sdk.EntityReference defraimp_ImporterNotificationId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defraimp_importernotificationid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ImporterNotificationId");
				this.SetAttributeValue("defraimp_importernotificationid", value);
				this.OnPropertyChanged("defraimp_ImporterNotificationId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_itahcid")]
		public Microsoft.Xrm.Sdk.EntityReference defraimp_ItahcId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defraimp_itahcid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ItahcId");
				this.SetAttributeValue("defraimp_itahcid", value);
				this.OnPropertyChanged("defraimp_ItahcId");
			}
		}
		
		/// <summary>
		/// Required name field
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_name")]
		public string defraimp_Name
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_name");
			}
			set
			{
				this.OnPropertyChanging("defraimp_Name");
				this.SetAttributeValue("defraimp_name", value);
				this.OnPropertyChanged("defraimp_Name");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_watchflagid")]
		public System.Nullable<System.Guid> defraimp_WatchFlagId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("defraimp_watchflagid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_WatchFlagId");
				this.SetAttributeValue("defraimp_watchflagid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("defraimp_WatchFlagId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_watchflagid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.defraimp_WatchFlagId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_watchlistid")]
		public Microsoft.Xrm.Sdk.EntityReference defraimp_WatchListId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defraimp_watchlistid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_WatchListId");
				this.SetAttributeValue("defraimp_watchlistid", value);
				this.OnPropertyChanged("defraimp_WatchListId");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Watch Flag
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual defraimp_watchflag_statecode? statecode
		{
			get
			{
				return ((defraimp_watchflag_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("statecode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statecode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Watch Flag
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual defraimp_watchflag_statuscode? statuscode
		{
			get
			{
				return ((defraimp_watchflag_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 defraimp_defraimp_importapplication_defraimp_watchflag_ImportApplicationId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_importapplicationid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defraimp_importapplication_defraimp_watchflag_ImportApplicationId")]
		public Defra.Imports.Model.defraimp_importapplication defraimp_defraimp_importapplication_defraimp_watchflag_ImportApplicationId
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.defraimp_importapplication>("defraimp_defraimp_importapplication_defraimp_watchflag_ImportApplicationId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defraimp_importapplication_defraimp_watchflag_ImportApplicationId");
				this.SetRelatedEntity<Defra.Imports.Model.defraimp_importapplication>("defraimp_defraimp_importapplication_defraimp_watchflag_ImportApplicationId", null, value);
				this.OnPropertyChanged("defraimp_defraimp_importapplication_defraimp_watchflag_ImportApplicationId");
			}
		}
		
		/// <summary>
		/// N:1 defraimp_defraimp_importernotification_defraimp_watchflag_ImporterNotificationId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_importernotificationid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defraimp_importernotification_defraimp_watchflag_ImporterNotificationId")]
		public Defra.Imports.Model.defraimp_ImporterNotification defraimp_defraimp_importernotification_defraimp_watchflag_ImporterNotificationId
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.defraimp_ImporterNotification>("defraimp_defraimp_importernotification_defraimp_watchflag_ImporterNotificationId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defraimp_importernotification_defraimp_watchflag_ImporterNotificationId");
				this.SetRelatedEntity<Defra.Imports.Model.defraimp_ImporterNotification>("defraimp_defraimp_importernotification_defraimp_watchflag_ImporterNotificationId", null, value);
				this.OnPropertyChanged("defraimp_defraimp_importernotification_defraimp_watchflag_ImporterNotificationId");
			}
		}
		
		/// <summary>
		/// N:1 defraimp_defraimp_itahc_defraimp_watchflag_ItahcId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_itahcid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defraimp_itahc_defraimp_watchflag_ItahcId")]
		public Defra.Imports.Model.defraimp_itahc defraimp_defraimp_itahc_defraimp_watchflag_ItahcId
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.defraimp_itahc>("defraimp_defraimp_itahc_defraimp_watchflag_ItahcId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defraimp_itahc_defraimp_watchflag_ItahcId");
				this.SetRelatedEntity<Defra.Imports.Model.defraimp_itahc>("defraimp_defraimp_itahc_defraimp_watchflag_ItahcId", null, value);
				this.OnPropertyChanged("defraimp_defraimp_itahc_defraimp_watchflag_ItahcId");
			}
		}
		
		/// <summary>
		/// N:1 defraimp_defraimp_watchlist_defraimp_watchflag_WatchListId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_watchlistid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defraimp_watchlist_defraimp_watchflag_WatchListId")]
		public Defra.Imports.Model.defraimp_WatchList defraimp_defraimp_watchlist_defraimp_watchflag_WatchListId
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.defraimp_WatchList>("defraimp_defraimp_watchlist_defraimp_watchflag_WatchListId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defraimp_watchlist_defraimp_watchflag_WatchListId");
				this.SetRelatedEntity<Defra.Imports.Model.defraimp_WatchList>("defraimp_defraimp_watchlist_defraimp_watchflag_WatchListId", null, value);
				this.OnPropertyChanged("defraimp_defraimp_watchlist_defraimp_watchflag_WatchListId");
			}
		}
		
		/// <summary>
		/// N:1 lk_defraimp_watchflag_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defraimp_watchflag_createdby")]
		public Defra.Imports.Model.SystemUser lk_defraimp_watchflag_createdby
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("lk_defraimp_watchflag_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_defraimp_watchflag_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defraimp_watchflag_createdonbehalfby")]
		public Defra.Imports.Model.SystemUser lk_defraimp_watchflag_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("lk_defraimp_watchflag_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_defraimp_watchflag_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defraimp_watchflag_modifiedby")]
		public Defra.Imports.Model.SystemUser lk_defraimp_watchflag_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("lk_defraimp_watchflag_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_defraimp_watchflag_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defraimp_watchflag_modifiedonbehalfby")]
		public Defra.Imports.Model.SystemUser lk_defraimp_watchflag_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("lk_defraimp_watchflag_modifiedonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 user_defraimp_watchflag
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_defraimp_watchflag")]
		public Defra.Imports.Model.SystemUser user_defraimp_watchflag
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("user_defraimp_watchflag", null);
			}
		}
	}
}
#pragma warning restore CS1591
