#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	/// <summary>
	/// Status of the Watch List
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum defraimp_watchlist_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Watch List
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum defraimp_watchlist_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("defraimp_watchlist")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class defraimp_WatchList : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the defraimp_watchlist entity
		/// </summary>
		public partial class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string defraimp_Comments = "defraimp_comments";
			public const string defraimp_ConsigneeId = "defraimp_consigneeid";
			public const string defraimp_EndDate = "defraimp_enddate";
			public const string defraimp_Name = "defraimp_name";
			public const string defraimp_PlaceOfDestinationId = "defraimp_placeofdestinationid";
			public const string defraimp_PlaceOfOriginId = "defraimp_placeoforiginid";
			public const string defraimp_StartDate = "defraimp_startdate";
			public const string defraimp_TransporterId = "defraimp_transporterid";
			public const string defraimp_VeterinarianId = "defraimp_veterinarianid";
			public const string defraimp_WatchListId = "defraimp_watchlistid";
			public const string Id = "defraimp_watchlistid";
			public const string defraimp_WatchType = "defraimp_watchtype";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string defraimp_defraimp_watchlist_defraimp_watchflag_WatchListId = "defraimp_defraimp_watchlist_defraimp_watchflag_WatchListId";
			public const string defraimp_watchlist_Annotations = "defraimp_watchlist_Annotations";
			public const string defraimp_defraimp_consignee_defraimp_watchlist_ConsigneeId = "defraimp_defraimp_consignee_defraimp_watchlist_ConsigneeId";
			public const string defraimp_defraimp_placeofdestination_defraimp_watchlist_PlaceOfDestinationId = "defraimp_defraimp_placeofdestination_defraimp_watchlist_PlaceOfDestinationId";
			public const string defraimp_defraimp_placeoforigin_defraimp_watchlist_PlaceOfOriginId = "defraimp_defraimp_placeoforigin_defraimp_watchlist_PlaceOfOriginId";
			public const string defraimp_defraimp_transporter_defraimp_watchlist_TransporterId = "defraimp_defraimp_transporter_defraimp_watchlist_TransporterId";
			public const string lk_defraimp_watchlist_createdby = "lk_defraimp_watchlist_createdby";
			public const string lk_defraimp_watchlist_createdonbehalfby = "lk_defraimp_watchlist_createdonbehalfby";
			public const string lk_defraimp_watchlist_modifiedby = "lk_defraimp_watchlist_modifiedby";
			public const string lk_defraimp_watchlist_modifiedonbehalfby = "lk_defraimp_watchlist_modifiedonbehalfby";
			public const string user_defraimp_watchlist = "user_defraimp_watchlist";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public defraimp_WatchList() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "defraimp_watchlist";
		
		public const string EntityLogicalCollectionName = "defraimp_watchlists";
		
		public const string EntitySetName = "defraimp_watchlists";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_comments")]
		public string defraimp_Comments
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_comments");
			}
			set
			{
				this.OnPropertyChanging("defraimp_Comments");
				this.SetAttributeValue("defraimp_comments", value);
				this.OnPropertyChanged("defraimp_Comments");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_consigneeid")]
		public Microsoft.Xrm.Sdk.EntityReference defraimp_ConsigneeId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defraimp_consigneeid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ConsigneeId");
				this.SetAttributeValue("defraimp_consigneeid", value);
				this.OnPropertyChanged("defraimp_ConsigneeId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_enddate")]
		public System.Nullable<System.DateTime> defraimp_EndDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("defraimp_enddate");
			}
			set
			{
				this.OnPropertyChanging("defraimp_EndDate");
				this.SetAttributeValue("defraimp_enddate", value);
				this.OnPropertyChanged("defraimp_EndDate");
			}
		}
		
		/// <summary>
		/// Required name field
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_name")]
		public string defraimp_Name
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_name");
			}
			set
			{
				this.OnPropertyChanging("defraimp_Name");
				this.SetAttributeValue("defraimp_name", value);
				this.OnPropertyChanged("defraimp_Name");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeofdestinationid")]
		public Microsoft.Xrm.Sdk.EntityReference defraimp_PlaceOfDestinationId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defraimp_placeofdestinationid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PlaceOfDestinationId");
				this.SetAttributeValue("defraimp_placeofdestinationid", value);
				this.OnPropertyChanged("defraimp_PlaceOfDestinationId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeoforiginid")]
		public Microsoft.Xrm.Sdk.EntityReference defraimp_PlaceOfOriginId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defraimp_placeoforiginid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PlaceOfOriginId");
				this.SetAttributeValue("defraimp_placeoforiginid", value);
				this.OnPropertyChanged("defraimp_PlaceOfOriginId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_startdate")]
		public System.Nullable<System.DateTime> defraimp_StartDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("defraimp_startdate");
			}
			set
			{
				this.OnPropertyChanging("defraimp_StartDate");
				this.SetAttributeValue("defraimp_startdate", value);
				this.OnPropertyChanged("defraimp_StartDate");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_transporterid")]
		public Microsoft.Xrm.Sdk.EntityReference defraimp_TransporterId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defraimp_transporterid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_TransporterId");
				this.SetAttributeValue("defraimp_transporterid", value);
				this.OnPropertyChanged("defraimp_TransporterId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_veterinarianid")]
		public Microsoft.Xrm.Sdk.EntityReference defraimp_VeterinarianId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defraimp_veterinarianid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_VeterinarianId");
				this.SetAttributeValue("defraimp_veterinarianid", value);
				this.OnPropertyChanged("defraimp_VeterinarianId");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_watchlistid")]
		public System.Nullable<System.Guid> defraimp_WatchListId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("defraimp_watchlistid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_WatchListId");
				this.SetAttributeValue("defraimp_watchlistid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("defraimp_WatchListId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_watchlistid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.defraimp_WatchListId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_watchtype")]
		public virtual defraimp_watchtype? defraimp_WatchType
		{
			get
			{
				return ((defraimp_watchtype?)(EntityOptionSetEnum.GetEnum(this, "defraimp_watchtype")));
			}
			set
			{
				this.OnPropertyChanging("defraimp_WatchType");
				this.SetAttributeValue("defraimp_watchtype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("defraimp_WatchType");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Watch List
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual defraimp_watchlist_statecode? statecode
		{
			get
			{
				return ((defraimp_watchlist_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("statecode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statecode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Watch List
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual defraimp_watchlist_statuscode? statuscode
		{
			get
			{
				return ((defraimp_watchlist_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defraimp_watchlist_defraimp_watchflag_WatchListId
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defraimp_watchlist_defraimp_watchflag_WatchListId")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_WatchFlag> defraimp_defraimp_watchlist_defraimp_watchflag_WatchListId
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_WatchFlag>("defraimp_defraimp_watchlist_defraimp_watchflag_WatchListId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defraimp_watchlist_defraimp_watchflag_WatchListId");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_WatchFlag>("defraimp_defraimp_watchlist_defraimp_watchflag_WatchListId", null, value);
				this.OnPropertyChanged("defraimp_defraimp_watchlist_defraimp_watchflag_WatchListId");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_watchlist_Annotations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_watchlist_Annotations")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.Annotation> defraimp_watchlist_Annotations
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.Annotation>("defraimp_watchlist_Annotations", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_watchlist_Annotations");
				this.SetRelatedEntities<Defra.Imports.Model.Annotation>("defraimp_watchlist_Annotations", null, value);
				this.OnPropertyChanged("defraimp_watchlist_Annotations");
			}
		}
		
		/// <summary>
		/// N:1 defraimp_defraimp_consignee_defraimp_watchlist_ConsigneeId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_consigneeid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defraimp_consignee_defraimp_watchlist_ConsigneeId")]
		public Defra.Imports.Model.defraimp_Consignee defraimp_defraimp_consignee_defraimp_watchlist_ConsigneeId
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.defraimp_Consignee>("defraimp_defraimp_consignee_defraimp_watchlist_ConsigneeId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defraimp_consignee_defraimp_watchlist_ConsigneeId");
				this.SetRelatedEntity<Defra.Imports.Model.defraimp_Consignee>("defraimp_defraimp_consignee_defraimp_watchlist_ConsigneeId", null, value);
				this.OnPropertyChanged("defraimp_defraimp_consignee_defraimp_watchlist_ConsigneeId");
			}
		}
		
		/// <summary>
		/// N:1 defraimp_defraimp_placeofdestination_defraimp_watchlist_PlaceOfDestinationId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeofdestinationid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defraimp_placeofdestination_defraimp_watchlist_PlaceOfDestinationId")]
		public Defra.Imports.Model.defraimp_PlaceOfDestination defraimp_defraimp_placeofdestination_defraimp_watchlist_PlaceOfDestinationId
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.defraimp_PlaceOfDestination>("defraimp_defraimp_placeofdestination_defraimp_watchlist_PlaceOfDestinationId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defraimp_placeofdestination_defraimp_watchlist_PlaceOfDestinationId");
				this.SetRelatedEntity<Defra.Imports.Model.defraimp_PlaceOfDestination>("defraimp_defraimp_placeofdestination_defraimp_watchlist_PlaceOfDestinationId", null, value);
				this.OnPropertyChanged("defraimp_defraimp_placeofdestination_defraimp_watchlist_PlaceOfDestinationId");
			}
		}
		
		/// <summary>
		/// N:1 defraimp_defraimp_placeoforigin_defraimp_watchlist_PlaceOfOriginId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeoforiginid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defraimp_placeoforigin_defraimp_watchlist_PlaceOfOriginId")]
		public Defra.Imports.Model.defraimp_placeoforigin defraimp_defraimp_placeoforigin_defraimp_watchlist_PlaceOfOriginId
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.defraimp_placeoforigin>("defraimp_defraimp_placeoforigin_defraimp_watchlist_PlaceOfOriginId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defraimp_placeoforigin_defraimp_watchlist_PlaceOfOriginId");
				this.SetRelatedEntity<Defra.Imports.Model.defraimp_placeoforigin>("defraimp_defraimp_placeoforigin_defraimp_watchlist_PlaceOfOriginId", null, value);
				this.OnPropertyChanged("defraimp_defraimp_placeoforigin_defraimp_watchlist_PlaceOfOriginId");
			}
		}
		
		/// <summary>
		/// N:1 defraimp_defraimp_transporter_defraimp_watchlist_TransporterId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_transporterid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defraimp_transporter_defraimp_watchlist_TransporterId")]
		public Defra.Imports.Model.defraimp_Transporter defraimp_defraimp_transporter_defraimp_watchlist_TransporterId
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.defraimp_Transporter>("defraimp_defraimp_transporter_defraimp_watchlist_TransporterId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defraimp_transporter_defraimp_watchlist_TransporterId");
				this.SetRelatedEntity<Defra.Imports.Model.defraimp_Transporter>("defraimp_defraimp_transporter_defraimp_watchlist_TransporterId", null, value);
				this.OnPropertyChanged("defraimp_defraimp_transporter_defraimp_watchlist_TransporterId");
			}
		}
		
		/// <summary>
		/// N:1 lk_defraimp_watchlist_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defraimp_watchlist_createdby")]
		public Defra.Imports.Model.SystemUser lk_defraimp_watchlist_createdby
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("lk_defraimp_watchlist_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_defraimp_watchlist_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defraimp_watchlist_createdonbehalfby")]
		public Defra.Imports.Model.SystemUser lk_defraimp_watchlist_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("lk_defraimp_watchlist_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_defraimp_watchlist_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defraimp_watchlist_modifiedby")]
		public Defra.Imports.Model.SystemUser lk_defraimp_watchlist_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("lk_defraimp_watchlist_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_defraimp_watchlist_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defraimp_watchlist_modifiedonbehalfby")]
		public Defra.Imports.Model.SystemUser lk_defraimp_watchlist_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("lk_defraimp_watchlist_modifiedonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 user_defraimp_watchlist
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_defraimp_watchlist")]
		public Defra.Imports.Model.SystemUser user_defraimp_watchlist
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("user_defraimp_watchlist", null);
			}
		}
	}
}
#pragma warning restore CS1591
