#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("defraimp_potentiallyrelatedimportrecords")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class defraimp_PotentiallyRelatedImportRecords : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the defraimp_potentiallyrelatedimportrecords entity
		/// </summary>
		public partial class Fields
		{
			public const string defraimp_importapplicationid = "defraimp_importapplicationid";
			public const string defraimp_matchrecordid = "defraimp_matchrecordid";
			public const string defraimp_PotentiallyRelatedImportRecordsId = "defraimp_potentiallyrelatedimportrecordsid";
			public const string Id = "defraimp_potentiallyrelatedimportrecordsid";
			public const string VersionNumber = "versionnumber";
			public const string defraimp_PotentiallyRelatedImportRecords1 = "defraimp_PotentiallyRelatedImportRecords";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public defraimp_PotentiallyRelatedImportRecords() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "defraimp_potentiallyrelatedimportrecords";
		
		public const string EntityLogicalCollectionName = null;
		
		public const string EntitySetName = "defraimp_potentiallyrelatedimportrecordsset";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_importapplicationid")]
		public System.Nullable<System.Guid> defraimp_importapplicationid
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("defraimp_importapplicationid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_matchrecordid")]
		public System.Nullable<System.Guid> defraimp_matchrecordid
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("defraimp_matchrecordid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_potentiallyrelatedimportrecordsid")]
		public System.Nullable<System.Guid> defraimp_PotentiallyRelatedImportRecordsId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("defraimp_potentiallyrelatedimportrecordsid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_potentiallyrelatedimportrecordsid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				base.Id = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:N defraimp_PotentiallyRelatedImportRecords
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_PotentiallyRelatedImportRecords")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_matchrecord> defraimp_PotentiallyRelatedImportRecords1
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_matchrecord>("defraimp_PotentiallyRelatedImportRecords", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_PotentiallyRelatedImportRecords1");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_matchrecord>("defraimp_PotentiallyRelatedImportRecords", null, value);
				this.OnPropertyChanged("defraimp_PotentiallyRelatedImportRecords1");
			}
		}
	}
}
#pragma warning restore CS1591
