#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("defraimp_importapplication_defra_country")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class defraimp_importapplication_defra_country : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the defraimp_importapplication_defra_country entity
		/// </summary>
		public partial class Fields
		{
			public const string defra_countryid = "defra_countryid";
			public const string defraimp_importapplication_defra_countryId = "defraimp_importapplication_defra_countryid";
			public const string Id = "defraimp_importapplication_defra_countryid";
			public const string defraimp_importapplicationid = "defraimp_importapplicationid";
			public const string VersionNumber = "versionnumber";
			public const string defraimp_defraimp_importapplication_defra_country = "defraimp_defraimp_importapplication_defra_country";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public defraimp_importapplication_defra_country() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "defraimp_importapplication_defra_country";
		
		public const string EntityLogicalCollectionName = null;
		
		public const string EntitySetName = "defraimp_importapplication_defra_countryset";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_countryid")]
		public System.Nullable<System.Guid> defra_countryid
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("defra_countryid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_importapplication_defra_countryid")]
		public System.Nullable<System.Guid> defraimp_importapplication_defra_countryId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("defraimp_importapplication_defra_countryid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_importapplication_defra_countryid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				base.Id = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_importapplicationid")]
		public System.Nullable<System.Guid> defraimp_importapplicationid
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("defraimp_importapplicationid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:N defraimp_defraimp_importapplication_defra_country
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defraimp_importapplication_defra_country")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_importapplication> defraimp_defraimp_importapplication_defra_country
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_importapplication>("defraimp_defraimp_importapplication_defra_country", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defraimp_importapplication_defra_country");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_importapplication>("defraimp_defraimp_importapplication_defra_country", null, value);
				this.OnPropertyChanged("defraimp_defraimp_importapplication_defra_country");
			}
		}
	}
}
#pragma warning restore CS1591
