#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	/// <summary>
	/// Status of the Consignee
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum defraimp_consignee_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Consignee
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum defraimp_consignee_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("defraimp_consignee")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class defraimp_Consignee : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the defraimp_consignee entity
		/// </summary>
		public partial class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string defraimp_AddressLine1 = "defraimp_addressline1";
			public const string defraimp_AddressLine2 = "defraimp_addressline2";
			public const string defraimp_AddressLine3 = "defraimp_addressline3";
			public const string defraimp_City = "defraimp_city";
			public const string defraimp_ConsigneeId = "defraimp_consigneeid";
			public const string Id = "defraimp_consigneeid";
			public const string defraimp_Country = "defraimp_country";
			public const string defraimp_Name = "defraimp_name";
			public const string defraimp_Postcode = "defraimp_postcode";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string defraimp_defraimp_consignee_defraimp_watchlist_ConsigneeId = "defraimp_defraimp_consignee_defraimp_watchlist_ConsigneeId";
			public const string defraimp_defra_country_defraimp_consignee_Country = "defraimp_defra_country_defraimp_consignee_Country";
			public const string lk_defraimp_consignee_createdby = "lk_defraimp_consignee_createdby";
			public const string lk_defraimp_consignee_createdonbehalfby = "lk_defraimp_consignee_createdonbehalfby";
			public const string lk_defraimp_consignee_modifiedby = "lk_defraimp_consignee_modifiedby";
			public const string lk_defraimp_consignee_modifiedonbehalfby = "lk_defraimp_consignee_modifiedonbehalfby";
			public const string user_defraimp_consignee = "user_defraimp_consignee";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public defraimp_Consignee() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "defraimp_consignee";
		
		public const string EntityLogicalCollectionName = "defraimp_consignees";
		
		public const string EntitySetName = "defraimp_consignees";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_addressline1")]
		public string defraimp_AddressLine1
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_addressline1");
			}
			set
			{
				this.OnPropertyChanging("defraimp_AddressLine1");
				this.SetAttributeValue("defraimp_addressline1", value);
				this.OnPropertyChanged("defraimp_AddressLine1");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_addressline2")]
		public string defraimp_AddressLine2
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_addressline2");
			}
			set
			{
				this.OnPropertyChanging("defraimp_AddressLine2");
				this.SetAttributeValue("defraimp_addressline2", value);
				this.OnPropertyChanged("defraimp_AddressLine2");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_addressline3")]
		public string defraimp_AddressLine3
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_addressline3");
			}
			set
			{
				this.OnPropertyChanging("defraimp_AddressLine3");
				this.SetAttributeValue("defraimp_addressline3", value);
				this.OnPropertyChanged("defraimp_AddressLine3");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_city")]
		public string defraimp_City
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_city");
			}
			set
			{
				this.OnPropertyChanging("defraimp_City");
				this.SetAttributeValue("defraimp_city", value);
				this.OnPropertyChanged("defraimp_City");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_consigneeid")]
		public System.Nullable<System.Guid> defraimp_ConsigneeId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("defraimp_consigneeid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ConsigneeId");
				this.SetAttributeValue("defraimp_consigneeid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("defraimp_ConsigneeId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_consigneeid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.defraimp_ConsigneeId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_country")]
		public Microsoft.Xrm.Sdk.EntityReference defraimp_Country
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defraimp_country");
			}
			set
			{
				this.OnPropertyChanging("defraimp_Country");
				this.SetAttributeValue("defraimp_country", value);
				this.OnPropertyChanged("defraimp_Country");
			}
		}
		
		/// <summary>
		/// Required name field
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_name")]
		public string defraimp_Name
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_name");
			}
			set
			{
				this.OnPropertyChanging("defraimp_Name");
				this.SetAttributeValue("defraimp_name", value);
				this.OnPropertyChanged("defraimp_Name");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_postcode")]
		public string defraimp_Postcode
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_postcode");
			}
			set
			{
				this.OnPropertyChanging("defraimp_Postcode");
				this.SetAttributeValue("defraimp_postcode", value);
				this.OnPropertyChanged("defraimp_Postcode");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Consignee
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual defraimp_consignee_statecode? statecode
		{
			get
			{
				return ((defraimp_consignee_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("statecode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statecode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Consignee
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual defraimp_consignee_statuscode? statuscode
		{
			get
			{
				return ((defraimp_consignee_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defraimp_consignee_defraimp_watchlist_ConsigneeId
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defraimp_consignee_defraimp_watchlist_ConsigneeId")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_WatchList> defraimp_defraimp_consignee_defraimp_watchlist_ConsigneeId
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_WatchList>("defraimp_defraimp_consignee_defraimp_watchlist_ConsigneeId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defraimp_consignee_defraimp_watchlist_ConsigneeId");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_WatchList>("defraimp_defraimp_consignee_defraimp_watchlist_ConsigneeId", null, value);
				this.OnPropertyChanged("defraimp_defraimp_consignee_defraimp_watchlist_ConsigneeId");
			}
		}
		
		/// <summary>
		/// N:1 defraimp_defra_country_defraimp_consignee_Country
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_country")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_consignee_Country")]
		public Defra.Imports.Model.defra_country defraimp_defra_country_defraimp_consignee_Country
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.defra_country>("defraimp_defra_country_defraimp_consignee_Country", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_consignee_Country");
				this.SetRelatedEntity<Defra.Imports.Model.defra_country>("defraimp_defra_country_defraimp_consignee_Country", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_consignee_Country");
			}
		}
		
		/// <summary>
		/// N:1 lk_defraimp_consignee_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defraimp_consignee_createdby")]
		public Defra.Imports.Model.SystemUser lk_defraimp_consignee_createdby
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("lk_defraimp_consignee_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_defraimp_consignee_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defraimp_consignee_createdonbehalfby")]
		public Defra.Imports.Model.SystemUser lk_defraimp_consignee_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("lk_defraimp_consignee_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_defraimp_consignee_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defraimp_consignee_modifiedby")]
		public Defra.Imports.Model.SystemUser lk_defraimp_consignee_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("lk_defraimp_consignee_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_defraimp_consignee_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defraimp_consignee_modifiedonbehalfby")]
		public Defra.Imports.Model.SystemUser lk_defraimp_consignee_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("lk_defraimp_consignee_modifiedonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 user_defraimp_consignee
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_defraimp_consignee")]
		public Defra.Imports.Model.SystemUser user_defraimp_consignee
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("user_defraimp_consignee", null);
			}
		}
	}
}
#pragma warning restore CS1591
