#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	/// <summary>
	/// Status of the ITAHC
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum defraimp_itahc_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the ITAHC
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum defraimp_itahc_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("defraimp_itahc")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class defraimp_itahc : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the defraimp_itahc entity
		/// </summary>
		public partial class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string defraimp_AnimalCertifiedAs = "defraimp_animalcertifiedas";
			public const string defraimp_CentralCompetentAuthority = "defraimp_centralcompetentauthority";
			public const string defraimp_CertificateStatus = "defraimp_certificatestatus";
			public const string defraimp_CertificateVersionNumber = "defraimp_certificateversionnumber";
			public const string defraimp_CommodityCode = "defraimp_commoditycode";
			public const string defraimp_CommodityComplementsText = "defraimp_commoditycomplementstext";
			public const string defraimp_CommodityIdTypes = "defraimp_commodityidtypes";
			public const string defraimp_CommodityType = "defraimp_commoditytype";
			public const string defraimp_ComplementId = "defraimp_complementid";
			public const string defraimp_ConsigneeAddressCity = "defraimp_consigneeaddresscity";
			public const string defraimp_ConsigneeAddressCountryId = "defraimp_consigneeaddresscountryid";
			public const string defraimp_ConsigneeAddressCountryISOCode = "defraimp_consigneeaddresscountryisocode";
			public const string defraimp_ConsigneeAddressPostcode = "defraimp_consigneeaddresspostcode";
			public const string defraimp_ConsigneeAddressStreet = "defraimp_consigneeaddressstreet";
			public const string defraimp_ConsigneeApprovalNumber = "defraimp_consigneeapprovalnumber";
			public const string defraimp_ConsigneeGeneralNumber = "defraimp_consigneegeneralnumber";
			public const string defraimp_ConsigneeName = "defraimp_consigneename";
			public const string defraimp_ConsigneeTracesId = "defraimp_consigneetracesid";
			public const string defraimp_ConsigneeType = "defraimp_consigneetype";
			public const string defraimp_ConsignorAddressCity = "defraimp_consignoraddresscity";
			public const string defraimp_ConsignorAddressCountryId = "defraimp_consignoraddresscountryid";
			public const string defraimp_ConsignorAddressCountryISOCode = "defraimp_consignoraddresscountryisocode";
			public const string defraimp_ConsignorAddressPostcode = "defraimp_consignoraddresspostcode";
			public const string defraimp_ConsignorAddressStreet = "defraimp_consignoraddressstreet";
			public const string defraimp_ConsignorApprovalNumber = "defraimp_consignorapprovalnumber";
			public const string defraimp_ConsignorGeneralNumber = "defraimp_consignorgeneralnumber";
			public const string defraimp_ConsignorName = "defraimp_consignorname";
			public const string defraimp_ConsignorTracesId = "defraimp_consignortracesid";
			public const string defraimp_ConsignorType = "defraimp_consignortype";
			public const string defraimp_CountryOfOriginId = "defraimp_countryoforiginid";
			public const string defraimp_CountryOfOriginISOCode = "defraimp_countryoforiginisocode";
			public const string defraimp_DeclarationEmail = "defraimp_declarationemail";
			public const string defraimp_DeclarationFax = "defraimp_declarationfax";
			public const string defraimp_DeclarationFirstName = "defraimp_declarationfirstname";
			public const string defraimp_DeclarationLastName = "defraimp_declarationlastname";
			public const string defraimp_DeclarationPhone = "defraimp_declarationphone";
			public const string defraimp_DeclarationSignatureDate = "defraimp_declarationsignaturedate";
			public const string defraimp_DepartureDateTime = "defraimp_departuredatetime";
			public const string defraimp_DevolvedOffice = "defraimp_devolvedoffice";
			public const string defraimp_EstimatedJourneyTime = "defraimp_estimatedjourneytime";
			public const string defraimp_FormattedCommodityComplementsText = "defraimp_formattedcommoditycomplementstext";
			public const string defraimp_formattedIdentificationOfAnimalsText = "defraimp_formattedidentificationofanimalstext";
			public const string defraimp_HasMultipleCommodities = "defraimp_hasmultiplecommodities";
			public const string defraimp_HealthCertificateNumber = "defraimp_healthcertificatenumber";
			public const string defraimp_IdentificationOfAnimalsText = "defraimp_identificationofanimalstext";
			public const string defraimp_itahcId = "defraimp_itahcid";
			public const string Id = "defraimp_itahcid";
			public const string defraimp_LocalCompetentAuthority = "defraimp_localcompetentauthority";
			public const string defraimp_LocalVeterinaryUnit = "defraimp_localveterinaryunit";
			public const string defraimp_LVUNo = "defraimp_lvuno";
			public const string defraimp_name = "defraimp_name";
			public const string defraimp_NumberOfPackages = "defraimp_numberofpackages";
			public const string defraimp_OfficialVetCapacity = "defraimp_officialvetcapacity";
			public const string defraimp_OfficialVetCompetentAuthority = "defraimp_officialvetcompetentauthority";
			public const string defraimp_OfficialVetEmail = "defraimp_officialvetemail";
			public const string defraimp_OfficialVetFax = "defraimp_officialvetfax";
			public const string defraimp_OfficialVetFirstName = "defraimp_officialvetfirstname";
			public const string defraimp_OfficialVetId = "defraimp_officialvetid";
			public const string defraimp_OfficialVetLastName = "defraimp_officialvetlastname";
			public const string defraimp_OfficialVetPhone = "defraimp_officialvetphone";
			public const string defraimp_OfficialVetSignatureDate = "defraimp_officialvetsignaturedate";
			public const string defraimp_OVName = "defraimp_ovname";
			public const string defraimp_PassportNumber = "defraimp_passportnumber";
			public const string defraimp_PlaceOfDestinationAddressCity = "defraimp_placeofdestinationaddresscity";
			public const string defraimp_PlaceOfDestinationAddressCountryId = "defraimp_placeofdestinationaddresscountryid";
			public const string defraimp_PlaceOfDestinationAddressCountryISOCode = "defraimp_placeofdestinationaddresscountryisocode";
			public const string defraimp_PlaceOfDestinationAddressPostcode = "defraimp_placeofdestinationaddresspostcode";
			public const string defraimp_PlaceOfDestinationAddressStreet = "defraimp_placeofdestinationaddressstreet";
			public const string defraimp_PlaceOfDestinationApprovalNumber = "defraimp_placeofdestinationapprovalnumber";
			public const string defraimp_PlaceOfDestinationGeneralNumber = "defraimp_placeofdestinationgeneralnumber";
			public const string defraimp_PlaceOfDestinationName = "defraimp_placeofdestinationname";
			public const string defraimp_PlaceOfDestinationTracesId = "defraimp_placeofdestinationtracesid";
			public const string defraimp_PlaceOfDestinationType = "defraimp_placeofdestinationtype";
			public const string defraimp_PlaceOfLoadingAddressCity = "defraimp_placeofloadingaddresscity";
			public const string defraimp_PlaceOfLoadingAddressCountryId = "defraimp_placeofloadingaddresscountryid";
			public const string defraimp_PlaceOfLoadingAddressCountryISOCode = "defraimp_placeofloadingaddresscountryisocode";
			public const string defraimp_PlaceOfLoadingAddressPostcode = "defraimp_placeofloadingaddresspostcode";
			public const string defraimp_PlaceOfLoadingAddressStreet = "defraimp_placeofloadingaddressstreet";
			public const string defraimp_PlaceOfLoadingApprovalNumber = "defraimp_placeofloadingapprovalnumber";
			public const string defraimp_PlaceOfLoadingGeneralNumber = "defraimp_placeofloadinggeneralnumber";
			public const string defraimp_PlaceOfLoadingName = "defraimp_placeofloadingname";
			public const string defraimp_PlaceOfLoadingTracesId = "defraimp_placeofloadingtracesid";
			public const string defraimp_PlaceOfLoadingType = "defraimp_placeofloadingtype";
			public const string defraimp_PlaceOfOriginHarvestAddressCity = "defraimp_placeoforiginharvestaddresscity";
			public const string defraimp_PlaceOfOriginHarvestAddressCountryId = "defraimp_placeoforiginharvestaddresscountryid";
			public const string defraimp_PlaceOfOriginHarvestAddressPostcode = "defraimp_placeoforiginharvestaddresspostcode";
			public const string defraimp_PlaceOfOriginHarvestAddressStreet = "defraimp_placeoforiginharvestaddressstreet";
			public const string defraimp_PlaceOfOriginHarvestApprovalNumber = "defraimp_placeoforiginharvestapprovalnumber";
			public const string defraimp_PlaceOfOriginHarvestGeneralNumber = "defraimp_placeoforiginharvestgeneralnumber";
			public const string defraimp_PlaceOfOriginHarvestName = "defraimp_placeoforiginharvestname";
			public const string defraimp_PlaceOfOriginHarvestTracesId = "defraimp_placeoforiginharvesttracesid";
			public const string defraimp_PlaceOfOriginHarvestType = "defraimp_placeoforiginharvesttype";
			public const string defraimp_Purpose = "defraimp_purpose";
			public const string defraimp_Quantity = "defraimp_quantity";
			public const string defraimp_RelatedImportRecord = "defraimp_relatedimportrecord";
			public const string defraimp_ReplacedById = "defraimp_replacedbyid";
			public const string defraimp_ReplacedReferenceNumber = "defraimp_replacedreferencenumber";
			public const string defraimp_ReplacesId = "defraimp_replacesid";
			public const string defraimp_ReplacingReferenceNumber = "defraimp_replacingreferencenumber";
			public const string defraimp_SpeciesClass = "defraimp_speciesclass";
			public const string defraimp_SpeciesId = "defraimp_speciesid";
			public const string defraimp_SpeciesModel = "defraimp_speciesmodel";
			public const string defraimp_SpeciesNomination = "defraimp_speciesnomination";
			public const string defraimp_SpeciesType = "defraimp_speciestype";
			public const string defraimp_TRACESReceivedDate = "defraimp_tracesreceiveddate";
			public const string defraimp_TransporterAddressCity = "defraimp_transporteraddresscity";
			public const string defraimp_TransporterAddressCountryId = "defraimp_transporteraddresscountryid";
			public const string defraimp_TransporterAddressCountryISOCode = "defraimp_transporteraddresscountryisocode";
			public const string defraimp_TransporterAddressPostcode = "defraimp_transporteraddresspostcode";
			public const string defraimp_TransporterAddressStreet = "defraimp_transporteraddressstreet";
			public const string defraimp_TransporterApprovalNumber = "defraimp_transporterapprovalnumber";
			public const string defraimp_TransporterGeneralNumber = "defraimp_transportergeneralnumber";
			public const string defraimp_TransporterName = "defraimp_transportername";
			public const string defraimp_TransporterTracesId = "defraimp_transportertracesid";
			public const string defraimp_TransporterType = "defraimp_transportertype";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string defraimp_defraimp_itahc_defraimp_importapplication = "defraimp_defraimp_itahc_defraimp_importapplication";
			public const string defraimp_defraimp_itahc_defraimp_importinspection_RelatedITAHC = "defraimp_defraimp_itahc_defraimp_importinspection_RelatedITAHC";
			public const string defraimp_defraimp_itahc_defraimp_importquery_ITAHC = "defraimp_defraimp_itahc_defraimp_importquery_ITAHC";
			public const string Referenceddefraimp_defraimp_itahc_defraimp_itahc = "Referenceddefraimp_defraimp_itahc_defraimp_itahc";
			public const string defraimp_defraimp_itahc_defraimp_matchrecord_ITAHC = "defraimp_defraimp_itahc_defraimp_matchrecord_ITAHC";
			public const string Referenceddefraimp_defraimp_itahc_defraimp_rb = "Referenceddefraimp_defraimp_itahc_defraimp_rb";
			public const string defraimp_defraimp_itahc_defraimp_watchflag_ItahcId = "defraimp_defraimp_itahc_defraimp_watchflag_ItahcId";
			public const string defraimp_itahc_Annotations = "defraimp_itahc_Annotations";
			public const string defraimp_defraimp_importapplication_defraimp_itahc = "defraimp_defraimp_importapplication_defraimp_itahc";
			public const string defraimp_defra_country_defraimp_itahc_ConsigneeAddressCountryId = "defraimp_defra_country_defraimp_itahc_ConsigneeAddressCountryId";
			public const string defraimp_defra_country_defraimp_itahc_ConsignorAddressCountryId = "defraimp_defra_country_defraimp_itahc_ConsignorAddressCountryId";
			public const string defraimp_defra_country_defraimp_itahc_CountryOfOriginId = "defraimp_defra_country_defraimp_itahc_CountryOfOriginId";
			public const string defraimp_defra_country_defraimp_itahc_PlaceOfDestinationAddressCountryId = "defraimp_defra_country_defraimp_itahc_PlaceOfDestinationAddressCountryId";
			public const string defraimp_defra_country_defraimp_itahc_PlaceOfLoadingAddressCountryId = "defraimp_defra_country_defraimp_itahc_PlaceOfLoadingAddressCountryId";
			public const string defraimp_defra_country_defraimp_itahc_PlaceOfOriginHarvestAddressCountryId = "defraimp_defra_country_defraimp_itahc_PlaceOfOriginHarvestAddressCountryId";
			public const string defraimp_defra_country_defraimp_itahc_TransporterAddressCountryId = "defraimp_defra_country_defraimp_itahc_TransporterAddressCountryId";
			public const string Referencingdefraimp_defraimp_itahc_defraimp_itahc = "defraimp_defraimp_itahc_defraimp_itahc";
			public const string Referencingdefraimp_defraimp_itahc_defraimp_rb = "defraimp_defraimp_itahc_defraimp_rb";
			public const string lk_defraimp_itahc_createdby = "lk_defraimp_itahc_createdby";
			public const string lk_defraimp_itahc_createdonbehalfby = "lk_defraimp_itahc_createdonbehalfby";
			public const string lk_defraimp_itahc_modifiedby = "lk_defraimp_itahc_modifiedby";
			public const string lk_defraimp_itahc_modifiedonbehalfby = "lk_defraimp_itahc_modifiedonbehalfby";
			public const string user_defraimp_itahc = "user_defraimp_itahc";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public defraimp_itahc() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "defraimp_itahc";
		
		public const string EntityLogicalCollectionName = "defraimp_itahcs";
		
		public const string EntitySetName = "defraimp_itahcs";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_animalcertifiedas")]
		public virtual defraimp_animalcertifiedas? defraimp_AnimalCertifiedAs
		{
			get
			{
				return ((defraimp_animalcertifiedas?)(EntityOptionSetEnum.GetEnum(this, "defraimp_animalcertifiedas")));
			}
			set
			{
				this.OnPropertyChanging("defraimp_AnimalCertifiedAs");
				this.SetAttributeValue("defraimp_animalcertifiedas", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("defraimp_AnimalCertifiedAs");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_centralcompetentauthority")]
		public string defraimp_CentralCompetentAuthority
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_centralcompetentauthority");
			}
			set
			{
				this.OnPropertyChanging("defraimp_CentralCompetentAuthority");
				this.SetAttributeValue("defraimp_centralcompetentauthority", value);
				this.OnPropertyChanged("defraimp_CentralCompetentAuthority");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_certificatestatus")]
		public virtual defraimp_certificatestatus? defraimp_CertificateStatus
		{
			get
			{
				return ((defraimp_certificatestatus?)(EntityOptionSetEnum.GetEnum(this, "defraimp_certificatestatus")));
			}
			set
			{
				this.OnPropertyChanging("defraimp_CertificateStatus");
				this.SetAttributeValue("defraimp_certificatestatus", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("defraimp_CertificateStatus");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_certificateversionnumber")]
		public System.Nullable<int> defraimp_CertificateVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("defraimp_certificateversionnumber");
			}
			set
			{
				this.OnPropertyChanging("defraimp_CertificateVersionNumber");
				this.SetAttributeValue("defraimp_certificateversionnumber", value);
				this.OnPropertyChanged("defraimp_CertificateVersionNumber");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_commoditycode")]
		public string defraimp_CommodityCode
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_commoditycode");
			}
			set
			{
				this.OnPropertyChanging("defraimp_CommodityCode");
				this.SetAttributeValue("defraimp_commoditycode", value);
				this.OnPropertyChanged("defraimp_CommodityCode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_commoditycomplementstext")]
		public string defraimp_CommodityComplementsText
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_commoditycomplementstext");
			}
			set
			{
				this.OnPropertyChanging("defraimp_CommodityComplementsText");
				this.SetAttributeValue("defraimp_commoditycomplementstext", value);
				this.OnPropertyChanged("defraimp_CommodityComplementsText");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_commodityidtypes")]
		public string defraimp_CommodityIdTypes
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_commodityidtypes");
			}
			set
			{
				this.OnPropertyChanging("defraimp_CommodityIdTypes");
				this.SetAttributeValue("defraimp_commodityidtypes", value);
				this.OnPropertyChanged("defraimp_CommodityIdTypes");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_commoditytype")]
		public Microsoft.Xrm.Sdk.EntityReference defraimp_CommodityType
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defraimp_commoditytype");
			}
			set
			{
				this.OnPropertyChanging("defraimp_CommodityType");
				this.SetAttributeValue("defraimp_commoditytype", value);
				this.OnPropertyChanged("defraimp_CommodityType");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_complementid")]
		public string defraimp_ComplementId
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_complementid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ComplementId");
				this.SetAttributeValue("defraimp_complementid", value);
				this.OnPropertyChanged("defraimp_ComplementId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_consigneeaddresscity")]
		public string defraimp_ConsigneeAddressCity
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_consigneeaddresscity");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ConsigneeAddressCity");
				this.SetAttributeValue("defraimp_consigneeaddresscity", value);
				this.OnPropertyChanged("defraimp_ConsigneeAddressCity");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_consigneeaddresscountryid")]
		public Microsoft.Xrm.Sdk.EntityReference defraimp_ConsigneeAddressCountryId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defraimp_consigneeaddresscountryid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ConsigneeAddressCountryId");
				this.SetAttributeValue("defraimp_consigneeaddresscountryid", value);
				this.OnPropertyChanged("defraimp_ConsigneeAddressCountryId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_consigneeaddresscountryisocode")]
		public string defraimp_ConsigneeAddressCountryISOCode
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_consigneeaddresscountryisocode");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ConsigneeAddressCountryISOCode");
				this.SetAttributeValue("defraimp_consigneeaddresscountryisocode", value);
				this.OnPropertyChanged("defraimp_ConsigneeAddressCountryISOCode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_consigneeaddresspostcode")]
		public string defraimp_ConsigneeAddressPostcode
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_consigneeaddresspostcode");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ConsigneeAddressPostcode");
				this.SetAttributeValue("defraimp_consigneeaddresspostcode", value);
				this.OnPropertyChanged("defraimp_ConsigneeAddressPostcode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_consigneeaddressstreet")]
		public string defraimp_ConsigneeAddressStreet
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_consigneeaddressstreet");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ConsigneeAddressStreet");
				this.SetAttributeValue("defraimp_consigneeaddressstreet", value);
				this.OnPropertyChanged("defraimp_ConsigneeAddressStreet");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_consigneeapprovalnumber")]
		public string defraimp_ConsigneeApprovalNumber
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_consigneeapprovalnumber");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ConsigneeApprovalNumber");
				this.SetAttributeValue("defraimp_consigneeapprovalnumber", value);
				this.OnPropertyChanged("defraimp_ConsigneeApprovalNumber");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_consigneegeneralnumber")]
		public string defraimp_ConsigneeGeneralNumber
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_consigneegeneralnumber");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ConsigneeGeneralNumber");
				this.SetAttributeValue("defraimp_consigneegeneralnumber", value);
				this.OnPropertyChanged("defraimp_ConsigneeGeneralNumber");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_consigneename")]
		public string defraimp_ConsigneeName
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_consigneename");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ConsigneeName");
				this.SetAttributeValue("defraimp_consigneename", value);
				this.OnPropertyChanged("defraimp_ConsigneeName");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_consigneetracesid")]
		public System.Nullable<int> defraimp_ConsigneeTracesId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("defraimp_consigneetracesid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ConsigneeTracesId");
				this.SetAttributeValue("defraimp_consigneetracesid", value);
				this.OnPropertyChanged("defraimp_ConsigneeTracesId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_consigneetype")]
		public string defraimp_ConsigneeType
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_consigneetype");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ConsigneeType");
				this.SetAttributeValue("defraimp_consigneetype", value);
				this.OnPropertyChanged("defraimp_ConsigneeType");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_consignoraddresscity")]
		public string defraimp_ConsignorAddressCity
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_consignoraddresscity");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ConsignorAddressCity");
				this.SetAttributeValue("defraimp_consignoraddresscity", value);
				this.OnPropertyChanged("defraimp_ConsignorAddressCity");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_consignoraddresscountryid")]
		public Microsoft.Xrm.Sdk.EntityReference defraimp_ConsignorAddressCountryId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defraimp_consignoraddresscountryid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ConsignorAddressCountryId");
				this.SetAttributeValue("defraimp_consignoraddresscountryid", value);
				this.OnPropertyChanged("defraimp_ConsignorAddressCountryId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_consignoraddresscountryisocode")]
		public string defraimp_ConsignorAddressCountryISOCode
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_consignoraddresscountryisocode");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ConsignorAddressCountryISOCode");
				this.SetAttributeValue("defraimp_consignoraddresscountryisocode", value);
				this.OnPropertyChanged("defraimp_ConsignorAddressCountryISOCode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_consignoraddresspostcode")]
		public string defraimp_ConsignorAddressPostcode
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_consignoraddresspostcode");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ConsignorAddressPostcode");
				this.SetAttributeValue("defraimp_consignoraddresspostcode", value);
				this.OnPropertyChanged("defraimp_ConsignorAddressPostcode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_consignoraddressstreet")]
		public string defraimp_ConsignorAddressStreet
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_consignoraddressstreet");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ConsignorAddressStreet");
				this.SetAttributeValue("defraimp_consignoraddressstreet", value);
				this.OnPropertyChanged("defraimp_ConsignorAddressStreet");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_consignorapprovalnumber")]
		public string defraimp_ConsignorApprovalNumber
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_consignorapprovalnumber");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ConsignorApprovalNumber");
				this.SetAttributeValue("defraimp_consignorapprovalnumber", value);
				this.OnPropertyChanged("defraimp_ConsignorApprovalNumber");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_consignorgeneralnumber")]
		public string defraimp_ConsignorGeneralNumber
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_consignorgeneralnumber");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ConsignorGeneralNumber");
				this.SetAttributeValue("defraimp_consignorgeneralnumber", value);
				this.OnPropertyChanged("defraimp_ConsignorGeneralNumber");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_consignorname")]
		public string defraimp_ConsignorName
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_consignorname");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ConsignorName");
				this.SetAttributeValue("defraimp_consignorname", value);
				this.OnPropertyChanged("defraimp_ConsignorName");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_consignortracesid")]
		public System.Nullable<int> defraimp_ConsignorTracesId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("defraimp_consignortracesid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ConsignorTracesId");
				this.SetAttributeValue("defraimp_consignortracesid", value);
				this.OnPropertyChanged("defraimp_ConsignorTracesId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_consignortype")]
		public string defraimp_ConsignorType
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_consignortype");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ConsignorType");
				this.SetAttributeValue("defraimp_consignortype", value);
				this.OnPropertyChanged("defraimp_ConsignorType");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_countryoforiginid")]
		public Microsoft.Xrm.Sdk.EntityReference defraimp_CountryOfOriginId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defraimp_countryoforiginid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_CountryOfOriginId");
				this.SetAttributeValue("defraimp_countryoforiginid", value);
				this.OnPropertyChanged("defraimp_CountryOfOriginId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_countryoforiginisocode")]
		public string defraimp_CountryOfOriginISOCode
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_countryoforiginisocode");
			}
			set
			{
				this.OnPropertyChanging("defraimp_CountryOfOriginISOCode");
				this.SetAttributeValue("defraimp_countryoforiginisocode", value);
				this.OnPropertyChanged("defraimp_CountryOfOriginISOCode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_declarationemail")]
		public string defraimp_DeclarationEmail
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_declarationemail");
			}
			set
			{
				this.OnPropertyChanging("defraimp_DeclarationEmail");
				this.SetAttributeValue("defraimp_declarationemail", value);
				this.OnPropertyChanged("defraimp_DeclarationEmail");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_declarationfax")]
		public string defraimp_DeclarationFax
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_declarationfax");
			}
			set
			{
				this.OnPropertyChanging("defraimp_DeclarationFax");
				this.SetAttributeValue("defraimp_declarationfax", value);
				this.OnPropertyChanged("defraimp_DeclarationFax");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_declarationfirstname")]
		public string defraimp_DeclarationFirstName
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_declarationfirstname");
			}
			set
			{
				this.OnPropertyChanging("defraimp_DeclarationFirstName");
				this.SetAttributeValue("defraimp_declarationfirstname", value);
				this.OnPropertyChanged("defraimp_DeclarationFirstName");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_declarationlastname")]
		public string defraimp_DeclarationLastName
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_declarationlastname");
			}
			set
			{
				this.OnPropertyChanging("defraimp_DeclarationLastName");
				this.SetAttributeValue("defraimp_declarationlastname", value);
				this.OnPropertyChanged("defraimp_DeclarationLastName");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_declarationphone")]
		public string defraimp_DeclarationPhone
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_declarationphone");
			}
			set
			{
				this.OnPropertyChanging("defraimp_DeclarationPhone");
				this.SetAttributeValue("defraimp_declarationphone", value);
				this.OnPropertyChanged("defraimp_DeclarationPhone");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_declarationsignaturedate")]
		public System.Nullable<System.DateTime> defraimp_DeclarationSignatureDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("defraimp_declarationsignaturedate");
			}
			set
			{
				this.OnPropertyChanging("defraimp_DeclarationSignatureDate");
				this.SetAttributeValue("defraimp_declarationsignaturedate", value);
				this.OnPropertyChanged("defraimp_DeclarationSignatureDate");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_departuredatetime")]
		public System.Nullable<System.DateTime> defraimp_DepartureDateTime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("defraimp_departuredatetime");
			}
			set
			{
				this.OnPropertyChanging("defraimp_DepartureDateTime");
				this.SetAttributeValue("defraimp_departuredatetime", value);
				this.OnPropertyChanged("defraimp_DepartureDateTime");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_devolvedoffice")]
		public Microsoft.Xrm.Sdk.EntityReference defraimp_DevolvedOffice
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defraimp_devolvedoffice");
			}
			set
			{
				this.OnPropertyChanging("defraimp_DevolvedOffice");
				this.SetAttributeValue("defraimp_devolvedoffice", value);
				this.OnPropertyChanged("defraimp_DevolvedOffice");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_estimatedjourneytime")]
		public System.Nullable<decimal> defraimp_EstimatedJourneyTime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("defraimp_estimatedjourneytime");
			}
			set
			{
				this.OnPropertyChanging("defraimp_EstimatedJourneyTime");
				this.SetAttributeValue("defraimp_estimatedjourneytime", value);
				this.OnPropertyChanged("defraimp_EstimatedJourneyTime");
			}
		}
		
		/// <summary>
		/// Field to store the formatted values from the JSON data from Commodity Complements Text
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_formattedcommoditycomplementstext")]
		public string defraimp_FormattedCommodityComplementsText
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_formattedcommoditycomplementstext");
			}
			set
			{
				this.OnPropertyChanging("defraimp_FormattedCommodityComplementsText");
				this.SetAttributeValue("defraimp_formattedcommoditycomplementstext", value);
				this.OnPropertyChanged("defraimp_FormattedCommodityComplementsText");
			}
		}
		
		/// <summary>
		/// Field to store the formatted values from JSON data of Identification Of Animals Text
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_formattedidentificationofanimalstext")]
		public string defraimp_formattedIdentificationOfAnimalsText
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_formattedidentificationofanimalstext");
			}
			set
			{
				this.OnPropertyChanging("defraimp_formattedIdentificationOfAnimalsText");
				this.SetAttributeValue("defraimp_formattedidentificationofanimalstext", value);
				this.OnPropertyChanged("defraimp_formattedIdentificationOfAnimalsText");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_hasmultiplecommodities")]
		public System.Nullable<bool> defraimp_HasMultipleCommodities
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("defraimp_hasmultiplecommodities");
			}
			set
			{
				this.OnPropertyChanging("defraimp_HasMultipleCommodities");
				this.SetAttributeValue("defraimp_hasmultiplecommodities", value);
				this.OnPropertyChanged("defraimp_HasMultipleCommodities");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_healthcertificatenumber")]
		public string defraimp_HealthCertificateNumber
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_healthcertificatenumber");
			}
			set
			{
				this.OnPropertyChanging("defraimp_HealthCertificateNumber");
				this.SetAttributeValue("defraimp_healthcertificatenumber", value);
				this.OnPropertyChanged("defraimp_HealthCertificateNumber");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_identificationofanimalstext")]
		public string defraimp_IdentificationOfAnimalsText
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_identificationofanimalstext");
			}
			set
			{
				this.OnPropertyChanging("defraimp_IdentificationOfAnimalsText");
				this.SetAttributeValue("defraimp_identificationofanimalstext", value);
				this.OnPropertyChanged("defraimp_IdentificationOfAnimalsText");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_itahcid")]
		public System.Nullable<System.Guid> defraimp_itahcId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("defraimp_itahcid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_itahcId");
				this.SetAttributeValue("defraimp_itahcid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("defraimp_itahcId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_itahcid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.defraimp_itahcId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_localcompetentauthority")]
		public string defraimp_LocalCompetentAuthority
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_localcompetentauthority");
			}
			set
			{
				this.OnPropertyChanging("defraimp_LocalCompetentAuthority");
				this.SetAttributeValue("defraimp_localcompetentauthority", value);
				this.OnPropertyChanged("defraimp_LocalCompetentAuthority");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_localveterinaryunit")]
		public string defraimp_LocalVeterinaryUnit
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_localveterinaryunit");
			}
			set
			{
				this.OnPropertyChanging("defraimp_LocalVeterinaryUnit");
				this.SetAttributeValue("defraimp_localveterinaryunit", value);
				this.OnPropertyChanged("defraimp_LocalVeterinaryUnit");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_lvuno")]
		public string defraimp_LVUNo
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_lvuno");
			}
			set
			{
				this.OnPropertyChanging("defraimp_LVUNo");
				this.SetAttributeValue("defraimp_lvuno", value);
				this.OnPropertyChanged("defraimp_LVUNo");
			}
		}
		
		/// <summary>
		/// The certificate number, for example: INTRA.HU.2019.0123456
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_name")]
		public string defraimp_name
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_name");
			}
			set
			{
				this.OnPropertyChanging("defraimp_name");
				this.SetAttributeValue("defraimp_name", value);
				this.OnPropertyChanged("defraimp_name");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_numberofpackages")]
		public System.Nullable<int> defraimp_NumberOfPackages
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("defraimp_numberofpackages");
			}
			set
			{
				this.OnPropertyChanging("defraimp_NumberOfPackages");
				this.SetAttributeValue("defraimp_numberofpackages", value);
				this.OnPropertyChanged("defraimp_NumberOfPackages");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_officialvetcapacity")]
		public virtual defraimp_officialvetcapacity? defraimp_OfficialVetCapacity
		{
			get
			{
				return ((defraimp_officialvetcapacity?)(EntityOptionSetEnum.GetEnum(this, "defraimp_officialvetcapacity")));
			}
			set
			{
				this.OnPropertyChanging("defraimp_OfficialVetCapacity");
				this.SetAttributeValue("defraimp_officialvetcapacity", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("defraimp_OfficialVetCapacity");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_officialvetcompetentauthority")]
		public string defraimp_OfficialVetCompetentAuthority
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_officialvetcompetentauthority");
			}
			set
			{
				this.OnPropertyChanging("defraimp_OfficialVetCompetentAuthority");
				this.SetAttributeValue("defraimp_officialvetcompetentauthority", value);
				this.OnPropertyChanged("defraimp_OfficialVetCompetentAuthority");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_officialvetemail")]
		public string defraimp_OfficialVetEmail
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_officialvetemail");
			}
			set
			{
				this.OnPropertyChanging("defraimp_OfficialVetEmail");
				this.SetAttributeValue("defraimp_officialvetemail", value);
				this.OnPropertyChanged("defraimp_OfficialVetEmail");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_officialvetfax")]
		public string defraimp_OfficialVetFax
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_officialvetfax");
			}
			set
			{
				this.OnPropertyChanging("defraimp_OfficialVetFax");
				this.SetAttributeValue("defraimp_officialvetfax", value);
				this.OnPropertyChanged("defraimp_OfficialVetFax");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_officialvetfirstname")]
		public string defraimp_OfficialVetFirstName
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_officialvetfirstname");
			}
			set
			{
				this.OnPropertyChanging("defraimp_OfficialVetFirstName");
				this.SetAttributeValue("defraimp_officialvetfirstname", value);
				this.OnPropertyChanged("defraimp_OfficialVetFirstName");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_officialvetid")]
		public System.Nullable<int> defraimp_OfficialVetId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("defraimp_officialvetid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_OfficialVetId");
				this.SetAttributeValue("defraimp_officialvetid", value);
				this.OnPropertyChanged("defraimp_OfficialVetId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_officialvetlastname")]
		public string defraimp_OfficialVetLastName
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_officialvetlastname");
			}
			set
			{
				this.OnPropertyChanging("defraimp_OfficialVetLastName");
				this.SetAttributeValue("defraimp_officialvetlastname", value);
				this.OnPropertyChanged("defraimp_OfficialVetLastName");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_officialvetphone")]
		public string defraimp_OfficialVetPhone
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_officialvetphone");
			}
			set
			{
				this.OnPropertyChanging("defraimp_OfficialVetPhone");
				this.SetAttributeValue("defraimp_officialvetphone", value);
				this.OnPropertyChanged("defraimp_OfficialVetPhone");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_officialvetsignaturedate")]
		public System.Nullable<System.DateTime> defraimp_OfficialVetSignatureDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("defraimp_officialvetsignaturedate");
			}
			set
			{
				this.OnPropertyChanging("defraimp_OfficialVetSignatureDate");
				this.SetAttributeValue("defraimp_officialvetsignaturedate", value);
				this.OnPropertyChanged("defraimp_OfficialVetSignatureDate");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_ovname")]
		public string defraimp_OVName
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_ovname");
			}
			set
			{
				this.OnPropertyChanging("defraimp_OVName");
				this.SetAttributeValue("defraimp_ovname", value);
				this.OnPropertyChanged("defraimp_OVName");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_passportnumber")]
		public string defraimp_PassportNumber
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_passportnumber");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PassportNumber");
				this.SetAttributeValue("defraimp_passportnumber", value);
				this.OnPropertyChanged("defraimp_PassportNumber");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeofdestinationaddresscity")]
		public string defraimp_PlaceOfDestinationAddressCity
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_placeofdestinationaddresscity");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PlaceOfDestinationAddressCity");
				this.SetAttributeValue("defraimp_placeofdestinationaddresscity", value);
				this.OnPropertyChanged("defraimp_PlaceOfDestinationAddressCity");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeofdestinationaddresscountryid")]
		public Microsoft.Xrm.Sdk.EntityReference defraimp_PlaceOfDestinationAddressCountryId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defraimp_placeofdestinationaddresscountryid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PlaceOfDestinationAddressCountryId");
				this.SetAttributeValue("defraimp_placeofdestinationaddresscountryid", value);
				this.OnPropertyChanged("defraimp_PlaceOfDestinationAddressCountryId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeofdestinationaddresscountryisocode")]
		public string defraimp_PlaceOfDestinationAddressCountryISOCode
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_placeofdestinationaddresscountryisocode");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PlaceOfDestinationAddressCountryISOCode");
				this.SetAttributeValue("defraimp_placeofdestinationaddresscountryisocode", value);
				this.OnPropertyChanged("defraimp_PlaceOfDestinationAddressCountryISOCode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeofdestinationaddresspostcode")]
		public string defraimp_PlaceOfDestinationAddressPostcode
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_placeofdestinationaddresspostcode");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PlaceOfDestinationAddressPostcode");
				this.SetAttributeValue("defraimp_placeofdestinationaddresspostcode", value);
				this.OnPropertyChanged("defraimp_PlaceOfDestinationAddressPostcode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeofdestinationaddressstreet")]
		public string defraimp_PlaceOfDestinationAddressStreet
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_placeofdestinationaddressstreet");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PlaceOfDestinationAddressStreet");
				this.SetAttributeValue("defraimp_placeofdestinationaddressstreet", value);
				this.OnPropertyChanged("defraimp_PlaceOfDestinationAddressStreet");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeofdestinationapprovalnumber")]
		public string defraimp_PlaceOfDestinationApprovalNumber
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_placeofdestinationapprovalnumber");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PlaceOfDestinationApprovalNumber");
				this.SetAttributeValue("defraimp_placeofdestinationapprovalnumber", value);
				this.OnPropertyChanged("defraimp_PlaceOfDestinationApprovalNumber");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeofdestinationgeneralnumber")]
		public string defraimp_PlaceOfDestinationGeneralNumber
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_placeofdestinationgeneralnumber");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PlaceOfDestinationGeneralNumber");
				this.SetAttributeValue("defraimp_placeofdestinationgeneralnumber", value);
				this.OnPropertyChanged("defraimp_PlaceOfDestinationGeneralNumber");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeofdestinationname")]
		public string defraimp_PlaceOfDestinationName
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_placeofdestinationname");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PlaceOfDestinationName");
				this.SetAttributeValue("defraimp_placeofdestinationname", value);
				this.OnPropertyChanged("defraimp_PlaceOfDestinationName");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeofdestinationtracesid")]
		public System.Nullable<int> defraimp_PlaceOfDestinationTracesId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("defraimp_placeofdestinationtracesid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PlaceOfDestinationTracesId");
				this.SetAttributeValue("defraimp_placeofdestinationtracesid", value);
				this.OnPropertyChanged("defraimp_PlaceOfDestinationTracesId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeofdestinationtype")]
		public string defraimp_PlaceOfDestinationType
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_placeofdestinationtype");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PlaceOfDestinationType");
				this.SetAttributeValue("defraimp_placeofdestinationtype", value);
				this.OnPropertyChanged("defraimp_PlaceOfDestinationType");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeofloadingaddresscity")]
		public string defraimp_PlaceOfLoadingAddressCity
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_placeofloadingaddresscity");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PlaceOfLoadingAddressCity");
				this.SetAttributeValue("defraimp_placeofloadingaddresscity", value);
				this.OnPropertyChanged("defraimp_PlaceOfLoadingAddressCity");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeofloadingaddresscountryid")]
		public Microsoft.Xrm.Sdk.EntityReference defraimp_PlaceOfLoadingAddressCountryId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defraimp_placeofloadingaddresscountryid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PlaceOfLoadingAddressCountryId");
				this.SetAttributeValue("defraimp_placeofloadingaddresscountryid", value);
				this.OnPropertyChanged("defraimp_PlaceOfLoadingAddressCountryId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeofloadingaddresscountryisocode")]
		public string defraimp_PlaceOfLoadingAddressCountryISOCode
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_placeofloadingaddresscountryisocode");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PlaceOfLoadingAddressCountryISOCode");
				this.SetAttributeValue("defraimp_placeofloadingaddresscountryisocode", value);
				this.OnPropertyChanged("defraimp_PlaceOfLoadingAddressCountryISOCode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeofloadingaddresspostcode")]
		public string defraimp_PlaceOfLoadingAddressPostcode
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_placeofloadingaddresspostcode");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PlaceOfLoadingAddressPostcode");
				this.SetAttributeValue("defraimp_placeofloadingaddresspostcode", value);
				this.OnPropertyChanged("defraimp_PlaceOfLoadingAddressPostcode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeofloadingaddressstreet")]
		public string defraimp_PlaceOfLoadingAddressStreet
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_placeofloadingaddressstreet");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PlaceOfLoadingAddressStreet");
				this.SetAttributeValue("defraimp_placeofloadingaddressstreet", value);
				this.OnPropertyChanged("defraimp_PlaceOfLoadingAddressStreet");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeofloadingapprovalnumber")]
		public string defraimp_PlaceOfLoadingApprovalNumber
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_placeofloadingapprovalnumber");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PlaceOfLoadingApprovalNumber");
				this.SetAttributeValue("defraimp_placeofloadingapprovalnumber", value);
				this.OnPropertyChanged("defraimp_PlaceOfLoadingApprovalNumber");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeofloadinggeneralnumber")]
		public string defraimp_PlaceOfLoadingGeneralNumber
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_placeofloadinggeneralnumber");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PlaceOfLoadingGeneralNumber");
				this.SetAttributeValue("defraimp_placeofloadinggeneralnumber", value);
				this.OnPropertyChanged("defraimp_PlaceOfLoadingGeneralNumber");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeofloadingname")]
		public string defraimp_PlaceOfLoadingName
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_placeofloadingname");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PlaceOfLoadingName");
				this.SetAttributeValue("defraimp_placeofloadingname", value);
				this.OnPropertyChanged("defraimp_PlaceOfLoadingName");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeofloadingtracesid")]
		public System.Nullable<int> defraimp_PlaceOfLoadingTracesId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("defraimp_placeofloadingtracesid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PlaceOfLoadingTracesId");
				this.SetAttributeValue("defraimp_placeofloadingtracesid", value);
				this.OnPropertyChanged("defraimp_PlaceOfLoadingTracesId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeofloadingtype")]
		public string defraimp_PlaceOfLoadingType
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_placeofloadingtype");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PlaceOfLoadingType");
				this.SetAttributeValue("defraimp_placeofloadingtype", value);
				this.OnPropertyChanged("defraimp_PlaceOfLoadingType");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeoforiginharvestaddresscity")]
		public string defraimp_PlaceOfOriginHarvestAddressCity
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_placeoforiginharvestaddresscity");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PlaceOfOriginHarvestAddressCity");
				this.SetAttributeValue("defraimp_placeoforiginharvestaddresscity", value);
				this.OnPropertyChanged("defraimp_PlaceOfOriginHarvestAddressCity");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeoforiginharvestaddresscountryid")]
		public Microsoft.Xrm.Sdk.EntityReference defraimp_PlaceOfOriginHarvestAddressCountryId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defraimp_placeoforiginharvestaddresscountryid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PlaceOfOriginHarvestAddressCountryId");
				this.SetAttributeValue("defraimp_placeoforiginharvestaddresscountryid", value);
				this.OnPropertyChanged("defraimp_PlaceOfOriginHarvestAddressCountryId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeoforiginharvestaddresspostcode")]
		public string defraimp_PlaceOfOriginHarvestAddressPostcode
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_placeoforiginharvestaddresspostcode");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PlaceOfOriginHarvestAddressPostcode");
				this.SetAttributeValue("defraimp_placeoforiginharvestaddresspostcode", value);
				this.OnPropertyChanged("defraimp_PlaceOfOriginHarvestAddressPostcode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeoforiginharvestaddressstreet")]
		public string defraimp_PlaceOfOriginHarvestAddressStreet
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_placeoforiginharvestaddressstreet");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PlaceOfOriginHarvestAddressStreet");
				this.SetAttributeValue("defraimp_placeoforiginharvestaddressstreet", value);
				this.OnPropertyChanged("defraimp_PlaceOfOriginHarvestAddressStreet");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeoforiginharvestapprovalnumber")]
		public string defraimp_PlaceOfOriginHarvestApprovalNumber
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_placeoforiginharvestapprovalnumber");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PlaceOfOriginHarvestApprovalNumber");
				this.SetAttributeValue("defraimp_placeoforiginharvestapprovalnumber", value);
				this.OnPropertyChanged("defraimp_PlaceOfOriginHarvestApprovalNumber");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeoforiginharvestgeneralnumber")]
		public string defraimp_PlaceOfOriginHarvestGeneralNumber
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_placeoforiginharvestgeneralnumber");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PlaceOfOriginHarvestGeneralNumber");
				this.SetAttributeValue("defraimp_placeoforiginharvestgeneralnumber", value);
				this.OnPropertyChanged("defraimp_PlaceOfOriginHarvestGeneralNumber");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeoforiginharvestname")]
		public string defraimp_PlaceOfOriginHarvestName
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_placeoforiginharvestname");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PlaceOfOriginHarvestName");
				this.SetAttributeValue("defraimp_placeoforiginharvestname", value);
				this.OnPropertyChanged("defraimp_PlaceOfOriginHarvestName");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeoforiginharvesttracesid")]
		public System.Nullable<int> defraimp_PlaceOfOriginHarvestTracesId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("defraimp_placeoforiginharvesttracesid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PlaceOfOriginHarvestTracesId");
				this.SetAttributeValue("defraimp_placeoforiginharvesttracesid", value);
				this.OnPropertyChanged("defraimp_PlaceOfOriginHarvestTracesId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeoforiginharvesttype")]
		public string defraimp_PlaceOfOriginHarvestType
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_placeoforiginharvesttype");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PlaceOfOriginHarvestType");
				this.SetAttributeValue("defraimp_placeoforiginharvesttype", value);
				this.OnPropertyChanged("defraimp_PlaceOfOriginHarvestType");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_purpose")]
		public string defraimp_Purpose
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_purpose");
			}
			set
			{
				this.OnPropertyChanging("defraimp_Purpose");
				this.SetAttributeValue("defraimp_purpose", value);
				this.OnPropertyChanged("defraimp_Purpose");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_quantity")]
		public System.Nullable<decimal> defraimp_Quantity
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("defraimp_quantity");
			}
			set
			{
				this.OnPropertyChanging("defraimp_Quantity");
				this.SetAttributeValue("defraimp_quantity", value);
				this.OnPropertyChanged("defraimp_Quantity");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_relatedimportrecord")]
		public System.Nullable<bool> defraimp_RelatedImportRecord
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("defraimp_relatedimportrecord");
			}
			set
			{
				this.OnPropertyChanging("defraimp_RelatedImportRecord");
				this.SetAttributeValue("defraimp_relatedimportrecord", value);
				this.OnPropertyChanged("defraimp_RelatedImportRecord");
			}
		}
		
		/// <summary>
		/// Unique identifier for ITAHC associated with ITAHC.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_replacedbyid")]
		public Microsoft.Xrm.Sdk.EntityReference defraimp_ReplacedById
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defraimp_replacedbyid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ReplacedById");
				this.SetAttributeValue("defraimp_replacedbyid", value);
				this.OnPropertyChanged("defraimp_ReplacedById");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_replacedreferencenumber")]
		public string defraimp_ReplacedReferenceNumber
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_replacedreferencenumber");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ReplacedReferenceNumber");
				this.SetAttributeValue("defraimp_replacedreferencenumber", value);
				this.OnPropertyChanged("defraimp_ReplacedReferenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier for ITAHC associated with ITAHC.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_replacesid")]
		public Microsoft.Xrm.Sdk.EntityReference defraimp_ReplacesId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defraimp_replacesid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ReplacesId");
				this.SetAttributeValue("defraimp_replacesid", value);
				this.OnPropertyChanged("defraimp_ReplacesId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_replacingreferencenumber")]
		public string defraimp_ReplacingReferenceNumber
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_replacingreferencenumber");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ReplacingReferenceNumber");
				this.SetAttributeValue("defraimp_replacingreferencenumber", value);
				this.OnPropertyChanged("defraimp_ReplacingReferenceNumber");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_speciesclass")]
		public string defraimp_SpeciesClass
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_speciesclass");
			}
			set
			{
				this.OnPropertyChanging("defraimp_SpeciesClass");
				this.SetAttributeValue("defraimp_speciesclass", value);
				this.OnPropertyChanged("defraimp_SpeciesClass");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_speciesid")]
		public string defraimp_SpeciesId
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_speciesid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_SpeciesId");
				this.SetAttributeValue("defraimp_speciesid", value);
				this.OnPropertyChanged("defraimp_SpeciesId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_speciesmodel")]
		public string defraimp_SpeciesModel
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_speciesmodel");
			}
			set
			{
				this.OnPropertyChanging("defraimp_SpeciesModel");
				this.SetAttributeValue("defraimp_speciesmodel", value);
				this.OnPropertyChanged("defraimp_SpeciesModel");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_speciesnomination")]
		public string defraimp_SpeciesNomination
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_speciesnomination");
			}
			set
			{
				this.OnPropertyChanging("defraimp_SpeciesNomination");
				this.SetAttributeValue("defraimp_speciesnomination", value);
				this.OnPropertyChanged("defraimp_SpeciesNomination");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_speciestype")]
		public string defraimp_SpeciesType
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_speciestype");
			}
			set
			{
				this.OnPropertyChanging("defraimp_SpeciesType");
				this.SetAttributeValue("defraimp_speciestype", value);
				this.OnPropertyChanged("defraimp_SpeciesType");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_tracesreceiveddate")]
		public System.Nullable<System.DateTime> defraimp_TRACESReceivedDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("defraimp_tracesreceiveddate");
			}
			set
			{
				this.OnPropertyChanging("defraimp_TRACESReceivedDate");
				this.SetAttributeValue("defraimp_tracesreceiveddate", value);
				this.OnPropertyChanged("defraimp_TRACESReceivedDate");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_transporteraddresscity")]
		public string defraimp_TransporterAddressCity
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_transporteraddresscity");
			}
			set
			{
				this.OnPropertyChanging("defraimp_TransporterAddressCity");
				this.SetAttributeValue("defraimp_transporteraddresscity", value);
				this.OnPropertyChanged("defraimp_TransporterAddressCity");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_transporteraddresscountryid")]
		public Microsoft.Xrm.Sdk.EntityReference defraimp_TransporterAddressCountryId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defraimp_transporteraddresscountryid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_TransporterAddressCountryId");
				this.SetAttributeValue("defraimp_transporteraddresscountryid", value);
				this.OnPropertyChanged("defraimp_TransporterAddressCountryId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_transporteraddresscountryisocode")]
		public string defraimp_TransporterAddressCountryISOCode
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_transporteraddresscountryisocode");
			}
			set
			{
				this.OnPropertyChanging("defraimp_TransporterAddressCountryISOCode");
				this.SetAttributeValue("defraimp_transporteraddresscountryisocode", value);
				this.OnPropertyChanged("defraimp_TransporterAddressCountryISOCode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_transporteraddresspostcode")]
		public string defraimp_TransporterAddressPostcode
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_transporteraddresspostcode");
			}
			set
			{
				this.OnPropertyChanging("defraimp_TransporterAddressPostcode");
				this.SetAttributeValue("defraimp_transporteraddresspostcode", value);
				this.OnPropertyChanged("defraimp_TransporterAddressPostcode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_transporteraddressstreet")]
		public string defraimp_TransporterAddressStreet
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_transporteraddressstreet");
			}
			set
			{
				this.OnPropertyChanging("defraimp_TransporterAddressStreet");
				this.SetAttributeValue("defraimp_transporteraddressstreet", value);
				this.OnPropertyChanged("defraimp_TransporterAddressStreet");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_transporterapprovalnumber")]
		public string defraimp_TransporterApprovalNumber
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_transporterapprovalnumber");
			}
			set
			{
				this.OnPropertyChanging("defraimp_TransporterApprovalNumber");
				this.SetAttributeValue("defraimp_transporterapprovalnumber", value);
				this.OnPropertyChanged("defraimp_TransporterApprovalNumber");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_transportergeneralnumber")]
		public string defraimp_TransporterGeneralNumber
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_transportergeneralnumber");
			}
			set
			{
				this.OnPropertyChanging("defraimp_TransporterGeneralNumber");
				this.SetAttributeValue("defraimp_transportergeneralnumber", value);
				this.OnPropertyChanged("defraimp_TransporterGeneralNumber");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_transportername")]
		public string defraimp_TransporterName
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_transportername");
			}
			set
			{
				this.OnPropertyChanging("defraimp_TransporterName");
				this.SetAttributeValue("defraimp_transportername", value);
				this.OnPropertyChanged("defraimp_TransporterName");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_transportertracesid")]
		public System.Nullable<int> defraimp_TransporterTracesId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("defraimp_transportertracesid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_TransporterTracesId");
				this.SetAttributeValue("defraimp_transportertracesid", value);
				this.OnPropertyChanged("defraimp_TransporterTracesId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_transportertype")]
		public string defraimp_TransporterType
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_transportertype");
			}
			set
			{
				this.OnPropertyChanging("defraimp_TransporterType");
				this.SetAttributeValue("defraimp_transportertype", value);
				this.OnPropertyChanged("defraimp_TransporterType");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the ITAHC
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual defraimp_itahc_statecode? statecode
		{
			get
			{
				return ((defraimp_itahc_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("statecode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statecode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the ITAHC
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual defraimp_itahc_statuscode? statuscode
		{
			get
			{
				return ((defraimp_itahc_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defraimp_itahc_defraimp_importapplication
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defraimp_itahc_defraimp_importapplication")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_importapplication> defraimp_defraimp_itahc_defraimp_importapplication
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_importapplication>("defraimp_defraimp_itahc_defraimp_importapplication", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defraimp_itahc_defraimp_importapplication");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_importapplication>("defraimp_defraimp_itahc_defraimp_importapplication", null, value);
				this.OnPropertyChanged("defraimp_defraimp_itahc_defraimp_importapplication");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defraimp_itahc_defraimp_importinspection_RelatedITAHC
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defraimp_itahc_defraimp_importinspection_RelatedITAHC")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_importinspection> defraimp_defraimp_itahc_defraimp_importinspection_RelatedITAHC
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_importinspection>("defraimp_defraimp_itahc_defraimp_importinspection_RelatedITAHC", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defraimp_itahc_defraimp_importinspection_RelatedITAHC");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_importinspection>("defraimp_defraimp_itahc_defraimp_importinspection_RelatedITAHC", null, value);
				this.OnPropertyChanged("defraimp_defraimp_itahc_defraimp_importinspection_RelatedITAHC");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defraimp_itahc_defraimp_importquery_ITAHC
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defraimp_itahc_defraimp_importquery_ITAHC")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_importquery> defraimp_defraimp_itahc_defraimp_importquery_ITAHC
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_importquery>("defraimp_defraimp_itahc_defraimp_importquery_ITAHC", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defraimp_itahc_defraimp_importquery_ITAHC");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_importquery>("defraimp_defraimp_itahc_defraimp_importquery_ITAHC", null, value);
				this.OnPropertyChanged("defraimp_defraimp_itahc_defraimp_importquery_ITAHC");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defraimp_itahc_defraimp_itahc
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defraimp_itahc_defraimp_itahc", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_itahc> Referenceddefraimp_defraimp_itahc_defraimp_itahc
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_itahc>("defraimp_defraimp_itahc_defraimp_itahc", Microsoft.Xrm.Sdk.EntityRole.Referenced);
			}
			set
			{
				this.OnPropertyChanging("Referenceddefraimp_defraimp_itahc_defraimp_itahc");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_itahc>("defraimp_defraimp_itahc_defraimp_itahc", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
				this.OnPropertyChanged("Referenceddefraimp_defraimp_itahc_defraimp_itahc");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defraimp_itahc_defraimp_matchrecord_ITAHC
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defraimp_itahc_defraimp_matchrecord_ITAHC")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_matchrecord> defraimp_defraimp_itahc_defraimp_matchrecord_ITAHC
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_matchrecord>("defraimp_defraimp_itahc_defraimp_matchrecord_ITAHC", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defraimp_itahc_defraimp_matchrecord_ITAHC");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_matchrecord>("defraimp_defraimp_itahc_defraimp_matchrecord_ITAHC", null, value);
				this.OnPropertyChanged("defraimp_defraimp_itahc_defraimp_matchrecord_ITAHC");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defraimp_itahc_defraimp_rb
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defraimp_itahc_defraimp_rb", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_itahc> Referenceddefraimp_defraimp_itahc_defraimp_rb
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_itahc>("defraimp_defraimp_itahc_defraimp_rb", Microsoft.Xrm.Sdk.EntityRole.Referenced);
			}
			set
			{
				this.OnPropertyChanging("Referenceddefraimp_defraimp_itahc_defraimp_rb");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_itahc>("defraimp_defraimp_itahc_defraimp_rb", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
				this.OnPropertyChanged("Referenceddefraimp_defraimp_itahc_defraimp_rb");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defraimp_itahc_defraimp_watchflag_ItahcId
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defraimp_itahc_defraimp_watchflag_ItahcId")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_WatchFlag> defraimp_defraimp_itahc_defraimp_watchflag_ItahcId
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_WatchFlag>("defraimp_defraimp_itahc_defraimp_watchflag_ItahcId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defraimp_itahc_defraimp_watchflag_ItahcId");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_WatchFlag>("defraimp_defraimp_itahc_defraimp_watchflag_ItahcId", null, value);
				this.OnPropertyChanged("defraimp_defraimp_itahc_defraimp_watchflag_ItahcId");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_itahc_Annotations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_itahc_Annotations")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.Annotation> defraimp_itahc_Annotations
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.Annotation>("defraimp_itahc_Annotations", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_itahc_Annotations");
				this.SetRelatedEntities<Defra.Imports.Model.Annotation>("defraimp_itahc_Annotations", null, value);
				this.OnPropertyChanged("defraimp_itahc_Annotations");
			}
		}
		
		/// <summary>
		/// N:N defraimp_defraimp_importapplication_defraimp_itahc
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defraimp_importapplication_defraimp_itahc")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_importapplication> defraimp_defraimp_importapplication_defraimp_itahc
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_importapplication>("defraimp_defraimp_importapplication_defraimp_itahc", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defraimp_importapplication_defraimp_itahc");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_importapplication>("defraimp_defraimp_importapplication_defraimp_itahc", null, value);
				this.OnPropertyChanged("defraimp_defraimp_importapplication_defraimp_itahc");
			}
		}
		
		/// <summary>
		/// N:1 defraimp_defra_country_defraimp_itahc_ConsigneeAddressCountryId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_consigneeaddresscountryid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_itahc_ConsigneeAddressCountryId")]
		public Defra.Imports.Model.defra_country defraimp_defra_country_defraimp_itahc_ConsigneeAddressCountryId
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.defra_country>("defraimp_defra_country_defraimp_itahc_ConsigneeAddressCountryId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_itahc_ConsigneeAddressCountryId");
				this.SetRelatedEntity<Defra.Imports.Model.defra_country>("defraimp_defra_country_defraimp_itahc_ConsigneeAddressCountryId", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_itahc_ConsigneeAddressCountryId");
			}
		}
		
		/// <summary>
		/// N:1 defraimp_defra_country_defraimp_itahc_ConsignorAddressCountryId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_consignoraddresscountryid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_itahc_ConsignorAddressCountryId")]
		public Defra.Imports.Model.defra_country defraimp_defra_country_defraimp_itahc_ConsignorAddressCountryId
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.defra_country>("defraimp_defra_country_defraimp_itahc_ConsignorAddressCountryId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_itahc_ConsignorAddressCountryId");
				this.SetRelatedEntity<Defra.Imports.Model.defra_country>("defraimp_defra_country_defraimp_itahc_ConsignorAddressCountryId", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_itahc_ConsignorAddressCountryId");
			}
		}
		
		/// <summary>
		/// N:1 defraimp_defra_country_defraimp_itahc_CountryOfOriginId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_countryoforiginid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_itahc_CountryOfOriginId")]
		public Defra.Imports.Model.defra_country defraimp_defra_country_defraimp_itahc_CountryOfOriginId
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.defra_country>("defraimp_defra_country_defraimp_itahc_CountryOfOriginId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_itahc_CountryOfOriginId");
				this.SetRelatedEntity<Defra.Imports.Model.defra_country>("defraimp_defra_country_defraimp_itahc_CountryOfOriginId", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_itahc_CountryOfOriginId");
			}
		}
		
		/// <summary>
		/// N:1 defraimp_defra_country_defraimp_itahc_PlaceOfDestinationAddressCountryId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeofdestinationaddresscountryid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_itahc_PlaceOfDestinationAddressCountryId")]
		public Defra.Imports.Model.defra_country defraimp_defra_country_defraimp_itahc_PlaceOfDestinationAddressCountryId
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.defra_country>("defraimp_defra_country_defraimp_itahc_PlaceOfDestinationAddressCountryId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_itahc_PlaceOfDestinationAddressCountryId");
				this.SetRelatedEntity<Defra.Imports.Model.defra_country>("defraimp_defra_country_defraimp_itahc_PlaceOfDestinationAddressCountryId", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_itahc_PlaceOfDestinationAddressCountryId");
			}
		}
		
		/// <summary>
		/// N:1 defraimp_defra_country_defraimp_itahc_PlaceOfLoadingAddressCountryId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeofloadingaddresscountryid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_itahc_PlaceOfLoadingAddressCountryId")]
		public Defra.Imports.Model.defra_country defraimp_defra_country_defraimp_itahc_PlaceOfLoadingAddressCountryId
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.defra_country>("defraimp_defra_country_defraimp_itahc_PlaceOfLoadingAddressCountryId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_itahc_PlaceOfLoadingAddressCountryId");
				this.SetRelatedEntity<Defra.Imports.Model.defra_country>("defraimp_defra_country_defraimp_itahc_PlaceOfLoadingAddressCountryId", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_itahc_PlaceOfLoadingAddressCountryId");
			}
		}
		
		/// <summary>
		/// N:1 defraimp_defra_country_defraimp_itahc_PlaceOfOriginHarvestAddressCountryId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeoforiginharvestaddresscountryid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_itahc_PlaceOfOriginHarvestAddressCountryId")]
		public Defra.Imports.Model.defra_country defraimp_defra_country_defraimp_itahc_PlaceOfOriginHarvestAddressCountryId
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.defra_country>("defraimp_defra_country_defraimp_itahc_PlaceOfOriginHarvestAddressCountryId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_itahc_PlaceOfOriginHarvestAddressCountryId");
				this.SetRelatedEntity<Defra.Imports.Model.defra_country>("defraimp_defra_country_defraimp_itahc_PlaceOfOriginHarvestAddressCountryId", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_itahc_PlaceOfOriginHarvestAddressCountryId");
			}
		}
		
		/// <summary>
		/// N:1 defraimp_defra_country_defraimp_itahc_TransporterAddressCountryId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_transporteraddresscountryid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_itahc_TransporterAddressCountryId")]
		public Defra.Imports.Model.defra_country defraimp_defra_country_defraimp_itahc_TransporterAddressCountryId
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.defra_country>("defraimp_defra_country_defraimp_itahc_TransporterAddressCountryId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_itahc_TransporterAddressCountryId");
				this.SetRelatedEntity<Defra.Imports.Model.defra_country>("defraimp_defra_country_defraimp_itahc_TransporterAddressCountryId", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_itahc_TransporterAddressCountryId");
			}
		}
		
		/// <summary>
		/// N:1 defraimp_defraimp_itahc_defraimp_itahc
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_replacesid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defraimp_itahc_defraimp_itahc", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public Defra.Imports.Model.defraimp_itahc Referencingdefraimp_defraimp_itahc_defraimp_itahc
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.defraimp_itahc>("defraimp_defraimp_itahc_defraimp_itahc", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
			set
			{
				this.OnPropertyChanging("Referencingdefraimp_defraimp_itahc_defraimp_itahc");
				this.SetRelatedEntity<Defra.Imports.Model.defraimp_itahc>("defraimp_defraimp_itahc_defraimp_itahc", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
				this.OnPropertyChanged("Referencingdefraimp_defraimp_itahc_defraimp_itahc");
			}
		}
		
		/// <summary>
		/// N:1 defraimp_defraimp_itahc_defraimp_rb
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_replacedbyid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defraimp_itahc_defraimp_rb", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public Defra.Imports.Model.defraimp_itahc Referencingdefraimp_defraimp_itahc_defraimp_rb
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.defraimp_itahc>("defraimp_defraimp_itahc_defraimp_rb", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
			set
			{
				this.OnPropertyChanging("Referencingdefraimp_defraimp_itahc_defraimp_rb");
				this.SetRelatedEntity<Defra.Imports.Model.defraimp_itahc>("defraimp_defraimp_itahc_defraimp_rb", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
				this.OnPropertyChanged("Referencingdefraimp_defraimp_itahc_defraimp_rb");
			}
		}
		
		/// <summary>
		/// N:1 lk_defraimp_itahc_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defraimp_itahc_createdby")]
		public Defra.Imports.Model.SystemUser lk_defraimp_itahc_createdby
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("lk_defraimp_itahc_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_defraimp_itahc_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defraimp_itahc_createdonbehalfby")]
		public Defra.Imports.Model.SystemUser lk_defraimp_itahc_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("lk_defraimp_itahc_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_defraimp_itahc_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defraimp_itahc_modifiedby")]
		public Defra.Imports.Model.SystemUser lk_defraimp_itahc_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("lk_defraimp_itahc_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_defraimp_itahc_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defraimp_itahc_modifiedonbehalfby")]
		public Defra.Imports.Model.SystemUser lk_defraimp_itahc_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("lk_defraimp_itahc_modifiedonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 user_defraimp_itahc
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_defraimp_itahc")]
		public Defra.Imports.Model.SystemUser user_defraimp_itahc
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("user_defraimp_itahc", null);
			}
		}
	}
}
#pragma warning restore CS1591
