#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	/// <summary>
	/// Status of the Match Record
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum defraimp_matchrecord_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Match Record
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum defraimp_matchrecord_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Unmatched = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Matched = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Rejected = 714100001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Removed = 714100000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("defraimp_matchrecord")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class defraimp_matchrecord : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the defraimp_matchrecord entity
		/// </summary>
		public partial class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string defraimp_AppendRecordsToImportRecords = "defraimp_appendrecordstoimportrecords";
			public const string defraimp_CloseRecordAsCompleted = "defraimp_closerecordascompleted";
			public const string defraimp_CloseRecordAsRejected = "defraimp_closerecordasrejected";
			public const string defraimp_CommodityCodeMatchRating = "defraimp_commoditycodematchrating";
			public const string defraimp_CopyCommodityFrom = "defraimp_copycommodityfrom";
			public const string defraimp_CopyConsigneeFrom = "defraimp_copyconsigneefrom";
			public const string defraimp_CopyConsignorFrom = "defraimp_copyconsignorfrom";
			public const string defraimp_CopyKeyDetailsFrom = "defraimp_copykeydetailsfrom";
			public const string defraimp_CopyPlaceofDestinationFrom = "defraimp_copyplaceofdestinationfrom";
			public const string defraimp_CopyPlaceofOriginFrom = "defraimp_copyplaceoforiginfrom";
			public const string defraimp_CopyTransporterFrom = "defraimp_copytransporterfrom";
			public const string defraimp_CountryofOriginMatchRating = "defraimp_countryoforiginmatchrating";
			public const string defraimp_DateofImportMatchRating = "defraimp_dateofimportmatchrating";
			public const string defraimp_DestinationPostcode = "defraimp_destinationpostcode";
			public const string defraimp_DestinationPostcodeMatchRating = "defraimp_destinationpostcodematchrating";
			public const string defraimp_ImporterNotification = "defraimp_importernotification";
			public const string defraimp_ImportRecord = "defraimp_importrecord";
			public const string defraimp_IsRecordValidMatch = "defraimp_isrecordvalidmatch";
			public const string defraimp_ITAHC = "defraimp_itahc";
			public const string defraimp_ITAHCNumberMatchRating = "defraimp_itahcnumbermatchrating";
			public const string defraimp_matchrecordId = "defraimp_matchrecordid";
			public const string Id = "defraimp_matchrecordid";
			public const string defraimp_name = "defraimp_name";
			public const string defraimp_OrganisationNameMatchRating = "defraimp_organisationnamematchrating";
			public const string defraimp_OverallMatchRating = "defraimp_overallmatchrating";
			public const string defraimp_OverwriteExistingFieldsonImportRecord = "defraimp_overwriteexistingfieldsonimportrecord";
			public const string defraimp_PlaceOfOriginNameMatchRating = "defraimp_placeoforiginnamematchrating";
			public const string defraimp_PlaceOfOriginPostcodeMatchRating = "defraimp_placeoforiginpostcodematchrating";
			public const string defraimp_QuantityMatchRating = "defraimp_quantitymatchrating";
			public const string defraimp_RejectedReason = "defraimp_rejectedreason";
			public const string defraimp_SpeciesMatchRating = "defraimp_speciesmatchrating";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string processid = "processid";
			public const string stageid = "stageid";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string traversedpath = "traversedpath";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string defraimp_PotentiallyRelatedImportRecords = "defraimp_PotentiallyRelatedImportRecords";
			public const string defraimp_defraimp_importernotification_defraimp_matchrecord_ImporterNotification = "defraimp_defraimp_importernotification_defraimp_matchrecord_ImporterNotification";
			public const string defraimp_defraimp_itahc_defraimp_matchrecord_ITAHC = "defraimp_defraimp_itahc_defraimp_matchrecord_ITAHC";
			public const string defraimp_defraimp_matchrecord_defraimp_Im = "defraimp_defraimp_matchrecord_defraimp_Im";
			public const string lk_defraimp_matchrecord_createdby = "lk_defraimp_matchrecord_createdby";
			public const string lk_defraimp_matchrecord_createdonbehalfby = "lk_defraimp_matchrecord_createdonbehalfby";
			public const string lk_defraimp_matchrecord_modifiedby = "lk_defraimp_matchrecord_modifiedby";
			public const string lk_defraimp_matchrecord_modifiedonbehalfby = "lk_defraimp_matchrecord_modifiedonbehalfby";
			public const string user_defraimp_matchrecord = "user_defraimp_matchrecord";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public defraimp_matchrecord() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "defraimp_matchrecord";
		
		public const string EntityLogicalCollectionName = "defraimp_matchrecords";
		
		public const string EntitySetName = "defraimp_matchrecords";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_appendrecordstoimportrecords")]
		public System.Nullable<bool> defraimp_AppendRecordsToImportRecords
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("defraimp_appendrecordstoimportrecords");
			}
			set
			{
				this.OnPropertyChanging("defraimp_AppendRecordsToImportRecords");
				this.SetAttributeValue("defraimp_appendrecordstoimportrecords", value);
				this.OnPropertyChanged("defraimp_AppendRecordsToImportRecords");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_closerecordascompleted")]
		public System.Nullable<bool> defraimp_CloseRecordAsCompleted
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("defraimp_closerecordascompleted");
			}
			set
			{
				this.OnPropertyChanging("defraimp_CloseRecordAsCompleted");
				this.SetAttributeValue("defraimp_closerecordascompleted", value);
				this.OnPropertyChanged("defraimp_CloseRecordAsCompleted");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_closerecordasrejected")]
		public System.Nullable<bool> defraimp_CloseRecordAsRejected
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("defraimp_closerecordasrejected");
			}
			set
			{
				this.OnPropertyChanging("defraimp_CloseRecordAsRejected");
				this.SetAttributeValue("defraimp_closerecordasrejected", value);
				this.OnPropertyChanged("defraimp_CloseRecordAsRejected");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_commoditycodematchrating")]
		public string defraimp_CommodityCodeMatchRating
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_commoditycodematchrating");
			}
			set
			{
				this.OnPropertyChanging("defraimp_CommodityCodeMatchRating");
				this.SetAttributeValue("defraimp_commoditycodematchrating", value);
				this.OnPropertyChanged("defraimp_CommodityCodeMatchRating");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_copycommodityfrom")]
		public System.Nullable<bool> defraimp_CopyCommodityFrom
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("defraimp_copycommodityfrom");
			}
			set
			{
				this.OnPropertyChanging("defraimp_CopyCommodityFrom");
				this.SetAttributeValue("defraimp_copycommodityfrom", value);
				this.OnPropertyChanged("defraimp_CopyCommodityFrom");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_copyconsigneefrom")]
		public System.Nullable<bool> defraimp_CopyConsigneeFrom
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("defraimp_copyconsigneefrom");
			}
			set
			{
				this.OnPropertyChanging("defraimp_CopyConsigneeFrom");
				this.SetAttributeValue("defraimp_copyconsigneefrom", value);
				this.OnPropertyChanged("defraimp_CopyConsigneeFrom");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_copyconsignorfrom")]
		public System.Nullable<bool> defraimp_CopyConsignorFrom
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("defraimp_copyconsignorfrom");
			}
			set
			{
				this.OnPropertyChanging("defraimp_CopyConsignorFrom");
				this.SetAttributeValue("defraimp_copyconsignorfrom", value);
				this.OnPropertyChanged("defraimp_CopyConsignorFrom");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_copykeydetailsfrom")]
		public System.Nullable<bool> defraimp_CopyKeyDetailsFrom
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("defraimp_copykeydetailsfrom");
			}
			set
			{
				this.OnPropertyChanging("defraimp_CopyKeyDetailsFrom");
				this.SetAttributeValue("defraimp_copykeydetailsfrom", value);
				this.OnPropertyChanged("defraimp_CopyKeyDetailsFrom");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_copyplaceofdestinationfrom")]
		public System.Nullable<bool> defraimp_CopyPlaceofDestinationFrom
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("defraimp_copyplaceofdestinationfrom");
			}
			set
			{
				this.OnPropertyChanging("defraimp_CopyPlaceofDestinationFrom");
				this.SetAttributeValue("defraimp_copyplaceofdestinationfrom", value);
				this.OnPropertyChanged("defraimp_CopyPlaceofDestinationFrom");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_copyplaceoforiginfrom")]
		public System.Nullable<bool> defraimp_CopyPlaceofOriginFrom
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("defraimp_copyplaceoforiginfrom");
			}
			set
			{
				this.OnPropertyChanging("defraimp_CopyPlaceofOriginFrom");
				this.SetAttributeValue("defraimp_copyplaceoforiginfrom", value);
				this.OnPropertyChanged("defraimp_CopyPlaceofOriginFrom");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_copytransporterfrom")]
		public System.Nullable<bool> defraimp_CopyTransporterFrom
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("defraimp_copytransporterfrom");
			}
			set
			{
				this.OnPropertyChanging("defraimp_CopyTransporterFrom");
				this.SetAttributeValue("defraimp_copytransporterfrom", value);
				this.OnPropertyChanged("defraimp_CopyTransporterFrom");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_countryoforiginmatchrating")]
		public string defraimp_CountryofOriginMatchRating
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_countryoforiginmatchrating");
			}
			set
			{
				this.OnPropertyChanging("defraimp_CountryofOriginMatchRating");
				this.SetAttributeValue("defraimp_countryoforiginmatchrating", value);
				this.OnPropertyChanged("defraimp_CountryofOriginMatchRating");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_dateofimportmatchrating")]
		public string defraimp_DateofImportMatchRating
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_dateofimportmatchrating");
			}
			set
			{
				this.OnPropertyChanging("defraimp_DateofImportMatchRating");
				this.SetAttributeValue("defraimp_dateofimportmatchrating", value);
				this.OnPropertyChanged("defraimp_DateofImportMatchRating");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_destinationpostcode")]
		public string defraimp_DestinationPostcode
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_destinationpostcode");
			}
			set
			{
				this.OnPropertyChanging("defraimp_DestinationPostcode");
				this.SetAttributeValue("defraimp_destinationpostcode", value);
				this.OnPropertyChanged("defraimp_DestinationPostcode");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_destinationpostcodematchrating")]
		public string defraimp_DestinationPostcodeMatchRating
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_destinationpostcodematchrating");
			}
			set
			{
				this.OnPropertyChanging("defraimp_DestinationPostcodeMatchRating");
				this.SetAttributeValue("defraimp_destinationpostcodematchrating", value);
				this.OnPropertyChanged("defraimp_DestinationPostcodeMatchRating");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_importernotification")]
		public Microsoft.Xrm.Sdk.EntityReference defraimp_ImporterNotification
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defraimp_importernotification");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ImporterNotification");
				this.SetAttributeValue("defraimp_importernotification", value);
				this.OnPropertyChanged("defraimp_ImporterNotification");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_importrecord")]
		public Microsoft.Xrm.Sdk.EntityReference defraimp_ImportRecord
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defraimp_importrecord");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ImportRecord");
				this.SetAttributeValue("defraimp_importrecord", value);
				this.OnPropertyChanged("defraimp_ImportRecord");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_isrecordvalidmatch")]
		public System.Nullable<bool> defraimp_IsRecordValidMatch
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("defraimp_isrecordvalidmatch");
			}
			set
			{
				this.OnPropertyChanging("defraimp_IsRecordValidMatch");
				this.SetAttributeValue("defraimp_isrecordvalidmatch", value);
				this.OnPropertyChanged("defraimp_IsRecordValidMatch");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_itahc")]
		public Microsoft.Xrm.Sdk.EntityReference defraimp_ITAHC
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defraimp_itahc");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ITAHC");
				this.SetAttributeValue("defraimp_itahc", value);
				this.OnPropertyChanged("defraimp_ITAHC");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_itahcnumbermatchrating")]
		public string defraimp_ITAHCNumberMatchRating
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_itahcnumbermatchrating");
			}
			set
			{
				this.OnPropertyChanging("defraimp_ITAHCNumberMatchRating");
				this.SetAttributeValue("defraimp_itahcnumbermatchrating", value);
				this.OnPropertyChanged("defraimp_ITAHCNumberMatchRating");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_matchrecordid")]
		public System.Nullable<System.Guid> defraimp_matchrecordId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("defraimp_matchrecordid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_matchrecordId");
				this.SetAttributeValue("defraimp_matchrecordid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("defraimp_matchrecordId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_matchrecordid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.defraimp_matchrecordId = value;
			}
		}
		
		/// <summary>
		/// The name of the custom entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_name")]
		public string defraimp_name
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_name");
			}
			set
			{
				this.OnPropertyChanging("defraimp_name");
				this.SetAttributeValue("defraimp_name", value);
				this.OnPropertyChanged("defraimp_name");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_organisationnamematchrating")]
		public string defraimp_OrganisationNameMatchRating
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_organisationnamematchrating");
			}
			set
			{
				this.OnPropertyChanging("defraimp_OrganisationNameMatchRating");
				this.SetAttributeValue("defraimp_organisationnamematchrating", value);
				this.OnPropertyChanged("defraimp_OrganisationNameMatchRating");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_overallmatchrating")]
		public string defraimp_OverallMatchRating
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_overallmatchrating");
			}
			set
			{
				this.OnPropertyChanging("defraimp_OverallMatchRating");
				this.SetAttributeValue("defraimp_overallmatchrating", value);
				this.OnPropertyChanged("defraimp_OverallMatchRating");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_overwriteexistingfieldsonimportrecord")]
		public System.Nullable<bool> defraimp_OverwriteExistingFieldsonImportRecord
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("defraimp_overwriteexistingfieldsonimportrecord");
			}
			set
			{
				this.OnPropertyChanging("defraimp_OverwriteExistingFieldsonImportRecord");
				this.SetAttributeValue("defraimp_overwriteexistingfieldsonimportrecord", value);
				this.OnPropertyChanged("defraimp_OverwriteExistingFieldsonImportRecord");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeoforiginnamematchrating")]
		public string defraimp_PlaceOfOriginNameMatchRating
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_placeoforiginnamematchrating");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PlaceOfOriginNameMatchRating");
				this.SetAttributeValue("defraimp_placeoforiginnamematchrating", value);
				this.OnPropertyChanged("defraimp_PlaceOfOriginNameMatchRating");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_placeoforiginpostcodematchrating")]
		public string defraimp_PlaceOfOriginPostcodeMatchRating
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_placeoforiginpostcodematchrating");
			}
			set
			{
				this.OnPropertyChanging("defraimp_PlaceOfOriginPostcodeMatchRating");
				this.SetAttributeValue("defraimp_placeoforiginpostcodematchrating", value);
				this.OnPropertyChanged("defraimp_PlaceOfOriginPostcodeMatchRating");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_quantitymatchrating")]
		public string defraimp_QuantityMatchRating
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_quantitymatchrating");
			}
			set
			{
				this.OnPropertyChanging("defraimp_QuantityMatchRating");
				this.SetAttributeValue("defraimp_quantitymatchrating", value);
				this.OnPropertyChanged("defraimp_QuantityMatchRating");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_rejectedreason")]
		public string defraimp_RejectedReason
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_rejectedreason");
			}
			set
			{
				this.OnPropertyChanging("defraimp_RejectedReason");
				this.SetAttributeValue("defraimp_rejectedreason", value);
				this.OnPropertyChanged("defraimp_RejectedReason");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_speciesmatchrating")]
		public string defraimp_SpeciesMatchRating
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_speciesmatchrating");
			}
			set
			{
				this.OnPropertyChanging("defraimp_SpeciesMatchRating");
				this.SetAttributeValue("defraimp_speciesmatchrating", value);
				this.OnPropertyChanged("defraimp_SpeciesMatchRating");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Contains the id of the process associated with the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processid")]
		public System.Nullable<System.Guid> processid
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("processid");
			}
			set
			{
				this.OnPropertyChanging("processid");
				this.SetAttributeValue("processid", value);
				this.OnPropertyChanged("processid");
			}
		}
		
		/// <summary>
		/// Contains the id of the stage where the entity is located.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stageid")]
		public System.Nullable<System.Guid> stageid
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("stageid");
			}
			set
			{
				this.OnPropertyChanging("stageid");
				this.SetAttributeValue("stageid", value);
				this.OnPropertyChanged("stageid");
			}
		}
		
		/// <summary>
		/// Status of the Match Record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual defraimp_matchrecord_statecode? statecode
		{
			get
			{
				return ((defraimp_matchrecord_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("statecode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statecode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Match Record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual defraimp_matchrecord_statuscode? statuscode
		{
			get
			{
				return ((defraimp_matchrecord_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// A comma separated list of string values representing the unique identifiers of stages in a Business Process Flow Instance in the order that they occur.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("traversedpath")]
		public string traversedpath
		{
			get
			{
				return this.GetAttributeValue<string>("traversedpath");
			}
			set
			{
				this.OnPropertyChanging("traversedpath");
				this.SetAttributeValue("traversedpath", value);
				this.OnPropertyChanged("traversedpath");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:N defraimp_PotentiallyRelatedImportRecords
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_PotentiallyRelatedImportRecords")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_importapplication> defraimp_PotentiallyRelatedImportRecords
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_importapplication>("defraimp_PotentiallyRelatedImportRecords", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_PotentiallyRelatedImportRecords");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_importapplication>("defraimp_PotentiallyRelatedImportRecords", null, value);
				this.OnPropertyChanged("defraimp_PotentiallyRelatedImportRecords");
			}
		}
		
		/// <summary>
		/// N:1 defraimp_defraimp_importernotification_defraimp_matchrecord_ImporterNotification
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_importernotification")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defraimp_importernotification_defraimp_matchrecord_ImporterNotification")]
		public Defra.Imports.Model.defraimp_ImporterNotification defraimp_defraimp_importernotification_defraimp_matchrecord_ImporterNotification
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.defraimp_ImporterNotification>("defraimp_defraimp_importernotification_defraimp_matchrecord_ImporterNotification", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defraimp_importernotification_defraimp_matchrecord_ImporterNotification");
				this.SetRelatedEntity<Defra.Imports.Model.defraimp_ImporterNotification>("defraimp_defraimp_importernotification_defraimp_matchrecord_ImporterNotification", null, value);
				this.OnPropertyChanged("defraimp_defraimp_importernotification_defraimp_matchrecord_ImporterNotification");
			}
		}
		
		/// <summary>
		/// N:1 defraimp_defraimp_itahc_defraimp_matchrecord_ITAHC
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_itahc")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defraimp_itahc_defraimp_matchrecord_ITAHC")]
		public Defra.Imports.Model.defraimp_itahc defraimp_defraimp_itahc_defraimp_matchrecord_ITAHC
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.defraimp_itahc>("defraimp_defraimp_itahc_defraimp_matchrecord_ITAHC", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defraimp_itahc_defraimp_matchrecord_ITAHC");
				this.SetRelatedEntity<Defra.Imports.Model.defraimp_itahc>("defraimp_defraimp_itahc_defraimp_matchrecord_ITAHC", null, value);
				this.OnPropertyChanged("defraimp_defraimp_itahc_defraimp_matchrecord_ITAHC");
			}
		}
		
		/// <summary>
		/// N:1 defraimp_defraimp_matchrecord_defraimp_Im
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_importrecord")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defraimp_matchrecord_defraimp_Im")]
		public Defra.Imports.Model.defraimp_importapplication defraimp_defraimp_matchrecord_defraimp_Im
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.defraimp_importapplication>("defraimp_defraimp_matchrecord_defraimp_Im", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defraimp_matchrecord_defraimp_Im");
				this.SetRelatedEntity<Defra.Imports.Model.defraimp_importapplication>("defraimp_defraimp_matchrecord_defraimp_Im", null, value);
				this.OnPropertyChanged("defraimp_defraimp_matchrecord_defraimp_Im");
			}
		}
		
		/// <summary>
		/// N:1 lk_defraimp_matchrecord_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defraimp_matchrecord_createdby")]
		public Defra.Imports.Model.SystemUser lk_defraimp_matchrecord_createdby
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("lk_defraimp_matchrecord_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_defraimp_matchrecord_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defraimp_matchrecord_createdonbehalfby")]
		public Defra.Imports.Model.SystemUser lk_defraimp_matchrecord_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("lk_defraimp_matchrecord_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_defraimp_matchrecord_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defraimp_matchrecord_modifiedby")]
		public Defra.Imports.Model.SystemUser lk_defraimp_matchrecord_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("lk_defraimp_matchrecord_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_defraimp_matchrecord_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defraimp_matchrecord_modifiedonbehalfby")]
		public Defra.Imports.Model.SystemUser lk_defraimp_matchrecord_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("lk_defraimp_matchrecord_modifiedonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 user_defraimp_matchrecord
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_defraimp_matchrecord")]
		public Defra.Imports.Model.SystemUser user_defraimp_matchrecord
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("user_defraimp_matchrecord", null);
			}
		}
	}
}
#pragma warning restore CS1591
