#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	/// <summary>
	/// Status of the Import Country Commodity Risk Level
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum defraimp_importcountrycommodityrisklevel_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Import Country Commodity Risk Level
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum defraimp_importcountrycommodityrisklevel_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("defraimp_importcountrycommodityrisklevel")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class defraimp_importcountrycommodityrisklevel : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the defraimp_importcountrycommodityrisklevel entity
		/// </summary>
		public partial class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string defraimp_commoditytypeid = "defraimp_commoditytypeid";
			public const string defraimp_countryid = "defraimp_countryid";
			public const string defraimp_importcountrycommodityrisklevelId = "defraimp_importcountrycommodityrisklevelid";
			public const string Id = "defraimp_importcountrycommodityrisklevelid";
			public const string defraimp_importrisklevelid = "defraimp_importrisklevelid";
			public const string defraimp_name = "defraimp_name";
			public const string defraimp_risklevelnotes = "defraimp_risklevelnotes";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OrganizationId = "organizationid";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string defraimp_defra_country_defraimp_importcountrycommodityrisklevel_countryid = "defraimp_defra_country_defraimp_importcountrycommodityrisklevel_countryid";
			public const string defraimp_defraimp_importrisklevel_defraimp_importcountrycommodityrisklevel_risklevelid = "defraimp_defraimp_importrisklevel_defraimp_importcountrycommodityrisklevel_riskle" +
		"velid";
			public const string lk_defraimp_importcountrycommodityrisklevel_createdby = "lk_defraimp_importcountrycommodityrisklevel_createdby";
			public const string lk_defraimp_importcountrycommodityrisklevel_createdonbehalfby = "lk_defraimp_importcountrycommodityrisklevel_createdonbehalfby";
			public const string lk_defraimp_importcountrycommodityrisklevel_modifiedby = "lk_defraimp_importcountrycommodityrisklevel_modifiedby";
			public const string lk_defraimp_importcountrycommodityrisklevel_modifiedonbehalfby = "lk_defraimp_importcountrycommodityrisklevel_modifiedonbehalfby";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public defraimp_importcountrycommodityrisklevel() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "defraimp_importcountrycommodityrisklevel";
		
		public const string EntityLogicalCollectionName = "defraimp_importcountrycommodityrisklevels";
		
		public const string EntitySetName = "defraimp_importcountrycommodityrisklevels";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_commoditytypeid")]
		public Microsoft.Xrm.Sdk.EntityReference defraimp_commoditytypeid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defraimp_commoditytypeid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_commoditytypeid");
				this.SetAttributeValue("defraimp_commoditytypeid", value);
				this.OnPropertyChanged("defraimp_commoditytypeid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_countryid")]
		public Microsoft.Xrm.Sdk.EntityReference defraimp_countryid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defraimp_countryid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_countryid");
				this.SetAttributeValue("defraimp_countryid", value);
				this.OnPropertyChanged("defraimp_countryid");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_importcountrycommodityrisklevelid")]
		public System.Nullable<System.Guid> defraimp_importcountrycommodityrisklevelId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("defraimp_importcountrycommodityrisklevelid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_importcountrycommodityrisklevelId");
				this.SetAttributeValue("defraimp_importcountrycommodityrisklevelid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("defraimp_importcountrycommodityrisklevelId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_importcountrycommodityrisklevelid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.defraimp_importcountrycommodityrisklevelId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_importrisklevelid")]
		public Microsoft.Xrm.Sdk.EntityReference defraimp_importrisklevelid
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("defraimp_importrisklevelid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_importrisklevelid");
				this.SetAttributeValue("defraimp_importrisklevelid", value);
				this.OnPropertyChanged("defraimp_importrisklevelid");
			}
		}
		
		/// <summary>
		/// The name of the custom entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_name")]
		public string defraimp_name
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_name");
			}
			set
			{
				this.OnPropertyChanging("defraimp_name");
				this.SetAttributeValue("defraimp_name", value);
				this.OnPropertyChanged("defraimp_name");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_risklevelnotes")]
		public string defraimp_risklevelnotes
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_risklevelnotes");
			}
			set
			{
				this.OnPropertyChanging("defraimp_risklevelnotes");
				this.SetAttributeValue("defraimp_risklevelnotes", value);
				this.OnPropertyChanged("defraimp_risklevelnotes");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Unique identifier for the organization
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		public Microsoft.Xrm.Sdk.EntityReference OrganizationId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("organizationid");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Status of the Import Country Commodity Risk Level
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual defraimp_importcountrycommodityrisklevel_statecode? statecode
		{
			get
			{
				return ((defraimp_importcountrycommodityrisklevel_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("statecode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statecode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Import Country Commodity Risk Level
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual defraimp_importcountrycommodityrisklevel_statuscode? statuscode
		{
			get
			{
				return ((defraimp_importcountrycommodityrisklevel_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 defraimp_defra_country_defraimp_importcountrycommodityrisklevel_countryid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_countryid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_importcountrycommodityrisklevel_countryid")]
		public Defra.Imports.Model.defra_country defraimp_defra_country_defraimp_importcountrycommodityrisklevel_countryid
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.defra_country>("defraimp_defra_country_defraimp_importcountrycommodityrisklevel_countryid", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_importcountrycommodityrisklevel_countryid");
				this.SetRelatedEntity<Defra.Imports.Model.defra_country>("defraimp_defra_country_defraimp_importcountrycommodityrisklevel_countryid", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_importcountrycommodityrisklevel_countryid");
			}
		}
		
		/// <summary>
		/// N:1 defraimp_defraimp_importrisklevel_defraimp_importcountrycommodityrisklevel_risklevelid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_importrisklevelid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defraimp_importrisklevel_defraimp_importcountrycommodityrisklevel_riskle" +
			"velid")]
		public Defra.Imports.Model.defraimp_importrisklevel defraimp_defraimp_importrisklevel_defraimp_importcountrycommodityrisklevel_risklevelid
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.defraimp_importrisklevel>("defraimp_defraimp_importrisklevel_defraimp_importcountrycommodityrisklevel_riskle" +
						"velid", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defraimp_importrisklevel_defraimp_importcountrycommodityrisklevel_riskle" +
						"velid");
				this.SetRelatedEntity<Defra.Imports.Model.defraimp_importrisklevel>("defraimp_defraimp_importrisklevel_defraimp_importcountrycommodityrisklevel_riskle" +
						"velid", null, value);
				this.OnPropertyChanged("defraimp_defraimp_importrisklevel_defraimp_importcountrycommodityrisklevel_riskle" +
						"velid");
			}
		}
		
		/// <summary>
		/// N:1 lk_defraimp_importcountrycommodityrisklevel_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defraimp_importcountrycommodityrisklevel_createdby")]
		public Defra.Imports.Model.SystemUser lk_defraimp_importcountrycommodityrisklevel_createdby
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("lk_defraimp_importcountrycommodityrisklevel_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_defraimp_importcountrycommodityrisklevel_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defraimp_importcountrycommodityrisklevel_createdonbehalfby")]
		public Defra.Imports.Model.SystemUser lk_defraimp_importcountrycommodityrisklevel_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("lk_defraimp_importcountrycommodityrisklevel_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_defraimp_importcountrycommodityrisklevel_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defraimp_importcountrycommodityrisklevel_modifiedby")]
		public Defra.Imports.Model.SystemUser lk_defraimp_importcountrycommodityrisklevel_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("lk_defraimp_importcountrycommodityrisklevel_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_defraimp_importcountrycommodityrisklevel_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defraimp_importcountrycommodityrisklevel_modifiedonbehalfby")]
		public Defra.Imports.Model.SystemUser lk_defraimp_importcountrycommodityrisklevel_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("lk_defraimp_importcountrycommodityrisklevel_modifiedonbehalfby", null);
			}
		}
	}
}
#pragma warning restore CS1591
