#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("defraimp_goldbronzecountriesnn")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class defraimp_goldbronzecountriesnn : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the defraimp_goldbronzecountriesnn entity
		/// </summary>
		public partial class Fields
		{
			public const string defra_countryid = "defra_countryid";
			public const string defraimp_goldbronzecommodityid = "defraimp_goldbronzecommodityid";
			public const string defraimp_goldbronzecountriesnnId = "defraimp_goldbronzecountriesnnid";
			public const string Id = "defraimp_goldbronzecountriesnnid";
			public const string VersionNumber = "versionnumber";
			public const string defraimp_goldbronzecountriesnn1 = "defraimp_goldbronzecountriesnn";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public defraimp_goldbronzecountriesnn() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "defraimp_goldbronzecountriesnn";
		
		public const string EntityLogicalCollectionName = null;
		
		public const string EntitySetName = "defraimp_goldbronzecountriesnnset";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_countryid")]
		public System.Nullable<System.Guid> defra_countryid
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("defra_countryid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_goldbronzecommodityid")]
		public System.Nullable<System.Guid> defraimp_goldbronzecommodityid
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("defraimp_goldbronzecommodityid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_goldbronzecountriesnnid")]
		public System.Nullable<System.Guid> defraimp_goldbronzecountriesnnId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("defraimp_goldbronzecountriesnnid");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_goldbronzecountriesnnid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				base.Id = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:N defraimp_goldbronzecountriesnn
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_goldbronzecountriesnn")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_goldbronzecommodity> defraimp_goldbronzecountriesnn1
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_goldbronzecommodity>("defraimp_goldbronzecountriesnn", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_goldbronzecountriesnn1");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_goldbronzecommodity>("defraimp_goldbronzecountriesnn", null, value);
				this.OnPropertyChanged("defraimp_goldbronzecountriesnn1");
			}
		}
	}
}
#pragma warning restore CS1591
