#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	/// <summary>
	/// Status of the Import Risk Level
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum defraimp_importrisklevel_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Import Risk Level
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum defraimp_importrisklevel_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	/// <summary>
	/// Reference Data for Risk Levels.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("defraimp_importrisklevel")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class defraimp_importrisklevel : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the defraimp_importrisklevel entity
		/// </summary>
		public partial class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string defraimp_importrisklevelId = "defraimp_importrisklevelid";
			public const string Id = "defraimp_importrisklevelid";
			public const string defraimp_name = "defraimp_name";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OrganizationId = "organizationid";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string defraimp_defraimp_importrisklevel_defraimp_importapplication_importrisklevelid = "defraimp_defraimp_importrisklevel_defraimp_importapplication_importrisklevelid";
			public const string defraimp_defraimp_importrisklevel_defraimp_importapplication_PreviousImportRiskLevelId = "defraimp_defraimp_importrisklevel_defraimp_importapplication_PreviousImportRiskLe" +
		"velId";
			public const string defraimp_defraimp_importrisklevel_defraimp_importcountrycommodityrisklevel_risklevelid = "defraimp_defraimp_importrisklevel_defraimp_importcountrycommodityrisklevel_riskle" +
		"velid";
			public const string defraimp_defraimp_importrisklevel_defraimp_inspectioncoveragerule_RiskLevelId = "defraimp_defraimp_importrisklevel_defraimp_inspectioncoveragerule_RiskLevelId";
			public const string lk_defraimp_importrisklevel_createdby = "lk_defraimp_importrisklevel_createdby";
			public const string lk_defraimp_importrisklevel_createdonbehalfby = "lk_defraimp_importrisklevel_createdonbehalfby";
			public const string lk_defraimp_importrisklevel_modifiedby = "lk_defraimp_importrisklevel_modifiedby";
			public const string lk_defraimp_importrisklevel_modifiedonbehalfby = "lk_defraimp_importrisklevel_modifiedonbehalfby";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public defraimp_importrisklevel() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "defraimp_importrisklevel";
		
		public const string EntityLogicalCollectionName = "defraimp_importrisklevels";
		
		public const string EntitySetName = "defraimp_importrisklevels";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_importrisklevelid")]
		public System.Nullable<System.Guid> defraimp_importrisklevelId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("defraimp_importrisklevelid");
			}
			set
			{
				this.OnPropertyChanging("defraimp_importrisklevelId");
				this.SetAttributeValue("defraimp_importrisklevelid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("defraimp_importrisklevelId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_importrisklevelid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.defraimp_importrisklevelId = value;
			}
		}
		
		/// <summary>
		/// The name of the custom entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_name")]
		public string defraimp_name
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_name");
			}
			set
			{
				this.OnPropertyChanging("defraimp_name");
				this.SetAttributeValue("defraimp_name", value);
				this.OnPropertyChanged("defraimp_name");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Unique identifier for the organization
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("organizationid")]
		public Microsoft.Xrm.Sdk.EntityReference OrganizationId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("organizationid");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Status of the Import Risk Level
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual defraimp_importrisklevel_statecode? statecode
		{
			get
			{
				return ((defraimp_importrisklevel_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("statecode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statecode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Import Risk Level
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual defraimp_importrisklevel_statuscode? statuscode
		{
			get
			{
				return ((defraimp_importrisklevel_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defraimp_importrisklevel_defraimp_importapplication_importrisklevelid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defraimp_importrisklevel_defraimp_importapplication_importrisklevelid")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_importapplication> defraimp_defraimp_importrisklevel_defraimp_importapplication_importrisklevelid
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_importapplication>("defraimp_defraimp_importrisklevel_defraimp_importapplication_importrisklevelid", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defraimp_importrisklevel_defraimp_importapplication_importrisklevelid");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_importapplication>("defraimp_defraimp_importrisklevel_defraimp_importapplication_importrisklevelid", null, value);
				this.OnPropertyChanged("defraimp_defraimp_importrisklevel_defraimp_importapplication_importrisklevelid");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defraimp_importrisklevel_defraimp_importapplication_PreviousImportRiskLevelId
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defraimp_importrisklevel_defraimp_importapplication_PreviousImportRiskLe" +
			"velId")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_importapplication> defraimp_defraimp_importrisklevel_defraimp_importapplication_PreviousImportRiskLevelId
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_importapplication>("defraimp_defraimp_importrisklevel_defraimp_importapplication_PreviousImportRiskLe" +
						"velId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defraimp_importrisklevel_defraimp_importapplication_PreviousImportRiskLe" +
						"velId");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_importapplication>("defraimp_defraimp_importrisklevel_defraimp_importapplication_PreviousImportRiskLe" +
						"velId", null, value);
				this.OnPropertyChanged("defraimp_defraimp_importrisklevel_defraimp_importapplication_PreviousImportRiskLe" +
						"velId");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defraimp_importrisklevel_defraimp_importcountrycommodityrisklevel_risklevelid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defraimp_importrisklevel_defraimp_importcountrycommodityrisklevel_riskle" +
			"velid")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_importcountrycommodityrisklevel> defraimp_defraimp_importrisklevel_defraimp_importcountrycommodityrisklevel_risklevelid
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_importcountrycommodityrisklevel>("defraimp_defraimp_importrisklevel_defraimp_importcountrycommodityrisklevel_riskle" +
						"velid", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defraimp_importrisklevel_defraimp_importcountrycommodityrisklevel_riskle" +
						"velid");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_importcountrycommodityrisklevel>("defraimp_defraimp_importrisklevel_defraimp_importcountrycommodityrisklevel_riskle" +
						"velid", null, value);
				this.OnPropertyChanged("defraimp_defraimp_importrisklevel_defraimp_importcountrycommodityrisklevel_riskle" +
						"velid");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defraimp_importrisklevel_defraimp_inspectioncoveragerule_RiskLevelId
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defraimp_importrisklevel_defraimp_inspectioncoveragerule_RiskLevelId")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_inspectioncoveragerule> defraimp_defraimp_importrisklevel_defraimp_inspectioncoveragerule_RiskLevelId
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_inspectioncoveragerule>("defraimp_defraimp_importrisklevel_defraimp_inspectioncoveragerule_RiskLevelId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defraimp_importrisklevel_defraimp_inspectioncoveragerule_RiskLevelId");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_inspectioncoveragerule>("defraimp_defraimp_importrisklevel_defraimp_inspectioncoveragerule_RiskLevelId", null, value);
				this.OnPropertyChanged("defraimp_defraimp_importrisklevel_defraimp_inspectioncoveragerule_RiskLevelId");
			}
		}
		
		/// <summary>
		/// N:1 lk_defraimp_importrisklevel_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defraimp_importrisklevel_createdby")]
		public Defra.Imports.Model.SystemUser lk_defraimp_importrisklevel_createdby
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("lk_defraimp_importrisklevel_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_defraimp_importrisklevel_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defraimp_importrisklevel_createdonbehalfby")]
		public Defra.Imports.Model.SystemUser lk_defraimp_importrisklevel_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("lk_defraimp_importrisklevel_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_defraimp_importrisklevel_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defraimp_importrisklevel_modifiedby")]
		public Defra.Imports.Model.SystemUser lk_defraimp_importrisklevel_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("lk_defraimp_importrisklevel_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_defraimp_importrisklevel_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defraimp_importrisklevel_modifiedonbehalfby")]
		public Defra.Imports.Model.SystemUser lk_defraimp_importrisklevel_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("lk_defraimp_importrisklevel_modifiedonbehalfby", null);
			}
		}
	}
}
#pragma warning restore CS1591
