#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Defra.Imports.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum cr01a_defra_country_cr01a_countrygroup
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EU = 100490000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ROW = 100490001,
	}
	
	/// <summary>
	/// Status of the Country
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum defra_country_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Country
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public enum defra_country_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("defra_country")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Dataverse Model Builder", "2.0.0.16")]
	public partial class defra_country : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the defra_country entity
		/// </summary>
		public partial class Fields
		{
			public const string cr01a_CountryGroup = "cr01a_countrygroup";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string defra_aka = "defra_aka";
			public const string defra_citizenemonym = "defra_citizenemonym";
			public const string defra_codeassignmenttype = "defra_codeassignmenttype";
			public const string defra_countryId = "defra_countryid";
			public const string Id = "defra_countryid";
			public const string defra_enddate = "defra_enddate";
			public const string defra_independent = "defra_independent";
			public const string defra_iso31662subdivisioncodes = "defra_iso31662subdivisioncodes";
			public const string defra_isocodealpha2 = "defra_isocodealpha2";
			public const string defra_isocodealpha3 = "defra_isocodealpha3";
			public const string defra_isonumericcode = "defra_isonumericcode";
			public const string defra_name = "defra_name";
			public const string defra_notes = "defra_notes";
			public const string defra_startdate = "defra_startdate";
			public const string defraimp_SixCharacterCountryCode = "defraimp_sixcharactercountrycode";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string defraimp_defra_country_defraimp_consignee_Country = "defraimp_defra_country_defraimp_consignee_Country";
			public const string defraimp_defra_country_defraimp_docom_ConsigneeAddressCountryId = "defraimp_defra_country_defraimp_docom_ConsigneeAddressCountryId";
			public const string defraimp_defra_country_defraimp_docom_ConsignorAddressCountryId = "defraimp_defra_country_defraimp_docom_ConsignorAddressCountryId";
			public const string defraimp_defra_country_defraimp_docom_CountryOfOriginId = "defraimp_defra_country_defraimp_docom_CountryOfOriginId";
			public const string defraimp_defra_country_defraimp_docom_PlaceOfDestinationAddressCountryId = "defraimp_defra_country_defraimp_docom_PlaceOfDestinationAddressCountryId";
			public const string defraimp_defra_country_defraimp_docom_PlaceOfLoadingAddressCountryId = "defraimp_defra_country_defraimp_docom_PlaceOfLoadingAddressCountryId";
			public const string defraimp_defra_country_defraimp_docom_PlaceOfOriginHarvestAddressCountryId = "defraimp_defra_country_defraimp_docom_PlaceOfOriginHarvestAddressCountryId";
			public const string defraimp_defra_country_defraimp_docom_TransporterAddressCountryId = "defraimp_defra_country_defraimp_docom_TransporterAddressCountryId";
			public const string defraimp_defra_country_defraimp_importapplication = "defraimp_defra_country_defraimp_importapplication";
			public const string defraimp_defra_country_defraimp_importapplication_CharityAddressCountry = "defraimp_defra_country_defraimp_importapplication_CharityAddressCountry";
			public const string defraimp_defra_country_defraimp_importapplication_ImporterAddressCountryID = "defraimp_defra_country_defraimp_importapplication_ImporterAddressCountryID";
			public const string defraimp_defra_country_defraimp_importapplication_PlaceofOriginCountryID = "defraimp_defra_country_defraimp_importapplication_PlaceofOriginCountryID";
			public const string defraimp_defra_country_defraimp_importapplication_transporteraddresscountryid = "defraimp_defra_country_defraimp_importapplication_transporteraddresscountryid";
			public const string defraimp_defra_country_defraimp_importapppermdest = "defraimp_defra_country_defraimp_importapppermdest";
			public const string defraimp_defra_country_defraimp_importappplacedest = "defraimp_defra_country_defraimp_importappplacedest";
			public const string defraimp_defra_country_defraimp_importcountrycommodityrisklevel_countryid = "defraimp_defra_country_defraimp_importcountrycommodityrisklevel_countryid";
			public const string defraimp_defra_country_defraimp_importernotification_ConsignedCountryid = "defraimp_defra_country_defraimp_importernotification_ConsignedCountryid";
			public const string defraimp_defra_country_defraimp_importernotification_ConsigneeAddressCountryId = "defraimp_defra_country_defraimp_importernotification_ConsigneeAddressCountryId";
			public const string defraimp_defra_country_defraimp_importernotification_ConsignorAddressCountryid = "defraimp_defra_country_defraimp_importernotification_ConsignorAddressCountryid";
			public const string defraimp_defra_country_defraimp_importernotification_ConsignorTwoAddressCountry = "defraimp_defra_country_defraimp_importernotification_ConsignorTwoAddressCountry";
			public const string defraimp_defra_country_defraimp_importernotification_CountryofOriginId = "defraimp_defra_country_defraimp_importernotification_CountryofOriginId";
			public const string defraimp_defra_country_defraimp_importernotification_ImporterAddressCountryid = "defraimp_defra_country_defraimp_importernotification_ImporterAddressCountryid";
			public const string defraimp_defra_country_defraimp_importernotification_PersonResponsibleCountryId = "defraimp_defra_country_defraimp_importernotification_PersonResponsibleCountryId";
			public const string defraimp_defra_country_defraimp_importernotification_PlaceofDestinationCountryid = "defraimp_defra_country_defraimp_importernotification_PlaceofDestinationCountryid";
			public const string defraimp_defra_country_defraimp_importernotification_PlaceofOriginHarvestAddressCountryId = "defraimp_defra_country_defraimp_importernotification_PlaceofOriginHarvestAddressC" +
		"ountryId";
			public const string defraimp_defra_country_defraimp_importernotification_transitdestinationcountryid = "defraimp_defra_country_defraimp_importernotification_transitdestinationcountryid";
			public const string defraimp_defra_country_defraimp_importernotification_TransporterAddressCountryid = "defraimp_defra_country_defraimp_importernotification_TransporterAddressCountryid";
			public const string defraimp_defra_country_defraimp_itahc_ConsigneeAddressCountryId = "defraimp_defra_country_defraimp_itahc_ConsigneeAddressCountryId";
			public const string defraimp_defra_country_defraimp_itahc_ConsignorAddressCountryId = "defraimp_defra_country_defraimp_itahc_ConsignorAddressCountryId";
			public const string defraimp_defra_country_defraimp_itahc_CountryOfOriginId = "defraimp_defra_country_defraimp_itahc_CountryOfOriginId";
			public const string defraimp_defra_country_defraimp_itahc_PlaceOfDestinationAddressCountryId = "defraimp_defra_country_defraimp_itahc_PlaceOfDestinationAddressCountryId";
			public const string defraimp_defra_country_defraimp_itahc_PlaceOfLoadingAddressCountryId = "defraimp_defra_country_defraimp_itahc_PlaceOfLoadingAddressCountryId";
			public const string defraimp_defra_country_defraimp_itahc_PlaceOfOriginHarvestAddressCountryId = "defraimp_defra_country_defraimp_itahc_PlaceOfOriginHarvestAddressCountryId";
			public const string defraimp_defra_country_defraimp_itahc_TransporterAddressCountryId = "defraimp_defra_country_defraimp_itahc_TransporterAddressCountryId";
			public const string defraimp_defra_country_defraimp_placeofdestination_Country = "defraimp_defra_country_defraimp_placeofdestination_Country";
			public const string defraimp_defra_country_defraimp_placeoforigin_AddressCountry = "defraimp_defra_country_defraimp_placeoforigin_AddressCountry";
			public const string defraimp_defra_country_defraimp_transporter_Country = "defraimp_defra_country_defraimp_transporter_Country";
			public const string defraimp_importernotification_PlaceofOriginCountryId_defra_country = "defraimp_importernotification_PlaceofOriginCountryId_defra_country";
			public const string defraimp_defraimp_importapplication_defra_country = "defraimp_defraimp_importapplication_defra_country";
			public const string defraimp_goldbronzecountriesnn = "defraimp_goldbronzecountriesnn";
			public const string defraimp_ImporterNotification_CountriesofTransit = "defraimp_ImporterNotification_CountriesofTransit";
			public const string lk_defra_country_createdby = "lk_defra_country_createdby";
			public const string lk_defra_country_createdonbehalfby = "lk_defra_country_createdonbehalfby";
			public const string lk_defra_country_modifiedby = "lk_defra_country_modifiedby";
			public const string lk_defra_country_modifiedonbehalfby = "lk_defra_country_modifiedonbehalfby";
			public const string user_defra_country = "user_defra_country";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public defra_country() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "defra_country";
		
		public const string EntityLogicalCollectionName = "defra_countries";
		
		public const string EntitySetName = "defra_countries";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Identifier for EU or ROW imports
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cr01a_countrygroup")]
		public virtual cr01a_defra_country_cr01a_countrygroup? cr01a_CountryGroup
		{
			get
			{
				return ((cr01a_defra_country_cr01a_countrygroup?)(EntityOptionSetEnum.GetEnum(this, "cr01a_countrygroup")));
			}
			set
			{
				this.OnPropertyChanging("cr01a_CountryGroup");
				this.SetAttributeValue("cr01a_countrygroup", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("cr01a_CountryGroup");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// The commonly used name of the country – e.g., United Kingdom, Germany, France, Spain and so on
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_aka")]
		public string defra_aka
		{
			get
			{
				return this.GetAttributeValue<string>("defra_aka");
			}
			set
			{
				this.OnPropertyChanging("defra_aka");
				this.SetAttributeValue("defra_aka", value);
				this.OnPropertyChanged("defra_aka");
			}
		}
		
		/// <summary>
		/// The demonym used to refer to the citizens of the Country – e.g., British, German, Spanish, and French
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_citizenemonym")]
		public string defra_citizenemonym
		{
			get
			{
				return this.GetAttributeValue<string>("defra_citizenemonym");
			}
			set
			{
				this.OnPropertyChanging("defra_citizenemonym");
				this.SetAttributeValue("defra_citizenemonym", value);
				this.OnPropertyChanged("defra_citizenemonym");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_codeassignmenttype")]
		public string defra_codeassignmenttype
		{
			get
			{
				return this.GetAttributeValue<string>("defra_codeassignmenttype");
			}
			set
			{
				this.OnPropertyChanging("defra_codeassignmenttype");
				this.SetAttributeValue("defra_codeassignmenttype", value);
				this.OnPropertyChanged("defra_codeassignmenttype");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_countryid")]
		public System.Nullable<System.Guid> defra_countryId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("defra_countryid");
			}
			set
			{
				this.OnPropertyChanging("defra_countryId");
				this.SetAttributeValue("defra_countryid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("defra_countryId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_countryid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.defra_countryId = value;
			}
		}
		
		/// <summary>
		/// The date a country denomination stopped being used.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_enddate")]
		public System.Nullable<System.DateTime> defra_enddate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("defra_enddate");
			}
			set
			{
				this.OnPropertyChanging("defra_enddate");
				this.SetAttributeValue("defra_enddate", value);
				this.OnPropertyChanged("defra_enddate");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_independent")]
		public System.Nullable<bool> defra_independent
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("defra_independent");
			}
			set
			{
				this.OnPropertyChanging("defra_independent");
				this.SetAttributeValue("defra_independent", value);
				this.OnPropertyChanged("defra_independent");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_iso31662subdivisioncodes")]
		public string defra_iso31662subdivisioncodes
		{
			get
			{
				return this.GetAttributeValue<string>("defra_iso31662subdivisioncodes");
			}
			set
			{
				this.OnPropertyChanging("defra_iso31662subdivisioncodes");
				this.SetAttributeValue("defra_iso31662subdivisioncodes", value);
				this.OnPropertyChanged("defra_iso31662subdivisioncodes");
			}
		}
		
		/// <summary>
		/// A 2 letter code uniquely identifying each country  and conforming to ISO 3166-2  - e.g. GB, DE, FR, ES, and so on
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_isocodealpha2")]
		public string defra_isocodealpha2
		{
			get
			{
				return this.GetAttributeValue<string>("defra_isocodealpha2");
			}
			set
			{
				this.OnPropertyChanging("defra_isocodealpha2");
				this.SetAttributeValue("defra_isocodealpha2", value);
				this.OnPropertyChanged("defra_isocodealpha2");
			}
		}
		
		/// <summary>
		/// A 3 letter code uniquely identifying each country  and conforming to ISO 3166-3  - e.g. GBR, DEU, FRA, ESP, and so on
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_isocodealpha3")]
		public string defra_isocodealpha3
		{
			get
			{
				return this.GetAttributeValue<string>("defra_isocodealpha3");
			}
			set
			{
				this.OnPropertyChanging("defra_isocodealpha3");
				this.SetAttributeValue("defra_isocodealpha3", value);
				this.OnPropertyChanged("defra_isocodealpha3");
			}
		}
		
		/// <summary>
		/// A 3 letter code uniquely identifying each country  and conforming to ISO 3166-1  - e.g. 826, 276, 250, 724, and so on
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_isonumericcode")]
		public string defra_isonumericcode
		{
			get
			{
				return this.GetAttributeValue<string>("defra_isonumericcode");
			}
			set
			{
				this.OnPropertyChanging("defra_isonumericcode");
				this.SetAttributeValue("defra_isonumericcode", value);
				this.OnPropertyChanged("defra_isonumericcode");
			}
		}
		
		/// <summary>
		/// The name of the custom entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_name")]
		public string defra_name
		{
			get
			{
				return this.GetAttributeValue<string>("defra_name");
			}
			set
			{
				this.OnPropertyChanging("defra_name");
				this.SetAttributeValue("defra_name", value);
				this.OnPropertyChanged("defra_name");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_notes")]
		public string defra_notes
		{
			get
			{
				return this.GetAttributeValue<string>("defra_notes");
			}
			set
			{
				this.OnPropertyChanging("defra_notes");
				this.SetAttributeValue("defra_notes", value);
				this.OnPropertyChanged("defra_notes");
			}
		}
		
		/// <summary>
		/// The date a country denomination first became relevant.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defra_startdate")]
		public System.Nullable<System.DateTime> defra_startdate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("defra_startdate");
			}
			set
			{
				this.OnPropertyChanging("defra_startdate");
				this.SetAttributeValue("defra_startdate", value);
				this.OnPropertyChanged("defra_startdate");
			}
		}
		
		/// <summary>
		/// Codes that are up to 6 characters in length e.g GB-ENG, ES-CN
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("defraimp_sixcharactercountrycode")]
		public string defraimp_SixCharacterCountryCode
		{
			get
			{
				return this.GetAttributeValue<string>("defraimp_sixcharactercountrycode");
			}
			set
			{
				this.OnPropertyChanging("defraimp_SixCharacterCountryCode");
				this.SetAttributeValue("defraimp_sixcharactercountrycode", value);
				this.OnPropertyChanged("defraimp_SixCharacterCountryCode");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Country
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual defra_country_statecode? statecode
		{
			get
			{
				return ((defra_country_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("statecode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statecode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Country
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual defra_country_statuscode? statuscode
		{
			get
			{
				return ((defra_country_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_consignee_Country
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_consignee_Country")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_Consignee> defraimp_defra_country_defraimp_consignee_Country
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_Consignee>("defraimp_defra_country_defraimp_consignee_Country", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_consignee_Country");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_Consignee>("defraimp_defra_country_defraimp_consignee_Country", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_consignee_Country");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_docom_ConsigneeAddressCountryId
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_docom_ConsigneeAddressCountryId")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_docom> defraimp_defra_country_defraimp_docom_ConsigneeAddressCountryId
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_docom>("defraimp_defra_country_defraimp_docom_ConsigneeAddressCountryId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_docom_ConsigneeAddressCountryId");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_docom>("defraimp_defra_country_defraimp_docom_ConsigneeAddressCountryId", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_docom_ConsigneeAddressCountryId");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_docom_ConsignorAddressCountryId
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_docom_ConsignorAddressCountryId")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_docom> defraimp_defra_country_defraimp_docom_ConsignorAddressCountryId
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_docom>("defraimp_defra_country_defraimp_docom_ConsignorAddressCountryId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_docom_ConsignorAddressCountryId");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_docom>("defraimp_defra_country_defraimp_docom_ConsignorAddressCountryId", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_docom_ConsignorAddressCountryId");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_docom_CountryOfOriginId
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_docom_CountryOfOriginId")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_docom> defraimp_defra_country_defraimp_docom_CountryOfOriginId
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_docom>("defraimp_defra_country_defraimp_docom_CountryOfOriginId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_docom_CountryOfOriginId");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_docom>("defraimp_defra_country_defraimp_docom_CountryOfOriginId", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_docom_CountryOfOriginId");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_docom_PlaceOfDestinationAddressCountryId
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_docom_PlaceOfDestinationAddressCountryId")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_docom> defraimp_defra_country_defraimp_docom_PlaceOfDestinationAddressCountryId
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_docom>("defraimp_defra_country_defraimp_docom_PlaceOfDestinationAddressCountryId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_docom_PlaceOfDestinationAddressCountryId");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_docom>("defraimp_defra_country_defraimp_docom_PlaceOfDestinationAddressCountryId", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_docom_PlaceOfDestinationAddressCountryId");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_docom_PlaceOfLoadingAddressCountryId
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_docom_PlaceOfLoadingAddressCountryId")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_docom> defraimp_defra_country_defraimp_docom_PlaceOfLoadingAddressCountryId
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_docom>("defraimp_defra_country_defraimp_docom_PlaceOfLoadingAddressCountryId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_docom_PlaceOfLoadingAddressCountryId");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_docom>("defraimp_defra_country_defraimp_docom_PlaceOfLoadingAddressCountryId", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_docom_PlaceOfLoadingAddressCountryId");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_docom_PlaceOfOriginHarvestAddressCountryId
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_docom_PlaceOfOriginHarvestAddressCountryId")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_docom> defraimp_defra_country_defraimp_docom_PlaceOfOriginHarvestAddressCountryId
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_docom>("defraimp_defra_country_defraimp_docom_PlaceOfOriginHarvestAddressCountryId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_docom_PlaceOfOriginHarvestAddressCountryId");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_docom>("defraimp_defra_country_defraimp_docom_PlaceOfOriginHarvestAddressCountryId", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_docom_PlaceOfOriginHarvestAddressCountryId");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_docom_TransporterAddressCountryId
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_docom_TransporterAddressCountryId")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_docom> defraimp_defra_country_defraimp_docom_TransporterAddressCountryId
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_docom>("defraimp_defra_country_defraimp_docom_TransporterAddressCountryId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_docom_TransporterAddressCountryId");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_docom>("defraimp_defra_country_defraimp_docom_TransporterAddressCountryId", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_docom_TransporterAddressCountryId");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_importapplication
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_importapplication")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_importapplication> defraimp_defra_country_defraimp_importapplication
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_importapplication>("defraimp_defra_country_defraimp_importapplication", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_importapplication");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_importapplication>("defraimp_defra_country_defraimp_importapplication", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_importapplication");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_importapplication_CharityAddressCountry
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_importapplication_CharityAddressCountry")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_importapplication> defraimp_defra_country_defraimp_importapplication_CharityAddressCountry
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_importapplication>("defraimp_defra_country_defraimp_importapplication_CharityAddressCountry", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_importapplication_CharityAddressCountry");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_importapplication>("defraimp_defra_country_defraimp_importapplication_CharityAddressCountry", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_importapplication_CharityAddressCountry");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_importapplication_ImporterAddressCountryID
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_importapplication_ImporterAddressCountryID")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_importapplication> defraimp_defra_country_defraimp_importapplication_ImporterAddressCountryID
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_importapplication>("defraimp_defra_country_defraimp_importapplication_ImporterAddressCountryID", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_importapplication_ImporterAddressCountryID");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_importapplication>("defraimp_defra_country_defraimp_importapplication_ImporterAddressCountryID", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_importapplication_ImporterAddressCountryID");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_importapplication_PlaceofOriginCountryID
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_importapplication_PlaceofOriginCountryID")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_importapplication> defraimp_defra_country_defraimp_importapplication_PlaceofOriginCountryID
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_importapplication>("defraimp_defra_country_defraimp_importapplication_PlaceofOriginCountryID", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_importapplication_PlaceofOriginCountryID");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_importapplication>("defraimp_defra_country_defraimp_importapplication_PlaceofOriginCountryID", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_importapplication_PlaceofOriginCountryID");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_importapplication_transporteraddresscountryid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_importapplication_transporteraddresscountryid")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_importapplication> defraimp_defra_country_defraimp_importapplication_transporteraddresscountryid
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_importapplication>("defraimp_defra_country_defraimp_importapplication_transporteraddresscountryid", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_importapplication_transporteraddresscountryid");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_importapplication>("defraimp_defra_country_defraimp_importapplication_transporteraddresscountryid", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_importapplication_transporteraddresscountryid");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_importapppermdest
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_importapppermdest")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_importapplication> defraimp_defra_country_defraimp_importapppermdest
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_importapplication>("defraimp_defra_country_defraimp_importapppermdest", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_importapppermdest");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_importapplication>("defraimp_defra_country_defraimp_importapppermdest", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_importapppermdest");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_importappplacedest
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_importappplacedest")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_importapplication> defraimp_defra_country_defraimp_importappplacedest
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_importapplication>("defraimp_defra_country_defraimp_importappplacedest", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_importappplacedest");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_importapplication>("defraimp_defra_country_defraimp_importappplacedest", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_importappplacedest");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_importcountrycommodityrisklevel_countryid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_importcountrycommodityrisklevel_countryid")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_importcountrycommodityrisklevel> defraimp_defra_country_defraimp_importcountrycommodityrisklevel_countryid
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_importcountrycommodityrisklevel>("defraimp_defra_country_defraimp_importcountrycommodityrisklevel_countryid", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_importcountrycommodityrisklevel_countryid");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_importcountrycommodityrisklevel>("defraimp_defra_country_defraimp_importcountrycommodityrisklevel_countryid", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_importcountrycommodityrisklevel_countryid");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_importernotification_ConsignedCountryid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_importernotification_ConsignedCountryid")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_ImporterNotification> defraimp_defra_country_defraimp_importernotification_ConsignedCountryid
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_ImporterNotification>("defraimp_defra_country_defraimp_importernotification_ConsignedCountryid", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_importernotification_ConsignedCountryid");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_ImporterNotification>("defraimp_defra_country_defraimp_importernotification_ConsignedCountryid", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_importernotification_ConsignedCountryid");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_importernotification_ConsigneeAddressCountryId
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_importernotification_ConsigneeAddressCountryId")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_ImporterNotification> defraimp_defra_country_defraimp_importernotification_ConsigneeAddressCountryId
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_ImporterNotification>("defraimp_defra_country_defraimp_importernotification_ConsigneeAddressCountryId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_importernotification_ConsigneeAddressCountryId");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_ImporterNotification>("defraimp_defra_country_defraimp_importernotification_ConsigneeAddressCountryId", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_importernotification_ConsigneeAddressCountryId");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_importernotification_ConsignorAddressCountryid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_importernotification_ConsignorAddressCountryid")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_ImporterNotification> defraimp_defra_country_defraimp_importernotification_ConsignorAddressCountryid
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_ImporterNotification>("defraimp_defra_country_defraimp_importernotification_ConsignorAddressCountryid", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_importernotification_ConsignorAddressCountryid");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_ImporterNotification>("defraimp_defra_country_defraimp_importernotification_ConsignorAddressCountryid", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_importernotification_ConsignorAddressCountryid");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_importernotification_ConsignorTwoAddressCountry
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_importernotification_ConsignorTwoAddressCountry")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_ImporterNotification> defraimp_defra_country_defraimp_importernotification_ConsignorTwoAddressCountry
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_ImporterNotification>("defraimp_defra_country_defraimp_importernotification_ConsignorTwoAddressCountry", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_importernotification_ConsignorTwoAddressCountry");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_ImporterNotification>("defraimp_defra_country_defraimp_importernotification_ConsignorTwoAddressCountry", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_importernotification_ConsignorTwoAddressCountry");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_importernotification_CountryofOriginId
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_importernotification_CountryofOriginId")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_ImporterNotification> defraimp_defra_country_defraimp_importernotification_CountryofOriginId
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_ImporterNotification>("defraimp_defra_country_defraimp_importernotification_CountryofOriginId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_importernotification_CountryofOriginId");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_ImporterNotification>("defraimp_defra_country_defraimp_importernotification_CountryofOriginId", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_importernotification_CountryofOriginId");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_importernotification_ImporterAddressCountryid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_importernotification_ImporterAddressCountryid")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_ImporterNotification> defraimp_defra_country_defraimp_importernotification_ImporterAddressCountryid
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_ImporterNotification>("defraimp_defra_country_defraimp_importernotification_ImporterAddressCountryid", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_importernotification_ImporterAddressCountryid");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_ImporterNotification>("defraimp_defra_country_defraimp_importernotification_ImporterAddressCountryid", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_importernotification_ImporterAddressCountryid");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_importernotification_PersonResponsibleCountryId
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_importernotification_PersonResponsibleCountryId")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_ImporterNotification> defraimp_defra_country_defraimp_importernotification_PersonResponsibleCountryId
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_ImporterNotification>("defraimp_defra_country_defraimp_importernotification_PersonResponsibleCountryId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_importernotification_PersonResponsibleCountryId");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_ImporterNotification>("defraimp_defra_country_defraimp_importernotification_PersonResponsibleCountryId", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_importernotification_PersonResponsibleCountryId");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_importernotification_PlaceofDestinationCountryid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_importernotification_PlaceofDestinationCountryid")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_ImporterNotification> defraimp_defra_country_defraimp_importernotification_PlaceofDestinationCountryid
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_ImporterNotification>("defraimp_defra_country_defraimp_importernotification_PlaceofDestinationCountryid", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_importernotification_PlaceofDestinationCountryid");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_ImporterNotification>("defraimp_defra_country_defraimp_importernotification_PlaceofDestinationCountryid", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_importernotification_PlaceofDestinationCountryid");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_importernotification_PlaceofOriginHarvestAddressCountryId
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_importernotification_PlaceofOriginHarvestAddressC" +
			"ountryId")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_ImporterNotification> defraimp_defra_country_defraimp_importernotification_PlaceofOriginHarvestAddressCountryId
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_ImporterNotification>("defraimp_defra_country_defraimp_importernotification_PlaceofOriginHarvestAddressC" +
						"ountryId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_importernotification_PlaceofOriginHarvestAddressC" +
						"ountryId");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_ImporterNotification>("defraimp_defra_country_defraimp_importernotification_PlaceofOriginHarvestAddressC" +
						"ountryId", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_importernotification_PlaceofOriginHarvestAddressC" +
						"ountryId");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_importernotification_transitdestinationcountryid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_importernotification_transitdestinationcountryid")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_ImporterNotification> defraimp_defra_country_defraimp_importernotification_transitdestinationcountryid
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_ImporterNotification>("defraimp_defra_country_defraimp_importernotification_transitdestinationcountryid", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_importernotification_transitdestinationcountryid");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_ImporterNotification>("defraimp_defra_country_defraimp_importernotification_transitdestinationcountryid", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_importernotification_transitdestinationcountryid");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_importernotification_TransporterAddressCountryid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_importernotification_TransporterAddressCountryid")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_ImporterNotification> defraimp_defra_country_defraimp_importernotification_TransporterAddressCountryid
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_ImporterNotification>("defraimp_defra_country_defraimp_importernotification_TransporterAddressCountryid", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_importernotification_TransporterAddressCountryid");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_ImporterNotification>("defraimp_defra_country_defraimp_importernotification_TransporterAddressCountryid", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_importernotification_TransporterAddressCountryid");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_itahc_ConsigneeAddressCountryId
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_itahc_ConsigneeAddressCountryId")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_itahc> defraimp_defra_country_defraimp_itahc_ConsigneeAddressCountryId
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_itahc>("defraimp_defra_country_defraimp_itahc_ConsigneeAddressCountryId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_itahc_ConsigneeAddressCountryId");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_itahc>("defraimp_defra_country_defraimp_itahc_ConsigneeAddressCountryId", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_itahc_ConsigneeAddressCountryId");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_itahc_ConsignorAddressCountryId
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_itahc_ConsignorAddressCountryId")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_itahc> defraimp_defra_country_defraimp_itahc_ConsignorAddressCountryId
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_itahc>("defraimp_defra_country_defraimp_itahc_ConsignorAddressCountryId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_itahc_ConsignorAddressCountryId");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_itahc>("defraimp_defra_country_defraimp_itahc_ConsignorAddressCountryId", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_itahc_ConsignorAddressCountryId");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_itahc_CountryOfOriginId
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_itahc_CountryOfOriginId")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_itahc> defraimp_defra_country_defraimp_itahc_CountryOfOriginId
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_itahc>("defraimp_defra_country_defraimp_itahc_CountryOfOriginId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_itahc_CountryOfOriginId");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_itahc>("defraimp_defra_country_defraimp_itahc_CountryOfOriginId", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_itahc_CountryOfOriginId");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_itahc_PlaceOfDestinationAddressCountryId
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_itahc_PlaceOfDestinationAddressCountryId")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_itahc> defraimp_defra_country_defraimp_itahc_PlaceOfDestinationAddressCountryId
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_itahc>("defraimp_defra_country_defraimp_itahc_PlaceOfDestinationAddressCountryId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_itahc_PlaceOfDestinationAddressCountryId");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_itahc>("defraimp_defra_country_defraimp_itahc_PlaceOfDestinationAddressCountryId", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_itahc_PlaceOfDestinationAddressCountryId");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_itahc_PlaceOfLoadingAddressCountryId
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_itahc_PlaceOfLoadingAddressCountryId")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_itahc> defraimp_defra_country_defraimp_itahc_PlaceOfLoadingAddressCountryId
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_itahc>("defraimp_defra_country_defraimp_itahc_PlaceOfLoadingAddressCountryId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_itahc_PlaceOfLoadingAddressCountryId");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_itahc>("defraimp_defra_country_defraimp_itahc_PlaceOfLoadingAddressCountryId", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_itahc_PlaceOfLoadingAddressCountryId");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_itahc_PlaceOfOriginHarvestAddressCountryId
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_itahc_PlaceOfOriginHarvestAddressCountryId")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_itahc> defraimp_defra_country_defraimp_itahc_PlaceOfOriginHarvestAddressCountryId
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_itahc>("defraimp_defra_country_defraimp_itahc_PlaceOfOriginHarvestAddressCountryId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_itahc_PlaceOfOriginHarvestAddressCountryId");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_itahc>("defraimp_defra_country_defraimp_itahc_PlaceOfOriginHarvestAddressCountryId", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_itahc_PlaceOfOriginHarvestAddressCountryId");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_itahc_TransporterAddressCountryId
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_itahc_TransporterAddressCountryId")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_itahc> defraimp_defra_country_defraimp_itahc_TransporterAddressCountryId
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_itahc>("defraimp_defra_country_defraimp_itahc_TransporterAddressCountryId", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_itahc_TransporterAddressCountryId");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_itahc>("defraimp_defra_country_defraimp_itahc_TransporterAddressCountryId", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_itahc_TransporterAddressCountryId");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_placeofdestination_Country
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_placeofdestination_Country")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_PlaceOfDestination> defraimp_defra_country_defraimp_placeofdestination_Country
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_PlaceOfDestination>("defraimp_defra_country_defraimp_placeofdestination_Country", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_placeofdestination_Country");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_PlaceOfDestination>("defraimp_defra_country_defraimp_placeofdestination_Country", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_placeofdestination_Country");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_placeoforigin_AddressCountry
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_placeoforigin_AddressCountry")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_placeoforigin> defraimp_defra_country_defraimp_placeoforigin_AddressCountry
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_placeoforigin>("defraimp_defra_country_defraimp_placeoforigin_AddressCountry", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_placeoforigin_AddressCountry");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_placeoforigin>("defraimp_defra_country_defraimp_placeoforigin_AddressCountry", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_placeoforigin_AddressCountry");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_defra_country_defraimp_transporter_Country
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defra_country_defraimp_transporter_Country")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_Transporter> defraimp_defra_country_defraimp_transporter_Country
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_Transporter>("defraimp_defra_country_defraimp_transporter_Country", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defra_country_defraimp_transporter_Country");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_Transporter>("defraimp_defra_country_defraimp_transporter_Country", null, value);
				this.OnPropertyChanged("defraimp_defra_country_defraimp_transporter_Country");
			}
		}
		
		/// <summary>
		/// 1:N defraimp_importernotification_PlaceofOriginCountryId_defra_country
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_importernotification_PlaceofOriginCountryId_defra_country")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_ImporterNotification> defraimp_importernotification_PlaceofOriginCountryId_defra_country
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_ImporterNotification>("defraimp_importernotification_PlaceofOriginCountryId_defra_country", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_importernotification_PlaceofOriginCountryId_defra_country");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_ImporterNotification>("defraimp_importernotification_PlaceofOriginCountryId_defra_country", null, value);
				this.OnPropertyChanged("defraimp_importernotification_PlaceofOriginCountryId_defra_country");
			}
		}
		
		/// <summary>
		/// N:N defraimp_defraimp_importapplication_defra_country
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_defraimp_importapplication_defra_country")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_importapplication> defraimp_defraimp_importapplication_defra_country
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_importapplication>("defraimp_defraimp_importapplication_defra_country", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_defraimp_importapplication_defra_country");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_importapplication>("defraimp_defraimp_importapplication_defra_country", null, value);
				this.OnPropertyChanged("defraimp_defraimp_importapplication_defra_country");
			}
		}
		
		/// <summary>
		/// N:N defraimp_goldbronzecountriesnn
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_goldbronzecountriesnn")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_goldbronzecommodity> defraimp_goldbronzecountriesnn
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_goldbronzecommodity>("defraimp_goldbronzecountriesnn", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_goldbronzecountriesnn");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_goldbronzecommodity>("defraimp_goldbronzecountriesnn", null, value);
				this.OnPropertyChanged("defraimp_goldbronzecountriesnn");
			}
		}
		
		/// <summary>
		/// N:N defraimp_ImporterNotification_CountriesofTransit
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("defraimp_ImporterNotification_CountriesofTransit")]
		public System.Collections.Generic.IEnumerable<Defra.Imports.Model.defraimp_ImporterNotification> defraimp_ImporterNotification_CountriesofTransit
		{
			get
			{
				return this.GetRelatedEntities<Defra.Imports.Model.defraimp_ImporterNotification>("defraimp_ImporterNotification_CountriesofTransit", null);
			}
			set
			{
				this.OnPropertyChanging("defraimp_ImporterNotification_CountriesofTransit");
				this.SetRelatedEntities<Defra.Imports.Model.defraimp_ImporterNotification>("defraimp_ImporterNotification_CountriesofTransit", null, value);
				this.OnPropertyChanged("defraimp_ImporterNotification_CountriesofTransit");
			}
		}
		
		/// <summary>
		/// N:1 lk_defra_country_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defra_country_createdby")]
		public Defra.Imports.Model.SystemUser lk_defra_country_createdby
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("lk_defra_country_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_defra_country_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defra_country_createdonbehalfby")]
		public Defra.Imports.Model.SystemUser lk_defra_country_createdonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("lk_defra_country_createdonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_defra_country_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defra_country_modifiedby")]
		public Defra.Imports.Model.SystemUser lk_defra_country_modifiedby
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("lk_defra_country_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_defra_country_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_defra_country_modifiedonbehalfby")]
		public Defra.Imports.Model.SystemUser lk_defra_country_modifiedonbehalfby
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("lk_defra_country_modifiedonbehalfby", null);
			}
		}
		
		/// <summary>
		/// N:1 user_defra_country
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_defra_country")]
		public Defra.Imports.Model.SystemUser user_defra_country
		{
			get
			{
				return this.GetRelatedEntity<Defra.Imports.Model.SystemUser>("user_defra_country", null);
			}
		}
	}
}
#pragma warning restore CS1591
