declare namespace Form.defraimp_importinspection.Main {
  namespace Information {
    namespace Tabs {
      interface IV17_Tab extends Xrm.SectionCollectionBase {
        get(name: "IV17_Tab_section_4"): Xrm.PageSection;
        get(name: "tab_5_section_1"): Xrm.PageSection;
        get(name: "tab_5_section_2"): Xrm.PageSection;
        get(name: "{e4254c81-e79c-4d25-9530-02ff7f875fe8}_section_5"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface Outcomes_Tab extends Xrm.SectionCollectionBase {
        get(name: "tab_4_section_1"): Xrm.PageSection;
        get(name: "tab_4_section_2"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface Sampling_Tab extends Xrm.SectionCollectionBase {
        get(name: "tab_3_section_1"): Xrm.PageSection;
        get(name: "tab_3_section_2"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface e4254c81e79c4d25953002ff7f875fe8 extends Xrm.SectionCollectionBase {
        get(name: "MultipleVisits_Section"): Xrm.PageSection;
        get(name: "Ovedue_Section"): Xrm.PageSection;
        get(name: "RelatedRecordsSection"): Xrm.PageSection;
        get(name: "{e4254c81-e79c-4d25-9530-02ff7f875fe8}_section_4"): Xrm.PageSection;
        get(name: "{e4254c81-e79c-4d25-9530-02ff7f875fe8}_section_6"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_2 extends Xrm.SectionCollectionBase {
        get(name: "tab_2_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
    }
    interface Attributes extends Xrm.AttributeCollectionBase {
      get(name: "createdon"): Xrm.DateAttribute;
      get(name: "defraimp_amendediv17receiveddate"): Xrm.DateAttribute;
      get(name: "defraimp_comments"): Xrm.Attribute<string>;
      get(name: "defraimp_compliantfirsttime"): Xrm.OptionSetAttribute<boolean>;
      get(name: "defraimp_cphnumber"): Xrm.Attribute<string>;
      get(name: "defraimp_customernumber"): Xrm.Attribute<string>;
      get(name: "defraimp_datecompleted"): Xrm.DateAttribute;
      get(name: "defraimp_dateofvisit"): Xrm.DateAttribute;
      get(name: "defraimp_datestartedworking"): Xrm.DateAttribute;
      get(name: "defraimp_datevisitallocated"): Xrm.DateAttribute;
      get(name: "defraimp_failedtovisit"): Xrm.Attribute<any>;
      get(name: "defraimp_fullycompliantvisit"): Xrm.OptionSetAttribute<boolean>;
      get(name: "defraimp_id46issued"): Xrm.Attribute<any>;
      get(name: "defraimp_id46issueddate"): Xrm.DateAttribute;
      get(name: "defraimp_inspectionoutcome"): Xrm.OptionSetAttribute<defraimp_importinspection_defraimp_inspectionoutcome>;
      get(name: "defraimp_iv16completeddate"): Xrm.DateAttribute;
      get(name: "defraimp_iv16issued"): Xrm.Attribute<any>;
      get(name: "defraimp_iv17chasedate"): Xrm.DateAttribute;
      get(name: "defraimp_iv17feedback"): Xrm.Attribute<string>;
      get(name: "defraimp_iv17receiveddate"): Xrm.DateAttribute;
      get(name: "defraimp_iv17returnedtofield"): Xrm.OptionSetAttribute<boolean>;
      get(name: "defraimp_iv17reviewapprovedbyid"): Xrm.LookupAttribute<"systemuser">;
      get(name: "defraimp_iv17reviewapproveddate"): Xrm.DateAttribute;
      get(name: "defraimp_name"): Xrm.Attribute<string>;
      get(name: "defraimp_newvisittoallocate"): Xrm.Attribute<any>;
      get(name: "defraimp_nextinspection"): Xrm.LookupAttribute<"defraimp_importinspection">;
      get(name: "defraimp_numberofanimalstested"): Xrm.NumberAttribute;
      get(name: "defraimp_othernoncompliancereason"): Xrm.Attribute<string>;
      get(name: "defraimp_previousinspection"): Xrm.LookupAttribute<"defraimp_importinspection">;
      get(name: "defraimp_reactorsorirsidentified"): Xrm.OptionSetAttribute<defraimp_importinspection_defraimp_reactorsorirsidentified>;
      get(name: "defraimp_reasonfornoncompliance"): Xrm.OptionSetAttribute<defraimp_reasonfornoncompliance>;
      get(name: "defraimp_reasoniv17returned"): Xrm.Attribute<string>;
      get(name: "defraimp_reasonnotvisited"): Xrm.Attribute<string>;
      get(name: "defraimp_reasontimeframemissed"): Xrm.Attribute<string>;
      get(name: "defraimp_regionareaallocatedtoid"): Xrm.LookupAttribute<"defraimp_apharegion">;
      get(name: "defraimp_relatedimportapplication"): Xrm.LookupAttribute<"defraimp_importapplication">;
      get(name: "defraimp_relateditahc"): Xrm.LookupAttribute<"defraimp_itahc">;
      get(name: "defraimp_replacementhealthcertificaterequested"): Xrm.OptionSetAttribute<boolean>;
      get(name: "defraimp_replyfromahodue"): Xrm.DateAttribute;
      get(name: "defraimp_restrictionslifted"): Xrm.MultiSelectOptionSetAttribute<defraimp_importinspection_defraimp_restrictionslifted>;
      get(name: "defraimp_restrictionsserved"): Xrm.MultiSelectOptionSetAttribute<defraimp_importinspection_defraimp_restrictionsserved>;
      get(name: "defraimp_resultsoftests"): Xrm.Attribute<string>;
      get(name: "defraimp_sampleresultsreceiveddate"): Xrm.DateAttribute;
      get(name: "defraimp_samplingrequired"): Xrm.Attribute<any>;
      get(name: "defraimp_samworkschedulenumber"): Xrm.Attribute<string>;
      get(name: "defraimp_tradeintelligence"): Xrm.Attribute<string>;
      get(name: "defraimp_visitwithinrequiredtimescale"): Xrm.Attribute<any>;
      get(name: "defraimp_welfareconcerns"): Xrm.Attribute<string>;
      get(name: "ownerid"): Xrm.LookupAttribute<"systemuser" | "team">;
      get(name: "statecode"): Xrm.OptionSetAttribute<defraimp_importinspection_statecode>;
      get(name: string): undefined;
      get(): Xrm.Attribute<any>[];
      get(index: number): Xrm.Attribute<any>;
      get(chooser: (item: Xrm.Attribute<any>, index: number) => boolean): Xrm.Attribute<any>[];
    }
    interface Controls extends Xrm.ControlCollectionBase {
      get(name: "SamplesTestsRequired"): Xrm.SubGridControl<"defraimp_sampletest">;
      get(name: "WebResource_FilesAndAttachments"): Xrm.WebResourceControl;
      get(name: "WebResource_MultipleUploads"): Xrm.WebResourceControl;
      get(name: "defraimp_amendediv17receiveddate"): Xrm.DateControl;
      get(name: "defraimp_comments"): Xrm.StringControl;
      get(name: "defraimp_compliantfirsttime"): Xrm.OptionSetControl<boolean>;
      get(name: "defraimp_cphnumber"): Xrm.StringControl;
      get(name: "defraimp_customernumber"): Xrm.StringControl;
      get(name: "defraimp_datecompleted"): Xrm.DateControl;
      get(name: "defraimp_dateofvisit"): Xrm.DateControl;
      get(name: "defraimp_datestartedworking"): Xrm.DateControl;
      get(name: "defraimp_datevisitallocated"): Xrm.DateControl;
      get(name: "defraimp_failedtovisit"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "defraimp_fullycompliantvisit"): Xrm.OptionSetControl<boolean>;
      get(name: "defraimp_id46issued"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "defraimp_id46issueddate"): Xrm.DateControl;
      get(name: "defraimp_inspectionoutcome"): Xrm.OptionSetControl<defraimp_importinspection_defraimp_inspectionoutcome>;
      get(name: "defraimp_iv16completeddate"): Xrm.DateControl;
      get(name: "defraimp_iv16issued"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "defraimp_iv17chasedate"): Xrm.DateControl;
      get(name: "defraimp_iv17feedback"): Xrm.StringControl;
      get(name: "defraimp_iv17receiveddate"): Xrm.DateControl;
      get(name: "defraimp_iv17returnedtofield"): Xrm.OptionSetControl<boolean>;
      get(name: "defraimp_iv17reviewapprovedbyid"): Xrm.LookupControl<"systemuser">;
      get(name: "defraimp_iv17reviewapproveddate"): Xrm.DateControl;
      get(name: "defraimp_name"): Xrm.StringControl;
      get(name: "defraimp_newvisittoallocate"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "defraimp_nextinspection"): Xrm.LookupControl<"defraimp_importinspection">;
      get(name: "defraimp_numberofanimalstested"): Xrm.NumberControl;
      get(name: "defraimp_othernoncompliancereason"): Xrm.StringControl;
      get(name: "defraimp_previousinspection"): Xrm.LookupControl<"defraimp_importinspection">;
      get(name: "defraimp_reactorsorirsidentified"): Xrm.OptionSetControl<defraimp_importinspection_defraimp_reactorsorirsidentified>;
      get(name: "defraimp_reasonfornoncompliance"): Xrm.OptionSetControl<defraimp_reasonfornoncompliance>;
      get(name: "defraimp_reasoniv17returned"): Xrm.StringControl;
      get(name: "defraimp_reasonnotvisited"): Xrm.StringControl;
      get(name: "defraimp_reasontimeframemissed"): Xrm.StringControl;
      get(name: "defraimp_regionareaallocatedtoid"): Xrm.LookupControl<"defraimp_apharegion">;
      get(name: "defraimp_relatedimportapplication"): Xrm.LookupControl<"defraimp_importapplication">;
      get(name: "defraimp_relateditahc"): Xrm.LookupControl<"defraimp_itahc">;
      get(name: "defraimp_replacementhealthcertificaterequested"): Xrm.OptionSetControl<boolean>;
      get(name: "defraimp_replyfromahodue"): Xrm.DateControl;
      get(name: "defraimp_restrictionslifted"): Xrm.MultiSelectOptionSetControl<defraimp_importinspection_defraimp_restrictionslifted>;
      get(name: "defraimp_restrictionsserved"): Xrm.MultiSelectOptionSetControl<defraimp_importinspection_defraimp_restrictionsserved>;
      get(name: "defraimp_resultsoftests"): Xrm.StringControl;
      get(name: "defraimp_sampleresultsreceiveddate"): Xrm.DateControl;
      get(name: "defraimp_samplingrequired"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "defraimp_samworkschedulenumber"): Xrm.StringControl;
      get(name: "defraimp_tradeintelligence"): Xrm.StringControl;
      get(name: "defraimp_visitwithinrequiredtimescale"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "defraimp_welfareconcerns"): Xrm.StringControl;
      get(name: "header_createdon"): Xrm.DateControl;
      get(name: "header_defraimp_name"): Xrm.StringControl;
      get(name: "header_ownerid"): Xrm.LookupControl<"systemuser" | "team">;
      get(name: "header_statecode"): Xrm.OptionSetControl<defraimp_importinspection_statecode>;
      get(name: "notescontrol"): Xrm.BaseControl;
      get(name: string): undefined;
      get(): Xrm.BaseControl[];
      get(index: number): Xrm.BaseControl;
      get(chooser: (item: Xrm.BaseControl, index: number) => boolean): Xrm.BaseControl[];
    }
    interface Tabs extends Xrm.TabCollectionBase {
      get(name: "IV17_Tab"): Xrm.PageTab<Tabs.IV17_Tab>;
      get(name: "Outcomes_Tab"): Xrm.PageTab<Tabs.Outcomes_Tab>;
      get(name: "Sampling_Tab"): Xrm.PageTab<Tabs.Sampling_Tab>;
      get(name: "{e4254c81-e79c-4d25-9530-02ff7f875fe8}"): Xrm.PageTab<Tabs.e4254c81e79c4d25953002ff7f875fe8>;
      get(name: "tab_2"): Xrm.PageTab<Tabs.tab_2>;
      get(name: string): undefined;
      get(): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
      get(index: number): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>;
      get(chooser: (item: Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>, index: number) => boolean): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
    }
  }
  interface Information extends Xrm.PageBase<Information.Attributes,Information.Tabs,Information.Controls> {
    getAttribute(attributeName: "createdon"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_amendediv17receiveddate"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_comments"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_compliantfirsttime"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "defraimp_cphnumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_customernumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_datecompleted"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_dateofvisit"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_datestartedworking"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_datevisitallocated"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_failedtovisit"): Xrm.Attribute<any>;
    getAttribute(attributeName: "defraimp_fullycompliantvisit"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "defraimp_id46issued"): Xrm.Attribute<any>;
    getAttribute(attributeName: "defraimp_id46issueddate"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_inspectionoutcome"): Xrm.OptionSetAttribute<defraimp_importinspection_defraimp_inspectionoutcome>;
    getAttribute(attributeName: "defraimp_iv16completeddate"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_iv16issued"): Xrm.Attribute<any>;
    getAttribute(attributeName: "defraimp_iv17chasedate"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_iv17feedback"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_iv17receiveddate"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_iv17returnedtofield"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "defraimp_iv17reviewapprovedbyid"): Xrm.LookupAttribute<"systemuser">;
    getAttribute(attributeName: "defraimp_iv17reviewapproveddate"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_name"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_newvisittoallocate"): Xrm.Attribute<any>;
    getAttribute(attributeName: "defraimp_nextinspection"): Xrm.LookupAttribute<"defraimp_importinspection">;
    getAttribute(attributeName: "defraimp_numberofanimalstested"): Xrm.NumberAttribute;
    getAttribute(attributeName: "defraimp_othernoncompliancereason"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_previousinspection"): Xrm.LookupAttribute<"defraimp_importinspection">;
    getAttribute(attributeName: "defraimp_reactorsorirsidentified"): Xrm.OptionSetAttribute<defraimp_importinspection_defraimp_reactorsorirsidentified>;
    getAttribute(attributeName: "defraimp_reasonfornoncompliance"): Xrm.OptionSetAttribute<defraimp_reasonfornoncompliance>;
    getAttribute(attributeName: "defraimp_reasoniv17returned"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_reasonnotvisited"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_reasontimeframemissed"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_regionareaallocatedtoid"): Xrm.LookupAttribute<"defraimp_apharegion">;
    getAttribute(attributeName: "defraimp_relatedimportapplication"): Xrm.LookupAttribute<"defraimp_importapplication">;
    getAttribute(attributeName: "defraimp_relateditahc"): Xrm.LookupAttribute<"defraimp_itahc">;
    getAttribute(attributeName: "defraimp_replacementhealthcertificaterequested"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "defraimp_replyfromahodue"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_restrictionslifted"): Xrm.MultiSelectOptionSetAttribute<defraimp_importinspection_defraimp_restrictionslifted>;
    getAttribute(attributeName: "defraimp_restrictionsserved"): Xrm.MultiSelectOptionSetAttribute<defraimp_importinspection_defraimp_restrictionsserved>;
    getAttribute(attributeName: "defraimp_resultsoftests"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_sampleresultsreceiveddate"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_samplingrequired"): Xrm.Attribute<any>;
    getAttribute(attributeName: "defraimp_samworkschedulenumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_tradeintelligence"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_visitwithinrequiredtimescale"): Xrm.Attribute<any>;
    getAttribute(attributeName: "defraimp_welfareconcerns"): Xrm.Attribute<string>;
    getAttribute(attributeName: "ownerid"): Xrm.LookupAttribute<"systemuser" | "team">;
    getAttribute(attributeName: "statecode"): Xrm.OptionSetAttribute<defraimp_importinspection_statecode>;
    getAttribute(attributeName: string): undefined;
    getControl(controlName: "SamplesTestsRequired"): Xrm.SubGridControl<"defraimp_sampletest">;
    getControl(controlName: "WebResource_FilesAndAttachments"): Xrm.WebResourceControl;
    getControl(controlName: "WebResource_MultipleUploads"): Xrm.WebResourceControl;
    getControl(controlName: "defraimp_amendediv17receiveddate"): Xrm.DateControl;
    getControl(controlName: "defraimp_comments"): Xrm.StringControl;
    getControl(controlName: "defraimp_compliantfirsttime"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "defraimp_cphnumber"): Xrm.StringControl;
    getControl(controlName: "defraimp_customernumber"): Xrm.StringControl;
    getControl(controlName: "defraimp_datecompleted"): Xrm.DateControl;
    getControl(controlName: "defraimp_dateofvisit"): Xrm.DateControl;
    getControl(controlName: "defraimp_datestartedworking"): Xrm.DateControl;
    getControl(controlName: "defraimp_datevisitallocated"): Xrm.DateControl;
    getControl(controlName: "defraimp_failedtovisit"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "defraimp_fullycompliantvisit"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "defraimp_id46issued"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "defraimp_id46issueddate"): Xrm.DateControl;
    getControl(controlName: "defraimp_inspectionoutcome"): Xrm.OptionSetControl<defraimp_importinspection_defraimp_inspectionoutcome>;
    getControl(controlName: "defraimp_iv16completeddate"): Xrm.DateControl;
    getControl(controlName: "defraimp_iv16issued"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "defraimp_iv17chasedate"): Xrm.DateControl;
    getControl(controlName: "defraimp_iv17feedback"): Xrm.StringControl;
    getControl(controlName: "defraimp_iv17receiveddate"): Xrm.DateControl;
    getControl(controlName: "defraimp_iv17returnedtofield"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "defraimp_iv17reviewapprovedbyid"): Xrm.LookupControl<"systemuser">;
    getControl(controlName: "defraimp_iv17reviewapproveddate"): Xrm.DateControl;
    getControl(controlName: "defraimp_name"): Xrm.StringControl;
    getControl(controlName: "defraimp_newvisittoallocate"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "defraimp_nextinspection"): Xrm.LookupControl<"defraimp_importinspection">;
    getControl(controlName: "defraimp_numberofanimalstested"): Xrm.NumberControl;
    getControl(controlName: "defraimp_othernoncompliancereason"): Xrm.StringControl;
    getControl(controlName: "defraimp_previousinspection"): Xrm.LookupControl<"defraimp_importinspection">;
    getControl(controlName: "defraimp_reactorsorirsidentified"): Xrm.OptionSetControl<defraimp_importinspection_defraimp_reactorsorirsidentified>;
    getControl(controlName: "defraimp_reasonfornoncompliance"): Xrm.OptionSetControl<defraimp_reasonfornoncompliance>;
    getControl(controlName: "defraimp_reasoniv17returned"): Xrm.StringControl;
    getControl(controlName: "defraimp_reasonnotvisited"): Xrm.StringControl;
    getControl(controlName: "defraimp_reasontimeframemissed"): Xrm.StringControl;
    getControl(controlName: "defraimp_regionareaallocatedtoid"): Xrm.LookupControl<"defraimp_apharegion">;
    getControl(controlName: "defraimp_relatedimportapplication"): Xrm.LookupControl<"defraimp_importapplication">;
    getControl(controlName: "defraimp_relateditahc"): Xrm.LookupControl<"defraimp_itahc">;
    getControl(controlName: "defraimp_replacementhealthcertificaterequested"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "defraimp_replyfromahodue"): Xrm.DateControl;
    getControl(controlName: "defraimp_restrictionslifted"): Xrm.MultiSelectOptionSetControl<defraimp_importinspection_defraimp_restrictionslifted>;
    getControl(controlName: "defraimp_restrictionsserved"): Xrm.MultiSelectOptionSetControl<defraimp_importinspection_defraimp_restrictionsserved>;
    getControl(controlName: "defraimp_resultsoftests"): Xrm.StringControl;
    getControl(controlName: "defraimp_sampleresultsreceiveddate"): Xrm.DateControl;
    getControl(controlName: "defraimp_samplingrequired"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "defraimp_samworkschedulenumber"): Xrm.StringControl;
    getControl(controlName: "defraimp_tradeintelligence"): Xrm.StringControl;
    getControl(controlName: "defraimp_visitwithinrequiredtimescale"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "defraimp_welfareconcerns"): Xrm.StringControl;
    getControl(controlName: "header_createdon"): Xrm.DateControl;
    getControl(controlName: "header_defraimp_name"): Xrm.StringControl;
    getControl(controlName: "header_ownerid"): Xrm.LookupControl<"systemuser" | "team">;
    getControl(controlName: "header_statecode"): Xrm.OptionSetControl<defraimp_importinspection_statecode>;
    getControl(controlName: "notescontrol"): Xrm.BaseControl;
    getControl(controlName: string): undefined;
  }
}
