declare namespace Form.defraimp_itahc.Main {
  namespace Information {
    namespace Tabs {
      interface _3c395ebac34345a3a58bea5860aa2036 extends Xrm.SectionCollectionBase {
        get(name: "{3c395eba-c343-45a3-a58b-ea5860aa2036}_column_2_section_1"): Xrm.PageSection;
        get(name: "{d0d7eecb-7ea7-40b8-bba2-42299867f7b8}"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_10 extends Xrm.SectionCollectionBase {
        get(name: "_section_384"): Xrm.PageSection;
        get(name: "tab_10_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_11 extends Xrm.SectionCollectionBase {
        get(name: "tab_11_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_12 extends Xrm.SectionCollectionBase {
        get(name: "tab_12_section_3"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_2 extends Xrm.SectionCollectionBase {
        get(name: "tab_2_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_3 extends Xrm.SectionCollectionBase {
        get(name: "_section_313"): Xrm.PageSection;
        get(name: "tab_3_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_4 extends Xrm.SectionCollectionBase {
        get(name: "_section_288"): Xrm.PageSection;
        get(name: "tab_4_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_5 extends Xrm.SectionCollectionBase {
        get(name: "_section_830"): Xrm.PageSection;
        get(name: "tab_5_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_7 extends Xrm.SectionCollectionBase {
        get(name: "_section_914"): Xrm.PageSection;
        get(name: "tab_7_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_8 extends Xrm.SectionCollectionBase {
        get(name: "_section_423"): Xrm.PageSection;
        get(name: "tab_8_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_9 extends Xrm.SectionCollectionBase {
        get(name: "_section_945"): Xrm.PageSection;
        get(name: "tab_9_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_commodities extends Xrm.SectionCollectionBase {
        get(name: "tab_12_section_1"): Xrm.PageSection;
        get(name: "tab_12_section_2"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
    }
    interface Attributes extends Xrm.AttributeCollectionBase {
      get(name: "createdon"): Xrm.DateAttribute;
      get(name: "defraimp_animalcertifiedas"): Xrm.OptionSetAttribute<defraimp_animalcertifiedas>;
      get(name: "defraimp_centralcompetentauthority"): Xrm.Attribute<string>;
      get(name: "defraimp_certificatestatus"): Xrm.OptionSetAttribute<defraimp_certificatestatus>;
      get(name: "defraimp_commoditycode"): Xrm.Attribute<string>;
      get(name: "defraimp_commoditycomplementstext"): Xrm.Attribute<string>;
      get(name: "defraimp_commodityidtypes"): Xrm.Attribute<string>;
      get(name: "defraimp_commoditytype"): Xrm.LookupAttribute<"defraexp_commoditytype">;
      get(name: "defraimp_consigneeaddresscity"): Xrm.Attribute<string>;
      get(name: "defraimp_consigneeaddresscountryid"): Xrm.LookupAttribute<"defra_country">;
      get(name: "defraimp_consigneeaddresspostcode"): Xrm.Attribute<string>;
      get(name: "defraimp_consigneeaddressstreet"): Xrm.Attribute<string>;
      get(name: "defraimp_consigneeapprovalnumber"): Xrm.Attribute<string>;
      get(name: "defraimp_consigneegeneralnumber"): Xrm.Attribute<string>;
      get(name: "defraimp_consigneename"): Xrm.Attribute<string>;
      get(name: "defraimp_consigneetracesid"): Xrm.NumberAttribute;
      get(name: "defraimp_consigneetype"): Xrm.Attribute<string>;
      get(name: "defraimp_consignoraddresscity"): Xrm.Attribute<string>;
      get(name: "defraimp_consignoraddresscountryid"): Xrm.LookupAttribute<"defra_country">;
      get(name: "defraimp_consignoraddresspostcode"): Xrm.Attribute<string>;
      get(name: "defraimp_consignoraddressstreet"): Xrm.Attribute<string>;
      get(name: "defraimp_consignorapprovalnumber"): Xrm.Attribute<string>;
      get(name: "defraimp_consignorgeneralnumber"): Xrm.Attribute<string>;
      get(name: "defraimp_consignorname"): Xrm.Attribute<string>;
      get(name: "defraimp_consignortracesid"): Xrm.NumberAttribute;
      get(name: "defraimp_consignortype"): Xrm.Attribute<string>;
      get(name: "defraimp_countryoforiginid"): Xrm.LookupAttribute<"defra_country">;
      get(name: "defraimp_declarationemail"): Xrm.Attribute<string>;
      get(name: "defraimp_declarationfax"): Xrm.Attribute<string>;
      get(name: "defraimp_declarationfirstname"): Xrm.Attribute<string>;
      get(name: "defraimp_declarationlastname"): Xrm.Attribute<string>;
      get(name: "defraimp_declarationphone"): Xrm.Attribute<string>;
      get(name: "defraimp_declarationsignaturedate"): Xrm.DateAttribute;
      get(name: "defraimp_departuredatetime"): Xrm.DateAttribute;
      get(name: "defraimp_devolvedoffice"): Xrm.LookupAttribute<"team">;
      get(name: "defraimp_estimatedjourneytime"): Xrm.NumberAttribute;
      get(name: "defraimp_formattedcommoditycomplementstext"): Xrm.Attribute<string>;
      get(name: "defraimp_formattedidentificationofanimalstext"): Xrm.Attribute<string>;
      get(name: "defraimp_healthcertificatenumber"): Xrm.Attribute<string>;
      get(name: "defraimp_identificationofanimalstext"): Xrm.Attribute<string>;
      get(name: "defraimp_localcompetentauthority"): Xrm.Attribute<string>;
      get(name: "defraimp_localveterinaryunit"): Xrm.Attribute<string>;
      get(name: "defraimp_lvuno"): Xrm.Attribute<string>;
      get(name: "defraimp_name"): Xrm.Attribute<any>;
      get(name: "defraimp_numberofpackages"): Xrm.NumberAttribute;
      get(name: "defraimp_officialvetcapacity"): Xrm.OptionSetAttribute<defraimp_officialvetcapacity>;
      get(name: "defraimp_officialvetcompetentauthority"): Xrm.Attribute<string>;
      get(name: "defraimp_officialvetemail"): Xrm.Attribute<string>;
      get(name: "defraimp_officialvetfax"): Xrm.Attribute<string>;
      get(name: "defraimp_officialvetfirstname"): Xrm.Attribute<string>;
      get(name: "defraimp_officialvetid"): Xrm.NumberAttribute;
      get(name: "defraimp_officialvetlastname"): Xrm.Attribute<string>;
      get(name: "defraimp_officialvetphone"): Xrm.Attribute<string>;
      get(name: "defraimp_officialvetsignaturedate"): Xrm.DateAttribute;
      get(name: "defraimp_ovname"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationaddresscity"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationaddresscountryid"): Xrm.LookupAttribute<"defra_country">;
      get(name: "defraimp_placeofdestinationaddresspostcode"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationaddressstreet"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationapprovalnumber"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationgeneralnumber"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationname"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationtracesid"): Xrm.NumberAttribute;
      get(name: "defraimp_placeofdestinationtype"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofloadingaddresscity"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofloadingaddresscountryid"): Xrm.LookupAttribute<"defra_country">;
      get(name: "defraimp_placeofloadingaddresspostcode"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofloadingaddressstreet"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofloadingapprovalnumber"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofloadinggeneralnumber"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofloadingname"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofloadingtracesid"): Xrm.NumberAttribute;
      get(name: "defraimp_placeofloadingtype"): Xrm.Attribute<string>;
      get(name: "defraimp_placeoforiginharvestaddresscity"): Xrm.Attribute<string>;
      get(name: "defraimp_placeoforiginharvestaddresscountryid"): Xrm.LookupAttribute<"defra_country">;
      get(name: "defraimp_placeoforiginharvestaddresspostcode"): Xrm.Attribute<string>;
      get(name: "defraimp_placeoforiginharvestaddressstreet"): Xrm.Attribute<string>;
      get(name: "defraimp_placeoforiginharvestapprovalnumber"): Xrm.Attribute<string>;
      get(name: "defraimp_placeoforiginharvestgeneralnumber"): Xrm.Attribute<string>;
      get(name: "defraimp_placeoforiginharvestname"): Xrm.Attribute<string>;
      get(name: "defraimp_placeoforiginharvesttracesid"): Xrm.NumberAttribute;
      get(name: "defraimp_placeoforiginharvesttype"): Xrm.Attribute<string>;
      get(name: "defraimp_quantity"): Xrm.NumberAttribute;
      get(name: "defraimp_relatedimportrecord"): Xrm.OptionSetAttribute<boolean>;
      get(name: "defraimp_replacedbyid"): Xrm.LookupAttribute<"defraimp_itahc">;
      get(name: "defraimp_replacesid"): Xrm.LookupAttribute<"defraimp_itahc">;
      get(name: "defraimp_tracesreceiveddate"): Xrm.DateAttribute;
      get(name: "defraimp_transporteraddresscity"): Xrm.Attribute<string>;
      get(name: "defraimp_transporteraddresscountryid"): Xrm.LookupAttribute<"defra_country">;
      get(name: "defraimp_transporteraddresspostcode"): Xrm.Attribute<string>;
      get(name: "defraimp_transporteraddressstreet"): Xrm.Attribute<string>;
      get(name: "defraimp_transporterapprovalnumber"): Xrm.Attribute<string>;
      get(name: "defraimp_transportergeneralnumber"): Xrm.Attribute<string>;
      get(name: "defraimp_transportername"): Xrm.Attribute<string>;
      get(name: "defraimp_transportertracesid"): Xrm.NumberAttribute;
      get(name: "defraimp_transportertype"): Xrm.Attribute<string>;
      get(name: "ownerid"): Xrm.LookupAttribute<"systemuser" | "team">;
      get(name: string): undefined;
      get(): Xrm.Attribute<any>[];
      get(index: number): Xrm.Attribute<any>;
      get(chooser: (item: Xrm.Attribute<any>, index: number) => boolean): Xrm.Attribute<any>[];
    }
    interface Controls extends Xrm.ControlCollectionBase {
      get(name: "WebResource_MultipleUploads"): Xrm.WebResourceControl;
      get(name: "WebResource_UploadFiles"): Xrm.WebResourceControl;
      get(name: "defraimp_animalcertifiedas"): Xrm.OptionSetControl<defraimp_animalcertifiedas>;
      get(name: "defraimp_centralcompetentauthority"): Xrm.StringControl;
      get(name: "defraimp_commoditycode"): Xrm.StringControl;
      get(name: "defraimp_commoditycomplementstext"): Xrm.StringControl;
      get(name: "defraimp_commodityidtypes"): Xrm.StringControl;
      get(name: "defraimp_commoditytype"): Xrm.LookupControl<"defraexp_commoditytype">;
      get(name: "defraimp_consigneeaddresscity"): Xrm.StringControl;
      get(name: "defraimp_consigneeaddresscountryid"): Xrm.LookupControl<"defra_country">;
      get(name: "defraimp_consigneeaddresspostcode"): Xrm.StringControl;
      get(name: "defraimp_consigneeaddressstreet"): Xrm.StringControl;
      get(name: "defraimp_consigneeapprovalnumber"): Xrm.StringControl;
      get(name: "defraimp_consigneegeneralnumber"): Xrm.StringControl;
      get(name: "defraimp_consigneename"): Xrm.StringControl;
      get(name: "defraimp_consigneetracesid"): Xrm.NumberControl;
      get(name: "defraimp_consigneetype"): Xrm.StringControl;
      get(name: "defraimp_consignoraddresscity"): Xrm.StringControl;
      get(name: "defraimp_consignoraddresscountryid"): Xrm.LookupControl<"defra_country">;
      get(name: "defraimp_consignoraddresspostcode"): Xrm.StringControl;
      get(name: "defraimp_consignoraddressstreet"): Xrm.StringControl;
      get(name: "defraimp_consignorapprovalnumber"): Xrm.StringControl;
      get(name: "defraimp_consignorgeneralnumber"): Xrm.StringControl;
      get(name: "defraimp_consignorname"): Xrm.StringControl;
      get(name: "defraimp_consignortracesid"): Xrm.NumberControl;
      get(name: "defraimp_consignortype"): Xrm.StringControl;
      get(name: "defraimp_countryoforiginid"): Xrm.LookupControl<"defra_country">;
      get(name: "defraimp_declarationemail"): Xrm.StringControl;
      get(name: "defraimp_declarationfax"): Xrm.StringControl;
      get(name: "defraimp_declarationfirstname"): Xrm.StringControl;
      get(name: "defraimp_declarationlastname"): Xrm.StringControl;
      get(name: "defraimp_declarationphone"): Xrm.StringControl;
      get(name: "defraimp_declarationsignaturedate"): Xrm.DateControl;
      get(name: "defraimp_departuredatetime"): Xrm.DateControl;
      get(name: "defraimp_devolvedoffice"): Xrm.LookupControl<"team">;
      get(name: "defraimp_estimatedjourneytime"): Xrm.NumberControl;
      get(name: "defraimp_formattedcommoditycomplementstext"): Xrm.StringControl;
      get(name: "defraimp_formattedidentificationofanimalstext"): Xrm.StringControl;
      get(name: "defraimp_healthcertificatenumber"): Xrm.StringControl;
      get(name: "defraimp_identificationofanimalstext"): Xrm.StringControl;
      get(name: "defraimp_localcompetentauthority"): Xrm.StringControl;
      get(name: "defraimp_localveterinaryunit"): Xrm.StringControl;
      get(name: "defraimp_lvuno"): Xrm.StringControl;
      get(name: "defraimp_name"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "defraimp_numberofpackages"): Xrm.NumberControl;
      get(name: "defraimp_officialvetcapacity"): Xrm.OptionSetControl<defraimp_officialvetcapacity>;
      get(name: "defraimp_officialvetcompetentauthority"): Xrm.StringControl;
      get(name: "defraimp_officialvetemail"): Xrm.StringControl;
      get(name: "defraimp_officialvetfax"): Xrm.StringControl;
      get(name: "defraimp_officialvetfirstname"): Xrm.StringControl;
      get(name: "defraimp_officialvetid"): Xrm.NumberControl;
      get(name: "defraimp_officialvetlastname"): Xrm.StringControl;
      get(name: "defraimp_officialvetphone"): Xrm.StringControl;
      get(name: "defraimp_officialvetsignaturedate"): Xrm.DateControl;
      get(name: "defraimp_ovname"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationaddresscity"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationaddresscountryid"): Xrm.LookupControl<"defra_country">;
      get(name: "defraimp_placeofdestinationaddresspostcode"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationaddressstreet"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationapprovalnumber"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationgeneralnumber"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationname"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationtracesid"): Xrm.NumberControl;
      get(name: "defraimp_placeofdestinationtype"): Xrm.StringControl;
      get(name: "defraimp_placeofloadingaddresscity"): Xrm.StringControl;
      get(name: "defraimp_placeofloadingaddresscountryid"): Xrm.LookupControl<"defra_country">;
      get(name: "defraimp_placeofloadingaddresspostcode"): Xrm.StringControl;
      get(name: "defraimp_placeofloadingaddressstreet"): Xrm.StringControl;
      get(name: "defraimp_placeofloadingapprovalnumber"): Xrm.StringControl;
      get(name: "defraimp_placeofloadinggeneralnumber"): Xrm.StringControl;
      get(name: "defraimp_placeofloadingname"): Xrm.StringControl;
      get(name: "defraimp_placeofloadingtracesid"): Xrm.NumberControl;
      get(name: "defraimp_placeofloadingtype"): Xrm.StringControl;
      get(name: "defraimp_placeoforiginharvestaddresscity"): Xrm.StringControl;
      get(name: "defraimp_placeoforiginharvestaddresscountryid"): Xrm.LookupControl<"defra_country">;
      get(name: "defraimp_placeoforiginharvestaddresspostcode"): Xrm.StringControl;
      get(name: "defraimp_placeoforiginharvestaddressstreet"): Xrm.StringControl;
      get(name: "defraimp_placeoforiginharvestapprovalnumber"): Xrm.StringControl;
      get(name: "defraimp_placeoforiginharvestgeneralnumber"): Xrm.StringControl;
      get(name: "defraimp_placeoforiginharvestname"): Xrm.StringControl;
      get(name: "defraimp_placeoforiginharvesttracesid"): Xrm.NumberControl;
      get(name: "defraimp_placeoforiginharvesttype"): Xrm.StringControl;
      get(name: "defraimp_quantity"): Xrm.NumberControl;
      get(name: "defraimp_relatedimportrecord"): Xrm.OptionSetControl<boolean>;
      get(name: "defraimp_replacedbyid"): Xrm.LookupControl<"defraimp_itahc">;
      get(name: "defraimp_replacesid"): Xrm.LookupControl<"defraimp_itahc">;
      get(name: "defraimp_tracesreceiveddate"): Xrm.DateControl;
      get(name: "defraimp_transporteraddresscity"): Xrm.StringControl;
      get(name: "defraimp_transporteraddresscountryid"): Xrm.LookupControl<"defra_country">;
      get(name: "defraimp_transporteraddresspostcode"): Xrm.StringControl;
      get(name: "defraimp_transporteraddressstreet"): Xrm.StringControl;
      get(name: "defraimp_transporterapprovalnumber"): Xrm.StringControl;
      get(name: "defraimp_transportergeneralnumber"): Xrm.StringControl;
      get(name: "defraimp_transportername"): Xrm.StringControl;
      get(name: "defraimp_transportertracesid"): Xrm.NumberControl;
      get(name: "defraimp_transportertype"): Xrm.StringControl;
      get(name: "header_createdon"): Xrm.DateControl;
      get(name: "header_defraimp_certificatestatus"): Xrm.OptionSetControl<defraimp_certificatestatus>;
      get(name: "header_ownerid"): Xrm.LookupControl<"systemuser" | "team">;
      get(name: string): undefined;
      get(): Xrm.BaseControl[];
      get(index: number): Xrm.BaseControl;
      get(chooser: (item: Xrm.BaseControl, index: number) => boolean): Xrm.BaseControl[];
    }
    interface Tabs extends Xrm.TabCollectionBase {
      get(name: "{3c395eba-c343-45a3-a58b-ea5860aa2036}"): Xrm.PageTab<Tabs._3c395ebac34345a3a58bea5860aa2036>;
      get(name: "tab_10"): Xrm.PageTab<Tabs.tab_10>;
      get(name: "tab_11"): Xrm.PageTab<Tabs.tab_11>;
      get(name: "tab_12"): Xrm.PageTab<Tabs.tab_12>;
      get(name: "tab_2"): Xrm.PageTab<Tabs.tab_2>;
      get(name: "tab_3"): Xrm.PageTab<Tabs.tab_3>;
      get(name: "tab_4"): Xrm.PageTab<Tabs.tab_4>;
      get(name: "tab_5"): Xrm.PageTab<Tabs.tab_5>;
      get(name: "tab_7"): Xrm.PageTab<Tabs.tab_7>;
      get(name: "tab_8"): Xrm.PageTab<Tabs.tab_8>;
      get(name: "tab_9"): Xrm.PageTab<Tabs.tab_9>;
      get(name: "tab_commodities"): Xrm.PageTab<Tabs.tab_commodities>;
      get(name: string): undefined;
      get(): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
      get(index: number): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>;
      get(chooser: (item: Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>, index: number) => boolean): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
    }
  }
  interface Information extends Xrm.PageBase<Information.Attributes,Information.Tabs,Information.Controls> {
    getAttribute(attributeName: "createdon"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_animalcertifiedas"): Xrm.OptionSetAttribute<defraimp_animalcertifiedas>;
    getAttribute(attributeName: "defraimp_centralcompetentauthority"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_certificatestatus"): Xrm.OptionSetAttribute<defraimp_certificatestatus>;
    getAttribute(attributeName: "defraimp_commoditycode"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_commoditycomplementstext"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_commodityidtypes"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_commoditytype"): Xrm.LookupAttribute<"defraexp_commoditytype">;
    getAttribute(attributeName: "defraimp_consigneeaddresscity"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consigneeaddresscountryid"): Xrm.LookupAttribute<"defra_country">;
    getAttribute(attributeName: "defraimp_consigneeaddresspostcode"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consigneeaddressstreet"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consigneeapprovalnumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consigneegeneralnumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consigneename"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consigneetracesid"): Xrm.NumberAttribute;
    getAttribute(attributeName: "defraimp_consigneetype"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignoraddresscity"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignoraddresscountryid"): Xrm.LookupAttribute<"defra_country">;
    getAttribute(attributeName: "defraimp_consignoraddresspostcode"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignoraddressstreet"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignorapprovalnumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignorgeneralnumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignorname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignortracesid"): Xrm.NumberAttribute;
    getAttribute(attributeName: "defraimp_consignortype"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_countryoforiginid"): Xrm.LookupAttribute<"defra_country">;
    getAttribute(attributeName: "defraimp_declarationemail"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_declarationfax"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_declarationfirstname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_declarationlastname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_declarationphone"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_declarationsignaturedate"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_departuredatetime"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_devolvedoffice"): Xrm.LookupAttribute<"team">;
    getAttribute(attributeName: "defraimp_estimatedjourneytime"): Xrm.NumberAttribute;
    getAttribute(attributeName: "defraimp_formattedcommoditycomplementstext"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_formattedidentificationofanimalstext"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_healthcertificatenumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_identificationofanimalstext"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_localcompetentauthority"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_localveterinaryunit"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_lvuno"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_name"): Xrm.Attribute<any>;
    getAttribute(attributeName: "defraimp_numberofpackages"): Xrm.NumberAttribute;
    getAttribute(attributeName: "defraimp_officialvetcapacity"): Xrm.OptionSetAttribute<defraimp_officialvetcapacity>;
    getAttribute(attributeName: "defraimp_officialvetcompetentauthority"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_officialvetemail"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_officialvetfax"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_officialvetfirstname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_officialvetid"): Xrm.NumberAttribute;
    getAttribute(attributeName: "defraimp_officialvetlastname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_officialvetphone"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_officialvetsignaturedate"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_ovname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationaddresscity"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationaddresscountryid"): Xrm.LookupAttribute<"defra_country">;
    getAttribute(attributeName: "defraimp_placeofdestinationaddresspostcode"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationaddressstreet"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationapprovalnumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationgeneralnumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationtracesid"): Xrm.NumberAttribute;
    getAttribute(attributeName: "defraimp_placeofdestinationtype"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofloadingaddresscity"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofloadingaddresscountryid"): Xrm.LookupAttribute<"defra_country">;
    getAttribute(attributeName: "defraimp_placeofloadingaddresspostcode"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofloadingaddressstreet"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofloadingapprovalnumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofloadinggeneralnumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofloadingname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofloadingtracesid"): Xrm.NumberAttribute;
    getAttribute(attributeName: "defraimp_placeofloadingtype"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeoforiginharvestaddresscity"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeoforiginharvestaddresscountryid"): Xrm.LookupAttribute<"defra_country">;
    getAttribute(attributeName: "defraimp_placeoforiginharvestaddresspostcode"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeoforiginharvestaddressstreet"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeoforiginharvestapprovalnumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeoforiginharvestgeneralnumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeoforiginharvestname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeoforiginharvesttracesid"): Xrm.NumberAttribute;
    getAttribute(attributeName: "defraimp_placeoforiginharvesttype"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_quantity"): Xrm.NumberAttribute;
    getAttribute(attributeName: "defraimp_relatedimportrecord"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "defraimp_replacedbyid"): Xrm.LookupAttribute<"defraimp_itahc">;
    getAttribute(attributeName: "defraimp_replacesid"): Xrm.LookupAttribute<"defraimp_itahc">;
    getAttribute(attributeName: "defraimp_tracesreceiveddate"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_transporteraddresscity"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_transporteraddresscountryid"): Xrm.LookupAttribute<"defra_country">;
    getAttribute(attributeName: "defraimp_transporteraddresspostcode"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_transporteraddressstreet"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_transporterapprovalnumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_transportergeneralnumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_transportername"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_transportertracesid"): Xrm.NumberAttribute;
    getAttribute(attributeName: "defraimp_transportertype"): Xrm.Attribute<string>;
    getAttribute(attributeName: "ownerid"): Xrm.LookupAttribute<"systemuser" | "team">;
    getAttribute(attributeName: string): undefined;
    getControl(controlName: "WebResource_MultipleUploads"): Xrm.WebResourceControl;
    getControl(controlName: "WebResource_UploadFiles"): Xrm.WebResourceControl;
    getControl(controlName: "defraimp_animalcertifiedas"): Xrm.OptionSetControl<defraimp_animalcertifiedas>;
    getControl(controlName: "defraimp_centralcompetentauthority"): Xrm.StringControl;
    getControl(controlName: "defraimp_commoditycode"): Xrm.StringControl;
    getControl(controlName: "defraimp_commoditycomplementstext"): Xrm.StringControl;
    getControl(controlName: "defraimp_commodityidtypes"): Xrm.StringControl;
    getControl(controlName: "defraimp_commoditytype"): Xrm.LookupControl<"defraexp_commoditytype">;
    getControl(controlName: "defraimp_consigneeaddresscity"): Xrm.StringControl;
    getControl(controlName: "defraimp_consigneeaddresscountryid"): Xrm.LookupControl<"defra_country">;
    getControl(controlName: "defraimp_consigneeaddresspostcode"): Xrm.StringControl;
    getControl(controlName: "defraimp_consigneeaddressstreet"): Xrm.StringControl;
    getControl(controlName: "defraimp_consigneeapprovalnumber"): Xrm.StringControl;
    getControl(controlName: "defraimp_consigneegeneralnumber"): Xrm.StringControl;
    getControl(controlName: "defraimp_consigneename"): Xrm.StringControl;
    getControl(controlName: "defraimp_consigneetracesid"): Xrm.NumberControl;
    getControl(controlName: "defraimp_consigneetype"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignoraddresscity"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignoraddresscountryid"): Xrm.LookupControl<"defra_country">;
    getControl(controlName: "defraimp_consignoraddresspostcode"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignoraddressstreet"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignorapprovalnumber"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignorgeneralnumber"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignorname"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignortracesid"): Xrm.NumberControl;
    getControl(controlName: "defraimp_consignortype"): Xrm.StringControl;
    getControl(controlName: "defraimp_countryoforiginid"): Xrm.LookupControl<"defra_country">;
    getControl(controlName: "defraimp_declarationemail"): Xrm.StringControl;
    getControl(controlName: "defraimp_declarationfax"): Xrm.StringControl;
    getControl(controlName: "defraimp_declarationfirstname"): Xrm.StringControl;
    getControl(controlName: "defraimp_declarationlastname"): Xrm.StringControl;
    getControl(controlName: "defraimp_declarationphone"): Xrm.StringControl;
    getControl(controlName: "defraimp_declarationsignaturedate"): Xrm.DateControl;
    getControl(controlName: "defraimp_departuredatetime"): Xrm.DateControl;
    getControl(controlName: "defraimp_devolvedoffice"): Xrm.LookupControl<"team">;
    getControl(controlName: "defraimp_estimatedjourneytime"): Xrm.NumberControl;
    getControl(controlName: "defraimp_formattedcommoditycomplementstext"): Xrm.StringControl;
    getControl(controlName: "defraimp_formattedidentificationofanimalstext"): Xrm.StringControl;
    getControl(controlName: "defraimp_healthcertificatenumber"): Xrm.StringControl;
    getControl(controlName: "defraimp_identificationofanimalstext"): Xrm.StringControl;
    getControl(controlName: "defraimp_localcompetentauthority"): Xrm.StringControl;
    getControl(controlName: "defraimp_localveterinaryunit"): Xrm.StringControl;
    getControl(controlName: "defraimp_lvuno"): Xrm.StringControl;
    getControl(controlName: "defraimp_name"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "defraimp_numberofpackages"): Xrm.NumberControl;
    getControl(controlName: "defraimp_officialvetcapacity"): Xrm.OptionSetControl<defraimp_officialvetcapacity>;
    getControl(controlName: "defraimp_officialvetcompetentauthority"): Xrm.StringControl;
    getControl(controlName: "defraimp_officialvetemail"): Xrm.StringControl;
    getControl(controlName: "defraimp_officialvetfax"): Xrm.StringControl;
    getControl(controlName: "defraimp_officialvetfirstname"): Xrm.StringControl;
    getControl(controlName: "defraimp_officialvetid"): Xrm.NumberControl;
    getControl(controlName: "defraimp_officialvetlastname"): Xrm.StringControl;
    getControl(controlName: "defraimp_officialvetphone"): Xrm.StringControl;
    getControl(controlName: "defraimp_officialvetsignaturedate"): Xrm.DateControl;
    getControl(controlName: "defraimp_ovname"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationaddresscity"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationaddresscountryid"): Xrm.LookupControl<"defra_country">;
    getControl(controlName: "defraimp_placeofdestinationaddresspostcode"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationaddressstreet"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationapprovalnumber"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationgeneralnumber"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationname"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationtracesid"): Xrm.NumberControl;
    getControl(controlName: "defraimp_placeofdestinationtype"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofloadingaddresscity"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofloadingaddresscountryid"): Xrm.LookupControl<"defra_country">;
    getControl(controlName: "defraimp_placeofloadingaddresspostcode"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofloadingaddressstreet"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofloadingapprovalnumber"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofloadinggeneralnumber"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofloadingname"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofloadingtracesid"): Xrm.NumberControl;
    getControl(controlName: "defraimp_placeofloadingtype"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeoforiginharvestaddresscity"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeoforiginharvestaddresscountryid"): Xrm.LookupControl<"defra_country">;
    getControl(controlName: "defraimp_placeoforiginharvestaddresspostcode"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeoforiginharvestaddressstreet"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeoforiginharvestapprovalnumber"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeoforiginharvestgeneralnumber"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeoforiginharvestname"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeoforiginharvesttracesid"): Xrm.NumberControl;
    getControl(controlName: "defraimp_placeoforiginharvesttype"): Xrm.StringControl;
    getControl(controlName: "defraimp_quantity"): Xrm.NumberControl;
    getControl(controlName: "defraimp_relatedimportrecord"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "defraimp_replacedbyid"): Xrm.LookupControl<"defraimp_itahc">;
    getControl(controlName: "defraimp_replacesid"): Xrm.LookupControl<"defraimp_itahc">;
    getControl(controlName: "defraimp_tracesreceiveddate"): Xrm.DateControl;
    getControl(controlName: "defraimp_transporteraddresscity"): Xrm.StringControl;
    getControl(controlName: "defraimp_transporteraddresscountryid"): Xrm.LookupControl<"defra_country">;
    getControl(controlName: "defraimp_transporteraddresspostcode"): Xrm.StringControl;
    getControl(controlName: "defraimp_transporteraddressstreet"): Xrm.StringControl;
    getControl(controlName: "defraimp_transporterapprovalnumber"): Xrm.StringControl;
    getControl(controlName: "defraimp_transportergeneralnumber"): Xrm.StringControl;
    getControl(controlName: "defraimp_transportername"): Xrm.StringControl;
    getControl(controlName: "defraimp_transportertracesid"): Xrm.NumberControl;
    getControl(controlName: "defraimp_transportertype"): Xrm.StringControl;
    getControl(controlName: "header_createdon"): Xrm.DateControl;
    getControl(controlName: "header_defraimp_certificatestatus"): Xrm.OptionSetControl<defraimp_certificatestatus>;
    getControl(controlName: "header_ownerid"): Xrm.LookupControl<"systemuser" | "team">;
    getControl(controlName: string): undefined;
  }
}
