declare namespace Form.defraimp_importernotification.Main {
  namespace Information {
    namespace Tabs {
      interface commoditycomplements_tab extends Xrm.SectionCollectionBase {
        get(name: "commoditycomplements_tab_section_3"): Xrm.PageSection;
        get(name: "tab_10_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface consignee_tab extends Xrm.SectionCollectionBase {
        get(name: "tab_4_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface consigners_tab extends Xrm.SectionCollectionBase {
        get(name: "tab_2_section_1"): Xrm.PageSection;
        get(name: "tab_2_section_2"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface details_tab extends Xrm.SectionCollectionBase {
        get(name: "_section_632"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface importer_tab extends Xrm.SectionCollectionBase {
        get(name: "_section_150"): Xrm.PageSection;
        get(name: "tab_5_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface meansoftransport_tab extends Xrm.SectionCollectionBase {
        get(name: "tab_9_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface permanentaddresses_tab extends Xrm.SectionCollectionBase {
        get(name: "tab_11_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface personresponsible_tab extends Xrm.SectionCollectionBase {
        get(name: "_section_562"): Xrm.PageSection;
        get(name: "tab_3_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface placeofdestination_tab extends Xrm.SectionCollectionBase {
        get(name: "_section_921"): Xrm.PageSection;
        get(name: "tab_6_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface placeoforigin_tab extends Xrm.SectionCollectionBase {
        get(name: "_section_514"): Xrm.PageSection;
        get(name: "tab_7_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_12 extends Xrm.SectionCollectionBase {
        get(name: "tab_12_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface transporter_tab extends Xrm.SectionCollectionBase {
        get(name: "_section_608"): Xrm.PageSection;
        get(name: "tab_8_section_1"): Xrm.PageSection;
        get(name: "transporter_tab_section_transit"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
    }
    interface Attributes extends Xrm.AttributeCollectionBase {
      get(name: "createdon"): Xrm.DateAttribute;
      get(name: "defraimp_arrivaldate"): Xrm.DateAttribute;
      get(name: "defraimp_commoditiesanimalscertifiedas"): Xrm.OptionSetAttribute<defraimp_animalcertifiedas>;
      get(name: "defraimp_commoditiesnumberofanimals"): Xrm.NumberAttribute;
      get(name: "defraimp_commoditiesregionoforigin"): Xrm.Attribute<string>;
      get(name: "defraimp_commoditycomplementstext"): Xrm.Attribute<string>;
      get(name: "defraimp_commodityid"): Xrm.Attribute<string>;
      get(name: "defraimp_commodityidtypes"): Xrm.Attribute<string>;
      get(name: "defraimp_commodityspeciesid"): Xrm.Attribute<string>;
      get(name: "defraimp_commodityspeciesname"): Xrm.Attribute<string>;
      get(name: "defraimp_consigneeaddressaddressline1"): Xrm.Attribute<string>;
      get(name: "defraimp_consigneeaddressaddressline2"): Xrm.Attribute<string>;
      get(name: "defraimp_consigneeaddressaddressline3"): Xrm.Attribute<string>;
      get(name: "defraimp_consigneeaddresscity"): Xrm.Attribute<string>;
      get(name: "defraimp_consigneeaddresscountryid"): Xrm.LookupAttribute<"defra_country">;
      get(name: "defraimp_consigneeaddressemail"): Xrm.Attribute<string>;
      get(name: "defraimp_consigneeaddresspostalzipcode"): Xrm.Attribute<string>;
      get(name: "defraimp_consigneeaddresstelephone"): Xrm.Attribute<string>;
      get(name: "defraimp_consigneeaddressuktelephone"): Xrm.Attribute<string>;
      get(name: "defraimp_consigneeapprovalnumber"): Xrm.Attribute<string>;
      get(name: "defraimp_consigneecompanyname"): Xrm.Attribute<string>;
      get(name: "defraimp_consigneeindividualname"): Xrm.Attribute<string>;
      get(name: "defraimp_consigneeinternationalphonenumber"): Xrm.Attribute<string>;
      get(name: "defraimp_consigneeotheridentifier"): Xrm.Attribute<string>;
      get(name: "defraimp_consigneestatus"): Xrm.Attribute<string>;
      get(name: "defraimp_consigneetype"): Xrm.Attribute<string>;
      get(name: "defraimp_consignoraddressaddressline1"): Xrm.Attribute<string>;
      get(name: "defraimp_consignoraddressaddressline2"): Xrm.Attribute<string>;
      get(name: "defraimp_consignoraddressaddressline3"): Xrm.Attribute<string>;
      get(name: "defraimp_consignoraddresscity"): Xrm.Attribute<string>;
      get(name: "defraimp_consignoraddresscountryid"): Xrm.LookupAttribute<"defra_country">;
      get(name: "defraimp_consignoraddressemail"): Xrm.Attribute<string>;
      get(name: "defraimp_consignoraddresspostalzipcode"): Xrm.Attribute<string>;
      get(name: "defraimp_consignoraddresstelephone"): Xrm.Attribute<string>;
      get(name: "defraimp_consignoraddressuktelephone"): Xrm.Attribute<string>;
      get(name: "defraimp_consignorapprovalnumber"): Xrm.Attribute<string>;
      get(name: "defraimp_consignorcompanyname"): Xrm.Attribute<string>;
      get(name: "defraimp_consignorindividualname"): Xrm.Attribute<string>;
      get(name: "defraimp_consignorinternationalphonenumber"): Xrm.Attribute<string>;
      get(name: "defraimp_consignorotheridentifier"): Xrm.Attribute<string>;
      get(name: "defraimp_consignorstatus"): Xrm.Attribute<string>;
      get(name: "defraimp_consignortwoaddressaddressline1"): Xrm.Attribute<string>;
      get(name: "defraimp_consignortwoaddressaddressline2"): Xrm.Attribute<string>;
      get(name: "defraimp_consignortwoaddressaddressline3"): Xrm.Attribute<string>;
      get(name: "defraimp_consignortwoaddresscity"): Xrm.Attribute<string>;
      get(name: "defraimp_consignortwoaddresscountry"): Xrm.LookupAttribute<"defra_country">;
      get(name: "defraimp_consignortwoaddressemail"): Xrm.Attribute<string>;
      get(name: "defraimp_consignortwoaddresspostalzipcode"): Xrm.Attribute<string>;
      get(name: "defraimp_consignortwoaddresstelephone"): Xrm.Attribute<string>;
      get(name: "defraimp_consignortwoaddressuktelephone"): Xrm.Attribute<string>;
      get(name: "defraimp_consignortwoapprovalnumber"): Xrm.Attribute<string>;
      get(name: "defraimp_consignortwocompanyname"): Xrm.Attribute<string>;
      get(name: "defraimp_consignortwoindividualname"): Xrm.Attribute<string>;
      get(name: "defraimp_consignortwointernationalphonenumber"): Xrm.Attribute<string>;
      get(name: "defraimp_consignortwootheridentifier"): Xrm.Attribute<string>;
      get(name: "defraimp_consignortwostatus"): Xrm.Attribute<string>;
      get(name: "defraimp_consignortwotype"): Xrm.Attribute<string>;
      get(name: "defraimp_consignortype"): Xrm.Attribute<string>;
      get(name: "defraimp_countryoforiginid"): Xrm.LookupAttribute<"defra_country">;
      get(name: "defraimp_cphnumber"): Xrm.Attribute<string>;
      get(name: "defraimp_formattedcommoditycomplementstext"): Xrm.Attribute<string>;
      get(name: "defraimp_formattedidentificationofanimalstext"): Xrm.Attribute<string>;
      get(name: "defraimp_identificationofanimalstext"): Xrm.Attribute<string>;
      get(name: "defraimp_importeraddressaddressline1"): Xrm.Attribute<string>;
      get(name: "defraimp_importeraddressaddressline2"): Xrm.Attribute<string>;
      get(name: "defraimp_importeraddressaddressline3"): Xrm.Attribute<string>;
      get(name: "defraimp_importeraddresscity"): Xrm.Attribute<string>;
      get(name: "defraimp_importeraddresscountryid"): Xrm.LookupAttribute<"defra_country">;
      get(name: "defraimp_importeraddressemail"): Xrm.Attribute<string>;
      get(name: "defraimp_importeraddresspostalzipcode"): Xrm.Attribute<string>;
      get(name: "defraimp_importeraddresstelephone"): Xrm.Attribute<string>;
      get(name: "defraimp_importerapprovalnumber"): Xrm.Attribute<string>;
      get(name: "defraimp_importercompanyname"): Xrm.Attribute<string>;
      get(name: "defraimp_importerstatus"): Xrm.Attribute<string>;
      get(name: "defraimp_importertype"): Xrm.Attribute<string>;
      get(name: "defraimp_importingfromcharity"): Xrm.Attribute<any>;
      get(name: "defraimp_isplaceofdestinationthepermanentaddress"): Xrm.Attribute<any>;
      get(name: "defraimp_lastupdated"): Xrm.DateAttribute;
      get(name: "defraimp_lastupdatedbydisplayname"): Xrm.Attribute<string>;
      get(name: "defraimp_meansoftransportfromentrypointdocument"): Xrm.Attribute<string>;
      get(name: "defraimp_meansoftransportfromentrypointtype"): Xrm.Attribute<string>;
      get(name: "defraimp_name"): Xrm.Attribute<string>;
      get(name: "defraimp_personresponsibleaddress"): Xrm.Attribute<string>;
      get(name: "defraimp_personresponsiblecompanyname"): Xrm.Attribute<string>;
      get(name: "defraimp_personresponsiblecountryid"): Xrm.LookupAttribute<"defra_country">;
      get(name: "defraimp_personresponsibleemail"): Xrm.Attribute<string>;
      get(name: "defraimp_personresponsiblephone"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationaddressaddressline1"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationaddressaddressline2"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationaddressaddressline3"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationaddresscity"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationaddressemail"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationaddresspostalzipcode"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationaddresstelephone"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationapprovalnumber"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationcompanyname"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationcountryid"): Xrm.LookupAttribute<"defra_country">;
      get(name: "defraimp_placeofdestinationstatus"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationtype"): Xrm.Attribute<string>;
      get(name: "defraimp_portofentry"): Xrm.Attribute<string>;
      get(name: "defraimp_responsiblefortransport"): Xrm.Attribute<string>;
      get(name: "defraimp_routetransitingstates"): Xrm.Attribute<string>;
      get(name: "defraimp_status"): Xrm.OptionSetAttribute<defraimp_importernotificationstatus>;
      get(name: "defraimp_submissiondate"): Xrm.DateAttribute;
      get(name: "defraimp_submittedbydisplayname"): Xrm.Attribute<string>;
      get(name: "defraimp_submittedbyiscontroluser"): Xrm.OptionSetAttribute<boolean>;
      get(name: "defraimp_transporteraddressaddressline1"): Xrm.Attribute<string>;
      get(name: "defraimp_transporteraddressaddressline2"): Xrm.Attribute<string>;
      get(name: "defraimp_transporteraddressaddressline3"): Xrm.Attribute<string>;
      get(name: "defraimp_transporteraddresscity"): Xrm.Attribute<string>;
      get(name: "defraimp_transporteraddresscountryid"): Xrm.LookupAttribute<"defra_country">;
      get(name: "defraimp_transporteraddressemail"): Xrm.Attribute<string>;
      get(name: "defraimp_transporteraddresspostalzipcode"): Xrm.Attribute<string>;
      get(name: "defraimp_transporteraddresstelephone"): Xrm.Attribute<string>;
      get(name: "defraimp_transporterapprovalnumber"): Xrm.Attribute<string>;
      get(name: "defraimp_transportercompanyname"): Xrm.Attribute<string>;
      get(name: "defraimp_transporterstatus"): Xrm.Attribute<string>;
      get(name: "defraimp_transportertype"): Xrm.Attribute<string>;
      get(name: "defraimp_type"): Xrm.OptionSetAttribute<defraimp_importernotificationtype>;
      get(name: "defraimp_version"): Xrm.NumberAttribute;
      get(name: "defraimp_veterinaryinformationveterinarydocument"): Xrm.Attribute<string>;
      get(name: "ownerid"): Xrm.LookupAttribute<"systemuser" | "team">;
      get(name: string): undefined;
      get(): Xrm.Attribute<any>[];
      get(index: number): Xrm.Attribute<any>;
      get(chooser: (item: Xrm.Attribute<any>, index: number) => boolean): Xrm.Attribute<any>[];
    }
    interface Controls extends Xrm.ControlCollectionBase {
      get(name: "Subgrid_2"): Xrm.SubGridControl<"defraimp_commoditycomplementparameterset">;
      get(name: "Subgrid_3"): Xrm.SubGridControl<"defraimp_notificationpermanentaddress">;
      get(name: "Subgrid_4"): Xrm.SubGridControl<"defra_country">;
      get(name: "defraimp_arrivaldate"): Xrm.DateControl;
      get(name: "defraimp_commoditiesanimalscertifiedas"): Xrm.OptionSetControl<defraimp_animalcertifiedas>;
      get(name: "defraimp_commoditiesnumberofanimals"): Xrm.NumberControl;
      get(name: "defraimp_commoditiesregionoforigin"): Xrm.StringControl;
      get(name: "defraimp_commoditycomplementstext"): Xrm.StringControl;
      get(name: "defraimp_commodityid"): Xrm.StringControl;
      get(name: "defraimp_commodityidtypes"): Xrm.StringControl;
      get(name: "defraimp_commodityspeciesid"): Xrm.StringControl;
      get(name: "defraimp_commodityspeciesname"): Xrm.StringControl;
      get(name: "defraimp_consigneeaddressaddressline1"): Xrm.StringControl;
      get(name: "defraimp_consigneeaddressaddressline2"): Xrm.StringControl;
      get(name: "defraimp_consigneeaddressaddressline3"): Xrm.StringControl;
      get(name: "defraimp_consigneeaddresscity"): Xrm.StringControl;
      get(name: "defraimp_consigneeaddresscountryid"): Xrm.LookupControl<"defra_country">;
      get(name: "defraimp_consigneeaddressemail"): Xrm.StringControl;
      get(name: "defraimp_consigneeaddresspostalzipcode"): Xrm.StringControl;
      get(name: "defraimp_consigneeaddresstelephone"): Xrm.StringControl;
      get(name: "defraimp_consigneeaddressuktelephone"): Xrm.StringControl;
      get(name: "defraimp_consigneeapprovalnumber"): Xrm.StringControl;
      get(name: "defraimp_consigneecompanyname"): Xrm.StringControl;
      get(name: "defraimp_consigneeindividualname"): Xrm.StringControl;
      get(name: "defraimp_consigneeinternationalphonenumber"): Xrm.StringControl;
      get(name: "defraimp_consigneeotheridentifier"): Xrm.StringControl;
      get(name: "defraimp_consigneestatus"): Xrm.StringControl;
      get(name: "defraimp_consigneetype"): Xrm.StringControl;
      get(name: "defraimp_consignoraddressaddressline1"): Xrm.StringControl;
      get(name: "defraimp_consignoraddressaddressline11"): Xrm.StringControl;
      get(name: "defraimp_consignoraddressaddressline2"): Xrm.StringControl;
      get(name: "defraimp_consignoraddressaddressline21"): Xrm.StringControl;
      get(name: "defraimp_consignoraddressaddressline3"): Xrm.StringControl;
      get(name: "defraimp_consignoraddressaddressline31"): Xrm.StringControl;
      get(name: "defraimp_consignoraddresscity"): Xrm.StringControl;
      get(name: "defraimp_consignoraddresscity1"): Xrm.StringControl;
      get(name: "defraimp_consignoraddresscountryid"): Xrm.LookupControl<"defra_country">;
      get(name: "defraimp_consignoraddresscountryid1"): Xrm.LookupControl<"defra_country">;
      get(name: "defraimp_consignoraddressemail"): Xrm.StringControl;
      get(name: "defraimp_consignoraddressemail1"): Xrm.StringControl;
      get(name: "defraimp_consignoraddresspostalzipcode"): Xrm.StringControl;
      get(name: "defraimp_consignoraddresspostalzipcode1"): Xrm.StringControl;
      get(name: "defraimp_consignoraddresstelephone"): Xrm.StringControl;
      get(name: "defraimp_consignoraddresstelephone1"): Xrm.StringControl;
      get(name: "defraimp_consignoraddressuktelephone"): Xrm.StringControl;
      get(name: "defraimp_consignorapprovalnumber"): Xrm.StringControl;
      get(name: "defraimp_consignorapprovalnumber1"): Xrm.StringControl;
      get(name: "defraimp_consignorcompanyname"): Xrm.StringControl;
      get(name: "defraimp_consignorcompanyname1"): Xrm.StringControl;
      get(name: "defraimp_consignorindividualname"): Xrm.StringControl;
      get(name: "defraimp_consignorinternationalphonenumber"): Xrm.StringControl;
      get(name: "defraimp_consignorotheridentifier"): Xrm.StringControl;
      get(name: "defraimp_consignorstatus"): Xrm.StringControl;
      get(name: "defraimp_consignorstatus1"): Xrm.StringControl;
      get(name: "defraimp_consignortwoaddressaddressline1"): Xrm.StringControl;
      get(name: "defraimp_consignortwoaddressaddressline2"): Xrm.StringControl;
      get(name: "defraimp_consignortwoaddressaddressline3"): Xrm.StringControl;
      get(name: "defraimp_consignortwoaddresscity"): Xrm.StringControl;
      get(name: "defraimp_consignortwoaddresscountry"): Xrm.LookupControl<"defra_country">;
      get(name: "defraimp_consignortwoaddressemail"): Xrm.StringControl;
      get(name: "defraimp_consignortwoaddresspostalzipcode"): Xrm.StringControl;
      get(name: "defraimp_consignortwoaddresstelephone"): Xrm.StringControl;
      get(name: "defraimp_consignortwoaddressuktelephone"): Xrm.StringControl;
      get(name: "defraimp_consignortwoapprovalnumber"): Xrm.StringControl;
      get(name: "defraimp_consignortwocompanyname"): Xrm.StringControl;
      get(name: "defraimp_consignortwoindividualname"): Xrm.StringControl;
      get(name: "defraimp_consignortwointernationalphonenumber"): Xrm.StringControl;
      get(name: "defraimp_consignortwootheridentifier"): Xrm.StringControl;
      get(name: "defraimp_consignortwostatus"): Xrm.StringControl;
      get(name: "defraimp_consignortwotype"): Xrm.StringControl;
      get(name: "defraimp_consignortype"): Xrm.StringControl;
      get(name: "defraimp_consignortype1"): Xrm.StringControl;
      get(name: "defraimp_countryoforiginid"): Xrm.LookupControl<"defra_country">;
      get(name: "defraimp_cphnumber"): Xrm.StringControl;
      get(name: "defraimp_formattedcommoditycomplementstext"): Xrm.StringControl;
      get(name: "defraimp_formattedidentificationofanimalstext"): Xrm.StringControl;
      get(name: "defraimp_identificationofanimalstext"): Xrm.StringControl;
      get(name: "defraimp_importeraddressaddressline1"): Xrm.StringControl;
      get(name: "defraimp_importeraddressaddressline2"): Xrm.StringControl;
      get(name: "defraimp_importeraddressaddressline3"): Xrm.StringControl;
      get(name: "defraimp_importeraddresscity"): Xrm.StringControl;
      get(name: "defraimp_importeraddresscountryid"): Xrm.LookupControl<"defra_country">;
      get(name: "defraimp_importeraddressemail"): Xrm.StringControl;
      get(name: "defraimp_importeraddresspostalzipcode"): Xrm.StringControl;
      get(name: "defraimp_importeraddresstelephone"): Xrm.StringControl;
      get(name: "defraimp_importerapprovalnumber"): Xrm.StringControl;
      get(name: "defraimp_importercompanyname"): Xrm.StringControl;
      get(name: "defraimp_importerstatus"): Xrm.StringControl;
      get(name: "defraimp_importertype"): Xrm.StringControl;
      get(name: "defraimp_importingfromcharity"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "defraimp_isplaceofdestinationthepermanentaddress"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "defraimp_lastupdated"): Xrm.DateControl;
      get(name: "defraimp_lastupdatedbydisplayname"): Xrm.StringControl;
      get(name: "defraimp_meansoftransportfromentrypointdocument"): Xrm.StringControl;
      get(name: "defraimp_meansoftransportfromentrypointtype"): Xrm.StringControl;
      get(name: "defraimp_personresponsibleaddress"): Xrm.StringControl;
      get(name: "defraimp_personresponsiblecompanyname"): Xrm.StringControl;
      get(name: "defraimp_personresponsiblecountryid"): Xrm.LookupControl<"defra_country">;
      get(name: "defraimp_personresponsibleemail"): Xrm.StringControl;
      get(name: "defraimp_personresponsiblephone"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationaddressaddressline1"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationaddressaddressline2"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationaddressaddressline3"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationaddresscity"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationaddressemail"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationaddresspostalzipcode"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationaddresstelephone"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationapprovalnumber"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationcompanyname"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationcountryid"): Xrm.LookupControl<"defra_country">;
      get(name: "defraimp_placeofdestinationstatus"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationtype"): Xrm.StringControl;
      get(name: "defraimp_portofentry"): Xrm.StringControl;
      get(name: "defraimp_portofentry1"): Xrm.StringControl;
      get(name: "defraimp_responsiblefortransport"): Xrm.StringControl;
      get(name: "defraimp_routetransitingstates"): Xrm.StringControl;
      get(name: "defraimp_routetransitingstates1"): Xrm.StringControl;
      get(name: "defraimp_submissiondate"): Xrm.DateControl;
      get(name: "defraimp_submittedbydisplayname"): Xrm.StringControl;
      get(name: "defraimp_submittedbyiscontroluser"): Xrm.OptionSetControl<boolean>;
      get(name: "defraimp_transporteraddressaddressline1"): Xrm.StringControl;
      get(name: "defraimp_transporteraddressaddressline2"): Xrm.StringControl;
      get(name: "defraimp_transporteraddressaddressline3"): Xrm.StringControl;
      get(name: "defraimp_transporteraddresscity"): Xrm.StringControl;
      get(name: "defraimp_transporteraddresscountryid"): Xrm.LookupControl<"defra_country">;
      get(name: "defraimp_transporteraddressemail"): Xrm.StringControl;
      get(name: "defraimp_transporteraddresspostalzipcode"): Xrm.StringControl;
      get(name: "defraimp_transporteraddresstelephone"): Xrm.StringControl;
      get(name: "defraimp_transporterapprovalnumber"): Xrm.StringControl;
      get(name: "defraimp_transportercompanyname"): Xrm.StringControl;
      get(name: "defraimp_transporterstatus"): Xrm.StringControl;
      get(name: "defraimp_transportertype"): Xrm.StringControl;
      get(name: "defraimp_type"): Xrm.OptionSetControl<defraimp_importernotificationtype>;
      get(name: "defraimp_version"): Xrm.NumberControl;
      get(name: "defraimp_veterinaryinformationveterinarydocument"): Xrm.StringControl;
      get(name: "header_createdon"): Xrm.DateControl;
      get(name: "header_defraimp_name"): Xrm.StringControl;
      get(name: "header_defraimp_status"): Xrm.OptionSetControl<defraimp_importernotificationstatus>;
      get(name: "header_ownerid"): Xrm.LookupControl<"systemuser" | "team">;
      get(name: "subgrid_countries_of_transit"): Xrm.SubGridControl<"defra_country">;
      get(name: string): undefined;
      get(): Xrm.BaseControl[];
      get(index: number): Xrm.BaseControl;
      get(chooser: (item: Xrm.BaseControl, index: number) => boolean): Xrm.BaseControl[];
    }
    interface Tabs extends Xrm.TabCollectionBase {
      get(name: "commoditycomplements_tab"): Xrm.PageTab<Tabs.commoditycomplements_tab>;
      get(name: "consignee_tab"): Xrm.PageTab<Tabs.consignee_tab>;
      get(name: "consigners_tab"): Xrm.PageTab<Tabs.consigners_tab>;
      get(name: "details_tab"): Xrm.PageTab<Tabs.details_tab>;
      get(name: "importer_tab"): Xrm.PageTab<Tabs.importer_tab>;
      get(name: "meansoftransport_tab"): Xrm.PageTab<Tabs.meansoftransport_tab>;
      get(name: "permanentaddresses_tab"): Xrm.PageTab<Tabs.permanentaddresses_tab>;
      get(name: "personresponsible_tab"): Xrm.PageTab<Tabs.personresponsible_tab>;
      get(name: "placeofdestination_tab"): Xrm.PageTab<Tabs.placeofdestination_tab>;
      get(name: "placeoforigin_tab"): Xrm.PageTab<Tabs.placeoforigin_tab>;
      get(name: "tab_12"): Xrm.PageTab<Tabs.tab_12>;
      get(name: "transporter_tab"): Xrm.PageTab<Tabs.transporter_tab>;
      get(name: string): undefined;
      get(): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
      get(index: number): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>;
      get(chooser: (item: Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>, index: number) => boolean): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
    }
  }
  interface Information extends Xrm.PageBase<Information.Attributes,Information.Tabs,Information.Controls> {
    getAttribute(attributeName: "createdon"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_arrivaldate"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_commoditiesanimalscertifiedas"): Xrm.OptionSetAttribute<defraimp_animalcertifiedas>;
    getAttribute(attributeName: "defraimp_commoditiesnumberofanimals"): Xrm.NumberAttribute;
    getAttribute(attributeName: "defraimp_commoditiesregionoforigin"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_commoditycomplementstext"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_commodityid"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_commodityidtypes"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_commodityspeciesid"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_commodityspeciesname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consigneeaddressaddressline1"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consigneeaddressaddressline2"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consigneeaddressaddressline3"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consigneeaddresscity"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consigneeaddresscountryid"): Xrm.LookupAttribute<"defra_country">;
    getAttribute(attributeName: "defraimp_consigneeaddressemail"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consigneeaddresspostalzipcode"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consigneeaddresstelephone"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consigneeaddressuktelephone"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consigneeapprovalnumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consigneecompanyname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consigneeindividualname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consigneeinternationalphonenumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consigneeotheridentifier"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consigneestatus"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consigneetype"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignoraddressaddressline1"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignoraddressaddressline2"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignoraddressaddressline3"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignoraddresscity"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignoraddresscountryid"): Xrm.LookupAttribute<"defra_country">;
    getAttribute(attributeName: "defraimp_consignoraddressemail"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignoraddresspostalzipcode"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignoraddresstelephone"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignoraddressuktelephone"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignorapprovalnumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignorcompanyname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignorindividualname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignorinternationalphonenumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignorotheridentifier"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignorstatus"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignortwoaddressaddressline1"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignortwoaddressaddressline2"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignortwoaddressaddressline3"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignortwoaddresscity"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignortwoaddresscountry"): Xrm.LookupAttribute<"defra_country">;
    getAttribute(attributeName: "defraimp_consignortwoaddressemail"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignortwoaddresspostalzipcode"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignortwoaddresstelephone"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignortwoaddressuktelephone"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignortwoapprovalnumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignortwocompanyname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignortwoindividualname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignortwointernationalphonenumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignortwootheridentifier"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignortwostatus"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignortwotype"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignortype"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_countryoforiginid"): Xrm.LookupAttribute<"defra_country">;
    getAttribute(attributeName: "defraimp_cphnumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_formattedcommoditycomplementstext"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_formattedidentificationofanimalstext"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_identificationofanimalstext"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_importeraddressaddressline1"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_importeraddressaddressline2"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_importeraddressaddressline3"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_importeraddresscity"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_importeraddresscountryid"): Xrm.LookupAttribute<"defra_country">;
    getAttribute(attributeName: "defraimp_importeraddressemail"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_importeraddresspostalzipcode"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_importeraddresstelephone"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_importerapprovalnumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_importercompanyname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_importerstatus"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_importertype"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_importingfromcharity"): Xrm.Attribute<any>;
    getAttribute(attributeName: "defraimp_isplaceofdestinationthepermanentaddress"): Xrm.Attribute<any>;
    getAttribute(attributeName: "defraimp_lastupdated"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_lastupdatedbydisplayname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_meansoftransportfromentrypointdocument"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_meansoftransportfromentrypointtype"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_name"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_personresponsibleaddress"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_personresponsiblecompanyname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_personresponsiblecountryid"): Xrm.LookupAttribute<"defra_country">;
    getAttribute(attributeName: "defraimp_personresponsibleemail"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_personresponsiblephone"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationaddressaddressline1"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationaddressaddressline2"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationaddressaddressline3"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationaddresscity"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationaddressemail"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationaddresspostalzipcode"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationaddresstelephone"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationapprovalnumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationcompanyname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationcountryid"): Xrm.LookupAttribute<"defra_country">;
    getAttribute(attributeName: "defraimp_placeofdestinationstatus"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationtype"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_portofentry"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_responsiblefortransport"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_routetransitingstates"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_status"): Xrm.OptionSetAttribute<defraimp_importernotificationstatus>;
    getAttribute(attributeName: "defraimp_submissiondate"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_submittedbydisplayname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_submittedbyiscontroluser"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "defraimp_transporteraddressaddressline1"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_transporteraddressaddressline2"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_transporteraddressaddressline3"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_transporteraddresscity"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_transporteraddresscountryid"): Xrm.LookupAttribute<"defra_country">;
    getAttribute(attributeName: "defraimp_transporteraddressemail"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_transporteraddresspostalzipcode"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_transporteraddresstelephone"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_transporterapprovalnumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_transportercompanyname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_transporterstatus"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_transportertype"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_type"): Xrm.OptionSetAttribute<defraimp_importernotificationtype>;
    getAttribute(attributeName: "defraimp_version"): Xrm.NumberAttribute;
    getAttribute(attributeName: "defraimp_veterinaryinformationveterinarydocument"): Xrm.Attribute<string>;
    getAttribute(attributeName: "ownerid"): Xrm.LookupAttribute<"systemuser" | "team">;
    getAttribute(attributeName: string): undefined;
    getControl(controlName: "Subgrid_2"): Xrm.SubGridControl<"defraimp_commoditycomplementparameterset">;
    getControl(controlName: "Subgrid_3"): Xrm.SubGridControl<"defraimp_notificationpermanentaddress">;
    getControl(controlName: "Subgrid_4"): Xrm.SubGridControl<"defra_country">;
    getControl(controlName: "defraimp_arrivaldate"): Xrm.DateControl;
    getControl(controlName: "defraimp_commoditiesanimalscertifiedas"): Xrm.OptionSetControl<defraimp_animalcertifiedas>;
    getControl(controlName: "defraimp_commoditiesnumberofanimals"): Xrm.NumberControl;
    getControl(controlName: "defraimp_commoditiesregionoforigin"): Xrm.StringControl;
    getControl(controlName: "defraimp_commoditycomplementstext"): Xrm.StringControl;
    getControl(controlName: "defraimp_commodityid"): Xrm.StringControl;
    getControl(controlName: "defraimp_commodityidtypes"): Xrm.StringControl;
    getControl(controlName: "defraimp_commodityspeciesid"): Xrm.StringControl;
    getControl(controlName: "defraimp_commodityspeciesname"): Xrm.StringControl;
    getControl(controlName: "defraimp_consigneeaddressaddressline1"): Xrm.StringControl;
    getControl(controlName: "defraimp_consigneeaddressaddressline2"): Xrm.StringControl;
    getControl(controlName: "defraimp_consigneeaddressaddressline3"): Xrm.StringControl;
    getControl(controlName: "defraimp_consigneeaddresscity"): Xrm.StringControl;
    getControl(controlName: "defraimp_consigneeaddresscountryid"): Xrm.LookupControl<"defra_country">;
    getControl(controlName: "defraimp_consigneeaddressemail"): Xrm.StringControl;
    getControl(controlName: "defraimp_consigneeaddresspostalzipcode"): Xrm.StringControl;
    getControl(controlName: "defraimp_consigneeaddresstelephone"): Xrm.StringControl;
    getControl(controlName: "defraimp_consigneeaddressuktelephone"): Xrm.StringControl;
    getControl(controlName: "defraimp_consigneeapprovalnumber"): Xrm.StringControl;
    getControl(controlName: "defraimp_consigneecompanyname"): Xrm.StringControl;
    getControl(controlName: "defraimp_consigneeindividualname"): Xrm.StringControl;
    getControl(controlName: "defraimp_consigneeinternationalphonenumber"): Xrm.StringControl;
    getControl(controlName: "defraimp_consigneeotheridentifier"): Xrm.StringControl;
    getControl(controlName: "defraimp_consigneestatus"): Xrm.StringControl;
    getControl(controlName: "defraimp_consigneetype"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignoraddressaddressline1"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignoraddressaddressline11"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignoraddressaddressline2"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignoraddressaddressline21"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignoraddressaddressline3"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignoraddressaddressline31"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignoraddresscity"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignoraddresscity1"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignoraddresscountryid"): Xrm.LookupControl<"defra_country">;
    getControl(controlName: "defraimp_consignoraddresscountryid1"): Xrm.LookupControl<"defra_country">;
    getControl(controlName: "defraimp_consignoraddressemail"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignoraddressemail1"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignoraddresspostalzipcode"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignoraddresspostalzipcode1"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignoraddresstelephone"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignoraddresstelephone1"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignoraddressuktelephone"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignorapprovalnumber"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignorapprovalnumber1"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignorcompanyname"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignorcompanyname1"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignorindividualname"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignorinternationalphonenumber"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignorotheridentifier"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignorstatus"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignorstatus1"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignortwoaddressaddressline1"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignortwoaddressaddressline2"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignortwoaddressaddressline3"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignortwoaddresscity"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignortwoaddresscountry"): Xrm.LookupControl<"defra_country">;
    getControl(controlName: "defraimp_consignortwoaddressemail"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignortwoaddresspostalzipcode"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignortwoaddresstelephone"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignortwoaddressuktelephone"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignortwoapprovalnumber"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignortwocompanyname"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignortwoindividualname"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignortwointernationalphonenumber"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignortwootheridentifier"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignortwostatus"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignortwotype"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignortype"): Xrm.StringControl;
    getControl(controlName: "defraimp_consignortype1"): Xrm.StringControl;
    getControl(controlName: "defraimp_countryoforiginid"): Xrm.LookupControl<"defra_country">;
    getControl(controlName: "defraimp_cphnumber"): Xrm.StringControl;
    getControl(controlName: "defraimp_formattedcommoditycomplementstext"): Xrm.StringControl;
    getControl(controlName: "defraimp_formattedidentificationofanimalstext"): Xrm.StringControl;
    getControl(controlName: "defraimp_identificationofanimalstext"): Xrm.StringControl;
    getControl(controlName: "defraimp_importeraddressaddressline1"): Xrm.StringControl;
    getControl(controlName: "defraimp_importeraddressaddressline2"): Xrm.StringControl;
    getControl(controlName: "defraimp_importeraddressaddressline3"): Xrm.StringControl;
    getControl(controlName: "defraimp_importeraddresscity"): Xrm.StringControl;
    getControl(controlName: "defraimp_importeraddresscountryid"): Xrm.LookupControl<"defra_country">;
    getControl(controlName: "defraimp_importeraddressemail"): Xrm.StringControl;
    getControl(controlName: "defraimp_importeraddresspostalzipcode"): Xrm.StringControl;
    getControl(controlName: "defraimp_importeraddresstelephone"): Xrm.StringControl;
    getControl(controlName: "defraimp_importerapprovalnumber"): Xrm.StringControl;
    getControl(controlName: "defraimp_importercompanyname"): Xrm.StringControl;
    getControl(controlName: "defraimp_importerstatus"): Xrm.StringControl;
    getControl(controlName: "defraimp_importertype"): Xrm.StringControl;
    getControl(controlName: "defraimp_importingfromcharity"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "defraimp_isplaceofdestinationthepermanentaddress"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "defraimp_lastupdated"): Xrm.DateControl;
    getControl(controlName: "defraimp_lastupdatedbydisplayname"): Xrm.StringControl;
    getControl(controlName: "defraimp_meansoftransportfromentrypointdocument"): Xrm.StringControl;
    getControl(controlName: "defraimp_meansoftransportfromentrypointtype"): Xrm.StringControl;
    getControl(controlName: "defraimp_personresponsibleaddress"): Xrm.StringControl;
    getControl(controlName: "defraimp_personresponsiblecompanyname"): Xrm.StringControl;
    getControl(controlName: "defraimp_personresponsiblecountryid"): Xrm.LookupControl<"defra_country">;
    getControl(controlName: "defraimp_personresponsibleemail"): Xrm.StringControl;
    getControl(controlName: "defraimp_personresponsiblephone"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationaddressaddressline1"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationaddressaddressline2"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationaddressaddressline3"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationaddresscity"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationaddressemail"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationaddresspostalzipcode"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationaddresstelephone"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationapprovalnumber"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationcompanyname"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationcountryid"): Xrm.LookupControl<"defra_country">;
    getControl(controlName: "defraimp_placeofdestinationstatus"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationtype"): Xrm.StringControl;
    getControl(controlName: "defraimp_portofentry"): Xrm.StringControl;
    getControl(controlName: "defraimp_portofentry1"): Xrm.StringControl;
    getControl(controlName: "defraimp_responsiblefortransport"): Xrm.StringControl;
    getControl(controlName: "defraimp_routetransitingstates"): Xrm.StringControl;
    getControl(controlName: "defraimp_routetransitingstates1"): Xrm.StringControl;
    getControl(controlName: "defraimp_submissiondate"): Xrm.DateControl;
    getControl(controlName: "defraimp_submittedbydisplayname"): Xrm.StringControl;
    getControl(controlName: "defraimp_submittedbyiscontroluser"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "defraimp_transporteraddressaddressline1"): Xrm.StringControl;
    getControl(controlName: "defraimp_transporteraddressaddressline2"): Xrm.StringControl;
    getControl(controlName: "defraimp_transporteraddressaddressline3"): Xrm.StringControl;
    getControl(controlName: "defraimp_transporteraddresscity"): Xrm.StringControl;
    getControl(controlName: "defraimp_transporteraddresscountryid"): Xrm.LookupControl<"defra_country">;
    getControl(controlName: "defraimp_transporteraddressemail"): Xrm.StringControl;
    getControl(controlName: "defraimp_transporteraddresspostalzipcode"): Xrm.StringControl;
    getControl(controlName: "defraimp_transporteraddresstelephone"): Xrm.StringControl;
    getControl(controlName: "defraimp_transporterapprovalnumber"): Xrm.StringControl;
    getControl(controlName: "defraimp_transportercompanyname"): Xrm.StringControl;
    getControl(controlName: "defraimp_transporterstatus"): Xrm.StringControl;
    getControl(controlName: "defraimp_transportertype"): Xrm.StringControl;
    getControl(controlName: "defraimp_type"): Xrm.OptionSetControl<defraimp_importernotificationtype>;
    getControl(controlName: "defraimp_version"): Xrm.NumberControl;
    getControl(controlName: "defraimp_veterinaryinformationveterinarydocument"): Xrm.StringControl;
    getControl(controlName: "header_createdon"): Xrm.DateControl;
    getControl(controlName: "header_defraimp_name"): Xrm.StringControl;
    getControl(controlName: "header_defraimp_status"): Xrm.OptionSetControl<defraimp_importernotificationstatus>;
    getControl(controlName: "header_ownerid"): Xrm.LookupControl<"systemuser" | "team">;
    getControl(controlName: "subgrid_countries_of_transit"): Xrm.SubGridControl<"defra_country">;
    getControl(controlName: string): undefined;
  }
}
