declare namespace Form.defraimp_importapplication.Main {
  namespace Information {
    namespace Tabs {
      interface AdditionalITAHC_Tab extends Xrm.SectionCollectionBase {
        get(name: "AdditionalITAHCIV66_Tab_section_2"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface Charity_Tab extends Xrm.SectionCollectionBase {
        get(name: "tab_11_section_1"): Xrm.PageSection;
        get(name: "tab_11_section_2"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface Destinations_Tab extends Xrm.SectionCollectionBase {
        get(name: "ConsignmentFinal_Section"): Xrm.PageSection;
        get(name: "PlaceofDestination_Section"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface Importer_Tab extends Xrm.SectionCollectionBase {
        get(name: "Importer_Section"): Xrm.PageSection;
        get(name: "Importer_Tab_column_4_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface PlaceofOrigin_Tab extends Xrm.SectionCollectionBase {
        get(name: "PlaceofOrigin_Tab"): Xrm.PageSection;
        get(name: "tab_9_section_2"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface Queries_Tab extends Xrm.SectionCollectionBase {
        get(name: "Summary_section_7"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface Summary extends Xrm.SectionCollectionBase {
        get(name: "CommodityIdentifiers_Section"): Xrm.PageSection;
        get(name: "Commodity_Section"): Xrm.PageSection;
        get(name: "GeneralComments_Sectiom"): Xrm.PageSection;
        get(name: "Hidden_Section"): Xrm.PageSection;
        get(name: "IV65_Section"): Xrm.PageSection;
        get(name: "Summary_section_15"): Xrm.PageSection;
        get(name: "Summary_section_5"): Xrm.PageSection;
        get(name: "Timeline_Section"): Xrm.PageSection;
        get(name: "Warble Fly Treatment"): Xrm.PageSection;
        get(name: "cheda_section"): Xrm.PageSection;
        get(name: "chedp_controls_section"): Xrm.PageSection;
        get(name: "chedp_section"): Xrm.PageSection;
        get(name: "countriesoftransit"): Xrm.PageSection;
        get(name: "iv66_section"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface Transporter_Tab extends Xrm.SectionCollectionBase {
        get(name: "tab_4_section_1"): Xrm.PageSection;
        get(name: "tab_4_section_2"): Xrm.PageSection;
        get(name: "transport_information_section"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_7 extends Xrm.SectionCollectionBase {
        get(name: "tab_7_section_1"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
      interface tab_8 extends Xrm.SectionCollectionBase {
        get(name: "tab_8_section_2"): Xrm.PageSection;
        get(name: string): undefined;
        get(): Xrm.PageSection[];
        get(index: number): Xrm.PageSection;
        get(chooser: (item: Xrm.PageSection, index: number) => boolean): Xrm.PageSection[];
      }
    }
    interface Attributes extends Xrm.AttributeCollectionBase {
      get(name: "createdon"): Xrm.DateAttribute;
      get(name: "defraimp_article15reimport"): Xrm.OptionSetAttribute<boolean>;
      get(name: "defraimp_article8monitored"): Xrm.OptionSetAttribute<boolean>;
      get(name: "defraimp_certificatecompliantfirsttime"): Xrm.OptionSetAttribute<boolean>;
      get(name: "defraimp_certificatenoncompliancereason"): Xrm.OptionSetAttribute<defraimp_importapplication_defraimp_certificatenoncompliancereason>;
      get(name: "defraimp_certificatenoncompliancereasonother"): Xrm.Attribute<string>;
      get(name: "defraimp_certificateverified"): Xrm.OptionSetAttribute<boolean>;
      get(name: "defraimp_charityaddresscity"): Xrm.Attribute<string>;
      get(name: "defraimp_charityaddresscountry"): Xrm.LookupAttribute<"defra_country">;
      get(name: "defraimp_charityaddressline1"): Xrm.Attribute<string>;
      get(name: "defraimp_charityaddressline2"): Xrm.Attribute<string>;
      get(name: "defraimp_charityaddressline3"): Xrm.Attribute<string>;
      get(name: "defraimp_charityaddresspostcode"): Xrm.Attribute<string>;
      get(name: "defraimp_charityname"): Xrm.Attribute<string>;
      get(name: "defraimp_commoditynotes"): Xrm.Attribute<string>;
      get(name: "defraimp_commoditytypeid"): Xrm.LookupAttribute<"defraexp_commoditytype">;
      get(name: "defraimp_completionsummary"): Xrm.Attribute<string>;
      get(name: "defraimp_consignmentconforming"): Xrm.OptionSetAttribute<boolean>;
      get(name: "defraimp_containernumber"): Xrm.Attribute<string>;
      get(name: "defraimp_countryoforiginid"): Xrm.LookupAttribute<"defra_country">;
      get(name: "defraimp_dateiv66received"): Xrm.DateAttribute;
      get(name: "defraimp_dateofconfirmationfromimporter"): Xrm.DateAttribute;
      get(name: "defraimp_dateofconfirmationtobip"): Xrm.DateAttribute;
      get(name: "defraimp_dateofemailtoimporter"): Xrm.DateAttribute;
      get(name: "defraimp_dateofimport"): Xrm.DateAttribute;
      get(name: "defraimp_destinationaddresscountryid"): Xrm.LookupAttribute<"defra_country">;
      get(name: "defraimp_devolvedofficeid"): Xrm.LookupAttribute<"team">;
      get(name: "defraimp_documentationnumber"): Xrm.Attribute<string>;
      get(name: "defraimp_documentnumber"): Xrm.Attribute<string>;
      get(name: "defraimp_generalcomments"): Xrm.Attribute<string>;
      get(name: "defraimp_healthcertificatenumber"): Xrm.Attribute<string>;
      get(name: "defraimp_importapplicationtype"): Xrm.OptionSetAttribute<defraimp_importapplication_defraimp_importapplicationtype>;
      get(name: "defraimp_importeraddress1"): Xrm.Attribute<string>;
      get(name: "defraimp_importeraddress2"): Xrm.Attribute<string>;
      get(name: "defraimp_importeraddress3"): Xrm.Attribute<string>;
      get(name: "defraimp_importeraddresscity"): Xrm.Attribute<string>;
      get(name: "defraimp_importeraddresscountryid"): Xrm.LookupAttribute<"defra_country">;
      get(name: "defraimp_importeraddresspostcode"): Xrm.Attribute<string>;
      get(name: "defraimp_importercontactname"): Xrm.Attribute<string>;
      get(name: "defraimp_importeremail"): Xrm.Attribute<string>;
      get(name: "defraimp_importerorganisation"): Xrm.Attribute<string>;
      get(name: "defraimp_importertelephone"): Xrm.Attribute<string>;
      get(name: "defraimp_importingfromcharity"): Xrm.OptionSetAttribute<boolean>;
      get(name: "defraimp_importrisklevelid"): Xrm.LookupAttribute<"defraimp_importrisklevel">;
      get(name: "defraimp_importrisklevelstatus"): Xrm.OptionSetAttribute<defraimp_importapplication_defraimp_importrisklevelstatus>;
      get(name: "defraimp_inspectiondeclinedreason"): Xrm.Attribute<string>;
      get(name: "defraimp_inspectionoutcome"): Xrm.OptionSetAttribute<defraimp_importapplication_defraimp_inspectionoutcome>;
      get(name: "defraimp_inspectionrequested"): Xrm.OptionSetAttribute<boolean>;
      get(name: "defraimp_inspectionrequired"): Xrm.OptionSetAttribute<defraimp_importapplication_defraimp_inspectionrequired>;
      get(name: "defraimp_inspectionrequiredreason"): Xrm.OptionSetAttribute<defraimp_importapplication_defraimp_inspectionrequiredreason>;
      get(name: "defraimp_iv65responseduedate"): Xrm.DateAttribute;
      get(name: "defraimp_iv65responsereceiveddate"): Xrm.DateAttribute;
      get(name: "defraimp_iv65sent"): Xrm.Attribute<any>;
      get(name: "defraimp_iv65sentdate"): Xrm.DateAttribute;
      get(name: "defraimp_iv66receivedinrequiredtimescale"): Xrm.Attribute<any>;
      get(name: "defraimp_localreferencenumber"): Xrm.Attribute<string>;
      get(name: "defraimp_manualpostimportcheckdecision"): Xrm.OptionSetAttribute<defraimp_importapplication_defraimp_manualpostimportcheckdecision>;
      get(name: "defraimp_meansoftransport"): Xrm.OptionSetAttribute<defraimp_meansoftransport>;
      get(name: "defraimp_movedtocompletiondate"): Xrm.DateAttribute;
      get(name: "defraimp_movetocompletion"): Xrm.OptionSetAttribute<boolean>;
      get(name: "defraimp_name"): Xrm.Attribute<string>;
      get(name: "defraimp_notifiedtobipwithin15days"): Xrm.OptionSetAttribute<boolean>;
      get(name: "defraimp_permanentdestinationaddresscity"): Xrm.Attribute<string>;
      get(name: "defraimp_permanentdestinationaddresscounid"): Xrm.LookupAttribute<"defra_country">;
      get(name: "defraimp_permanentdestinationaddressline1"): Xrm.Attribute<string>;
      get(name: "defraimp_permanentdestinationaddressline2"): Xrm.Attribute<string>;
      get(name: "defraimp_permanentdestinationaddressline3"): Xrm.Attribute<string>;
      get(name: "defraimp_permanentdestinationaddresspostcode"): Xrm.Attribute<string>;
      get(name: "defraimp_permanentdestinationcontactname"): Xrm.Attribute<string>;
      get(name: "defraimp_permanentdestinationemail"): Xrm.Attribute<string>;
      get(name: "defraimp_permanentdestinationorganisation"): Xrm.Attribute<string>;
      get(name: "defraimp_permanentdestinationtelephone"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationaddresscity"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationaddressline1"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationaddressline2"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationaddressline3"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationaddresspostcode"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationcontactname"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationemail"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationorganisation"): Xrm.Attribute<string>;
      get(name: "defraimp_placeofdestinationtelephone"): Xrm.Attribute<string>;
      get(name: "defraimp_placeoforiginaddresscity"): Xrm.Attribute<string>;
      get(name: "defraimp_placeoforiginaddressline1"): Xrm.Attribute<string>;
      get(name: "defraimp_placeoforiginaddressline2"): Xrm.Attribute<string>;
      get(name: "defraimp_placeoforiginaddressline3"): Xrm.Attribute<string>;
      get(name: "defraimp_placeoforiginaddresspostcode"): Xrm.Attribute<string>;
      get(name: "defraimp_placeoforigincontactname"): Xrm.Attribute<string>;
      get(name: "defraimp_placeoforigincountryid"): Xrm.LookupAttribute<"defra_country">;
      get(name: "defraimp_placeoforiginid"): Xrm.LookupAttribute<"defraimp_placeoforigin">;
      get(name: "defraimp_placeoforiginorganisation"): Xrm.Attribute<string>;
      get(name: "defraimp_pointofentry"): Xrm.Attribute<string>;
      get(name: "defraimp_primaryimporternotificationid"): Xrm.LookupAttribute<"defraimp_importernotification">;
      get(name: "defraimp_primaryitahcid"): Xrm.LookupAttribute<"defraimp_itahc">;
      get(name: "defraimp_purpose"): Xrm.OptionSetAttribute<defraimp_importapplication_defraimp_purpose>;
      get(name: "defraimp_quantity"): Xrm.NumberAttribute;
      get(name: "defraimp_regionareaallocatedtoid"): Xrm.LookupAttribute<"defraimp_apharegion">;
      get(name: "defraimp_resettrustleveltobronze"): Xrm.OptionSetAttribute<boolean>;
      get(name: "defraimp_risklevelverified"): Xrm.OptionSetAttribute<boolean>;
      get(name: "defraimp_sealnumber"): Xrm.Attribute<string>;
      get(name: "defraimp_transporteraddresscity"): Xrm.Attribute<string>;
      get(name: "defraimp_transporteraddresscountryid"): Xrm.LookupAttribute<"defra_country">;
      get(name: "defraimp_transporteraddressline1"): Xrm.Attribute<string>;
      get(name: "defraimp_transporteraddressline2"): Xrm.Attribute<string>;
      get(name: "defraimp_transporteraddressline3"): Xrm.Attribute<string>;
      get(name: "defraimp_transporteraddresspostcode"): Xrm.Attribute<string>;
      get(name: "defraimp_transporteremail"): Xrm.Attribute<string>;
      get(name: "defraimp_transportername"): Xrm.Attribute<string>;
      get(name: "defraimp_transportertelephone"): Xrm.Attribute<string>;
      get(name: "defraimp_unit"): Xrm.Attribute<string>;
      get(name: "defraimp_warbleflytreatmentdeclarationreceiveddate"): Xrm.DateAttribute;
      get(name: "defraimp_warbleflytreatmentdeclarationrequired"): Xrm.Attribute<any>;
      get(name: "ownerid"): Xrm.LookupAttribute<"systemuser" | "team">;
      get(name: "statuscode"): Xrm.OptionSetAttribute<defraimp_importapplication_statuscode>;
      get(name: string): undefined;
      get(): Xrm.Attribute<any>[];
      get(index: number): Xrm.Attribute<any>;
      get(chooser: (item: Xrm.Attribute<any>, index: number) => boolean): Xrm.Attribute<any>[];
    }
    interface Controls extends Xrm.ControlCollectionBase {
      get(name: "AdditionalITAHC_SubGrid"): Xrm.SubGridControl<"defraimp_itahc">;
      get(name: "CountriesofTransit"): Xrm.SubGridControl<"defra_country">;
      get(name: "RelatedInspections"): Xrm.SubGridControl<"defraimp_importinspection">;
      get(name: "RelatedQueries"): Xrm.BaseControl;
      get(name: "Subgrid_WatchFlags"): Xrm.SubGridControl<"defraimp_watchflag">;
      get(name: "WebResource_FilesAndAttachments"): Xrm.WebResourceControl;
      get(name: "WebResource_UploadFiles"): Xrm.WebResourceControl;
      get(name: "defraimp_article15reimport"): Xrm.OptionSetControl<boolean>;
      get(name: "defraimp_article8monitored"): Xrm.OptionSetControl<boolean>;
      get(name: "defraimp_charityaddresscity"): Xrm.StringControl;
      get(name: "defraimp_charityaddresscountry"): Xrm.LookupControl<"defra_country">;
      get(name: "defraimp_charityaddressline1"): Xrm.StringControl;
      get(name: "defraimp_charityaddressline2"): Xrm.StringControl;
      get(name: "defraimp_charityaddressline3"): Xrm.StringControl;
      get(name: "defraimp_charityaddresspostcode"): Xrm.StringControl;
      get(name: "defraimp_charityname"): Xrm.StringControl;
      get(name: "defraimp_commoditynotes"): Xrm.StringControl;
      get(name: "defraimp_commoditytypeid"): Xrm.LookupControl<"defraexp_commoditytype">;
      get(name: "defraimp_consignmentconforming"): Xrm.OptionSetControl<boolean>;
      get(name: "defraimp_containernumber"): Xrm.StringControl;
      get(name: "defraimp_countryoforiginid"): Xrm.LookupControl<"defra_country">;
      get(name: "defraimp_dateiv66received"): Xrm.DateControl;
      get(name: "defraimp_dateofconfirmationfromimporter"): Xrm.DateControl;
      get(name: "defraimp_dateofconfirmationtobip"): Xrm.DateControl;
      get(name: "defraimp_dateofemailtoimporter"): Xrm.DateControl;
      get(name: "defraimp_dateofimport"): Xrm.DateControl;
      get(name: "defraimp_destinationaddresscountryid"): Xrm.LookupControl<"defra_country">;
      get(name: "defraimp_devolvedofficeid"): Xrm.LookupControl<"team">;
      get(name: "defraimp_documentationnumber"): Xrm.StringControl;
      get(name: "defraimp_documentnumber"): Xrm.StringControl;
      get(name: "defraimp_generalcomments"): Xrm.StringControl;
      get(name: "defraimp_importapplicationtype"): Xrm.OptionSetControl<defraimp_importapplication_defraimp_importapplicationtype>;
      get(name: "defraimp_importeraddress1"): Xrm.StringControl;
      get(name: "defraimp_importeraddress2"): Xrm.StringControl;
      get(name: "defraimp_importeraddress3"): Xrm.StringControl;
      get(name: "defraimp_importeraddresscity"): Xrm.StringControl;
      get(name: "defraimp_importeraddresscountryid"): Xrm.LookupControl<"defra_country">;
      get(name: "defraimp_importeraddresspostcode"): Xrm.StringControl;
      get(name: "defraimp_importercontactname"): Xrm.StringControl;
      get(name: "defraimp_importeremail"): Xrm.StringControl;
      get(name: "defraimp_importerorganisation"): Xrm.StringControl;
      get(name: "defraimp_importertelephone"): Xrm.StringControl;
      get(name: "defraimp_importingfromcharity"): Xrm.OptionSetControl<boolean>;
      get(name: "defraimp_importrisklevelid"): Xrm.LookupControl<"defraimp_importrisklevel">;
      get(name: "defraimp_importrisklevelstatus"): Xrm.OptionSetControl<defraimp_importapplication_defraimp_importrisklevelstatus>;
      get(name: "defraimp_inspectiondeclinedreason"): Xrm.StringControl;
      get(name: "defraimp_inspectionoutcome"): Xrm.OptionSetControl<defraimp_importapplication_defraimp_inspectionoutcome>;
      get(name: "defraimp_inspectionrequired"): Xrm.OptionSetControl<defraimp_importapplication_defraimp_inspectionrequired>;
      get(name: "defraimp_inspectionrequiredreason"): Xrm.OptionSetControl<defraimp_importapplication_defraimp_inspectionrequiredreason>;
      get(name: "defraimp_iv65responseduedate"): Xrm.DateControl;
      get(name: "defraimp_iv65responsereceiveddate"): Xrm.DateControl;
      get(name: "defraimp_iv65sent"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "defraimp_iv65sentdate"): Xrm.DateControl;
      get(name: "defraimp_iv66receivedinrequiredtimescale"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "defraimp_localreferencenumber"): Xrm.StringControl;
      get(name: "defraimp_localreferencenumber1"): Xrm.StringControl;
      get(name: "defraimp_manualpostimportcheckdecision"): Xrm.OptionSetControl<defraimp_importapplication_defraimp_manualpostimportcheckdecision>;
      get(name: "defraimp_meansoftransport"): Xrm.OptionSetControl<defraimp_meansoftransport>;
      get(name: "defraimp_movedtocompletiondate"): Xrm.DateControl;
      get(name: "defraimp_movetocompletion"): Xrm.OptionSetControl<boolean>;
      get(name: "defraimp_name"): Xrm.StringControl;
      get(name: "defraimp_notifiedtobipwithin15days"): Xrm.OptionSetControl<boolean>;
      get(name: "defraimp_permanentdestinationaddresscity"): Xrm.StringControl;
      get(name: "defraimp_permanentdestinationaddresscounid"): Xrm.LookupControl<"defra_country">;
      get(name: "defraimp_permanentdestinationaddressline1"): Xrm.StringControl;
      get(name: "defraimp_permanentdestinationaddressline2"): Xrm.StringControl;
      get(name: "defraimp_permanentdestinationaddressline3"): Xrm.StringControl;
      get(name: "defraimp_permanentdestinationaddresspostcode"): Xrm.StringControl;
      get(name: "defraimp_permanentdestinationcontactname"): Xrm.StringControl;
      get(name: "defraimp_permanentdestinationemail"): Xrm.StringControl;
      get(name: "defraimp_permanentdestinationorganisation"): Xrm.StringControl;
      get(name: "defraimp_permanentdestinationtelephone"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationaddresscity"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationaddressline1"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationaddressline2"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationaddressline3"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationaddresspostcode"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationcontactname"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationemail"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationorganisation"): Xrm.StringControl;
      get(name: "defraimp_placeofdestinationtelephone"): Xrm.StringControl;
      get(name: "defraimp_placeoforiginaddresscity"): Xrm.StringControl;
      get(name: "defraimp_placeoforiginaddressline1"): Xrm.StringControl;
      get(name: "defraimp_placeoforiginaddressline2"): Xrm.StringControl;
      get(name: "defraimp_placeoforiginaddressline3"): Xrm.StringControl;
      get(name: "defraimp_placeoforiginaddresspostcode"): Xrm.StringControl;
      get(name: "defraimp_placeoforigincontactname"): Xrm.StringControl;
      get(name: "defraimp_placeoforigincountryid"): Xrm.LookupControl<"defra_country">;
      get(name: "defraimp_placeoforiginid"): Xrm.LookupControl<"defraimp_placeoforigin">;
      get(name: "defraimp_placeoforiginorganisation"): Xrm.StringControl;
      get(name: "defraimp_pointofentry"): Xrm.StringControl;
      get(name: "defraimp_primaryimporternotificationid"): Xrm.LookupControl<"defraimp_importernotification">;
      get(name: "defraimp_primaryitahcid"): Xrm.LookupControl<"defraimp_itahc">;
      get(name: "defraimp_purpose"): Xrm.OptionSetControl<defraimp_importapplication_defraimp_purpose>;
      get(name: "defraimp_quantity"): Xrm.NumberControl;
      get(name: "defraimp_regionareaallocatedtoid"): Xrm.LookupControl<"defraimp_apharegion">;
      get(name: "defraimp_sealnumber"): Xrm.StringControl;
      get(name: "defraimp_transporteraddresscity"): Xrm.StringControl;
      get(name: "defraimp_transporteraddresscountryid"): Xrm.LookupControl<"defra_country">;
      get(name: "defraimp_transporteraddressline1"): Xrm.StringControl;
      get(name: "defraimp_transporteraddressline2"): Xrm.StringControl;
      get(name: "defraimp_transporteraddressline3"): Xrm.StringControl;
      get(name: "defraimp_transporteraddresspostcode"): Xrm.StringControl;
      get(name: "defraimp_transporteremail"): Xrm.StringControl;
      get(name: "defraimp_transportername"): Xrm.StringControl;
      get(name: "defraimp_transportertelephone"): Xrm.StringControl;
      get(name: "defraimp_unit"): Xrm.StringControl;
      get(name: "defraimp_warbleflytreatmentdeclarationreceiveddate"): Xrm.DateControl;
      get(name: "defraimp_warbleflytreatmentdeclarationrequired"): Xrm.Control<Xrm.Attribute<any>>;
      get(name: "footer_createdon"): Xrm.DateControl;
      get(name: "footer_defraimp_healthcertificatenumber"): Xrm.StringControl;
      get(name: "footer_ownerid"): Xrm.LookupControl<"systemuser" | "team">;
      get(name: "header_ownerid"): Xrm.LookupControl<"systemuser" | "team">;
      get(name: "header_process_defraimp_certificatecompliantfirsttime"): Xrm.OptionSetControl<boolean> | null;
      get(name: "header_process_defraimp_certificatenoncompliancereason"): Xrm.OptionSetControl<defraimp_importapplication_defraimp_certificatenoncompliancereason> | null;
      get(name: "header_process_defraimp_certificatenoncompliancereasonother"): Xrm.StringControl | null;
      get(name: "header_process_defraimp_certificateverified"): Xrm.OptionSetControl<boolean> | null;
      get(name: "header_process_defraimp_commoditytypeid"): Xrm.LookupControl<"defraexp_commoditytype"> | null;
      get(name: "header_process_defraimp_completionsummary"): Xrm.StringControl | null;
      get(name: "header_process_defraimp_completionsummary1"): Xrm.StringControl | null;
      get(name: "header_process_defraimp_countryoforiginid"): Xrm.LookupControl<"defra_country"> | null;
      get(name: "header_process_defraimp_importrisklevelid"): Xrm.LookupControl<"defraimp_importrisklevel"> | null;
      get(name: "header_process_defraimp_inspectiondeclinedreason"): Xrm.StringControl | null;
      get(name: "header_process_defraimp_inspectionrequested"): Xrm.OptionSetControl<boolean> | null;
      get(name: "header_process_defraimp_inspectionrequired"): Xrm.OptionSetControl<defraimp_importapplication_defraimp_inspectionrequired> | null;
      get(name: "header_process_defraimp_manualpostimportcheckdecision"): Xrm.OptionSetControl<defraimp_importapplication_defraimp_manualpostimportcheckdecision> | null;
      get(name: "header_process_defraimp_movedtocompletiondate"): Xrm.DateControl | null;
      get(name: "header_process_defraimp_movedtocompletiondate1"): Xrm.DateControl | null;
      get(name: "header_process_defraimp_movetocompletion"): Xrm.OptionSetControl<boolean> | null;
      get(name: "header_process_defraimp_movetocompletion1"): Xrm.OptionSetControl<boolean> | null;
      get(name: "header_process_defraimp_placeoforiginid"): Xrm.LookupControl<"defraimp_placeoforigin"> | null;
      get(name: "header_process_defraimp_primaryitahcid"): Xrm.LookupControl<"defraimp_itahc"> | null;
      get(name: "header_process_defraimp_regionareaallocatedtoid"): Xrm.LookupControl<"defraimp_apharegion"> | null;
      get(name: "header_process_defraimp_resettrustleveltobronze"): Xrm.OptionSetControl<boolean> | null;
      get(name: "header_process_defraimp_risklevelverified"): Xrm.OptionSetControl<boolean> | null;
      get(name: "header_process_ownerid"): Xrm.LookupControl<"systemuser" | "team"> | null;
      get(name: "header_statuscode"): Xrm.OptionSetControl<defraimp_importapplication_statuscode>;
      get(name: "notescontrol"): Xrm.BaseControl;
      get(name: "ownerid"): Xrm.LookupControl<"systemuser" | "team">;
      get(name: string): undefined;
      get(): Xrm.BaseControl[];
      get(index: number): Xrm.BaseControl;
      get(chooser: (item: Xrm.BaseControl, index: number) => boolean): Xrm.BaseControl[];
    }
    interface Tabs extends Xrm.TabCollectionBase {
      get(name: "AdditionalITAHC_Tab"): Xrm.PageTab<Tabs.AdditionalITAHC_Tab>;
      get(name: "Charity_Tab"): Xrm.PageTab<Tabs.Charity_Tab>;
      get(name: "Destinations_Tab"): Xrm.PageTab<Tabs.Destinations_Tab>;
      get(name: "Importer_Tab"): Xrm.PageTab<Tabs.Importer_Tab>;
      get(name: "PlaceofOrigin_Tab"): Xrm.PageTab<Tabs.PlaceofOrigin_Tab>;
      get(name: "Queries_Tab"): Xrm.PageTab<Tabs.Queries_Tab>;
      get(name: "Summary"): Xrm.PageTab<Tabs.Summary>;
      get(name: "Transporter_Tab"): Xrm.PageTab<Tabs.Transporter_Tab>;
      get(name: "tab_7"): Xrm.PageTab<Tabs.tab_7>;
      get(name: "tab_8"): Xrm.PageTab<Tabs.tab_8>;
      get(name: string): undefined;
      get(): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
      get(index: number): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>;
      get(chooser: (item: Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>, index: number) => boolean): Xrm.PageTab<Xrm.Collection<Xrm.PageSection>>[];
    }
  }
  interface Information extends Xrm.PageBase<Information.Attributes,Information.Tabs,Information.Controls> {
    getAttribute(attributeName: "createdon"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_article15reimport"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "defraimp_article8monitored"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "defraimp_certificatecompliantfirsttime"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "defraimp_certificatenoncompliancereason"): Xrm.OptionSetAttribute<defraimp_importapplication_defraimp_certificatenoncompliancereason>;
    getAttribute(attributeName: "defraimp_certificatenoncompliancereasonother"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_certificateverified"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "defraimp_charityaddresscity"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_charityaddresscountry"): Xrm.LookupAttribute<"defra_country">;
    getAttribute(attributeName: "defraimp_charityaddressline1"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_charityaddressline2"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_charityaddressline3"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_charityaddresspostcode"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_charityname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_commoditynotes"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_commoditytypeid"): Xrm.LookupAttribute<"defraexp_commoditytype">;
    getAttribute(attributeName: "defraimp_completionsummary"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_consignmentconforming"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "defraimp_containernumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_countryoforiginid"): Xrm.LookupAttribute<"defra_country">;
    getAttribute(attributeName: "defraimp_dateiv66received"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_dateofconfirmationfromimporter"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_dateofconfirmationtobip"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_dateofemailtoimporter"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_dateofimport"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_destinationaddresscountryid"): Xrm.LookupAttribute<"defra_country">;
    getAttribute(attributeName: "defraimp_devolvedofficeid"): Xrm.LookupAttribute<"team">;
    getAttribute(attributeName: "defraimp_documentationnumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_documentnumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_generalcomments"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_healthcertificatenumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_importapplicationtype"): Xrm.OptionSetAttribute<defraimp_importapplication_defraimp_importapplicationtype>;
    getAttribute(attributeName: "defraimp_importeraddress1"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_importeraddress2"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_importeraddress3"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_importeraddresscity"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_importeraddresscountryid"): Xrm.LookupAttribute<"defra_country">;
    getAttribute(attributeName: "defraimp_importeraddresspostcode"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_importercontactname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_importeremail"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_importerorganisation"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_importertelephone"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_importingfromcharity"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "defraimp_importrisklevelid"): Xrm.LookupAttribute<"defraimp_importrisklevel">;
    getAttribute(attributeName: "defraimp_importrisklevelstatus"): Xrm.OptionSetAttribute<defraimp_importapplication_defraimp_importrisklevelstatus>;
    getAttribute(attributeName: "defraimp_inspectiondeclinedreason"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_inspectionoutcome"): Xrm.OptionSetAttribute<defraimp_importapplication_defraimp_inspectionoutcome>;
    getAttribute(attributeName: "defraimp_inspectionrequested"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "defraimp_inspectionrequired"): Xrm.OptionSetAttribute<defraimp_importapplication_defraimp_inspectionrequired>;
    getAttribute(attributeName: "defraimp_inspectionrequiredreason"): Xrm.OptionSetAttribute<defraimp_importapplication_defraimp_inspectionrequiredreason>;
    getAttribute(attributeName: "defraimp_iv65responseduedate"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_iv65responsereceiveddate"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_iv65sent"): Xrm.Attribute<any>;
    getAttribute(attributeName: "defraimp_iv65sentdate"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_iv66receivedinrequiredtimescale"): Xrm.Attribute<any>;
    getAttribute(attributeName: "defraimp_localreferencenumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_manualpostimportcheckdecision"): Xrm.OptionSetAttribute<defraimp_importapplication_defraimp_manualpostimportcheckdecision>;
    getAttribute(attributeName: "defraimp_meansoftransport"): Xrm.OptionSetAttribute<defraimp_meansoftransport>;
    getAttribute(attributeName: "defraimp_movedtocompletiondate"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_movetocompletion"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "defraimp_name"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_notifiedtobipwithin15days"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "defraimp_permanentdestinationaddresscity"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_permanentdestinationaddresscounid"): Xrm.LookupAttribute<"defra_country">;
    getAttribute(attributeName: "defraimp_permanentdestinationaddressline1"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_permanentdestinationaddressline2"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_permanentdestinationaddressline3"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_permanentdestinationaddresspostcode"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_permanentdestinationcontactname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_permanentdestinationemail"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_permanentdestinationorganisation"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_permanentdestinationtelephone"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationaddresscity"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationaddressline1"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationaddressline2"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationaddressline3"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationaddresspostcode"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationcontactname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationemail"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationorganisation"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeofdestinationtelephone"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeoforiginaddresscity"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeoforiginaddressline1"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeoforiginaddressline2"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeoforiginaddressline3"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeoforiginaddresspostcode"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeoforigincontactname"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_placeoforigincountryid"): Xrm.LookupAttribute<"defra_country">;
    getAttribute(attributeName: "defraimp_placeoforiginid"): Xrm.LookupAttribute<"defraimp_placeoforigin">;
    getAttribute(attributeName: "defraimp_placeoforiginorganisation"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_pointofentry"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_primaryimporternotificationid"): Xrm.LookupAttribute<"defraimp_importernotification">;
    getAttribute(attributeName: "defraimp_primaryitahcid"): Xrm.LookupAttribute<"defraimp_itahc">;
    getAttribute(attributeName: "defraimp_purpose"): Xrm.OptionSetAttribute<defraimp_importapplication_defraimp_purpose>;
    getAttribute(attributeName: "defraimp_quantity"): Xrm.NumberAttribute;
    getAttribute(attributeName: "defraimp_regionareaallocatedtoid"): Xrm.LookupAttribute<"defraimp_apharegion">;
    getAttribute(attributeName: "defraimp_resettrustleveltobronze"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "defraimp_risklevelverified"): Xrm.OptionSetAttribute<boolean>;
    getAttribute(attributeName: "defraimp_sealnumber"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_transporteraddresscity"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_transporteraddresscountryid"): Xrm.LookupAttribute<"defra_country">;
    getAttribute(attributeName: "defraimp_transporteraddressline1"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_transporteraddressline2"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_transporteraddressline3"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_transporteraddresspostcode"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_transporteremail"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_transportername"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_transportertelephone"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_unit"): Xrm.Attribute<string>;
    getAttribute(attributeName: "defraimp_warbleflytreatmentdeclarationreceiveddate"): Xrm.DateAttribute;
    getAttribute(attributeName: "defraimp_warbleflytreatmentdeclarationrequired"): Xrm.Attribute<any>;
    getAttribute(attributeName: "ownerid"): Xrm.LookupAttribute<"systemuser" | "team">;
    getAttribute(attributeName: "statuscode"): Xrm.OptionSetAttribute<defraimp_importapplication_statuscode>;
    getAttribute(attributeName: string): undefined;
    getControl(controlName: "AdditionalITAHC_SubGrid"): Xrm.SubGridControl<"defraimp_itahc">;
    getControl(controlName: "CountriesofTransit"): Xrm.SubGridControl<"defra_country">;
    getControl(controlName: "RelatedInspections"): Xrm.SubGridControl<"defraimp_importinspection">;
    getControl(controlName: "RelatedQueries"): Xrm.BaseControl;
    getControl(controlName: "Subgrid_WatchFlags"): Xrm.SubGridControl<"defraimp_watchflag">;
    getControl(controlName: "WebResource_FilesAndAttachments"): Xrm.WebResourceControl;
    getControl(controlName: "WebResource_UploadFiles"): Xrm.WebResourceControl;
    getControl(controlName: "defraimp_article15reimport"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "defraimp_article8monitored"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "defraimp_charityaddresscity"): Xrm.StringControl;
    getControl(controlName: "defraimp_charityaddresscountry"): Xrm.LookupControl<"defra_country">;
    getControl(controlName: "defraimp_charityaddressline1"): Xrm.StringControl;
    getControl(controlName: "defraimp_charityaddressline2"): Xrm.StringControl;
    getControl(controlName: "defraimp_charityaddressline3"): Xrm.StringControl;
    getControl(controlName: "defraimp_charityaddresspostcode"): Xrm.StringControl;
    getControl(controlName: "defraimp_charityname"): Xrm.StringControl;
    getControl(controlName: "defraimp_commoditynotes"): Xrm.StringControl;
    getControl(controlName: "defraimp_commoditytypeid"): Xrm.LookupControl<"defraexp_commoditytype">;
    getControl(controlName: "defraimp_consignmentconforming"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "defraimp_containernumber"): Xrm.StringControl;
    getControl(controlName: "defraimp_countryoforiginid"): Xrm.LookupControl<"defra_country">;
    getControl(controlName: "defraimp_dateiv66received"): Xrm.DateControl;
    getControl(controlName: "defraimp_dateofconfirmationfromimporter"): Xrm.DateControl;
    getControl(controlName: "defraimp_dateofconfirmationtobip"): Xrm.DateControl;
    getControl(controlName: "defraimp_dateofemailtoimporter"): Xrm.DateControl;
    getControl(controlName: "defraimp_dateofimport"): Xrm.DateControl;
    getControl(controlName: "defraimp_destinationaddresscountryid"): Xrm.LookupControl<"defra_country">;
    getControl(controlName: "defraimp_devolvedofficeid"): Xrm.LookupControl<"team">;
    getControl(controlName: "defraimp_documentationnumber"): Xrm.StringControl;
    getControl(controlName: "defraimp_documentnumber"): Xrm.StringControl;
    getControl(controlName: "defraimp_generalcomments"): Xrm.StringControl;
    getControl(controlName: "defraimp_importapplicationtype"): Xrm.OptionSetControl<defraimp_importapplication_defraimp_importapplicationtype>;
    getControl(controlName: "defraimp_importeraddress1"): Xrm.StringControl;
    getControl(controlName: "defraimp_importeraddress2"): Xrm.StringControl;
    getControl(controlName: "defraimp_importeraddress3"): Xrm.StringControl;
    getControl(controlName: "defraimp_importeraddresscity"): Xrm.StringControl;
    getControl(controlName: "defraimp_importeraddresscountryid"): Xrm.LookupControl<"defra_country">;
    getControl(controlName: "defraimp_importeraddresspostcode"): Xrm.StringControl;
    getControl(controlName: "defraimp_importercontactname"): Xrm.StringControl;
    getControl(controlName: "defraimp_importeremail"): Xrm.StringControl;
    getControl(controlName: "defraimp_importerorganisation"): Xrm.StringControl;
    getControl(controlName: "defraimp_importertelephone"): Xrm.StringControl;
    getControl(controlName: "defraimp_importingfromcharity"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "defraimp_importrisklevelid"): Xrm.LookupControl<"defraimp_importrisklevel">;
    getControl(controlName: "defraimp_importrisklevelstatus"): Xrm.OptionSetControl<defraimp_importapplication_defraimp_importrisklevelstatus>;
    getControl(controlName: "defraimp_inspectiondeclinedreason"): Xrm.StringControl;
    getControl(controlName: "defraimp_inspectionoutcome"): Xrm.OptionSetControl<defraimp_importapplication_defraimp_inspectionoutcome>;
    getControl(controlName: "defraimp_inspectionrequired"): Xrm.OptionSetControl<defraimp_importapplication_defraimp_inspectionrequired>;
    getControl(controlName: "defraimp_inspectionrequiredreason"): Xrm.OptionSetControl<defraimp_importapplication_defraimp_inspectionrequiredreason>;
    getControl(controlName: "defraimp_iv65responseduedate"): Xrm.DateControl;
    getControl(controlName: "defraimp_iv65responsereceiveddate"): Xrm.DateControl;
    getControl(controlName: "defraimp_iv65sent"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "defraimp_iv65sentdate"): Xrm.DateControl;
    getControl(controlName: "defraimp_iv66receivedinrequiredtimescale"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "defraimp_localreferencenumber"): Xrm.StringControl;
    getControl(controlName: "defraimp_localreferencenumber1"): Xrm.StringControl;
    getControl(controlName: "defraimp_manualpostimportcheckdecision"): Xrm.OptionSetControl<defraimp_importapplication_defraimp_manualpostimportcheckdecision>;
    getControl(controlName: "defraimp_meansoftransport"): Xrm.OptionSetControl<defraimp_meansoftransport>;
    getControl(controlName: "defraimp_movedtocompletiondate"): Xrm.DateControl;
    getControl(controlName: "defraimp_movetocompletion"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "defraimp_name"): Xrm.StringControl;
    getControl(controlName: "defraimp_notifiedtobipwithin15days"): Xrm.OptionSetControl<boolean>;
    getControl(controlName: "defraimp_permanentdestinationaddresscity"): Xrm.StringControl;
    getControl(controlName: "defraimp_permanentdestinationaddresscounid"): Xrm.LookupControl<"defra_country">;
    getControl(controlName: "defraimp_permanentdestinationaddressline1"): Xrm.StringControl;
    getControl(controlName: "defraimp_permanentdestinationaddressline2"): Xrm.StringControl;
    getControl(controlName: "defraimp_permanentdestinationaddressline3"): Xrm.StringControl;
    getControl(controlName: "defraimp_permanentdestinationaddresspostcode"): Xrm.StringControl;
    getControl(controlName: "defraimp_permanentdestinationcontactname"): Xrm.StringControl;
    getControl(controlName: "defraimp_permanentdestinationemail"): Xrm.StringControl;
    getControl(controlName: "defraimp_permanentdestinationorganisation"): Xrm.StringControl;
    getControl(controlName: "defraimp_permanentdestinationtelephone"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationaddresscity"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationaddressline1"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationaddressline2"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationaddressline3"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationaddresspostcode"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationcontactname"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationemail"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationorganisation"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeofdestinationtelephone"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeoforiginaddresscity"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeoforiginaddressline1"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeoforiginaddressline2"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeoforiginaddressline3"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeoforiginaddresspostcode"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeoforigincontactname"): Xrm.StringControl;
    getControl(controlName: "defraimp_placeoforigincountryid"): Xrm.LookupControl<"defra_country">;
    getControl(controlName: "defraimp_placeoforiginid"): Xrm.LookupControl<"defraimp_placeoforigin">;
    getControl(controlName: "defraimp_placeoforiginorganisation"): Xrm.StringControl;
    getControl(controlName: "defraimp_pointofentry"): Xrm.StringControl;
    getControl(controlName: "defraimp_primaryimporternotificationid"): Xrm.LookupControl<"defraimp_importernotification">;
    getControl(controlName: "defraimp_primaryitahcid"): Xrm.LookupControl<"defraimp_itahc">;
    getControl(controlName: "defraimp_purpose"): Xrm.OptionSetControl<defraimp_importapplication_defraimp_purpose>;
    getControl(controlName: "defraimp_quantity"): Xrm.NumberControl;
    getControl(controlName: "defraimp_regionareaallocatedtoid"): Xrm.LookupControl<"defraimp_apharegion">;
    getControl(controlName: "defraimp_sealnumber"): Xrm.StringControl;
    getControl(controlName: "defraimp_transporteraddresscity"): Xrm.StringControl;
    getControl(controlName: "defraimp_transporteraddresscountryid"): Xrm.LookupControl<"defra_country">;
    getControl(controlName: "defraimp_transporteraddressline1"): Xrm.StringControl;
    getControl(controlName: "defraimp_transporteraddressline2"): Xrm.StringControl;
    getControl(controlName: "defraimp_transporteraddressline3"): Xrm.StringControl;
    getControl(controlName: "defraimp_transporteraddresspostcode"): Xrm.StringControl;
    getControl(controlName: "defraimp_transporteremail"): Xrm.StringControl;
    getControl(controlName: "defraimp_transportername"): Xrm.StringControl;
    getControl(controlName: "defraimp_transportertelephone"): Xrm.StringControl;
    getControl(controlName: "defraimp_unit"): Xrm.StringControl;
    getControl(controlName: "defraimp_warbleflytreatmentdeclarationreceiveddate"): Xrm.DateControl;
    getControl(controlName: "defraimp_warbleflytreatmentdeclarationrequired"): Xrm.Control<Xrm.Attribute<any>>;
    getControl(controlName: "footer_createdon"): Xrm.DateControl;
    getControl(controlName: "footer_defraimp_healthcertificatenumber"): Xrm.StringControl;
    getControl(controlName: "footer_ownerid"): Xrm.LookupControl<"systemuser" | "team">;
    getControl(controlName: "header_ownerid"): Xrm.LookupControl<"systemuser" | "team">;
    getControl(controlName: "header_process_defraimp_certificatecompliantfirsttime"): Xrm.OptionSetControl<boolean> | null;
    getControl(controlName: "header_process_defraimp_certificatenoncompliancereason"): Xrm.OptionSetControl<defraimp_importapplication_defraimp_certificatenoncompliancereason> | null;
    getControl(controlName: "header_process_defraimp_certificatenoncompliancereasonother"): Xrm.StringControl | null;
    getControl(controlName: "header_process_defraimp_certificateverified"): Xrm.OptionSetControl<boolean> | null;
    getControl(controlName: "header_process_defraimp_commoditytypeid"): Xrm.LookupControl<"defraexp_commoditytype"> | null;
    getControl(controlName: "header_process_defraimp_completionsummary"): Xrm.StringControl | null;
    getControl(controlName: "header_process_defraimp_completionsummary1"): Xrm.StringControl | null;
    getControl(controlName: "header_process_defraimp_countryoforiginid"): Xrm.LookupControl<"defra_country"> | null;
    getControl(controlName: "header_process_defraimp_importrisklevelid"): Xrm.LookupControl<"defraimp_importrisklevel"> | null;
    getControl(controlName: "header_process_defraimp_inspectiondeclinedreason"): Xrm.StringControl | null;
    getControl(controlName: "header_process_defraimp_inspectionrequested"): Xrm.OptionSetControl<boolean> | null;
    getControl(controlName: "header_process_defraimp_inspectionrequired"): Xrm.OptionSetControl<defraimp_importapplication_defraimp_inspectionrequired> | null;
    getControl(controlName: "header_process_defraimp_manualpostimportcheckdecision"): Xrm.OptionSetControl<defraimp_importapplication_defraimp_manualpostimportcheckdecision> | null;
    getControl(controlName: "header_process_defraimp_movedtocompletiondate"): Xrm.DateControl | null;
    getControl(controlName: "header_process_defraimp_movedtocompletiondate1"): Xrm.DateControl | null;
    getControl(controlName: "header_process_defraimp_movetocompletion"): Xrm.OptionSetControl<boolean> | null;
    getControl(controlName: "header_process_defraimp_movetocompletion1"): Xrm.OptionSetControl<boolean> | null;
    getControl(controlName: "header_process_defraimp_placeoforiginid"): Xrm.LookupControl<"defraimp_placeoforigin"> | null;
    getControl(controlName: "header_process_defraimp_primaryitahcid"): Xrm.LookupControl<"defraimp_itahc"> | null;
    getControl(controlName: "header_process_defraimp_regionareaallocatedtoid"): Xrm.LookupControl<"defraimp_apharegion"> | null;
    getControl(controlName: "header_process_defraimp_resettrustleveltobronze"): Xrm.OptionSetControl<boolean> | null;
    getControl(controlName: "header_process_defraimp_risklevelverified"): Xrm.OptionSetControl<boolean> | null;
    getControl(controlName: "header_process_ownerid"): Xrm.LookupControl<"systemuser" | "team"> | null;
    getControl(controlName: "header_statuscode"): Xrm.OptionSetControl<defraimp_importapplication_statuscode>;
    getControl(controlName: "notescontrol"): Xrm.BaseControl;
    getControl(controlName: "ownerid"): Xrm.LookupControl<"systemuser" | "team">;
    getControl(controlName: string): undefined;
  }
}
